### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by liuchuancong** [FirebaseExtended/flutterfire#113]
```
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at io.flutter.plugins.firebaseanalytics.FirebaseAnalyticsPlugin.createBundleFromMap(FirebaseAnalyticsPlugin.java:155)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at io.flutter.plugins.firebaseanalytics.FirebaseAnalyticsPlugin.handleLogEvent(FirebaseAnalyticsPlugin.java:75)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at io.flutter.plugins.firebaseanalytics.FirebaseAnalyticsPlugin.onMethodCall(FirebaseAnalyticsPlugin.java:39)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/MethodChannel#plugins.flutter.io/firebase_analytics(16703): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
```
  firebase_analytics: ^4.0.2
```

**Comment by liuchuancong** [comment]
```
 firebase_analytics: ^5.0.1
```
