### ISSUE TITLE
cloud_functions plugin - java.lang.NullPointerException during call()

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1192]
On iOS, call to a Cloud Function works. On Android, I get the following (same exact Dart function calling the same function):

```
E/MethodChannel#cloud_functions(13636): Failed to handle method call
E/MethodChannel#cloud_functions(13636): java.lang.NullPointerException: null reference
E/MethodChannel#cloud_functions(13636): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source)
E/MethodChannel#cloud_functions(13636): 	at com.google.firebase.functions.FirebaseFunctions.<init>(com.google.firebase:firebase-functions@@17.0.0:81)
E/MethodChannel#cloud_functions(13636): 	at com.google.firebase.functions.FunctionsMultiResourceComponent.get(com.google.firebase:firebase-functions@@17.0.0:46)
E/MethodChannel#cloud_functions(13636): 	at com.google.firebase.functions.FirebaseFunctions.getInstance(com.google.firebase:firebase-functions@@17.0.0:137)
E/MethodChannel#cloud_functions(13636): 	at com.google.firebase.functions.FirebaseFunctions.getInstance(com.google.firebase:firebase-functions@@17.0.0:146)
E/MethodChannel#cloud_functions(13636): 	at io.flutter.plugins.firebase.cloudfunctions.cloudfunctions.CloudFunctionsPlugin.onMethodCall(CloudFunctionsPlugin.java:45)
E/MethodChannel#cloud_functions(13636): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#cloud_functions(13636): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
E/MethodChannel#cloud_functions(13636): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
E/MethodChannel#cloud_functions(13636): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#cloud_functions(13636): 	at android.os.MessageQueue.next(MessageQueue.java:359)
E/MethodChannel#cloud_functions(13636): 	at android.os.Looper.loop(Looper.java:138)
E/MethodChannel#cloud_functions(13636): 	at android.app.ActivityThread.main(ActivityThread.java:6531)
E/MethodChannel#cloud_functions(13636): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#cloud_functions(13636): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
E/MethodChannel#cloud_functions(13636): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
E/flutter (13636): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: Unable to call function productsUpdateStocksNumber
```

Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.13.6 17G7024, locale en-MG)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by kroikie** [comment]
@eliezedeck

The issue at https://github.com/flutter/flutter/issues/34011 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Ehesp** [comment]
Hi @eliezedeck please could you try on the latest version of Flutter and the plugin. This issue has been stale for a long time, please let me know if it's still an issue and I can reopen.

**Comment by eliezedeck** [comment]
Hi @Ehesp, I have opted to not use this feature at all because of the difference of behaviors. I will let you know if I come across a project that will make use of this again and I still have the same issue. Thanks.
