### ISSUE TITLE
Unhandled Exception: PlatformException(error, PluginRegistrantCallback is not set., null)

### ISSUE THREAD

**Issue by boyfox** [FirebaseExtended/flutterfire#1284]
Code in main dart initState:

```
_firebaseMessaging.configure(
	onMessage: (Map<String, dynamic> message) async {
		print('Firebase on message: $message');
	},
	onResume: (Map<String, dynamic> message) async {
		print('Firebase on resume: $message');
	},
	onLaunch: (Map<String, dynamic> message) async {
		print('Firebase on launch: $message');
	},
	onBackgroundMessage: fcmBackgroundMessageHandler
);
```
Here background message handler:

```
static Future<dynamic> fcmBackgroundMessageHandler(Map<String, dynamic> message) {
	print('Firebase on onBackgroundMessage: $message');

	if (message.containsKey('data')) {
		// Handle data message
		final dynamic data = message['data'];
	}

	if (message.containsKey('notification')) {
		// Handle notification message
		final dynamic notification = message['notification'];
	}

	return null;
	// Or do other work.
}
```

Here error:
```
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): java.lang.RuntimeException: PluginRegistrantCallback is not set.
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:157)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onMethodCall(FirebaseMessagingPlugin.java:134)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#plugins.flutter.io/firebase_messaging(30941): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
D/eglCodecCommon(30941): setVertexArrayObject: set vao to 0 (0) 1 0
D/EGL_emulation(30941): eglMakeCurrent: 0xdf71a660: ver 3 0 (tinfo 0xdf70f8a0)
E/flutter (30941): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, PluginRegistrantCallback is not set., null)
E/flutter (30941): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (30941): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (30941): <asynchronous suspension>
E/flutter (30941): #2      FirebaseMessaging.configure (package:firebase_messaging/firebase_messaging.dart:118:16)
E/flutter (30941): #3      JoylaState.initState (package:joyla/main.dart:141:22)
E/flutter (30941): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
E/flutter (30941): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
E/flutter (30941): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
E/flutter (30941): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
E/flutter (30941): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:998:16)
E/flutter (30941): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:969:5)
E/flutter (30941): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:17)
E/flutter (30941): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
E/flutter (30941): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:914:13)
E/flutter (30941): #13     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:795:7)
E/flutter (30941): #14     runApp (package:flutter/src/widgets/binding.dart:845:7)
E/flutter (30941): #15     main (package:joyla/main.dart:21:2)
E/flutter (30941): #16     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
E/flutter (30941): #17     main (package:joyla/main.dart:20:18)
E/flutter (30941): #18     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
E/flutter (30941): #19     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (30941): #20     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (30941): #21     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (30941): #22     runZoned (dart:async/zone.dart:1500:12)
E/flutter (30941): #23     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
E/flutter (30941): #24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter (30941): #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by BondarenkoStas** [comment]
Hi @boyfox, I'm going to close this issue in favour to https://github.com/FirebaseExtended/flutterfire/issues/248, please follow it there and upvote.

**Comment by marceloiavenissi** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/248
I believe I solved the problem.
