### ISSUE TITLE
[firebase_admob] RewardedVideoAdEvent.failedToLoad didn't work at all

### ISSUE THREAD

**Issue by rdcoder33** [FirebaseExtended/flutterfire#1300]
**Describe the bug**
So, what I want is to do some actions if a rewarded video add fails to load which happens quite often.

Minimum code to reproduce error:

```
 onPressed: () {
            RewardedVideoAd.instance.load(
                adUnitId: RewardedVideoAd.testAdUnitId,
                targetingInfo: targetingInfo);
            RewardedVideoAd.instance.show();
            RewardedVideoAd.instance.listener = (RewardedVideoAdEvent event,
                {String rewardType, int rewardAmount}) {
              if (event == RewardedVideoAdEvent.rewarded) {
                todoActionModel.deleteTodoList(todoActionModel.listType);
                todoActionModel.initTodo();
              } else if (event == RewardedVideoAdEvent.failedToLoad) {
                print('*************************************');
                todoActionModel.deleteTodoList(todoActionModel.listType);
                todoActionModel.initTodo();
                loadInterAd();
              }
            };
          },
```

But nothing happens. All I get is unhandled PlatformException in debug console, which I can't catch using try and catch block. 

```
E/flutter (11105): <asynchronous suspension>
E/flutter (11105): #3      RewardedVideoAd.show 
package:firebase_admob/firebase_admob.dart:397
E/flutter (11105): #4      TodoState.todoBottomActions.<anonymous closure> 
package:mentor101/…/ui/todos.dart:235
E/flutter (11105): #5      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:635
E/flutter (11105): #6      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:711
E/flutter (11105): #7      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter (11105): #8      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:365
E/flutter (11105): #9      TapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:312
E/flutter (11105): #10     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter (11105): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
E/flutter (11105): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (11105): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter (11105): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter (11105): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (11105): #16     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter (11105): #17     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (11105): #18     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter (11105): #19     _invoke1  (dart:ui/hooks.dart:250:10)
E/flutter (11105): #20     _dispatchPointerDataPacket  (dart:ui/hooks.dart:159:5)
E/flutter (11105): 
```

Is there any working way by which I can write some code when add fails to load?

**Comment by Holofox** [comment]
You need to wait for the ad to load in order to show it. The implementation should be something like this:

1. Preload the advertisement at the first initialization.
2. Keep track of whether the ad has been downloaded. If it loaded, then it is available for display.
3. After closing the advertisement, initialize the loading of the next advertisement.

Note: if the advertisement has not loaded, and the user has initiated the display, wait for the advertisement to load and show it to the user (use the state of the listener to understand when you can show the advertisement).

```dart
_rewardedVideoAd.listener =
    (RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
  switch (event) {
    case RewardedVideoAdEvent.loaded:
      _rewardedAdLoaded = true;
      _rewardedAdLoading = false;
      if (_rewardedAdCanShowed)
        _showRewardedAd(_rewardedType);
      break;
    case RewardedVideoAdEvent.failedToLoad:
      _rewardedAdLoaded = false;
      _rewardedAdLoading = false;
      break;
    case RewardedVideoAdEvent.closed:
      _rewardedAdLoaded = false;
      _loadRewardedAd();
      break;
    case RewardedVideoAdEvent.rewarded:
      _rewardedEvent();
      break;
    default:
      break;
  }
};
```

**Comment by iapicca** [comment]
Hi @rdcoder33 
does the proposed [solution ](https://github.com/FirebaseExtended/flutterfire/issues/1300#issuecomment-545422948) (thank you @Holofox ) fix the issue?

**Comment by rdcoder33** [comment]
> Hi @rdcoder33
> does the proposed [solution ](https://github.com/FirebaseExtended/flutterfire/issues/1300#issuecomment-545422948) (thank you @Holofox ) fix the issue?

Extremely sorry for the late reply and Yup, checking if the ad is loaded before showing the add removes the error. Thanks :)
