### ISSUE TITLE
[FirebaseAuth]: Unhandled Exception: type 'List<Object?>' is not a subtype of type 'PigeonUserInfo' in type cast

### ISSUE THREAD

**Issue by EgHubs** [FirebaseExtended/flutterfire#13077]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Which plugins are affected?

Auth

### Which platforms are affected?

iOS

### Description

i get this error when i click on home to got to the simulator home and put the app in the background
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'List<Object?>' is not a subtype of type 'PigeonUserInfo' in type cast
#0      PigeonUserDetails.decode (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:401:28)
#1      _FirebaseAuthUserHostApiCodec.readValueOfType (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:1573:34)
#2      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#3      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:522:23)
#4      _FirebaseAuthUserHostApiCodec.readValueOfType (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:1581:22)
#5      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#6      StandardMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:341:28)
#7      BasicMessageChannel.send (package:flutter/src/services/platform_channel.<…>
```

these

### Reproducing the issue

on the latest ios version in the simulator click the home button while running the app

### Firebase Core version

3.2.0

### Flutter Version

Channel stable, 3.22.2

### Relevant Log Output

```shell
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'List<Object?>' is not a subtype of type 'PigeonUserInfo' in type cast
#0      PigeonUserDetails.decode (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:401:28)
#1      _FirebaseAuthUserHostApiCodec.readValueOfType (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:1573:34)
#2      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#3      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:522:23)
#4      _FirebaseAuthUserHostApiCodec.readValueOfType (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:1581:22)
#5      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
#6      StandardMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:341:28)
#7      BasicMessageChannel.send (package:flutter/src/services/platform_channel.<…>
```

### Flutter dependencies

dependencies:
  firebase_messaging: ^15.0.3
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_database: ^11.0.3
  firebase_storage: ^12.1.1
  cloud_functions: ^5.0.3
  firebase_analytics: ^11.2.0

**Comment by Lyokone** [comment]
Hello @EgHubs I cannot reproduce this issue on my end, can you provide a full sample app?

**Comment by muqeetkhan01** [comment]
Hi @EgHubs is there any update on this issue?

**Comment by Muhammad-Abubakr** [comment]
Can you try running `flutter pub upgrade firebase_auth` and re-run the application. It solved the issue on my end. 

Checking what `upgrade` does reveals that it updates the dependencies of the specified package.

**Comment by myproblemchild** [comment]
I'm having the same issue, no suggestions from this thread or other sources worked so far.

```
try {
      final googleAccount = await _googleSignIn?.signIn();
      final googleAuth = await googleAccount?.authentication;
      final googleCredential = GoogleAuthProvider.credential(
        accessToken: googleAuth?.accessToken,
        idToken: googleAuth?.idToken,
      );
      await FirebaseAuth.instance.signInWithCredential(googleCredential);
    } catch (error, st) {
      //
    }
```
And I see it's printing
```
I/flutter (31925): error caught: type 'List<Object?>' is not a subtype of type 'PigeonUserDetails?' in type cast #0      PigeonUserCredential.decode (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:432:23)
I/flutter (31925): #1      _FirebaseAuthHostApiCodec.readValueOfType (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:830:37)
I/flutter (31925): #2      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
I/flutter (31925): #3      StandardMessageCodec.readValueOfType (package:flutter/src/services/message_codecs.dart:522:23)
I/flutter (31925): #4      _FirebaseAuthHostApiCodec.readValueOfType (package:firebase_auth_platform_interface/src/pigeon/messages.pigeon.dart:840:22)
I/flutter (31925): #5      StandardMessageCodec.readValue (package:flutter/src/services/message_codecs.dart:477:12)
I/flutter (31925): #6      StandardMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:341:28)
I/flutter (31925): #7      BasicMessageChannel.send (package:flutter/src/services/platform_channel.dart:218:18)
```

Versions:
```
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  firebase_crashlytics: ^4.0.4
  firebase_analytics: ^11.2.1
```
