### ISSUE TITLE
[cloud_firestore] PlatformException (PlatformException(error, length=0; index=-1, null)) on getDocuments

### ISSUE THREAD

**Issue by DSenanayake** [FirebaseExtended/flutterfire#1374]
I'm keep getting this exception after I call startAtDocument(). I cannot catch it from catchError either.

**Flutter Doctor**
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale en-LK)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 11.2)
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

_cloud_firestore: ^0.12.9+6_

![image](https://user-images.githubusercontent.com/8406132/68265492-36918680-0072-11ea-9586-22fda6e81ed3.png)

**Comment by iapicca** [comment]
Hi @DSenanayake 
can you please provide your `flutter run --verbose`/`flutter build --verbose`,
also to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by DSenanayake** [comment]
Hi @iapicca 
Thank you for your response. 
Here is the result of  **flutter run --verbose**

```
[+31212 ms] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): Failed to handle method call
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at java.util.ArrayList.get(ArrayList.java:413)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getQuery(CloudFirestorePlugin.java:262)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:694)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at android.os.MessageQueue.next(MessageQueue.java:323)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at android.os.Looper.loop(Looper.java:136)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[        ] E/MethodChannel#plugins.flutter.io/cloud_firestore(20300): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[  +12 ms] I/flutter (20300): 4.0
[  +52 ms] I/flutter (20300): PlatformException(error, length=0; index=-1, null)
```

And here is my api.dart file for firestore functions. 
```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:async';

class Api {
  final Firestore _db = Firestore.instance;
  final String path;
  CollectionReference ref;

  Api(this.path) {
    ref = _db.collection(path);
  }

  Future<DocumentSnapshot> getDocumentById(String id) {
    return ref.document(id).get();
  }

  Future<QuerySnapshot> getPriceList(String mobileId) {
    return ref
        .where("mobile_id", isEqualTo: mobileId)
        .orderBy('price')
        .getDocuments();
  }

  void getCustomerReviews(String mobileId, int pageLimit,
      {last, onComplete}) {
    Query query = ref
        .where("mobile_id", isEqualTo: mobileId)
        .where("visible", isEqualTo: true)
        .limit(pageLimit);

    if (last != null) {
      query = query.startAtDocument(last);
    }

    query.getDocuments().then(onComplete).catchError((error) {
      print(error);
      onComplete(null);
    });
  }
}

```
