### ISSUE TITLE
[firebase_storage] writeToFile not correctly invoking exception

### ISSUE THREAD

**Issue by MichaelM97** [FirebaseExtended/flutterfire#1418]
When downloading a file from firebase storage, if the file does not exist then when `writeToFile()` is called then the `catch` in the below example is not invoked.

However, the `catch` *is* correctly invoked when calling other functions, like `getMetadata()`.

Code for writeToFile():
```dart
    final directory = await getApplicationDocumentsDirectory();
    final File file = File(directory.path);
    final StorageReference ref = _firebaseStorage.ref().child("Does_not_exist");

    try {
      final StorageFileDownloadTask downloadTask = ref.writeToFile(file);
      await downloadTask.future;
    } catch (error) {
      print("Error! - " + error.toString());
    }
```
Exception that is apparently 'Unhandled':
```
23:02:59.472 3 info flutter.tools [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(Error -13021, FIRStorageErrorDomain, User does not have permission to access gs://test-app.appspot.com/Does_not_exist.)
23:02:59.472 4 info flutter.tools #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
23:02:59.472 5 info flutter.tools #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
23:02:59.472 6 info flutter.tools <asynchronous suspension>
23:02:59.472 7 info flutter.tools #2      StorageFileDownloadTask._start (package:firebase_storage/src/firebase_storage.dart:137:62)
23:02:59.472 8 info flutter.tools <asynchronous suspension>
23:02:59.472 9 info flutter.tools #3      StorageReference.writeToFile (package:firebase_storage/src/storage_reference.dart:134:10)
```

Code for getMetaData():
```dart
    final StorageReference ref = _firebaseStorage.ref().child("Does_not_exist");

    try {
      await ref.getMetadata();
    } catch (error) {
      print("Error! - " + error.toString());
    }
```

Exception that is correctly handled:
```
23:07:55.205 13 info flutter.tools  Error! - PlatformException(Error -13021, FIRStorageErrorDomain, User does not have permission to access gs://test-app.appspot.com/Does_not_exist.)
```

**Comment by iapicca** [comment]
Hi @MichaelM97 
could you please provide your updated  `flutter doctor -v` ?
Thank you

**Comment by MichaelM97** [comment]
> Hi @MichaelM97
> could you please provide your updated `flutter doctor -v` ?
> Thank you

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.9.1+hotfix.6 at /Users/michaelmccormick/development/flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/michaelmccormick/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by tolo** [comment]
If I understand it correctly, it seems the underlying issue is that the exception is currently "consumed" and hidden by StorageFileDownloadTask (since the future returned by that method isn't used). The `_start` method of that class needs to include a try-catch around the `FirebaseStorage.channel.invokeMethod` call, and pass the error to the `Completer` instance for things to work correctly.
  https://github.com/FirebaseExtended/flutterfire/blob/dafb4ecc7ecb106ea848a2186f8d645fa6984619/packages/firebase_storage/lib/src/firebase_storage.dart#L136

Like so: 
```dart
try {
  final int totalByteCount = await FirebaseStorage.channel.invokeMethod<int>(...);
  _completer.complete(FileDownloadTaskSnapshot(totalByteCount: totalByteCount));
} catch (e) {
  _completer.completeError(e);
}
```

**Comment by iapicca** [comment]
Hi again @MichaelM97
did the proposed solution worked for you?
thank you @tolo

**Comment by tolo** [comment]
Just to be clear - this needs to be fixed in firebase_storage (StorageFileDownloadTask). I would have submitted a PR, but I haven't had the time. But perhaps I'll try to find time to do that.
