### ISSUE TITLE
[firebase_admob] Use AndroidView the bug that occurs when ad is in setstate.

### ISSUE THREAD

**Issue by a27919478** [FirebaseExtended/flutterfire#1441]
Using Android view causes native ads or banner ads to crash. When using setstate.
Due to the high probability of occurrence, please reply as soon as possible.
![image](https://user-images.githubusercontent.com/19726808/69037646-335baa80-0a23-11ea-93b8-e03ec37ec662.png)

Crash log:
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Display.getSize(android.graphics.Point)' on a null object reference
       at org.chromium.ui.display.DisplayAndroid.updateFromDisplay(DisplayAndroid.java:133)
       at org.chromium.ui.display.DisplayAndroidManager$DisplayListenerBackendImpl.onDisplayChanged(DisplayAndroidManager.java:169)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:540)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5988)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)`

My flutter version:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-HK)
 
[!] Android toolchain - develop for Android devices (Android SDK version
    29.0.0-rc1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

**Comment by iapicca** [comment]
Hi @a27919478 
could you please provide could post a minimal code sample to reproduce the problem
Thank you

**Comment by a27919478** [comment]
Because I can't reproduce the problem, but I suspect that this problem is related to the previous use of WebView by flutter.
It's a little bit like this:
https://github.com/flutter/flutter/issues/30420
