### ISSUE TITLE
[remote_config] error when Remote Config instance for the first time

### ISSUE THREAD

**Issue by jcsena** [FirebaseExtended/flutterfire#1461]
**Describe the bug**
```dart
   final  remoteConfig = await RemoteConfig.instance;
   await remoteConfig.fetch(expiration: const Duration(seconds: 3000));
   await remoteConfig.activateFetched();
```
It only happens when I compile for the first time, then it doesn't generate the error

```java
W/FirebaseRemoteConfig(28083): Could not update ABT experiments.
W/FirebaseRemoteConfig(28083): com.google.firebase.abt.AbtException: The Analytics SDK is not available. Please check that the Analytics SDK is included in your app dependencies.
W/FirebaseRemoteConfig(28083): 	at com.google.firebase.abt.FirebaseABTesting.throwAbtExceptionIfAnalyticsIsNull(com.google.firebase:firebase-abt@@19.0.0:293)
W/FirebaseRemoteConfig(28083): 	at com.google.firebase.abt.FirebaseABTesting.replaceAllExperiments(com.google.firebase:firebase-abt@@19.0.0:119)
W/FirebaseRemoteConfig(28083): 	at com.google.firebase.remoteconfig.FirebaseRemoteConfig.updateAbtWithActivatedExperiments(com.google.firebase:firebase-config@@19.0.3:725)
W/FirebaseRemoteConfig(28083): 	at com.google.firebase.remoteconfig.FirebaseRemoteConfig.processActivatePutTask(com.google.firebase:firebase-config@@19.0.3:663)
W/FirebaseRemoteConfig(28083): 	at com.google.firebase.remoteconfig.FirebaseRemoteConfig.access$lambda$0(Unknown Source:0)
W/FirebaseRemoteConfig(28083): 	at com.google.firebase.remoteconfig.FirebaseRemoteConfig$$Lambda$11.then(Unknown Source:2)
W/FirebaseRemoteConfig(28083): 	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
W/FirebaseRemoteConfig(28083): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/FirebaseRemoteConfig(28083): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/FirebaseRemoteConfig(28083): 	at java.lang.Thread.run(Thread.java:764)
```
**To Reproduce**
Error when Remote Config instance for the first time

version : 0.3.0

**Comment by iapicca** [comment]
Hi @jcsena 
could you please provide your updated  `flutter doctor -v` ?
Thank you

**Comment by jcsena** [comment]
Hi @iapicca 
The behavior is when I install the app for the first time and request some variable

``` dart
      final  remoteConfig = await RemoteConfig.instance;
      await remoteConfig.fetch(expiration: const Duration(seconds: 3000));
      await remoteConfig.activateFetched();

      final rt = remoteConfig.getBool('tournamentRoundTripPlayOffDefault');
      print('\r');
      print('\r');
      print('>>>>><<<<<<');
      print(rt);
      print('>>>>><<<<<<');
      print('\r');
      print('\r');
```
debugging 
```java
W/FirebaseRemoteConfig(21071): 	at com.google.firebase.remoteconfig.FirebaseRemoteConfig.updateAbtWithActivatedExperiments(com.google.firebase:firebase-config@@19.0.3:725)
W/FirebaseRemoteConfig(21071): 	at com.google.firebase.remoteconfig.FirebaseRemoteConfig.processActivatePutTask(com.google.firebase:firebase-config@@19.0.3:663)
W/FirebaseRemoteConfig(21071): 	at com.google.firebase.remoteconfig.FirebaseRemoteConfig.access$lambda$0(Unknown Source:0)
W/FirebaseRemoteConfig(21071): 	at com.google.firebase.remoteconfig.FirebaseRemoteConfig$$Lambda$11.then(Unknown Source:2)
W/FirebaseRemoteConfig(21071): 	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
W/FirebaseRemoteConfig(21071): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/FirebaseRemoteConfig(21071): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/FirebaseRemoteConfig(21071): 	at java.lang.Thread.run(Thread.java:764)
I/flutter (21071):
I/flutter (21071):
I/flutter (21071): >>>>><<<<<<
I/flutter (21071): false
I/flutter (21071): >>>>><<<<<<
I/flutter (21071):
I/flutter (21071):
W/FDL     (21071): FDL logging failed. Add a dependency for Firebase Analytics to your app to enable logging of Dynamic Link events.
I/flutter (21071): Transition { currentState: DynamicLinkInitial, event: ConfigDynamicLink, nextState: ConfigDynamicLinkLoading }
I/flutter (21071): Transition { currentState: PushNotificationState type: null,  isInit: false, event: ConfigureFCM, nextState: PushNotificationState type: null,  isInit: true }
I/flutter (21071): Transition { currentState: ConfigDynamicLinkLoading, event: ConfigDynamicLink, nextState: ConfigDynamicLinkSuccess }
```
flutter doctor -v

> [✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.15.1 19B88, locale en-PA)
>     • Flutter version 1.10.7 at /Users/juliosena/flutter
>     • Framework revision e70236e36c (7 weeks ago), 2019-10-02 09:32:30 -0700
>     • Engine revision 9e6314d348
>     • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at /Users/juliosena/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 28.0.3
>     • ANDROID_HOME = /Users/juliosena/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.2.1, Build version 11B500
>     • CocoaPods version 1.8.3
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] VS Code (version 1.40.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.6.0
> 
> [✓] Connected device (1 available)
>     • Redmi Note 7 • 11fc7316 • android-arm64 • Android 9 (API 28)
> 
> • No issues found!

**Comment by iapicca** [comment]
thank you @jcsena

**Comment by AdamBCo** [comment]
Any update on this problem?

**Comment by naguchennai** [comment]
no still not working i also same problem but firebase database working fine

**Comment by yourshinsuke** [comment]
Unhandled Exception: MissingPluginException(No implementation found for method RemoteConfig#instance on channel plugins.flutter.io/firebase_remote_config)

**Comment by allanwolski** [comment]
Having the same issue here.

<details>
  <summary>flutter doctor -v</summary>
  
```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [versão 10.0.19041.804], locale pt-BR)
    • Flutter version 1.22.6 at C:\Flutter
    • Framework revision 9b2d32b605 (5 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\allan\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\allan\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.1

[√] Connected device (1 available)
    • MI 8 (mobile) • 7a862928 • android-arm64 • Android 10 (API 29)

• No issues found!
```
</details>

**Comment by Salakar** [comment]
Given the age of this issue and that Remote Config has had a major rework since; I'm going to close this issue in favour of trying the latest release.
