### ISSUE TITLE
[firebase_auth] FirebaseAuth.sendSignInWithEmailLink() throws ERROR_INTERNAL_ERROR

### ISSUE THREAD

**Issue by HaoCherHong** [FirebaseExtended/flutterfire#1514]
**Describe the bug**

Calling FirebaseAuth.sendSignInWithEmailLink() causes platform exception:

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(ERROR_INTERNAL_ERROR, An internal error has occurred, print and inspect the error details for more information., null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      FirebaseAuth.sendSignInWithEmailLink (package:firebase_auth/src/firebase_auth.dart:160:19)
<asynchronous suspension>
#3      SessionRepository.sendSignInWithEmailLink (package:buki_flutter/repositories/session_repository.dart:35:32)
<asynchronous suspension>
#4      SessionBloc.sendSignInWithEmailLink (package:buki_flutter/blocs/session_bloc.dart:225:31)
#5      _EmailLoginPageState.build.<anonymous closure> (package:buki_flutter/pages/email_login_page.dart:25:59)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#7      _InkResponseState.build.<ano<…>

```
Running on: iOS 13.2 simulator
Package version: `firebase_auth: ^0.14.0+5`

**Comment by HaoCherHong** [comment]
flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G84, locale en-TW)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[!] Android Studio (version 3.4)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.40.1)
[✓] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @HaoCherHong 
I see that you are active in this [issue](https://github.com/FirebaseExtended/flutterfire/issues/124) ,
that appears to address your issue;
is there any difference that I'm missing between the 2 issues?
thank you

**Comment by HaoCherHong** [comment]
I thought #124 is talking about `signInWithEmailAndPassword()` not `sendSignInWithEmailLink()`, so I opened another one.

**Comment by iapicca** [comment]
Hi @HaoCherHong 
are you still experiencing the issue with the latest stable version of flutter 
and the latest version of firebase_auth?
thank you

**Comment by Salakar** [comment]
Consolidating under #1456 - we'll be looking at parsing native error messages & codes and bubbling these up to the Dart layer in a consistent cross-platform format.
