### ISSUE TITLE
[firebase_auth] Android application crashes on successful sign up

### ISSUE THREAD

**Issue by Hadii1** [FirebaseExtended/flutterfire#1576]
The user signing works and the email appears in the firebase console but the app crashes instantly with the following output: 

```bash
E/AndroidRuntime(32278): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/dev.vkras.auth_test-qLqcuUIdsTXTvhfFqMoEWg==/base.apk"],nativeLibraryDirectories=[/data/app/dev.vkras.auth_test-qLqcuUIdsTXTvhfFqMoEWg==/lib/x86, /data/app/dev.vkras.auth_test-qLqcuUIdsTXTvhfFqMoEWg==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
E/AndroidRuntime(32278): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
E/AndroidRuntime(32278): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(32278): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(32278): 	... 16 more
I/zygote  (32278): Do full code cache collection, code=122KB, data=80KB
I/zygote  (32278): After code cache collection, code=105KB, data=59KB
D/EGL_emulation(32278): eglMakeCurrent: 0xe952f060: ver 3 1 (tinfo 0xcd6c7780)
W/FlutterJNI(32278): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter/textinput. Response ID: 0
Lost connection to device.
Exited (sigterm)

```
I tried upgrading com.google.gms:google-services:4.2.0 but that results in other issues and the project not compiling.
I  tried migrating the project to androidx with android studio but there was no usage so
I created a new minimal project to test it with and same issue occured.

(the only pubspec.yaml dependency is the firebase_auth: ^0.15.1)
```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  TextEditingController emailCtrl;
  TextEditingController passwordCtrl;

  @override
  void initState() {
    emailCtrl = TextEditingController();
    passwordCtrl = TextEditingController();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              controller: emailCtrl,
            ),
            TextField(
              controller: passwordCtrl,
            ),
            OutlineButton(
              onPressed: () => _registerUser(),
              child: Text(
                'sign up',
              ),
            ),
          ],
        ),
      ),
    );
  }

  _registerUser() async {
    FirebaseAuth _auth = FirebaseAuth.instance;
    try {
      await _auth.createUserWithEmailAndPassword(
          email: emailCtrl.text.trim(), password: passwordCtrl.text);
      print('signed in');
    } on PlatformException catch (e) {
      print(e.message);
    }
  }
}
```

app level build.gradle:
```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "dev.vkras.auth_test"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.google.firebase:firebase-analytics:17.2.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
apply plugin: 'com.google.gms.google-services'
```

``
project level build.gradle:
```gradle


buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

flutter doctor:

```bash
Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\Flutter Sdk\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\hadih\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
```

**Comment by iapicca** [comment]
Hi @Hadii1 
can you please provide your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by Hadii1** [comment]
I changed my machine from windows to mac recently and re-installed the sdks and tried the code I posted above and it worked, I don't know what the issue was precisely but I'll go ahead and close it.
