### ISSUE TITLE
[firebase_auth ] fails w/ google_sign_in

### ISSUE THREAD

**Issue by emailsubjekt** [FirebaseExtended/flutterfire#1583]
```bash
W/ActivityThread( 5472): handleWindowVisibility: no activity for token android.os.BinderProxy@a29313d
D/EGL_emulation( 5472): eglMakeCurrent: 0xe0aa9540: ver 3 0 (tinfo 0xd552f660)
D/EGL_emulation( 5472): eglMakeCurrent: 0xe0aa9540: ver 3 0 (tinfo 0xd552f660)
E/flutter ( 5472): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
E/flutter ( 5472): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 5472): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 5472): <asynchronous suspension>
E/flutter ( 5472): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
E/flutter ( 5472): #3      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45:10)
E/flutter ( 5472): #4      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:212:42)
E/flutter ( 5472): <asynchronous suspension>
E/flutter ( 5472): #5      GoogleSignIn._addMethodCall.<anonymous closure> (package:google_sign_in/google_sign_in.dart:275:16)
E/flutter ( 5472): #6      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 5472): #7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 5472): #8      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
E/flutter ( 5472): #9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 5472): #10     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 5472): #11     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:391:9)
E/flutter ( 5472): #12     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 5472): #13     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 5472): #14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 5472): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 5472): #16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 5472): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 5472): 
I/baseauthexampl( 5472): Background young concurrent copying GC freed 27267(1242KB) AllocSpace objects, 2(104KB) LOS objects, 46% free, 1700KB/3157KB, paused 11.266ms total 81.107ms
```

**Comment by iapicca** [comment]
Hi @emailsubjekt 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by emailsubjekt** [comment]
> Hi @emailsubjekt
> can you please provide your updated `flutter doctor -v`
> and your `flutter run --verbose`?
> Also, to better address the issue, would be helpful
> if you could post a minimal code sample
> or the steps to reproduce the problem.
> Thank you

Of course, I apologize for not sending it. Also, I am using the official firebase_auth example 

I have just realized when running flutter doctor -v that I'm getting a missing dart and flutter plugin for Android Studio 3.5, however the one listed where it's missing is in downloads and I don't have android studio there. I have a now older version of the Yellow Android Studio that I don't use at all, the Android Studio beta or what's it called but even that is not in the downloads folder

----------------------------------------------------------
[√] Flutter (Channel dev, v1.13.0, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.13.0 at C:\flutter
    • Framework revision 09126abb22 (6 days ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\siris\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Users\siris\Downloads\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Android Studio (version 3.5)
    • Android Studio at C:\Users\siris\Downloads\android-studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\siris\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
-------------------------------------------------------------------------

This is from running flutter run --verbose


D:\FlutterDell\Test126-FlutterFirebaseFire\flutterfire-master\packages\firebase_auth\firebase_auth>flutter run --verbose
[  +44 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 09126abb222d0f25b03318a1ab4a99d27d9aaa8d
[   +1 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +57 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.13.0-0-g09126abb2
[   +8 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +77 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +50 ms] "flutter run" took 85ms.
Target file "lib\main.dart" not found.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:709:9)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:285:19)
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:591:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:516:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:506:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:333:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:284:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:227:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by emailsubjekt** [comment]
I changed the pubspec to 

name: firebase_auth
description: Flutter plugin for Firebase Auth, enabling Android and iOS
  authentication using passwords, phone numbers and identity providers
  like Google, Facebook and Twitter.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth
version: 0.15.1

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebaseauth
    iosPrefix: FLT
    pluginClass: FirebaseAuthPlugin

dependencies:
#  meta: ^1.0.4
  meta: ^1.1.8
#  firebase_core: ^0.4.0
  firebase_core: ^0.4.2+1
  firebase_auth_platform_interface: ^1.0.0

  flutter:
    sdk: flutter

dev_dependencies:
#  async: ^2.3.0
  async: ^2.4.0
#  google_sign_in: ^3.0.4
  google_sign_in: ^4.0.14
#  firebase_dynamic_links: ^0.3.0
  firebase_dynamic_links: ^0.5.0+8
  mockito: ^4.1.1
#  uuid: ^2.0.2
  uuid: ^2.0.4
#  test: ^1.3.0
  test: ^1.9.4
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

environment:
#  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"

**Comment by iapicca** [comment]
Hi @emailsubjekt 
are you still experiencing the issue with the latest stable version of flutter 
and the latest version of firebase_auth?
thank you

**Comment by Ehesp** [comment]
Closing due to inactivity. Please try with the latest version of the plugin and if this issue still occurs, I'll reopen the issue.

Also posting exactly how you hit this crash would help, as logs don't indicate what methods were called.
