### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for C:\Users\User\Desktop\Flutter v1.9\Flutter\bin\cache\dart-sdk\bin\pub.bat.

### ISSUE THREAD

**Issue by AsadAslamm** [FirebaseExtended/flutterfire#1621]
## Command
  ```
  flutter run --machine --target lib\main.dart -d emulator-5554 --track-widget-creation --start-paused
  ```

  ## Steps to Reproduce
  1. ...
  2. ...
  3. ...

  ## Logs
  ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\User\Desktop\Flutter v1.9\Flutter\bin\cache\dart-sdk\bin\pub.bat.
  ```
  #0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:413:27)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:431:35)
#4      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:259:33)
#5      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:176:15)
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:604:17)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:516:33)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1465:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:506:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:333:21)
<asynchronous suspension>
  ```
  ```
  [✓] Flutter (Channel dev, v1.13.0, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.13.0 at C:\Users\User\Desktop\Flutter v1.9\Flutter
    • Framework revision 09126abb22 (9 days ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\User\Desktop\Android Studio
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\User\Desktop\Android Studio
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

  ```

  ## Flutter Application Metadata
  **Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

  Since the update my every app, even the ones working fine before ,is showing this error.

**Comment by iapicca** [comment]
Hi @AsadAslamm 
in this [issue](https://github.com/flutter/flutter/issues/46880) you mentioned that 
among others your app uses these packages
```yaml
cloud_firestore
firebase_auth
firebase_auth_web
firebase_core
firebase_core_web
firebase_database
```
and you were getting an error on `flutter packages get`
is that correct?
could you please try this [solution](https://github.com/FirebaseExtended/flutterfire/issues/1606#issuecomment-565031084)?
let me know if the issue persists
thank you

**Comment by kroikie** [comment]
I don't think this is an issue with the FlutterFire plugins. @AsadAslamm this issue looks like a Framework one, maybe better to file it in the flutter/flutter repo?

**Comment by iapicca** [comment]
Hi @AsadAslamm 
are you still experiencing the issue with the latest stable version of flutter 
and the latest version of firebase?
thank you

**Comment by Ehesp** [comment]
Closing due to inactivity. Please let us know if you still have issues on the latest versions of Flutter & the plugins.
