### ISSUE TITLE
CreateShortDynamicLink are blocked

### ISSUE THREAD

**Issue by OsamaFelFel** [FirebaseExtended/flutterfire#1648]
I'm trying to shorten URLs using firebase_dynamic_links version 0.5.0+8. I have configured a custom domain on firebase and accepted the terms.

The code is matching the documentation

```
final ShortDynamicLink shortLink = await DynamicLinkParameters.shortenUrl(
        Uri.parse('https://custom_domain_configured_in_firebase/?link=${file.url}'),
        DynamicLinkParametersOptions(shortDynamicLinkPathLength: ShortDynamicLinkPathLength.unguessable),
      );
```

Which results in the following exception
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(Error 0, com.firebase.durabledeeplink, The operation couldn’t be completed. Requests to this API firebasedynamiclinks.googleapis.com method google.firebase.dynamiclinks.v1.DynamicLinksService.CreateShortDynamicLink are blocked.)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:344:48)
<asynchronous suspension>
#3      DynamicLinkParameters.shortenUrl (package:firebase_dynamic_links/src/dynamic_link_parameters.dart:70:10)
<asynchronous suspension>
```

**Comment by naumanmir** [comment]
Getting same error.

**Comment by naumanmir** [comment]
Did you add App Store Id and Team id in ios firebase application?

**Comment by OsamaFelFel** [comment]
No I didn't but as per the [documentation](https://firebase.google.com/support/guides/url-shortener) I should be able to shorten URLs without an application

> If you only want to create short links for web URLs, you may skip adding mobile apps in your Firebase project from the Project Overview page of the Firebase console. (Specify any value for the bundle ID and skip the subsequent steps).

**Comment by ch-muhammad-adil** [comment]
are you able to fix it or not ?

**Comment by OsamaFelFel** [comment]
@ch-muhammad-adil unfortunately no. I moved the shortening logic to the backend and I switched to use the REST API version instead of the plugin. You can use the REST API version in your app but you will have to add the Web Key to the app ( I believe this is not a good idea and that's why I moved the logic to the backend).

Here is the REST [documentation](https://firebase.google.com/docs/dynamic-links/rest#create_a_short_link_from_parameters). Follow that example without adding androidInfo/iosInfo part.

**Comment by Eddybrtn** [comment]
@OsamaFelFel I faced the same issue recently and I managed to find out what was wrong :
Both my Android and iOS API keys configured in google-services.json and GoogleService-Info.plist were restricted to specific APIs.
I updated these keys in API credentials section of GCP console by adding Firebase Dynamic Links, and now the short lnks are successfully created.

**Comment by kaz-mercari** [comment]
@OsamaFelFel thank you for sharing! It worked perfectly!!

**Comment by russellwheatley** [comment]
> @OsamaFelFel I faced the same issue recently and I managed to find out what was wrong :
> Both my Android and iOS API keys configured in google-services.json and GoogleService-Info.plist were restricted to specific APIs.
> 
> I updated these keys in API credentials section of GCP console by adding Firebase Dynamic Links, and now the short links are successfully created.

Hey @OsamaFelFel, can you confirm this resolved your issue?

**Comment by Salakar** [comment]
Closing due to inactivity.
