### ISSUE TITLE
[firebase_auth] anonymous sign in fails

### ISSUE THREAD

**Issue by sgehrman** [FirebaseExtended/flutterfire#1671]
Unhandled Exception: PlatformException(FirebaseException, An internal error has occurred., null)

I've seen this discussed numerous times, but not solutions.

I have the latest packages, I tried all the steps, normal email login works just fine, just not anonymous.

I'm on Android.  Crashes on phone and simulator.  Android 10.

E/flutter (30315): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(FirebaseException, An internal error has occurred., null)
E/flutter (30315): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
E/flutter (30315): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
E/flutter (30315): <asynchronous suspension>
E/flutter (30315): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349)
E/flutter (30315): #3      MethodChannelFirebaseAuth.signInAnonymously (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:52)
E/flutter (30315): #4      FirebaseAuth.signInAnonymously (package:firebase_auth/src/firebase_auth.dart:42)
E/flutter (30315): #5      AuthService.anonLogin (package:therapist_training/services/auth.dart:79)
E/flutter (30315): #6      _LoginButtonState.build.<anonymous closure> (package:therapist_training/widgets/login_button.dart:74)
E/flutter (30315): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706)
E/flutter (30315): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789)
E/flutter (30315): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
E/flutter (30315): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486)
E/flutter (30315): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282)
E/flutter (30315): #12     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199)
E/flutter (30315): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467)
E/flutter (30315): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76)
E/flutter (30315): #15     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117)
E/flutter (30315): #16     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379)
E/flutter (30315): #17     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115)
E/flutter (30315): #18     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
E/flutter (30315): #19     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218)
E/flutter (30315): #20     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
E/flutter (30315): #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
E/flutter (30315): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
E/flutter (30315): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
E/flutter (30315): #24     _rootRunUnary (dart:async/zone.dart:1138)
E/flutter (30315): #25     _CustomZone.runUnary (dart:async/zone.dart:1031)
E/flutter (30315): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
E/flutter (30315): #27     _invoke1 (dart:ui/hooks.dart:273)
E/flutter (30315): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:182)
E/flutter (30315): 

$ flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.0)
[✓] Connected device (2 available)

• No issues found!

**Comment by sgehrman** [comment]
nevermind, you have to go on firebase and enabled anonymous login.  duh.
