### ISSUE TITLE
[firebase_storage] Firebase App crashes after splash screen 

### ISSUE THREAD

**Issue by JonasJW** [FirebaseExtended/flutterfire#1692]
The beta version of my app on the play store is crashing after the splash screen. In Android Studio I can find these exceptions 

<details>
	<summary>logs</summary>

```bash
2019-12-21 16:05:13.603 21888-21993/? E/e.b.b.D: Creating atomic field updaters failed
java.lang.RuntimeException: java.security.PrivilegedActionException: java.lang.NoSuchFieldException: No field streamClosed in class Le/b/b/D$c; (declaration of 'e.b.b.D$c' appears in /data/app/com.wallmann.project_fit_flutter-ow2qlZAyLY4PRx1wLHclMw==/base.apk)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:409)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater.newUpdater(AtomicIntegerFieldUpdater.java:87)
    at e.b.b.D.<clinit>(:79)
    at e.b.b.c.d(:436)
    at e.b.b.c.b(:411)
    at e.b.a.d.b(:176)
    at com.google.firebase.firestore.f.p.<init>(:131)
    at com.google.firebase.firestore.b.z.a(:245)
    at com.google.firebase.firestore.b.z.a(:116)
    at com.google.firebase.firestore.b.u.run(Unknown Source:8)
    at com.google.firebase.firestore.g.j.a(:311)
    at com.google.firebase.firestore.g.f.call(Unknown Source:2)
    at com.google.firebase.firestore.g.j.a(:287)
    at com.google.firebase.firestore.g.e.run(Unknown Source:4)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at com.google.firebase.firestore.g.j$a.run(:205)
    at java.lang.Thread.run(Thread.java:764)
 Caused by: java.security.PrivilegedActionException: java.lang.NoSuchFieldException: No field streamClosed in class Le/b/b/D$c; (declaration of 'e.b.b.D$c' appears in /data/app/com.wallmann.project_fit_flutter-ow2qlZAyLY4PRx1wLHclMw==/base.apk)
    at java.security.AccessController.doPrivileged(AccessController.java:71)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:387)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater.newUpdater(AtomicIntegerFieldUpdater.java:87) 
    at e.b.b.D.<clinit>(:79) 
    at e.b.b.c.d(:436) 
    at e.b.b.c.b(:411) 
    at e.b.a.d.b(:176) 
    at com.google.firebase.firestore.f.p.<init>(:131) 
    at com.google.firebase.firestore.b.z.a(:245) 
    at com.google.firebase.firestore.b.z.a(:116) 
    at com.google.firebase.firestore.b.u.run(Unknown Source:8) 
    at com.google.firebase.firestore.g.j.a(:311) 
    at com.google.firebase.firestore.g.f.call(Unknown Source:2) 
    at com.google.firebase.firestore.g.j.a(:287) 
    at com.google.firebase.firestore.g.e.run(Unknown Source:4) 
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
    at com.google.firebase.firestore.g.j$a.run(:205) 
    at java.lang.Thread.run(Thread.java:764) 
 Caused by: java.lang.NoSuchFieldException: No field streamClosed in class Le/b/b/D$c; (declaration of 'e.b.b.D$c' appears in /data/app/com.wallmann.project_fit_flutter-ow2qlZAyLY4PRx1wLHclMw==/base.apk)
    at java.lang.Class.getDeclaredField(Native Method)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl$1.run(AtomicIntegerFieldUpdater.java:390)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl$1.run(AtomicIntegerFieldUpdater.java:389)
    at java.security.AccessController.doPrivileged(AccessController.java:67)
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater$AtomicIntegerFieldUpdaterImpl.<init>(AtomicIntegerFieldUpdater.java:387) 
    at java.util.concurrent.atomic.AtomicIntegerFieldUpdater.newUpdater(AtomicIntegerFieldUpdater.java:87) 
    at e.b.b.D.<clinit>(:79) 
    at e.b.b.c.d(:436) 
    at e.b.b.c.b(:411) 
    at e.b.a.d.b(:176) 
    at com.google.firebase.firestore.f.p.<init>(:131) 
    at com.google.firebase.firestore.b.z.a(:245) 
    at com.google.firebase.firestore.b.z.a(:116) 
    at com.google.firebase.firestore.b.u.run(Unknown Source:8) 
    at com.google.firebase.firestore.g.j.a(:311) 
    at com.google.firebase.firestore.g.f.call(Unknown Source:2) 
    at com.google.firebase.firestore.g.j.a(:287) 
    at com.google.firebase.firestore.g.e.run(Unknown Source:4) 
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
    at com.google.firebase.firestore.g.j$a.run(:205) 
    at java.lang.Thread.run(Thread.java:764)
````

</details>

And this one:

<details>
	<summary>logs</summary>

````bash 
2019-12-21 16:05:13.735 21888-21888/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.wallmann.project_fit_flutter, PID: 21888
java.lang.RuntimeException: Internal error in Firestore (19.0.0).
    at com.google.firebase.firestore.g.j.a(:379)
    at com.google.firebase.firestore.g.g.run(Unknown Source:2)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6710)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
 Caused by: java.lang.AbstractMethodError: abstract method "c.b.h.w$d c.b.h.w$d.d(int)"
    at c.b.h.r.a(:1319)
    at c.b.f.a.ka$b.s(:145)
    at c.b.f.a.ka$b.b(:181)
    at c.b.f.a.ka$b.a(:78)
    at c.b.f.a.ka$b$a.a(:428)
    at com.google.firebase.firestore.f.y.a(:699)
    at com.google.firebase.firestore.c.h.a(:213)
    at com.google.firebase.firestore.c.va.c(:103)
    at com.google.firebase.firestore.c.va.a(:142)
    at com.google.firebase.firestore.c.t.a(:530)
    at com.google.firebase.firestore.c.q.run(Unknown Source:6)
    at com.google.firebase.firestore.c.na.a(:180)
    at com.google.firebase.firestore.c.t.a(:520)
    at com.google.firebase.firestore.b.P.a(:178)
    at com.google.firebase.firestore.b.m.a(:91)
    at com.google.firebase.firestore.b.z.b(:152)
    at com.google.firebase.firestore.b.v.run(Unknown Source:4)
    at com.google.firebase.firestore.g.j.a(:311)
    at com.google.firebase.firestore.g.f.call(Unknown Source:2)
    at com.google.firebase.firestore.g.j.a(:287)
    at com.google.firebase.firestore.g.e.run(Unknown Source:4)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at com.google.firebase.firestore.g.j$a.run(:205)
    at java.lang.Thread.run(Thread.java:764)
````

</details>

I can run the app with `flutter run --release` without problems.

Any Ideas what this issue could be?

**Comment by lohanidamodar** [comment]
I am having similar problem, just adding admob to pubspec, crashes my app.

**Comment by JonasJW** [comment]
@lohanidamodar What admob version are you using? Does it give you any errors?

**Comment by lohanidamodar** [comment]
@JonasJW  Just by adding firebase_admob: ^0.9.0+10 in the pubspec dependency, the app crashes soon after crashing, without even connecting to flutter debugger, however there might be errors on native side which I haven't tested on android studio

**Comment by lohanidamodar** [comment]
@JonasJW I am sorry, mine was simply a misplaced application id meta error, I placed meta inside <Activity> instead of <Application>

**Comment by iapicca** [comment]
Hi @phoelapyae69 
can you please provide your `flutter doctor -v` ?
Thank you

**Comment by JonasJW** [comment]
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale de-DE)
    • Flutter version 1.12.13+hotfix.5 at /Users/jonas/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jonas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jonas/Library/Android/sdk
    • ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[!] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • LG H870 • LGH8705317fe7 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 2 categories.

```

Of course! I'm still perplexed that the app version in the Play Store crashed but `flutter run --profile` works fine. Are there any big differences between these "versions"? I always thought it would be the same thing, so I have no idea where this issue could come from.

**Comment by JonasJW** [comment]
I resolved this issue by deleting the `android` folder and configuring everything again. Now it works, I still have no idea what the issue was but at least it is fixed now.
