### ISSUE TITLE
[firebase_auth 0.15.3 ] NoSuchMethodError: The method 'verifyPhoneNumber' was called on null.

### ISSUE THREAD

**Issue by dSquadAdmin** [FirebaseExtended/flutterfire#1715]
**Describe the bug**
FirebaseAuth.instance is null when calling FirebaseAuth.instance.verifyPhoneNumber

**To Reproduce**

```dart 
final Auth = FirebaseAuth.instance;

 Future<void> _init(BuildContext context) async {
    final PhoneCodeAutoRetrievalTimeout autoRetrieve =
        (String verificID) async {
      this._verificationId = verificID;
    };

    final PhoneCodeSent codeSent = (String verid, [int forceCodeResend]) async {
      this._verificationId = verid;
    };

    final PhoneVerificationCompleted success =
        (AuthCredential credential) async {
      Auth.signInWithCredential(credential).then((user) {
        logInStreamController.add(true);
      }).catchError((error) {
        logInStreamController.add(false);
      });
      Navigator.pop(context);
    };

    final PhoneVerificationFailed failed = (AuthException exception) async {
      print('Error: ${exception.message}');
      Navigator.pop(context);
    };

    await Auth.verifyPhoneNumber(
      phoneNumber: this._phoneNum,
      timeout: const Duration(seconds: 120),
      verificationCompleted: success,
      verificationFailed: failed,
      codeSent: codeSent,
      codeAutoRetrievalTimeout: autoRetrieve,
    );
  }

 @override
  Widget build(BuildContext context) {
    this._phoneNum = widget.phoneNum;

    _init(context);

    return Scaffold(
      backgroundColor: Colors.white, ....
}

```
**Expected behavior**
It should initiate the phone verification process for Firebase.

**Additional context**
```bash
E/flutter ( 4704): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
E/flutter ( 4704): NoSuchMethodError: The method 'verifyPhoneNumber' was called on null.
E/flutter ( 4704): Receiver: null
E/flutter ( 4704): Tried calling: verifyPhoneNumber("[DEFAULT]", codeAutoRetrievalTimeout: Closure: (String) => Future<Null>, codeSent: Closure: (String, [int]) => Future<Null>, forceResendingToken: null, phoneNumber: "+9779840063836", timeout: Instance of 'Duration', verificationCompleted: Closure: (AuthCredential) => Future<Null>, verificationFailed: Closure: (AuthException) => Future<Null>)
E/flutter ( 4704): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 4704): #1      FirebaseAuth.verifyPhoneNumber (package:firebase_auth/src/firebase_auth.dart:266:42)
E/flutter ( 4704): #2      _VerifySMSScreenState._init (package:webrtc/screens/verify_screen.dart:44:16)
E/flutter ( 4704): #3      _VerifySMSScreenState.build (package:webrtc/screens/verify_screen.dart:58:5)
E/flutter ( 4704): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
E/flutter ( 4704): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
Reloaded 0 of 498 libraries in 1,296ms.
E/flutter ( 4704): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4704): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
E/flutter ( 4704): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4704): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4704): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4704): #13     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
E/flutter ( 4704): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4704): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4704): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4704): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4704): #21     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
E/flutter ( 4704): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4704): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4704): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4704): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4704): #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
E/flutter ( 4704): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4704): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4704): #33     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
E/flutter ( 4704): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter ( 4704): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter ( 4704): #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
E/flutter ( 4704): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
E/flutter ( 4704): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
E/flutter ( 4704): #41     ComponentElemen

```

**Comment by iapicca** [comment]
Hi @dSquadAdmin  
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by dSquadAdmin** [comment]
- Hmm sorry, I figured it out. I forgot to call ensureInitialized on main method. After doing that Firebase libraries worked well.
