### ISSUE TITLE
[firebase_dynamic_links] getInitialLink: getter 'length' called on null

### ISSUE THREAD

**Issue by BastianCode** [FirebaseExtended/flutterfire#1731]
**Describe the bug**
 I am currently using Flutter to develop an IOS-App and added Firebase. While using PayPal Connect with `url_launcher`, PayPal calls my DeepLink and the app is actually opening but when I try to get the path that opened the App I get an error 

**To Reproduce**
1. set up custom dynamic link  in firebase console "mydomain.page.link"
2. add "mydomain.page.link" as an associated domain in XCode
3. add appropriate url type "com.mydomain.app" with identifier "id1"
4. Using Simulator: After PayPal redirects back to the app (deep linking worked) this error appears:

```
>  VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception:
> NoSuchMethodError: The getter 'length' was called on null.
>     Receiver: null
>     Tried calling: length
>     #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
>     #1      Uri.parse (dart:core/uri.dart:794:17)
>     #2      FirebaseDynamicLinks.getPendingDynamicLinkDataFromMap (package:firebase_dynamic_links/src/firebase_dynamic_links.dart:67:11)
>     #3      FirebaseDynamicLinks.getInitialLink (package:firebase_dynamic_links/src/firebase_dynamic_links.dart:37:12)
>     <asynchronous suspension>
>     #4      _AddPaymentState.retrieveDynamicLink (package:premorrowhq/pages/add_payment.dart:37:75)
>     #5      _AddPaymentState.didChangeAppLifecycleState.<anonymous closure> (package:premorrowhq/pages/add_payment.dart:31:9)
>     #6      _rootRun (dart:async/zone.dart:1122:38)
>     #7      _CustomZone.run (dart:async/zone.dart:1023:19)
>     #8      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
>     #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)

```

**My Code:**

```
class _AddPaymentState extends State<AddPayment> with WidgetsBindingObserver{
      Timer _timerLink;


     @override
     void initState() {
       super.initState();
       WidgetsBinding.instance.addObserver(this);
     }



      @override
      void didChangeAppLifecycleState(AppLifecycleState state) {
        if (state == AppLifecycleState.resumed) {
            _timerLink = new Timer(const Duration(milliseconds: 1000), () {
            retrieveDynamicLink();
          });
        }
      }



      Future<void> retrieveDynamicLink() async {
      final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
        final Uri deepLink = data?.link;

        if (deepLink != null) {
          print(deepLink.path);
        }

        FirebaseDynamicLinks.instance.onLink(
          onSuccess: (PendingDynamicLinkData dynamicLink) async {
            final Uri deepLink = dynamicLink?.link;

            if (deepLink != null) {
              print(deepLink.path);
            }
          },
          onError: (OnLinkErrorException e) async {
            print('onLinkError');
            print(e.message);
          }
        );
    }
    }
```
**The line that causes the error:**

`  final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
`

**Flutter doctor**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)
```

**Comment by BastianCode** [comment]
readded everything, it works now. No clue why but I wont complain
