### ISSUE TITLE
[cloud_firestore] Internal error in cloud firestore, logcat reports (release builds)

### ISSUE THREAD

**Issue by GroovinChip** [FirebaseExtended/flutterfire#1993]
As of yesterday my app has been crashing on startup. It was working for weeks beforehand and I had changed nothing at the time of the crashes starting. I took a logcat, which indicated that firestore was the problem. See:
```
02-11 15:42:25.236 14480 14480 E AndroidRuntime: FATAL EXCEPTION: main
02-11 15:42:25.236 14480 14480 E AndroidRuntime: Process: com.groovinchip.solo_social, PID: 14480
02-11 15:42:25.236 14480 14480 E AndroidRuntime: java.lang.RuntimeException: Internal error in Cloud Firestore (21.3.0).
02-11 15:42:25.236 14480 14480 E AndroidRuntime:     at com.google.firebase.firestore.g.i.a(:529)
02-11 15:42:25.236 14480 14480 E AndroidRuntime:     at com.google.firebase.firestore.g.e.run(Unknown Source:2)
02-11 15:42:25.236 14480 14480 E AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:883)
02-11 15:42:25.236 14480 14480 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:100)
02-11 15:42:25.236 14480 14480 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:237)
02-11 15:42:25.236 14480 14480 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:7762)
02-11 15:42:25.236 14480 14480 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
02-11 15:42:25.236 14480 14480 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-11 15:42:25.236 14480 14480 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
02-11 15:42:25.236 14480 14480 E AndroidRuntime: Caused by: java.lang.AbstractMethodError: abstract method "b.c.g.w$d b.c.g.w$d.a(int)"
```

Ii occurred to me that web support was added right around the time the startup crashes began. I wonder if that is contributing to this problem?

**Comment by amrfarid140** [comment]
@GroovinChip Yes, the latest version had major changes. Do you know which operation is crashing?

**Comment by GroovinChip** [comment]
No, I don't know which operation is crashing. The only logging I can get is from the logcat, which I pasted in the OP

**Comment by GroovinChip** [comment]
@amrfarid140 here is a more complete log:
```
02-13 13:57:01.362 18050 18050 E AndroidRuntime: FATAL EXCEPTION: main
02-13 13:57:01.362 18050 18050 E AndroidRuntime: Process: com.groovinchip.solo_social, PID: 18050
02-13 13:57:01.362 18050 18050 E AndroidRuntime: java.lang.RuntimeException: Internal error in Cloud Firestore (21.3.0).
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.g.i.a(:529)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.g.e.run(Unknown Source:2)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7762)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: Caused by: java.lang.AbstractMethodError: abstract method "b.c.g.w$d b.c.g.w$d.a(int)"
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at b.c.g.r.a(:1319)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at b.c.e.a.da.C(:5478)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at b.c.e.a.da.a(:5547)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at b.c.e.a.da.a(:13)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at b.c.e.a.da$a.a(:6627)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.f.N.b(:728)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.c.j.a(:217)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.c.ya.c(:103)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.c.ya.a(:142)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.c.v.a(:547)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.c.s.run(Unknown Source:6)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.c.qa.a(:189)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.c.v.a(:537)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.b.P.a(:183)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.b.o.a(:104)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.b.C.b(:169)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.b.y.run(Unknown Source:4)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.g.i.a(:431)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.g.d.call(Unknown Source:2)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.g.i$b.a(:317)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.g.k.run(Unknown Source:4)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at com.google.firebase.firestore.g.i$b$a.run(:224)
02-13 13:57:01.362 18050 18050 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
02-13 13:57:01.368  1251 12714 E FreecessController: UFZ error : com.groovinchip.solo_social(0)
02-13 13:57:01.414  1251  3870 E InputDispatcher: channel '9b85d3d com.groovinchip.solo_social/com.groovinchip.solo_social.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-13 13:57:01.464  1251 13401 E WindowManager: win=Window{9b85d3d u0 com.groovinchip.solo_social/com.groovinchip.solo_social.MainActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1186 com.android.server.wm.AppWindowToken.destroySurfaces:1167 com.android.server.wm.WindowState.onExitAnimationDone:4969 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:3481 com.android.server.wm.AppWindowToken.commitVisibility:846 
02-13 13:57:01.560  1251 11708 E BartenderActivityManager: BarTender: pid : 26633 cached=false abnormal=true kill=false stay=false release=true
02-13 13:57:01.566  6759  6870 E PBSessionCacheImpl: sessionId[29727977931012874] not persisted.
02-13 13:57:02.089  1251 12298 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
02-13 13:57:02.354 17654 18173 E BatteryFasDaoImpl: This app com.facebook.katana is disabled now, so we do not insert this app to FAS table
02-13 13:57:02.354 17654 18173 E BatteryFasDaoImpl: traverseFasDatabase : 10163 com.facebook.katanais disabled now, so we skip !!
02-13 13:57:02.658  7712  7712 E FirebaseAuth: [UpdateProfile] RemoteException when sending get token and account info user response
02-13 13:57:02.658  7712  7712 E FirebaseAuth: android.os.DeadObjectException
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at android.os.BinderProxy.transactNative(Native Method)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at android.os.BinderProxy.transact(BinderProxy.java:526)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at ciw.c(:com.google.android.gms@200414037@20.04.14 (120400-294335909):1)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at bqcw.a(:com.google.android.gms@200414037@20.04.14 (120400-294335909):10)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at bqbi.a(:com.google.android.gms@200414037@20.04.14 (120400-294335909):9)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at bpyx.a(:com.google.android.gms@200414037@20.04.14 (120400-294335909):1)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at aten.run(:com.google.android.gms@200414037@20.04.14 (120400-294335909):1)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at sms.a(:com.google.android.gms@200414037@20.04.14 (120400-294335909):3)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at zyu.run(:com.google.android.gms@200414037@20.04.14 (120400-294335909):0)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at android.os.Handler.handleCallback(Handler.java:883)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at adrt.a(:com.google.android.gms@200414037@20.04.14 (120400-294335909):2)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at adrt.dispatchMessage(:com.google.android.gms@200414037@20.04.14 (120400-294335909):14)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at android.os.Looper.loop(Looper.java:237)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at android.app.ActivityThread.main(ActivityThread.java:7762)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at java.lang.reflect.Method.invoke(Native Method)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-13 13:57:02.658  7712  7712 E FirebaseAuth: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
02-13 13:57:02.908  1251  1380 E NotificationService: Suppressing notification from package by user request.```

**Comment by amrfarid140** [comment]
@GroovinChip just to confirm, you are seeing this crash on version `0.12.11` as well?

**Comment by GroovinChip** [comment]
Oh I didn't go that far back, I went to `0.13.1`, before mentions of web started showing in the changelogs. So `0.12.11` is the true last version before web support started?

**Comment by amrfarid140** [comment]
Yes it is. It's the last version before `cloud_firstore` migrated to use the `cloud_firestore_platform_interface`. It would help if you can test with `0.12.11` and let us know if you still see the crash or not. 

Also, it would really help if you can give us more context on what is operation the app is doing when you get this crash.

**Comment by GroovinChip** [comment]
Sure, I'm doing a build right now. The context is that I use Google Sign In in conjunction with Firebase Auth to log into the app, and it immediately crashes. Then, on relaunch the home screen of the app flashes briefly (the auth worked) before it crashes again.

**Comment by amrfarid140** [comment]
Thanks for this context. Would you be able to share a code sample to reproduce ?

**Comment by GroovinChip** [comment]
OK so `0.12.11` isn't working either. I'm not sure how I would share a code sample, the app is a bit complicated. I can link the relevant files here (they aren't long):
1) https://github.com/GroovinChip/SoloSocial/blob/master/lib/utilities/google_auth.dart
2) https://github.com/GroovinChip/SoloSocial/blob/master/lib/utilities/auth_check.dart

File 1 handles the auth, File 2 takes you to various screens based on auth state.

**Comment by amrfarid140** [comment]
Thanks, let me have a look and try to track down the issue if I can.

**Comment by GroovinChip** [comment]
Thanks!

**Comment by GroovinChip** [comment]
Update - when choosing "run in release mode" from Android Studio, the app runs with no problem on `0.12.11`. However, simply building an apk and installing it manually, or building the apk and doing `flutter install` still has crashes. With `0.13.2+1`, the result is the same. Why would there be a difference between these installation methods?

**Comment by atnegrete** [comment]
I'm having this issue as well, running `0.13.0+1` in release mode breaks Android.

**Comment by GroovinChip** [comment]
Is there any movement on this?

**Comment by GroovinChip** [comment]
@amrfarid140 This is a major blocker for me in my current project, is there anything I can do to help solve this problem?

**Comment by amrfarid140** [comment]
@GroovinChip I looked at your code samples and couldn't find a specific reason for the crash. However, v0.13.3 was recently published with fixes for other issues so maybe try it out and see if it resolves your issue.

@atnegrete Do you know the operation that is causing the issue?

**Comment by GroovinChip** [comment]
@amrfarid140 no, I'm still experiencing the crashes

**Comment by GroovinChip** [comment]
Okay so I just worked this out with @slightfoot and the problem was with the gradle build process and versions of gradle and google services. Closing issue.

**Comment by kobe-anacoimbra** [comment]
@GroovinChip can you explain how did you fix this? And how is your `build.gradle` files, google services plugin version, kotlin version, etc.? I'm still having this issue. Thank you!

**Comment by GroovinChip** [comment]
@kobe-anacoimbra make your dependencies in your project level `build.gradle` look exactly like [this](https://github.com/GroovinChip/SoloSocial/blob/master/android/build.gradle#L10)

**Comment by emiliodallatorre** [comment]
> @kobe-anacoimbra make your dependencies in your project level `build.gradle` look exactly like [this](https://github.com/GroovinChip/SoloSocial/blob/master/android/build.gradle#L10)

I tried this out, and I don't think it's a valid solution (it didn't work for me).
I found this [StackOverflow question](https://stackoverflow.com/questions/58353313/flutter-app-crashes-when-it-use-firestore-plugin-in-release-mode) that will probably help.
