### ISSUE TITLE
[firebase_messaging] Upgrading the Firebase Messaging android library to latest version

### ISSUE THREAD

**Issue by mayurdhurpate** [FirebaseExtended/flutterfire#2067]
Firebase Messaging latest version `com.google.firebase:firebase-messaging:20.1.0` [fixed a major NPE bug causing crashes on sending image notifications](https://firebase.google.com/support/release-notes/android#messaging_v20-1-0). 

Bug Fix comment: https://github.com/firebase/firebase-android-sdk/issues/1006#issuecomment-566152818

It seems the `firebase_messaging` Flutter plugin currently uses the previous version of the library. 

https://github.com/FirebaseExtended/flutterfire/blob/44e07cc2a0a8700a86290b383b03bc974c5d633a/packages/firebase_messaging/android/build.gradle#L35

Would like to propose upgrading the Android library to the latest version. Though I never contributed, I could attempt to open a PR for this one.

**Comment by mayurdhurpate** [comment]
Any updates on this? This issue is causing a lot of bugs on Crashylytics for our users.

**Comment by mayurdhurpate** [comment]
For reference, this is the crash which I'm getting on Google Play Console and Crashylytics in huge numbers which are probably happening due to this bug.
```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference
       at com.android.okhttp.okio.Buffer.write(Buffer.java:1182)
       at com.android.okhttp.okio.Buffer.read(Buffer.java:1221)
       at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:65)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:602)
       at com.android.okhttp.internal.Util.skipAll(Util.java:172)
       at com.android.okhttp.internal.Util.discard(Util.java:154)
       at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:619)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:421)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:409)
       at com.google.android.gms.internal.firebase_messaging.zzk.zza(zzk.java:4)
       at com.google.firebase.messaging.zzj.close(zzj.java:37)
       at com.google.firebase.messaging.zzd.zza(zzd.java:51)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc(FirebaseMessagingService.java:60)
       at com.google.firebase.messaging.zze.run(zze.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:764)
```
![image](https://user-images.githubusercontent.com/10077074/86199632-3a7d9600-bb78-11ea-9f40-94cea7dd9304.png)

Requesting the team to have a look at it.

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.
