### ISSUE TITLE
flutter.io/firebase_database

### ISSUE THREAD

**Issue by asharora** [FirebaseExtended/flutterfire#2070]
```bash
Restarted application in 40,260ms.
E/flutter (23203): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method DatabaseReference#set on channel plugins.flutter.io/firebase_database)
[38;5;244mE/flutter (23203): #0      MethodChannel.invokeMethod[39;49m
E/flutter (23203): <asynchronous suspension>
[38;5;248mE/flutter (23203): #1      DatabaseReference.set  (package:firebase_database/src/database_reference.dart:73:31)[39;49m
[38;5;248mE/flutter (23203): #2      society_listviewState.build[39;49m
[38;5;244mE/flutter (23203): #3      StatefulElement.build[39;49m
[38;5;244mE/flutter (23203): #4      ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #5      Element.rebuild[39;49m
[38;5;244mE/flutter (23203): #6      ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #7      StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #8      ComponentElement.mount[39;49m
[38;5;244mE/flutter (23203): #9      Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #10     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #11     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #12     Element.rebuild[39;49m
[38;5;244mE/flutter (23203): #13     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #14     ComponentElement.mount[39;49m
[38;5;244mE/flutter (23203): #15     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #16     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #17     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter (23203): #18     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #19     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #20     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter (23203): #21     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #22     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #23     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #24     Element.rebuild[39;49m
[38;5;244mE/flutter (23203): #25     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #26     ComponentElement.mount[39;49m
[38;5;244mE/flutter (23203): #27     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #28     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #29     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #30     Element.rebuild[39;49m
[38;5;244mE/flutter (23203): #31     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #32     ComponentElement.mount[39;49m
[38;5;244mE/flutter (23203): #33     ParentDataElement.mount[39;49m
[38;5;244mE/flutter (23203): #34     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #35     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #36     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #37     Element.rebuild[39;49m
[38;5;244mE/flutter (23203): #38     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #39     StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #40     ComponentElement.mount[39;49m
[38;5;244mE/flutter (23203): #41     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #42     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #43     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #44     Element.rebuild[39;49m
E/flutter (23203): #45     Comp
Restarted application in 40,260ms.
E/flutter (23203): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method DatabaseReference#set on channel plugins.flutter.io/firebase_database)
[38;5;244mE/flutter (23203): #0      MethodChannel.invokeMethod[39;49m
E/flutter (23203): <asynchronous suspension>
[38;5;248mE/flutter (23203): #1      DatabaseReference.set  (package:firebase_database/src/database_reference.dart:73:31)[39;49m
[38;5;248mE/flutter (23203): #2      society_listviewState.build[39;49m
[38;5;244mE/flutter (23203): #3      StatefulElement.build[39;49m
[38;5;244mE/flutter (23203): #4      ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #5      Element.rebuild[39;49m
[38;5;244mE/flutter (23203): #6      ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #7      StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #8      ComponentElement.mount[39;49m
[38;5;244mE/flutter (23203): #9      Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #10     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #11     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #12     Element.rebuild[39;49m
[38;5;244mE/flutter (23203): #13     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #14     ComponentElement.mount[39;49m
[38;5;244mE/flutter (23203): #15     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #16     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #17     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter (23203): #18     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #19     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #20     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mE/flutter (23203): #21     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #22     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #23     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #24     Element.rebuild[39;49m
[38;5;244mE/flutter (23203): #25     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #26     ComponentElement.mount[39;49m
[38;5;244mE/flutter (23203): #27     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #28     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #29     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #30     Element.rebuild[39;49m
[38;5;244mE/flutter (23203): #31     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #32     ComponentElement.mount[39;49m
[38;5;244mE/flutter (23203): #33     ParentDataElement.mount[39;49m
[38;5;244mE/flutter (23203): #34     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #35     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #36     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #37     Element.rebuild[39;49m
[38;5;244mE/flutter (23203): #38     ComponentElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #39     StatefulElement._firstBuild[39;49m
[38;5;244mE/flutter (23203): #40     ComponentElement.mount[39;49m
[38;5;244mE/flutter (23203): #41     Element.inflateWidget[39;49m
[38;5;244mE/flutter (23203): #42     Element.updateChild[39;49m
[38;5;244mE/flutter (23203): #43     ComponentElement.performRebuild[39;49m
[38;5;244mE/flutter (23203): #44     Element.rebuild[39;49m
E/flutter (23203): #45     Comp

```

**Comment by iapicca** [comment]
Hi @asharora 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @asharora 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
