### ISSUE TITLE
[firebase_messaging] example breaks on second navigation to item detail

### ISSUE THREAD

**Issue by biergit** [FirebaseExtended/flutterfire#2142]
**Describe the bug**
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/example breaks on second navigation to item detail.

**To Reproduce**
1. Run the app and click the floating action button
2. Click show
3. Navigate back
4. Click the button again
5. Click show again
4. See red screen of death

```/flutter (32289): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 189 pos 12: '!_transitionCompleter.isCompleted': Cannot install a MaterialPageRoute<void> after disposing it.
E/flutter (32289): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
E/flutter (32289): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
E/flutter (32289): #2      TransitionRoute.install (package:flutter/src/widgets/routes.dart:189:12)
E/flutter (32289): #3      ModalRoute.install (package:flutter/src/widgets/routes.dart:972:11)
E/flutter (32289): #4      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1791:11)
E/flutter (32289): #5      Navigator.push (package:flutter/src/widgets/navigator.dart:1121:34)
E/flutter (32289): #6      _PushMessagingExampleState._navigateToItemDetail (package:werona/main.dart:130:17)
E/flutter (32289): #7      _PushMessagingExampleState._showItemDialog.<anonymous closure> (package:werona/main.dart:120:9)
E/flutter (32289): #8      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (32289): #9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (32289): #10   

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#45c9d](dirty, state: NavigatorState#e40b3(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2335 pos 12: '!_debugLocked': is not true.```

**Comment by iapicca** [comment]
Hi @biergit 
can you please provide your `flutter doctor -v` , 
and your `pubspec.yaml` 
Thank you

**Comment by biergit** [comment]
Hi :)
here you go

## `flutter doctor -v`
```
C:\Users\user_name\AndroidStudioProjects\werona>flutter doctor -v
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.17763.737], locale de-DE)
    • Flutter version 1.14.6 at E:\Flutter\flutter
    • Framework revision fabeb2a16f (7 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\user_name\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
```
## `pubspec.yaml`
```
name: werona
description: Some description

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4
  html: ^0.14.0+3
  firebase_core: ^0.4.4+2
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.12
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
