### ISSUE TITLE
App crash on receiving Push Notification (Flutter - iOS device)

### ISSUE THREAD

**Issue by iud1295** [FirebaseExtended/flutterfire#2157]
I have enabled `Push Notifications` capability and using `firebase_messaging: ^6.0.12`
I have this in my Info.plist file
```
<key>FirebaseAppDelegateProxyEnabled</key>
<false/>
<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
```

My code in app.dart
```
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';

class App extends StatefulWidget {
  static GlobalKey globalKey = new GlobalKey(debugLabel: "");

  @override
  State<StatefulWidget> createState() => AppState();
}

class AppState extends State<App> with WidgetsBindingObserver {
  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
  final navigatorKey = GlobalKey<NavigatorState>();

  @override
  void initState() {
    super.initState();

    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
        _showNotification(message);
      },
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
        _navigateToItemDetail(message);
      },
    );

    if (Platform.isIOS) {
      Future.delayed(Duration(seconds: 8), () {
        _firebaseMessaging.requestNotificationPermissions(
            const IosNotificationSettings(
                sound: true, badge: true, alert: true));
      });

      _firebaseMessaging.onIosSettingsRegistered
          .listen((IosNotificationSettings settings) {
        print("Settings registered: $settings");
      });
    }

    _firebaseMessaging.getToken().then((String token) {
      assert(token != null);
      print("Push Messaging token: $token");
    });
  }

  void _showNotification(Map<String, dynamic> message) async {
     //shows alert
  }

  void _navigateToItemDetail(Map<String, dynamic> message) {
    //navigate to detail
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
              navigatorKey: navigatorKey,
              child: Scaffold(),
              bottomNavigationBar: ...,
    );
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
}

```
My notification object has this payload format
```
"notification": {
        "title": "",
        "subtitle": "",
        "body": "",
        "badge": 1,
        "sound": "default",
        "content-available": 1
  },
  "data": {
  	"notification": {
    	       "title": "",
    	       "subtitle": "",
    	       "body": ""
	},
       "type": "",
       "item": {
               "id": 242, ....
      }
  }
```

Every time I send a notification app crashes on iPhone
![Screenshot 2020-03-11 at 12 48 37 PM](https://user-images.githubusercontent.com/43640586/76391964-a30cf100-6396-11ea-8332-d56ae4f59521.png)

I have tried cleaning and reinstalling the app

**Comment by iapicca** [comment]
Hi @iud1295 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by iud1295** [comment]
Hi @iapicca 
-> flutter doctor -v
```
[✓] Flutter (Channel dev, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-IN)
    • Flutter version 1.14.6 at /Users/ishadhavaskar/Documents/flutter
    • Framework revision fabeb2a16f (6 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.9.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
-> flutter run --verbose
```
[  +34 ms] executing: [/Users/ishadhavaskar/Documents/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +50 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/Users/ishadhavaskar/Documents/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +116 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] v1.14.6-0-gfabeb2a16
[  +12 ms] executing: [/Users/ishadhavaskar/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[        ] executing: [/Users/ishadhavaskar/Documents/flutter/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +64 ms] executing: [/Users/ishadhavaskar/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +11 ms] executing: sw_vers -productName
[  +23 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +19 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +29 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +46 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] Unable to locate an Android SDK.
[  +20 ms] Unable to locate an Android SDK.
[  +45 ms] executing: /Users/ishadhavaskar/Documents/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +81 ms] executing: /usr/bin/xcode-select --print-path
[  +13 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +2 ms] executing: /usr/bin/xcodebuild -version
[ +953 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.2
           Build version 11B52
[   +5 ms] /usr/bin/xcrun simctl list --json devices
[ +334 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +98 ms] No supported devices connected.
[  +17 ms] "flutter run" took 1,783ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:325:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:619:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:537:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:527:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/ishadhavaskar/Documents/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

-> pubspec.yaml
[pubspec_yaml.docx](https://github.com/FirebaseExtended/flutterfire/files/4317082/pubspec_yaml.docx)

**Comment by iapicca** [comment]
Thank you for the logs @iud1295  .

I don't think this is the cause,
but just in case, 
could you please run `flutter upgrade`
thanks again

**Comment by iud1295** [comment]
Hi @iapicca 
This issue still persists. 

Output: 
```
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6ff94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c53dac ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c55f38 _CF_forwarding_prep_0 + 120
	5   Runner                              0x0000000104c13282 -[FIRMessagingDataMessageManager parseDataMessage:] + 1618
	6   Runner                              0x0000000104c12b32 -[FIRMessagingDataMessageManager processPacket:] + 338
	7   Runner                              0x0000000104c099db -[FIRMessagingClient connectionDidRecieveMess<…>
Lost connection to device.
```

**Comment by iapicca** [comment]
Thank you for trying @iud1295

**Comment by russellwheatley** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: [https://firebase.flutter.dev/docs/messaging/overview](https://firebase.flutter.dev/docs/messaging/overview)If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
