### ISSUE TITLE
[firebase_messaging] Caused by java.lang.RuntimeException: PluginRegistrantCallback is not set.

### ISSUE THREAD

**Issue by eugene-exd** [FirebaseExtended/flutterfire#2202]
**Describe the bug**
Application uses push messages, but **without handling background** messages. So, all related things for configuration was skipped. Nonetheless we have crash on some Android devices, mostly with Android 10.

**To Reproduce**
Cannot provide steps to reproduce. Crashing causing on user side. Most likely at the time of initialization or the first launch of the application.

**Additional context**
Used firebase_messaging: 6.0.12

**Crash log**

```
Fatal Exception: java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.RuntimeException: PluginRegistrantCallback is not set.
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4165)
       at android.app.ActivityThread.access$1600(ActivityThread.java:267)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1997)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
	   
	   
Caused by java.lang.RuntimeException: PluginRegistrantCallback is not set.
       at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.b(FlutterFirebaseMessagingService.java:80)
       at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate(FlutterFirebaseMessagingService.java:42)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4153)
       at android.app.ActivityThread.access$1600(ActivityThread.java:267)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1997)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

```

**Comment by nezoat** [comment]
I'm having same problem.  Also not using background message handling, and did not configure background handling.  Also using firebase_messaging 6.0.12.

**Comment by iapicca** [comment]
Hi @eugene-exd  and @nezoat 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and if possible a minimal code sample
of your implementation of `firebase_messaging`
Thank you

**Comment by nezoat** [comment]
If found that the issue was some kind of conflict with the keyboard_visibility plugin.  Resolved when I removed it.

**Comment by eugene-exd** [comment]
**pubspec.yaml**

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.2

  
  shared_preferences: 0.5.6
  package_info: ^0.4.0+3
  sprintf: ^4.0.0
  path_provider: ^0.5.0+1
  cached_network_image: ^2.0.0-rc
  flutter_youtube: ^2.0.0
  mime_type: 0.2.5
  sqflite: ^1.2.1
  
  firebase_crashlytics: 0.1.3
  firebase_messaging: ^6.0.12

  rating_bar: ^0.2.0
  percent_indicator: ^2.1.1
  image_picker: 0.6.2+3
  fluttertoast: 3.1.3

  ping_discover_network: ^0.2.0+1
  wifi: ^0.1.5
  mdns_plugin: 1.1.3

  webview_flutter: 0.3.19+5

  back_button_interceptor: ^4.2.3

  flutter_localizations:
    sdk: flutter
```

**flutter doctor -v**

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.1)
    • VS Code at C:\Users\Owner\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

**Usage**
```
  static final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();

  static Future<String> register() async {
    _firebaseMessaging.setAutoInitEnabled(false);
    return _firebaseMessaging.getToken();
  }

  static Future<bool> unregister() async {
    return _firebaseMessaging.deleteInstanceID();
  }

  static configure() async {
    _firebaseMessaging.configure(
        onMessage: firebaseBackgroundMessageHandler, onLaunch: firebaseBackgroundMessageHandler, onResume: firebaseBackgroundMessageHandler);
  }
  
...
  
  Future<dynamic> firebaseBackgroundMessageHandler(Map<String, dynamic> message) async {
    PushNotification.addNotification(message);
  }
```

**Comment by Salakar** [comment]
Closing in favour of trying the latest messaging version which has since this issue was created been heavily reworked to improve it along with detailed documentation: https://firebase.flutter.dev/docs/messaging/overview

If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
