### ISSUE TITLE
I found this error all over github however nothing seems to work 

### ISSUE THREAD

**Issue by bader871** [FirebaseExtended/flutterfire#228]
So I'm following a flutter course where we make a chat app and to avoid mistakes im following the instructor's code closely, however firebase just wouldn't work and here's the full error code: 

E/MethodChannel#plugins.flutter.io/firebase_auth(11390): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.createUserWithEmailAndPassword(java.lang.String, java.lang.String)' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleCreateUserWithEmailAndPassword(FirebaseAuthPlugin.java:312)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:93)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/firebase_auth(11390): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (11390): CAUGHT EXCEPTION: PlatformException(error, Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.createUserWithEmailAndPassword(java.lang.String, java.lang.String)' on a null object reference, null)

and heres my code: 
`import 'package:flash_chat/constants.dart';
import 'package:flash_chat/rounded_buttons.dart';
import 'package:flash_chat/screens/chat_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';

class RegistrationScreen extends StatefulWidget {
  static const String id = "registration";
  
  @override
  _RegistrationScreenState createState() => _RegistrationScreenState();
}

class _RegistrationScreenState extends State<RegistrationScreen> {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  String email,password;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: Padding(
        padding: EdgeInsets.symmetric(horizontal: 24.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: <Widget>[
            Hero(
              tag: "lightningBolt",
              child: Container(
                height: 200.0,
                child: Image.asset('images/logo.png'),
              ),
            ),
            SizedBox(
              height: 48.0,
            ),
            TextField(
              textAlign: TextAlign.center,
              keyboardType: TextInputType.emailAddress,
              onChanged: (value) {
                //Do something with the user input.
                email=value;
              },
              decoration: kTextFieldDecoration.copyWith(
                hintText: "Enter your email",
              ),
            ),
            SizedBox(
              height: 8.0,
            ),
            TextField(
              textAlign: TextAlign.center,
              obscureText: true,
              onChanged: (value) {
                //Do something with the user input.
                password=value;
              },
              decoration: kTextFieldDecoration.copyWith(
                  hintText: "Enter your password"),
            ),
            SizedBox(
              height: 24.0,
            ),
            RoundedButton(
              color: Colors.blueAccent,
              buttonText: "Register",
              onPressed: () async {
              
                try{
                final newUser = await _auth.createUserWithEmailAndPassword(
                  email: "email@gmail.com",
                  password: "password123");
                  
                  if(newUser != null){
                    Navigator.pushNamed(context, ChatScreen.id);
                  }
                 
                }
                catch (e){
                  print("CAUGHT EXCEPTION: $e");
                }

              },
            )
          ],
        ),
      ),
    );
  }
}
`

**Comment by bader871** [comment]
I found the solution to this and many other bugs that came with it by simply going to
_PROJECT/Android/gradle/wrapper/gradle-wrapper.properties_
then update the distributerUrl to 
distributionUrl=https://services.gradle.org/distributions/gradle-5.1.1-all.zip
