### ISSUE TITLE
[firebase_auth] [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null. 

### ISSUE THREAD

**Issue by saffer4u** [FirebaseExtended/flutterfire#2281]
I am continuously getting these error messages in all my firebase projects.
```
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  String email;
  String password;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firebase Retest'),
      ),
      body: Column(
        children: <Widget>[
          TextField(
            onChanged: (value) {
              email = value;
            },
          ),
          TextField(
            onChanged: (value) {
              password = value;
            },
          ),
          RaisedButton(
            child: Text('Sign Up'),
            onPressed: () {
              FirebaseAuth.instance
                  .createUserWithEmailAndPassword(
                      email: email, password: password)
                  .then((result) {
                print(result.user.email);
              });
            },
          ),
        ],
      ),
    );
  }
}
```
dependencies :
firebase_auth: ^0.15.5+2
```
I/BiChannelGoogleApi(12641): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@1e23187
D/FirebaseAuth(12641): Notifying id token listeners about user ( lFNdsGC2ITVoKNIChfd3McZ0buA2 ).
D/FirebaseAuth(12641): Notifying auth state listeners about user ( lFNdsGC2ITVoKNIChfd3McZ0buA2 ).
E/flutter (12641): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (12641): Receiver: null
E/flutter (12641): Tried calling: []("providerData")
E/flutter (12641): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (12641): #1      _decodeUser (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:422:45)
E/flutter (12641): #2      _decodeAuthResult (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:454:29)
E/flutter (12641): #3      MethodChannelFirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:68:12)
E/flutter (12641): <asynchronous suspension>
E/flutter (12641): #4      FirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth/src/firebase_auth.dart:64:10)
E/flutter (12641): #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter (12641): #6      FirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth/src/firebase_auth.dart:57:52)
E/flutter (12641): #7      MyHomePage.build.<anonymous closure> (package:firebaseretest/main.dart:40:20)
E/flutter (12641): #8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter (12641): #9      MyHomePage.build.<anonymous closure> (package:firebaseretest/main.dart:38:24)
E/flutter (12641): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (12641): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (12641): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (12641): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (12641): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (12641): #15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (12641): #16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (12641): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (12641): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (12641): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (12641): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (12641): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (12641): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (12641): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (12641): #24     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (12641): #25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (12641): #26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (12641): #27     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (12641): #28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (12641): #29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (12641): #30     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (12641): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (12641): 
```
New user is created in the firebase, but i get null in return.
Someone please help me i got stuck.

Yesterday it was working but i don't know why it's not working today

**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57,
    locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at /Users/aftab/Desktop/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/aftab/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

```

**flutter run --verbose**
```
[  +35 ms] executing: [/Users/aftab/Desktop/flutter/] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +1 ms] executing: [/Users/aftab/Desktop/flutter/] git describe --match
v*.*.* --first-parent --long --tags
[  +12 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +10 ms] executing: [/Users/aftab/Desktop/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/aftab/Desktop/flutter/] git ls-remote --get-url
origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +68 ms] executing: [/Users/aftab/Desktop/flutter/] git rev-parse --abbrev-ref
HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +18 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +22 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.2
[        ] executing: sw_vers -buildVersion
[  +19 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19C57
[  +38 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +142 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +2 ms] Xcode 11.3
           Build version 11C29
[  +71 ms] executing: /Users/aftab/Library/Android/sdk/platform-tools/adb
devices -l
[   +8 ms] Exit code 0 from: /Users/aftab/Library/Android/sdk/platform-tools/adb
devices -l
[        ] List of devices attached
[  +17 ms] executing:
/Users/aftab/Desktop/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +68 ms] /usr/bin/xcrun simctl list --json devices
[ +137 ms] No supported devices connected.
[  +13 ms] "flutter run" took 589ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main
(file:///Users/aftab/Desktop/flutter/packages/flutter_tools/bin/flutter_tools.da
rt:8:3)
#40     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by saffer4u** [comment]
Someone please help me

**Comment by TahaTesser** [comment]
Hi @saffer4u 
You are not properly assigning your textfield values to your variable
Convert your stateless class to stateful and setState for each variable 

### Code Sample
```
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String email;

  String password;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firebase Retest'),
      ),
      body: Column(
        children: <Widget>[
          TextField(
            onChanged: (value) {
              setState(() {
                email = value;
              });
            },
          ),
          TextField(
            onChanged: (value) {
              setState(() {
                password = value;
              });
            },
          ),
          RaisedButton(
            child: Text('Sign Up'),
            onPressed: () {
              FirebaseAuth.instance
                  .createUserWithEmailAndPassword(
                      email: email, password: password)
                  .then((result) {
                print(result.user.email);
              });
            },
          ),
        ],
      ),
    );
  }
}
```

```
I/BiChannelGoogleApi(25380): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@b469f11
D/FirebaseAuth(25380): Notifying id token listeners about user ( wNHQvQbPu7amwkpdQsU77deXXkC2 ).
D/FirebaseAuth(25380): Notifying auth state listeners about user ( wNHQvQbPu7amwkpdQsU77deXXkC2 ).
```

Make sure you've  Email and Password auth enable in your firebase console too

Closing, as this isn't an issue with firebase_auth itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by saffer4u** [comment]
Hii  **TahaTesser**
I did the same as you told me, and my email and password auth is also enabled in firebase console,
but i'm still getting this error.
```
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String email;

  String password;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firebase Retest'),
      ),
      body: Column(
        children: <Widget>[
          TextField(
            onChanged: (value) {
              setState(() {
                email = value;
              });
            },
          ),
          TextField(
            onChanged: (value) {
              setState(() {
                password = value;
              });
            },
          ),
          RaisedButton(
            child: Text('Sign Up'),
            onPressed: () {
              FirebaseAuth.instance
                  .createUserWithEmailAndPassword(
                      email: email, password: password)
                  .then((result) {
                print(result.user.email);
              });
            },
          ),
        ],
      ),
    );
  }
}

```

Everything was working fine two days before, but now this error is not going away it's happening in all my firebase auth projects.

```
I/BiChannelGoogleApi(16913): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@2b926a
D/FirebaseAuth(16913): Notifying id token listeners about user ( 0urI4ivkTwV75PHCNfhREkxKEPX2 ).
D/FirebaseAuth(16913): Notifying auth state listeners about user ( 0urI4ivkTwV75PHCNfhREkxKEPX2 ).
E/flutter (16913): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (16913): Receiver: null
E/flutter (16913): Tried calling: []("providerData")
E/flutter (16913): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (16913): #1      _decodeUser (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:422:45)
E/flutter (16913): #2      _decodeAuthResult (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:454:29)
E/flutter (16913): #3      MethodChannelFirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:68:12)
E/flutter (16913): <asynchronous suspension>
E/flutter (16913): #4      FirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth/src/firebase_auth.dart:64:10)
E/flutter (16913): #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter (16913): #6      FirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth/src/firebase_auth.dart:57:52)
E/flutter (16913): #7      _MyHomePageState.build.<anonymous closure> (package:test1/main.dart:51:20)
E/flutter (16913): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (16913): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (16913): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (16913): #11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (16913): #12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (16913): #13     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (16913): #14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (16913): #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (16913): #16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (16913): #17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (16913): #18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (16913): #19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (16913): #20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (16913): #21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (16913): #22     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (16913): #23     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (16913): #24     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (16913): #25     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (16913): #26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (16913): #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (16913): #28     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (16913): #29     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (16913): 

```
I tried almost everything to resolve this problem, i've change channel from stable to master then get back to the stable, i've updated flutter dart, Android studio and tried to make small project to resolve this problem, but now i'm stuck on this.
please help me.

**Comment by bdoubleu86** [comment]
Any update on this?
I just updated to firebase_auth: ^0.15.3 and having exactly the same issue now.
@saffer4u did you fix it?

**Comment by bdoubleu86** [comment]
Some debugging shows that it first occurs with firebase_auth 0.12.0. The version right before was fine.

**Comment by mirajago** [comment]
Same problem here

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
