### ISSUE TITLE
[Cloud Functions] App crashes when it receives HTTPS ERROR response without msg detail.

### ISSUE THREAD

**Issue by yamauchieduardo** [FirebaseExtended/flutterfire#229]
When the flutter app receive cloud-functions HTTPS error without message detail
the app crash.
```
> E/AndroidRuntime( 9345): FATAL EXCEPTION: OkHttp Dispatcher
> E/AndroidRuntime( 9345): Process: myapp.app, PID: 9345
> E/AndroidRuntime( 9345): java.lang.IllegalArgumentException: Detail message must not be empty
> E/AndroidRuntime( 9345): 	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:8)
> E/AndroidRuntime( 9345): 	at com.google.firebase.FirebaseException.<init>(Unknown Source:2)
> E/AndroidRuntime( 9345): 	at com.google.firebase.functions.FirebaseFunctionsException.<init>(com.google.firebase:firebase-functions@@17.0.0:231)
> E/AndroidRuntime( 9345): 	at com.google.firebase.functions.FirebaseFunctionsException.fromResponse(com.google.firebase:firebase-functions@@17.0.0:223)
> E/AndroidRuntime( 9345): 	at com.google.firebase.functions.FirebaseFunctions$2.onResponse(com.google.firebase:firebase-functions@@17.0.0:273)
> E/AndroidRuntime( 9345): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
> E/AndroidRuntime( 9345): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
> E/AndroidRuntime( 9345): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
> E/AndroidRuntime( 9345): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
> E/AndroidRuntime( 9345): 	at java.lang.Thread.run(Thread.java:764)
> D/EGL_emulation( 9345): eglMakeCurrent: 0xe0f86260: ver 3 1 (tinfo 0xc79dd9e0)
> W/FlutterJNI( 9345): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: flutter/textinput. Response ID: 0
> I/zygote  ( 9345): Do partial code cache collection, code=242KB, data=167KB
> I/zygote  ( 9345): After code cache collection, code=242KB, data=167KB
> I/zygote  ( 9345): Increasing code cache capacity to 1024KB
```
cloud functions version: ^0.4.1

**Comment by yamauchieduardo** [comment]
After `cloud_functions 0.6.0`  version the errors stoped.
