### ISSUE TITLE
[firebase_analytics] Sending analytics events from widgets on third tab result in Java stacktrace

### ISSUE THREAD

**Issue by elliottmb** [FirebaseExtended/flutterfire#230]
**Describe the bug**
When logging an event for a nested `ExpansionTile`'s `onExpansionChanged` contained on the third tab of a screen, a stacktrace can be seen and no event is received by analytics.

**To Reproduce**
1. Create a Screen with a three tabs, place an `ExpansionTile` within it and then another within that. 
2. On the nested most `ExpansionTile`, put a `onExpansionChanged` callback that calls `logEvent()` with an event name of `section_(expanded|collapsed)` and a string name for the section.
3. Expand and/or collapse the `ExpansionTile`.
4. The following stack trace is seen in the log 
```
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at io.flutter.plugins.firebaseanalytics.FirebaseAnalyticsPlugin.createBundleFromMap(FirebaseAnalyticsPlugin.java:140)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at io.flutter.plugins.firebaseanalytics.FirebaseAnalyticsPlugin.handleLogEvent(FirebaseAnalyticsPlugin.java:69)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at io.flutter.plugins.firebaseanalytics.FirebaseAnalyticsPlugin.onMethodCall(FirebaseAnalyticsPlugin.java:39)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#plugins.flutter.io/firebase_analytics(28128): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/flutter (28128): PlatformException(error, Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference, null)
```

**Expected behavior**
For the stacktrace to not have occurred in the underlying platform code and the analytics event to be sent.

**Additional context**
Problem does not occur if on the first tab. We're using a `DefaultTabController(length: 3, ...)`, `TabBar` and `TabBarView` when building the screen.

Version of the package we're using is `5.0.2`

**Comment by Ehesp** [comment]
Please try upgrading to the latest version of the plugin.

Closing due to inactivity. If this is still a problem, please create a new issue following the issue template with code reproduction.

Thanks
