### ISSUE TITLE
[firebase_storage] NullPointerException

### ISSUE THREAD

**Issue by cmkweber** [FirebaseExtended/flutterfire#2301]
Crash submitted to Google Play Store, no reproducible.

```
Stacktrace:
java.lang.NullPointerException: 
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.b (FirebaseStoragePlugin.java:8)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.access$000 (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.access$100 (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.access$200 (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.addUploadListeners (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.buildMapFromMetadata (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.buildMapFromTaskEvent (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.buildMapFromTaskSnapshot (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.buildMetadataFromMap (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.cancelUploadTask (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.ensureMimeType (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.getMimeType (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.onAttachedToEngine (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin$15.a (FirebaseStoragePlugin.java:7)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin$15.a (FirebaseStoragePlugin.java:2)
  at com.google.firebase.storage.StorageTask$$Lambda$5.a (StorageTask.java:4)
  at com.google.firebase.storage.TaskListenerImpl.lambda$onInternalStateChanged$2 (TaskListenerImpl.java:2)
  at com.google.firebase.storage.TaskListenerImpl$$Lambda$3.run (TaskListenerImpl.java:6)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7356)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:930)```


Flutter doctor:
[√] Flutter (Channel master, v1.16.4-pre.69, on Microsoft Windows [Version 10.0.18362.720], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code, 64-bit edition (version 1.43.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by Ehesp** [comment]
Please can you share some code of what storage code you're using in the app.

> no reproducible.

If you're getting this issue, it has to be reproducible. Please help debug so we can find the problem.

**Comment by cmkweber** [comment]
@Ehesp - Unfortunately I don't have a reproducible, this crash occurred in the wild and I received it through Google Plays console. It occurred on this device: Google Pixel 4 (flame), 5632MB RAM, Android 10

I have uploaded deobfuscation to Play now so if it happens again we should hopefully have more info.

But I will say, judging from the stack trace it looks like its straight-line through java during when it attaches to the engine, so I'm not sure a dart reproducible will be helpful here, but that's just a guess.

When I collect more info I will post it.

**Comment by cmkweber** [comment]
This crash is occurring on a few different android devices now. The proguard deobfucation didn't seem to elaborate further on the previous stack trace as this appears the same, firebase did catch it this time although it's stack trace doesn't look any more descriptive...

```
Additional Play stacktrace:

java.lang.NullPointerException: 
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.b (FirebaseStoragePlugin.java:8)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.access$000 (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.access$100 (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.access$200 (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.addUploadListeners (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.buildMapFromMetadata (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.buildMapFromTaskEvent (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.buildMapFromTaskSnapshot (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.buildMetadataFromMap (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.cancelUploadTask (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.ensureMimeType (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.getMimeType (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.onAttachedToEngine (FirebaseStoragePlugin.java)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin$15.a (FirebaseStoragePlugin.java:7)
  at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin$15.a (FirebaseStoragePlugin.java:2)
  at com.google.firebase.storage.StorageTask$$Lambda$5.a (StorageTask.java:4)
  at com.google.firebase.storage.TaskListenerImpl.lambda$onInternalStateChanged$2 (TaskListenerImpl.java:2)
  at com.google.firebase.storage.TaskListenerImpl$$Lambda$3.run (TaskListenerImpl.java:6)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8016)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)

Crashlytics:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void d.b.b.a.j.a(java.lang.String, java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.storage.a.b(:8)
       at io.flutter.plugins.firebase.storage.a.a()
       at io.flutter.plugins.firebase.storage.a$f.a(:7)
       at io.flutter.plugins.firebase.storage.a$f.a(:2)
       at com.google.firebase.storage.a0.a(:4)
       at com.google.firebase.storage.m0.b(:2)
       at com.google.firebase.storage.l0.run(:6)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8016)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)```

**Comment by noelmansour** [comment]
I've hit this issue as well.

It happens if leaving the app while an upload is happening.

Here are a set of reproducible steps:

Using the code below:
1. Tap on the button to begin the upload
2. Before the upload is complete, i.e. before "done upload" prints, hit the android back button
3. Observe crash

Relevant dependencies from pubspec.yaml:
```yaml
  firebase_core: ^0.4.5
  firebase_storage: ^3.1.6
```

main.dart:
```dart
import 'dart:convert';

import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Storage Repro',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: StorageReproWidget(),
    );
  }
}

class StorageReproWidget extends StatefulWidget {
  @override
  _StorageReproWidgetState createState() => _StorageReproWidgetState();
}

class _StorageReproWidgetState extends State<StorageReproWidget> {
  final FirebaseStorage _storage = FirebaseStorage.instance;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: new AppBar(
        title: new Text('Repro'),
      ),
      body: Center(
        child: OutlineButton(
          child: Text('Upload data'),
          onPressed: () async {
            print('starting upload');
            await _storage
                .ref()
                .child('temp.txt')
                .putData(utf8
                    .encode(List<String>.generate(5 * 1024, (_) => 'a').join()))
                .onComplete;
            print('done upload');
          },
        ),
      ),
    );
  }
}
```

Here's the unobfuscated stacktrace:
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
        at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.invokeStorageTaskEvent(FirebaseStoragePlugin.java:485)
        at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.access$100(FirebaseStoragePlugin.java:39)
        at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin$15.onProgress(FirebaseStoragePlugin.java:441)
        at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin$15.onProgress(FirebaseStoragePlugin.java:438)
        at com.google.firebase.storage.StorageTask$$Lambda$5.raise(Unknown Source:4)
        at com.google.firebase.storage.TaskListenerImpl.lambda$onInternalStateChanged$2(com.google.firebase:firebase-storage@@17.0.0:94)
        at com.google.firebase.storage.TaskListenerImpl$$Lambda$3.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
