### ISSUE TITLE
[cloud_firestore_web] Crashes on load when not using default firebase app

### ISSUE THREAD

**Issue by buntagonalprism** [FirebaseExtended/flutterfire#2375]
**Description**
The Readme for cloud firestore, and other FlutterFire plugins that support the web, indicate that you can either setup the FirebaseApp in `index.html`, or in Dart using `package:firebase_core` methods. 

However, `cloud_firestore_web` crashes on application load when a default app has not been initialised in index.html. From what I can see, this is because the implementation of `cloud_firestore_web` tries to access the default firebase app when it is constructed as part of plugin registration. Since web plugin registration runs before the `main()` function of the Flutter app this means there is no chance to register a firebase app before the crash occurs. 

The specific use case in which I encountered this issue was using different firebase projects for dev/test/production environments. Each environment has its own main.dart that supplies the Firebase settings. This works fine when used with `firebase_auth_web` for example.  

**To Reproduce**
1. See [modified example project here](https://github.com/buntagonalprism/flutterfire/tree/firestore-web-default-app-issue/packages/cloud_firestore/cloud_firestore/example) from the cloud firestore packag , with only change made being to comment-out the firebaseApp initialization in index.html. The FirebaseApp configuration in main.dart is still present. 
2. Run the example app for web `flutter run -d chrome`. 
3. App fails to load with the following error:

```
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at Object.p [as app] (https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js:1:10100)
    at Object.app$ [as app] (http://localhost:56586/packages/firebase/src/top_level.dart.lib.js:72:56)
    at new cloud_firestore_web.FirestoreWeb.new (http://localhost:56586/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:793:57)
    at Function.registerWith (http://localhost:56586/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:738:71)
    at Object.registerPlugins (http://localhost:56586/packages/firestore_example/generated_plugin_registrant.dart.lib.js:13:38)
    at main$ (http://localhost:56586/web_entrypoint.dart.lib.js:15:35)
    at main$.next (<anonymous>)
    at runBody (http://localhost:56586/dart_sdk.js:43121:34)
    at Object._async [as async] (http://localhost:56586/dart_sdk.js:43149:7)
    at main$ (http://localhost:56586/web_entrypoint.dart.lib.js:14:18)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:56586/dwds/src/injected/client.js:8319:15)
    at http://localhost:56586/dwds/src/injected/client.js:22326:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56586/dwds/src/injected/client.js:3636:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:56586/dwds/src/injected/client.js:10827:12)
    at Object._asyncStartSync (http://localhost:56586/dwds/src/injected/client.js:3600:20)
    at main__closure1.$call$body$main__closure (http://localhost:56586/dwds/src/injected/client.js:22338:16)
    at main__closure1.call$1 (http://localhost:56586/dwds/src/injected/client.js:22270:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:56586/dwds/src/injected/client.js:3958:16)
    at _CustomZone.runUnary$2$2 (http://localhost:56586/dwds/src/injected/client.js:12137:125)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:56586/dwds/src/injected/client.js:12065:14)
    at _ControllerSubscription._sendData$1 (http://localhost:56586/dwds/src/injected/client.js:11621:19)
    at _DelayedData.perform$1 (http://localhost:56586/dwds/src/injected/client.js:11775:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:56586/dwds/src/injected/client.js:11824:14)
    at Object._microtaskLoop (http://localhost:56586/dwds/src/injected/client.js:3801:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:56586/dwds/src/injected/client.js:3807:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:56586/dwds/src/injected/client.js:10699:9)
    at invokeClosure (http://localhost:56586/dwds/src/injected/client.js:1172:26)
    at MutationObserver.<anonymous> (http://localhost:56586/dwds/src/injected/client.js:1191:18)
```

**Expected behavior**

**Additional context**
<details>
<summary>Flutter Doctor</summary>

```
[√] Flutter (Channel dev, v1.18.0-dev.5.0, on Microsoft Windows [Version 10.0.18362.778], locale en-AU)
    • Flutter version 1.18.0-dev.5.0 at C:\flutter
    • Framework revision 7f56b53de4 (3 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\t\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\t\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 8.0.0 (API 26) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.163
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
```

</details>

<details>
<summary>Flutter run -v</summary>

```
flutter run -d chrome -v
[  +27 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +86 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 7f56b53de4e5da2147c4d30d857a72c6f2e4f42f
[        ] executing: [C:\flutter/] git describe --match *.*.* --first-parent --long --tags
[  +66 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.18.0-dev.5.0-0-g7f56b53de
[  +11 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +68 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +98 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +52 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[  +67 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +19 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] executing: C:\Users\t\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +46 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[   +9 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +85 ms] Found plugin cloud_firestore at C:\git\flutterfire-buntagonalprism\packages\cloud_firestore\cloud_firestore\
[   +9 ms] Found plugin cloud_firestore_web at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[  +24 ms] Found plugin e2e at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\e2e-0.2.4+4\
[   +8 ms] Found plugin firebase_core at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[  +22 ms] Found plugin firebase_core_web at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[ +117 ms] Found plugin cloud_firestore at C:\git\flutterfire-buntagonalprism\packages\cloud_firestore\cloud_firestore\
[   +4 ms] Found plugin cloud_firestore_web at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[  +30 ms] Found plugin e2e at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\e2e-0.2.4+4\
[   +3 ms] Found plugin firebase_core at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +4 ms] Found plugin firebase_core_web at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[ +110 ms] Generating C:\git\flutterfire-buntagonalprism\packages\cloud_firestore\cloud_firestore\example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +101 ms] Launching lib\main.dart on Chrome in debug mode...
[  +96 ms] Updating assets
[ +132 ms] Syncing files to device Chrome...
[   +9 ms] Found plugin cloud_firestore at C:\git\flutterfire-buntagonalprism\packages\cloud_firestore\cloud_firestore\
[  +20 ms] Found plugin cloud_firestore_web at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[   +4 ms] Found plugin e2e at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\e2e-0.2.4+4\
[   +2 ms] Found plugin firebase_core at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +1 ms] Found plugin firebase_core_web at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +36 ms] Found plugin cloud_firestore at C:\git\flutterfire-buntagonalprism\packages\cloud_firestore\cloud_firestore\
[   +2 ms] Found plugin cloud_firestore_web at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[  +27 ms] Found plugin e2e at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\e2e-0.2.4+4\
[   +2 ms] Found plugin firebase_core at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[  +28 ms] Found plugin firebase_core_web at C:\Users\t\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +36 ms] Generating C:\git\flutterfire-buntagonalprism\packages\cloud_firestore\cloud_firestore\example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +40 ms] <- reset
[  +31 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\t\AppData\Local\Temp\flutter_tool.edbd8d13-7f8c-11ea-8169-bc5ff4756d18\app.dill --libraries-spec file:///C:/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
C:\git\flutterfire-buntagonalprism\packages\cloud_firestore\cloud_firestore\example\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
C:\Users\t\AppData\Local\Temp\flutter_tools.edbd8d14-7f8c-11ea-8169-bc5ff4756d18 --filesystem-scheme org-dartlang-app --initialize-from-dill build\cache.dill --platform file:///C:/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +31 ms] <- compile org-dartlang-app:///web_entrypoint.dart
[+20174 ms] Syncing files to device Chrome... (completed in 20,440ms, longer than expected)
[   +3 ms] Synced 22.8MB.
[   +1 ms] <- accept
[ +266 ms] [CHROME]:
[   +2 ms] [CHROME]:DevTools listening on ws://127.0.0.1:56986/devtools/browser/6ec2c261-79ea-4175-b9b2-c9ce28a41b11
[+6844 ms] Debug service listening on ws://127.0.0.1:57027/K-sKMrN7qg4=

[ +359 ms] Debug service listening on ws://127.0.0.1:57027/K-sKMrN7qg4=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[   +1 ms] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[   +2 ms]   To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[  +44 ms] For a more detailed help message, press "h". To quit, press "q".
[  +86 ms] FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
               at Object.p [as app] (https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js:1:10100)
               at Object.app$ [as app] (http://localhost:56952/packages/firebase/src/top_level.dart.lib.js:72:56)
               at new cloud_firestore_web.FirestoreWeb.new (http://localhost:56952/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:793:57)
               at Function.registerWith (http://localhost:56952/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:738:71)
               at Object.registerPlugins (http://localhost:56952/packages/firestore_example/generated_plugin_registrant.dart.lib.js:13:38)
               at main$ (http://localhost:56952/web_entrypoint.dart.lib.js:15:35)
               at main$.next (<anonymous>)
               at runBody (http://localhost:56952/dart_sdk.js:43121:34)
               at Object._async [as async] (http://localhost:56952/dart_sdk.js:43149:7)
               at main$ (http://localhost:56952/web_entrypoint.dart.lib.js:14:18)
               at <anonymous>:1:8
               at Object.runMain (http://localhost:56952/dwds/src/injected/client.js:8319:15)
               at http://localhost:56952/dwds/src/injected/client.js:22326:19
               at _wrapJsFunctionForAsync_closure.$protected (http://localhost:56952/dwds/src/injected/client.js:3636:15)
               at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:56952/dwds/src/injected/client.js:10827:12)
               at Object._asyncStartSync (http://localhost:56952/dwds/src/injected/client.js:3600:20)
               at main__closure1.$call$body$main__closure (http://localhost:56952/dwds/src/injected/client.js:22338:16)
               at main__closure1.call$1 (http://localhost:56952/dwds/src/injected/client.js:22270:19)
               at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:56952/dwds/src/injected/client.js:3958:16)
               at _CustomZone.runUnary$2$2 (http://localhost:56952/dwds/src/injected/client.js:12137:125)
               at _CustomZone.runUnaryGuarded$1$2 (http://localhost:56952/dwds/src/injected/client.js:12065:14)
               at _ControllerSubscription._sendData$1 (http://localhost:56952/dwds/src/injected/client.js:11621:19)
               at _DelayedData.perform$1 (http://localhost:56952/dwds/src/injected/client.js:11775:59)
               at _PendingEvents_schedule_closure.call$0 (http://localhost:56952/dwds/src/injected/client.js:11824:14)
               at Object._microtaskLoop (http://localhost:56952/dwds/src/injected/client.js:3801:21)
               at StaticClosure._startMicrotaskLoop (http://localhost:56952/dwds/src/injected/client.js:3807:11)
               at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:56952/dwds/src/injected/client.js:10699:9)
               at invokeClosure (http://localhost:56952/dwds/src/injected/client.js:1172:26)
               at MutationObserver.<anonymous> (http://localhost:56952/dwds/src/injected/client.js:1191:18)
```

</details>

**Comment by Salakar** [comment]
Hey, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you
