### ISSUE TITLE
[firebase_analytics] logEvent throws exception on Android if parameters are not strings

### ISSUE THREAD

**Issue by orestesgaolin** [FirebaseExtended/flutterfire#2469]
**Describe the bug**
When I call analytics.logEvent(...) and pass Map<String, dynamic> of parameters then the following exception is thrown if at least one of the map values is not String.

`Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference`

**To Reproduce**
1. Use firebase_analytics (version ^5.0.11)
2. Log new event by calling:

```dart
    analytics.logEvent(
      name: 'test',
      parameters: {
        'test': null,
        'test2': 1,
        'test3': SomeEnum.value,
      },
    );
```

3. See exception thrown from plugin in `StandardMethodCodec.decodeEnvelope` `Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference`
4. Wrap all values in the parameters map with String interpolation

```dart
    _analytics.logEvent(
      name: 'test',
      parameters: {
        'test': '${null}',
        'test1': '${1}',
        'test2': '${SomeEnum.value}',
      },
    );
```
5. The event is logged properly

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.15.4 19E287, locale pl-PL)
    • Flutter version 1.17.0-3.2.pre at /Users/dominik/fvm/versions/beta
    • Framework revision 2a7bc389f2 (8 days ago), 2020-04-21 20:34:20 -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dominik/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/dominik/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (4 available)
    • SM G950F         • ce031713b404900c0d                       • android-arm64  • Android 9 (API 28)
    • iPhone (Dominik) • f96e187ec1f51b6be1830c7965a482dc653765d2 • ios            • iOS 13.4
    • Chrome           • chrome                                   • web-javascript • Google Chrome 81.0.4044.129
    • Web Server       • web-server                               • web-javascript • Flutter Tools

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @orestesgaolin 
can you please provide your  `flutter run --verbose`? 
Thank you

**Comment by orestesgaolin** [comment]
Please find verbose log from Android below:

```
[   +7 ms] I/flutter (26197): [filterReceiptsByTimeRange] Filtering by date range TimeRangeFilterState(timeRange: TimeRange.monthly, rangeFrom:
2020-05-01 00:00:00.000, rangeTo: 2020-05-19 23:59:59.999)
[   +6 ms] I/flutter (26197): PlatformException(error, Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null
object reference, null)
[   +4 ms] I/flutter (26197): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] I/flutter (26197): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
[        ] I/flutter (26197): <asynchronous suspension>
[        ] I/flutter (26197): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
[        ] I/flutter (26197): #3      FirebaseAnalytics.logEvent (package:firebase_analytics/firebase_analytics.dart:48:20)
[        ] I/flutter (26197): #4      Analytics.setFilters (package:app/features/analytics/analytics.dart:48:16)
[        ] I/flutter (26197): #5      PersistentFiltersRepository.setFilter
(package:app/features/filters/repository/filters_repository.dart:78:15)
[        ] I/flutter (26197): <asynchronous suspension>
[        ] I/flutter (26197): #6      FilterBloc._mapToggleRecurringToState (package:app/features/filters/bloc/filter_bloc.dart:81:25)
[        ] I/flutter (26197): #7      _AsyncStarStreamController.runBody (dart:async-patch/async_patch.dart:162:18)
[        ] I/flutter (26197): #8      _rootRun (dart:async/zone.dart:1180:38)
[        ] I/flutter (26197): #9      _CustomZone.run (dart:async/zone.dart:1077:19)
[        ] I/flutter (26197): #10     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[        ] I/flutter (26197): #11     _CustomZone.bindCallbac
[  +12 ms] E/mainCommon(26197): [Exception PlatformException] [PlatformException(error, Attempt to invoke virtual method 'java.lang.Class
java.lang.Object.getClass()' on a null object reference, null)] | [null] | package:flutter/src/services/message_codecs.dart 569:7
StandardMethodCodec.decodeEnvelope
[        ] E/mainCommon(26197): package:flutter/src/services/platform_channel.dart 156:18              MethodChannel._invokeMethod
[        ] E/mainCommon(26197): package:flutter/src/services/platform_channel.dart 329:12              MethodChannel.invokeMethod
[        ] E/mainCommon(26197): package:firebase_analytics/firebase_analytics.dart 48:20               FirebaseAnalytics.logEvent
[        ] E/mainCommon(26197): package:app/features/analytics/analytics.dart 48:16                    Analytics.setFilters
[        ] E/mainCommon(26197): package:app/features/filters/repository/filters_repository.dart 78:15  PersistentFiltersRepository.setFilter
[        ] E/mainCommon(26197): package:app/features/filters/bloc/filter_bloc.dart 81:25               FilterBloc._mapToggleRecurringToState
[        ] I/flutter (26197): Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
[        ] I/flutter (26197): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] I/flutter (26197): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
[        ] I/flutter (26197): <asynchronous suspension>
[        ] I/flutter (26197): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
[        ] I/flutter (26197): #3      FirebaseAnalytics.logEvent (package:firebase_analytics/firebase_analytics.dart:48:20)
[        ] I/flutter (26197): #4      Analytics.setFilters (package:app/features/analytics/analytics.dart:48:16)
[        ] I/flutter (26197): #5      PersistentFiltersRepository.setFilter
(package:app/features/filters/repository/filters_repository.dart:78:15)
[        ] I/flutter (26197): <asynchronous suspension>
[        ] I/flutter (26197): #6      FilterBloc._mapToggleRecurringToState (package:app/features/filters/bloc/filter_bloc.dart:81:25)
[        ] I/flutter (26197): #7      _AsyncStarStreamController.runBody (dart:async-patch/async_patch.dart:162:18)
[        ] I/flutter (26197): #8      _rootRun (dart:async/zone.dart:1180:38)
[        ] I/flutter (26197): #9      _CustomZone.run (dart:async/zone.dart:1077:19)
[        ] I/flutter (26197): #10     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[        ] I/flutter (26197): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
[        ] I/flutter (26197): #12     _rootRun (dart:async/zone.dart:1184:13)
[        ] I/flutter (26197): #13     _CustomZone.run (dart:async/zone.dart:1077:19)
[        ] I/flutter (26197): #14     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[        ] I/flutter (26197): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
[        ] I/flutter (26197): #16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[        ] I/flutter (26197): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[        ] I/flutter (26197):
[        ] I/flutter (26197): Error caught by Crashlytics plugin <recordError>:
[        ] E/Bugfender(26197): Reported issue with Title: PlatformException and Message: null | Exception: PlatformException(error, Attempt to
invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference, null) | Stacktrace:
package:flutter/src/services/message_codecs.dart 569:7                 StandardMethodCodec.decodeEnvelope
[        ] E/Bugfender(26197): package:flutter/src/services/platform_channel.dart 156:18              MethodChannel._invokeMethod
[        ] E/Bugfender(26197): package:flutter/src/services/platform_channel.dart 329:12              MethodChannel.invokeMethod
[        ] E/Bugfender(26197): package:firebase_analytics/firebase_analytics.dart 48:20               FirebaseAnalytics.logEvent
[        ] E/Bugfender(26197): package:app/features/analytics/analytics.dart 48:16                    Analytics.setFilters
[        ] E/Bugfender(26197): package:app/features/filters/repository/filters_repository.dart 78:15  PersistentFiltersRepository.setFilter
[        ] E/Bugfender(26197): package:app/features/filters/bloc/filter_bloc.dart 81:25               FilterBloc._mapToggleRecurringToState
[        ] I/Bugfender(26197): Synchronizing all the logs and issues
[  +33 ms] I/System.out(26197): (HTTPLog)-Static: isSBSettingEnabled false
[        ] I/System.out(26197): (HTTPLog)-Static: isSBSettingEnabled false
[   +7 ms] V/NativeCrypto(26197): SSL shutdown failed: ssl=0x77ad3c8388: I/O error during system call, Broken pipe
[  +55 ms] I/flutter (26197): firebase_crashlytics: Error reported to Crashlytics.
```

In this case the event logged looked like follows:

```dart
    _analytics.logEvent(
      name: 'test',
      parameters: {
        'test': null,
        'test2': 1,
        'test4': 1.2,
        'test3': true,
      },
    );
```

**Comment by Choem** [comment]
I've got the same issue with multiple events. Anyone has a workaround or updates regarding this bug?

**Comment by russellwheatley** [comment]
This has been resolved https://github.com/FirebaseExtended/flutterfire/pull/5563.
