### ISSUE TITLE
FirebaseDatabase Cannot interact with realtime database

### ISSUE THREAD

**Issue by camstar915** [FirebaseExtended/flutterfire#2477]
Cannot find a way to get access to my FirebaseDatabase using FirebaseDatabase.instance.
Connecting with Firebase and setting up FirebaseAuth was a breeze, but I've spent an entire day trying to get this to work... PLEASEEE help :(

**To Reproduce**
I've connected my app to Firebase and used FirebaseAuth successfully registering/signing in users, so I assume a connection exists.
I copied and pasted the example https://pub.dev/packages/firebase_database#-example-tab- both with directly configuring the database and using FirebaseDatabase.instance.reference().child('counter') with no luck on either.

I added dummy data directly to my database in the Firebase console that I assume the example code I linked above would be able to access

```
[PROJECT-NAME]
    counter: 2
    messages: 
        1: "test"
```

**Expected behavior**
Expecting the example code to be able to increment the counter and for the increment to be reflected in the database

**Additional context**
Debug Console is displaying this error:
```
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at io.flutter.plugins.firebase.database.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:275)
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#plugins.flutter.io/firebase_database( 2462): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
D/NetworkSecurityConfig( 2462): No Network Security Config specified, using platform default
E/flutter ( 2462): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.Integer cannot be cast to java.lang.Long, null)
E/flutter ( 2462): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter ( 2462): #1      MethodChannel.invokeMethod 
E/flutter ( 2462): <asynchronous suspension>
E/flutter ( 2462): #2      FirebaseDatabase.setPersistenceCacheSizeBytes 
package:firebase_database/src/firebase_database.dart:120
E/flutter ( 2462): #3      _ChatScreenState.initState 
package:safts/screens/chat_screen.dart:43
E/flutter ( 2462): #4      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4355
E/flutter ( 2462): #5      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4201
E/flutter ( 2462): #6      Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter ( 2462): #7      Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter ( 2462): #8      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4243
E/flutter ( 2462): #9      Element.rebuild 
package:flutter/…/widgets/framework.dart:3947
E/flutter ( 2462): #10     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4206
E/flutter ( 2462): #11     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4201
E/flutter ( 2462): #12     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter ( 2462): #13     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter ( 2462): #14     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4243
E/flutter ( 2462): #15     Element.rebuild 
package:flutter/…/widgets/framework.dart:3947
E/flutter ( 2462): #16     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4206
E/flutter ( 2462): #17     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4201
E/flutter ( 2462): #18     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter ( 2462): #19     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter ( 2462): #20     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4243
E/flutter ( 2462): #21     Element.rebuild 
package:flutter/…/widgets/framework.dart:3947
E/flutter ( 2462): #22     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4206
E/flutter ( 2462): #23     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4201
E/flutter ( 2462): #24     ParentDataElement.mount 
package:flutter/…/widgets/framework.dart:4617
E/flutter ( 2462): #25     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter ( 2462): #26     MultiChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5551
E/flutter ( 2462): #27     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter ( 2462): #28     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter ( 2462): #29     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4243
E/flutter ( 2462): #30     Element.rebuild 
package:flutter/…/widgets/framework.dart:3947
E/flutter ( 2462): #31     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4206
E/flutter ( 2462): #32     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4381
E/flutter ( 2462): #33     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4201
E/flutter ( 2462): #34     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter ( 2462): #35     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter ( 2462): #36     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4243
E/flutter ( 2462): #37     Element.rebuild 
package:flutter/…/widgets/framework.dart:3947
E/flutter ( 2462): #38     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4206
E/flutter ( 2462): #39     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4201
E/flutter ( 2462): #40     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3194
E/flutter ( 2462): #41     Element.updateChild 
package:flutter/…/widgets/framework.dart:2988
E/flutter ( 2462): #42     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4243
E/flutter ( 2462): #43     Element.rebuild 
package:flutter/…/widgets/framework.dart:3947
E/flutter ( 2462): #44     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:4206
E/flutter ( 2462): #45     StatefulE
```

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18362.778], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.44.2)
[√] Connected device (1 available)

• No issues found!
```

**Comment by camstar915** [comment]
Disregard this issue...
Apparently was something with the wifi.
Turned wifi off and it fired up and worked.
-_-
