### ISSUE TITLE
[cloud_functions] (Android) Cannot invoke callable with a String

### ISSUE THREAD

**Issue by yzhan94** [FirebaseExtended/flutterfire#2492]
**Describe the bug**
`HttpsCallable#call` does not work with a String parameter, throwing the following error:
```
 java.lang.String cannot be cast to java.util.Map
```

**To Reproduce**
1. Create a sample callable and call the function with a String parameter:
```dart
final HttpsCallable callable = CloudFunctions.instance.getHttpsCallable(
    functionName: 'YOUR_CALLABLE_FUNCTION_NAME',
);
dynamic resp = await callable.call('YOUR_PARAMETER_VALUE');
```
2. Compile and run

**Expected behavior**
The cloud function should be called.

**Additional context**
I have only tried it on Android, and have not tested it in iOS.
Following the source code, I have determined the source of the issue to be in the Plugin implementation:
```dart
Map<String, Object> parameters = call.argument("parameters");
```
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/cloud_functions/android/src/main/java/io/flutter/plugins/firebase/cloudfunctions/CloudFunctionsPlugin.java#L38

**Comment by TahaTesser** [comment]
Hi @yzhan94 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Thank you

**Comment by yzhan94** [comment]
Hi, sorry for the delay.
Here's the result of `flutter doctor -v`
```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [VersiÃ³n 10.0.18363.836], locale es-ES)
    • Flutter version 1.12.13+hotfix.9 at E:\projects\flutter\flutter
    • Framework revision f139b11009 (6 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Yzhan\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.
```

And the error stack with `--verbose` option
```
[+4727 ms] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565): Failed to handle method call
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at io.flutter.plugins.firebase.cloudfunctions.CloudFunctionsPlugin.onMethodCall(CloudFunctionsPlugin.java:38)
[   +1 ms] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at android.os.MessageQueue.next(MessageQueue.java:336)
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at android.os.Looper.loop(Looper.java:174)
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at android.app.ActivityThread.main(ActivityThread.java:7356)
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[        ] E/MethodChannel#plugins.flutter.io/cloud_functions( 7565):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[   +2 ms] E/flutter ( 7565): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.String cannot be cast to java.util.Map, null)
[        ] E/flutter ( 7565): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] E/flutter ( 7565): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
[        ] E/flutter ( 7565): <asynchronous suspension>
[        ] E/flutter ( 7565): #2      MethodChannelCloudFunctions.callCloudFunction (package:cloud_functions_platform_interface/src/method_channel_cloud_functions.dart:43:15)
[        ] E/flutter ( 7565): #3      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:33:12)
[        ] E/flutter ( 7565): #4      _MyHomePageState._callFunction (package:hellocloudfunctions/main.dart:55:47)
[        ] E/flutter ( 7565): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
[        ] E/flutter ( 7565): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
[        ] E/flutter ( 7565): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] E/flutter ( 7565): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
[        ] E/flutter ( 7565): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
[        ] E/flutter ( 7565): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
[        ] E/flutter ( 7565): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
[        ] E/flutter ( 7565): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
[        ] E/flutter ( 7565): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
[        ] E/flutter ( 7565): #14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
[        ] E/flutter ( 7565): #15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
[        ] E/flutter ( 7565): #16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
[        ] E/flutter ( 7565): #17     _rootRunUnary (dart:async/zone.dart:1138:13)
[        ] E/flutter ( 7565): #18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] E/flutter ( 7565): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
[        ] E/flutter ( 7565): #20     _invoke1 (dart:ui/hooks.dart:273:10)
[        ] E/flutter ( 7565): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
[        ] E/flutter ( 7565):
```

**Comment by TahaTesser** [comment]
<details> 
<summary>Code Sample</summary> 

``` 
import 'package:cloud_functions/cloud_functions.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  final HttpsCallable callable = CloudFunctions.instance.getHttpsCallable(
    functionName: 'YOUR_CALLABLE_FUNCTION_NAME',
  );
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          dynamic resp = await callable.call('YOUR_PARAMETER_VALUE');
        },
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>logs</summary> 

``` 
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at io.flutter.plugins.firebase.cloudfunctions.CloudFunctionsPlugin.onMethodCall(CloudFunctionsPlugin.java:38)
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#plugins.flutter.io/cloud_functions( 7932): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 7932): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, java.lang.String cannot be cast to java.util.Map, null)
[38;5;244mE/flutter ( 7932): #0      StandardMethodCodec.decodeEnvelope[39;49m
[38;5;244mE/flutter ( 7932): #1      MethodChannel._invokeMethod[39;49m
E/flutter ( 7932): <asynchronous suspension>
[38;5;244mE/flutter ( 7932): #2      MethodChannel.invokeMethod[39;49m
[38;5;248mE/flutter ( 7932): #3      MethodChannelCloudFunctions.callCloudFunction[39;49m
[38;5;248mE/flutter ( 7932): #4      HttpsCallable.call[39;49m
[38;5;248mE/flutter ( 7932): #5      Home.build.<anonymous closure>[39;49m
[38;5;244mE/flutter ( 7932): #6      _InkResponseState._handleTap[39;49m
[38;5;244mE/flutter ( 7932): #7      _InkResponseState.build.<anonymous closure>[39;49m
[38;5;244mE/flutter ( 7932): #8      GestureRecognizer.invokeCallback[39;49m
[38;5;244mE/flutter ( 7932): #9      TapGestureRecognizer.handleTapUp[39;49m
[38;5;244mE/flutter ( 7932): #10     BaseTapGestureRecognizer._checkUp[39;49m
[38;5;244mE/flutter ( 7932): #11     BaseTapGestureRecognizer.handlePrimaryPointer[39;49m
[38;5;244mE/flutter ( 7932): #12     PrimaryPointerGestureRecognizer.handleEvent[39;49m
[38;5;244mE/flutter ( 7932): #13     PointerRouter._dispatch[39;49m
[38;5;244mE/flutter ( 7932): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure>[39;49m
[38;5;244mE/flutter ( 7932): #15     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)[39;49m
[38;5;244mE/flutter ( 7932): #16     PointerRouter._dispatchEventToRoutes[39;49m
[38;5;244mE/flutter ( 7932): #17     PointerRouter.route[39;49m
[38;5;244mE/flutter ( 7932): #18     GestureBinding.handleEvent[39;49m
[38;5;244mE/flutter ( 7932): #19     GestureBinding.dispatchEvent[39;49m
[38;5;244mE/flutter ( 7932): #20     GestureBinding._handlePointerEvent[39;49m
[38;5;244mE/flutter ( 7932): #21     GestureBinding._flushPointerEventQueue[39;49m
[38;5;244mE/flutter ( 7932): #22     GestureBinding._handlePointerDataPacket[39;49m
[38;5;244mE/flutter ( 7932): #23     _rootRunUnary  (dart:async/zone.dart:1206:13)[39;49m
[38;5;244mE/flutter ( 7932): #24     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)[39;49m
[38;5;244mE/flutter ( 7932): #25     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)[39;49m
[38;5;244mE/flutter ( 7932): #26     _invoke1  (dart:ui/hooks.dart:291:10)[39;49m
[38;5;244mE/flutter ( 7932): #27     _dispatchPointerDataPacket  (dart:ui/hooks.dart:200:5)[39;49m
E/flutter ( 7932):

``` 

</details>

**Comment by kamaleshbasu** [comment]
Same issue with any payload type other than:
`Map<String, dynamic>`

**Comment by Thanzex** [comment]
I too have this problem. I'd rather solve this here than rewriting many Cloud Functions.
`parameters` can be anything really, could it simply be declared as `dynamic` instead of `Map<String, Object>`?

**Comment by kamaleshbasu** [comment]
I am pretty sure it's unintended. But until it is fixed, I don't see any way around rewriting cloud functions.

**Comment by russellwheatley** [comment]
This has been fixed now.
