### ISSUE TITLE
[firebase_messaging] Unhandled Exception: PlatformException

### ISSUE THREAD

**Issue by ali-thowfeek** [FirebaseExtended/flutterfire#251]
**Describe the bug**
I was testing in iOS and even though I'm receiving the token, and `onIosSettingsRegistered` callback runs and prints `flutter: Settings registered: PushNotificationSettings {sound: true, alert: true, badge: true}` Both subscribe to topic and send directly to token doesn't work. 

when subscribing to topic:
```
5.20.0 - [Firebase/Messaging][I-FCM004001] Failed to subscribe to topic Error Domain=com.google.fcm Code=0 "(null)"
```

when i send directly to token using postman, this is the response i get:
```
{
    "multicast_id": <id>,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "NotRegistered"
        }
    ]
}
```
**Steps to reproduce**
After playing around a bit, i found that this happens:
1. when you `run` the app for the first time.
2. And then `stop` the app from the ide OR kill the app on the device
3. `Run` the app again via the ide

The stack trace can be found below

**Work around**
uninstalling the app from the device and then running fresh installation via the ide does the trick for now.

**Additional context**
full stack trace:
```
flutter: Settings registered: PushNotificationSettings {sound: true, alert: true, badge: true}
flutter: dG.............. (I got the token successfully)
5.20.0 - [Firebase/Messaging][I-FCM004001] Failed to subscribe to topic Error Domain=com.google.fcm Code=0 "(null)"
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(Error 0, com.google.fcm, The operation couldn’t be completed. (com.google.fcm error 0.))
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      FirebaseMessaging.subscribeToTopic (package:firebase_messaging/firebase_messaging.dart:146:21)
#3      MainState.setupFireBaseCloudMessagingListeners (package:bizlog/src/ui/main/main.dart:89:24)
#4      MainState.initState (package:bizlog/src/ui/main/main.dart:32:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#31     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#35     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#56     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#68     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#71     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#75     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#79     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4910:32)
#80     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5243:17)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#82     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
#83     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#86     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#90     ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
#91     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#93     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#96     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#97     StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
#98     Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#99     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
#100    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#101    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
#102    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#105    StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#109    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
#110    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
#111    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
#112    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
#113    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
#114    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
#115    _rootRun (dart:async/zone.dart:1124:13)
#116    _CustomZone.run (dart:async/zone.dart:1021:19)
#117    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#118    _invoke (dart:ui/hooks.dart:249:10)
#119    _drawFrame (dart:ui/hooks.dart:207:3)
```

**Comment by iamprakash13** [comment]
addressing #251, try to instantiate firebase before use. use latest versions firebase , gradle.

i'm wondering that it might be similar to issue [#2438](https://github.com/firebase/firebase-ios-sdk/issues/2438)

**Comment by ali-thowfeek** [comment]
I am using the latest `firebase_messaging` and I am instantiating before use and it works just fine, but when i kill the app and run the app again from the ide the above error occurs and notifications no longer work until i uninstall and install it again.

**Comment by Salakar** [comment]
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone 🤓
