### ISSUE TITLE
[cloud_functions] TypeError: Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by VitaminTussle** [FirebaseExtended/flutterfire#2557]
**Describe the bug**
I'm trying to use Firebase cloud functions to send an HTTP request to a 3rd party email-sending API so that on form completion on my personal website, it sends me an email saying who wants to contact me and what they want to say. I've changed the web\index.html to initialize Firebase and double checked that it's initializing the right version and all my config info is correct; everything should be in order, but when I hit the submit button under my form it gives the error in the title.

**To Reproduce**
1. Create a new Flutter project
2. Add firebase_core 0.4.4+3 and cloud_functions 0.5.0 (latest versions) to pubspec.yaml 
3. Edit `web\index.html` as required by `packages\cloud_functions\cloud_functions_web\README.md`
4. Set up Flutter project to make HTTP call to Firebase cloud function

**Expected behavior**
Your cloud function is called and does what it's supposed to do (I'm supposed to get an email).

**Additional context**
`flutter run --verbose -d chrome` returns...
```
[   +8 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +53 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 456d80b9ddd74b4b5ca3b77bbfb70ab0e05d3fa8
[        ] executing: [C:\src\flutter/] git tag --contains HEAD
[ +176 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.19.0-1.0.pre
[   +8 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +31 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +28 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +59 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] dev
[  +42 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +22 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +21 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +20 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +48 ms] executing: C:\Users\deuce\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +53 ms] List of devices attached
[   +7 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +15 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[  +19 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +14 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +117 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-0.4.2+3\
[  +11 ms] Found plugin cloud_functions_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-1.1.0\
[  +11 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[  +30 ms] Found plugin firebase_core_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +28 ms] Found plugin flutter_email_sender at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-3.0.1\
[  +29 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.8\
[   +7 ms] Found plugin path_provider_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+2\
[  +46 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.7\
[   +5 ms] Found plugin url_launcher_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+5\
[  +25 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+5\
[  +50 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-0.4.2+3\
[   +5 ms] Found plugin cloud_functions_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-1.1.0\
[  +20 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[  +21 ms] Found plugin firebase_core_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +18 ms] Found plugin flutter_email_sender at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-3.0.1\
[  +15 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.8\
[   +8 ms] Found plugin path_provider_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+2\
[  +39 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.7\
[  +22 ms] Found plugin url_launcher_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+5\
[   +3 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+5\
[  +40 ms] Generating
C:\Users\deuce\OneDrive\Documents\Flutter\DLBlackDev\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistr
ant.java
[  +78 ms] Launching lib\main.dart on Chrome in debug mode...
[  +61 ms] Updating assets
[ +109 ms] Syncing files to device Chrome...
[  +15 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-0.4.2+3\
[   +3 ms] Found plugin cloud_functions_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-1.1.0\
[   +8 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[  +18 ms] Found plugin firebase_core_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +16 ms] Found plugin flutter_email_sender at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-3.0.1\
[  +20 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.8\
[  +11 ms] Found plugin path_provider_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+2\
[  +25 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.7\
[  +10 ms] Found plugin url_launcher_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+5\
[  +16 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+5\
[  +22 ms] Found plugin cloud_functions at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-0.4.2+3\
[   +9 ms] Found plugin cloud_functions_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-1.1.0\
[  +19 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[  +13 ms] Found plugin firebase_core_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[  +17 ms] Found plugin flutter_email_sender at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_email_sender-3.0.1\
[  +20 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.8\
[  +11 ms] Found plugin path_provider_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+2\
[  +23 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.7\
[  +10 ms] Found plugin url_launcher_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+5\
[  +18 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.1+5\
[  +19 ms] Generating
C:\Users\deuce\OneDrive\Documents\Flutter\DLBlackDev\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistr
ant.java
[  +83 ms] <- reset
[   +8 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill C:\Users\deuce\AppData\Local\Temp\flutter_tool.6eb01efc\app.dill
--libraries-spec file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
C:\Users\deuce\AppData\Local\Temp\flutter_tools.5c79c7bb --filesystem-scheme org-dartlang-app --initialize-from-dill
build\cache.dill.track.dill --platform file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +17 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+17599 ms] Syncing files to device Chrome... (completed in 18,033ms, longer than expected)
[   +5 ms] Synced 29.2MB.
[  +14 ms] <- accept
[ +163 ms] [CHROME]:
[   +8 ms] [CHROME]:DevTools listening on ws://127.0.0.1:65109/devtools/browser/a067a855-60e9-4dfb-a3ae-2ce85008568b
[+6434 ms] Debug service listening on ws://127.0.0.1:65159/XydGJx0nUjE=

[ +617 ms] Debug service listening on ws://127.0.0.1:65159/XydGJx0nUjE=
[   +5 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[  +14 ms] been thoroughly tested in production environments.
[  +16 ms] For more information see https://flutter.dev/web
[  +17 ms]   To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[  +15 ms] For a more detailed help message, press "h". To quit, press "q".
[ +986 ms] A null value was passed into a non-nullable parameter value
                    This will become a failure when runtime null safety is enabled.

[ +163 ms] Null is not a subtype of Future<dynamic>.
                    This will become a failure when runtime null safety is enabled.

[ +411 ms] A null value was passed into a non-nullable parameter value
                    This will become a failure when runtime null safety is enabled.

[+19203 ms] TypeError: Cannot read property 'app' of undefined
                         at Object.app$ [as app]
(http://localhost:65085/packages/firebase/src/top_level.dart.lib.js:78:56)
                         at cloud_functions_web.CloudFunctionsWeb.new.callCloudFunction
                         (http://localhost:65085/packages/cloud_functions_web/cloud_functions_web.dart.lib.js:28:27)
                         at cloud_functions.HttpsCallable.__.call
                         (http://localhost:65085/packages/cloud_functions/cloud_functions.dart.lib.js:114:83)
                         at contact_form._ContactFormState.new.sendEmail

(http://localhost:65085/packages/DLBlackDev/widgets/contact_form/contact_form.dart.lib.js:1014:30)
                         at contact_form._ContactFormState.new._save

(http://localhost:65085/packages/DLBlackDev/widgets/contact_form/contact_form.dart.lib.js:1007:16)
                         at _save.next (<anonymous>)
                         at runBody (http://localhost:65085/dart_sdk.js:36923:34)
                         at Object._async [as async] (http://localhost:65085/dart_sdk.js:36951:7)
                         at contact_form._ContactFormState.new.[_save]

(http://localhost:65085/packages/DLBlackDev/widgets/contact_form/contact_form.dart.lib.js:1001:20)
                         at
http://localhost:65085/packages/DLBlackDev/widgets/contact_form/contact_form.dart.lib.js:997:28
                         at tap.TapGestureRecognizer.new.invokeCallback
                         (http://localhost:65085/packages/flutter/src/gestures/recognizer.dart.lib.js:197:18)
                         at tap.TapGestureRecognizer.new.handleTapUp
                         (http://localhost:65085/packages/flutter/src/gestures/tap.dart.lib.js:355:40)
                         at tap.TapGestureRecognizer.new.[_checkUp]
                         (http://localhost:65085/packages/flutter/src/gestures/tap.dart.lib.js:186:12)
                         at tap.TapGestureRecognizer.new.acceptGesture
                         (http://localhost:65085/packages/flutter/src/gestures/tap.dart.lib.js:164:23)
                         at arena.GestureArenaManager.new.sweep
                         (http://localhost:65085/packages/flutter/src/gestures/arena.dart.lib.js:208:31)
                         at binding$5.WidgetsFlutterBinding.new.handleEvent
                         (http://localhost:65085/packages/flutter/src/gestures/binding.dart.lib.js:170:27)
                         at binding$5.WidgetsFlutterBinding.new.dispatchEvent
                         (http://localhost:65085/packages/flutter/src/gestures/binding.dart.lib.js:154:24)
                         at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent]
                         (http://localhost:65085/packages/flutter/src/gestures/binding.dart.lib.js:131:14)
                         at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue]
                         (http://localhost:65085/packages/flutter/src/gestures/binding.dart.lib.js:105:34)
                         at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket]
                         (http://localhost:65085/packages/flutter/src/gestures/binding.dart.lib.js:96:65)
                         at Object._invoke1 (http://localhost:65085/dart_sdk.js:166485:7)
                         at _engine.EngineWindow.new.invokeOnPointerDataPacket
(http://localhost:65085/dart_sdk.js:163617:15)
                         at _engine.PointerBinding.__.[_onPointerData] (http://localhost:65085/dart_sdk.js:143285:24)
                         at http://localhost:65085/dart_sdk.js:143637:26
                         at http://localhost:65085/dart_sdk.js:143602:16
                         at http://localhost:65085/dart_sdk.js:143374:11
[+20198 ms] TypeError: Cannot read property 'app' of undefined
                         at Object.app$ [as app]
(http://localhost:65085/packages/firebase/src/top_level.dart.lib.js:78:56)
                         at cloud_functions_web.CloudFunctionsWeb.new.callCloudFunction
                         (http://localhost:65085/packages/cloud_functions_web/cloud_functions_web.dart.lib.js:28:27)
                         at cloud_functions.HttpsCallable.__.call
                         (http://localhost:65085/packages/cloud_functions/cloud_functions.dart.lib.js:114:83)
                         at contact_form._ContactFormState.new.sendEmail

(http://localhost:65085/packages/DLBlackDev/widgets/contact_form/contact_form.dart.lib.js:1014:30)
                         at contact_form._ContactFormState.new._save

(http://localhost:65085/packages/DLBlackDev/widgets/contact_form/contact_form.dart.lib.js:1007:16)
                         at _save.next (<anonymous>)
                         at runBody (http://localhost:65085/dart_sdk.js:36923:34)
                         at Object._async [as async] (http://localhost:65085/dart_sdk.js:36951:7)
                         at contact_form._ContactFormState.new.[_save]

(http://localhost:65085/packages/DLBlackDev/widgets/contact_form/contact_form.dart.lib.js:1001:20)
                         at
http://localhost:65085/packages/DLBlackDev/widgets/contact_form/contact_form.dart.lib.js:997:28
                         at tap.TapGestureRecognizer.new.invokeCallback
                         (http://localhost:65085/packages/flutter/src/gestures/recognizer.dart.lib.js:197:18)
                         at tap.TapGestureRecognizer.new.handleTapUp
                         (http://localhost:65085/packages/flutter/src/gestures/tap.dart.lib.js:355:40)
                         at tap.TapGestureRecognizer.new.[_checkUp]
                         (http://localhost:65085/packages/flutter/src/gestures/tap.dart.lib.js:186:12)
                         at tap.TapGestureRecognizer.new.acceptGesture
                         (http://localhost:65085/packages/flutter/src/gestures/tap.dart.lib.js:164:23)
                         at arena.GestureArenaManager.new.sweep
                         (http://localhost:65085/packages/flutter/src/gestures/arena.dart.lib.js:208:31)
                         at binding$5.WidgetsFlutterBinding.new.handleEvent
                         (http://localhost:65085/packages/flutter/src/gestures/binding.dart.lib.js:170:27)
                         at binding$5.WidgetsFlutterBinding.new.dispatchEvent
                         (http://localhost:65085/packages/flutter/src/gestures/binding.dart.lib.js:154:24)
                         at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent]
                         (http://localhost:65085/packages/flutter/src/gestures/binding.dart.lib.js:131:14)
                         at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue]
                         (http://localhost:65085/packages/flutter/src/gestures/binding.dart.lib.js:105:34)
                         at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket]
                         (http://localhost:65085/packages/flutter/src/gestures/binding.dart.lib.js:96:65)
                         at Object._invoke1 (http://localhost:65085/dart_sdk.js:166485:7)
                         at _engine.EngineWindow.new.invokeOnPointerDataPacket
(http://localhost:65085/dart_sdk.js:163617:15)
                         at _engine.PointerBinding.__.[_onPointerData] (http://localhost:65085/dart_sdk.js:143285:24)
                         at http://localhost:65085/dart_sdk.js:143637:26
                         at http://localhost:65085/dart_sdk.js:143602:16
                         at http://localhost:65085/dart_sdk.js:143374:11
[+387833 ms] Stopped debug service on ws://127.0.0.1:65159

[ +126 ms] Application finished.
[  +45 ms] "flutter run" took 455,462ms.
```
...after multiple presses of my button. My Firebase function manager still shows the function has yet to be called, too.

My index.ts file under the functions\src folder:
```
import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';

admin.initializeApp();
// const db = admin.firestore();

import * as sgMail from '@sendgrid/mail';

const API_KEY = functions.config().sendgrid.key;
const TEMPLATE_ID = functions.config().sendgrid.template;
sgMail.setApiKey(API_KEY);

export const contactEmail = functions.https.onCall(async (data, context) =>{
    const msg = {
        to: 'MyEmail@gmail.com',
        from: 'MyWebsiteManagementEmail@gmail.com',
        templateId: TEMPLATE_ID,
        dynamic_template_data: {
            name: data.name,
            content: data.message,
            email: data.email
        }
    }

    await sgMail.send(msg);
    return { success: true };
});
```
Just in case that might show anything. The admin.firestore() line is commented because db ended up being unused and throwing errors.

**Flutter doctor**

```
[√] Flutter (Channel dev, 1.19.0-1.0.pre, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
    • Flutter version 1.19.0-1.0.pre at C:\src\flutter
    • Framework revision 456d80b9dd (3 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\deuce\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.45.1)
    • VS Code at C:\Users\deuce\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

Would love to roll out this contact page on my website.

**Comment by shinriyo** [comment]
me too.

**Comment by russellwheatley** [comment]
I've just tested the example app in the functions package for web. It works fine. 

I have noticed in your logs this line:

```bash
TypeError: Cannot read property 'app' of undefined
```
No idea where that is coming from without any app code, but it is worth investigating this error. Furthermore, please provide a reproducible code sample should you find a problem with the functions package and I'll happily investigate.
