### ISSUE TITLE
Can't login with google account with this issue

### ISSUE THREAD

**Issue by hashika2** [FirebaseExtended/flutterfire#2606]
```
E/flutter (17401): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
[        ] E/flutter (17401): Receiver: null
[        ] E/flutter (17401): Tried calling: []("email")
[        ] E/flutter (17401): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[   +3 ms] E/flutter (17401): #1      DocumentSnapshot.[] (package:cloud_firestore/src/document_snapshot.dart:29:42)
[  +22 ms] E/flutter (17401): #2      new User.fromDocument (package:buddiesgram/models/user.dart:23:17)
[        ] E/flutter (17401): #3      _HomePageState.saveUserInfoFirestore (package:buddiesgram/pages/HomePage.dart:79:26)
[        ] E/flutter (17401): <asynchronous suspension>
[        ] E/flutter (17401): #4      _HomePageState.controlSignIn (package:buddiesgram/pages/HomePage.dart:50:13)
[        ] E/flutter (17401): #5      _HomePageState.initState.<anonymous closure> (package:buddiesgram/pages/HomePage.dart:36:9)
[        ] E/flutter (17401): #6      _rootRunUnary (dart:async/zone.dart:1134:38)
[        ] E/flutter (17401): #7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] E/flutter (17401): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
[        ] E/flutter (17401): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
[        ] E/flutter (17401): #10     _DelayedData.perform (dart:async/stream_impl.dart:593:14)
[        ] E/flutter (17401): #11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:709:11)
[        ] E/flutter (17401): #12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:669:7)
[        ] E/flutter (17401): #13     _rootRun (dart:async/zone.dart:1122:38)
[  +20 ms] E/flutter (17401): #14     _CustomZone.run (dart:async/zone.dart:1023:19)
[  +23 ms] E/flutter (17401): #15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
[        ] E/flutter (17401): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
[        ] E/flutter (17401): #17     _rootRun (dart:async/zone.dart:1126:13)
[        ] E/flutter (17401): #18     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] E/flutter (17401): #19     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
[        ] E/flutter (17401): #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
[        ] E/flutter (17401): #21     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[        ] E/flutter (17401): #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[        ] E/flutter (17401): 
```

**Comment by TahaTesser** [comment]
Hi @hashika2 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by hashika2** [comment]
Flutter version 1.17.1
Dart version 2.8.2

**Comment by TahaTesser** [comment]
Hi @hashika2 
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you
