### ISSUE TITLE
[cloud_firestore] Fatal Exception: java.lang.NullPointerException ($EventObserver.onEvent(:33))

### ISSUE THREAD

**Issue by EliasDeuss** [FirebaseExtended/flutterfire#2613]
Firebase crashlytics started to pick up a high amount of users app crashing when sending a Firestore add transaction.

crashlytics output:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(:33)
       at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(:2)
       at com.google.firebase.firestore.c0.a(:27)
       at com.google.firebase.firestore.b0.onEvent(:6)
       at com.google.firebase.firestore.p0.i.a(:6)
       at com.google.firebase.firestore.p0.h.run(:6)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

Flutter doctor:
```
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.19.0-1.0.pre at /Users/elias/flutter
    • Framework revision 456d80b9dd (12 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)
```

**Comment by iapicca** [comment]
Hi @EliasDeuss 
can you please provide 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by andcea** [comment]
Probably same as https://github.com/FirebaseExtended/flutterfire/issues/2390
