### ISSUE TITLE
[firebase_messaging] Exception on casting returning integer to long in FirebaseMessagingPlugin.java

### ISSUE THREAD

**Issue by gregertw** [FirebaseExtended/flutterfire#2654]
**Describe the bug**
```
E/FirebaseMessagingPlugin( 6713): There was an exception when getting callback handle from Dart side
W/System.err( 6713): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
W/System.err( 6713):    at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onMethodCall(FirebaseMessagingPlugin.java:170)
W/System.err( 6713):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/System.err( 6713):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 6713):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/System.err( 6713):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 6713):    at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err( 6713):    at android.os.Looper.loop(Looper.java:174)
W/System.err( 6713):    at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err( 6713):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 6713):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 6713):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**To Reproduce**
1. https://github.com/gregertw/actingweb_firstapp/tree/firebase_messaging
2. Run test task: start observatory
3. Run test task: run integration tasks
4. Error is shown in console

**Expected behavior**
No exception

**Additional context**
Note that Application.kt is used, not the Application.java as in the example!

I have also observed issues with flutter_auth0 conflicting with firebase_messaging, which is how I found this. This happens after firebase_messaging has been initialised and only the second time you try to log in (you need to log out and in again). Not sure if it is related.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by gregertw** [comment]
I have rewritten to get rid of flutter_auth0, but still get the exact same exception.
