### ISSUE TITLE
Exception on configuration of Firebase Messaging on an iOS Emulator

### ISSUE THREAD

**Issue by ahmaducg** [FirebaseExtended/flutterfire#2823]
Whenever I run the Flutter app on the iOS emulator, the following exception is thrown

```
[Firebase/Crashlytics] Version 4.2.0
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
Debug service listening on ws://127.0.0.1:49970/KF9FQXkBwU0=/ws
Syncing files to device iPhone 11 Pro...
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method FcmDartService#start on channel plugins.flutter.io/firebase_messaging)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      FirebaseMessaging.configure (package:firebase_messaging/firebase_messaging.dart:130:16)
#3      App.build (package:alyamin/main.dart:109:23)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#9      Element.inflateWidget (package:fl<…>
flutter: cWCQfK5BU07UhgX0HgKGZj:APA91bGRzD3qDOrdStZiCj-u6HasKKGoPt9CmxMiZD60fKiIgiwcSy_I8ffRaXToUQxTknqqyeK2rI7ZcvdI-ee-Nf-5XZQvswXnFXZFFB6ppTd5wx31z5NzXcGjbZlHFe-3c7RKFcky
[VERBOSE-2:shell.cc(213)] Dart Error: Unhandled exception:
MissingPluginException(No implementation found for method FcmDartService#start on channel plugins.flutter.io/firebase_messaging)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      FirebaseMessaging.configure (package:firebase_messaging/firebase_messaging.dart:130:16)
#3      App.build (package:alyamin/main.dart:109:23)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
#9      RendererBinding._handlePersistentFr<…>
flutter: cWCQfK5BU07UhgX0HgKGZj:APA91bGRzD3qDOrdStZiCj-u6HasKKGoPt9CmxMiZD60fKiIgiwcSy_I8ffRaXToUQxTknqqyeK2rI7ZcvdI-ee-Nf-5XZQvswXnFXZFFB6ppTd5wx31z5NzXcGjbZlHFe-3c7RKFcky

```

This is when I'm doing on the start of the app :

```
// Configure Firebase Cloud Messaging with a notification handler
    firebaseMessaging.configure(
      onBackgroundMessage: notificationHandler,
      onMessage: notificationHandler,
    );
```

Flutter Doctor :

```
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.4 19E287, locale en-SY)
    • Flutter version 1.17.4 at /Users/ucgmacmini/Library/flutter
    • Framework revision 1ad9baa8b9 (6 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at /Users/ucgmacmini/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro             • 7CF0AEC0-6B2F-4EDA-9C70-5941AE459EED • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 2 categories.

```

firebase_messaging : ^6.0.16

**Comment by TahaTesser** [comment]
Hi @ahmaducg 
Please try [solution](https://github.com/FirebaseExtended/flutterfire/issues/116#issuecomment-537516766), you cannot have  onBackgroundMessage on iOS

Thank you

**Comment by ahmaducg** [comment]
Disabling the onBackgroundMessage made the app run without the exception at the start.
