### ISSUE TITLE
[firebase_analytics] Tests are failing with flutter:master

### ISSUE THREAD

**Issue by tugorez** [FirebaseExtended/flutterfire#2850]
**Describe the bug**
While trying to merge https://github.com/FirebaseExtended/flutterfire/pull/2844 we found [the tests for the master channel were failing](https://github.com/FirebaseExtended/flutterfire/pull/2844/checks?check_run_id=809273148). After some debugging we found that the tests are failing only the first time after deleting the cache (the build folder). 

**To Reproduce**
1. Clone this repo
2. Go to the firebase_analytics package folder: `cd packages/firebase_analytics/firebase_analytics`
3. Switch to channel master: `flutter channel master`
4. Clean your cache: `flutter clean`
5. Run the  tests: `flutter test` (the tests should fail)
6. Make some change to the test/observer_test.dart file (can be anything even introducing a new empty line).
7. Run the tests" `flutter test` (the tests should pass)

![image](https://user-images.githubusercontent.com/7821057/85893518-dfc6f180-b7a7-11ea-8993-cfb90f7028da.png)

**Expected behavior**
The tests should pass (or fail) consistenly.

**Additional context**
flutter in beta doesn't present this behavior.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-1.0.pre.224, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by tugorez** [comment]
cc @ditman

**Comment by ditman** [comment]
Hm, I can't repro the issue:

```
dit@dit:~/github/flutterfire/packages/firebase_analytics/firebase_analytics$ flutter clean
Deleting build...                                                    6ms
Deleting .dart_tool...                                               0ms
dit@dit:~/github/flutterfire/packages/firebase_analytics/firebase_analytics$ flutter test
Running "flutter pub get" in firebase_analytics...                  0.5s
00:06 +56: All tests passed!
```

```
dit@dit:~/github/flutterfire/packages/firebase_analytics/firebase_analytics$ flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.20.0-1.0.pre.224, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[✓] Chrome - develop for the web
[!] Android Studio (version 3.4)
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by ditman** [comment]
It started failing on my box, not sure what triggered the failure, but here's a `-v` run:

```
dit@dit:~/github/flutterfire/packages/firebase_analytics/firebase_analytics$ flutter test -v test/observer_test.dart
[  +89 ms] executing: [/usr/local/google/home/dit/github/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +29 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 3ce26910923b6a5e784df17a8a9a17b50598df4a
[   +1 ms] executing: [/usr/local/google/home/dit/github/flutter/] git tag --contains HEAD
[  +22 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] executing: [/usr/local/google/home/dit/github/flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[  +11 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.20.0-2.0.pre-72-g3ce2691092
[   +6 ms] executing: [/usr/local/google/home/dit/github/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/usr/local/google/home/dit/github/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] git@github.com:ditman/flutter.git
[  +45 ms] executing: [/usr/local/google/home/dit/github/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +37 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +79 ms] running test package with arguments: [-r, compact, --concurrency=4, --,
/usr/local/google/home/dit/github/flutterfire/packages/firebase_analytics/firebase_analytics/test/observer_test.dart]
00:00 +0: ... /usr/local/google/home/dit/github/flutterfire/packages/firebase_analytics/firebase_analytics/test/observer_test.dart                 [ +196 ms] test 0: starting test
/usr/local/google/home/dit/github/flutterfire/packages/firebase_analytics/firebase_analytics/test/observer_test.dart
[  +10 ms] test 0: starting shell process
[   +4 ms] Stopping scan for flutter_test_config.dart; found project root at
/usr/local/google/home/dit/github/flutterfire/packages/firebase_analytics/firebase_analytics
[   +6 ms] Compiler will use the following file as its incremental dill file: /tmp/flutter_tools.YUSEQJ/flutter_test_compiler.NABMYE/output.dill
[        ] Listening to compiler controller...
[   +7 ms] Compiling file:///tmp/flutter_tools.YUSEQJ/flutter_test_listener.QINQRF/listener.dart
[  +10 ms] /usr/local/google/home/dit/github/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/usr/local/google/home/dit/github/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/usr/local/google/home/dit/github/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tools.YUSEQJ/flutter_test_compiler.NABMYE/output.dill
--packages /usr/local/google/home/dit/github/flutterfire/packages/firebase_analytics/firebase_analytics/.packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --initialize-from-dill
/usr/local/google/home/dit/github/flutterfire/packages/firebase_analytics/firebase_analytics/build/testfile.dill.track.dill
[  +23 ms] <- compile file:///tmp/flutter_tools.YUSEQJ/flutter_test_listener.QINQRF/listener.dart
[ +887 ms] <- accept
[        ] <- reset
[        ] Compiling /tmp/flutter_tools.YUSEQJ/flutter_test_listener.QINQRF/listener.dart took 922ms
[   +1 ms] /usr/local/google/home/dit/github/flutter/bin/cache/artifacts/engine/linux-x64/flutter_tester --disable-observatory --enable-checked-mode
--verify-entry-points --enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling --non-interactive --use-test-fonts
--packages=/usr/local/google/home/dit/github/flutterfire/packages/firebase_analytics/firebase_analytics/.packages
/tmp/flutter_tools.YUSEQJ/flutter_test_listener.QINQRF/listener.dart.dill
[   +2 ms] Using this directory for fonts configuration: /tmp/flutter_tools.YUSEQJ/flutter_test_fonts.YGUXIY
00:01 +0: ... /usr/local/google/home/dit/github/flutterfire/packages/firebase_analytics/firebase_analytics/test/observer_test.dart                 [   +9 ms] test 0: awaiting initial result for pid 450700
[ +501 ms] test 0: process with pid 450700 connected to test harness
[        ] test 0: awaiting test result for pid 450700
00:01 +4 -1: FirebaseAnalyticsObserver handles only PlatformExceptions [E]                                                                         
  Invalid argument(s)
  package:mockito/src/mock.dart 342:7                       PostExpectation.thenThrow.<fn>
  package:mockito/src/mock.dart 119:45                      Mock.noSuchMethod
  package:firebase_analytics/firebase_analytics.dart 83:16  MockFirebaseAnalytics.setCurrentScreen
  package:firebase_analytics/observer.dart 80:17            FirebaseAnalyticsObserver._sendScreenView
  package:firebase_analytics/observer.dart 97:7             FirebaseAnalyticsObserver.didPush
  test/observer_test.dart 98:29                             main.<fn>.<fn>.<fn>
  package:test_api                                          expect
  package:flutter_test/src/widget_tester.dart 369:3         expect
  test/observer_test.dart 98:7                              main.<fn>.<fn>
  test/observer_test.dart 85:48                             main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                _AsyncAwaitCompleter.completeError
  package:firebase_analytics/firebase_analytics.dart        MockFirebaseAnalytics.setCurrentScreen
  package:firebase_analytics/observer.dart 80:17            FirebaseAnalyticsObserver._sendScreenView
  package:firebase_analytics/observer.dart 97:7             FirebaseAnalyticsObserver.didPush
  test/observer_test.dart 98:29                             main.<fn>.<fn>.<fn>
  package:test_api                                          expect
  package:flutter_test/src/widget_tester.dart 369:3         expect
  test/observer_test.dart 98:7                              main.<fn>.<fn>
  test/observer_test.dart 85:48                             main.<fn>.<fn>
  
  Expected: throws <Instance of 'ArgumentError'>
    Actual: <Closure: () => void>
     Which: returned <null>
  
  package:test_api                                   expect
  package:flutter_test/src/widget_tester.dart 369:3  expect
  test/observer_test.dart 98:7                       main.<fn>.<fn>
  test/observer_test.dart 85:48                      main.<fn>.<fn>
  
00:01 +5 -1: FirebaseAnalyticsObserver runs onError                                                                                                [ +249 ms] test 0: process with pid 450700 no longer needed by test harness
[        ] test 0: cleaning up...
[        ] test 0: ensuring end-of-process for shell
[   +7 ms] test 0: deleting temporary directory
[   +4 ms] test 0: shutting down test harness socket server
[   +1 ms] test 0: finished
00:01 +5 -1: Some tests failed.                                                                                                                    
[   +9 ms] Deleting /tmp/flutter_tools.YUSEQJ/flutter_test_compiler.NABMYE...
[   +3 ms] killing pid 450690
[  +31 ms] Deleting /tmp/flutter_tools.YUSEQJ/flutter_test_fonts.YGUXIY...
[   +3 ms] test package returned with exit code 1
[   +7 ms] "flutter test" took 2,079ms.
[  +10 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:292:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:853:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #10     _rootRun (dart:async/zone.dart:1190:13)
           #11     _CustomZone.run (dart:async/zone.dart:1093:19)
           #12     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[  +28 ms] ensureAnalyticsSent: 25ms
[        ] Running shutdown hooks
[        ] Shutdown hook priority 4
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by ditman** [comment]
I've bisected the issue to [this engine roll](https://github.com/flutter/flutter/pull/60291):

```
dit@dit:~/github/flutter$ git bisect good 15a28159bc
dit@dit:~/github/flutter$ git bisect bad 3ce2691092
Bisecting: 35 revisions left to test after this (roughly 5 steps)
[c36c4293d59a03bfc67752f632264388003d4feb] Roll Engine from a0deaf9b04dc to 733b1aa7b90d (4 revisions) (#60218)
dit@dit:~/github/flutter$ git bisect good
Bisecting: 17 revisions left to test after this (roughly 4 steps)
[82a6f9bf0bef537537d91b8b5d927a0d5364f834] [flutter_tools] remove most use of global packages path (#60231)
dit@dit:~/github/flutter$ git bisect good
Bisecting: 8 revisions left to test after this (roughly 3 steps)
[1e6e7150f3b4464065e36ebacc9a3b46a12c7cec] [gen_l10n] Update the arb filename parsing logic (#60185)
dit@dit:~/github/flutter$ git bisect bad
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[47c5174bef0bbbf8ff678ebfddf4dde4b068fc8b] Roll Engine from 781885120002 to 9ad489e7d7ba (4 revisions) (#60314)
dit@dit:~/github/flutter$ git bisect bad
Bisecting: 1 revision left to test after this (roughly 1 step)
[8a5042b2dfe09212228a6665163adf8c1fb7a569] Roll Engine from 73ff2bdd36ab to 781885120002 (12 revisions) (#60291)
dit@dit:~/github/flutter$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[1e843bb6bac47e692ee02be1f997c45adcdc9b18] fix paint order of ink feature (#59108)
dit@dit:~/github/flutter$ git bisect good
8a5042b2dfe09212228a6665163adf8c1fb7a569 is the first bad commit
commit 8a5042b2dfe09212228a6665163adf8c1fb7a569
Author: engine-flutter-autoroll <engine-flutter-autoroll@skia.org>
Date:   Thu Jun 25 15:58:02 2020 -0400

    Roll Engine from 73ff2bdd36ab to 781885120002 (12 revisions) (#60291)

 bin/internal/engine.version        | 2 +-
 bin/internal/fuchsia-linux.version | 2 +-
 bin/internal/fuchsia-mac.version   | 2 +-
 3 files changed, 3 insertions(+), 3 deletions(-)
```

Here's the build failure with the first bad flutter/flutter revision:

```
dit@dit:~/github/flutterfire/packages/firebase_analytics/firebase_analytics$ flutter clean && flutter test test/observer_test.dart
Downloading Dart SDK from Flutter engine 781885120002e7be770b0854ce97402cdae778a6...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  245M  100  245M    0     0  47.1M      0  0:00:05  0:00:05 --:--:-- 53.0M
Building flutter tool...
Downloading package sky_engine...                                   0.3s
Downloading flutter_patched_sdk tools...                            0.5s
Downloading flutter_patched_sdk_product tools...                    0.5s
Downloading linux-x64 tools...                                      1.3s
Downloading linux-x64/font-subset tools...                          0.3s
Deleting build...                                                    3ms
Deleting .dart_tool...                                               0ms
Running "flutter pub get" in firebase_analytics...                  0.5s
00:06 +4 -1: FirebaseAnalyticsObserver handles only PlatformExceptions [E]                                                                         
  Invalid argument(s)
  package:mockito/src/mock.dart 342:7                       PostExpectation.thenThrow.<fn>
  package:mockito/src/mock.dart 119:45                      Mock.noSuchMethod
  package:firebase_analytics/firebase_analytics.dart 83:16  MockFirebaseAnalytics.setCurrentScreen
  package:firebase_analytics/observer.dart 80:17            FirebaseAnalyticsObserver._sendScreenView
  package:firebase_analytics/observer.dart 97:7             FirebaseAnalyticsObserver.didPush
  test/observer_test.dart 98:29                             main.<fn>.<fn>.<fn>
  package:test_api                                          expect
  package:flutter_test/src/widget_tester.dart 369:3         expect
  test/observer_test.dart 98:7                              main.<fn>.<fn>
  test/observer_test.dart 85:48                             main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                _AsyncAwaitCompleter.completeError
  package:firebase_analytics/firebase_analytics.dart        MockFirebaseAnalytics.setCurrentScreen
  package:firebase_analytics/observer.dart 80:17            FirebaseAnalyticsObserver._sendScreenView
  package:firebase_analytics/observer.dart 97:7             FirebaseAnalyticsObserver.didPush
  test/observer_test.dart 98:29                             main.<fn>.<fn>.<fn>
  package:test_api                                          expect
  package:flutter_test/src/widget_tester.dart 369:3         expect
  test/observer_test.dart 98:7                              main.<fn>.<fn>
  test/observer_test.dart 85:48                             main.<fn>.<fn>
  
  Expected: throws <Instance of 'ArgumentError'>
    Actual: <Closure: () => void>
     Which: returned <null>
  
  package:test_api                                   expect
  package:flutter_test/src/widget_tester.dart 369:3  expect
  test/observer_test.dart 98:7                       main.<fn>.<fn>
  test/observer_test.dart 85:48                      main.<fn>.<fn>
  
00:06 +5 -1: Some tests failed.                                                                                                                    
```

**Comment by ditman** [comment]
Note, I had to manually run the specific test file to reliably reproduce the issue: `flutter test test/observer_test.dart`

There might be a problem with the order in which test files are being run (?) (that's why @tugorez was able to reproduce without passing the test file?)

**Comment by ditman** [comment]
This may have to do with `dart` or `build_runner`. It's on Dart's team radar.

For now, I'll disable the failing assertion(s) and add a TODO to this ticket.

(cc @vsmenon)

**Comment by ditman** [comment]
(The expectation has been disabled until there's progress in this issue (or related))

**Comment by ditman** [comment]
I have bisected third_party/dart within an overridden `host_release` engine to [this commit](https://dart-review.googlesource.com/c/sdk/+/152330). 

(I found the starting "good" revision by going back a bunch of revisions; `HEAD~20` or similar).

```
dit@dit:~/github/engine/src/third_party/dart$ git bisect start
dit@dit:~/github/engine/src/third_party/dart$ git bisect bad 4079c373c0
dit@dit:~/github/engine/src/third_party/dart$ git bisect good 77b0817f35
Bisecting: 9 revisions left to test after this (roughly 3 steps)
[ff83b0fec9a24020684efefa42ae2faf329b9814] Add support for navigating from the URI in import and export configurations to the referenced file
dit@dit:~/github/engine/src/third_party/dart$ git bisect good
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[d33e51df3cda1d8caa0a4a6c006adb7c6aa331ee] [build] Support --clang when building dart sdk on Windows.
dit@dit:~/github/engine/src/third_party/dart$ git bisect good
Bisecting: 2 revisions left to test after this (roughly 1 step)
[0a77a1f63ec7fba9a8658db82704e2dba541abe6] [infra] Add VM/fuchsia builder to the test matrix
dit@dit:~/github/engine/src/third_party/dart$ git bisect good
Bisecting: 0 revisions left to test after this (roughly 1 step)
[2ad66bbffee6cdf77f5de90a3c09c0423994d401] [CFE] Set correct async markers in outline phase
dit@dit:~/github/engine/src/third_party/dart$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[1c512ef1203b086089105e3b6c7b55e93566be0a] [co19] Enable more migrated "Language" tests
dit@dit:~/github/engine/src/third_party/dart$ git bisect good
2ad66bbffee6cdf77f5de90a3c09c0423994d401 is the first bad commit
commit 2ad66bbffee6cdf77f5de90a3c09c0423994d401
Author: Jens Johansen <jensj@google.com>
Date:   Thu Jun 25 10:29:28 2020 +0000

    [CFE] Set correct async markers in outline phase
    
    Change-Id: I4ac1fe1f4195dea2c20b8e55963b7e7dffc2d289
    Reviewed-on: https://dart-review.googlesource.com/c/sdk/+/152330
    Reviewed-by: Johnni Winther <johnniwinther@google.com>
    Commit-Queue: Jens Johansen <jensj@google.com>

... a bunch of changed files...
```

After each checkout, I had to `ninja -C out/host_release -j100` to rebuild the engine, and then:

```
dit@dit:~/github/flutterfire/packages/firebase_analytics/firebase_analytics$ flutter clean --local-engine host_release && flutter test --local-engine host_release test/observer_test.dart 
Deleting build...                                                    7ms
Deleting .dart_tool...                                               0ms
Running "flutter pub get" in firebase_analytics...                  0.4s
00:06 +4 -1: FirebaseAnalyticsObserver handles only PlatformExceptions [E]
  Invalid argument(s)
  package:mockito/src/mock.dart 342:7                       PostExpectation.thenThrow.<fn>
  package:mockito/src/mock.dart 119:45                      Mock.noSuchMethod
  package:firebase_analytics/firebase_analytics.dart 83:16  MockFirebaseAnalytics.setCurrentScreen
  package:firebase_analytics/observer.dart 80:17            FirebaseAnalyticsObserver._sendScreenView
  package:firebase_analytics/observer.dart 97:7             FirebaseAnalyticsObserver.didPush
  test/observer_test.dart 98:29                             main.<fn>.<fn>.<fn>
  package:test_api                                          expect
  package:flutter_test/src/widget_tester.dart 369:3         expect
  test/observer_test.dart 98:7                              main.<fn>.<fn>
  test/observer_test.dart 85:48                             main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async                                                _AsyncAwaitCompleter.completeError
  package:firebase_analytics/firebase_analytics.dart        MockFirebaseAnalytics.setCurrentScreen
  package:firebase_analytics/observer.dart 80:17            FirebaseAnalyticsObserver._sendScreenView
  package:firebase_analytics/observer.dart 97:7             FirebaseAnalyticsObserver.didPush
  test/observer_test.dart 98:29                             main.<fn>.<fn>.<fn>
  package:test_api                                          expect
  package:flutter_test/src/widget_tester.dart 369:3         expect
  test/observer_test.dart 98:7                              main.<fn>.<fn>
  test/observer_test.dart 85:48                             main.<fn>.<fn>
  
  Expected: throws <Instance of 'ArgumentError'>
    Actual: <Closure: () => void>
     Which: returned <null>
  
  package:test_api                                   expect
  package:flutter_test/src/widget_tester.dart 369:3  expect
  test/observer_test.dart 98:7                       main.<fn>.<fn>
  test/observer_test.dart 85:48                      main.<fn>.<fn>
  
00:06 +5 -1: Some tests failed.
```

**Comment by russellwheatley** [comment]
The Analytics plugin has been reworked and the tests have also been completely updated. As such, the "observer_test.dart" doesn't even exist anymore.
