### ISSUE TITLE
cloud_firestore : Batch commit not failing even though there is an error in one of the transactions

### ISSUE THREAD

**Issue by vin-fandemand** [FirebaseExtended/flutterfire#2965]
**Describe the bug**
While working on Flutter, I was writing a batch of transactions for creating documents on Firestore. The first transaction was valid, but the second transaction gave the error 

```
`E/flutter ( 3848): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Invalid data. Document fields must not be empty, null)
E/flutter ( 3848): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 3848): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 3848): <asynchronous suspension>
E/flutter ( 3848): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 3848): #3      MethodChannelWriteBatch.setData.<anonymous closure> (package:cloud_firestore_platform_interface/src/method_channel/method_channel_write_batch.dart:67:40)`
```

Now there is something missing the data that I have to fix. However, my batch commit did not catch the error and the first transaction was successful. I thought the point of batch transactions was to ensure integrity when there are multiple transactions. So if one transaction fails, I expect everything else to fail as well.

Is this an expected behaviour or am I missing something ? Can you please advice ?

**To Reproduce**
```Future<String> _writeToCloud() async {
    final WriteBatch _batch = Firestore.instance.batch();
    String flag = '';

    final int timestamp = DateTime.now().millisecondsSinceEpoch;
// this transaction succeeds
    _batch.setData(
        Firestore.instance
            .collection('users')
            .document(uid)
            .collection('collection')
            .document('$uid$timestamp'),
        <String, dynamic>{'timestamp': timestamp}); 

// this transaction fails
    _batch.setData(
        Firestore.instance
            .collection('collection')
            .document('$uid$timestamp'),
        <Data that gives that error>);

    await _batch.commit().then((value) {
      flag = 'Submitted Successfully';
    }).catchError((dynamic onError) {
      print(onError.toString());
      flag = 'Submission Failed';
    });

    return flag;
  }
```

**Expected behavior**
I expect the whole batch transaction to back out as one of the transactions failed. I also expect the commit would catch the error.

**Additional context**
`cloud_firestore: ^0.13.7`

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Linux, locale en_CA.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @vin-fandemand 
Can you provide an example data that gives error
```
// this transaction fails
    _batch.setData(
        Firestore.instance
            .collection('collection')
            .document('$uid$timestamp'),
        <Data that gives that error>);
```


<details> 
<summary>Code Sample</summary> 

``` 
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  String flag;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firestore Example'),
      ),
      body: Center(
        child: BookList(),
      ),
      floatingActionButton: FloatingActionButton(onPressed: () async {
        final WriteBatch _batch = Firestore.instance.batch();

        final int timestamp = DateTime.now().millisecondsSinceEpoch;
// this transaction succeeds
        _batch.setData(
            Firestore.instance
                .collection('users')
                .document('2020')
                .collection('collection')
                .document('20202 $timestamp'),
            <String, dynamic>{'timestamp': timestamp});

// this transaction fails
        _batch.setData(
            Firestore.instance
                .collection('collection')
                .document('2020 $timestamp'),
            <String, dynamic>{'timestamp': timestamp});

        await _batch.commit().then((value) {
          flag = 'Submitted Successfully';
        }).catchError((dynamic onError) {
          print(onError.toString());
          flag = 'Submission Failed';
        });
      }),
    );
  }
}

class BookList extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<QuerySnapshot>(
      stream: Firestore.instance.collection('books').snapshots(),
      builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        if (snapshot.hasError) return new Text('Error: ${snapshot.error}');
        switch (snapshot.connectionState) {
          case ConnectionState.waiting:
            return new Text('Loading...');
          default:
            return new ListView(
              children:
                  snapshot.data.documents.map((DocumentSnapshot document) {
                return new ListTile(
                  title: new Text(document['title']),
                  subtitle: new Text(document['author']),
                );
              }).toList(),
            );
        }
      },
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (6 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            •
      iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     •
      Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
```

</details>

**Comment by vin-fandemand** [comment]
I am unable to recreate the issue. It is working as expected.

**Comment by TahaTesser** [comment]
Hi @vin-fandemand 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you
