### ISSUE TITLE
[Firebase_auth_example] Not compiling-  Error: Getter not found: 'Firebase'.

### ISSUE THREAD

**Issue by fhidal01** [FirebaseExtended/flutterfire#2994]
**Describe the bug**
I get a compile error when running `flutter run --verbose -d web-server --web-port 5000`
```
Compiler message:
[        ] ../lib/src/firebase_auth.dart:18:55: Error: Getter not found: 'Firebase'.
[        ]   static final FirebaseAuth instance = FirebaseAuth._(Firebase.app());
[        ]                                                       ^^^^^^^^
[+11261 ms] Syncing files to device Web Server... (completed in 13,076ms, longer than expected)
[        ] Synced 0.0MB.
[        ] Failed to compile application.
```

**To Reproduce**
1. Checked out master branch
2. Ran `flutter channel beta` followed by `flutter upgrade`
4. cd into firebase_auth/example
5. run the following command `flutter run --verbose -d web-server --web-port 5000`

Gets a compile error

**Expected behavior**
For it to start up normally

**Additional context**
```
Flutter 1.19.0-4.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8fe7655ed2 (3 weeks ago) • 2020-07-01 14:31:18 -0700
Engine • revision 9a28c3bcf4
Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)
```

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Downloading android-arm-profile/darwin-x64 tools...                 0.8s
Downloading android-arm-release/darwin-x64 tools...                 0.7s
Downloading android-arm64-profile/darwin-x64 tools...               0.5s
Downloading android-arm64-release/darwin-x64 tools...               0.6s
Downloading android-x64-profile/darwin-x64 tools...                 0.8s
Downloading android-x64-release/darwin-x64 tools...                 0.5s
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.19.0-4.3.pre, on Mac OS X 10.15.6 19G73, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.47.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

``` 
taha@Tahas-MacBook-Pro app % flutterd run --verbose -d web-server --web-port 5000
[ +138 ms] executing: [/Users/taha/Code/flutter_dev/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +47 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f25bd9c55c48c139524139b477d04b13e9f36b2c
[        ] executing: [/Users/taha/Code/flutter_dev/] git tag --contains HEAD
[ +178 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.21.0-1.0.pre
[  +11 ms] executing: [/Users/taha/Code/flutter_dev/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [/Users/taha/Code/flutter_dev/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +57 ms] executing: [/Users/taha/Code/flutter_dev/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[   +5 ms] executing: sw_vers -productName
[  +29 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +21 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.6
[        ] executing: sw_vers -buildVersion
[  +19 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19G73
[  +57 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] executing: /Users/taha/Code/sdk/platform-tools/adb devices -l
[   +8 ms] executing: /usr/bin/xcode-select --print-path
[  +10 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +2 ms] executing: /usr/bin/xcodebuild -version
[ +368 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.6
           Build version 11E708
[   +2 ms] executing: xcrun --find xcdevice
[   +9 ms] Exit code 0 from: xcrun --find xcdevice
[        ] /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice
[        ] executing: xcrun xcdevice list --timeout 2
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[        ] executing: /usr/bin/xcrun simctl list --json devices
[  +47 ms] List of devices attached
           32003c30dc19668f       device usb:336723968X product:m30ltedd model:SM_M305F device:m30lte transport_id:1
[ +479 ms] {
                      "devices" : {
                        "com.apple.CoreSimulator.SimRuntime.tvOS-13-4" : [

                        ],
                        "com.apple.CoreSimulator.SimRuntime.watchOS-6-2" : [
                          {
                            "dataPath" :
                            "\/Users\/taha\/Library\/Developer\/CoreSimulator\/Devices\/C66161C3-D955-44E1-9C94-25E81303
                            F058\/data",
                            "logPath" :
                            "\/Users\/taha\/Library\/Logs\/CoreSimulator\/C66161C3-D955-44E1-9C94-25E81303F058",
                            "udid" : "C66161C3-D955-44E1-9C94-25E81303F058",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm",
                            "state" : "Shutdown",
                            "name" : "Apple Watch Series 4 - 40mm"
                          },
                          {
                            "dataPath" :
                            "\/Users\/taha\/Library\/Developer\/CoreSimulator\/Devices\/518BBA07-5EB6-46CB-A4A0-66589B53
                            A1E6\/data",
                            "logPath" :
                            "\/Users\/taha\/Library\/Logs\/CoreSimulator\/518BBA07-5EB6-46CB-A4A0-66589B53A1E6",
                            "udid" : "518BBA07-5EB6-46CB-A4A0-66589B53A1E6",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm",
                            "state" : "Shutdown",
                            "name" : "Apple Watch Series 4 - 44mm"
                          }
                        ],
                        "com.apple.CoreSimulator.SimRuntime.iOS-13-6" : [
                          {
                            "dataPath" :
                            "\/Users\/taha\/Library\/Developer\/CoreSimulator\/Devices\/AAB605C7-0569-43D6-9D8D-2AC1A9C3
                            6264\/data",
                            "logPath" :
                            "\/Users\/taha\/Library\/Logs\/CoreSimulator\/AAB605C7-0569-43D6-9D8D-2AC1A9C36264",
                            "udid" : "AAB605C7-0569-43D6-9D8D-2AC1A9C36264",
                            "isAvailable" : true,
                            "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-11",
                            "state" : "Shutdown",
                            "name" : "iPhone 11"
                          }
                        ]
                      }
                    }
[+3047 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.2.1 (17T531)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch4,3",
                        "identifier" : "C66161C3-D955-44E1-9C94-25E81303F058",
                        "architecture" : "i386",
                        "modelUTI" : "com.apple.watch-series4-1",
                        "modelName" : "Apple Watch Series 4 - 40mm",
                        "name" : "Apple Watch Series 4 - 40mm"
                      },
                      {
                        "simulator" : false,
                        "operatingSystemVersion" : "13.6 (17G68)",
                        "interface" : "usb",
                        "available" : true,
                        "platform" : "com.apple.platform.iphoneos",
                        "modelCode" : "iPhone11,8",
                        "identifier" : "00008020-001059882212002E",
                        "architecture" : "arm64e",
                        "modelUTI" : "com.apple.iphone-xr-1",
                        "modelName" : "iPhone XR",
                        "name" : "Taha’s iPhone"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "13.6 (17G64)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone12,1",
                        "identifier" : "AAB605C7-0569-43D6-9D8D-2AC1A9C36264",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-11-1",
                        "modelName" : "iPhone 11",
                        "name" : "iPhone 11"
                      },
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "6.2.1 (17T531)",
                        "available" : true,
                        "platform" : "com.apple.platform.watchsimulator",
                        "modelCode" : "Watch4,4",
                        "identifier" : "518BBA07-5EB6-46CB-A4A0-66589B53A1E6",
                        "architecture" : "i386",
                        "modelUTI" : "com.apple.watch-series4-1",
                        "modelName" : "Apple Watch Series 4 - 44mm",
                        "name" : "Apple Watch Series 4 - 44mm"
                      }
                    ]
[  +10 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +14 ms] Changing current working directory to:
           /Users/taha/AndroidStudioProjects/flutterfire/packages/firebase_auth/firebase_auth/example
[ +148 ms] Found plugin e2e at /Users/taha/.pub-cache/hosted/pub.dartlang.org/e2e-0.4.3+1/
[  +23 ms] Found plugin firebase_auth_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.3+1/
[   +3 ms] Found plugin firebase_core at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +6 ms] Found plugin firebase_core_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[   +3 ms] Found plugin firebase_dynamic_links at
/Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.5.1/
[   +4 ms] Found plugin google_sign_in at /Users/taha/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.1/
[   +9 ms] Found plugin google_sign_in_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1+1/
[  +65 ms] Found plugin firebase_auth at
/Users/taha/AndroidStudioProjects/flutterfire/packages/firebase_auth/firebase_auth/
[  +47 ms] Found plugin e2e at /Users/taha/.pub-cache/hosted/pub.dartlang.org/e2e-0.4.3+1/
[   +3 ms] Found plugin firebase_auth_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.3+1/
[        ] Found plugin firebase_core at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +1 ms] Found plugin firebase_core_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[        ] Found plugin firebase_dynamic_links at
/Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.5.1/
[   +2 ms] Found plugin google_sign_in at /Users/taha/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.1/
[   +1 ms] Found plugin google_sign_in_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1+1/
[  +27 ms] Found plugin firebase_auth at
/Users/taha/AndroidStudioProjects/flutterfire/packages/firebase_auth/firebase_auth/
[  +64 ms] Generating
/Users/taha/AndroidStudioProjects/flutterfire/packages/firebase_auth/firebase_auth/example/android/app/src/main/java/io/
flutter/plugins/GeneratedPluginRegistrant.java
[  +82 ms] Launching lib/main.dart on Web Server in debug mode...
[  +60 ms] Updating assets
[ +181 ms] Syncing files to device Web Server...
[  +16 ms] Found plugin e2e at /Users/taha/.pub-cache/hosted/pub.dartlang.org/e2e-0.4.3+1/
[   +2 ms] Found plugin firebase_auth_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.3+1/
[        ] Found plugin firebase_core at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +1 ms] Found plugin firebase_core_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[        ] Found plugin firebase_dynamic_links at
/Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.5.1/
[   +1 ms] Found plugin google_sign_in at /Users/taha/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.1/
[   +1 ms] Found plugin google_sign_in_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1+1/
[  +20 ms] Found plugin firebase_auth at
/Users/taha/AndroidStudioProjects/flutterfire/packages/firebase_auth/firebase_auth/
[  +13 ms] Found plugin e2e at /Users/taha/.pub-cache/hosted/pub.dartlang.org/e2e-0.4.3+1/
[   +3 ms] Found plugin firebase_auth_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.3+1/
[        ] Found plugin firebase_core at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.5/
[   +1 ms] Found plugin firebase_core_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[        ] Found plugin firebase_dynamic_links at
/Users/taha/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-0.5.1/
[   +1 ms] Found plugin google_sign_in at /Users/taha/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.5.1/
[        ] Found plugin google_sign_in_web at /Users/taha/.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.9.1+1/
[  +20 ms] Found plugin firebase_auth at
/Users/taha/AndroidStudioProjects/flutterfire/packages/firebase_auth/firebase_auth/
[   +8 ms] Generating
/Users/taha/AndroidStudioProjects/flutterfire/packages/firebase_auth/firebase_auth/example/android/app/src/main/java/io/
flutter/plugins/GeneratedPluginRegistrant.java
[  +45 ms] <- reset
[   +7 ms] /Users/taha/Code/flutter_dev/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/taha/Code/flutter_dev/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/taha/Code/flutter_dev/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill
/var/folders/_j/4f81s2vs4_gdszjgwmy5h5740000gn/T/flutter_tools.8CaRuP/flutter_tool.QnXOcr/app.dill --libraries-spec
file:///Users/taha/Code/flutter_dev/bin/cache/flutter_web_sdk/libraries.json --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root
/var/folders/_j/4f81s2vs4_gdszjgwmy5h5740000gn/T/flutter_tools.8CaRuP/flutter_tools.TYXNxh --filesystem-scheme
org-dartlang-app --initialize-from-dill build/cache.dill.track.dill --platform
file:///Users/taha/Code/flutter_dev/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[   +7 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+2314 ms] ../lib/src/firebase_auth.dart:18:55: Error: Getter not found: 'Firebase'.
[   +1 ms]   static final FirebaseAuth instance = FirebaseAuth._(Firebase.app());
[        ]                                                       ^^^^^^^^
[+11458 ms] Syncing files to device Web Server... (completed in 13,918ms, longer than expected)
[        ] Synced 0.0MB.
[        ] Failed to compile application.
[   +3 ms] "flutter run" took 18,739ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:593:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:869:18)
           #3      _rootRunUnary (dart:async/zone.dart:1198:47)
           #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #12     _rootRunUnary (dart:async/zone.dart:1198:47)
           #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #19     _rootRun (dart:async/zone.dart:1190:13)
           #20     _CustomZone.run (dart:async/zone.dart:1093:19)
           #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +254 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +5 ms] Shutdown hooks complete
[        ] exiting with code 1
taha@Tahas-MacBook-Pro app % 
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (6 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 84.0.4147.89

• No issues found!

```

</details>

**Comment by fhidal01** [comment]
@TahaTesser you are getting same issue huh?

**Comment by Salakar** [comment]
Hey 👋 

Our rework of the `firebase_auth` plugin as part of the [FlutterFire roadmap](https://github.com/FirebaseExtended/flutterfire/issues/2582) was published over a week ago with a ton of fixes and new features. Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
