### ISSUE TITLE
[firebase_analytics] can not add firebase analytics for android flutter

### ISSUE THREAD

**Issue by humayuntanwar** [FirebaseExtended/flutterfire#3031]
**Describe the bug**
when creating a brand new flutter and firebase project and adding the dependency for firebase_anlytics module android app can not be built

**To Reproduce**
1. create new flutter flutter
2. create new firebase project
3. follow the guide to add firebase https://firebase.google.com/docs/flutter/setup?platform=android
4 build and run project on android device

**Expected behavior**
Application should launch on android device successfully.

***Error***

```
[ +887 ms] > Task :app:mergeDebugAssets FAILED
[ +100 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[        ] Execution failed for task ':app:mergeDebugAssets'.
[        ] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[        ]    > Could not download firebase-iid-interop-16.0.1.aar (com.google.firebase:firebase-iid-interop:16.0.1)
[        ]       > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid-interop/16.0.1/firebase-iid-interop-16.0.1.aar'.
[        ]          > Failed to move file 'C:\Users\humay\AppData\Local\Temp\gradle_download4061747990835146100bin' into filestore at
'com.google.firebase/firebase-iid-interop/16.0.1/8707ad5e1fdd9182313a5eb5edd16e1a839cdd75/firebase-iid-interop-16.0.1.aar' 
[   +1 ms]             > Failed to create directory
'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.firebase\firebase-iid-interop\16.0.1\8707ad5e1fdd9182313a5eb5edd16e1a839cdd75'
[   +1 ms]    > Could not download play-services-stats-16.0.1.aar (com.google.android.gms:play-services-stats:16.0.1)
[   +1 ms]       > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-stats/16.0.1/play-services-stats-16.0.1.aar'.
[   +1 ms]          > Failed to move file 'C:\Users\humay\AppData\Local\Temp\gradle_download4776169764270189491bin' into filestore at
'com.google.android.gms/play-services-stats/16.0.1/d5ca5898019c0913d163dbfeaa42b77b148716c/play-services-stats-16.0.1.aar' 
[   +1 ms]             > Failed to create directory
'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.android.gms\play-services-stats\16.0.1\d5ca5898019c0913d163dbfeaa42b77b148716c'
[   +1 ms]    > Could not download play-services-stats-16.0.1.aar (com.google.android.gms:play-services-stats:16.0.1)
[        ]       > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-stats/16.0.1/play-services-stats-16.0.1.aar'.
[        ]          > Failed to move file 'C:\Users\humay\AppData\Local\Temp\gradle_download276339117192968188bin' into filestore at
'com.google.android.gms/play-services-stats/16.0.1/d5ca5898019c0913d163dbfeaa42b77b148716c/play-services-stats-16.0.1.aar' 
[   +1 ms]             > Failed to create directory
'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.android.gms\play-services-stats\16.0.1\d5ca5898019c0913d163dbfeaa42b77b148716c'
[   +2 ms]    > Could not download play-services-stats-16.0.1.aar (com.google.android.gms:play-services-stats:16.0.1)
[        ]       > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-stats/16.0.1/play-services-stats-16.0.1.aar'.
[        ]          > Failed to move file 'C:\Users\humay\AppData\Local\Temp\gradle_download348843082829809947bin' into filestore at
'com.google.android.gms/play-services-stats/16.0.1/d5ca5898019c0913d163dbfeaa42b77b148716c/play-services-stats-16.0.1.aar' 
[   +1 ms]             > Failed to create directory
'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.android.gms\play-services-stats\16.0.1\d5ca5898019c0913d163dbfeaa42b77b148716c'
[   +1 ms]    > Could not download firebase-measurement-connector-17.0.1.aar (com.google.firebase:firebase-measurement-connector:17.0.1)
[        ]       > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-measurement-connector/17.0.1/firebase-measurement-connector-17.0.1.aar'.
[   +3 ms]          > Failed to move file 'C:\Users\humay\AppData\Local\Temp\gradle_download7076088740918663072bin' into filestore at
'com.google.firebase/firebase-measurement-connector/17.0.1/bcef3a812b71fb7e3faf15f6e3eda949c7455edc/firebase-measurement-connector-17.0.1.aar' 
[   +2 ms]             > Failed to create directory
'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.firebase\firebase-measurement-connector\17.0.1\bcef3a812b71fb7e3faf15f6e3eda949c7455edc'
[   +1 ms] * Try:
[   +4 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 25s
[   +1 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +1 ms] See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] 12 actionable tasks: 2 executed, 10 up-to-date
[ +705 ms] Running Gradle task 'assembleDebug'... (completed in 26.9s)
[   +7 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 28,623ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1192:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1184:13)
#29     _CustomZone.run (dart:async/zone.dart:1077:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.18362.900], locale en-US)
    • Flutter version 1.17.5 at F:\flutter_windows_v1.12.13+hotfix.9-stable\flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\humay\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\humay\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (1 available)
    • HUAWEI VNS L21 • 192.168.0.182:5555 • android-arm64 • Android 7.0 (API 24)

• No issues found!

```

Additional Info:
minSdkVersion 23 ---- added
apply plugin: 'com.google.gms.google-services' ----added
classpath 'com.google.gms:google-services:4.3.3' ----added
google() ----added

plugin used:
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16

**Comment by darshankawar** [comment]
Hi @humayuntanwar,
Are you able to build by removing `firebase_analytics` plugin ? I recently created a new Flutter project and added same plugin and have been able to build successfully.
I also noticed you used `Huawei` device to build. Can you try on another device or emulator and see if you still experience the issue ?
Thanks.

**Comment by humayuntanwar** [comment]
build is successful on the huawei device if i comment out the analytics plugin, i have tested with firebase core, auth both plugins are building on huawei device.

tested on pixel 2 emulator, same error with analytics enabled
 detailed logs https://pastebin.com/QM0qhyGq

can you share your project with me.

```

Plugin project :firebase_core_web not found. Please update settings.gradle.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not download firebase-iid-interop-16.0.1.aar (com.google.firebase:firebase-iid-interop:16.0.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-iid-interop/16.0.1/firebase-iid-interop-16.0.1.aar'.
         > Failed to move file 'C:\Users\humay\AppData\Local\Temp\gradle_download7575188163180828524bin' into filestore at 'com.google.firebase/firebase-iid-interop/16.0.1/8707ad5e1fdd9182313a5eb5edd16e1a839cdd75/firebase-iid-interop-16.0.1.aar' 
            > Failed to create directory 'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.firebase\firebase-iid-interop\16.0.1\8707ad5e1fdd9182313a5eb5edd16e1a839cdd75'
   > Could not download play-services-stats-16.0.1.aar (com.google.android.gms:play-services-stats:16.0.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-stats/16.0.1/play-services-stats-16.0.1.aar'.
         > Failed to move file 'C:\Users\humay\AppData\Local\Temp\gradle_download7188279326640515141bin' into filestore at 'com.google.android.gms/play-services-stats/16.0.1/d5ca5898019c0913d163dbfeaa42b77b148716c/play-services-stats-16.0.1.aar' 
            > Failed to create directory 'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.android.gms\play-services-stats\16.0.1\d5ca5898019c0913d163dbfeaa42b77b148716c'
   > Could not download play-services-stats-16.0.1.aar (com.google.android.gms:play-services-stats:16.0.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-stats/16.0.1/play-services-stats-16.0.1.aar'.
         > Failed to move file 'C:\Users\humay\AppData\Local\Temp\gradle_download5591133629286866630bin' into filestore at 'com.google.android.gms/play-services-stats/16.0.1/d5ca5898019c0913d163dbfeaa42b77b148716c/play-services-stats-16.0.1.aar' 
            > Failed to create directory 'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.android.gms\play-services-stats\16.0.1\d5ca5898019c0913d163dbfeaa42b77b148716c'
   > Could not download play-services-stats-16.0.1.aar (com.google.android.gms:play-services-stats:16.0.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-stats/16.0.1/play-services-stats-16.0.1.aar'.
         > Failed to move file 'C:\Users\humay\AppData\Local\Temp\gradle_download5554925023036776783bin' into filestore at 'com.google.android.gms/play-services-stats/16.0.1/d5ca5898019c0913d163dbfeaa42b77b148716c/play-services-stats-16.0.1.aar' 
            > Failed to create directory 'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.android.gms\play-services-stats\16.0.1\d5ca5898019c0913d163dbfeaa42b77b148716c'
   > Could not download firebase-measurement-connector-17.0.1.aar (com.google.firebase:firebase-measurement-connector:17.0.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/google/firebase/firebase-measurement-connector/17.0.1/firebase-measurement-connector-17.0.1.aar'.
         > Failed to move file 'C:\Users\humay\AppData\Local\Temp\gradle_download1440558496378249911bin' into filestore at 'com.google.firebase/firebase-measurement-connector/17.0.1/bcef3a812b71fb7e3faf15f6e3eda949c7455edc/firebase-measurement-connector-17.0.1.aar' 
            > Failed to create directory 'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.firebase\firebase-measurement-connector\17.0.1\bcef3a812b71fb7e3faf15f6e3eda949c7455edc'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 47s
Exception: Gradle task assembleDebug failed with exit code 1

```

can you help identify issue here

**Comment by darshankawar** [comment]
Hi @humayuntanwar,
I again created a new project and added firebase to it and then added `firebase_analytics` plugin to it and I was able to build successfully. 
I am leaving this issue open for further analysis.

**Comment by kroikie** [comment]
@humayuntanwar It looks like gradle is not able to create the needed directories for the analytics dependencies.

For example:
`> Failed to create directory 'C:\Users\humay\.gradle\caches\modules-2\files-2.1\com.google.firebase\firebase-iid-interop\16.0.1\8707ad5e1fdd9182313a5eb5edd16e1a839cdd75'`

I would try deleting `C:\Users\humay\.gradle\caches` and try the build again.

**Comment by humayuntanwar** [comment]
deleting .gradle folder worked.
project running on both emulator and huawei device.
thanks.
