### ISSUE TITLE
[cloud_firestore] Flutter Web: "TypeError: Cannot read property 'app' of undefined"

### ISSUE THREAD

**Issue by maxmoros** [FirebaseExtended/flutterfire#3073]
**Describe the bug**
Flutter Web crashed when adding cloud_firestore to pubspec.yaml with updating the index.html as described in documentation.
I need this plugin for access to my database.

```
TypeError: Cannot read property 'app' of undefined
    at Object.app$ [as app] (http://localhost:61837/packages/firebase/src/top_level.dart.lib.js:78:89)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:61837/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:688:57)
    at Function.registerWith (http://localhost:61837/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:624:73)
    at Object.registerPlugins (http://localhost:61837/packages/the_basics/generated_plugin_registrant.dart.lib.js:15:46)
    at main (http://localhost:61837/web_entrypoint.dart.lib.js:29:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:61837/dart_sdk.js:37369:34)
    at Object._async [as async] (http://localhost:61837/dart_sdk.js:37400:7)
    at main$ (http://localhost:61837/web_entrypoint.dart.lib.js:28:18)
    at http://localhost:61837/main_module.bootstrap.js:20:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:61837/main_module.bootstrap.js:19:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:61837/dwds/src/injected/client.js:8758:21)
    at http://localhost:61837/dwds/src/injected/client.js:22459:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:61837/dwds/src/injected/client.js:3802:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:61837/dwds/src/injected/client.js:10996:12)
    at Object._asyncStartSync (http://localhost:61837/dwds/src/injected/client.js:3766:20)
    at main__closure1.$call$body$main__closure (http://localhost:61837/dwds/src/injected/client.js:22471:16)
    at main__closure1.call$1 (http://localhost:61837/dwds/src/injected/client.js:22398:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:61837/dwds/src/injected/client.js:4136:16)
    at _CustomZone.runUnary$2$2 (http://localhost:61837/dwds/src/injected/client.js:12301:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:61837/dwds/src/injected/client.js:12233:14)
    at _ControllerSubscription._sendData$1 (http://localhost:61837/dwds/src/injected/client.js:11784:19)
    at _DelayedData.perform$1 (http://localhost:61837/dwds/src/injected/client.js:11936:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:61837/dwds/src/injected/client.js:11985:14)
    at Object._microtaskLoop (http://localhost:61837/dwds/src/injected/client.js:3969:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:61837/dwds/src/injected/client.js:3975:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:61837/dwds/src/injected/client.js:10865:9)
    at invokeClosure (http://localhost:61837/dwds/src/injected/client.js:1204:26)
    at MutationObserver.<anonymous> (http://localhost:61837/dwds/src/injected/client.js:1223:18)
```

**To Reproduce**
index.html:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>the_basics</title>
</head>
<body id="app-container">
  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-app.js"></script>

  <!-- TODO: Add SDKs for Firebase products that you want to use
      https://firebase.google.com/docs/web/setup#available-libraries -->
  <script src="https://www.gstatic.com/firebasejs/7.17.1/firebase-analytics.js"></script>

  <script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
      apiKey: ,
      authDomain: ,
      databaseURL: ,
      projectId: ,
      storageBucket: ,
      messagingSenderId:,
      appId:,
      measurementId:
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```

pubspec.yaml dependancies:
```
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  responsive_builder: ^0.1.4
  get_it:
  provider_architecture:
  provider: ^3.1.0
  http: ^0.12.0+2
  firebase: ^7.3.0
  # firebase_core: "0.5.0-dev.2"
  cloud_firestore: 0.14.0-dev.1
  cached_network_image: ^2.2.0+1
  firebase_auth:
  firebase_auth_web:

dev_dependencies:
  flutter_test:
    sdk: flutter
```

**Expected behavior**
I expected that cloud_firestore for flutter web would work if following the documentation for initialization.

**Additional context**
The application builds fine if I remove cloud_firestore from the pubspec.yaml

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.117, on Mac OS X 10.15.5 19F2200, locale en-CA)
    • Flutter version 1.21.0-6.0.pre.117 at /Users/maksymmoros/development/flutter
    • Framework revision 7ec2d360bc (2 days ago), 2020-07-29 23:25:38 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/maksymmoros/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

**Comment by kroikie** [comment]
@maxmoros could you try adding the Firestore js SDK dependency to your index.html file?

`<script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-firestore.js"></script>`

**Comment by maxmoros** [comment]
Same issue persists with the Firestore SDK included

**Comment by maxmoros** [comment]
I also found that commenting out:
```FirestoreWeb.registerWith(registry.registrarFor(FirestoreWeb));```
from the generated_plugin_registrant.dart file fixes the crash but also causes the plugin to not work...

**Comment by greghesp** [comment]
@maxmoros Can you provide a minimum code sample please?

I can't replicate this issue on my side by just adding ` cloud_firestore: "0.14.0-dev.1"` my `pubspec`

```
  firebase: ^7.3.0
  cloud_firestore: "0.14.0-dev.1"
```

```
  <script src="https://www.gstatic.com/firebasejs/7.15.5/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.15.5/firebase-firestore.js"></script>
  <script>
    var firebaseConfig = {
      apiKey: "",
      databaseURL: "",
      authDomain: "",
      projectId: "",
      storageBucket: "",
      messagingSenderId: "",
      appId: ""
    };

    firebase.initializeApp(firebaseConfig);
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
```

**Comment by maxmoros** [comment]
I fixed the issue. 
I created a new project and copied all the files and dependancies in. All works now. Don't know why, but I'm happy :)
