### ISSUE TITLE
[Cloud Firestore]  App crashes in some devices - API 23 Android, due to some issue in Cloud Firestore.

### ISSUE THREAD

**Issue by missiorex** [FirebaseExtended/flutterfire#3155]
**Describe the bug**
The app crashes in Android release build specifically API 23. The error points to some issue with Cloud Firestore plugin.
The issue reproduced in Moto G4 Play, LG K3 and few more.

**To Reproduce**
1. Open the app with some calls to cloud firestore using listeners.
2.FATAL EXCEPTION:
java.lang.OutOfMemoryError: Failed to allocate a 18263534 byte allocation with 13846296 free bytes and 13MB until OOM
	at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
	at io.flutter.plugin.common.StandardMessageCodec.writeBytes()
	at io.flutter.plugin.common.StandardMessageCodec.writeValue()
	at io.flutter.plugins.firebase.cloudfirestore.FirestoreMessageCodec.writeValue()
	at io.flutter.plugin.common.StandardMessageCodec.writeValue()
	at io.flutter.plugins.firebase.cloudfirestore.FirestoreMessageCodec.writeValue()
	at io.flutter.plugin.common.StandardMessageCodec.writeValue()
	at io.flutter.plugins.firebase.cloudfirestore.FirestoreMessageCodec.writeValue()
	at io.flutter.plugin.common.StandardMessageCodec.writeValue()
	at io.flutter.plugins.firebase.cloudfirestore.FirestoreMessageCodec.writeValue()
	at io.flutter.plugin.common.StandardMethodCodec.encodeMethodCall()
	at io.flutter.plugin.common.MethodChannel.invokeMethod()
	at io.flutter.plugin.common.MethodChannel.invokeMethod()
	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent()
	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent()
	at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2()
	at com.google.firebase.firestore.Query$$Lambda$3.onEvent()
	at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0()
	at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run()
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5459)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Expected behavior**
The App shouldn't crash.

**Additional context**

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-IN)
    • Flutter version 1.20.1 at
      /Users/prakashgeorge/Documents/CreativeColts/Projects/flutter
    • Framework revision 2ae34518b8 (6 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/prakashgeorge/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Moto G 5 Plus (mobile) • ZY2245BFXF • android-arm • Android 8.1.0 (API 27)
```

**Comment by missiorex** [comment]
Downgrading cloud_firestore to 0.13.4+2 based on some suggestions in related issues also didn't help.

**Comment by Ehesp** [comment]
Could you show us your pubspec file please?

**Comment by missiorex** [comment]
environment:
    sdk: ">=2.0.0-dev.68.0 <3.0.0"

  dependencies:
    flutter:
      sdk: flutter
    animated_background: "^1.0.1"
    base_helpers:
      path: ../helpers
    bubble_tab_indicator: "^0.1.3"
    cached_network_image: "^2.0.0-rc"
    carousel_slider: "^1.3.0"
    connectivity: "^0.4.8+2"
    country_code_picker:
      path: ../country_code_picker
    chewie: "0.9.10"
    cloud_firestore: "^0.12.7"
    mem_repository:
      path: ../mem_repository
    mem_blocs:
      path: ../mem_blocs
    mem_models:
      path: ../mem_models
    mem_entities:
      path: ../mem_entities
    mem_repository_firebase:
      path: ../mem_repository_firebase
    firebase_auth: "^0.11.1+8"
    firebase_messaging: "^5.0.4"
    firebase_database: "3.0.6"
    indexed_list_view : "^0.0.4"
    firebase_storage: "^3.0.0"
    firebase_remote_config: "0.2.0+3"
    image_picker: "^0.6.7+4"
    flutter_native_image: "^0.0.5+2"
    flutter_local_notifications: "^0.8.1+1"
    flutter_localizations:
      sdk: flutter
    http: ^0.12.1
    intl: "^0.16.0"
    liquid_progress_indicator: 0.3.2
    package_info: "^0.4.0+16"
    path_provider: "^0.5.0"
    recase: "^2.0.0+1"
    share: "0.6.3+6"
    shared_preferences: "^0.5.6+3"
    shimmer: "^1.0.0"
    url_launcher: "^5.1.4"
    video_player: "0.10.11+1"
    fluro: "^1.3.1"
    flutter_speed_dial: "^1.1.1"
    flutter_linkify: "^2.1.0"
    youtube_player_flutter: "7.0.0+3"
    emoji_picker :
      path: ../mem_emoji_picker
    font_awesome_flutter: "^8.0.1"


  dev_dependencies:
    flutter_launcher_icons: "^0.7.2"
    flutter_driver:
      sdk: flutter
    flutter_test:
      sdk: flutter
    mockito: "3.0.0"

  flutter_icons:
    android: "ic_launcher"
    ios: false
    image_path: "assets/logo/logo.png"
    adaptive_icon_background: "#ffffff"

**Comment by darshankawar** [comment]
Hi @missiorex,
Can you upgrade all firebase plugins you are using to respective latest versions, try again and see if it works for you ?
If problem persists, please provide a minimal complete reproducible code sample that shows the issue.
Thanks.
