### ISSUE TITLE
[cloud_firestore] WEB Multiple 'where' on a Query doesn't work

### ISSUE THREAD

**Issue by vixez** [FirebaseExtended/flutterfire#3177]
**Describe the bug**
When chaining multiple `where` on Flutter web, it results in an error. A single `where` works.
This is only the case on Flutter web, on Android it works fine.

**To Reproduce**
For example (trimmed code):

```
  CollectionReference get _sessionsReference {
    return firestore
        ?.collection('logs')
        ?.doc(Log.environment.name)
        ?.collection('sessions');
  }

  Query query = _sessionsReference;

  if (userId?.isEmpty == false) {
    query = query?.where(UserSession.kFSUserId, isEqualTo: userId);
  }

  if (country?.isEmpty == false) {
    query = query?.where(UserSession.kFSCountry, isEqualTo: country);
  }

  (await query?.get())?.docs;
```

Works when:
`userId` is not empty, and `country` is empty
`userId` is empty, and `country` is not empty
`userId` is empty, and `country` is empty

Does not work when:
`userId` is not empty, and `country` is not empty

So when chaining two or more `where`'s the query fails with the following error:

```
Error: Expected a value of type 'FieldPath', but got one of type 'NativeJavaScriptObject'
    at Object.throw_ [as throw] (http://localhost:60848/dart_sdk.js:4322:11)
    at Object.castError (http://localhost:60848/dart_sdk.js:4293:15)
    at Object.cast [as as] (http://localhost:60848/dart_sdk.js:4609:17)
    at dart.LegacyType.new.as (http://localhost:60848/dart_sdk.js:6151:60)
    at cloud_firestore.Query.__.where (http://localhost:60848/packages/cloud_firestore/cloud_firestore.dart.lib.js:338:34)
    at search_firestore.SearchFirestore.new._performSearch (http://localhost:60848/packages/api_core/src/utils/api_access.dart.lib.js:658:61)
    at _performSearch.next (<anonymous>)
    at runBody (http://localhost:60848/dart_sdk.js:37231:34)
    at Object._async [as async] (http://localhost:60848/dart_sdk.js:37262:7)
    at search_firestore.SearchFirestore.new.[_performSearch] (http://localhost:60848/packages/api_core/src/utils/api_access.dart.lib.js:651:20)
    at search_firestore.SearchFirestore.new.getUserSessions (http://localhost:60848/packages/api_core/src/utils/api_access.dart.lib.js:632:50)
    at getUserSessions.next (<anonymous>)
    at runBody (http://localhost:60848/dart_sdk.js:37231:34)
    at Object._async [as async] (http://localhost:60848/dart_sdk.js:37262:7)
    at search_firestore.SearchFirestore.new.getUserSessions (http://localhost:60848/packages/api_core/src/utils/api_access.dart.lib.js:630:20)
    at search_page._SearchPageState.new.<anonymous> (http://localhost:60848/packages/logging_example_app/search_page.dart.lib.js:1558:65)
    at Generator.next (<anonymous>)
```

**Expected behavior**
Being able to chain multiple `where`

**Flutter doctor**
```
[✓] Flutter (Channel beta, 1.20.0-7.4.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[!] VS Code (version 1.47.3)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
 
[✓] Connected device (3 available)            

! Doctor found issues in 1 category.
```

**Comment by vixez** [comment]
i did some more testing. It seems like this issue is only in the prerelease version (0.14.0-dev.1). When stable (0.13.7) it works fine on web.

**Comment by rodrigoaguilar** [comment]
I'm seeing the same issue.

**Comment by Ehesp** [comment]
Thanks for reporting, this has been fixed in the linked PR above - will release soon.

**Comment by Ehesp** [comment]
@vixez Just a follow up, whats your use-case for doing multiple wheres with a documentId? That would always return zero results.

This is still an issue, just wondering on your use-case?

**Comment by vixez** [comment]
@Ehesp I'm doing multiple where's on a collection called `sessions`.

`kFSUserId` = `user_id` field in Firestore document

`kFSCountry` = `country` field in Firestore document

So in this case I would be looking for all sessions with a certain `user_id` and `country`.
