### ISSUE TITLE
[messaging] Crash with embedding v2 and onBackgroundMessage

### ISSUE THREAD

**Issue by MTRNord** [FirebaseExtended/flutterfire#3187]
**Describe the bug**
Firebase Messaging throws the following error when calling configure with a onBackgroundMessage argument present:

```
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): java.lang.RuntimeException: PluginRegistrantCallback is not set.
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:157)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onMethodCall(FirebaseMessagingPlugin.java:176)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/MethodChannel#plugins.flutter.io/firebase_messaging(15821): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

As I expect that I get the issue closed because you dont see it in the example: You do not set onBackgroundMessage in the example. Which is why it works in the example. See https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/example/lib/main.dart#L141

**To Reproduce**
1. Setup the firebase plugin with onBackgroundMessage and embedding v2

**Expected behavior**
No Crash

**Flutter doctor**

```
PS C:\Users\marce\StudioProjects\famedly> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.20.2, on Microsoft Windows [Version 10.0.20180.1000], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.
[√] Chrome - develop for the web
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.48.0)
[√] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by MTRNord** [comment]
Seems like I also get after full app close this:

```
E/AndroidRuntime(20277): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate(FlutterFirebaseMessagingService.java:77)
E/AndroidRuntime(20277): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4083)
E/AndroidRuntime(20277): 	... 8 more
I/Process (20277): Sending signal. PID: 20277 SIG: 9
E/AndroidRuntime(20386): FATAL EXCEPTION: main
E/AndroidRuntime(20386): Process: com.famedly.talk, PID: 20386
E/AndroidRuntime(20386): java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
E/AndroidRuntime(20386): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4095)
E/AndroidRuntime(20386): 	at android.app.ActivityThread.access$1900(ActivityThread.java:231)
E/AndroidRuntime(20386): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1981)
E/AndroidRuntime(20386): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(20386): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(20386): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
E/AndroidRuntime(20386): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20386): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(20386): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(20386): Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
E/AndroidRuntime(20386): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:189)
E/AndroidRuntime(20386): 	at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:85)
E/AndroidRuntime(20386): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate(FlutterFirebaseMessagingService.java:71)
E/AndroidRuntime(20386): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4083)
E/AndroidRuntime(20386): 	... 8 more
```

**Comment by MTRNord** [comment]
Nvm 
Duplicate of #1754
