### ISSUE TITLE
[firebase_auth] web signInWithPhoneNumber method throws TypeError: Cannot read property 'Symbol(dartx.isEmpty)' of undefined

### ISSUE THREAD

**Issue by erabti** [FirebaseExtended/flutterfire#3188]
**Describe the bug**
When I try to sign in with phone number on Flutter Web I get this error:

**To Reproduce**
1. Create a new Flutter project
2. Try to call signInWithPhoneNumber on FirebaseAuth instance

**Expected behavior**
To sign in via reCAPTCHA.

**Additional context**
firebase_auth version: ^0.18.0-dev.2

**Flutter doctor**
[✓] Flutter (Channel beta, 1.20.2, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (3 available)

• No issues found!

```
TypeError: Cannot read property 'Symbol(dartx.isEmpty)' of undefined
    at dart._StackTrace.new.toString (http://localhost:38371/dart_sdk.js:6940:16)
    at Object.str (http://localhost:38371/dart_sdk.js:4751:54)
    at dev_log.DevLog.new.onValue (http://localhost:38371/packages/core/src/presentation/widgets/text_button.dart.lib.js:3012:74)
    at _RootZone.runUnaryGuarded (http://localhost:38371/dart_sdk.js:36991:11)
    at _BroadcastSubscription.new.[_sendData] (http://localhost:38371/dart_sdk.js:30600:22)
    at _BroadcastSubscription.new.[_add] (http://localhost:38371/dart_sdk.js:30546:26)
    at _SyncBroadcastStreamController.new.[_sendData] (http://localhost:38371/dart_sdk.js:31268:34)
    at _SyncBroadcastStreamController.new.add (http://localhost:38371/dart_sdk.js:31062:24)
    at logger.Logger._internal.[_publish] (http://localhost:38371/packages/logging/src/logger.dart.lib.js:192:27)
    at logger.Logger._internal.log (http://localhost:38371/packages/logging/src/logger.dart.lib.js:146:25)
    at logger.Logger._internal.severe (http://localhost:38371/packages/logging/src/logger.dart.lib.js:177:19)
    at dev_log.DevLog.new.severe (http://localhost:38371/packages/core/src/presentation/widgets/text_button.dart.lib.js:3024:29)
    at login_provider.LoginStateNotifier.new.startOTPProcess (http://localhost:38371/packages/login/src/application/login_provider.dart.lib.js:404:24)
    at startOTPProcess.throw (<anonymous>)
    at http://localhost:38371/dart_sdk.js:37217:38
    at _RootZone.runBinary (http://localhost:38371/dart_sdk.js:37070:58)
    at _FutureListener.thenAwait.handleError (http://localhost:38371/dart_sdk.js:32061:48)
    at handleError (http://localhost:38371/dart_sdk.js:32612:51)
    at Function._propagateToListeners (http://localhost:38371/dart_sdk.js:32638:17)
    at _Future.new.[_completeError] (http://localhost:38371/dart_sdk.js:32485:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:38371/dart_sdk.js:32523:31)
    at Object._microtaskLoop (http://localhost:38371/dart_sdk.js:37326:13)
    at _startMicrotaskLoop (http://localhost:38371/dart_sdk.js:37332:13)
    at http://localhost:38371/dart_sdk.js:32851:9
```

**Comment by Ehesp** [comment]
@erabti Taking a look - however unfortunately phone number sign-in is not yet supported on web, so this should throw an unimplemented error.

**Comment by Ehesp** [comment]
Good news! I managed to fix/hack a long standing issue with Flutter web to get things working. Working on a PR for this over the next couple of days.
