### ISSUE TITLE
[firebase_auth] unknown exception code when attempting to login multiple times

### ISSUE THREAD

**Issue by erabti** [FirebaseExtended/flutterfire#3194]
**Describe the bug**
The `FirebaseException` code is `unknown`.

**To Reproduce**
1. Create new flutter project with firebase auth included.
2. Attempt to login with email and password multiple times incorrectly.
3. An `unknown` exception is thrown

**Expected behavior**
Code of 'too-many-requests' or something similar with the FirebaseException.
So we can show proper error to users.

**Additional context**
firebase_auth: ^0.18.0-dev.2

**Flutter doctor**
Run `flutter doctor` and paste the output below:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.20.2, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (3 available)

• No issues found!
```

```
I/flutter ( 4343): [firebase_auth/unknown] com.google.firebase.FirebaseTooManyRequestsException: We have blocked all
I/flutter ( 4343): requests from this device due to unusual activity. Try again later. [ Too many unsuccessful login
I/flutter ( 4343): attempts. Please try again later. ]: #0      catchPlatformException
I/flutter ( 4343): (package:firebase_auth_platform_interface/src/method_channel/utils/exception.dart:20:3)
I/flutter ( 4343): #1      _rootRunUnary (dart:async/zone.dart:1198:47)
I/flutter ( 4343): #2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
I/flutter ( 4343): #3      _FutureListener.handleError (dart:async/future_impl.dart:160:20)
I/flutter ( 4343): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
I/flutter ( 4343): #5      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
I/flutter ( 4343): #6      Future._completeError (dart:async/future_impl.dart:537:5)
I/flutter ( 4343): #7      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
I/flutter ( 4343): #8      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart)
I/flutter ( 4343): <asynchronous suspension>
I/flutter ( 4343): #9      MethodChannelFirebaseAuth.signInWithEmailAndPassword (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:420:47)
I/flutter ( 4343): #10     FirebaseAuth.signInWithEmailAndPassword (package:firebase_auth/src/firebase_auth.dart:491:31)
```

**Comment by TahaTesser** [comment]
Hi @erabti 
Tried to login incorrectly but in my case, it only returns `firebase_auth/user-not-found`, not throwing `FirebaseTooManyRequestsException` even after spamming, it should correctly throw exception and also not unknown 

Using [example](https://github.com/invertase/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) 
```
  firebase_auth: ^0.18.0-dev.2
  firebase_core: ^0.5.0-dev.2
  google_sign_in: ^4.5.1
  firebase_dynamic_links: ^0.5.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_signin_button: ^1.0.0
  uuid: ^2.2.0
```

<details> 
<summary>logs</summary> 

```
D/ViewRootImpl@9ce3e3e[MainActivity](31363): stopped(false) old=true
D/SurfaceView(31363): windowStopped(false) true io.flutter.embedding.android.FlutterSurfaceView{a20e9ec V.E...... ........ 0,0-1080,2301} of ViewRootImpl@9ce3e3e[MainActivity]
D/SurfaceView(31363): surfaceCreated 1 #1 io.flutter.embedding.android.FlutterSurfaceView{a20e9ec V.E...... ........ 0,0-1080,2301}
D/mali_winsys(31363): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView(31363): surfaceChanged (1080,2301) 1 #1 io.flutter.embedding.android.FlutterSurfaceView{a20e9ec V.E...... ........ 0,0-1080,2301}
D/ViewRootImpl@9ce3e3e[MainActivity](31363): stopped(false) old=false
D/SurfaceView(31363): onWindowVisibilityChanged(0) true io.flutter.embedding.android.FlutterSurfaceView{a20e9ec V.E...... ......ID 0,0-1080,2301} of ViewRootImpl@9ce3e3e[MainActivity]
W/libEGL  (31363): EGLNativeWindowType 0x7914711b10 disconnect failed
D/ViewRootImpl@9ce3e3e[MainActivity](31363): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=8 res=0x40001 s={true 520034062336} ch=false
D/OpenGLRenderer(31363): createReliableSurface : 0x7914711b00, 0x7914721000
D/mali_winsys(31363): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/ViewRootImpl@9ce3e3e[MainActivity](31363): MSG_RESIZED_REPORT: frame=(0,0,1080,2340) ci=(0,83,0,39) vi=(0,83,0,39) or=1
D/ViewRootImpl@9ce3e3e[MainActivity](31363): MSG_RESIZED: frame=(0,0,1080,2340) ci=(0,83,0,867) vi=(0,83,0,867) or=1
D/ViewRootImpl@9ce3e3e[MainActivity](31363): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(31363): prepareNavigationBarInfo() DecorView@3cc4f2[MainActivity]
D/InputMethodManager(31363): getNavigationBarColor() -855310
D/InputMethodManager(31363): prepareNavigationBarInfo() DecorView@3cc4f2[MainActivity]
D/InputMethodManager(31363): getNavigationBarColor() -855310
V/InputMethodManager(31363): Starting input: tba=com.nevercode.triage ic=io.flutter.plugin.editing.InputConnectionAdaptor@3eb942c mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(31363): startInputInner - Id : 0
I/InputMethodManager(31363): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(31363): Input channel destroyed: 'ClientS', fd=95
D/ViewRootImpl@9ce3e3e[MainActivity](31363): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=14 res=0x40001 s={true 520034062336} ch=false
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
W/DynamiteModule(31363): Local module descriptor class for com.google.firebase.auth not found.
I/FirebaseAuth(31363): [FirebaseAuth:] Preparing to create service connection to gms implementation
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
I/flutter (31363): [firebase_auth/user-not-found] There is no user record corresponding to this identifier. The user may have been deleted.
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 0
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme pointer 1
I/BiChannelGoogleApi(31363): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@72efd98
D/ViewRootImpl@9ce3e3e[MainActivity](31363): ViewPostIme poi
``` 

</details>

**Comment by DanGerHOGGISH** [comment]
Hi i have the same problem. Can you please checkout the new version of the firebase_auth: ^0.18.0 it was updated yesterday and it needs 
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(AppName());
}

**Comment by Salakar** [comment]
Confirmed bug with the error codes being unknown on Android. I'll push a fix for this today
