### ISSUE TITLE
[Firebase messaging] onBackgroundMessage on iOS

### ISSUE THREAD

**Issue by csarigumba** [FirebaseExtended/flutterfire#3240]
Hi, does `onBackgroundMessage()` now works with iOS? I tried to configure it but I'm getting an error below.

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method FcmDartService#start on channel plugins.flutter.io/firebase_messaging)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>                                               
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      FirebaseMessaging.configure (package:firebase_messaging/firebase_messaging.dart:130:16)
#3      FCMProvider.initialise (package:ptflutter/src/resources/fcm_provider.dart:32:10)
#4      PushNotificationRepository.initializePushNotification (package:ptflutter/src/resources/push_notification_repository.dart:8:24)
#5      FCMBloc.mapEventToState (package:ptflutter/src/bloc/fcm/fcm_bloc.dart:29:40)
#6      _AsyncStarStreamController.runBody (dart:async-patch/async_patch.dart:162:18)
#7      _rootRun (dart:async/zone.dart:1180:38)                         
#8      _CustomZone.run (dart:async/zone.dart:1077:19)                  
#9      _CustomZone.r<…>       
```

Please advise.

**Comment by csarigumba** [comment]
@TahaTesser I read your comment here, https://github.com/FirebaseExtended/flutterfire/issues/2823#issuecomment-650114360.

Question, how can wehandle onBackgroundMessage in iOS? Please help.

**Comment by russellwheatley** [comment]
Closing in favour of trying the latest messaging version which has been been heavily reworked, along with documentation, since this issue was raised: [https://firebase.flutter.dev/docs/messaging/overview](https://firebase.flutter.dev/docs/messaging/overview)If you still have a problem please raise a new GitHub issue with up to date information and code snippets if possible. Thanks.
