### ISSUE TITLE
[firebase_auth]  Exception being thrown by sendSignInLinkToEmail

### ISSUE THREAD

**Issue by lfv89** [FirebaseExtended/flutterfire#3259]
**Describe the bug**

```
E/flutter ( 7062): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: [firebase_auth/unknown] java.lang.Integer cannot be cast to java.lang.String
E/flutter ( 7062): #0      catchPlatformException (package:firebase_auth_platform_interface/src/method_channel/utils/exception.dart:20:3)
E/flutter ( 7062): #1      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 7062): #2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 7062): #3      _FutureListener.handleError (dart:async/future_impl.dart:159:20)
E/flutter ( 7062): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:698:47)
E/flutter ( 7062): #5      Future._propagateToListeners (dart:async/future_impl.dart:719:24)
E/flutter ( 7062): #6      Future._completeError (dart:async/future_impl.dart:534:5)
E/flutter ( 7062): #7      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
E/flutter ( 7062): #8      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter ( 7062): <asynchronous suspension>
E/flutter ( 7062): #9      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 7062): #10     MethodChannelFireb
aseAuth.sendSignInLinkToEmail (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:338:10)
E/flutter ( 7062): #11     FirebaseAuth.sendSignInLinkToEmail (package:firebase_auth/src/firebase_auth.dart:301:21)
E/flutter ( 7062): #12     _SplashScreenState.handleSubmit (package:mobile/screens/splash_screen.dart:63:42)
E/flutter ( 7062): #13     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 7062): #14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 7062): #15     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 7062): #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
E/flutter ( 7062): #17     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
E/flutter ( 7062): #18     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:391:9)
E/flutter ( 7062): #19     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 7062): #20     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 7062): #21     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 7062): #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 7062): #23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 7062): #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 7062):
```

**To Reproduce**

Invoke `sendSignInLinkToEmail( ... )`

**Expected behavior**

Not to throw an error

**Additional context**

Happening in `0.18.0` and `0.18.0+1`

**Flutter doctor**

Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel dev, 1.19.0-0.0.pre, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
[!] Android Studio (not installed)
[!] VS Code (version 1.47.3)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)
```

**Comment by Salakar** [comment]
Could you confirm what args you're passing to the `sendSignInLinkToEmail` method? Thanks

**Comment by lfv89** [comment]
Hey, 

Thanks for the fast reply.

I was using them wrong indeed.

I was using `android { minimumVersion } ` with an `int` and not with a `String`. Not a bug then, but maybe the error could have been a little bit more friendly?!

**Comment by Salakar** [comment]
Re-opening as this shouldn't be allowed either way - there should be some validation in Dart or at least have typed properties so this doesn't happen

**Comment by Ehesp** [comment]
Added a PR for this - let me know what you think!

**Comment by Salakar** [comment]
Fix merged, pending release. Thanks
