### ISSUE TITLE
A problem occurred configuring project ':cloud_firestore_web' failed  flutter run --release

### ISSUE THREAD

**Issue by sampathkumar7** [FirebaseExtended/flutterfire#3285]
```
[  +22 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +66 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[   +1 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +79 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.9-0-gf139b11009
[   +6 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +49 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] fatal: HEAD does not point to a branch
[  +12 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +77 ms] executing: C:\Users\xxx\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +31 ms] Exit code 0 from: C:\Users\xxx\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           315bbc84               device product:OnePlus6T model:ONEPLUS_A6010 device:OnePlus6T transport_id:1
[  +17 ms] C:\Users\xxx\AppData\Local\Android\sdk\platform-tools\adb.exe -s 315bbc84 shell getprop
[ +164 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +39 ms] Found plugin admob_flutter at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\admob_flutter-0.3.3\
[  +26 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.14.0+2\
[   +6 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.2.0+1\
[  +18 ms] Found plugin facebook_audience_network at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\facebook_audience_network-0.6.2\
[  +12 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.18.0+1\
[   +8 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.0+1\
[  +14 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[  +28 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[  +17 ms] Found plugin firebase_messaging at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-7.0.0\
[   +3 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-4.0.0\
[  +20 ms] Found plugin flutter_facebook_login at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-2.0.1\
[  +22 ms] Found plugin flutter_inapp_purchase at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inapp_purchase-2.2.0\
[  +14 ms] Found plugin flutter_local_notifications at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-0.8.2\
[   +2 ms] Found plugin flutter_native_admob at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_native_admob-2.1.0\
[  +11 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-3.1.3\
[  +30 ms] Found plugin image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.1+4\
[  +34 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.10\
[   +2 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+1\
[  +15 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[  +12 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +8 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[   +2 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[   +5 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.0+2\
[ +386 ms] Found plugin admob_flutter at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\admob_flutter-0.3.3\
[  +10 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.14.0+2\
[  +12 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.2.0+1\
[  +11 ms] Found plugin facebook_audience_network at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\facebook_audience_network-0.6.2\
[  +17 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.18.0+1\
[  +17 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.0+1\
[  +15 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.5.0\
[  +11 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[   +3 ms] Found plugin firebase_messaging at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-7.0.0\
[   +9 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-4.0.0\
[   +5 ms] Found plugin flutter_facebook_login at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_facebook_login-2.0.1\
[  +11 ms] Found plugin flutter_inapp_purchase at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_inapp_purchase-2.2.0\
[   +2 ms] Found plugin flutter_local_notifications at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-0.8.2\
[   +1 ms] Found plugin flutter_native_admob at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_native_admob-2.1.0\
[   +6 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-3.1.3\
[  +13 ms] Found plugin image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.1+4\
[  +14 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.10\
[  +13 ms] Found plugin path_provider_linux at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+1\
[   +2 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+3\
[   +6 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\
[   +7 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+10\
[  +12 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+7\
[  +12 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.3.0+2\
[  +76 ms] Generating D:\FlutterApps\FYD\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +22 ms] ro.hardware = qcom
[  +35 ms] Launching lib\main.dart on ONEPLUS A6010 in debug mode...
[  +59 ms] executing: C:\Users\xxx\AppData\Local\Android\sdk\platform-tools\adb.exe -s 315bbc84 shell -x logcat -v time -t 1
[ +354 ms] Exit code 0 from: C:\Users\xxx\AppData\Local\Android\sdk\platform-tools\adb.exe -s 315bbc84 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of main
           08-22 15:52:38.728 D/NetworkController.MobileSignalController(2)( 2129): onSignalStrengthsChanged
           signalStrength=SignalStrength:{mCdma=CellSignalStrengthCdma: cdmaDbm=2147483647 cdmaEcio=2147483647 evdoDbm=2147483647 evdoEcio=2147483647
           evdoSnr=2147483647 level=0 oplevel=0,mGsm=CellSignalStrengthGsm: rssi=2147483647 ber=2147483647 mTa=2147483647
           mLevel=0,mWcdma=CellSignalStrengthWcdma: ss=-97 ber=2147483647 rscp=-99 ecno=-11 level=2 oplevel=2,mTdscdma=CellSignalStrengthTdscdma:
           rssi=2147483647 ber=2147483647 rscp=2147483647 level=0,mLte=CellSignalStrengthLte: rssi=2147483647 rsrp=2147483647 rsrq=2147483647 rssnr=2147483647           cqi=2147483647 ta=2147483647 level=0 oplevel=0,mNr=CellSignalStrengthNr:{ csiRsrp = 2147483647 csiRsrq = 2147483647 csiSinr = 2147483647 ssRsrp =  
           2147483647 ssRsrq = 2147483647 ssSinr = 2147483647 level = 0 },primary=CellSignalStrengthWcdma,voice level =2,data level =2,isGsm =true} level=2   
           voicelevel=2 datalevel=2
[  +23 ms] executing: C:\Users\xxx\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +7 ms] executing: C:\Users\xxx\AppData\Local\Android\sdk\platform-tools\adb.exe -s 315bbc84 logcat -v time -T 08-22 15:52:38.728
[  +57 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Users\xxx\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +5 ms] executing: C:\Users\xxx\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +57 ms] Building APK
[  +23 ms] Invalid build-number: 1.3 for Android, overridden by 13.
           See versionCode at https://developer.android.com/studio/publish/versioning
[   +6 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[  +16 ms] Using gradle from D:\FlutterApps\FYD\android\gradlew.bat.
[  +19 ms] executing: D:\androidstd\jre\bin\java -version
[ +122 ms] Exit code 0 from: D:\androidstd\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +7 ms] executing: [D:\FlutterApps\FYD\android\] D:\FlutterApps\FYD\android\gradlew.bat -Pverbose=true -Ptarget=D:\FlutterApps\FYD\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[+2429 ms] > Configure project :app
[   +2 ms] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[   +1 ms] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[  +13 ms] registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
[ +150 ms] FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[  +17 ms] Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 362
[  +30 ms] * What went wrong:
[   +2 ms] A problem occurred configuring project ':cloud_firestore_web'.
[   +3 ms] > Could not find method implementation() for arguments [project ':firebase_core'] on object of type
org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
[   +8 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[   +6 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 2s
[   +4 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings
[ +286 ms] Running Gradle task 'assembleDebug'... (completed in 3.1s)
[   +5 ms] "flutter run" took 5,235ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
<asynchronous suspension>
#2      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:522:28)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#14     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#16     _rootRunUnary (dart:async/zone.dart:1134:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#24     AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#26     _rootRunUnary (dart:async/zone.dart:1134:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#32     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by Ehesp** [comment]
Also please follow the issue template. Don't delete the comments are replace it with a stack trace, please.

**Comment by sampathkumar7** [comment]
Followed guide still same issue.
Even after creating a new project with following dependencies

flutter_swiper : any
  firebase_auth: ^0.18.0+1
  flutter_facebook_login: ^2.0.1
  shared_preferences: ^0.5.6
  cloud_firestore: ^0.14.0+2
  fluttertoast: ^3.1.3  
  image_picker: ^0.6.1+3
  cached_network_image: ^2.0.0
  intl: ^0.16.1
  #google_sign_in: any
  flutter_local_notifications: ^0.8.2
  firebase_messaging: ^7.0.0
  photo_view: ^0.4.2
  firebase_storage: ^4.0.0
  firebase_core: "^0.5.0"
  #image_picker_modern: ^0.4.12+1
  animated_text_kit: ^1.3.1
  #permission: ^0.1.4 
  admob_flutter: ^0.3.3
  timeago: ^2.0.20
  giphy_picker: ^0.0.2
  flutter_native_admob: ^2.0.0
  facebook_audience_network: ^0.6.2
  flutter_inapp_purchase: ^2.2.0

**Comment by darshankawar** [comment]
Hi @sampathkumar7,
Are you using all the plugins you listed ? Can you try `flutter pub cache repair` and then `flutter run` to see if it works for you ?
Can you also try to segregate the issue by temporarily removing the unused plugins and try again ?
Thanks.
