### ISSUE TITLE
[cloud_firestore] query requires an index error. (collection is already indexed)

### ISSUE THREAD

**Issue by EliasDeuss** [FirebaseExtended/flutterfire#3293]
**Describe the bug**
After updating to cloud_firestore: 0.14.0 my stream builders of two collections are telling me the ```query requires an index.``` even though they are already indexed.

**Expected behavior**
Return collection documents where uid is the selected uid.

**Additional context**
```
StreamBuilder<QuerySnapshot>(
                stream: FirebaseFirestore.instance
                    .collection("art-room")
                    .orderBy("date", descending: true)
                    .where('uid', isEqualTo: widget.selectedUID)
                    .snapshots(),
                builder: (context, snapshot) {
                  QuerySnapshot querySnapshot = snapshot.data;
```

<img width="958" alt="Screen Shot 2020-08-22 at 11 02 47 PM" src="https://user-images.githubusercontent.com/13773566/90972172-9f47d380-e4cb-11ea-8f43-f69fefd0a630.png">

**Flutter doctor**
```
[✓] Flutter (Channel stable, 1.20.2, on macOS 11.0 20A5354i, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.48.1)
[✓] Connected device (1 available)

• No issues found!
```

```
flutter: Flutter error caught by Crashlytics plugin:
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building StreamBuilder<QuerySnapshot>(dirty, state:
flutter: _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#8642d):
flutter: The getter 'docs' was called on null.
flutter: Receiver: null
flutter: Tried calling: docs
flutter:
flutter: The relevant error-causing widget was:
flutter:   StreamBuilder<QuerySnapshot>
flutter:   file:///Users/elias/Documents/GitHub/the_unwanteds/lib/pages/profile/artRoomPosts.dart:318:22
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
flutter: #1      UsersArtRoomState.build.<anonymous closure>.<anonymous closure> (package:the_unwanteds/pages/profile/artRoomPosts.dart:552:48)
flutter: #2      StreamBuilder.build (package:flutter/src/widgets/async.dart:514:81)
flutter: #3      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:129:48)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
flutter: #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
flutter: #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
flutter: #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
flutter: ...     Normal element mounting (85 frames)
flutter: #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
flutter: #96     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
flutter: ...     Normal element mounting (71 frames)
flutter: #167    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
flutter: #168    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
flutter: #169    _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:137:18)
flutter: #170    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
flutter: #171    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:117:11)
flutter: #172    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1868:58)
flutter: #173    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:920:15)
flutter: #174    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1868:13)
flutter: #175    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:226:7)
flutter: #176    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:299:5)
flutter: #177    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #178    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #179    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #180    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #181    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #182    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #183    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #184    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:562:15)
flutter: #185    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #186    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #187    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #188    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #189    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #190    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #191    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #192    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #193    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #194    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #195    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #196    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3226:14)
flutter: #197    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #198    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:115:13)
flutter: #199    RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #200    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:702:15)
flutter: #201    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
flutter: #202    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
flutter: #203    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
flutter: #204    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
flutter: #205    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #206    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #207    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #208    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #212    _invoke (dart:ui/hooks.dart:253:10)
flutter: #213    _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: [cloud_firestore/failed-precondition] The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/the-unwanteds/firestore/indexes?create_composite=<url>
```

**Comment by EliasDeuss** [comment]
@Salakar It creates another index with the same name. Just without the topic tag.
<img width="987" alt="Screen Shot 2020-08-23 at 1 05 30 PM" src="https://user-images.githubusercontent.com/13773566/90987640-69453680-e541-11ea-9c8e-421d998340bf.png">

**Comment by Salakar** [comment]
You're not using 'topic' in the above query so this is working as intended and that new index is required as it's without 'topic'.
