### ISSUE TITLE
[firebase_auth] Sign in using email and password causes an unknown exception

### ISSUE THREAD

**Issue by ziedReg** [FirebaseExtended/flutterfire#3323]
I'm using Flutter Web, i updated my Firebase dependencies and now when i sign in using `signInWithEmailAndPassword` i get a FirebaseAuthException `[firebase_auth/unknown] An unknown error occurred.`

To reproduce, i just call this method :
```
static Future<UserCredential> signIn(String email, String password) async {
    final FirebaseAuth _firebaseAuth = FirebaseAuth.instance;
    UserCredential result = await _firebaseAuth.signInWithEmailAndPassword(
        email: email, password: password);
    return result;
  }
```

The expected behaviour is to move to the next page of course but that does not happen. What is strange is that if i refresh the page, i find that i'm authenticated and i go automatically to the next page but before refreshing i'm not. I checked the authentication state listener `FirebaseAuth.instance.authStateChanges().listen()` which is inside `initState` the "app" widget but it doesn't get called.

Here is the error stack :

```
TypeError: Cannot read property 'parse' of null
    at new firebase_auth_web_user.UserWeb.new (http://localhost:2710/packages/firebase_auth_web/firebase_auth_web_user_credential.dart.lib.js:165:353)
    at _MapStream.new.<anonymous> (http://localhost:2710/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:286:18)
    at _MapStream.new.[_handleData] (http://localhost:2710/dart_sdk.js:34799:61)
    at _ForwardingStreamSubscription.new.[_handleData] (http://localhost:2710/dart_sdk.js:34706:37)
    at _RootZone.runUnaryGuarded (http://localhost:2710/dart_sdk.js:36955:11)
    at _BroadcastSubscription.new.[_sendData] (http://localhost:2710/dart_sdk.js:30667:22)
    at _BroadcastSubscription.new.[_add] (http://localhost:2710/dart_sdk.js:30613:26)
    at _SyncBroadcastStreamController.new.[_sendData] (http://localhost:2710/dart_sdk.js:31335:34)
    at _SyncBroadcastStreamController.new.add (http://localhost:2710/dart_sdk.js:31129:24)
    at http://localhost:2710/packages/firebase/src/storage.dart.lib.js:1735:43
    at Object._checkAndCall (http://localhost:2710/dart_sdk.js:4673:16)
    at Object.dcall (http://localhost:2710/dart_sdk.js:4678:17)
    at Object.ret [as next] (http://localhost:2710/dart_sdk.js:59570:21)
    at https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js:1:1977
    at https://www.gstatic.com/firebasejs/7.5.0/firebase-app.js:1:3269TypeError: Cannot read property 'parse' of null
    at new firebase_auth_web_user.UserWeb.new (http://localhost:2710/packages/firebase_auth_web/firebase_auth_web_user_credential.dart.lib.js:165:353)
    at firebase_auth_web.FirebaseAuthWeb.new.get currentUser [as currentUser] (http://localhost:2710/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:70:14)
    at firebase_auth.FirebaseAuth.__.get currentUser [as currentUser] (http://localhost:2710/packages/firebase_auth/firebase_auth.dart.lib.js:97:28)
    at login_view._LoginViewState.new.login (http://localhost:2710/packages/sprime/widgets/navbar_item/navbar_item.dart.lib.js:3082:58)
    at login.throw (<anonymous>)
    at http://localhost:2710/dart_sdk.js:37181:38
    at _RootZone.runBinary (http://localhost:2710/dart_sdk.js:37034:58)
    at _FutureListener.thenAwait.handleError (http://localhost:2710/dart_sdk.js:32128:48)
    at handleError (http://localhost:2710/dart_sdk.js:32679:51)
    at Function._propagateToListeners (http://localhost:2710/dart_sdk.js:32705:17)
    at _Future.new.[_completeWithValue] (http://localhost:2710/dart_sdk.js:32544:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:2710/dart_sdk.js:32566:35)
    at Object._microtaskLoop (http://localhost:2710/dart_sdk.js:37290:13)
    at _startMicrotaskLoop (http://localhost:2710/dart_sdk.js:37296:13)
    at http://localhost:2710/dart_sdk.js:32918:9
```
 
Flutter doctor :

```
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [version 10.0.18363.1016], locale fr-TN)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[!] IntelliJ IDEA Community Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.47.3)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (2 available)

! Doctor found issues in 3 categories.

```

**Comment by dhanniex82** [comment]
same here.
i couldn't catch the FirebaseAuthException or even general exception,

**Comment by Ehesp** [comment]
@dhanniex82 There's an issue with your code. You're doing this:

```dart
                   try {
                      await FirebaseAuth.instance
                          .signInWithEmailAndPassword(
                              email: _emailTextController.text,
                              password: _passwordTextController.text)
                          .whenComplete(
                            () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) => HomePage()),
                            ),
                          );
                    } on FirebaseAuthException catch (e) {
                      print(e.code);
                      print(e.message);
                    }
```

vs this:

```dart
                    try {
                      await FirebaseAuth.instance
                          .signInWithEmailAndPassword(
                              email: _emailTextController.text,
                              password: _passwordTextController.text)
                          .then((u) {
                            Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) => HomePage()),
                            );
                          });
                    } on FirebaseAuthException catch (e) {
                      print(e.code);
                      print(e.message);
                    }
```

`whenComplete` captures success and failure, and is swallowing the error so it isn't caught.

**Comment by Ehesp** [comment]
@ziedReg I just tried this locally and can't reproduce - can you send me a link to an example project I can run? Thanks.

**Comment by dhanniex82** [comment]
@Ehesp I have tried the code you suggested. Still couldn't catch the exception.
I tried to displayed it on screen with Text widget. 
But when I input wrong email or password, the app just stopped.
With firebase_auth: ^0.16.1, I can catch the exception and display it on app screen and on debug console and the app still running so I can make correction with the wrong email or password.

**Comment by dhanniex82** [comment]
sorry, forgot to mentioned I'm on android platform.
but I have the code you suggested and it still couldn't catch the exception.

**Comment by Ehesp** [comment]
Please make a new issue. This is not the same problem as OP.

**Comment by ziedReg** [comment]
@Ehesp Thank you for taking the time, [here](https://github.com/ziedReg/flutter-auth-bug) is a sample app containing the files needed to reproduce the error.
You can connect with the user i created (email : sample@demo.com & password : Password123).
The `signIn()` method is called inside `login_view` (line 98) which you can find under `lib\views\authentication`.

**Comment by TahaTesser** [comment]
Hi @ziedReg 
Can you please isolate `firebase_auth` code, Can you please provide a [minimal complete  reproducible runnable code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by ziedReg** [comment]
Hi again, sorry for the late answer. I found a fix for the error.
I am using Intl and i had to add these lines :

`
import 'package:intl/date_symbol_data_local.dart';
`

and in the `build` method of the main widget :

`
initializeDateFormatting();
`

Before upgrading my dependencies (both Firebase and Intl) i didn't need to do this initialization.

**Comment by TahaTesser** [comment]
Hi @ziedReg 
Can you please provide a complete reproducible minimal code sample
Thank you

**Comment by Flawe** [comment]
For what it's worth, I'm getting a [firebase_auth/unknown] exception on Android as well. For me it happens only on the apk from Play Store, not a debug one, which would indicate a signing key problem but I've added the SHA1 key from Play Console to Firebase and I still get this issue.
