### ISSUE TITLE
[cloud_functions] Public callable functions aren't executed and fail with exception UNAUTHENTICATED

### ISSUE THREAD

**Issue by kaiserschmarrn0** [FirebaseExtended/flutterfire#3335]
**Describe the bug**

Recently created firebase callable functions are not executed, and fail with the following exception: 
<details>
  <summary>stack trace</summary>

```
E/flutter (29437): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(functionsError, Cloud function failed with exception., {code: UNAUTHENTICATED, details: null, message: UNAUTHENTICATED})
E/flutter (29437): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:572
E/flutter (29437): #1      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:161
E/flutter (29437): <asynchronous suspension>
E/flutter (29437): #2      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:334
E/flutter (29437): #3      MethodChannelCloudFunctions.callCloudFunction 
package:cloud_functions_platform_interface/src/method_channel_cloud_functions.dart:43
E/flutter (29437): #4      HttpsCallable.call 
package:cloud_functions/src/https_callable.dart:33
E/flutter (29437): #5      _MessageBoxState.build.<anonymous closure>.<anonymous closure> 
package:pocket_pro/lesson.dart:505
E/flutter (29437): #6      _rootRunUnary  (dart:async/zone.dart:1198:47)
E/flutter (29437): #7      _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (29437): #8      _FutureListener.handleValue  (dart:async/future_impl.dart:143:18)
E/flutter (29437): #9      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:696:45)
E/flutter (29437): #10     Future._propagateToListeners  (dart:async/future_impl.dart:725:32)
E/flutter (29437): #11     Future._completeWithValue  (dart:async/future_impl.dart:529:5)
E/flutter (29437): #12     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:40:15)
E/flutter (29437): #13     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:311:13)
E/flutter (29437): #14     DocumentReference.get (package:cloud_firestore/src/document_reference.dart)
E/flutter (29437): <asynchronous suspension>
E/flutter (29437): #15     _MessageBoxState.build.<anonymous closure> 
package:pocket_pro/lesson.dart:504
E/flutter (29437): #16     _InkResponseState._handleTap
E/flutter (29437): #17     _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:1098
E/flutter (29437): #18     GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:184
E/flutter (29437): #19     TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:524
E/flutter (29437): #20     BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:284
E/flutter (29437): #21     BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:256
E/flutter (29437): #22     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:158
E/flutter (29437): #23     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:224
E/flutter (29437): #24     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:200
E/flutter (29437): #25     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:158
E/flutter (29437): #26     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:104
E/flutter (29437): #27     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:88
E/flutter (29437): #28     _rootRunUnary  (dart:async/zone.dart:1206:13)
E/flutter (29437): #29     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter (29437): #30     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
E/flutter (29437): #31     _invoke1  (dart:ui/hooks.dart:267:10)
E/flutter (29437): #32     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)
E/flutter (29437):
```
</details>

This is similar to https://github.com/FirebaseExtended/flutterfire/issues/2374, but that was caused by outdated firebase-tools and upstream firebase changes that prevented public access to the callable.

Newly created firebase callable functions that are causing this error have public access, and work properly using the javascript sdk. Note that these functions are not executed when this exception is thrown, and no info is provided in the firebase logs.
![image](https://user-images.githubusercontent.com/15952100/91108345-acc89f00-e62c-11ea-9088-56038694ae33.png)

Previously created functions can be updated and still work. If a function is deleted and recreated, it begins to cause the same issue.

**To Reproduce**
1. Create new firebase callable function (not a different function with an existing name)
2. Call the function from a flutter app

**Expected behavior**
Function executes

**Flutter doctor**
Run `flutter doctor` and paste the output below:

<details>
  <summary>flutter doctor -v</summary>

```
flutter doctor -v
[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.20.0-7.2.pre at /home/j/flutter
    • Framework revision a2bde82fbd (5 weeks ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio
    • Android Studio at /home/j/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Pixel (mobile) • FA68H0304357 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```
</details>

**Comment by kaiserschmarrn0** [comment]
Restarting my flutter project from scratch seems to have fixed this. I am not sure what I might have changed in my previous configuration that would cause this, though.
