### ISSUE TITLE
[firebase_auth] <Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference>

### ISSUE THREAD

**Issue by Acver14** [FirebaseExtended/flutterfire#3353]
I have error at 'google login'.
this function run correctly in IOS, but in Android this function is not working.
I have tested this code, I find the error occured in GoogleAuthProvider.getCredential.
please help me(i`m sorry my bad english... 😢 )

```
 Future<bool> signInWithGoogleAccount() async {
    try {
      final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
      final GoogleSignInAuthentication googleAuth =
          await googleUser.authentication;
      final AuthCredential credential = GoogleAuthProvider.getCredential(
          accessToken: googleAuth.accessToken, idToken: googleAuth.idToken);
      final authResult = await fAuth.signInWithCredential(credential);
      final FirebaseUser user = authResult.user;

      assert(user.email != null);
      assert(user.displayName != null);
      assert(!user.isAnonymous);
      assert(await user.getIdToken() != null);

      final FirebaseUser currentUser = await fAuth.currentUser();
      assert(user.uid == currentUser.uid);
      setUser(user);

      //await setUserInfo();
      return true;
    } on Exception catch (e) {
      logger.e(e.toString());
      List<String> result = e.toString().split(", ");
      setLastFBMessage(result[1]);
      return false;
    }
  }
```

**Flutter doctor**
Run `flutter doctor` and paste the output below:
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale ko-KR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

Paste output here

```
I/flutter (11740): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (11740): │ #0   SignInPageState.build (package:ssdam/auth/signin_page.dart:48:12)
I/flutter (11740): │ #1   StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
I/flutter (11740): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (11740): │ 🐛 null
I/flutter (11740): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/Surface (11740): getSlotFromBufferLocked: unknown buffer: 0x200
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInWithCredential(FirebaseAuthPlugin.java:478)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:120)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#plugins.flutter.io/firebase_auth(11740): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/flutter (11740): [38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────[0m
I/flutter (11740): [38;5;196m│ #0   FirebaseProvider.signInWithGoogleAccount (package:ssdam/firebase_provider.dart:112:14)
I/flutter (11740): [38;5;196m│ <asynchronous suspension>
I/flutter (11740): [38;5;196m│ #1   SignInPageState._signInWithGoogle (package:ssdam/auth/signin_page.dart:233:28)
I/flutter (11740): [38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄[0m
I/flutter (11740): [38;5;196m│ ⛔ PlatformException(error, Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference, null)[0m
``

**Comment by TahaTesser** [comment]
Hi @Acver14 
This is an issue your code, you have a null value in your code 

I tried to reproduce the issue using your code, some of it is outdated in `firebase_auth` 

Try this code with the official [example](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/example/lib/signin_page.dart) 

```
  void _signInWithGoogle() async {
    try {
      final GoogleSignInAccount googleUser = await GoogleSignIn().signIn();
      final GoogleSignInAuthentication googleAuth =
          await googleUser.authentication;
      final AuthCredential credential = GoogleAuthProvider.credential(
          accessToken: googleAuth.accessToken, idToken: googleAuth.idToken);
      final authResult = await _auth.signInWithCredential(credential);
      final User user = authResult.user;

      assert(user.email != null);
      assert(user.displayName != null);
      assert(!user.isAnonymous);
      assert(await user.getIdToken() != null);

      final User currentUser = _auth.currentUser;
      assert(user.uid == currentUser.uid);
      print(user);
      // setUser(user);
      Scaffold.of(context).showSnackBar(SnackBar(
        content: Text("Sign In ${user.uid} with Google"),
      ));
      //await setUserInfo();
    } on Exception catch (e) {
      print(e);
      List<String> result = e.toString().split(", ");
      for (var item in result) {
        print(item);
      }
    }
}
```

Closing, as this isn't an issue with flutterfire itself. If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by Acver14** [comment]
@TahaTesser , Thanks for your reply.
I tried that example, but error was occured.
lib/firebase_provider.dart:96:60: Error: Method not found: 'GoogleAuthProvider.credential'.
      final AuthCredential credential = GoogleAuthProvider.credential(  
                                                           ^^^^^^^^^^   
lib/firebase_provider.dart:99:13: Error: 'User' isn't a type.           
      final User user = authResult.user;     

my firebase_auth version is 0.14.0+5(but, using recently version also occured error) and google_sign_in version is 4.4.1
also I'm curious why in IOS, my code work well, but in AOS not working

Any help would be appreciated

**Comment by TahaTesser** [comment]
Hi @Acver14 
There is no issue in my reproduction, please execute `flutter pub get` and use the latest packages in your pubspec.yaml
`lib/firebase_provider.dart:99:13: Error: 'User' isn't a type.` this error shows you're using an older package which with new code sample  

If the problem persists,  Can you please provide your `pubspec.yaml` and `flutter run --verbose` logs, and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you
