### ISSUE TITLE
🐛 [admob] PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null, null)

### ISSUE THREAD

**Issue by SwissCheese5** [FirebaseExtended/flutterfire#3396]
## Bug report

**Describe the bug**
I tried showing a Reward Ad on the latest firebase_admob version compatible with firebase_core 5
`firebase_admob: ^0.10.0-dev.1`

### Steps to reproduce

```dart
  @override
  Future showRewardAd() async {
    return RewardedVideoAd.instance
        .load(
            adUnitId: kDebugMode
                ? 'ca-app-pub-3940256099942544/5224354917'
                : 'ca-app-pub-5499064177088813/4962627070')
        .then((bool success) {
      return !success ? null : RewardedVideoAd.instance.show();
    });
  }
```

### Expected behavior

An Ad to be previewed.
---

## Additional context

Here's all the relevant console log output as soon as I click my ad button.
```

I/Ads     (18717): This request is sent from a test device.
W/flutter (18717): onRewardedVideoAdFailedToLoad: 0
I/Ads     (18717): Ad failed to load : 0
E/flutter (18717): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: Unhandled error PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null, null) occurred in Instance of 'UserEndpointBloc'.
E/flutter (18717): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (18717): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (18717): <asynchronous suspension>
E/flutter (18717): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (18717): #3      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:612:61)
E/flutter (18717): #4      RewardedVideoAd.show (package:firebase_admob/firebase_admob.dart:487:12)
```

As well as the fact that the ad literally returns success on load

![image](https://user-images.githubusercontent.com/7407478/91641439-1d0c6180-ea2d-11ea-99ca-5c88b1ea07d4.png)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 1.22.0-2.0.pre.36, on Microsoft Windows [Version 10.0.19041.450], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.1)
[!] Android Studio (not installed)
[√] Connected device (5 available)

! Doctor found issues in 1 category.

```
(android studio beta/alpha are installed, not the release version)
</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.0-49.0.dev
Flutter SDK 1.22.0-2.0.pre.36
chacha 1.0.0+1

dependencies:
- animations 1.1.2 [flutter]
- async 2.5.0-nullsafety [collection]
- bloc 6.0.2 [meta]
- blurhash 0.2.0 [flutter]
- blurhash_dart 0.2.3
- clipboard 0.1.2+8 [flutter]
- cloud_firestore 0.14.0+2 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- connectivity 0.4.9+2 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- data_connection_checker 0.3.4
- dio 3.0.10 [http_parser path]
- dotted_border 1.0.6 [flutter path_drawing]
- equatable 1.2.4 [collection meta]
- file_picker_cross 3.1.1 [flutter file_picker http http_parser file_chooser]
- firebase_admob 0.10.0-dev.1 [meta platform flutter firebase_core]
- firebase_auth 0.18.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_crashlytics 0.1.4+1 [flutter stack_trace]
- firebase_dynamic_links 0.6.0 [flutter firebase_core]
- firebase_storage 4.0.0 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.0.1 [flutter bloc provider]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_downloader 1.5.0 [flutter]
- flutter_widgets 0.1.12 [collection flutter html meta quiver]
- google_fonts 1.1.0 [flutter http path_provider crypto pedantic]
- google_sign_in 4.5.3 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- hive 1.4.4 [meta crypto]
- hive_flutter 0.3.1 [flutter hive path_provider path]
- howler 1.1.2 [swiss_knife]
- implicitly_animated_reorderable_list 0.2.3 [flutter async meta]
- meta 1.3.0-nullsafety.2
- network_image_to_byte 0.0.1 [flutter]
- path_provider 1.6.14 [flutter path_provider_platform_interface path_provider_macos path_provider_linux]
- preload_page_view 0.1.4 [flutter]
- provider 4.3.2+1 [flutter nested collection]
- responsive_framework 0.0.8 [flutter]
- salsa_entities 0.0.0 [json_annotation meta]
- sounds 1.0.0-beta.12 [device_info flutter_spinkit meta path path_provider provider sounds_common uuid flutter]
- string_validator 0.1.4
- transparent_image 1.0.0
- uni_links 0.4.0 [flutter]
- url_launcher 5.5.0 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos]
- uuid 2.2.0 [crypto convert]
- watcher 0.9.7+15 [async path pedantic]

dev dependencies:
- build_runner 1.10.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic
pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed
_data]
- hive_generator 0.7.1 [build source_gen hive analyzer dartx]
- pedantic 1.9.2 [meta]

transitive dependencies:
- _fe_analyzer_shared 7.0.0 [meta]
- analyzer 0.39.17 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- args 1.6.0
- boolean_selector 2.1.0-nullsafety [source_span string_scanner]
- build 1.3.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.3.11 [analyzer build crypto graphs logging path package_config pub_semver]
- build_runner_core 6.0.1 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.2
- charcode 1.2.0-nullsafety
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety
- cloud_firestore_platform_interface 2.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.0+1 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- code_builder 3.4.1 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.2
- connectivity_for_web 0.3.1+2 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+4 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- dartx 0.5.0 [collection path crypto characters time meta]
- device_info 0.4.2+7 [flutter device_info_platform_interface]
- device_info_platform_interface 1.0.0 [flutter meta plugin_platform_interface]
- fake_async 1.1.0-nullsafety [clock collection]
- file 5.2.1 [intl meta path]
- file_chooser 0.1.4 [flutter]
- file_picker 1.13.3 [flutter flutter_plugin_android_lifecycle file_picker_platform_interface]
- file_picker_platform_interface 1.3.1 [flutter plugin_platform_interface]
- firebase 7.3.0 [http http_parser js]
- firebase_auth_platform_interface 2.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.0+1 [flutter flutter_web_plugins firebase meta http_parser intl firebase_core firebase_auth_platform_interface js]
- firebase_core 0.5.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- fixnum 0.10.11
- flutter_plugin_android_lifecycle 1.0.8 [flutter]
- flutter_spinkit 4.1.2+1 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.1+1 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 0.2.0
- html 0.14.0+3 [csslib source_span]
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_annotation 3.0.1
- logger 0.9.2
- logging 0.11.4
- matcher 0.12.10-nullsafety [stack_trace]
- mime 0.9.7
- nested 0.0.4 [flutter]
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+3 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- platform 2.2.1
- platform_detect 1.4.0 [meta pub_semver]
- plugin_platform_interface 1.0.2 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.3 [matcher meta]
- resource_portable 2.1.7 [typed_data]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- sounds_common 1.0.8 [intl logger meta path pedantic uuid flutter]
- source_gen 0.9.6 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety [path]
- stream_channel 2.1.0-nullsafety [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety [charcode source_span]
- swiss_knife 2.5.11 [intl resource_portable]
- term_glyph 1.2.0-nullsafety
- test_api 0.2.19-nullsafety [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- time 1.3.0
- timing 0.1.1+2 [json_annotation]
- typed_data 1.3.0-nullsafety.2 [collection]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+7 [flutter]
- url_launcher_platform_interface 1.0.7 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.2+1 [url_launcher_platform_interface platform_detect flutter flutter_web_plugins meta]
- vector_math 2.1.0-nullsafety.2
- web_socket_channel 1.1.0 [async crypto stream_channel]
- xdg_directories 0.1.2 [meta path process]
- yaml 2.2.1 [charcode collection string_scanner source_span]

```

</details>

---

**Comment by SwissCheese5** [comment]
Note: I changed the test ad unit id with `RewardedVideoAd.testAdUnitId`, with the EXACT same result.

**Comment by darshankawar** [comment]
H @SwissCheese5,
I see a similar open issue, describing your case, [2175](https://github.com/FirebaseExtended/flutterfire/issues/2175).
Please follow-up there for updates and any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
