### ISSUE TITLE
🐛 [cloud_firestore] CocoaPods's specs repository is too out-of-date

### ISSUE THREAD

**Issue by khalifa007** [FirebaseExtended/flutterfire#3424]
## Bug report

**Describe the bug**
I was trying to add firebase packages in my flutter project with latest versions , its work in android but in IOS its not work it says(see down) . How to run my project with latest packages in IOS Flutter project ? also I tried to pod repo update but its not work its keeb asking to update again!

docs : https://firebase.flutter.dev/

main error :

```
 Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
    To update the CocoaPods specs, run:
      pod repo update
```
Firebase pkgs list :

```
  firebase_analytics: ^6.0.0
  google_sign_in: ^4.5.3
  firebase_auth: ^0.18.0+1
  cloud_firestore: "^0.14.0+2"
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.0
```

### Steps to reproduce

I followed 
docs : https://firebase.flutter.dev/

adding firebase core and firestore

### Expected behavior

How to remove errors ? 

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
 khalifas-MacBook-Air:squlife-master-2 khalifa$ flutter run
    Launching lib/main.dart on iPhone SE (2nd generation) in debug mode...
     
    Running pod install...                                              4.9s
    CocoaPods' output:
    ↳
          Preparing
    
        Analyzing dependencies
    
        Inspecting targets to integrate
          Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    
        Finding Podfile changes
          A Firebase
          A apple_sign_in
          A firebase_analytics
          A firebase_auth
          A flutter_full_pdf_viewer
          A google_sign_in
          - Flutter
          - cloud_firestore
          - firebase_core
          - firebase_messaging
          - flutter_inappwebview
          - in_app_purchase
          - package_info
          - path_provider
          - shared_preferences
          - sqflite
          - url_launcher
    
        Fetching external sources
        -> Fetching podspec for `Flutter` from `Flutter`
        -> Fetching podspec for `apple_sign_in` from `.symlinks/plugins/apple_sign_in/ios`
        -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
        cloud_firestore: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
        -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
        firebase_analytics: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
        -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
        firebase_auth: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
        -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
        firebase_core: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
        -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
        firebase_messaging: Using Firebase SDK version '6.26.0' defined in 'firebase_core'
        -> Fetching podspec for `flutter_full_pdf_viewer` from
        `.symlinks/plugins/flutter_full_pdf_viewer/ios`
        -> Fetching podspec for `flutter_inappwebview` from
        `.symlinks/plugins/flutter_inappwebview/ios`
        -> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
        -> Fetching podspec for `in_app_purchase` from `.symlinks/plugins/in_app_purchase/ios`
        -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
        -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
        -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
        -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`
        -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    
        Resolving dependencies of `Podfile`
          CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is
          only perfomed in repo update
          CDN: trunk Relative path: all_pods_versions_0_3_5.txt exists! Returning local because
          checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.31.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.28.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.28.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/1.0.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/1.0.5/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/1.0.7/Firebase.podspec.json exists!
  urning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.8.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.9.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.10.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.11.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.11.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.12.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.13.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.14.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.15.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.16.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/3.17.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.0.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.0.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.0.2/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.0.3/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.0.4/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.1.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.1.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.2.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.3.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.4.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.5.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.6.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.7.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.8.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.8.2/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.9.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.10.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.10.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.11.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.12.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/4.13.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.0.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.0.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.1.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.2.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.3.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.4.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.4.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.5.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.6.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.7.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.8.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.8.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.9.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.10.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.11.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.12.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.13.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.14.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.15.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.16.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.17.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.18.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.19.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.20.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.20.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/5.20.2/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.0.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.1.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.2.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.3.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.4.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.5.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.6.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.7.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.8.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.8.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.9.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.10.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.11.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.12.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.13.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.14.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.15.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.16.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.17.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.18.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.19.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.20.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.21.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.22.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.23.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.24.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.25.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.26.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.27.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.27.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.28.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.28.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.29.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.30.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.31.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.31.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.28.1/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: all_pods_versions_f_4_e.txt exists! Returning local because
          checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json exists! Returning local
          because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.26.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.26.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: all_pods_versions_d_4_0.txt exists! Returning local because
          checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/d/4/0/GoogleSignIn/5.0.2/GoogleSignIn.podspec.json exists!
          Returning local because checking is only perfomed in repo update
          CDN: trunk Relative path: Specs/0/3/5/Firebase/6.26.0/Firebase.podspec.json exists!
          Returning local because checking is only perfomed in repo update
        [!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
          In snapshot (Podfile.lock):
            Firebase/CoreOnly (= 6.28.1)
    
          In Podfile:
            firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to
            6.0.0, which depends on
              Firebase/CoreOnly (~> 6.26.0)
    
    
        You have either:
         * out-of-date source repos which you can update with `pod repo update` or with `pod install
         --repo-update`.
         * changed the constraints of dependency `Firebase/CoreOnly` inside your development pod
         `firebase_analytics`.
           You should run `pod update Firebase/CoreOnly` to apply changes you've made.
    
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in
        `raise_error_unless_state'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in
        unwind_for_conflict'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in
        `unwind_for_conflict'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in
        `process_topmost_state'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
        /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/resolver.rb:94:in
        `resolve'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:107
        4:in `block in resolve_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/user_interface.rb:64:in
        `section'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:107
        2:in `resolve_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:124
        :in `analyze'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:414:in
        `analyze'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:239:in
        `block in resolve_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/user_interface.rb:64:in
        `section'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:238:in
        `resolve_dependencies'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:160:in
        `install!'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/command/install.rb:52:in
        `run'
        /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/command.rb:52:in `run'
        /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0.beta.2/bin/pod:55:in `<top (required)>'
        /usr/local/bin/pod:23:in `load'
        /usr/local/bin/pod:23:in `<main>'
    
    Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
    To update the CocoaPods specs, run:
      pod repo update
    
    
    
    Error running pod install
    Error launching application on iPhone SE (2nd generation).
    khalifas-MacBook-Air:squlife-master-2 khalifa$ 
```

</details>

---

**Comment by abdullahkaracabey** [comment]
I have same error.

**Comment by TahaTesser** [comment]
Hi @khalifa007  @abdullahkaracabey 
Can you please provide your `flutter doctor -v`
Thank you

**Comment by Aashay7** [comment]
1. Go to **/ios** folder inside your App Package.
2. Delete **Podfile.lock**
3. Run  **pod install --repo-update**
4. cd..  (Go Back to the App Package)
5. Run **flutter clean**
6. Rebuild and Run the App.

**Comment by abdullahkaracabey** [comment]
> flutter doctor -v

[✓] Flutter (Channel master, 1.22.0-2.0.pre.80, on Mac OS X 10.15.6 19G2021, locale en-TR)
    • Flutter version 1.22.0-2.0.pre.80 at /Users/abdullah/Library/flutter
    • Framework revision 5a2153d340 (8 days ago), 2020-08-26 04:16:07 -0400
    • Engine revision c7467a4359
    • Dart version 2.10.0 (build 2.10.0-59.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/abdullah/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/abdullah/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/abdullah/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
      Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Users/abdullah/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 (mobile)                 • 93EAFC5F-80A8-4BD6-8FFC-B50FFF3F1866 • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64  • Mac OS X 10.15.6 19G2021

• No issues found!

[pubspec.yaml.zip](https://github.com/FirebaseExtended/flutterfire/files/5164539/pubspec.yaml.zip)

**Comment by Salakar** [comment]
```
To update the CocoaPods specs, run:
      pod repo update
```

**Comment by VeArnold** [comment]
@Salakar Seems a bit presumptuous. There seem to be many cases of this out there where pod repo update does not help.

**Comment by abdullahkaracabey** [comment]
> 1. Go to **/ios** folder inside your App Package.
> 2. Delete **Podfile.lock**
> 3. Run  **pod install --repo-update**
> 4. cd..  (Go Back to the App Package)
> 5. Run **flutter clean**
> 6. Rebuild and Run the App.

it works after delete Podfile.lock; thank you.
