### ISSUE TITLE
🐛 [firebase_crashlytics: 0.2.0-dev.2] Hot restart fails

### ISSUE THREAD

**Issue by mono0926** [FirebaseExtended/flutterfire#3432]
## Bug report

**Describe the bug**

Hot restart fails at firebase_crashlytics: 0.2.0-dev.2.
With 0.1.4+1, there are no problems.

### Steps to reproduce

1. Run the app which uses `firebase_crashlytics: 0.2.0-dev.2` on Android
2. Execute "Hot Restart"
3. "Hot Restart" failed with error logs:

```
Performing hot restart...
Syncing files to device sdk gphone x86...
Restarted application in 975ms.
W/oca.developmen(24954): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)
E/flutter (24954): [ERROR:flutter/lib/ui/ui_dart_state.cc(171)] Unhandled Exception: PlatformException(firebase_core, java.lang.NullPointerException: Task must not be null, null)
E/flutter (24954): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:571:7)
E/flutter (24954): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (24954): <asynchronous suspension>
E/flutter (24954): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (24954): #3      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)
E/flutter (24954): #4      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30:36)
E/flutter (24954): #5      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75:13)
E/flutter (24954): #6      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:25)
E/flutter (24954): #7      main (package:xxx/main.dart:49:18)
E/flutter (24954): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (24954): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (24954): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (24954): #11     _runZoned (dart:async/zone.dart:1630:10)
E/flutter (24954): #12     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (24954): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (24954): #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (24954): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (24954): 
```

On iOS, the app freezes without any errors after "Hot Restart".

### Expected behavior

"Hot Restart" should succeed without any errors.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.22.0-1.0.pre, on Mac OS X 10.15.6 19G2021, locale
    en-JP)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] VS Code (version 1.48.1)
[✓] Connected device (6 available)
    ! Error: monoPhone is not connected. Xcode will continue when monoPhone is connected. (code -13)
    ! Error: monoyagon is not connected. Xcode will continue when monoyagon is connected. (code -13)
    ! Error: monoPhone7Plus has recently restarted. Xcode will continue when monoPhone7Plus is unlocked. (code -14)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
❯ flutter pub deps -- --style=compact
Dart SDK 2.10.0-45.0.dev
Flutter SDK 1.22.0-1.0.pre
xxx 0.1.0+134

dependencies:
- adaptive_dialog 0.8.0-dev [flutter animations meta]
- android_intent 0.3.7+3 [flutter platform meta]
- animations 1.1.2 [flutter]
- app_settings 4.0.3 [flutter]
- barcode_scan 3.0.1 [protobuf flutter]
- characters 1.1.0-nullsafety.2
- cloud_firestore 0.14.0+2 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_functions 0.6.0 [meta flutter firebase_core cloud_functions_platform_interface cloud_functions_web]
- collection 1.15.0-nullsafety.2
- cupertino_icons 0.1.3
- device_info 0.4.2+7 [flutter device_info_platform_interface]
- devicelocale 0.3.1 [flutter]
- disposable_provider 2.2.0 [flutter provider]
- enum_to_string 1.0.9
- expansion_tile_card 1.1.0 [flutter]
- extended_image 1.1.1 [flutter extended_image_library meta]
- firebase_analytics 6.0.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.1.4+1 [flutter stack_trace]
- firebase_dynamic_links 0.6.0 [flutter firebase_core]
- firebase_messaging 7.0.0 [meta platform flutter firebase_core]
- firebase_performance 0.4.0 [flutter firebase_core]
- firebase_remote_config 0.4.0 [flutter firebase_core]
- firebase_storage 4.0.0 [flutter firebase_core]
- firestore_ref 0.9.0 [flutter cloud_firestore disposable_provider firebase json_annotation simple_logger meta quiver rxdart subscription_holder]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_hooks 0.13.2 [flutter]
- flutter_image_compress 0.7.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_material_color_picker 1.0.5 [flutter]
- flutter_portal 0.1.0 [flutter]
- flutter_reorderable_list 0.1.4 [flutter]
- flutter_secure_storage 3.3.3 [meta flutter]
- flutter_slidable 0.5.7 [flutter]
- flutter_svg 0.18.1 [path_drawing xml vector_math meta flutter]
- font_awesome_flutter 8.8.1 [flutter]
- freezed_annotation 0.11.0+1 [collection json_annotation meta]
- gap 1.2.0 [flutter]
- google_sign_in 4.5.3 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- hooks_riverpod 0.8.0 [flutter_riverpod riverpod flutter flutter_hooks collection state_notifier]
- image_cropper 1.3.1 [flutter]
- image_picker 0.6.7+7 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.16.1 [path]
- json_annotation 3.0.1
- local_auth 0.6.3+1 [flutter meta intl platform flutter_plugin_android_lifecycle]
- material_design_icons_flutter 4.0.5555 [flutter]
- mono_kit 0.17.1+2 [flutter adaptive_dialog flutter_cache_manager image_picker rxdart url_launcher disposable_provider freezed_annotation nested hooks_riverpod quiver stream_transform subscription_holder simple_logger tinycolor flutter_svg state_notifier flutter_hooks]
- nested 0.0.4 [flutter]
- notification_permissions 0.4.7 [flutter]
- package_info 0.4.3 [flutter]
- passcode_screen 1.2.0 [flutter]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- reorderables 0.3.2 [flutter]
- rxdart 0.24.1
- share 0.6.5 [meta mime flutter]
- shared_preferences 0.5.10 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web]
- snack_bar_presenter 0.1.2 [flutter riverpod simple_logger]
- sort_key_generator 0.1.0
- state_notifier 0.6.0 [meta]
- stream_transform 1.2.0
- tinycolor 1.0.3 [pigment meta flutter]
- tuple 1.0.3 [quiver]
- url_launcher 5.5.2 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos]
- version 1.2.0
- wiredash 0.2.0 [flutter http http_parser provider shared_preferences]

dev dependencies:
- build_runner 1.10.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 0.11.6 [analyzer build build_config meta source_gen freezed_annotation]
- grinder 0.8.5 [cli_util glob meta path]
- intl_translation 0.17.10+1 [analyzer args dart_style intl path petitparser]
- json_serializable 3.4.1 [analyzer build build_config json_annotation meta path source_gen]
- pedantic_mono 1.10.0+2
- pubspec_version 0.6.1+archived [args pub_semver pubspec]

dependency overrides:
- flutter_reorderable_list 0.1.4 [flutter]

transitive dependencies:
- _fe_analyzer_shared 7.0.0 [meta]
- analyzer 0.39.17 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- args 1.6.0
- async 2.5.0-nullsafety [collection]
- boolean_selector 2.1.0-nullsafety [source_span string_scanner]
- build 1.3.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.3.11 [analyzer build crypto graphs logging path package_config pub_semver]
- build_runner_core 6.0.1 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- charcode 1.2.0-nullsafety
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety
- cloud_firestore_platform_interface 2.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.0+1 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 2.0.0 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 2.0.0 [cloud_functions_platform_interface flutter flutter_web_plugins firebase http_parser meta]
- code_builder 3.4.1 [built_collection built_value collection matcher meta]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- device_info_platform_interface 1.0.0 [flutter meta plugin_platform_interface]
- extended_image_library 0.3.0 [flutter path_provider http_client_helper crypto path]
- fake_async 1.1.0-nullsafety [clock collection]
- file 5.2.1 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.0+1 [flutter flutter_web_plugins firebase meta http_parser intl firebase_core firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- fixnum 0.10.11
- flutter_cache_manager 1.4.1 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_plugin_android_lifecycle 1.0.8 [flutter]
- flutter_riverpod 0.7.2 [flutter collection riverpod state_notifier]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.1+1 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 0.2.0
- html 0.14.0+3 [csslib source_span]
- http 0.12.2 [http_parser path pedantic]
- http_client_helper 0.2.1 [http]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.0 [flutter meta http plugin_platform_interface]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- logging 0.11.4
- matcher 0.12.10-nullsafety [stack_trace]
- meta 1.3.0-nullsafety.2
- mime 0.9.7
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.14 [flutter path_provider_platform_interface path_provider_macos path_provider_linux]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+3 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- pedantic 1.9.2 [meta]
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- pigment 1.0.3 [flutter]
- platform 2.2.1
- platform_detect 1.4.0 [meta pub_semver]
- plugin_platform_interface 1.0.2 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- protobuf 1.0.1 [fixnum]
- provider 4.3.2+1 [flutter nested collection]
- pub_semver 1.4.4 [collection]
- pubspec 0.1.4 [path pub_semver yaml uri]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.3 [matcher meta]
- riverpod 0.7.0 [meta collection freezed_annotation state_notifier]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- simple_logger 1.7.0 [logging stack_trace]
- sky_engine 0.0.99
- source_gen 0.9.6 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety [charcode collection path term_glyph]
- sqflite 1.3.1+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety [path]
- stream_channel 2.1.0-nullsafety [async]
- string_scanner 1.1.0-nullsafety [charcode source_span]
- subscription_holder 2.0.0+3 [flutter rxdart state_notifier]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety
- test_api 0.2.19-nullsafety [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+2 [json_annotation]
- typed_data 1.3.0-nullsafety.2 [collection]
- uri 0.11.3+1 [matcher quiver utf]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+7 [flutter]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.3+1 [url_launcher_platform_interface platform_detect flutter flutter_web_plugins meta]
- utf 0.9.0+5
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.2
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- xdg_directories 0.1.2 [meta path process]
- xml 4.4.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by Salakar** [comment]
Fixed in dev.3 - thanks for the report :)

**Comment by mono0926** [comment]
@Salakar 

Thanks for the very quick fix!

But https://github.com/invertase/flutterfire/commit/d4c7dfcef6871c3ab33aa0b806ce16f7fa6223a5 only fixed the Android issue and the problem on iOS still remains.

The title of the issue was `🐛 [firebase_crashlytics: 0.2.0-dev.2] Hot restart fails on Android` but I trimmed `on Android` and edited the description because similar problem was reproduced on iOS.

> On iOS, the app freezes without any errors after "Hot Restart".

**Comment by Salakar** [comment]
Woops, didn't see that this was iOS also, dev.4 is up now with a fix for iOS

**Comment by mono0926** [comment]
@Salakar It works fine 👍 Thanks again!
