### ISSUE TITLE
Firebase_auth - An unkown error occured

### ISSUE THREAD

**Issue by vadrian89** [FirebaseExtended/flutterfire#3533]
Hello, 
My login is crashing with the following exception on the web only. 
Android is working fine.

`Error: FormatException: Trying to read EEE from Sat, 12 Sep 2020 10:04:20 GMT at position 0
    at Object.throw_ [as throw] (http://localhost:39009/dart_sdk.js:4334:11)
    at intl._DateFormatPatternField.new.throwFormatException (http://localhost:39009/packages/intl/src/intl_helpers.dart.lib.js:2840:17)
    at intl._DateFormatPatternField.new.parseField (http://localhost:39009/packages/intl/src/intl_helpers.dart.lib.js:3058:14)
    at intl._DateFormatPatternField.new.parse (http://localhost:39009/packages/intl/src/intl_helpers.dart.lib.js:2942:12)
    at intl.DateFormat.new.[_parse] (http://localhost:39009/packages/intl/src/intl_helpers.dart.lib.js:2155:15)
    at intl.DateFormat.new.parse (http://localhost:39009/packages/intl/src/intl_helpers.dart.lib.js:2116:26)
    at new firebase_auth_web_user.UserWeb.new (http://localhost:39009/packages/firebase_auth_web/firebase_auth_web_user_credential.dart.lib.js:165:353)
    at _MapStream.new.<anonymous> (http://localhost:39009/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:286:18)
    at _MapStream.new.[_handleData] (http://localhost:39009/dart_sdk.js:35227:61)
    at _ForwardingStreamSubscription.new.[_handleData] (http://localhost:39009/dart_sdk.js:35134:37)
    at _RootZone.runUnaryGuarded (http://localhost:39009/dart_sdk.js:37383:11)
    at _BroadcastSubscription.new.[_sendData] (http://localhost:39009/dart_sdk.js:30992:22)
    at _BroadcastSubscription.new.[_add] (http://localhost:39009/dart_sdk.js:30938:26)
    at _SyncBroadcastStreamController.new.[_sendData] (http://localhost:39009/dart_sdk.js:31660:34)
    at _SyncBroadcastStreamController.new.add (http://localhost:39009/dart_sdk.js:31454:24)
    at http://localhost:39009/packages/firebase/src/storage.dart.lib.js:1735:43
    at Object._checkAndCall (http://localhost:39009/dart_sdk.js:4544:16)
    at Object.dcall (http://localhost:39009/dart_sdk.js:4549:17)
    at Object.ret [as next] (http://localhost:39009/dart_sdk.js:59952:21)
    at https://www.gstatic.com/firebasejs/7.19.1/firebase-app.js:1:3961
`

This is my flutter doctor output:
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.21.0-9.2.pre, on Linux, locale ro_RO.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Connected device (3 available)`

Tried flutter clean but nothing.
On another project which uses firebase_auth: ^0.16.1, built with the same flutter version, it is working.

**Comment by vadrian89** [comment]
Downgrading to 0.16.1 solved the issue.

**Comment by gtgalone** [comment]
Duplicate #3374

**Comment by darshankawar** [comment]
@vadrian89,
Please follow-up in [3374](https://github.com/FirebaseExtended/flutterfire/issues/3374) for updates and any questions.
Closing this as duplicate.
