### ISSUE TITLE
🐛 firebase_admob Native Ads in example is not working

### ISSUE THREAD

**Issue by DaBotGuy** [FirebaseExtended/flutterfire#3607]
## Bug report

**Describe the bug**
The banner, interstitial and rewarded video ads are working correctly. But, when a native ad is shown in the example. Following exception is thrown

<details><summary>Click To Expand</summary>

```
Unhandled Exception: PlatformException(no_native_ad_factory, There is no non-null NativeAdFactory for the following factoryId: adFactoryExample, null)
E/flutter ( 6979): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:571
E/flutter ( 6979): #1      MethodChannel._invokeMethod 
package:flutter/…/services/platform_channel.dart:160
E/flutter ( 6979): <asynchronous suspension>
E/flutter ( 6979): #2      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:333
E/flutter ( 6979): #3      _invokeBooleanMethod 
package:firebase_admob/firebase_admob.dart:612
E/flutter ( 6979): #4      NativeAd.load 
package:firebase_admob/firebase_admob.dart:346
E/flutter ( 6979): #5      _MyAppState.build.<anonymous closure> 
package:dark_chat/main.dart:407
E/flutter ( 6979): #6      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:993
E/flutter ( 6979): #7      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:1111
I/Choreographer( 6979): Skipped 264 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 6979): Skipped 41 frames!  The application may be doing too much work on its main thread.
W/Ads     ( 6979): #004 The webview is destroyed. Ignoring action.
W/Ads     ( 6979): #004 The webview is destroyed. Ignoring action.
W/Ads     ( 6979): #004 The webview is destroyed. Ignoring action.
W/Ads     ( 6979): #004 The webview is destroyed. Ignoring action.
W/Ads     ( 6979): #004 The webview is destroyed. Ignoring action.
E/flutter ( 6979): #8      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:183
E/flutter ( 6979): #9      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:598
E/flutter ( 6979): #10     BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:287
E/flutter ( 6979): #11     BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:259
E/flutter ( 6979): #12     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:157
E/flutter ( 6979): #13     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:223
E/flutter ( 6979): #14     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:199
E/flutter ( 6979): #15     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:157
E/flutter ( 6979): #16     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:103
E/flutter ( 6979): #17     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:87
E/flutter ( 6979): #18     _rootRunUnary  (dart:async/zone.dart:1206:13)
E/flutter ( 6979): #19     _CustomZone.runUnary  (dart:async/zone.dart:1100:19)
E/flutter ( 6979): #20     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7)
E/flutter ( 6979): #21     _invoke1  (dart:ui/hooks.dart:267:10)
E/flutter ( 6979): #22     _dispatchPointerDataPacket  (dart:ui/hooks.dart:176:5)
```

</details>

### Steps to reproduce

1. Run the example code in the firebase_admob folder.

Versions Im using:

<details><summary>Click To Expand</summary>

```
firebase_admob version: 0.9.3+4 (Its also not working for the 0.10.0-dev.1)

**flutter --version output**
Flutter 1.21.0-10.0.pre.50 • channel master • https://github.com/flutter/flutter.git
Framework • revision 8dcb4c338a (6 weeks ago) • 2020-08-11 17:29:35 -0700
Engine • revision 06458d2f6c
Tools • Dart 2.10.0 (build 2.10.0-11.0.dev)
```

</details>

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel master, 1.21.0-10.0.pre.50, on Microsoft Windows [Version 10.0.18362.1082], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code, 64-bit edition (version 1.48.1)
[√] Connected device (1 available)

• No issues found!
```

</details>

**Comment by DaBotGuy** [comment]
My bad. I havent understood how to register native ad factory.
