### ISSUE TITLE
🐛 [firebase_crashlystics] can not get pass on onboarding page for android

### ISSUE THREAD

**Issue by zirho** [FirebaseExtended/flutterfire#3664]
## Bug report

**Describe the bug**

### Steps to reproduce

1. create firebase project "firebase_test"
2. create a new flutter app with a name "firebase_test"
3. follow instructions here
https://firebase.flutter.dev/docs/crashlytics/overview

4. get the entire example code from here
https://pub.dev/packages/firebase_crashlytics/example

5. log and crash app by using the example code (clicking buttons and restart the apps multiple times)
6. waited about an hour
7. still see the onboarding page

![image](https://user-images.githubusercontent.com/19755104/94330758-2c26f680-ff7c-11ea-98f9-507fa2b35da1.png)

8. Here is the entire code that does not work for me
https://github.com/zirho/firebase_test

### Expected behavior

get pass the onboarding page and see some crash logs

---

## Additional context

no

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
 flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.3 at /Users/zirho6/Documents/flutter
    • Framework revision 216dee60c0 (3 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/zirho6/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • ONEPLUS A6013 (mobile) • 23a4895f                             • android-arm64 • Android 10 (API 29)
    • iPhone 11 Pro (mobile) • 1A833BED-F624-43E4-808C-D14B2AC7F388 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.9.2
Flutter SDK 1.20.3
firebase_test 1.0.0+1

dependencies:
- cupertino_icons 0.1.3
- firebase_analytics 6.0.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_core 0.5.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.0 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.4.2 [collection]
- boolean_selector 2.0.0 [source_span string_scanner]
- characters 1.0.0
- charcode 1.1.3
- clock 1.0.1 [meta]
- collection 1.14.13
- fake_async 1.1.0 [clock collection]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.0.0 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.2
- matcher 0.12.8 [stack_trace]
- meta 1.1.8
- path 1.7.0
- pedantic 1.9.0
- plugin_platform_interface 1.0.2 [meta]
- quiver 2.1.3 [matcher meta]
- sky_engine 0.0.99
- source_span 1.7.0 [charcode collection meta path term_glyph]
- stack_trace 1.9.5 [path]
- stream_channel 2.0.0 [async]
- string_scanner 1.0.5 [charcode meta source_span]
- term_glyph 1.1.0
- test_api 0.2.17 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.2.0 [collection]
- vector_math 2.0.8
```

</details>

---

**Comment by zirho** [comment]
<details><summary>crash logs</summary>

```
Launching lib/main.dart on ONEPLUS A6013 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Waiting for ONEPLUS A6013 to report its views...
Debug service listening on ws://127.0.0.1:59377/GgiNUDBh_Cw=/ws
Syncing files to device ONEPLUS A6013...
E/FirebaseCrashlytics(18765): Failed to retrieve settings from https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:820457391189:android:33220265265531acb000dc/settings
I/flutter (18765): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (18765): The following exception was thrown as an example:
I/flutter (18765): error_example
I/flutter (18765): 
I/flutter (18765): #0      _MyAppState.build.<anonymous closure>.<anonymous closure> (package:firebase_test/main.dart:183:31)
I/flutter (18765): #1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
I/flutter (18765): #2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
I/flutter (18765): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
I/flutter (18765): #4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
I/flutter (18765): #5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
I/flutter (18765): #6      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
I/flutter (18765): #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
I/flutter (18765): #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
I/flutter (18765): #9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
I/flutter (18765): #10     _LinkedHashMapMixin.forEac
I/flutter (18765): ----------------------------------------------------
I/Surface (18765): opservice is null false
D/AndroidRuntime(18765): Shutting down VM
E/AndroidRuntime(18765): FATAL EXCEPTION: main
E/AndroidRuntime(18765): Process: com.aquadesk.firebase_test, PID: 18765
E/AndroidRuntime(18765): io.flutter.plugins.firebase.crashlytics.FirebaseCrashlyticsTestCrash: This is a test crash caused by calling .crash() in Dart.
E/AndroidRuntime(18765): 	at io.flutter.plugins.firebase.crashlytics.FlutterFirebaseCrashlyticsPlugin.lambda$crash$1(FlutterFirebaseCrashlyticsPlugin.java:81)
E/AndroidRuntime(18765): 	at io.flutter.plugins.firebase.crashlytics.-$$Lambda$FlutterFirebaseCrashlyticsPlugin$H0t0BleSpjDMVvqpx8Hy-ZKGwP8.run(Unknown Source:0)
E/AndroidRuntime(18765): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(18765): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(18765): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(18765): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime(18765): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18765): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(18765): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process (18765): Sending signal. PID: 18765 SIG: 9
Lost connection to device.
```

**Comment by zirho** [comment]
I actually started to see some data coming in on the overview page but not in the dashboard
![image](https://user-images.githubusercontent.com/1251296/94332667-eeca6500-ff8b-11ea-907a-42a93b7dcd76.png)

![image](https://user-images.githubusercontent.com/1251296/94332675-f5f17300-ff8b-11ea-92a2-1eb46759a8c6.png)

**Comment by zirho** [comment]
somehow I started to see some logs in the dashboard.
