### ISSUE TITLE
Firebase-database not working on desktop

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#367]
When building for desktop (macOS) the firebase-database plugin throws an exception. Is Firebase not supported on desktop yet?

Log:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      Query._observe.<anonymous closure> (package:firebase_database/src/query.dart:53:38)
#2      _runGuarded (dart:async/stream_controller.dart:805:24)
#3      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
#4      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#5      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#6      Stream.first (dart:async/stream.dart:1188:25)
#7      Query.once (package:firebase_database/src/query.dart:90:55)
<asynchronous suspension>
#8      new RobotsScreen (package:example_flutter/robots.dart:9:42)
...
```

**Comment by rmelian** [comment]
why is this closed, are you not considering desktop support for firebase?

**Comment by Dohmanlechx** [comment]
I am wondering the same thing.
