### ISSUE TITLE
🐛 [cloud_functions] web: `dartify()` throws when a cloud function returns geographic coordinates

### ISSUE THREAD

**Issue by alexandergottlieb** [FirebaseExtended/flutterfire#3690]
## Bug report

I'm using `cloud_functions` on the web to load location data. But I get an exception when the response from a cloud function includes geographic coordinates as a JSON object:

```
{
  "latitude": 51.501091,
  "longitude": -0.124287
}
```

The exception is raised when casting to `GeoPoint` in the following block of code in `firebase-7.3.0/lib/src/utils.dart`:

```
if (util.hasProperty(jsObject, 'latitude') &&
      util.hasProperty(jsObject, 'longitude') &&
      js.objectKeys(jsObject).length == 2) {
    // This is likely a GeoPoint – return it as-is
    return jsObject as GeoPoint;
```

Stack trace:

```
"Error: Expected a value of type 'JSObject<yd>', but got one of type 'NativeJavaScriptObject'
    at Object.throw_ [as throw] (http://localhost:57353/dart_sdk.js:4328:11)
    at Object.castError (http://localhost:57353/dart_sdk.js:4299:15)
    at dart.LazyJSType.new.as (http://localhost:57353/dart_sdk.js:6055:55)
    at Object.dartify (http://localhost:57353/packages/firebase/src/storage.dart.lib.js:3191:108)
    at Object.dartifyMap (http://localhost:57353/packages/firebase/src/storage.dart.lib.js:3206:29)
    at Object.dartify (http://localhost:57353/packages/firebase/src/storage.dart.lib.js:3200:18)
    at Object.dartifyMap (http://localhost:57353/packages/firebase/src/storage.dart.lib.js:3206:29)
    at MappedListIterable.new.dartify (http://localhost:57353/packages/firebase/src/storage.dart.lib.js:3200:18)
    at MappedListIterable.new.elementAt (http://localhost:57353/dart_sdk.js:21541:25)
    at ListIterator.new.moveNext (http://localhost:57353/dart_sdk.js:21335:55)
    at JsIterator.next (http://localhost:57353/dart_sdk.js:5997:21)
    at Function.from (http://localhost:57353/dart_sdk.js:43902:20)
    at Function.of (http://localhost:57353/dart_sdk.js:43917:30)
    at MappedListIterable.new.toList (http://localhost:57353/dart_sdk.js:21141:26)
    at Object.dartify (http://localhost:57353/packages/firebase/src/storage.dart.lib.js:3181:66)
    at Object.dartifyMap (http://localhost:57353/packages/firebase/src/storage.dart.lib.js:3206:29)
    at Object.dartify (http://localhost:57353/packages/firebase/src/storage.dart.lib.js:3200:18)
    at functions.HttpsCallableResult._fromJsObject.get data [as data] (http://localhost:57353/packages/firebase/src/storage.dart.lib.js:975:47)
    at http://localhost:57353/packages/cloud_functions_web/cloud_functions_web.dart.lib.js:39:78
    at _RootZone.runUnary (http://localhost:57353/dart_sdk.js:37447:58)
    at _FutureListener.then.handleValue (http://localhost:57353/dart_sdk.js:32424:29)
    at handleValueCallback (http://localhost:57353/dart_sdk.js:32971:49)
    at Function._propagateToListeners (http://localhost:57353/dart_sdk.js:33009:17)
    at _Future.new.[_completeWithValue] (http://localhost:57353/dart_sdk.js:32852:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:57353/dart_sdk.js:32874:35)
    at Object._microtaskLoop (http://localhost:57353/dart_sdk.js:37708:13)
    at _startMicrotaskLoop (http://localhost:57353/dart_sdk.js:37714:13)
    at http://localhost:57353/dart_sdk.js:33226:9"
```

### Steps to reproduce

1. Create a cloud function that returns a JSON object like `{ "latitude": 51.501091, "longitude": -0.124287 }`
1. Call this function from Flutter on the web like below:

```
final HttpsCallable searchFunction = CloudFunctions.instance.getHttpsCallable(
  functionName: 'searchLocations',
);
final response = await searchFunction.call(<String, dynamic>{});
```

### Expected behavior

The `cloud_functions` web implementation should be able to receive JSON data of the form `{ latitude, longitude }` from a callable function without throwing.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel beta, 1.22.0-12.2.pre, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.0-12.2.pre at /Users/xander/development/flutter
    • Framework revision 2bafdc8226 (4 days ago), 2020-09-25 12:48:22 -0700
    • Engine revision f763b5b9b9
    • Dart version 2.10.0 (build 2.10.0-110.5.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/xander/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.0-110.5.beta
Flutter SDK 1.22.0-12.2.pre
project 0.0.1+1

dependencies:
- cloud_firestore 0.14.0+2 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_functions 0.6.0 [meta flutter firebase_core cloud_functions_platform_interface cloud_functions_web]
- collection 1.15.0-nullsafety.2
- cupertino_icons 1.0.0
- firebase_core 0.5.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_dynamic_links 0.6.0 [flutter firebase_core]
- firebase_messaging 7.0.0 [meta platform flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_advanced_networkimage 0.7.0 [flutter http path_provider path flutter_svg]
- font_awesome_flutter 8.8.1 [flutter]
- geocoding 1.0.4+1 [flutter geocoding_platform_interface url_launcher]
- geolocator 6.0.0+4 [flutter geolocator_platform_interface]
- google_maps_flutter 0.5.33 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_maps_flutter_web 0.1.0+2 [flutter flutter_web_plugins meta google_maps_flutter_platform_interface google_maps stream_transform sanitize_html]
- http 0.12.2 [http_parser path pedantic]
- path_provider 1.6.18 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_to_regexp 0.3.0
- provider 4.3.2+2 [flutter nested collection]
- rxdart 0.24.1
- share 0.6.5+2 [meta mime flutter]
- shared_preferences 0.5.12 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- url_launcher 5.7.2 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]

dev dependencies:
- flutter_launcher_icons 0.7.5 [image args yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

dependency overrides:
- flutter_svg 0.18.1 [path_drawing xml vector_math meta flutter]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety [collection]
- boolean_selector 2.1.0-nullsafety [source_span string_scanner]
- characters 1.1.0-nullsafety.2
- charcode 1.2.0-nullsafety
- clock 1.1.0-nullsafety
- cloud_firestore_platform_interface 2.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.0+1 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 2.0.0 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 2.0.0 [cloud_functions_platform_interface flutter flutter_web_plugins firebase http_parser meta]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- fake_async 1.1.0-nullsafety [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- geocoding_platform_interface 1.0.1+1 [flutter meta plugin_platform_interface]
- geolocator_platform_interface 1.0.4 [flutter meta plugin_platform_interface vector_math]
- google_maps 3.4.5 [js_wrapping meta]
- google_maps_flutter_platform_interface 1.0.4 [flutter meta plugin_platform_interface stream_transform]
- html 0.14.0+3 [csslib source_span]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.18 [archive xml meta]
- intl 0.16.1 [path]
- js 0.6.2
- js_wrapping 0.5.0
- matcher 0.12.10-nullsafety [stack_trace]
- meta 1.3.0-nullsafety.2
- mime 0.9.7
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.2 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.3 [matcher meta]
- sanitize_html 1.3.0 [html meta]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety [path]
- stream_channel 2.1.0-nullsafety [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety [charcode source_span]
- term_glyph 1.2.0-nullsafety
- test_api 0.2.19-nullsafety [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.2 [collection]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.4+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- vector_math 2.1.0-nullsafety.2
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by TahaTesser** [comment]
<details> 
<summary>test function example</summary> 

```dart

const functions = require('firebase-functions');

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
exports.test_obj = functions.https.onCall((request, response) => {
    //   functions.logger.info("Hello logs!", {structuredData: true});
    //   response.send("Hello from Firebase!");

    return {
        "latitude": 51.501091,
        "longitude": -0.124287
    };
});

```

</details> 

<details> 
<summary>complete code sample</summary> 

```dart
// Copyright 2018, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:cloud_functions/cloud_functions.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  String _response = 'no response';
  int _responseCount = 0;

  @override
  Widget build(BuildContext context) {
    final HttpsCallable callable = CloudFunctions.instance
        .getHttpsCallable(functionName: 'test_obj')
          ..timeout = const Duration(seconds: 30);
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Cloud Functions example app'),
        ),
        body: Center(
          child: Container(
            margin: const EdgeInsets.only(top: 32.0, left: 16.0, right: 16.0),
            child: Column(
              children: <Widget>[
                Text('Response $_responseCount: $_response'),
                MaterialButton(
                  child: const Text('SEND REQUEST'),
                  onPressed: () async {
                    try {
                      final HttpsCallableResult result = await callable.call(
                        <String, dynamic>{
                          'message': 'hello world!',
                          'count': _responseCount,
                        },
                      );
                      print(result.data);
                      setState(() {
                        _response = result.data['repeat_message'];
                        _responseCount = result.data['repeat_count'];
                      });
                    } on CloudFunctionsException catch (e) {
                      print('caught firebase functions exception');
                      print(e.code);
                      print(e.message);
                      print(e.details);
                    } catch (e) {
                      print('caught generic exception');
                      print(e);
                    }
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details> 

<details> 
<summary>logs</summary> 

```bash
[ +105 ms] executing: [C:\Code\flutter_beta/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +53 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 198df796aa80073ef22bdf249e614e2ff33c6895
[        ] executing: [C:\Code\flutter_beta/] git tag --points-at HEAD
[  +40 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.23.0-18.1.pre
[   +8 ms] executing: [C:\Code\flutter_beta/] git rev-parse --abbrev-ref --symbolic @{u}
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\Code\flutter_beta/] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +55 ms] executing: [C:\Code\flutter_beta/] git rev-parse --abbrev-ref HEAD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +49 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +52 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +37 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[  +13 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +14 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +57 ms] executing: C:\Code\sdk\platform-tools\adb.exe devices -l
[  +43 ms] Found plugin cloud_functions at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_functions-0.6.0+1\
[   +9 ms] Found plugin cloud_functions_web at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_functions_web-2.0.0\
[   +7 ms] Found plugin firebase_core at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.5.0+1\
[   +7 ms] Found plugin firebase_core_web at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[ +110 ms] Found plugin cloud_functions at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_functions-0.6.0+1\
[   +3 ms] Found plugin cloud_functions_web at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_functions_web-2.0.0\
[   +4 ms] Found plugin firebase_core at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.5.0+1\
[  +12 ms] Found plugin firebase_core_web at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[  +26 ms] Generating
C:\Users\Taha\AndroidStudioProjects\triage\flutterfire_examples\cloud_functions_example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +42 ms] List of devices attached
[  +49 ms] Launching lib\main.dart on Chrome in debug mode...
[  +16 ms] List of devices attached
[  +90 ms] Updating assets
[  +82 ms] Syncing files to device Chrome...
[  +12 ms] Found plugin cloud_functions at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_functions-0.6.0+1\
[   +4 ms] Found plugin cloud_functions_web at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_functions_web-2.0.0\
[   +4 ms] Found plugin firebase_core at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.5.0+1\
[  +12 ms] Found plugin firebase_core_web at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[  +28 ms] Found plugin cloud_functions at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_functions-0.6.0+1\
[  +10 ms] Found plugin cloud_functions_web at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\cloud_functions_web-2.0.0\
[   +4 ms] Found plugin firebase_core at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-0.5.0+1\
[   +7 ms] Found plugin firebase_core_web at
C:\Users\Taha\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core_web-0.2.0\
[  +11 ms] Generating
C:\Users\Taha\AndroidStudioProjects\triage\flutterfire_examples\cloud_functions_example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +54 ms] <- reset
[   +8 ms] C:\Code\flutter_beta\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\Code\flutter_beta\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\Code\flutter_beta\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Taha\AppData\Local\Temp\flutter_tools.1410eb74\flutter_tool.c370ec35\app.dill --libraries-spec
file:///C:/Code/flutter_beta/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
C:\Users\Taha\AppData\Local\Temp\flutter_tools.1410eb74\flutter_tools.ea88bb1a --filesystem-scheme org-dartlang-app
--initialize-from-dill build\cache.dill.track.dill --platform
file:///C:/Code/flutter_beta/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +17 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+14339 ms] Syncing files to device Chrome... (completed in 14,509ms, longer than expected)
[   +2 ms] Synced 28.9MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[ +167 ms] Using Opening in existing browser session.

[ +217 ms] [CHROME]:
[  +11 ms] [CHROME]:DevTools listening on ws://127.0.0.1:61533/devtools/browser/f329668b-322f-4643-9802-58525c9f81f1
[+5674 ms] Debug service listening on ws://127.0.0.1:61557/AfJDBOvV-qI=

[ +225 ms] Debug service listening on ws://127.0.0.1:61557/AfJDBOvV-qI=
[   +3 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[  +15 ms] been thoroughly tested in production environments.
[   +1 ms] For more information see https://flutter.dev/web
[   +1 ms]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+62198 ms] Cannot find native JavaScript type (firebase.firestore.GeoPoint) for type check
[   +2 ms] caught generic exception
[   +1 ms] Expected a value of type 'Map<String, dynamic>', but got one of type 'NativeJavaScriptObject'
[+23564 ms] Stopped debug service on ws://127.0.0.1:61557

[  +37 ms] Failed to clean up temp directory: C:\Users\Taha\AppData\Local\Temp\flutter_tools.1410eb74\flutter_tools.ea88bb1a[   +1 ms] Failed to clean up temp directory: C:\Users\Taha\AppData\Local\Temp\flutter_tools.1410eb74\flutter_tools.ea88bb1a[   +1 ms] Application finished.
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.23.0-18.1.pre at C:\Code\flutter_beta
    • Framework revision 198df796aa (20 hours ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] Android Studio
    • Android Studio at C:\Code\android-studio\
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = C:\Code\android-studio\
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.50.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.1

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.75

• No issues found!
```

</details> 

Related https://github.com/FirebaseExtended/flutterfire/issues/3098

**Comment by russellwheatley** [comment]
I believe this problem has been rectified now, please use the latest web versions as recommended in the [documentation](https://firebase.flutter.dev/docs/functions/overview#3-web-only-add-the-sdk):

```html
	<script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-functions.js"></script>
```

along with the latest functions version:

```yaml
  firebase_core: "^1.0.4"
  cloud_functions: "^1.0.4"
```
