### ISSUE TITLE
🐛 [firebase_auth] Randomly getting "bad state" on Flutter 1.22 on build

### ISSUE THREAD

**Issue by stx** [FirebaseExtended/flutterfire#3756]
Using iOS 14.0 device. Started with 1.22. Seems to happen completely randomly because I am not doing anything to FirebaseAuth other than making occasional .currentUser.email/uid calls.

Happens on stable and master.

```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: Bad state: Cannot add new events while doing an addStream
flutter:
#0      _BroadcastStreamController.add  (dart:async/broadcast_stream_controller.dart:249:24))
#1      FirebaseAuth._pipeStreamChanges.<anonymous closure> 
package:firebase_auth/src/firebase_auth.dart:236
#2      _runGuarded  (dart:async/stream_controller.dart:847:24))
#3      _BroadcastStreamController._subscribe  (dart:async/broadcast_stream_controller.dart:213:7))
#4      _ControllerStream._createSubscription  (dart:async/stream_controller.dart:860:19))
#5      _StreamImpl.listen  (dart:async/stream_impl.dart:493:9))
#6      _StreamBuilderBaseState._subscribe 
package:flutter/…/widgets/async.dart:137
#7      _StreamBuilderBaseState.initState 
package:flutter/…/widgets/async.dart:111
#8      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4793
#9      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4630
#10     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3596

```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel master, 1.23.0-8.0.pre.127, on Mac OS X 10.15.6 19G2021 x86_64, locale en-US)
    • Flutter version 1.23.0-8.0.pre.127 at /Users/james/Development/flutter
    • Framework revision 63852d2073 (6 hours ago), 2020-10-03 09:14:48 -0700
    • Engine revision a24c7c1392
    • Dart version 2.11.0 (build 2.11.0-183.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/james/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[✓] Connected device (4 available)
    • Virgo (mobile)   • 00008030-000848D11EF0802E • ios            • iOS 14.0
    • macOS (desktop)  • macos                     • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web) • web-server                • web-javascript • Flutter Tools
    • Chrome (web)     • chrome                    • web-javascript • Google Chrome 85.0.4183.121

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- ansicolor 1.0.5
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.1.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.0+3 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 2.0.0 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 2.0.0 [cloud_functions_platform_interface flutter flutter_web_plugins firebase http_parser meta]
- collection 1.15.0-nullsafety.3
- console_log_handler 1.1.6 [logging intl ansicolor]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_auth_platform_interface 2.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.1 [flutter flutter_web_plugins firebase meta http_parser intl firebase_core firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.0 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- google_maps_flutter_platform_interface 1.0.4 [flutter meta plugin_platform_interface stream_transform]
- google_maps_webservice 0.0.18 [http meta]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.18 [archive xml meta]
- intl 0.16.1 [path]
- js 0.6.2
- location_platform_interface 1.0.0 [flutter meta plugin_platform_interface]
- location_web 1.0.0 [flutter flutter_web_plugins location_platform_interface http_parser meta js]
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.3 [matcher meta]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.2 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- syncfusion_flutter_core 18.3.35 [flutter pedantic]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.4+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- validate 1.7.0
- vector_math 2.1.0-nullsafety.3
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

**Comment by sarbogast** [comment]
I'm having the same issue right now, but it's everything but random, and not limited to iOS either. I have the same issue on Android 29:

> E/flutter ( 4420): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Cannot add new events while doing an addStream
> E/flutter ( 4420): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:249:24)
> E/flutter ( 4420): #1      FirebaseAuth._pipeStreamChanges.<anonymous closure> (package:firebase_auth/src/firebase_auth.dart:236:24)
> E/flutter ( 4420): #2      _runGuarded (dart:async/stream_controller.dart:847:24)
> E/flutter ( 4420): #3      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
> E/flutter ( 4420): #4      _ControllerStream._createSubscription (dart:async/stream_controller.dart:860:19)
> E/flutter ( 4420): #5      _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
> E/flutter ( 4420): #6      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:139:37)
> E/flutter ( 4420): #7      _StreamBuilderBaseState.initState (package:flutter/src/widgets/async.dart:113:5)
> E/flutter ( 4420): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
> E/flutter ( 4420): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
> E/flutter ( 4420): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
> E/flutter ( 4420): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
> E/flutter ( 4420): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
> E/flutter ( 4420): #13     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
> E/flutter ( 4420): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
> E/flutter ( 4420): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
> E/flutter ( 4420): #16     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
> E/flutter ( 4420): #17     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
> E/flutter ( 4420): #18     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
> E/flutter ( 4420): #19     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
> E/flutter ( 4420): #20     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
> E/flutter ( 4420): #21     _rootRun (dart:async/zone.dart:1190:13)
> E/flutter ( 4420): #22     _CustomZone.run (dart:async/zone.dart:1093:19)
> E/flutter ( 4420): #23     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> E/flutter ( 4420): #24     _invoke (dart:ui/hooks.dart:251:10)
> E/flutter ( 4420): #25     _drawFrame (dart:ui/hooks.dart:209:3)

**Comment by cedvdb** [comment]
Same issue, happening on hot restarts

**Comment by ioridev** [comment]
I have the same issue ...

**Comment by th8m0z** [comment]
It's happening to me too every time I do a hot restart. Did anybody manage do fix it?

**Comment by russellwheatley** [comment]
Hey @stx, are you still having the same trouble? Flutter and the auth package are now on the next major release since this issue. Failing that, this [PR](https://github.com/FirebaseExtended/flutterfire/pull/4643) will be released next week that might have an impact on this bug.
