### ISSUE TITLE
Fatal error: PluginRegistrantCallback is not set

### ISSUE THREAD

**Issue by michaelu123** [FirebaseExtended/flutterfire#3760]
Hi, I think I currently have the most up-to-date software, but when I send a message via the firebase console/Cloud Messaging my app, which is running in the foreground, crashes with:

```
D/AndroidRuntime(16432): Shutting down VM
E/AndroidRuntime(16432): FATAL EXCEPTION: main
E/AndroidRuntime(16432): Process: com.example.chat, PID: 16432
E/AndroidRuntime(16432): java.lang.RuntimeException: Unable to create service io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService: java.lang.RuntimeException: PluginRegistrantCallback is not set.
E/AndroidRuntime(16432): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3349)
E/AndroidRuntime(16432): 	at android.app.ActivityThread.-wrap4(Unknown Source:0)
E/AndroidRuntime(16432): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
E/AndroidRuntime(16432): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16432): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(16432): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(16432): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16432): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(16432): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime(16432): Caused by: java.lang.RuntimeException: PluginRegistrantCallback is not set.
E/AndroidRuntime(16432): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.startBackgroundIsolate(FlutterFirebaseMessagingService.java:157)
E/AndroidRuntime(16432): 	at io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService.onCreate(FlutterFirebaseMessagingService.java:77)
E/AndroidRuntime(16432): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
E/AndroidRuntime(16432): 	... 8 more

```
In the document https://pub.dev/packages/firebase_messaging it says,  put a file Application.java besides MainActivity.java, but first there is no MainActivity.java, but a MainActivity.kt, second, if I add MainActivity.java, it generates compiler errors:

```
...\android\app\src\main\java\Application.java:13: error: cannot access FirebaseMessagingService
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
                                   ^
  class file for com.google.firebase.messaging.FirebaseMessagingService not found
C:\Users\Michael\FlutterProjects\chat\android\app\src\main\java\Application.java:18: error: incompatible types: PluginRegistry cannot be converted to FlutterEngine
    GeneratedPluginRegistrant.registerWith(registry);
                                           ^
```

In https://github.com/FirebaseExtended/flutterfire/issues/3757 , an issue that is two hours old, I see something that looks like an Application.kt file. Itried this, and changed my android:name in AndroidManifest.xml from ".MainActivity" to ".App", but then I get the error message that an Application cannot be cast to an Activity.

Worst of all, I do not even intend to receive background messages at all. For some hours, I was able to receive  onLaunch/onMessage/onResume messages, then I made the mistake to configure also onBackgroundMessage, I no longer configure onBackgroundMessage, but I must have changed something else, so that "normal" messages also stopped working...

**Comment by michaelu123** [comment]
A bit further: On https://stackoverflow.com/questions/59446933/pluginregistry-cannot-be-converted-to-flutterengine/60958130#60958130 I found an Application.java:

```
package ...;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin;

import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.os.Build;
import android.util.Log;


public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FlutterFirebaseMessagingService.setPluginRegistrant(this);

    if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O){
      NotificationChannel channel = new NotificationChannel("messages","Messages", NotificationManager.IMPORTANCE_LOW);
      NotificationManager manager = getSystemService(NotificationManager.class);
      manager.createNotificationChannel(channel);
    }
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
  }
}

```
and I also learned that in AndroidManifest.xml there is an android:name for the Application, which I set to ".Application", and left the activity android:name unchanged to ".MainActivity", but this did not remove the bug. I am not sure if Application.java is executed at all.

**Comment by michaelu123** [comment]
Also with the Application.kt from https://github.com/FirebaseExtended/flutterfire/issues/3757:
```
package ...

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

class App : FlutterApplication(), PluginRegistrantCallback {

    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
    }
}
```
and AndroidManifest.xml:

```
   <application
        android:label="chat"
        android:icon="@mipmap/ic_launcher">
        android:name=".App"
        <activity
            android:name=".MainActivity"
...
```
no success, I wonder how I can insert logging statements into the above code that appears in the VS Code Debug Console. For Application.java, neither System.out.print nor Log.e showed any output. Because the code was not executed, or because the output went to /dev/null?

**Comment by michaelu123** [comment]
A stupid mistake in the AndroidManifest.xml above: the android:name is outside the <application> tag, It must of course be:
```
   <application
        android:label="chat"
        android:name=".App"
        android:icon="@mipmap/ic_launcher">
```
With that, and the Application.kt, it works.
