### ISSUE TITLE
🐛 [firebase_storage] App crashes on iOS when trying to upload image using image_picker

### ISSUE THREAD

**Issue by Unown-Fashion** [FirebaseExtended/flutterfire#3776]
## Bug report

**Describe the bug**
App crashes on iOS when trying to upload image to Storage, selected from [image_picker](https://pub.dev/packages/image_picker), despite the code being wrapped in try/catch. 

Here's error code:
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(storage_error, NSInternalInconsistencyException, URI must be in the form of gs://<bucket>/)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#3      _StorageFileUploadTask._platformStart (package:firebase_storage/src/upload_task.dart:130:36)
#4      StorageUploadTask._start (package:firebase_storage/src/upload_task.dart:35:21)
#5      StorageReference.putFile (package:firebase_storage/src/storage_reference.dart:65:10)
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all
details, run flutter doctor
-v):
[✓] Flutter (Channel stable,
    1.22.0, on Mac OS X
    10.15.7 19H2, locale
    ru-UA)
 
[✓] Android toolchain -          develop for Android          devices (Android SDK
    version 30.0.0)
[✓] Xcode - develop for iOS
    and macOS (Xcode 11.7)
[✓] Android Studio (version
    4.0)
[✓] VS Code (version 1.49.2)
[✓] Connected device (1
    available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
image_picker: ^0.6.6+1
firebase_storage: 4.0.1
```

</details>

---

**Comment by Unown-Fashion** [comment]
Here's the code:
```
var image = await ImagePicker().getImage(source: ImageSource.gallery);

    /// Pushing image to Firebase Storage
    if (image != null) {
      setState(() {
        _loadingProfilePhoto = true;
      });
      StorageReference ref = FirebaseStorage.instance.ref();
      StorageTaskSnapshot addImg;
      try {
        addImg = await ref
            .child("profiles/${Storage.customerId}")
            .putFile(File(image.path))
            .onComplete;
      } catch (error) {
        print(error);
      }
```

**Comment by helenaford** [comment]
Can confirm this works this using the prerelease version of `firebase_storage`.  
```
    var image = await ImagePicker().getImage(source: ImageSource.gallery);
    if (image == null) return;

    firebase_storage.UploadTask task = firebase_storage.FirebaseStorage.instance
        .ref('testImage.png')
        .putFile(File(image.path));

    try {
       await task;
    } on FirebaseException catch (e) {
       print(e);
    }
```

**Comment by Unown-Fashion** [comment]
@helenaford 
Thanks for response.
Just tried your solution, but it throws error in my case with following message:
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
#0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:118:5)
#1      Firebase.app (package:firebase_core/src/firebase.dart:52:41)
#2      FirebaseStorage.instance (package:firebase_storage/src/firebase_storage.dart:53:21)
...
```

**Comment by helenaford** [comment]
No problem, happy to help. For the error that's being thrown, please read the migration guide (https://firebase.flutter.dev/docs/migration), in particular this part (https://firebase.flutter.dev/docs/migration#4-initialize-flutterfire). 
Will need to initialize the app first with `await Firebase.initializeApp();`. 
Closing this issue as I believe it's fixed in the rework of Storage.
