### ISSUE TITLE
🐛 [firebase_storage] UploadTask pauses without warning when network is disabled

### ISSUE THREAD

**Issue by crtl** [FirebaseExtended/flutterfire#3784]
## Bug report

**Describe the bug**

Uploading a file while having network disabled (Airplane mode) on Android the UploadTask pauses itself and logs `W/ExponenentialBackoff(12480): network unavailable, sleeping.` without emitting any kind of state / event to notify about network not being available.

### Steps to reproduce

1. Enable Airplane mode
2. Use a simple file upload like:
    ```flutter
    final file = await pickFile();
    final task = FirebaseStorage.instance.ref().child("path/file.txt").putFile(file);

    task.events.listen((event) {
      print(event.type)
    });
    ```
Only prints `StorageTaskEventType.progress` twice.
`W/ExponenentialBackoff(28410): network unavailable, sleeping.` is logged as warning to the console.

After a while the following exception is thrown and logged internally:
```
E/StorageException(28410): StorageException has occurred.
E/StorageException(28410): The operation retry limit has been exceeded.
E/StorageException(28410):  Code: -13030 HttpResult: -2
E/StorageException(28410): Network subsystem is unavailable
E/StorageException(28410): java.net.SocketException: Network subsystem is unavailable
E/StorageException(28410): 	at com.google.firebase.storage.network.NetworkRequest.ensureNetworkAvailable(com.google.firebase:firebase-storage@@19.1.1:294)
E/StorageException(28410): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(com.google.firebase:firebase-storage@@19.1.1:283)
E/StorageException(28410): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(com.google.firebase:firebase-storage@@19.1.1:103)
E/StorageException(28410): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(com.google.firebase:firebase-storage@@19.1.1:62)
E/StorageException(28410): 	at com.google.firebase.storage.GetDownloadUrlTask.run(com.google.firebase:firebase-storage@@19.1.1:76)
E/StorageException(28410): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/StorageException(28410): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/StorageException(28410): 	at java.lang.Thread.run(Thread.java:923)
I/flutter (28410): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (28410): PlatformException(download_error, The operation retry limit has been exceeded., null, null)
```

### Expected behavior

An event should be emitted notifying users about connection state or an exception should be thrown.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel master, 1.23.0-8.0.pre.132, on Microsoft Windows [Version 10.0.18363.1082], locale en-DE)
    • Flutter version 1.23.0-8.0.pre.132 at D:\dev\flutter\sdk
    • Framework revision 5e97eed895 (28 hours ago), 2020-10-05 00:42:50 -0700
    • Engine revision a8d7d97bef
    • Dart version 2.11.0 (build 2.11.0-185.0.dev)

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact | grep fire` and paste the output below:

<details><summary>Click To Expand</summary>

```
- cloud_firestore 0.14.1+2 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_functions 0.6.0+1 [meta flutter firebase_core cloud_functions_platform_interface cloud_functions_web]
- firebase_analytics 6.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.1+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_dynamic_links 0.6.0+1 [flutter firebase_core]
- firebase_messaging 7.0.2 [meta flutter firebase_core]
- firebase_storage 4.0.1 [flutter firebase_core]
- cloud_firestore_platform_interface 2.1.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.0+3 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 2.0.0 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 2.0.0 [cloud_functions_platform_interface flutter flutter_web_plugins firebase http_parser meta]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.1 [flutter flutter_web_plugins firebase meta http_parser intl firebase_core firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.0 [flutter meta collection firebase_core plugin_platform_interface]

```

</details>

---

**Comment by Ehesp** [comment]
Will have to check whether the SDKs support that, however the error being thrown should at least be a FirebaseException.

**Comment by crtl** [comment]
@greghesp Problem with an exception is that this is in fact expected behaviour which is not communiated well.
I think the current bug is that `StorageTaskEventType.pause` is not emitted or if this type is only to be associated with calling `pause` on the task then a new type should be added like `StorageTaskEventType.suspended`

**Comment by Ehesp** [comment]
Yeah unfortunately those sorts of events are out of our control. We relay what the native SDK emits into Dart. We'll do some digging though on whether network based changes can be handled.

**Comment by Salakar** [comment]
Unfortunately network events are not something we handle in FlutterFire as we simply wrap the native SDKs and expose only the APIs they provide.
