### ISSUE TITLE
🐛 [cloud_firestore] Vague exception report - PlatformException(firebase_firestore, length=11; index=11, {}, null)

### ISSUE THREAD

**Issue by larssn** [FirebaseExtended/flutterfire#3862]
## Bug report

**Describe the bug**
I have a hundreds of occurrences of the following error in our sentry.io:
```
PlatformException: PlatformException(firebase_firestore, length=11; index=11, {}, null)
  File "message_codecs.dart", line 582, in StandardMethodCodec.decodeEnvelope
  File "platform_channel.dart", line 159, in MethodChannel._invokeMethod
  File "<asynchronous suspension>"
  File "method_channel_query.dart", line 139, in MethodChannelQuery.snapshots.<fn>
  File "<asynchronous suspension>"
  File "unparsed"
```
Also this one:
`PlatformException(firebase_firestore, length=95; index=95, {}, null)`

From VSCode:
```
I/flutter (26225): Caught error: PlatformException(firebase_firestore, src.length=95 srcPos=92 dst.length=95 dstPos=93 length=-37, {}, null)
I/flutter (26225): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:582
I/flutter (26225): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:159
I/flutter (26225): <asynchronous suspension>
I/flutter (26225): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
I/flutter (26225): #3      MethodChannelDocumentReference.snapshots.<anonymous closure>
package:cloud_firestore_platform_interface/…/method_channel/method_channel_document_reference.dart:110
I/flutter (26225): #4      _runGuarded (dart:async/stream_controller.dart:847:24)
I/flutter (26225): #5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
I/flutter (26225): #6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:860:19)
I/flutter (26225): #7      _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
I/flutter (26225): #8      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
I/flutter (26225): #9      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
I/flutter (26225): #10     _ForwardingStream.listen (dart:async/stream_p <cuts off>
```

I have no idea what it means as the error description is vague.
It only comes from Android devices.

I'm not sure this causes any problems, as we've had no stability complaints.

**EDIT**
I have run into this one personally, see the reproduction section 

### Steps to reproduce

It's periodic and very rare but I've hit it **once** myself running the following code:
```
Stream<MyUser> read() {
    return _auth.authStateChanges().switchMap((myUser) {
      if (myUser != null) {
        return _fs.doc('users/${myUser.uid}').snapshots().map((userSnapshot) {
          if (userSnapshot.exists) return MyUser.fromSnapshot(userSnapshot);

          return null;
        });
      }

      return Stream.value(null);
    }).handleError((_) => null); // Handles logout events
  }

  /// Returns a list of the businesses the logged in user has access to.
  Stream<BuiltList<Business>> listMyBusinesses() {
    return _myUserRepo.read().switchMap((user) {
      if (user?.businesses?.isEmpty ?? true) return Stream.value(BuiltList<Business>([]));

      final businesses = <Stream<Business>>[];
      for (final busId in user.businesses.keys) {
        businesses.add(_busRepo.read(busId));
      }

      return Rx.combineLatest(
          businesses,
          (List<Business> list) =>
              BuiltList<Business>(list.where((business) => !business.deleted).toList()..sort((a, b) => a.name.compareTo(b.name))));
    });
  }

  listMyBusinesses().listen((_) {});
```

Whats suspicious about the above code is that it adds a lot of listeners rapidly.
So maybe that hits a race condition in an internal list of subscriptions internally in the cloud_firestore plugin (which could make sense since the error hints at "indexes"). I'm just speculating.

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.13.6 17G14033, locale en-DK)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.0)
[✓] Connected device (2 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.3
Flutter SDK 1.22.3
tillty 5.16.7+51607

dependencies:
- animated_text_kit 2.5.4 [flutter characters]
- audioplayers 0.16.2 [uuid path_provider flutter flutter_web_plugins]
- bloc 6.1.0 [meta]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
- charts_flutter 0.9.0 [charts_common collection flutter intl logging meta]
- cloud_firestore 0.14.3 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- country_code_picker 1.6.2 [flutter modal_bottom_sheet]
- country_pickers 1.3.0 [flutter]
- crypto 2.1.5 [collection convert typed_data]
- cupertino_icons 1.0.0
- dart_date 1.0.7 [intl timeago]
- data_connection_checker 0.3.4
- device_info 1.0.0 [flutter device_info_platform_interface]
- drag_and_drop_gridview 1.0.8 [flutter]
- firebase_auth 0.18.3 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.3 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_dynamic_links 0.6.2 [flutter firebase_core]
- firebase_storage 4.0.1 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.1.0 [flutter bloc provider]
- flutter_dotenv 2.1.0 [flutter meta]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_material_color_picker 1.0.5 [flutter]
- flutter_nfc_acs 0.1.6 [flutter flutter_plugin_android_lifecycle]
- flutter_slidable 0.5.7 [flutter]
- flutter_vibrate 1.0.0 [flutter]
- http 0.12.2 [http_parser path pedantic]
- image 2.1.18 [archive xml meta]
- image_picker 0.6.7+12 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.16.1 [path]
- nfc_in_flutter 2.0.5 [flutter]
- package_info 0.4.3+2 [flutter]
- phone_number 0.8.1 [meta flutter]
- positioned_tap_detector 1.0.3 [flutter]
- provider 4.3.2+2 [flutter nested collection]
- qr_flutter 3.2.0 [flutter qr]
- random_string 2.1.0
- reorderables 0.3.2 [flutter]
- rxdart 0.24.1
- sentry 3.0.1 [http meta stack_trace usage pedantic]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sprintf 5.0.0
- strings 0.1.4 [characters unicode]
- time 1.3.0
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- uuid 2.2.2 [crypto convert]
- validators 2.0.1 [vin_decoder]

dev dependencies:
- build_runner 1.10.4 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- built_value_generator 7.1.0 [analyzer build build_config built_collection built_value source_gen quiver]
- intl_translation 0.17.10+1 [analyzer args dart_style intl path petitparser]

dependency overrides:
- analyzer 0.40.6 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]

transitive dependencies:
- _fe_analyzer_shared 12.0.0 [meta]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.4.2 [collection]
- basic_utils 2.7.0-rc.1 [http logging json_annotation pointycastle convert crypto]
- build 1.5.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.4.3 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.0.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- characters 1.1.0-nullsafety.3
- charcode 1.1.3
- charts_common 0.9.0 [collection intl logging meta vector_math]
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.0.1 [meta]
- cloud_firestore_platform_interface 2.2.0 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- dart_style 1.3.9 [analyzer args path source_span]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 2.1.3 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.3 [flutter meta collection firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_annotation 3.1.0
- lists 0.1.6
- logging 0.11.4
- matcher 0.12.9 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- modal_bottom_sheet 1.0.1-dev [flutter]
- nested 0.0.4 [flutter]
- node_interop 1.2.0 [js]
- node_io 1.1.1 [node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 2.0.0
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- qr 1.3.0 [meta]
- quiver 2.1.5 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.8 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.7.0 [charcode collection meta path term_glyph]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.9.6 [path]
- stream_channel 2.0.0 [async]
- stream_transform 1.2.0
- string_scanner 1.0.5 [charcode meta source_span]
- synchronized 2.2.0+2
- term_glyph 1.1.0
- timeago 2.0.28
- timing 0.1.1+2 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- unicode 0.2.4 [lists]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- usage 3.4.2 [path]
- vector_math 2.1.0-nullsafety.3
- vin_decoder 0.1.2 [meta basic_utils http random_string]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by dgilperez** [comment]
I am just seeing the same error, with same lack of context and with a very uncommunicative Crashlytics log. 

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(firebase_firestore, length=11; index=11, {})
StandardMethodCodec.decodeEnvelope (message_codecs.dart:572)
MethodChannel._invokeMethod (platform_channel.dart:161)
MethodChannelDocumentReference.<fn> (method_channel_document_reference.dart:94)
.suspension> (<asynchronous)
```

**Comment by hyungtaecf** [comment]
Same here.

E/flutter (24950): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(firebase_core, java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: length=11; index=11, null, null)
E/flutter (24950): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:582
E/flutter (24950): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:159
E/flutter (24950): <asynchronous suspension>
E/flutter (24950): #2      MethodChannel.invokeMethod
package:flutter/…/services/platform_channel.dart:332
E/flutter (24950): #3      MethodChannel.invokeListMethod
package:flutter/…/services/platform_channel.dart:345
E/flutter (24950): #4      MethodChannelFirebase._initializeCore
package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart:30
E/flutter (24950): #5      MethodChannelFirebase.initializeApp
package:firebase_core_platform_interface/…/method_channel/method_channel_firebase.dart:75
E/flutter (24950): #6      Firebase.initializeApp

**Comment by oodavid** [comment]
We've seen the same error a few times with `firebase_storage: ^5.0.1` on `ios`.

**Comment by israellias** [comment]
me too with one only user... 375 events on Android 10
<img width="786" alt="image" src="https://user-images.githubusercontent.com/16140960/106334883-fc596980-6261-11eb-9995-f915eac9c3ae.png">

**Comment by utkarshpateriya** [comment]
I'm having the same issue. Although when I build and run a release version, it acts normally. But, in the debug mode I get this error unlimited times and after a while, it shows Platform exception. 
![image](https://user-images.githubusercontent.com/48222091/108965923-8818b700-76a3-11eb-9bd5-35fc7eee2ede.png)

**Comment by russellwheatley** [comment]
Hey @larssn,  we updated the way we handle [snapshot event listeners](https://github.com/FirebaseExtended/flutterfire/pull/4209) back in January which may have fixed your problem. Can you confirm if you're still seeing the same issue crop up?

**Comment by larssn** [comment]
I think it did! Can't find it in our error logging service anymore.
