### ISSUE TITLE
🐛 [firebase_core] Task 'assembleAarRelease' not found in root project 'firebase_core' when running flutter build --release

### ISSUE THREAD

**Issue by gabeaventh** [FirebaseExtended/flutterfire#3866]
## Bug report

**Describe the bug**
i tried to build my signed release apk, and it gave me this error:

`Task 'assembleAarRelease' not found in root project 'firebase_core'`

tried --debug, it able to build my apk, but --release cannot

### Steps to reproduce

1. flutter clean && flutter build apk --release -v
2. BUILD Failed: Task 'assembleAarRelease' not found in root project 'firebase_core'

### Expected behavior

should be able to build my release apk

---

## Additional context

ive tried this suggestion from flutter issues [suggestion](https://github.com/flutter/flutter/issues/43704#issuecomment-669792020)
it return the same thing with additional error 
`BUILD FAILED: Task 'assembleAarRelease' not found in root project 'firebase_core'. Some candidates are: 'assembleRelease'.`

tried to build on master channel, return with the same results

my flutter build apk --release -v logs where the error happened, incase needed:
<details><summary>Click To Expand</summary>

[  +98 ms] > Task :path_provider:syncReleaseLibJars
[        ] > Task :path_provider:bundleReleaseAar
[        ] > Task :permission_handler:copyReleaseJniLibsProjectAndLocalJars
[ +199 ms] > Task :path_provider:mergeReleaseResources
[+2900 ms] > Task :permission_handler:extractReleaseAnnotations
[        ] > Task :permission_handler:mergeReleaseConsumerProguardFiles UP-TO-DATE
[        ] > Task :permission_handler:prepareLintJarForPublish UP-TO-DATE
[        ] > Task :package_info:verifyReleaseResources FAILED
[ +100 ms] > Task :path_provider:verifyReleaseResources
[        ] > Task :permission_handler:mergeReleaseJavaResource
[  +99 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 587 actionable tasks: 509 executed, 78 up-to-date
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':package_info:verifyReleaseResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > 1 exception was raised by workers:
[        ]      com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
[        ]      /Users/lpt533/.gradle/caches/transforms-2/files-2.1/8a68b0f85eb9dea9501039cf6183777d/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource
android:attr/fontVariationSettings not found.
[        ]      /Users/lpt533/.gradle/caches/transforms-2/files-2.1/8a68b0f85eb9dea9501039cf6183777d/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource
android:attr/ttcIndex not found.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 2m 37s
[ +495 ms] Running Gradle task 'assembleRelease'... (completed in 158.1s)
[   +4 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[   +5 ms] Building plugin contacts_service...
[   +5 ms] Running Gradle task 'assembleAarRelease'...
[        ] gradle.properties already sets `android.enableR8`
[   +2 ms] Using gradle from /Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.4.6/android/gradlew.
[        ] /Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.4.6/android/gradlew mode: 33261 rwxr-xr-x.
[   +2 ms] executing: [/Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.4.6/android/]
/Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/contacts_service-0.4.6/android/gradlew -I=/Users/lpt533/dev/flutter/packages/flutter_tools/gradle/aar_init_script.gradle
-Pflutter-root=/Users/lpt533/dev/flutter -Poutput-dir=/Users/lpt533/dev/workspace/cashfazz-app/build/app -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true -Pfont-subset=true
-Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+2027 ms] > Task :assembleAarRelease UP-TO-DATE
                    > Task :preBuild UP-TO-DATE
                    > Task :preReleaseBuild UP-TO-DATE
                    > Task :compileReleaseAidl NO-SOURCE
                    > Task :compileReleaseRenderscript UP-TO-DATE
                    > Task :checkReleaseManifest UP-TO-DATE
                    > Task :generateReleaseBuildConfig UP-TO-DATE
                    > Task :generateReleaseResValues UP-TO-DATE
                    > Task :generateReleaseResources UP-TO-DATE
                    > Task :packageReleaseResources UP-TO-DATE
                    > Task :processReleaseManifest UP-TO-DATE
                    > Task :generateReleaseRFile UP-TO-DATE
                    > Task :prepareLintJar UP-TO-DATE
                    > Task :generateReleaseSources UP-TO-DATE
                    > Task :javaPreCompileRelease UP-TO-DATE
                    > Task :compileReleaseJavaWithJavac UP-TO-DATE
                    > Task :extractReleaseAnnotations UP-TO-DATE
                    > Task :mergeReleaseConsumerProguardFiles UP-TO-DATE
                    > Task :mergeReleaseShaders UP-TO-DATE
                    > Task :compileReleaseShaders UP-TO-DATE
                    > Task :generateReleaseAssets UP-TO-DATE
                    > Task :packageReleaseAssets UP-TO-DATE
                    > Task :packageReleaseRenderscript NO-SOURCE
                    > Task :processReleaseJavaRes NO-SOURCE
                    > Task :transformResourcesWithMergeJavaResForRelease UP-TO-DATE
                    > Task :transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
                    > Task :compileReleaseNdk NO-SOURCE
                    > Task :mergeReleaseJniLibFolders UP-TO-DATE
                    > Task :transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
                    > Task :transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
                    > Task :bundleReleaseAar UP-TO-DATE
                    > Task :uploadArchives

                    BUILD SUCCESSFUL in 1s
                    22 actionable tasks: 1 executed, 21 up-to-date
[        ] Running Gradle task 'assembleAarRelease'... (completed in 2,033ms)
[   +6 ms] ✓ Built build/app/outputs/repo.
[        ] Building plugin device_info...
[   +2 ms] Running Gradle task 'assembleAarRelease'...
[        ] gradle.properties already sets `android.enableR8`
[   +2 ms] Using gradle from /Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.2+8/android/gradlew.
[        ] /Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.2+8/android/gradlew mode: 33261 rwxr-xr-x.
[        ] executing: [/Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.2+8/android/]
/Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.2+8/android/gradlew -I=/Users/lpt533/dev/flutter/packages/flutter_tools/gradle/aar_init_script.gradle
-Pflutter-root=/Users/lpt533/dev/flutter -Poutput-dir=/Users/lpt533/dev/workspace/cashfazz-app/build/app -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true -Pfont-subset=true
-Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+2019 ms]
                    > Configure project :
                    WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
                    It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.

                    > Task :assembleAarRelease UP-TO-DATE
                    > Task :preBuild UP-TO-DATE
                    > Task :preReleaseBuild UP-TO-DATE
                    > Task :compileReleaseAidl NO-SOURCE
                    > Task :mergeReleaseJniLibFolders UP-TO-DATE
                    > Task :mergeReleaseNativeLibs UP-TO-DATE
                    > Task :stripReleaseDebugSymbols UP-TO-DATE
                    > Task :copyReleaseJniLibsProjectAndLocalJars UP-TO-DATE
                    > Task :compileReleaseRenderscript NO-SOURCE
                    > Task :generateReleaseBuildConfig UP-TO-DATE
                    > Task :generateReleaseResValues UP-TO-DATE
                    > Task :generateReleaseResources UP-TO-DATE
                    > Task :packageReleaseResources UP-TO-DATE
                    > Task :parseReleaseLocalResources UP-TO-DATE
                    > Task :processReleaseManifest UP-TO-DATE
                    > Task :generateReleaseRFile UP-TO-DATE
                    > Task :javaPreCompileRelease UP-TO-DATE
                    > Task :compileReleaseJavaWithJavac UP-TO-DATE
                    > Task :extractReleaseAnnotations UP-TO-DATE
                    > Task :mergeReleaseGeneratedProguardFiles UP-TO-DATE
                    > Task :mergeReleaseConsumerProguardFiles UP-TO-DATE
                    > Task :mergeReleaseShaders UP-TO-DATE
                    > Task :compileReleaseShaders UP-TO-DATE
                    > Task :generateReleaseAssets UP-TO-DATE
                    > Task :packageReleaseAssets UP-TO-DATE
                    > Task :packageReleaseRenderscript NO-SOURCE
                    > Task :prepareLintJarForPublish UP-TO-DATE
                    > Task :processReleaseJavaRes NO-SOURCE
                    > Task :mergeReleaseJavaResource UP-TO-DATE
                    > Task :syncReleaseLibJars UP-TO-DATE
                    > Task :bundleReleaseAar UP-TO-DATE
                    > Task :uploadArchives

                    BUILD SUCCESSFUL in 1s
                    23 actionable tasks: 1 executed, 22 up-to-date
[   +2 ms] Running Gradle task 'assembleAarRelease'... (completed in 2,026ms)
[   +1 ms] ✓ Built build/app/outputs/repo.
[        ] Building plugin firebase_core...
[   +8 ms] Running Gradle task 'assembleAarRelease'...
[        ] gradle.properties already sets `android.enableR8`
[   +1 ms] Using gradle from /Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0+1/android/gradlew.
[        ] /Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0+1/android/gradlew mode: 33261 rwxr-xr-x.
[        ] executing: [/Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0+1/android/]
/Users/lpt533/dev/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.5.0+1/android/gradlew -I=/Users/lpt533/dev/flutter/packages/flutter_tools/gradle/aar_init_script.gradle
-Pflutter-root=/Users/lpt533/dev/flutter -Poutput-dir=/Users/lpt533/dev/workspace/cashfazz-app/build/app -Pis-plugin=true -PbuildNumber=1.0 -Pverbose=true -Pfont-subset=true
-Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+1223 ms] Configuration on demand is an incubating feature.

                    > Configure project :
                    WARNING: The option setting 'android.enableR8=true' is deprecated.
                    It will be removed in version 5.0 of the Android Gradle plugin.
                    You will no longer be able to disable R8

                    FAILURE: Build failed with an exception.

                    * What went wrong:
                    Task 'assembleAarRelease' not found in root project 'firebase_core'. Some candidates are: 'assembleRelease'.

                    * Try:
                    Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run
                    with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 1s
[        ] Running Gradle task 'assembleAarRelease'... (completed in 1,226ms)
[        ] Configuration on demand is an incubating feature.

           > Configure project :
           WARNING: The option setting 'android.enableR8=true' is deprecated.
           It will be removed in version 5.0 of the Android Gradle plugin.
           You will no longer be able to disable R8

[        ]
           FAILURE: Build failed with an exception.

           * What went wrong:
           Task 'assembleAarRelease' not found in root project 'firebase_core'. Some candidates are: 'assembleRelease'.

           * Try:
           Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 1s

[   +4 ms] "flutter apk" took 166,489ms.
[   +5 ms] The plugin firebase_core could not be built due to the issue above.
[        ]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:842:7)
           #2      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:91:64)
           #3      _rootRunBinary (dart:async/zone.dart:1214:47)
           #4      _CustomZone.runBinary (dart:async/zone.dart:1107:19)
           #5      _FutureListener.handleError (dart:async/future_impl.dart:157:20)
           #6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
           #7      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
           #8      Future._completeError (dart:async/future_impl.dart:537:5)
           #9      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
           #10     buildGradleAar (package:flutter_tools/src/android/gradle.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #19     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
           #20     _rootRunUnary (dart:async/zone.dart:1198:47)
           #21     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #22     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #24     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #25     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #28     _run (package:flutter_tools/src/base/error_handling_io.dart)
           #29     _rootRunUnary (dart:async/zone.dart:1198:47)
           #30     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #31     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #33     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #34     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #35     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
           #36     _rootRunUnary (dart:async/zone.dart:1198:47)
           #37     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #38     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #40     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #41     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #42     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #43     _rootRun (dart:async/zone.dart:1190:13)
           #44     _CustomZone.run (dart:async/zone.dart:1093:19)
           #45     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[ +175 ms] ensureAnalyticsSent: 172ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.23.0-19.0.pre.48, on Mac OS X 10.15.6 19G73 darwin-x64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.49.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
╰─ flutter pub deps -- --style=compact
Dart SDK 2.11.0-218.0.dev
Flutter SDK 1.23.0-19.0.pre.48
cashfazz 1.0.0+10000

dependencies:
- auto_size_text 0.2.2 [flutter]
- autocomplete_textfield 1.7.3 [flutter]
- cached_network_image 2.3.2+1 [flutter flutter_cache_manager octo_image]
- camera 0.5.7+3 [flutter]
- contacts_service 0.4.6 [flutter collection quiver]
- crypto 2.1.5 [collection convert typed_data]
- cupertino_icons 0.1.3
- dartz 0.9.2
- device_info 0.4.2+8 [flutter device_info_platform_interface]
- dio 3.0.10 [http_parser path]
- encrypt 0.2.0+2 [pointycastle]
- equatable 1.2.5 [collection meta]
- firebase_core 0.5.0+1 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.1+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.0.6 [flutter bloc provider]
- flutter_ditto 1.0.0+1 [flutter cupertino_icons]
- flutter_markdown 0.3.5 [flutter markdown meta path]
- flutter_redux 0.5.4 [meta redux flutter]
- flutter_svg 0.19.0 [path_drawing xml vector_math meta flutter]
- flutter_webview_plugin 0.3.11 [flutter]
- flutter_widget_from_html 0.5.1+2 [cached_network_image chewie flutter flutter_layout_grid flutter_svg flutter_widget_from_html_core html url_launcher video_player webview_flutter]
- fluttertoast 7.1.1 [flutter flutter_web_plugins]
- graphql 3.1.0 [meta http mime path crypto http_parser uuid_enhanced gql rxdart websocket quiver]
- html2md 0.5.1 [path html]
- image_picker 0.6.7+11 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.16.1 [path]
- kiwi 0.1.0
- launch_review 2.0.0 [flutter]
- logging 0.11.4
- package_info 0.3.2+1 [flutter]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- qr_flutter 3.2.0 [flutter qr]
- qr_mobile_vision 1.0.2 [flutter native_device_orientation]
- redux 3.0.0
- redux_thunk 0.2.1 [redux]
- rxdart 0.24.1
- sensors 0.4.2+5 [flutter]
- shared_preferences 0.5.12 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- solid_bottom_sheet 0.1.9 [flutter]
- sqflite 1.3.1+1 [flutter sqflite_common path]
- url_launcher 5.7.2 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]

dev dependencies:
- flutter_driver 0.0.0 [file json_rpc_2 meta path web_socket_channel vm_service_client webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async matcher platform process pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- mockito 4.1.2 [analyzer build code_builder collection dart_style matcher meta source_gen test_api]
- test 1.16.0-nullsafety.5 [analyzer async boolean_selector coverage http http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _fe_analyzer_shared 7.0.0 [meta]
- analyzer 0.39.17 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- bloc 6.0.3 [meta]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.5.0 [analyzer async convert crypto logging meta path glob]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- chewie 0.9.10 [open_iconic_flutter video_player wakelock flutter]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- coverage 0.14.1 [args logging package_config path source_maps stack_trace vm_service]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 6.0.0-nullsafety.2 [meta path]
- firebase 7.3.1 [http http_parser js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.1 [flutter meta collection firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 1.4.2 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_layout_grid 0.10.2 [collection flutter meta quiver]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- flutter_widget_from_html_core 0.5.1+2 [flutter html]
- fuchsia_remote_debug_protocol 0.0.0 [json_rpc_2 process web_socket_channel flutter_test flutter_driver archive args async boolean_selector charcode clock collection convert crypto fake_async file matcher meta path platform pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math vm_service_client webdriver]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- gql 0.12.3 [source_span meta collection]
- html 0.14.0+4 [csslib source_span]
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3-nullsafety.1
- json_rpc_2 2.2.2 [stack_trace stream_channel]
- markdown 2.1.8 [args charcode meta]
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.4
- mime 0.9.7
- native_device_orientation 0.3.0 [flutter]
- nested 0.0.4 [flutter]
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- node_preamble 1.4.12
- octo_image 0.3.0 [flutter flutter_blurhash]
- open_iconic_flutter 0.3.0 [flutter]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.18 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.10.0-nullsafety.1
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 3.0.0-nullsafety.2
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 1.0.2
- pool 1.5.0-nullsafety.1 [async stack_trace]
- process 4.0.0-nullsafety.2 [file path platform]
- provider 4.3.2+2 [flutter nested collection]
- pub_semver 1.4.4 [collection]
- qr 1.3.0 [meta]
- quiver 2.1.3 [matcher meta]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.0 [path shelf shelf_static]
- shelf_static 0.2.8 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.1.0-nullsafety.2 [path stack_trace source_maps]
- source_maps 0.10.10-nullsafety.1 [source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.2 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- sync_http 0.2.0
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.12-nullsafety.5 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.4+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- uuid 2.2.2 [crypto convert]
- uuid_enhanced 3.0.2 [crypto convert collection]
- vector_math 2.1.0-nullsafety.3
- video_player 0.10.12+5 [meta video_player_platform_interface video_player_web flutter]
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- vm_service 5.2.0 [meta]
- vm_service_client 0.2.6+2 [async collection json_rpc_2 pub_semver source_span stack_trace stream_channel web_socket_channel]
- wakelock 0.1.4+2 [flutter]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 0.7.3 [logging]
- websocket 0.0.5
- webview_flutter 1.0.1 [flutter]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by gabeaventh** [comment]
Problem Solved

as shown on logs
```
[ ] Execution failed for task ':package_info:verifyReleaseResources'.
[ ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[ ] > 1 exception was raised by workers:
[ ] com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
[ ] /Users/lpt533/.gradle/caches/transforms-2/files-2.1/8a68b0f85eb9dea9501039cf6183777d/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource
android:attr/fontVariationSettings not found.
[ ] /Users/lpt533/.gradle/caches/transforms-2/files-2.1/8a68b0f85eb9dea9501039cf6183777d/core-1.1.0/res/values/values.xml:142:5-173:25: AAPT: error: resource
android:attr/ttcIndex not found.
```

The culprit is package_info, still using the outdated package
upgrading the package to the newer version solved the issue

my mistake was not reading all the logs thoroughly
was focused on the last error
