### ISSUE TITLE
[firebase_auth_web] _FirebaseErrorWrapper thrown instead of FirebaseAuthException

### ISSUE THREAD

**Issue by peerwaya** [FirebaseExtended/flutterfire#3877]
## Flutter for Web,  auth.verifyPasswordResetCode,  auth does not throw FirebaseAuthException instead throws _FirebaseErrorWrapper

calling FirebaseAuth.instance.verifyPasswordResetCode(invalidActionCode)  does not throw FirebaseAuthException when an invalid action code is provided instead _FirebaseErrorWrapper is thrown. I suspect this is as a result of not awaiting the result of `_webAuth.verifyPasswordResetCode(code)`. Theses applies to the following methods too:
```
FirebaseAuth.instance.applyActionCode(String code)
FirebaseAuth.instance.fetchSignInMethodsForEmail(String email)
FirebaseAuth.instance.setPersistence(Persistence persistence)
```

```
  firebase_core: "^0.5.0+1"
  firebase_auth: ^0.18.1+2

  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js"></script>
```

**Comment by TahaTesser** [comment]
I can reproduce it on the web, exception isn't caught when you put in a  try-catch 
```daer
          try {
            await FirebaseAuth.instance.verifyPasswordResetCode('12drfhsd');
          } on FirebaseAuthException catch (e) {
            print('Failed with error code: ${e.code}');
            print(e.message);
          }
```

<details> 
<summary>complete code sample</summary> 

```dart
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () async {
          try {
            await FirebaseAuth.instance.verifyPasswordResetCode('12drfhsd');
          } on FirebaseAuthException catch (e) {
            print('Failed with error code: ${e.code}');
            print(e.message);
          }
        },
      ),
    );
  }
}

```

</details> 

Web
```bash
[38;5;248mLaunching lib/main.dart on Chrome in debug mode...[39;49m
 lib/main.dart
Debug service listening on ws://127.0.0.1:53577/NdeaBKlECmY=
Connecting to VM Service at ws://127.0.0.1:53577/NdeaBKlECmY=
Error: FirebaseError: The action code is invalid. This can happen if the code is malformed, expired, or has already been used. (auth/invalid-action-code)
    at Object.throw_ [as throw] (http://localhost:53543/dart_sdk.js:4344:11)
    at handleThenable (http://localhost:53543/packages/firebase/src/storage.dart.lib.js:3264:21)
    at handleThenable.throw (<anonymous>)
    at http://localhost:53543/dart_sdk.js:37690:38
    at _RootZone.runBinary (http://localhost:53543/dart_sdk.js:37543:58)
    at _FutureListener.thenAwait.handleError (http://localhost:53543/dart_sdk.js:32524:48)
    at handleError (http://localhost:53543/dart_sdk.js:33075:51)
    at Function._propagateToListeners (http://localhost:53543/dart_sdk.js:33101:17)
    at _Future.new.[_completeError] (http://localhost:53543/dart_sdk.js:32948:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53543/dart_sdk.js:32986:31)
    at Object._microtaskLoop (http://localhost:53543/dart_sdk.js:37799:13)
    at _startMicrotaskLoop (http://localhost:53543/dart_sdk.js:37805:13)
    at http://localhost:53543/dart_sdk.js:33314:9
```

Mobile 

```bash
I/flutter (14210): Failed with error code: invalid-action-code
I/flutter (14210): The out of band code is invalid. This can happen if the code is malformed, expired, or has already been used.

```

**Comment by russellwheatley** [comment]
Hey @peerwaya, is this still an issue for you? auth package is now on the next major version.
