### ISSUE TITLE
🐛 [firebase_storage 4.0.1] Can't upload image to firebase in flutter web version, is this possible today? Everything is fine on Android

### ISSUE THREAD

**Issue by Fitz1991** [FirebaseExtended/flutterfire#3882]
## Bug report

**Describe the bug**
```
Overflow on channel: plugins.flutter.io/firebase_storage.  Messages on this channel are being discarded in FIFO fashion.  The engine may not be running or you need to adjust the buffer size if of the channel.
Error: MissingPluginException(No implementation found for method StorageReference#putData on channel plugins.flutter.io/firebase_storage)
    at Object.throw_ [as throw] (http://localhost:55439/dart_sdk.js:4328:11)
    at MethodChannel._invokeMethod (http://localhost:55439/packages/flutter/src/services/system_channels.dart.lib.js:942:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:55439/dart_sdk.js:37593:33
    at _RootZone.runUnary (http://localhost:55439/dart_sdk.js:37447:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:55439/dart_sdk.js:32424:29)
    at handleValueCallback (http://localhost:55439/dart_sdk.js:32971:49)
    at Function._propagateToListeners (http://localhost:55439/dart_sdk.js:33009:17)
    at _Future.new.[_completeWithValue] (http://localhost:55439/dart_sdk.js:32852:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55439/dart_sdk.js:32874:35)
    at Object._microtaskLoop (http://localhost:55439/dart_sdk.js:37708:13)
    at _startMicrotaskLoop (http://localhost:55439/dart_sdk.js:37714:13)
    at http://localhost:55439/dart_sdk.js:33226:9
```

### Steps to reproduce
mydependencies:
```
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.1+2
  firebase_core: ^0.5.0+1
  cloud_functions: 0.7.0-dev.2
  firebase_storage: ^4.0.1
  firebase_auth: ^0.18.1+1
```
index.html:
```
<script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-functions.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-storage.js"></script>
```
my code:
```
class WebImagePicker implements ImagePickerUniversal {
  Future<Map<String, dynamic>> pickImage() async {
    Map<String, dynamic> data = {};
    final html.FileUploadInputElement input = html.FileUploadInputElement();
    input..accept = 'image/*';
    input.click();
    await input.onChange.first;
    if (input.files.isEmpty) return null;
    final reader = html.FileReader();
    reader.readAsArrayBuffer(input.files[0]);
    await reader.onLoad.first;
    final encoded = reader.result as Uint8List;
    final imageName = input.files?.first?.name;

    data.addAll({'name': imageName, 'file': encoded, 'museumDir': 'Иванов'});
    StorageRefere

**Comment by Tihan-Nico** [comment]
Firebase Storage currently doesn't support Web functionality. I'd advise you to use Firebase Dart plugin for web. It has all the functionality you need.

**Comment by TahaTesser** [comment]
Hi @Fitz1991 
As stated above, there is no web yet in `firebase_storage` package
https://github.com/FirebaseExtended/flutterfire/issues/1972
Closing as duplicate
Thank you
