### ISSUE TITLE
🐛 [firebase_admob] banner ad is shown when dispose already happened

### ISSUE THREAD

**Issue by WouterVandenputte** [FirebaseExtended/flutterfire#3900]
## Bug report

**Describe the bug**
Suppose we make two pages, one with only a button (so without banner) and one with only a banner at the bottom.
The button navigates to the page with the banner, where a banner ad is shown.
The bug now is that if you go to the banner page and immediately return before the ad is loaded and shown, the banner is shown on the page with the button, this banner then in turn could be displayed over navigation items et cetera.

### Steps to reproduce

1. Add the firebase_admob dependency
2. Implement the given code below and run it
4. Click on the button on the main page
5. Immediately go back, try this several times if it does not appear the first time
![image](https://user-images.githubusercontent.com/23052815/96367880-b7954100-1150-11eb-830b-dec08abc69f0.png)

### Expected behavior

The banner ad should not be shown over the first page

---

## Additional context

Android tested only
Unknown for iOS
Using Android Studio 
Latest Flutter SDK as of 18 October 2020
Latest firebase_admob plugin as of 18 October 2020
Added the app id metadata in androidManifest.xml

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18362.1139], locale nl-BE)
    • Flutter version 1.22.2 at D:\flutter
    • Framework revision 84f3d28555 (3 days ago), 2020-10-15 16:26:19 -0700
    • Engine revision b8752bbfff
    • Dart version 2.10.2

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\woute\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[!] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

```

</details>
Note: the Dart and Flutter plugin are in fact installed, no idea why the doctor says otherwise.

Note: trying to accept the android licenses yields in an error

<details><summary>Click To Expand</summary>

```

C:\Users\woute>flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more

```

</details>
Either way, building works without a problem and the bug is not correlated. 

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
D:\repositories\admob_bug>flutter pub deps
Dart SDK 2.10.2
Flutter SDK 1.22.2
admob_bug 1.0.0+1
|-- cupertino_icons 1.0.0
|-- firebase_admob 0.10.0+2
|   |-- firebase_core 0.5.0+1
|   |   |-- firebase_core_platform_interface 2.0.0
|   |   |   |-- flutter...
|   |   |   |-- meta...
|   |   |   |-- plugin_platform_interface 1.0.3
|   |   |   |   '-- meta...
|   |   |   '-- quiver...
|   |   |-- firebase_core_web 0.2.0
|   |   |   |-- firebase 7.3.2
|   |   |   |   |-- http 0.12.2
|   |   |   |   |   |-- http_parser...
|   |   |   |   |   |-- path...
|   |   |   |   |   '-- pedantic 1.9.2
|   |   |   |   |       '-- meta...
|   |   |   |   |-- http_parser 3.1.4
|   |   |   |   |   |-- charcode...
|   |   |   |   |   |-- collection...
|   |   |   |   |   |-- source_span...
|   |   |   |   |   |-- string_scanner...
|   |   |   |   |   '-- typed_data...
|   |   |   |   '-- js...
|   |   |   |-- firebase_core_platform_interface...
|   |   |   |-- flutter...
|   |   |   |-- flutter_web_plugins 0.0.0
|   |   |   |   |-- characters...
|   |   |   |   |-- collection...
|   |   |   |   |-- flutter...
|   |   |   |   |-- meta...
|   |   |   |   |-- typed_data...
|   |   |   |   '-- vector_math...
|   |   |   |-- js 0.6.2
|   |   |   '-- meta...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- quiver 2.1.3
|   |       |-- matcher...
|   |       '-- meta...
|   |-- flutter...
|   '-- meta...
|-- flutter 0.0.0
|   |-- characters 1.1.0-nullsafety.3
|   |-- collection 1.15.0-nullsafety.3
|   |-- meta 1.3.0-nullsafety.3
|   |-- sky_engine 0.0.99
|   |-- typed_data 1.3.0-nullsafety.3
|   |   '-- collection...
|   '-- vector_math 2.1.0-nullsafety.3
'-- flutter_test 0.0.0
    |-- async 2.5.0-nullsafety.1
    |   '-- collection...
    |-- boolean_selector 2.1.0-nullsafety.1
    |   |-- source_span...
    |   '-- string_scanner...
    |-- characters...
    |-- charcode 1.2.0-nullsafety.1
    |-- clock 1.1.0-nullsafety.1
    |-- collection...
    |-- fake_async 1.2.0-nullsafety.1
    |   |-- clock...
    |   '-- collection...
    |-- flutter...
    |-- matcher 0.12.10-nullsafety.1
    |   '-- stack_trace...
    |-- meta...
    |-- path 1.8.0-nullsafety.1
    |-- source_span 1.8.0-nullsafety.2
    |   |-- charcode...
    |   |-- collection...
    |   |-- path...
    |   '-- term_glyph...
    |-- stack_trace 1.10.0-nullsafety.1
    |   '-- path...
    |-- stream_channel 2.1.0-nullsafety.1
    |   '-- async...
    |-- string_scanner 1.1.0-nullsafety.1
    |   |-- charcode...
    |   '-- source_span...
    |-- term_glyph 1.2.0-nullsafety.1
    |-- test_api 0.2.19-nullsafety.2
    |   |-- async...
    |   |-- boolean_selector...
    |   |-- collection...
    |   |-- matcher...
    |   |-- meta...
    |   |-- path...
    |   |-- source_span...
    |   |-- stack_trace...
    |   |-- stream_channel...
    |   |-- string_scanner...
    |   '-- term_glyph...
    |-- typed_data...
    '-- vector_math...
```

</details>

---

**Comment by WouterVandenputte** [comment]
Forgot to add the code to reproduce

```

import 'package:firebase_admob/firebase_admob.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Admob Bug',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Page without a banner'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(title),
      ),
      body: Center(
        child: RaisedButton.icon(
          onPressed: () {
            Navigator.push(
                context, MaterialPageRoute(builder: (context) => BannerPage()));
          },
          icon: Icon(Icons.play_arrow),
          label: Text("Go to a new page with a  banner"),
        ),
      ),
    );
  }
}

class BannerPage extends StatefulWidget {

  BannerPage(){
    FirebaseAdMob.instance.initialize(appId: 'ca-app-pub-3940256099942544~3347511713');
  }

  @override
  State<StatefulWidget> createState() => _BannerPageState();
}

class _BannerPageState extends State<BannerPage> {
  BannerAd _bannerAd;
  static MobileAdTargetingInfo targetingInfo = MobileAdTargetingInfo(
    keywords: <String>['fun', 'game', 'friends', 'family'],
    contentUrl: 'https://flutter.io',
    childDirected: false,
    testDevices: <String>[], // Android emulators are considered test devices
  );

  @override
  void initState() {
    super.initState();
    _bannerAd = BannerAd(
      adUnitId: 'ca-app-pub-3940256099942544/6300978111',
      size: AdSize.smartBanner,
      targetingInfo: targetingInfo,
      listener: (MobileAdEvent event) {
        print("BannerAd event is $event");
      },
    )
      ..load()
      ..show(
        anchorOffset: 10.0,
        anchorType: AnchorType.bottom,
      );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Page with a banner"),
      ),
    );
  }

  @override
  void dispose(){
    _bannerAd?.dispose();
    super.dispose();
  }
}
```

**Comment by danieeelfc** [comment]
I've discovered it the hard way.

After calling dispose you must set _bannerAd to null for it to disappear.

```
  @override
  void dispose(){
    _bannerAd?.dispose();
    _bannerAd = null;
    super.dispose();
  }
```

**Comment by markusaksli-nc** [comment]
This is reproducible with master `1.24.0-2.0.pre.98` and `firebase_admob: ^0.10.0+2` but I'm not sure if this is the intended behavior or not.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-2.0.pre.98, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.24.0-2.0.pre.98 at C:\Development\flutter_master
    • Framework revision a4ac7cce82 (4 hours ago), 2020-10-21 00:46:59 -0400
    • Engine revision c2c74ed708
    • Dart version 2.11.0 (build 2.11.0-240.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.4818.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 86.0.622.38

• No issues found!
```
</details>
<details>
 <summary>Official example</summary>

```dart
import 'package:flutter/material.dart';
import 'package:firebase_admob/firebase_admob.dart';

const String testDevice = 'YOUR_DEVICE_ID';

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  static const MobileAdTargetingInfo targetingInfo = MobileAdTargetingInfo(
    testDevices: testDevice != null ? <String>[testDevice] : null,
    keywords: <String>['foo', 'bar'],
    contentUrl: 'http://foo.com/bar.html',
    childDirected: true,
    nonPersonalizedAds: true,
  );

  BannerAd _bannerAd;
  NativeAd _nativeAd;
  InterstitialAd _interstitialAd;

  BannerAd createBannerAd() {
    return BannerAd(
      adUnitId: BannerAd.testAdUnitId,
      size: AdSize.banner,
      targetingInfo: targetingInfo,
      listener: (MobileAdEvent event) {
        print("BannerAd event $event");
      },
    );
  }

  InterstitialAd createInterstitialAd() {
    return InterstitialAd(
      adUnitId: InterstitialAd.testAdUnitId,
      targetingInfo: targetingInfo,
      listener: (MobileAdEvent event) {
        print("InterstitialAd event $event");
      },
    );
  }

  NativeAd createNativeAd() {
    return NativeAd(
      adUnitId: NativeAd.testAdUnitId,
      factoryId: 'adFactoryExample',
      targetingInfo: targetingInfo,
      listener: (MobileAdEvent event) {
        print("$NativeAd event $event");
      },
    );
  }

  @override
  void initState() {
    super.initState();
    FirebaseAdMob.instance.initialize(appId: FirebaseAdMob.testAppId);
    _bannerAd = createBannerAd()..load();
  }

  @override
  void dispose() {
    _bannerAd?.dispose();
    _nativeAd?.dispose();
    _interstitialAd?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('AdMob Plugin example app'),
        ),
        body: SingleChildScrollView(
          child: Center(
            child: Builder(
              builder: (localContext) => Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  RaisedButton(
                    child: const Text("Push new page"),
                    onPressed: () {
                      Navigator.push(
                        localContext,
                        MaterialPageRoute(
                          builder: (context) => Container(
                            child: Center(
                              child: RaisedButton(
                                child: Text("Go back"),
                                onPressed: () {
                                  Navigator.of(context).pop();
                                },
                              ),
                            ),
                          ),
                        ),
                      );
                    },
                  ),
                  RaisedButton(
                      child: const Text('SHOW BANNER'),
                      onPressed: () {
                        _bannerAd ??= createBannerAd();
                        _bannerAd
                          ..load()
                          ..show();
                      }),
                  RaisedButton(
                      child: const Text('SHOW BANNER WITH OFFSET'),
                      onPressed: () {
                        _bannerAd ??= createBannerAd();
                        _bannerAd
                          ..load()
                          ..show(horizontalCenterOffset: -50, anchorOffset: 100);
                      }),
                  RaisedButton(
                      child: const Text('REMOVE BANNER'),
                      onPressed: () {
                        _bannerAd?.dispose();
                        _bannerAd = null;
                      }),
                ].map((Widget button) {
                  return Padding(
                    padding: const EdgeInsets.symmetric(vertical: 16.0),
                    child: button,
                  );
                }).toList(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

void main() {
  runApp(MyApp());
}
```
</details>

**Comment by ReveredMachine** [comment]
I faced the same issue, but my intention was to display a banner on the first page and on the second page a banner with another size.
When returning from the second page immediately to the first page, before the banner of second page was displayed it resulted in seeing two banners on the first page.
It seems to be working when taking the MobileAdEvent.loaded into account.

**Comment by HiIamAlanOu** [comment]
I faced the same issue.
It will happen when calling the dispose function before the showing function complete.

**Comment by ReveredMachine** [comment]
I had a short look into the code, but unfortunately not the time to create a pull request.

My idea is the following:

A hide() method on the flutter and native side like

Flutter (firebase_admob.dart)
```
  Future<bool> hide() {
    return _invokeBooleanMethod("hideAd", <String, dynamic>{
      'id': id,
    });
  }
```
Native(FirebaseAdMobPlugin.java)
```
	public void onMethodCall(MethodCall call, Result result) {
	  ...
      case "showAd":
        callShowAd(id, call, result);
        break;
      case "hideAd":
        callHideAd(id, call, result);
        break;
	  ...
	}
```

Native (MobileAd.java)
```
    void hide() {
      View contentView = activity.findViewById(id);
      if (contentView == null || !(contentView.getParent() instanceof ViewGroup)) return;
      contentView.setVisibility(View.INVISIBLE);
    }
```

And a small modification in the show() method on the Native side (MobileAd.java)
```
    void show() {
      View contentView = activity.findViewById(id);
      if (contentView == null) {
	    //remains unchanged
      } else {
        contentView.setVisibility(View.VISIBLE);
      }
    }
```

So one can keep the used banner objects on the flutter side as the reference to the native side and is then be able to quickly set the banner visible / invisible.

**Comment by alexandr-efimov** [comment]
any updates so far?

Changing of route and navigating back doesn't dispose, with:
`  @override
  void dispose() {
    _bannerAd?.dispose();
    _bannerAd = null;
    super.dispose();
  }`

**Comment by russellwheatley** [comment]
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.
