### ISSUE TITLE
🐛 [firebase_crashlytics] FirebaseCrashlytics: Settings request failed

### ISSUE THREAD

**Issue by CaiXiaoBai** [FirebaseExtended/flutterfire#3924]
I used firebase_crashlytics for Flutter project, but I received these errors when I ran the project.
```
E/FirebaseCrashlytics( 6223): Settings request failed.
E/FirebaseCrashlytics( 6223): java.io.InterruptedIOException: timeout
E/FirebaseCrashlytics( 6223): 	at okhttp3.RealCall.timeoutExit(RealCall.java:107)
E/FirebaseCrashlytics( 6223): 	at okhttp3.RealCall.execute(RealCall.java:96)
E/FirebaseCrashlytics( 6223): 	at com.google.firebase.crashlytics.internal.network.HttpRequest.execute(HttpRequest.java:129)
E/FirebaseCrashlytics( 6223): 	at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:86)
E/FirebaseCrashlytics( 6223): 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
E/FirebaseCrashlytics( 6223): 	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
E/FirebaseCrashlytics( 6223): 	at com.google.android.gms.tasks.zzp.run(Unknown Source:2)
E/FirebaseCrashlytics( 6223): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseCrashlytics( 6223): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseCrashlytics( 6223): 	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:60)
E/FirebaseCrashlytics( 6223): 	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
E/FirebaseCrashlytics( 6223): 	at java.lang.Thread.run(Thread.java:764)
E/FirebaseCrashlytics( 6223): Caused by: java.io.IOException: Canceled
E/FirebaseCrashlytics( 6223): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
E/FirebaseCrashlytics( 6223): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
E/FirebaseCrashlytics( 6223): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
E/FirebaseCrashlytics( 6223): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
E/FirebaseCrashlytics( 6223): 	at okhttp3.RealCall.execute(RealCall.java:92)
E/FirebaseCrashlytics( 6223): 	... 10 more
```
I have seen some information [here](https://status.firebase.google.com/incident/Crashlytics/20004), but the Incident began at 2020-07-10 04:43 and ended at 2020-07-13 09:08 (All Times are US/Pacific).

Here are some of my configurations:

android/build.gradle
```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
app/build.gradle
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}


def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.firebase.crashlytics'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile file(keystoreProperties['storeFile'])
           storePassword keystoreProperties['storePassword']
       }
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.keepupcoder.todo"
        minSdkVersion 16
        targetSdkVersion 28
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3'
    // Add the Firebase Crashlytics SDK.
    implementation 'com.google.firebase:firebase-crashlytics:17.2.1'

    // Recommended: Add the Google Analytics SDK.
    implementation 'com.google.firebase:firebase-analytics:17.5.0'
}
```
pubspec.yaml
```
dependencies:
  firebase_core: "0.5.0+1"
  firebase_crashlytics: "^0.2.1+1"
```
I have updated firebase_crashlytics to the latest version, and I have enabled crashlytics at firebase console.

**Comment by darshankawar** [comment]
@CaiXiaoBai 
There's similar open issue describing your case, [3669](https://github.com/FirebaseExtended/flutterfire/issues/3669).
Please follow-up there for updates and for any questions.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.
