### ISSUE TITLE
🐛 [cloud_firestore: ^0.14.1+3] Type Error

### ISSUE THREAD

**Issue by FunlabStudio** [FirebaseExtended/flutterfire#3965]
TypeError: dart.global.firebase.firestore is not a function
    at Object.firestore$ [as firestore] (http://localhost:64194/packages/firebase/src/top_level.dart.lib.js:94:55)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:64194/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:753:37)
    at Function.registerWith (http://localhost:64194/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:669:73)
    at Object.registerPlugins (http://localhost:64194/packages/talkme/generated_plugin_registrant.dart.lib.js:15:46)
    at main (http://localhost:64194/web_entrypoint.dart.lib.js:29:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:64194/dart_sdk.js:37687:34)
    at Object._async [as async] (http://localhost:64194/dart_sdk.js:37718:7)
    at main$ (http://localhost:64194/web_entrypoint.dart.lib.js:28:18)
    at http://localhost:64194/main_module.bootstrap.js:20:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:64194/main_module.bootstrap.js:19:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:64194/dwds/src/injected/client.js:8764:21)
    at http://localhost:64194/dwds/src/injected/client.js:22538:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:64194/dwds/src/injected/client.js:3793:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:64194/dwds/src/injected/client.js:11010:12)
    at Object._asyncStartSync (http://localhost:64194/dwds/src/injected/client.js:3757:20)
    at main__closure1.$call$body$main__closure (http://localhost:64194/dwds/src/injected/client.js:22550:16)
    at main__closure1.call$1 (http://localhost:64194/dwds/src/injected/client.js:22477:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:64194/dwds/src/injected/client.js:4124:16)
    at _CustomZone.runUnary$2$2 (http://localhost:64194/dwds/src/injected/client.js:12315:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:64194/dwds/src/injected/client.js:12247:14)
    at _ControllerSubscription._sendData$1 (http://localhost:64194/dwds/src/injected/client.js:11798:19)
    at _DelayedData.perform$1 (http://localhost:64194/dwds/src/injected/client.js:11950:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:64194/dwds/src/injected/client.js:11999:14)
    at Object._microtaskLoop (http://localhost:64194/dwds/src/injected/client.js:3960:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:64194/dwds/src/injected/client.js:3966:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:64194/dwds/src/injected/client.js:10879:9)
    at invokeClosure (http://localhost:64194/dwds/src/injected/client.js:1204:26)
    at MutationObserver.<anonymous> (http://localhost:64194/dwds/src/injected/client.js:1223:18)
Restarted application in 183ms.

**Comment by markusaksli-nc** [comment]
Hi @FunlabStudio 
This has been documented as mentioned in https://github.com/FirebaseExtended/flutterfire/issues/2682#issuecomment-655136736. Please see the official [documentation](https://firebase.flutter.dev/docs/firestore/overview#3-web-only-add-the-sdk) for how to fix this.
Closing this since it is documented.
Thank you
