### ISSUE TITLE
🐛 [firebase_messaging] v8.0.0-dev.2 java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal

### ISSUE THREAD

**Issue by LasseRosenow** [FirebaseExtended/flutterfire#3990]
## Bug report

Since firebase_messaging v8.0.0 I get this error:

```
W/ConnectionTracker(22164): Exception thrown while unbinding
W/ConnectionTracker(22164): java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzji@2f37ede
W/ConnectionTracker(22164): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1759)
W/ConnectionTracker(22164): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1786)
W/ConnectionTracker(22164): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:751)
W/ConnectionTracker(22164): 	at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55)
W/ConnectionTracker(22164): 	at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50)
W/ConnectionTracker(22164): 	at com.google.android.gms.measurement.internal.zzio.zzag(com.google.android.gms:play-services-measurement-impl@@17.6.0:245)
W/ConnectionTracker(22164): 	at com.google.android.gms.measurement.internal.zzio.zzal(com.google.android.gms:play-services-measurement-impl@@17.6.0:262)
W/ConnectionTracker(22164): 	at com.google.android.gms.measurement.internal.zzio.zzc(com.google.android.gms:play-services-measurement-impl@@17.6.0:336)
W/ConnectionTracker(22164): 	at com.google.android.gms.measurement.internal.zzir.zza(com.google.android.gms:play-services-measurement-impl@@17.6.0:2)
W/ConnectionTracker(22164): 	at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.6.0:7)
W/ConnectionTracker(22164): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(22164): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(22164): 	at com.google.android.gms.measurement.internal.zzfs.run(com.google.android.gms:play-services-measurement-impl@@17.6.0:21)
```

**Comment by markusaksli-nc** [comment]
This is caused by an upstream `P1` https://github.com/firebase/firebase-android-sdk/issues/1662 on the Android side.

Should probably leave this open to track it here until it is fixed.

**Comment by Artur110** [comment]
Please fix it :)

**Comment by jesusrb89** [comment]
I have the same problem and I am using version 7.0.3

**Comment by kovalyovi** [comment]
There was a useful comment [here (4052 by @MattyBoy4444)](https://github.com/FirebaseExtended/flutterfire/issues/4052#issuecomment-724748014) on how to temporarily fix the issue. 
In short, add `implementation 'com.google.firebase:firebase-analytics:18.0.0'` into the dependencies of your `app/build.gradle`. It helped me.

**Comment by kleberapsilva** [comment]
I have the same error in version 8.0.0-dev.11, in the application build.
I'm following the sample applicationhttps: //github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/lib/main.dart

**Comment by markusaksli-nc** [comment]
The upstream issue has been closed and I think the update there is relevant to everyone herehttps://github.com/firebase/firebase-android-sdk/issues/1662#issuecomment-756917362

**Comment by russellwheatley** [comment]
Hey folks, I believe this has now been fixed upstream. Will reopen for tracking if it is confirmed as still an upstream bug.
