### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Your issue title here

### ISSUE THREAD

**Issue by pangj** [FirebaseExtended/flutterfire#4044]
## Bug report

**Describe the bug**
exception thrown when running the example in foreground mode in android phone v10, there is no problem when running in background mode.  The notification of the message has no android object, don't know if this is the cause.  

### Steps to reproduce

1. keep running the app in foreground
2. copy the device token
3. send a push message with the device token, the notification has not set 'android' field

### Actual behavior

the stack trace is as below (message_codecs.dart:582):

---

## Additional context

```
PlatformException (PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.setSmallIcon(FlutterLocalNotificationsPlugin.java:221)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.createNotification(FlutterLocalNotificationsPlugin.java:171)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.showNotification(FlutterLocalNotificationsPlugin.java:765)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.show(FlutterLocalNotificationsPlugin.java:1014)
	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:912)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:363)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @pangj 
Please fill out the entire issue template so we can help you out.
Thank you

**Comment by pangj** [comment]
Thank you for your email, the issue has been solved.

**Comment by markusaksli-nc** [comment]
Thank you,

Closing this as fixed based on your last comment.
