### ISSUE TITLE
🐛 [firebase_messaging] Receiving notifications causes IllegalArgumentException

### ISSUE THREAD

**Issue by jpprime** [FirebaseExtended/flutterfire#4052]
## Bug report

**Describe the bug**
When the app if first built and when I receive a test notification using the specific device token, I get an exception and nothing happens on the app. Here is the exception:

```
D/FLTFireMsgReceiver(21935): broadcast received for message
W/ConnectionTracker(21935): Exception thrown while unbinding
W/ConnectionTracker(21935): java.lang.IllegalArgumentException: Service not registered: lp@6b3449c
W/ConnectionTracker(21935):     at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
W/ConnectionTracker(21935):     at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
W/ConnectionTracker(21935):     at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(21935):     at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204215081@20.42.15 (120400-0):1)
W/ConnectionTracker(21935):     at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204215081@20.42.15 (120400-0):2)
W/ConnectionTracker(21935):     at lq.D(:com.google.android.gms.dynamite_measurementdynamite@204215081@20.42.15 (120400-0):10)
W/ConnectionTracker(21935):     at lc.a(:com.google.android.gms.dynamite_measurementdynamite@204215081@20.42.15 (120400-0):2)
W/ConnectionTracker(21935):     at ee.run(:com.google.android.gms.dynamite_measurementdynamite@204215081@20.42.15 (120400-0):3)
W/ConnectionTracker(21935):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(21935):     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(21935):     at ix.run(:com.google.android.gms.dynamite_measurementdynamite@204215081@20.42.15 (120400-0):6)
```

This was not the case prior to migrating to version `8.0.0-dev.5`, and now I have updated to `8.0.0-dev.7` and the problem persists. I have reviewed the migration page about three times now and can't find anything that is missing, all seems to be fine. It might also be worth noting that I am using Cloud Firestore to store the tokens and it is working as intended, adding and removing the tokens.

### Steps to reproduce

1. Install and configure `firebase_messaging` version `7.0.3`;
2. Migrate to version `8.0.0-dev.7`;
3. Initialize Firebase;
4. Configure `firebase_messaging` to show a SnackBar when a notification arrives and the app is opened;
5. Retrieve the device's token;
6. Open the Cloud Messaging console to send a test notification to that specific device using its token;
7. See error or incorrect behavior

### Expected behavior

There should be a SnackBar showing the notification's title.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.9.2
Flutter SDK 1.20.4
sascar_app 1.0.0+1

dependencies:
- cloud_firestore 0.14.2 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- connectivity 0.4.9+3 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- dio 3.0.10 [http_parser path]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_messaging 8.0.0-dev.7 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_dotenv 2.1.0 [flutter meta]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_mobx 1.1.0+2 [mobx flutter]
- flutter_modular 1.3.2 [flutter]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- google_maps_cluster_manager 0.1.0 [flutter geohash google_maps_flutter]
- google_maps_flutter 0.5.33 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- intl 0.16.1 [path]
- intl_translation 0.17.10+1 [analyzer args dart_style intl path petitparser]
- location 3.0.2 [flutter meta location_platform_interface location_web]
- mobx 1.2.1+2 [meta]
- path 1.7.0
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sqflite 1.3.0 [flutter sqflite_common path]
- tree_view 0.0.5 [flutter]

dev dependencies:
- build_runner 1.10.1 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- fast_flutter_driver 0.1.1+2 [flutter mockito csv test args process_run colorize meta fast_flutter_driver_tool]
- flutter_driver 0.0.0 [file json_rpc_2 meta path web_socket_channel vm_service_client webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async intl matcher platform process pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_launcher_icons 0.8.1 [image args yaml path]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- mobx_codegen 1.1.0+1 [analyzer build build_resolvers meta mobx path source_gen]
- mockito 4.1.1 [collection matcher meta test_api]
- test 1.15.2 [analyzer async boolean_selector coverage http http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

dependency overrides:
- google_maps_flutter 0.5.33 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]

transitive dependencies:
- _fe_analyzer_shared 6.0.0 [meta]
- analyzer 0.39.14 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.4.2 [collection]
- boolean_selector 2.0.0 [source_span string_scanner]
- build 1.3.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.3.11 [analyzer build crypto graphs logging path package_config pub_semver]
- build_runner_core 6.0.1 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.0.0
- charcode 1.1.3
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.1.4 [path]
- clock 1.0.1 [meta]
- cloud_firestore_platform_interface 2.1.3 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.0+5 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- code_builder 3.3.0 [built_collection built_value collection matcher meta]
- collection 1.14.13
- colorize 2.0.0
- connectivity_for_web 0.3.1+2 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+5 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- coverage 0.13.11 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.1 [source_span]
- csv 4.0.3
- dart_style 1.3.6 [analyzer args path source_span]
- fake_async 1.1.0 [clock collection]
- fast_flutter_driver_tool 0.2.2+2 [args process_run colorize meta cli_util path yaml http]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.2 [http http_parser js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_messaging_platform_interface 1.0.0-dev.5 [flutter meta firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flutter_plugin_android_lifecycle 1.0.8 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [json_rpc_2 process web_socket_channel flutter_test flutter_driver archive args async boolean_selector charcode clock collection convert crypto fake_async file intl matcher meta path platform pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math vm_service_client webdriver]
- geohash 0.2.1
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_maps_flutter_platform_interface 1.0.4 [flutter meta plugin_platform_interface stream_transform]
- graphs 0.2.0
- html 0.14.0+3 [csslib source_span]
- http 0.12.1 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.14 [archive xml]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_annotation 3.0.1
- json_rpc_2 2.2.1 [stack_trace stream_channel]
- location_platform_interface 1.0.0 [flutter meta plugin_platform_interface]
- location_web 1.0.0 [flutter flutter_web_plugins location_platform_interface http_parser meta js]
- logging 0.11.4
- matcher 0.12.8 [stack_trace]
- meta 1.1.8
- mime 0.9.6+3
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- node_preamble 1.4.12
- package_config 1.9.3 [path charcode]
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.0
- petitparser 3.0.4 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.2 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- process_run 0.10.10+2 [path collection io yaml meta args pub_semver]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.3 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.7 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.0 [path shelf shelf_static]
- shelf_static 0.2.8 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.5 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.0.0 [path stack_trace source_maps]
- source_maps 0.10.9 [source_span]
- source_span 1.7.0 [charcode collection meta path term_glyph]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.9.5 [path]
- stream_channel 2.0.0 [async]
- stream_transform 1.2.0
- string_scanner 1.0.5 [charcode meta source_span]
- sync_http 0.2.0
- synchronized 2.2.0+2
- term_glyph 1.1.0
- test_api 0.2.17 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.10 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 0.1.1+2 [json_annotation]
- typed_data 1.2.0 [collection]
- vector_math 2.0.8
- vm_service 4.1.0 [meta]
- vm_service_client 0.2.6+2 [async collection json_rpc_2 pub_semver source_span stack_trace stream_channel web_socket_channel]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 0.7.3 [logging]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.0 [path process flutter]
- xml 4.2.0 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by codjias** [comment]
The exact same issue here. It started last week.

**Comment by joniaiuser** [comment]
maybe these are related? https://github.com/FirebaseExtended/flutterfire/issues/3990

**Comment by darshankawar** [comment]
@jpprime 
There's similar open issue describing your case, [3990](https://github.com/FirebaseExtended/flutterfire/issues/3990).
Please follow-up there for updates and any questions you may have.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Comment by jpprime** [comment]
> @jpprime
> There's similar open issue describing your case, [3990](https://github.com/FirebaseExtended/flutterfire/issues/3990).
> Please follow-up there for updates and any questions you may have.
> Closing this as duplicate. If you disagree, write in comments and I'll reopen.
> Thanks.

I'm so sorry, I searched a bit but didn't find my problem on the issues (open or closed). Thank you!

**Comment by MattyBoy4444** [comment]
What fixed it for me was adding back in the firebase-analytics implementation in build.gradle

implementation 'com.google.firebase:firebase-analytics:18.0.0'

**Comment by jpprime** [comment]
> What fixed it for me was adding back in the firebase-analytics implementation in build.gradle
> 
> implementation 'com.google.firebase:firebase-analytics:18.0.0'

Thanks, will try as a workaround while the final version with this issue fixed isn't released.

**Comment by jpprime** [comment]
> What fixed it for me was adding back in the firebase-analytics implementation in build.gradle
> 
> implementation 'com.google.firebase:firebase-analytics:18.0.0'

Hey, it worked! Thanks a bunch!!

**Comment by nemoryoliver** [comment]
> What fixed it for me was adding back in the firebase-analytics implementation in build.gradle
> 
> implementation 'com.google.firebase:firebase-analytics:18.0.0'

didn't work for me :(

**Comment by Samad321** [comment]
> What fixed it for me was adding back in the firebase-analytics implementation in build.gradle
> 
> implementation 'com.google.firebase:firebase-analytics:18.0.0'

it worked out thanks, please can you tell us why we got this error and how this line of code solved?

**Comment by pqtrong17** [comment]
> What fixed it for me was adding back in the firebase-analytics implementation in build.gradle
> 
> implementation 'com.google.firebase:firebase-analytics:18.0.0'

Not work for me... Any update?
