### ISSUE TITLE
🐛 [cloud_functions ] Calling function on cloud_functions 0.7.0+1,  throws exception

### ISSUE THREAD

**Issue by TahaTesser** [FirebaseExtended/flutterfire#4077]
### Steps to reproduce
1.. Deploy official function from https://flutter-firebase-docs.web.app/docs/functions/usage/#calling-endpoints
```js
const functions = require('firebase-functions');

exports.listFruit = functions.https.onCall((data, context) => {
  return ["Apple", "Banana", "Cherry", "Date", "Fig", "Grapes"]
});
```
2.  Add the following packages in your `pubspec.yaml` 
```yaml
  cloud_functions: ^0.7.0+1
  firebase_core: ^0.5.2
```
3. Use the minimal code sample below 
<details> 
<summary>code sample</summary> 

```dart
// Copyright 2018, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:cloud_functions/cloud_functions.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseFunctions.instance
      .useFunctionsEmulator(origin: 'http://localhost:5001');
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List<dynamic> listOfFruits;
  String exceptionMessage = '';

  @override
  Widget build(BuildContext context) {
    final HttpsCallable callable = FirebaseFunctions.instance.httpsCallable(
        'listFruit',
        options: HttpsCallableOptions(timeout: const Duration(seconds: 30)));
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Cloud Functions example app'),
        ),
        body: Center(
          child: Container(
            margin: const EdgeInsets.only(top: 32.0, left: 16.0, right: 16.0),
            child: Column(
              children: [
                Text(listOfFruits.toString() ?? exceptionMessage),
                MaterialButton(
                  child: const Text('Get Fruits'),
                  onPressed: () async {
                    try {
                      final HttpsCallableResult result = await callable.call();
                      print(result.data);
                      listOfFruits = [];
                      setState(() {
                        for (var item in result.data) {
                          listOfFruits.add(item);
                        }
                      });
                    } on FirebaseFunctionsException catch (e) {
                      print('caught firebase functions exception');
                      print(e.code);
                      print(e.message);
                      print(e.details);
                      setState(() {
                        listOfFruits = null;
                        exceptionMessage =
                            "caught firebase functions exception\n${e.code}\n${e.message}\n${e.details}";
                      });
                    } catch (e) {
                      print('caught generic exception');
                      print(e);
                    }
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

4. Run the app and tap `Get fruits` button and see it doesn't update text view and instead throws an exception.

```bash
I/flutter ( 9134): caught firebase functions exception
I/flutter ( 9134): unavailable
I/flutter ( 9134): UNAVAILABLE
```

### Same official function works fine if you use earlier code sample and package version
1. Updating ` pubspec.yaml`, comment out  `firebase_core` and change to `cloud_functions: ^0.5.0` (earlier version)
```yaml
  cloud_functions: ^0.5.0
  # firebase_core: ^0.5.2
```
2. Use the minimal code sample below (which doesn't use `firebse_core`)
<details> 
<summary>code sample</summary> 

```dart
// Copyright 2018, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:cloud_functions/cloud_functions.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List<dynamic> listOfFruits;
  String exceptionMessage = '';

  @override
  Widget build(BuildContext context) {
    final HttpsCallable callable = CloudFunctions.instance
        .getHttpsCallable(functionName: 'listFruit')
          ..timeout = const Duration(seconds: 30);
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Cloud Functions example app'),
        ),
        body: Center(
          child: Container(
            margin: const EdgeInsets.only(top: 32.0, left: 16.0, right: 16.0),
            child: Column(
              children: [
                Text(listOfFruits.toString() ?? exceptionMessage),
                MaterialButton(
                  child: const Text('Get Fruits'),
                  onPressed: () async {
                    try {
                      final HttpsCallableResult result = await callable.call();
                      print(result.data);
                      listOfFruits = [];
                      setState(() {
                        for (var item in result.data) {
                          listOfFruits.add(item);
                        }
                      });
                    } on CloudFunctionsException catch (e) {
                      print('caught firebase functions exception');
                      print(e.code);
                      print(e.message);
                      print(e.details);
                      setState(() {
                        listOfFruits = null;
                        exceptionMessage =
                            "caught firebase functions exception\n${e.code}\n${e.message}\n${e.details}";
                      });
                    } catch (e) {
                      print('caught generic exception');
                      print(e);
                    }
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

</details>

3. Run the app and tap `Get fruits` button and you will see text view is updated list of fruits 
### Preview
![ezgif com-gif-maker](https://user-images.githubusercontent.com/48603081/98686688-dcb35300-238e-11eb-89fe-f4505ea480b5.gif)

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19042.610], locale en-US)
    • Flutter version 1.22.3 at C:\Code\flutter_stable
    • Framework revision 8874f21e79 (12 days ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.51.0)
    • VS Code at C:\Users\taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

</details>

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.3
Flutter SDK 1.22.3
triage 1.0.0+1

dependencies:
- cloud_functions 0.7.0+1 [meta flutter firebase_core firebase_core_platform_interface cloud_functions_platform_interface cloud_functions_web]
- cupertino_icons 0.1.3
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_functions_platform_interface 3.0.1 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 3.0.1 [firebase_core cloud_functions_platform_interface flutter flutter_web_plugins firebase http_parser meta]
- collection 1.15.0-nullsafety.3
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase 7.3.0 [http http_parser js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.1 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.1+1
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- pedantic 1.9.0
- plugin_platform_interface 1.0.2 [meta]
- quiver 2.1.3 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner 
term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3```
```
</details>

**Comment by markusaksli-nc** [comment]
I can reproduce this on the the latest flutter master `1.24.0-8.0.pre.194` with `cloud_functions: ^0.7.0` but not with `cloud_functions: ^0.6.0+1`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.194, on Microsoft Windows [Version 10.0.19041.572], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.194 at C:\Development\flutter_master
    • Framework revision 018467cdb1 (2 hours ago), 2020-11-11 02:04:03 -0500
    • Engine revision 81f219c59c
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 86.0.4240.183
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 86.0.622.63

• No issues found!
```
</details>

**Comment by ghprod** [comment]
I also got this when try to run `flutter run`

```
Note: /home/bolt/dev/data/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.7.0+1/android/src/main/java/io/flutter/plugins/firebase/functions/FlutterFirebaseFunctionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.
```

pubspec.yml

```
  firebase_core: 0.5.2
  cloud_functions: 0.7.0+1
```

```
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /home/bolt/dev/data/flutter
    • Framework revision 1aafb3a8b9 (5 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
```

Android Studio 4.1

**Comment by markuspaschi** [comment]
Works again with:

Flutter 1.26.0-1.0.pre • channel dev
cloud_functions: 0.7.2

**Comment by TahaTesser** [comment]
Still can't run, getting `I/flutter (12155): [firebase_functions/deadline-exceeded] DEADLINE_EXCEEDED` 
```yaml
dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^0.7.2
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.3

```

**Comment by osaxma** [comment]
I'm getting `deadline-exceeded` exception  as well on the `Web` platform. 

The error appears inconsistently and only when using `httpsCallable`. 

The exception appears even though the cloud function executed successfully. Since the function in question only writes data to Firestore, I was able to confirm that the results were actually written. Also the functions logs on the firebase console shows successful execution. 

The main issue here is that the response is lost because of this exception plus the uncertainty of what's happening _(ie fear of a high bill)_. 

**Exception with the Stack Trace:**
```
[firebase_functions/deadline-exceeded] deadline-exceeded
=========================================== stack trace:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 231:49  throw_
packages/cloud_functions_web/https_callable_web.dart 44:7                     call
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 60:31            <fn>
dart-sdk/lib/async/zone.dart 1451:54                                          runBinary
dart-sdk/lib/async/future_impl.dart 164:20                                    handleError
dart-sdk/lib/async/future_impl.dart 720:46                                    handleError
dart-sdk/lib/async/future_impl.dart 741:13                                    _propagateToListeners
dart-sdk/lib/async/future_impl.dart 549:5                                     [_completeError]
dart-sdk/lib/async/future_impl.dart 605:7                                     callback
dart-sdk/lib/async/schedule_microtask.dart 41:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 50:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
TypeError: Cannot read property 'Symbol(dartx.forEach)' of null
    at Function.from (http://localhost:56045/dart_sdk.js:40763:14)
    at callFunction (http://localhost:56045/packages/foro/src/services/firestore_service.dart.lib.js:132:64)
    at callFunction.next (<anonymous>)
    at http://localhost:56045/dart_sdk.js:38561:33
    at _RootZone.runUnary (http://localhost:56045/dart_sdk.js:38418:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:56045/dart_sdk.js:33395:29)
    at handleValueCallback (http://localhost:56045/dart_sdk.js:33955:49)
    at Function._propagateToListeners (http://localhost:56045/dart_sdk.js:33993:17)
    at _Future.new.[_completeError] (http://localhost:56045/dart_sdk.js:33843:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:56045/dart_sdk.js:33882:31)
    at Object._microtaskLoop (http://localhost:56045/dart_sdk.js:38676:13)
    at _startMicrotaskLoop (http://localhost:56045/dart_sdk.js:38682:13)
    at http://localhost:56045/dart_sdk.js:34209:9

```


**Firebase Dependencies**
pubspec.yaml:
```
  firebase_core : ^0.5.0
  firebase_auth: ^0.18.1
  cloud_firestore: ^0.14.1
  firebase_storage: ^5.2.0
  firebase_analytics: ^6.0.2
  cloud_functions: ^0.7.2
```

index.html :
```
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-storage.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-functions.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-analytics.js"></script>
```

**Flutter Doctor**

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.145, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!
```

Please let me know if you need any additional information. Unfortunately, I'm not able to reproduce the error consistently because it doesn't appear all the time but it comes up frequently.

**Comment by tapizquent** [comment]
Any news on this? Cloud functions seems to be totally broken for web.

**Comment by Eufranio** [comment]
I'm getting `DEADLINE_EXCEEDED` as well on latest (as of now) cloud_functions on mobile. 
---
<details><summary>flutter doctor -v:</summary>

```
D:\Dev\IdeaProjects\morada-dos-sonhos>flutter doctor -v
[√] Flutter (Channel dev, 2.1.0-12.1.pre, on Microsoft Windows [versÃ£o 10.0.19041.867], locale pt-BR)
    • Flutter version 2.1.0-12.1.pre at D:\Dev\Android\flutter
    • Framework revision 8264cb3e8a (6 days ago), 2021-03-10 12:37:57 -0800
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Dev\Android
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = D:\Dev\Android
    • Java binary at: C:\Program Files\Java\jdk1.8.0_241\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.2
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 89.0.774.45

! Doctor found issues in 1 category.

```

</details>

**Comment by Salakar** [comment]
Is this still an issue, I've not seen it on our testing suite and other local testing we do?

**Comment by TahaTesser** [comment]
Hi @Salakar 
I just created a fresh sample on the latest versions and deployed the [function ](https://firebase.flutter.dev/docs/functions/usage/#calling-endpoints)

Calling the function gets the results

### Preview
<img src="https://user-images.githubusercontent.com/48603081/115018461-8f4c8c00-9ec0-11eb-9927-ad0c83ee16d4.png" height="450" /> | 


Thank you so much
