### ISSUE TITLE
[runtime error] java.lang.IncompatibleClassChangeError: Class 'com.google.android.gms.auth.api.signin.internal.SignInHubActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)

### ISSUE THREAD

**Issue by terryBaz** [FirebaseExtended/flutterfire#41]
### Setup

`android/build.gradle`
```
buildscript {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.google.gms:google-services:4.2.0'
        classpath 'com.android.tools.build:gradle:3.3.2'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')

    project.configurations.all {

        exclude group: 'com.google.guava', module: 'failureaccess'


        resolutionStrategy.eachDependency { details ->
//            if (details.requested.group == 'com.android.support'
//                    && !details.requested.name.contains('multidex') ) {
//                details.useVersion "26.1.0"
//            }

            if('guava' == details.requested.name) {
                details.useVersion '27.0-android'
            }

        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

`android/app/build.gradle`
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

//def keystoreProperties = new Properties()
//def keystorePropertiesFile = rootProject.file('key.properties')
//if (keystorePropertiesFile.exists()) {
//    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
//}

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "dz.softart.tamejida"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

//    signingConfigs {
//        release {
//            keyAlias keystoreProperties['keyAlias']
//            keyPassword keystoreProperties['keyPassword']
////            storeFile file(keystoreProperties['storeFile'])
//            storeFile file("D:\\codeLabs\\tamejida\\key.jks")
//            storePassword keystoreProperties['storePassword']
//        }
//    }
    buildTypes {
        release {
//            signingConfig signingConfigs.release

            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    def multidex_version = "2.0.1"
    implementation 'androidx.multidex:multidex:$multidex_version'

    implementation 'com.google.firebase:firebase-core:17.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

apply plugin: 'com.google.gms.google-services'
```

`pubspec.yaml`
```
name: tamejida
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.12.0+2
  provider: ^3.1.0
  firebase_auth: ^0.14.0+4
  google_sign_in: ^4.0.4
  flutter_facebook_login: ^2.0.1
  shared_preferences: ^0.5.3+4
  flutter_svg: ^0.13.1
  video_player: ^0.10.1+6
  flutter_swiper : ^1.1.6
  intl: ^0.15.8
  transparent_image: ^1.0.0
  cached_network_image: ^1.1.1
  carousel_slider: ^1.3.0
  flutter_radio: ^0.1.7
  connectivity: ^0.4.3+7
  photo_view: ^0.4.2
  shimmer: ^1.0.0

  flutter_downloader: ^1.1.9
  webview_flutter: ^0.3.13


dev_dependencies:
  flutter_test:
    sdk: flutter
```
### Error

```
D/FeatureProxyBase(13397): FeatureProxyBase class constructor
D/MultiWindow(13397): MultiWindowProxy constructor.
D/FeatureProxyBase(13397): getService(), serviceName = multiwindow_service_v1
D/FeatureProxyBase(13397): FeatureProxyBase class constructor
D/MultiWindow(13397): MultiWindowProxy constructor.
D/FeatureProxyBase(13397): getService(), serviceName = multiwindow_service_v1
D/ActivityThread(13397): ACT-AM_ON_PAUSE_CALLED ActivityRecord{3fa64be4 token=android.os.BinderProxy@1b45f84d {dz.softart.tamejida/dz.softart.tamejida.MainActivity}}
D/ActivityThread(13397): ACT-PAUSE_ACTIVITY handled : 1 / android.os.BinderProxy@1b45f84d
V/ActivityThread(13397): Handling launch of ActivityRecord{d9ac6c token=android.os.BinderProxy@36bf8235 {dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}}
V/ActivityThread(13397): ActivityRecord{d9ac6c token=android.os.BinderProxy@36bf8235 {dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}}: app=io.flutter.app.FlutterApplication@230aa73e, appName=dz.softart.tamejida, pkg=dz.softart.tamejida, comp={dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}, dir=/data/app/dz.softart.tamejida-2/base.apk
D/FeatureProxyBase(13397): FeatureProxyBase class constructor
D/MultiWindow(13397): MultiWindowProxy constructor.
D/FeatureProxyBase(13397): getService(), serviceName = multiwindow_service_v1
D/MALI    (13397): _egl_make_current:857: [MALI] make current with display 0x1, context 0x40000003, state 0xaf8285d8
D/MALI    (13397): _egl_make_current:872: [MALI] Map __dpy 0x1 to dpy 0xb46f1920
D/MALI    (13397): _egl_make_current:906: [MALI] Map __ctx 0x40000003 to ctx 0xaf9df3d0
D/FeatureProxyBase(13397): FeatureProxyBase class constructor
D/MultiWindow(13397): MultiWindowProxy constructor.
D/FeatureProxyBase(13397): getService(), serviceName = multiwindow_service_v1
D/Surface (13397): Surface::setBuffersDimensions(this=0xb45c8400,w=720,h=1280)
D/FeatureProxyBase(13397): FeatureProxyBase class constructor
D/MultiWindow(13397): MultiWindowProxy constructor.
D/FeatureProxyBase(13397): getService(), serviceName = multiwindow_service_v1
D/FeatureProxyBase(13397): FeatureProxyBase class constructor
D/MultiWindow(13397): MultiWindowProxy constructor.
D/FeatureProxyBase(13397): getService(), serviceName = multiwindow_service_v1
V/ActivityThread(13397): Performing resume of ActivityRecord{d9ac6c token=android.os.BinderProxy@36bf8235 {dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}}
D/ActivityThread(13397): ACT-AM_ON_RESUME_CALLED ActivityRecord{d9ac6c token=android.os.BinderProxy@36bf8235 {dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}}
V/ActivityThread(13397): Resume ActivityRecord{d9ac6c token=android.os.BinderProxy@36bf8235 {dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}} started activity: true, hideForNow: false, finished: false
V/PhoneWindow(13397): DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.impl.PhoneWindow$DecorView{1d2f0570 I.E..... R.....I. 0,0-0,0}
D/ViewRootImpl(13397): hardware acceleration is enabled, this = ViewRoot{254da0e9 dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity,ident = 1}
D/SQLiteDatabase(13397): beginTransaction()
D/SQLiteDatabase(13397): endTransaction()
V/ActivityThread(13397): Resuming ActivityRecord{d9ac6c token=android.os.BinderProxy@36bf8235 {dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}} with isForward=true
D/FeatureProxyBase(13397): FeatureProxyBase class constructor
D/MultiWindow(13397): MultiWindowProxy constructor.
D/FeatureProxyBase(13397): getService(), serviceName = multiwindow_service_v1
V/PhoneWindow(13397): DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{254da0e9 dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity,ident = 1}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{1d2f0570 V.E..... R.....I. 0,0-0,0}
V/ActivityThread(13397): Scheduling idle handler for ActivityRecord{d9ac6c token=android.os.BinderProxy@36bf8235 {dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}}
D/ActivityThread(13397): ACT-LAUNCH_ACTIVITY handled : 0 / ActivityRecord{d9ac6c token=android.os.BinderProxy@36bf8235 {dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}}
D/ActivityThread(13397): ACT-AM_ON_PAUSE_CALLED ActivityRecord{d9ac6c token=android.os.BinderProxy@36bf8235 {dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}}
D/ActivityThread(13397): ACT-PAUSE_ACTIVITY handled : 1 / android.os.BinderProxy@36bf8235
D/OpenGLRenderer(13397): CanvasContext() 0x9f96c6c0 initialize 0x9faa6a08
D/Surface (13397): Surface::connect(this=0x9faa6a00,api=1)
D/MALI    (13397): _egl_make_current:857: [MALI] make current with display 0x1, context 0x40000003, state 0xaf8285d8
D/MALI    (13397): _egl_make_current:872: [MALI] Map __dpy 0x1 to dpy 0xb46f1920
D/MALI    (13397): _egl_make_current:906: [MALI] Map __ctx 0x40000003 to ctx 0xaf9df3d0
D/Surface (13397): Surface::setBuffersDimensions(this=0xb45c8400,w=720,h=1280)
D/GraphicBuffer(13397): register, handle(0x9f954700) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
I/MaliEGL (13397): [Mali]window_type=1, is_framebuffer=0, errnum = 0
I/MaliEGL (13397): [Mali]surface->num_buffers=4, surface->num_frames=3, win_min_undequeued=1
I/MaliEGL (13397): [Mali]max_allowed_dequeued_buffers=3
D/Surface (13397): Surface::setBufferCount(this=0x9faa6a00,bufferCount=4)
D/GraphicBuffer(13397): unregister, handle(0x9f954700) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
D/MALI    (13397): _egl_make_current:857: [MALI] make current with display 0x1, context 0x40000002, state 0x9f8c62e0
D/MALI    (13397): _egl_make_current:872: [MALI] Map __dpy 0x1 to dpy 0xb46f1920
D/MALI    (13397): _egl_make_current:906: [MALI] Map __ctx 0x40000002 to ctx 0xb4736650
D/Surface (13397): Surface::setBuffersDimensions(this=0x9faa6a00,w=720,h=1280)
D/GraphicBuffer(13397): register, handle(0x9f954700) (w:720 h:1280 s:720 f:0x1 u:0x000f02)
D/Surface (13397): Surface::allocateBuffers(this=0x9faa6a00)
D/MALI    (13397): _egl_make_current:857: [MALI] make current with display 0x1, context 0x40000003, state 0xaf8285d8
D/MALI    (13397): _egl_make_current:872: [MALI] Map __dpy 0x1 to dpy 0xb46f1920
D/MALI    (13397): _egl_make_current:906: [MALI] Map __ctx 0x40000003 to ctx 0xaf9df3d0
D/Surface (13397): Surface::setBuffersDimensions(this=0xb45c8400,w=720,h=1280)
D/MALI    (13397): _egl_make_current:857: [MALI] make current with display 0x1, context 0x40000003, state 0xaf8285d8
D/MALI    (13397): _egl_make_current:872: [MALI] Map __dpy 0x1 to dpy 0xb46f1920
D/MALI    (13397): _egl_make_current:906: [MALI] Map __ctx 0x40000003 to ctx 0xaf9df3d0
D/Surface (13397): Surface::setBuffersDimensions(this=0xb45c8400,w=720,h=1280)
D/MALI    (13397): _egl_make_current:857: [MALI] make current with display 0x1, context 0x40000003, state 0xaf8285d8
D/MALI    (13397): _egl_make_current:872: [MALI] Map __dpy 0x1 to dpy 0xb46f1920
D/MALI    (13397): _egl_make_current:906: [MALI] Map __ctx 0x40000003 to ctx 0xaf9df3d0
D/Surface (13397): Surface::setBuffersDimensions(this=0xb45c8400,w=720,h=1280)
V/ActivityThread(13397): Finishing stop of ActivityRecord{3fa64be4 token=android.os.BinderProxy@1b45f84d {dz.softart.tamejida/dz.softart.tamejida.MainActivity}}: show=true win=com.android.internal.policy.impl.PhoneWindow@36d662a5
D/ActivityThread(13397): ACT-STOP_ACTIVITY_SHOW handled : 0 / android.os.BinderProxy@1b45f84d
V/ActivityThread(13397): Finishing stop of ActivityRecord{d9ac6c token=android.os.BinderProxy@36bf8235 {dz.softart.tamejida/com.google.android.gms.auth.api.signin.internal.SignInHubActivity}}: show=true win=com.android.internal.policy.impl.PhoneWindow@1bf4767a
D/ActivityThread(13397): ACT-STOP_ACTIVITY_SHOW handled : 0 / android.os.BinderProxy@36bf8235
D/SQLiteDatabase(13397): beginTransaction()
D/MALI    (13397): _egl_make_current:857: [MALI] make current with display 0x1, context 0x40000003, state 0xaf8285d8
D/MALI    (13397): _egl_make_current:872: [MALI] Map __dpy 0x1 to dpy 0xb46f1920
D/MALI    (13397): _egl_make_current:906: [MALI] Map __ctx 0x40000003 to ctx 0xaf9df3d0
D/Surface (13397): Surface::setBuffersDimensions(this=0xb45c8400,w=720,h=1280)
D/SQLiteDatabase(13397): endTransaction()
D/SQLiteDatabase(13397): beginTransaction()
D/SQLiteDatabase(13397): endTransaction()
D/AndroidRuntime(13397): Shutting down VM
E/AndroidRuntime(13397): FATAL EXCEPTION: main
E/AndroidRuntime(13397): Process: dz.softart.tamejida, PID: 13397
E/AndroidRuntime(13397): java.lang.IncompatibleClassChangeError: Class 'com.google.android.gms.auth.api.signin.internal.SignInHubActivity' does not implement interface 'androidx.lifecycle.LifecycleOwner' in call to 'androidx.lifecycle.Lifecycle androidx.lifecycle.LifecycleOwner.getLifecycle()' (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
E/AndroidRuntime(13397): 	at androidx.lifecycle.LiveData.observe(LiveData.java:172)
E/AndroidRuntime(13397): 	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setCallback(LoaderManagerImpl.java:100)
E/AndroidRuntime(13397): 	at androidx.loader.app.LoaderManagerImpl.createAndInstallLoader(LoaderManagerImpl.java:400)
E/AndroidRuntime(13397): 	at androidx.loader.app.LoaderManagerImpl.initLoader(LoaderManagerImpl.java:421)
E/AndroidRuntime(13397): 	at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.zzn(Unknown Source)
E/AndroidRuntime(13397): 	at com.google.android.gms.auth.api.signin.internal.SignInHubActivity.onActivityResult(Unknown Source)
E/AndroidRuntime(13397): 	at android.app.Activity.dispatchActivityResult(Activity.java:6294)
E/AndroidRuntime(13397): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3829)
E/AndroidRuntime(13397): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3876)
E/AndroidRuntime(13397): 	at android.app.ActivityThread.access$1300(ActivityThread.java:178)
E/AndroidRuntime(13397): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1519)
E/AndroidRuntime(13397): 	at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime(13397): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime(13397): 	at android.app.ActivityThread.main(ActivityThread.java:5631)
E/AndroidRuntime(13397): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13397): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(13397): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
E/AndroidRuntime(13397): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
D/SQLiteDatabase(13397): beginTransaction()
D/SQLiteDatabase(13397): endTransaction()
```

**Comment by terryBaz** [comment]
error is gone by adding : 
```grovy
dependencies {
//...
    implementation "androidx.appcompat:appcompat:1.1.0-rc01"
//...
}
````
in `android/app/build.gradle`
