### ISSUE TITLE
🐛 [firebase_auth 0.18.3] checkActionCode throws TypeError and never completes Future

### ISSUE THREAD

**Issue by gabriel-casado** [FirebaseExtended/flutterfire#4146]
## Bug report

**Describe the bug**
Calling FirebaseAuth.checkActionCode() with a valid value throws an uncaught exception:

```
nexttick.js:37 Uncaught TypeError: Right-hand side of 'instanceof' is not callable
    at dart.LazyJSType.new.isRawJSType (types.dart:219)
    at dart.LazyJSType.new.is (types.dart:225)
    at dart.LegacyType.new.is (types.dart:414)
    at Function.is_FutureOr [as is] (future.dart:43)
    at dart.NullableType.new.as (types.dart:390)
    at js_util.dart:158
    at e.g (promise.js:826)
    at Oe (promise.js:1166)
    at _e (promise.js:1140)
    at le.t.fc (promise.js:1111)
    at he (run.js:124)
```

### Steps to reproduce

Tested on Flutter Web:

1. Call FirebaseAuth's checkActionCode
2. See exception in console output

### Expected behavior

The expected behavior is that the Future returned in checkActionCode will be completed with success or error.

---

## Additional context

Firebase config in index.html:

```
  <script src="https://www.gstatic.com/firebasejs/7.14.3/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.14.3/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.14.3/firebase-analytics.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.14.3/firebase-firestore.js"></script>
  <script>
    // Firebase configuration
    var firebaseConfig = {
      apiKey: "...",
      authDomain: "...",
      databaseURL: "...",
      projectId: "...",
      storageBucket: "...",
      messagingSenderId: "...",
      appId: "...",
      measurementId: "..."
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
  </script>
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Android Studio
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
[√] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.11.0-213.1.beta
Flutter SDK 1.23.0-18.1.pre
app 1.0.0+1

dependencies:
- cloud_firestore 0.14.3 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 1.0.0
- firebase_auth 0.18.3 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_auth_buttons 0.8.0 [flutter]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_sign_in 4.5.6 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- provider 4.3.2+2 [flutter nested collection]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.0 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase_auth_platform_interface 2.1.3 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.3-nullsafety.1
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.4
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.2 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
- xml 4.5.1 [collection convert meta petitparser]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Reproducible on latest master `1.24.0-8.0.pre.321` with
```yaml
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
```
```html
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js"></script>
```
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.321, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.321 at C:\Development\flutter_master
    • Framework revision 05dadb0120 (9 hours ago), 2020-11-20 07:33:05 +0530
    • Engine revision a0da844845
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 86.0.622.68

• No issues found!

```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';
import 'package:flutter/material.dart';
import 'package:flutter_signin_button/flutter_signin_button.dart';

final FirebaseAuth _auth = FirebaseAuth.instance;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(AuthExampleApp());
}

/// The entry point of the application.
///
/// Returns a [MaterialApp].
class AuthExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Example App',
      theme: ThemeData.dark(),
      home: SignInPage(),
      routes: {"signInPage": (ctx) => SignInPage()},
    );
  }
}

/// Entrypoint example for various sign-in flows with Firebase.
class SignInPage extends StatefulWidget {
  /// The page title.
  final String title = 'Anonymous number link test';

  @override
  State<StatefulWidget> createState() => _SignInPageState();
}

class _SignInPageState extends State<SignInPage> {
  String uid = "";
  String code = "";

  @override
  void initState() {
    initDynamicLinks();
    changeUidText(_auth.currentUser);
    _auth.userChanges().listen(changeUidText);
    super.initState();
  }

  void initDynamicLinks() async {
    final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;

    if (deepLink != null) {
      String linkCode = deepLink.queryParameters['oobCode'];
      print(linkCode);
      if (linkCode != null) {
        setState(() {
          code = linkCode;
        });
      }
    }

    FirebaseDynamicLinks.instance.onLink(onSuccess: (PendingDynamicLinkData dynamicLink) async {
      final Uri deepLink = dynamicLink?.link;
      if (deepLink != null) {
        String linkCode = deepLink.queryParameters['oobCode'];
        print(linkCode);
        if (linkCode != null) {
          setState(() {
            code = linkCode;
          });
        }
      }
    }, onError: (OnLinkErrorException e) async {
      print('onLinkError');
      print(e.message);
    });
  }

  void changeUidText(User user) {
    setState(() {
      if (user == null) {
        uid = "Signed out";
        return;
      }
      uid = user.uid;
      if (user.phoneNumber != null) {
        uid += " " + user.phoneNumber;
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          Builder(builder: (BuildContext context) {
            return FlatButton(
              child: const Text('Sign out'),
              textColor: Theme.of(context).buttonColor,
              onPressed: () async {
                final User user = await _auth.currentUser;
                if (user == null) {
                  Scaffold.of(context).showSnackBar(const SnackBar(
                    content: Text('No one has signed in.'),
                  ));
                  return;
                }
                _signOut();
                final String uid = user.uid;
                Scaffold.of(context).showSnackBar(SnackBar(
                  content: Text(uid + ' has successfully signed out.'),
                ));
              },
            );
          })
        ],
      ),
      body: Builder(builder: (BuildContext context) {
        return ListView(
          padding: EdgeInsets.all(8),
          scrollDirection: Axis.vertical,
          children: <Widget>[
            Text(uid),
            _EmailLinkSignInSection(),
            Text(code),
            RaisedButton(
              child: Text("Check sign in code"),
              onPressed: () async {
                var result = (await FirebaseAuth.instance.checkActionCode(code));
                print(result.operation);
              },
            ),
            TextField(
              onChanged: (value) => setState(() => code = value),
            ),
          ],
        );
      }),
    );
  }

  // Example code for sign out.
  void _signOut() async {
    await _auth.signOut();
  }
}

class _EmailLinkSignInSection extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _EmailLinkSignInSectionState();
}

class _EmailLinkSignInSectionState extends State<_EmailLinkSignInSection> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final TextEditingController _emailController = TextEditingController();

  String _userEmail;

  @override
  Widget build(BuildContext context) {
    return Form(
        key: _formKey,
        child: Card(
            child: Padding(
          padding: EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Container(
                child: Text('Test sign in with email and link', style: TextStyle(fontWeight: FontWeight.bold)),
                alignment: Alignment.center,
              ),
              TextFormField(
                controller: _emailController,
                decoration: const InputDecoration(labelText: 'Email'),
                validator: (String value) {
                  if (value.isEmpty) return 'Please enter your email.';
                  return null;
                },
              ),
              Container(
                padding: const EdgeInsets.only(top: 16.0),
                alignment: Alignment.center,
                child: SignInButtonBuilder(
                  icon: Icons.insert_link,
                  text: "Sign In",
                  backgroundColor: Colors.blueGrey[700],
                  onPressed: () async {
                    await _signInWithEmailAndLink();
                  },
                ),
              ),
            ],
          ),
        )));
  }

  @override
  void dispose() {
    _emailController.dispose();
    super.dispose();
  }

  void _signInWithEmailAndLink() async {
    try {
      _userEmail = _emailController.text;
      await _auth.sendSignInLinkToEmail(
          email: _userEmail,
          actionCodeSettings: ActionCodeSettings(
              url:
              'https://react-native-firebase-testing.firebaseapp.com/emailSignin',
              handleCodeInApp: true,
              iOSBundleId: 'io.flutter.plugins.firebaseAuthExample',
              androidPackageName: 'io.flutter.plugins.firebaseauthexample'));
      Scaffold.of(context).showSnackBar(SnackBar(
        content: Text("An email has been sent to ${_userEmail}"),
      ));
    } catch (e) {
      print(e);
      Scaffold.of(context).showSnackBar(SnackBar(
        content: Text("Sending email failed"),
      ));
    }
  }
}
```
</details>

`https://www.gstatic.com/firebasejs/8.0.2/firebase-auth.js` doesn't seem to help.

<details>
 <summary>Logs</summary>

```
TypeError: Right-hand side of 'instanceof' is not callable
    at dart.LazyJSType.new.isRawJSType (http://localhost:61201/dart_sdk.js:6097:35)
    at dart.LazyJSType.new.is (http://localhost:61201/dart_sdk.js:6101:19)
    at dart.LegacyType.new.is (http://localhost:61201/dart_sdk.js:6209:24)
    at Function.is_FutureOr [as is] (http://localhost:61201/dart_sdk.js:3961:24)
    at dart.NullableType.new.as (http://localhost:61201/dart_sdk.js:6175:39)
    at http://localhost:61201/dart_sdk.js:60098:136
    at e.g (https://www.gstatic.com/firebasejs/8.0.2/firebase-auth.js:1:28817)
    at Re (https://www.gstatic.com/firebasejs/8.0.2/firebase-auth.js:1:29843)
    at Ce (https://www.gstatic.com/firebasejs/8.0.2/firebase-auth.js:1:29734)
    at de.t.fc (https://www.gstatic.com/firebasejs/8.0.2/firebase-auth.js:1:30574)
    at fe (https://www.gstatic.com/firebasejs/8.0.2/firebase-auth.js:1:27643)
```
</details>

**Comment by recycledhominid** [comment]
I have the same error. It's only happening on web, iOS seems fine.

Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)

firebase_core: ^0.5.2+1
firebase_auth: ^0.18.3+1

<script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-auth.js"></script>

Is there any workaround to this or any previous version that works? This is breaking my app 😞

**Comment by casadogg** [comment]
> I have the same error. It's only happening on web, iOS seems fine.
> 
> Flutter (Channel beta, 1.24.0-10.2.pre, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
> 
> ```yaml
> firebase_core: ^0.5.2+1
> firebase_auth: ^0.18.3+1
> ```
> 
> ```
> <script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-app.js"></script>
> <script src="https://www.gstatic.com/firebasejs/8.1.1/firebase-auth.js"></script>
> ```
> 
> Is there any workaround to this or any previous version that works? This is breaking my app 😞
> 
> [EDIT] Workaround: Skip checkActionCode and go straight to applyActionCode 😌

Yeah, we skipped checkActionCode too in our app.

**Comment by russellwheatley** [comment]
This problem is not something we have much control over as far as I can tell. I did a bit of digging and found the dart SDK is making the equivalent following check in JavaScript:
```js
const OPERATIONS = {EMAIL_SIGNIN: "EMAIL_SIGNIN", PASSWORD_RESET: "PASSWORD_RESET", RECOVER_EMAIL: "RECOVER_EMAIL", VERIFY_EMAIL: "VERIFY_EMAIL"};

//...however it is initialised by Firebase web SDK
const actionCodeInfo = firebase.auth.ActionCodeInfo();

// this throw an error because OPERATIONS is an object, not a class
if(actionCodeInfo instanceof OPERATIONS){
...
}
```
results in the following error:
```
Uncaught TypeError: Right-hand side of 'instanceof' is not callable

```

I had a look into the dart SDK and noticed the offending function has been removed in this [commit](https://github.com/dart-lang/sdk/commit/8e663541c9a25f491be015c684c170dbe57f3276#diff-53a682145f0103b8eaf64357c5447dcb38ee2b87034577136bb54c69668ee30dL245) recently.

I tested `checkActionCode` on the flutter dev channel which is using the latest dart SDK and it works as expected.

**Comment by kaumudpa** [comment]
I conform - that `checkActionCode` and `applyActionCode` are working as expected in `dev` channel.

**Comment by russellwheatley** [comment]
I'm going to assume this issue has now been resolved given the amount of time elapsed without feedback.
