### ISSUE TITLE
🐛 [cloud_firestore] java.lang.NullPointerException at FlutterFirebaseFirestorePlugin.java:67

### ISSUE THREAD

**Issue by talent-apps** [FirebaseExtended/flutterfire#4180]
## Bug report
The following crash started occurring sporadically on our Android production app after upgrading `cloud_firestore` from `0.14.0+2` to `0.14.1+2`:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.lambda$null$8$FlutterFirebaseFirestorePlugin(FlutterFirebaseFirestorePlugin.java:67)
       at io.flutter.plugins.firebase.firestore.-$$Lambda$FlutterFirebaseFirestorePlugin$Om-QqNeCto0p2tej6MhbBamtjUw.onEvent(-.java:6)
       at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(Query.java:27)
       at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Query.java:6)
       at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(AsyncEventListener.java:6)
       at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(AsyncEventListener.java:6)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.google.android.gms.internal.tasks.zzb.dispatchMessage(zzb.java)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by markusaksli-nc** [comment]
Hi @talent-apps 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/3507.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
