### ISSUE TITLE
🐛 [firebase_admob] Verification of void com.shatsy.admobflutter.AdmobBanner

### ISSUE THREAD

**Issue by imeDevelopers** [FirebaseExtended/flutterfire#4183]
```
[+2878 ms] W/pp.package.i(26645): Verification of void
com.shatsy.admobflutter.AdmobBanner.<init>(android.content.Context,
io.flutter.plugin.common.BinaryMessenger, int, java.util.HashMap) took 104.137ms
[+3019 ms] D/DynamitePackage(26645): Instantiating
com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
[ +751 ms] I/Ads     (26645): Use
RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("19E855AB94562A6A75B2CBF49DBE980E") to get test ads on this device.
[ +180 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +18 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)[  +65 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking,        
allowed)
[ +104 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[  +71 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed) 
[  +15 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[  +82 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking,        
allowed)
[  +94 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +14 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking,        
allowed)
[ +217 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +74 ms] W/pp.package.i(26645): Accessing hidden method Llibcore/io/Memory;->pokeByte(JB)V
(greylist, reflection, allowed)
[  +95 ms] W/pp.package.i(26645): Accessing hidden method Llibcore/io/Memory;->peekByte(J)B   
(greylist, reflection, allowed)
[ +188 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[  +91 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[ +100 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking,        
allowed)
[  +97 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[ +186 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed) 
[   +7 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)[ +115 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection,       
allowed)
[ +211 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, reflection, allowed)
[  +20 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, reflection, allowed)
[  +95 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, reflection,       
allowed)
[  +93 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, reflection, allowed)
[  +95 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, reflection,      
allowed)
[ +207 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, reflection,     
allowed)
[ +211 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[ +117 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[ +102 ms] I/DynamiteModule(26645): Considering local module
com.google.android.gms.ads.dynamite:0 and remote module
com.google.android.gms.ads.dynamite:204102000
[ +115 ms] I/DynamiteModule(26645): Selected remote version of
com.google.android.gms.ads.dynamite, version >= 204102000
[  +82 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[ +112 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[ +206 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[ +260 ms] I/AudioManager(26645): In isSpeakerphoneOn(), calling application: app.package.id[ +126 ms] D/AudioManager(26645): getStreamVolume packageName=app.package.id, index=2,
streamType=3
[ +126 ms] D/AudioManager(26645): getStreamVolume packageName=app.package.id, index=16,     
streamType=2
[ +120 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[ +172 ms] D/ColorViewRootUtil(26645): initSwipState, isDisplayCompatApp false
[ +121 ms] D/ColorViewRootUtil(26645): don't initSwipState because display 1449 is not default  
display
[   +8 ms] D/WindowManager(26645): Add to mViews: DecorView@f667fa9[MainActivity], this =       
android.view.WindowManagerGlobal@ce94ecb,pkg= app.package.id
[ +151 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)[  +73 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +17 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed) 
[  +80 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[  +18 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed) 
[ +151 ms] I/chatty  (26645): uid=10458(app.package.id) AdWorker(Defaul identical 2 lines
[ +353 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed) 
[  +86 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)[  +12 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +80 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[  +16 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[  +97 ms] D/ColorViewRootUtil(26645): nav bar mode ignore false downX 228 downY 583
mScreenHeight 1600 mScreenWidth 720 mStatusBarHeight 36 globalScale 1.125 nav mode 0 rotation 0 
event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=228.0, y[0]=583.0,        
toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0,       
edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1032421786, downTime=1032421786,        
deviceId=6, source=0x1002, displayId=0 }
[ +205 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking,        
allowed)
[  +32 ms] I/Choreographer(26645): Skipped 89 frames!  The application may be doing too much
work on its main thread.
[ +111 ms] W/pp.package.i(26645): Verification of java.lang.String hq.toString() took
130.728ms
[  +17 ms] W/pp.package.i(26645): Verification of boolean mf.a(int, android.os.Parcel,
android.os.Parcel) took 131.135ms
[  +84 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[  +86 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[  +15 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[  +57 ms] I/OpenGLRenderer(26645): Davey! duration=4050ms; Flags=1,
IntendedVsync=1032428232904058, Vsync=1032429716237332, OldestInputEvent=9223372036854775807,   
NewestInputEvent=0, HandleInputStart=1032429724222249, AnimationStart=1032429724310478,
PerformTraversalsStart=1032429725282093, DrawStart=1032432261393654,
SyncQueued=1032432263217717, SyncStart=1032432270854227,
IssueDrawCommandsStart=1032432271082196, SwapBuffers=1032432273484279,
FrameCompleted=1032432290710633, DequeueBufferDuration=354000, QueueBufferDuration=16652000,    
[ +201 ms] E/ANR_LOG (26645): >>> msg's executing time is too long
[  +75 ms] E/ANR_LOG (26645): Blocked msg = { when=-4s73ms what=0
target=android.view.Choreographer$FrameHandler
callback=android.view.Choreographer$FrameDisplayEventReceiver } , cost  = 2582 ms
[  +15 ms] E/ANR_LOG (26645): >>>Current msg List is:
[  +64 ms] E/ANR_LOG (26645): Current msg <1> = { when=-11d22h47m12s305ms what=0
target=android.view.ViewRootImpl$ViewRootHandler
callback=android.view.-$$Lambda$ViewRootImpl$7A_3tkr_Kw4TZAeIUGVlOoTcZhg }
[  +91 ms] E/ANR_LOG (26645): Current msg <2> = { when=-3s411ms what=131
target=android.app.ActivityThread$H obj=android.app.ActivityThread$ProviderRefCount@40bb4fd }   
[ +383 ms] E/ANR_LOG (26645): Current msg <3> = { when=-3s321ms what=0
target=com.google.android.gms.ads.internal.util.f
callback=com.google.android.gms.ads.nonagon.ad.event.de }
[ +521 ms] E/ANR_LOG (26645): Current msg <4> = { when=-3s292ms what=0
target=com.google.android.gms.ads.internal.util.f
callback=com.google.android.gms.ads.internal.js.e }
[ +308 ms] E/ANR_LOG (26645): Current msg <5> = { when=-3s247ms what=0 target=nc
callback=com.google.maps.api.android.lib6.impl.bq }
[  +89 ms] E/ANR_LOG (26645): Current msg <6> = { when=-3s63ms what=0
target=android.app.ActivityThread$H
callback=android.app.LoadedApk$ServiceDispatcher$RunConnection }
[ +863 ms] E/ANR_LOG (26645): Current msg <7> = { when=-2s968ms what=1
target=android.os.AsyncTask$InternalHandler obj=android.os.AsyncTask$AsyncTaskResult@2cf55f2 }  
[ +132 ms] E/ANR_LOG (26645): Current msg <8> = { when=-2s943ms what=1
target=android.os.AsyncTask$InternalHandler obj=android.os.AsyncTask$AsyncTaskResult@9a38443 }  
[ +250 ms] E/ANR_LOG (26645): Current msg <9> = { when=-2s927ms what=1
target=android.os.AsyncTask$InternalHandler obj=android.os.AsyncTask$AsyncTaskResult@bbdeac0 }  
[   +6 ms] E/ANR_LOG (26645): Current msg <10> = { when=-2s919ms what=1
target=android.os.AsyncTask$InternalHandler obj=android.os.AsyncTask$AsyncTaskResult@de3a3f9 }  
[  +96 ms] E/ANR_LOG (26645): >>>CURRENT MSG DUMP OVER<<<
[ +288 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[ +808 ms] E/ANR_LOG (26645): >>> msg's executing time is too long
[   +6 ms] E/ANR_LOG (26645): Blocked msg = { when=-7s748ms what=4
target=android.view.inputmethod.InputMethodManager$H arg1=1 } , cost  = 4537 ms
[  +13 ms] E/ANR_LOG (26645): >>>Current msg List is:
[   +9 ms] E/ANR_LOG (26645): Current msg <1> = { when=-7s629ms what=1
target=android.os.AsyncTask$InternalHandler obj=android.os.AsyncTask$AsyncTaskResult@5051fa2 }  
[  +96 ms] E/ANR_LOG (26645): Current msg <2> = { when=-7s377ms what=0
target=android.graphics.SurfaceTexture$1 }
[  +14 ms] E/ANR_LOG (26645): Current msg <3> = { when=-7s374ms what=0
target=android.graphics.SurfaceTexture$1 }
[ +816 ms] E/ANR_LOG (26645): Current msg <4> = { when=-4s789ms what=0
target=android.view.Choreographer$FrameHandler
callback=android.view.Choreographer$FrameDisplayEventReceiver }
[ +119 ms] E/ANR_LOG (26645): Current msg <5> = { when=-4s566ms what=1
target=android.os.AsyncTask$InternalHandler obj=android.os.AsyncTask$AsyncTaskResult@c1e0433 }  
[ +303 ms] E/ANR_LOG (26645): Current msg <6> = { when=-4s547ms what=1
target=android.os.AsyncTask$InternalHandler obj=android.os.AsyncTask$AsyncTaskResult@8183f0 }   
[  +99 ms] E/ANR_LOG (26645): Current msg <7> = { when=-4s514ms what=1
target=android.os.AsyncTask$InternalHandler obj=android.os.AsyncTask$AsyncTaskResult@8f87d69 }  
[ +384 ms] E/ANR_LOG (26645): Current msg <8> = { when=-4s511ms what=0 target=nc
callback=com.google.maps.api.android.lib6.gmm6.api.b }
[  +91 ms] E/ANR_LOG (26645): Current msg <9> = { when=-4s511ms what=0 target=nc
callback=com.google.maps.api.android.lib6.impl.y }
[  +14 ms] E/ANR_LOG (26645): Current msg <10> = { when=-3s323ms what=1 target=oL
obj=https://googleads.g.doubleclick.net/getconfig/pubsetting?app_name=app.package.id&client=ca-app-pub-7719109668755974&admob_appcc=7955697597 }
[ +322 ms] E/ANR_LOG (26645): >>>CURRENT MSG DUMP OVER<<<
[ +117 ms] I/LooperMessageSuperviser(26645): NoSuchMethodException :
android.app.IActivityManager.sendTheiaEvent [class java.lang.String]
[ +735 ms] W/System.err(26645): java.lang.NoSuchMethodException:
android.app.IActivityManager.sendTheiaEvent [class java.lang.String]
[ +457 ms] W/System.err(26645):         at java.lang.Class.getMethod(Class.java:2072)
[ +105 ms] W/System.err(26645):         at java.lang.Class.getDeclaredMethod(Class.java:2050)
[  +18 ms] W/System.err(26645):         at
android.os.LooperMessageSuperviser.callDeclaredMethod(LooperMessageSuperviser.java:155)
[ +145 ms] W/System.err(26645):         at
android.os.LooperMessageSuperviser.endLooperMessage(LooperMessageSuperviser.java:112)
[  +99 ms] W/System.err(26645):         at android.os.Looper.loop(Looper.java:263)
[  +16 ms] W/System.err(26645):         at android.app.ActivityThread.main(ActivityThread.java:7853)
[ +201 ms] W/System.err(26645):         at java.lang.reflect.Method.invoke(Native Method)
[  +11 ms] W/System.err(26645):         at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[ +223 ms] W/System.err(26645):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
[ +164 ms] I/Choreographer(26645): Skipped 345 frames!  The application may be doing too much
work on its main thread.
[ +357 ms] D/SharedPreferencesImpl(26645): Time required to fsync
/data/user/0/app.package.id/shared_prefs/FlutterSharedPreferences.xml: [<1: 0, <2: 0, <4:   
70, <8: 495, <16: 1961, <32: 229, <64: 31, <128: 9, <256: 6, <512: 1, <1024: 0, <2048: 0, <4096:0, <8192: 0, <16384: 0, >=16384: 0]
[ +267 ms] D/ColorViewRootUtil(26645): initSwipState, isDisplayCompatApp false
[ +259 ms] D/ColorViewRootUtil(26645): don't initSwipState because display 1449 is not default
display
[ +296 ms] I/Choreographer(26645): Skipped 8 frames!  The application may be doing too much workon its main thread.
[ +324 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[ +102 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
[ +144 ms] I/Ads     (26645): Ad failed to load : 3
[   +7 ms] I/Choreographer(26645): Skipped 1 frames!  The application may be doing too much workon its main thread.
[+3516 ms] E/ANR_LOG (26645): >>> msg's executing time is too long
[   +4 ms] E/ANR_LOG (26645): Blocked msg = { when=-1s926ms what=4
target=android.view.inputmethod.InputMethodManager$H } , cost  = 1926 ms
[  +10 ms] E/ANR_LOG (26645): >>>Current msg List is:
[   +3 ms] E/ANR_LOG (26645): Current msg <1> = { when=-1s925ms what=3
target=android.view.inputmethod.InputMethodManager$H arg1=7528 arg2=3 }
[   +7 ms] E/ANR_LOG (26645): Current msg <2> = { when=-1s892ms what=0
target=android.graphics.SurfaceTexture$1 }
[   +5 ms] E/ANR_LOG (26645): Current msg <3> = { when=-1s888ms what=0
target=android.graphics.SurfaceTexture$1 }
[ +285 ms] E/ANR_LOG (26645): Current msg <4> = { when=-1s817ms what=4
target=android.view.inputmethod.InputMethodManager$H arg1=1 }
[ +126 ms] E/ANR_LOG (26645): Current msg <5> = { when=-1s679ms what=0 target=qb
obj=com.google.android.gms.gass.START }
[ +318 ms] E/ANR_LOG (26645): Current msg <6> = { when=-437ms what=0 target=qb
obj=com.google.android.gms.ads.service.START }
[ +270 ms] E/ANR_LOG (26645): Current msg <7> = { when=+564ms what=0
target=com.google.android.gms.internal.measurement.zzm
callback=com.google.android.gms.measurement.internal.zzah }
[ +668 ms] E/ANR_LOG (26645): Current msg <8> = { when=+10s493ms what=0
target=com.google.android.gms.ads.internal.util.f
callback=com.google.android.gms.ads.internal.cache.a }
[ +413 ms] E/ANR_LOG (26645): Current msg <9> = { when=+16s256ms what=0
target=android.os.Handler callback=aR }
[ +496 ms] E/ANR_LOG (26645): >>>CURRENT MSG DUMP OVER<<<
[  +54 ms] I/Choreographer(26645): Skipped 1 frames!  The application may be doing too much workon its main thread.
[ +197 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[   +8 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking,        
allowed)
[  +11 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[ +536 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[ +444 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)[ +360 ms] I/pp.package.i(26645): Background concurrent copying GC freed 163489(7880KB)       
AllocSpace objects, 140(7148KB) LOS objects, 49% free, 20MB/40MB, paused 129us total 224.624ms  
[+1795 ms] W/pp.package.i(26645): Accessing hidden method
Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[+4486 ms] I/Choreographer(26645): Skipped 1 frames!  The application may be doing too much workon its main thread.
[+6700 ms] E/ANR_LOG (26645): >>> msg's executing time is too long
[   +4 ms] E/ANR_LOG (26645): Blocked msg = { when=-1s657ms what=0 target=qb
obj=com.google.android.gms.ads.service.CACHE } , cost  = 1656 ms
[   +5 ms] E/ANR_LOG (26645): >>>Current msg List is:
[   +4 ms] E/ANR_LOG (26645): Current msg <1> = { when=-1s592ms what=0
target=android.graphics.SurfaceTexture$1 }
[ +120 ms] E/ANR_LOG (26645): Current msg <2> = { when=-1s588ms what=0
target=android.graphics.SurfaceTexture$1 }
[  +10 ms] E/ANR_LOG (26645): Current msg <3> = { when=-922ms what=0 target=android.os.Handler
callback=aR }
[ +505 ms] E/ANR_LOG (26645): >>>CURRENT MSG DUMP OVER<<<
[ +420 ms] I/Choreographer(26645): Skipped 22 frames!  The application may be doing too much
work on its main thread.
[+5093 ms] D/ColorViewRootUtil(26645): nav bar mode ignore false downX 367 downY 849
mScreenHeight 1600 mScreenWidth 720 mStatusBarHeight 36 globalScale 1.125 nav mode 0 rotation 0 
event MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=367.0, y[0]=849.0,        
toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0,       
edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=1032470140, downTime=1032470140,        
deviceId=6, source=0x1002, displayId=0 }
[ +975 ms] D/SharedPreferencesImpl(26645): Time required to fsync
/data/user/0/app.package.id/shared_prefs/FlutterSharedPreferences.xml: [<1: 0, <2: 0, <4:   
70, <8: 497, <16: 1963, <32: 238, <64: 41, <128: 14, <256: 9, <512: 1, <1024: 0, <2048: 0,      
<4096: 1, <8192: 0, <16384: 0, >=16384: 0]
[+3503 ms] Service protocol connection closed.
[  +33 ms] Lost connection to device.
```

**Comment by imeDevelopers** [comment]
package version: 0.10.0+2 #depends on firebase_core so i can't use latest because firebase_core have problem duplicated classes so i use firebase_core package version: 0.5.0+1 [#look at this](https://github.com/FirebaseExtended/flutterfire/issues/4141#issue-745094120)

dev system v: windows 10
device: realme 5
android 10
flutter v: 1.22.4

**Comment by markusaksli-nc** [comment]
Hi @imeDevelopers 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you
