### ISSUE TITLE
🐛 [Firebase Auth] Crash

### ISSUE THREAD

**Issue by JCKodel** [FirebaseExtended/flutterfire#4240]
## Bug report

**Describe the bug**
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object, io.flutter.plugin.common.MethodChannel$Result)' on a null object reference
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.lambda$null$0$FlutterFirebaseAuthPlugin(FlutterFirebaseAuthPlugin.java:513)
       at io.flutter.plugins.firebase.auth.-$$Lambda$FlutterFirebaseAuthPlugin$tWHRqndMAmD1Pw4Ghd6GrE-h3DA.onAuthStateChanged(:4)
       at com.google.firebase.auth.zzj.run(com.google.firebase:firebase-auth@@19.3.1:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage(com.google.firebase:firebase-auth@@19.3.1:6)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6704)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:916)

### Steps to reproduce
Not sure. > 500k devices, 831 events with this crash.

**Comment by markusaksli-nc** [comment]
Hi @JCKodel 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/3507.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
