### ISSUE TITLE
🐛 [firebase_storage] can't upload file

### ISSUE THREAD

**Issue by marcoberetta96** [FirebaseExtended/flutterfire#4288]
## Bug report

**Describe the bug**
Can't upload file on my (single bucket) after the changing firebase_storage from 4.0.0 to 5.1.0

### Steps to reproduce
```
var storage = FirebaseStorage.instance.ref("gs://flutterapp-4defc.appspot.com");
firebase_storage.Reference ref = storage.child('test.mp3');
firebase_storage.UploadTask uploadTask = ref.putFile(audioFile);
print(ref.storage.bucket);
```

### Output
```
I/flutter (12321): flutterapp-4defc.appspot.com
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): java.lang.IllegalArgumentException: Please use a gs:// URL for your Firebase Storage bucket.
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at com.google.firebase.storage.FirebaseStorage.getInstance(FirebaseStorage.java:145)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at com.google.firebase.storage.FirebaseStorage.getInstance(FirebaseStorage.java:101)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.onMethodCall(FirebaseStoragePlugin.java:77)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:693)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#plugins.flutter.io/firebase_storage(12321): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

### Flutter doctor
```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.221, on Linux, locale en_US.UTF-8)
    • Flutter version 1.24.0-8.0.pre.221 at /home/marco/flutter
    • Framework revision c7f092515c (3 weeks ago), 2020-11-12 13:54:03 -0800
    • Engine revision c5c7e83b9e
    • Dart version 2.12.0 (build 2.12.0-31.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /mnt/DATA/Utils/Sdk/
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
    • Linux (desktop)                    • linux         • linux-x64   • Linux
```

**Comment by marcoberetta96** [comment]
Solved by running flutter clean and rebuilding all
