### ISSUE TITLE
🐛 [firebase_storage] 5.1.0 causes crashes on Android.

### ISSUE THREAD

**Issue by njovy** [FirebaseExtended/flutterfire#4334]
## Bug report

**Describe the bug**
I updated firebase_storage plugin to 5.1.0 from 4.x last week and new crashes are getting reported with this new update. Unfortunately, I am not able to reproduce this issue and what causes this at the moment. One thing I can guarantee is that these two crash reports are getting received with a plugin update.

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=23; index=23
       at android.util.ContainerHelpers.binarySearch(ContainerHelpers.java:28)
       at android.util.SparseArray.delete(SparseArray.java:133)
       at android.util.SparseArray.remove(SparseArray.java:165)
       at io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.destroy(FlutterFirebaseStorageTask.java:142)
       at io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.lambda$startTaskWithMethodChannel$8(FlutterFirebaseStorageTask.java:261)
       at io.flutter.plugins.firebase.storage.-$$Lambda$FlutterFirebaseStorageTask$8fk18gdKgl7Z6GfjppLSHWRYM0w.onSuccess(-.java:6)
       at com.google.firebase.storage.StorageTask.lambda$new$0(StorageTask.java:123)
       at com.google.firebase.storage.StorageTask$$Lambda$1.a(StorageTask.java:6)
       at com.google.firebase.storage.TaskListenerImpl.lambda$onInternalStateChanged$2(TaskListenerImpl.java:90)
       at com.google.firebase.storage.TaskListenerImpl$$Lambda$3.run(TaskListenerImpl.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {app.ranchat.talk/app.ranchat.talk.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5456)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5493)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8154)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by Salakar** [comment]
I can't seem to reproduce this myself but I can add some safeguards for it at least to stop it happening - will push this up tomorrow.

**Comment by njovy** [comment]
@Salakar It hasn't been pushed it yet. Any chance to fix this soon? I am getting a lot of reports because of this.

**Comment by njovy** [comment]
Caused by java.lang.ArrayIndexOutOfBoundsException
length=11; index=11
```java

android.util.SparseArray.gc (SparseArray.java:217)
android.util.SparseArray.size (SparseArray.java:270)
io.flutter.plugins.firebase.storage.FlutterFirebaseStorageTask.cancelInProgressTasks (FlutterFirebaseStorageTask.java:67)
io.flutter.plugins.firebase.storage.FlutterFirebaseStoragePlugin.onDetachedFromEngine (FlutterFirebaseStoragePlugin.java:139)
io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove (FlutterEnginePluginRegistry.java:252)
io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove (FlutterEnginePluginRegistry.java:260)
io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll (FlutterEnginePluginRegistry.java:268)
io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy (FlutterEnginePluginRegistry.java:112)
io.flutter.embedding.engine.FlutterEngine.destroy (FlutterEngine.java:365)
io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach (FlutterActivityAndFragmentDelegate.java:528)
io.flutter.embedding.android.FlutterActivity.onDestroy (FlutterActivity.java:577)
android.app.Activity.performDestroy (Activity.java:8225)
android.app.Instrumentation.callActivityOnDestroy (Instrumentation.java:1342)
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:5441)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:5493)
android.app.servertransaction.DestroyActivityItem.execute (DestroyActivityItem.java:44)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2267)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:8154)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
```

@Salakar Attached is a report from other app.

**Comment by DeanPack** [comment]
I'm getting this same issue on my app. Here is the stack:
Caused by java.lang.ArrayIndexOutOfBoundsException: length=95; index=95
       at android.util.SparseArray.gc(SparseArray.java:213)
       at android.util.SparseArray.size(SparseArray.java:270)
       at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.removeEventListeners(FlutterFirebaseFirestorePlugin.java:3)
       at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.onDetachedFromEngine(FlutterFirebaseFirestorePlugin.java)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:118)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.remove(FlutterEnginePluginRegistry.java:16)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:11)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:10)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:9)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:90)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:10)
       at android.app.Activity.performDestroy(Activity.java:8123)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1388)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5250)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5294)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:230)
       at android.app.ActivityThread.main(ActivityThread.java:7816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by njovy** [comment]
@Salakar I observed this issue when my app tries to load a bunch of images in grid view(3x3). It just kills the app immediately upon this exception. I believe this issue appears because of concurrency. That's why it doesn't always happen because my app caches images once it's loaded from firebase storage.

**Comment by njovy** [comment]
@Salakar 
![Screen Shot 2020-12-16 at 8 37 40 AM](https://user-images.githubusercontent.com/1792070/102285713-2c7ece80-3f7a-11eb-8fde-740697bc2e62.png)

**Comment by njovy** [comment]
@Salakar @markusaksli-nc Please assign someone else if you can't fix this.

**Comment by britannio** [comment]
This is the most common way my app is crashing although, according to Firebase Crashlytics, 94% of the time, the app is in the background (out of 18 events across 5 devices).
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.invokeStorageTaskEvent(FirebaseStoragePlugin.java:8)
       at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin.access$100(FirebaseStoragePlugin.java)
       at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin$15.onProgress(FirebaseStoragePlugin.java:7)
       at io.flutter.plugins.firebase.storage.FirebaseStoragePlugin$15.onProgress(FirebaseStoragePlugin.java:2)
       at com.google.firebase.storage.StorageTask$$Lambda$7.raise(StorageTask.java:4)
       at com.google.firebase.storage.TaskListenerImpl.lambda$onInternalStateChanged$2(TaskListenerImpl.java:2)
       at com.google.firebase.storage.TaskListenerImpl$$Lambda$3.run(TaskListenerImpl.java:6)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:227)
       at android.app.ActivityThread.main(ActivityThread.java:7802)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
```

**Comment by Salakar** [comment]
This should no longer be an issue on the latest release.

**Comment by canturkay** [comment]
I'm still facing this issue even with beta version 1.25.0-8.3.pre, only shows up on Crashlytics though.
