### ISSUE TITLE
[firebase_database 4.4.0] W/ConnectionTracker( 6919): java.lang.IllegalArgumentException: Service not registered:

### ISSUE THREAD

**Issue by pqtrong17** [FirebaseExtended/flutterfire#4343]
I use `firebase database realtime` and get an error:

```
W/ConnectionTracker( 6919): Exception thrown while unbinding
W/ConnectionTracker( 6919): java.lang.IllegalArgumentException: Service not registered: lu@6e411f3
W/ConnectionTracker( 6919): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1671)
W/ConnectionTracker( 6919): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1781)
W/ConnectionTracker( 6919): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:730)
W/ConnectionTracker( 6919): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):1)
W/ConnectionTracker( 6919): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):2)
W/ConnectionTracker( 6919): 	at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):9)
W/ConnectionTracker( 6919): 	at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):3)
W/ConnectionTracker( 6919): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):3)
W/ConnectionTracker( 6919): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
W/ConnectionTracker( 6919): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 6919): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516065@20.45.16 (100400-0):5)
```
How to fix it?

**Comment by pqtrong17** [comment]
Any update, please?

**Comment by markusaksli-nc** [comment]
Hi @pqtrong17 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4090.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
