### ISSUE TITLE
🐛 [firebase_performance: 0.4.3] PlatformException when the url contains percent-encoding reserved characters

### ISSUE THREAD

**Issue by shinsenter** [FirebaseExtended/flutterfire#4346]
## Bug report

**Describe the bug**
PlatformException when the url contains percent-encoding reserved characters, such as: `%21`, `%23`, `%24`, `%25`, `%26`, `%27`, `%28`, `%29`, `%2A`, `%2B`, `%2C`, `%2F`, `%3A`, `%3B`, `%3D`, `%3F`, `%40`, `%5B`, `%5D`.

### Steps to reproduce

1. Create an HttpMetric instance with url that contains percent-encoding reserved characters
2. Run the snippet
3. See error or incorrect behavior

### Expected behavior

No error.

---

## Additional context

<details><summary>Sample code</summary>

```

String url = 'https://google.com/?q=1%2C2%2C3';
HttpMetric metric = FirebasePerformance.instance.newHttpMetric(url, HttpMethod.Get); // <- Error

```

</details>

<details><summary>Error message</summary>

```
E/flutter (27457): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Format specifier '%2C', null, java.util.MissingFormatArgumentException: Format specifier '%2C'
E/flutter (27457):      at java.util.Formatter.format(Formatter.java:2523)
E/flutter (27457):      at java.util.Formatter.format(Formatter.java:2459)
E/flutter (27457):      at java.lang.String.format(String.java:2911)
E/flutter (27457):      at com.google.firebase.perf.logging.AndroidLogger.info(AndroidLogger.java:103)
E/flutter (27457):      at com.google.firebase.perf.metrics.HttpMetric.<init>(HttpMetric.java:65)
E/flutter (27457):      at com.google.firebase.perf.FirebasePerformance.newHttpMetric(FirebasePerformance.java:433)
E/flutter (27457):      at io.flutter.plugins.firebaseperformance.FlutterFirebasePerformance.newHttpMetric(FlutterFirebasePerformance.java:95)
E/flutter (27457):      at io.flutter.plugins.firebaseperformance.FlutterFirebasePerformance.onMethodCall(FlutterFirebasePerformance.java:60)
E/flutter (27457):      at io.flutter.plugins.firebaseperformance.FirebasePerformancePlugin.onMethodCall(FirebasePerformancePlugin.java:61)
E/flutter (27457):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (27457):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (27457):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (27457):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (27457):      at android.os.MessageQueue.next(MessageQueue.java:339)
E/flutter (27457):      at android.os.Looper.loop(Looper.java:314)
E/flutter (27457):      at android.app.ActivityThread.main(ActivityThread.java:7418)
E/flutter (27457):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (27457):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (27457):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
E/flutter (27457): )
E/flutter (27457): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (27457): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (27457): <asynchronous suspension>
E/flutter (27457): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (27457): #3      FirebasePerformance.newHttpMetric (package:firebase_performance/src/firebase_performance.dart:76:33)
```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.19042.630], locale ja-JP)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.   
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
$ flutter pub deps -- --style=compact
The ".dart_tool/package_config.json" file is not recognized by "pub" version, please run "pub get".
pub finished with exit code 65
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @shinsenter 
I'm not seeing this on the latest master `1.25.0-5.0.pre.91` with `firebase_performance: ^0.4.3` and `http: ^0.12.2`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.25.0-5.0.pre.91, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.25.0-5.0.pre.91 at C:\Development\flutter_master
    • Framework revision 7dade22f25 (20 hours ago), 2020-12-06 21:34:04 +0530
    • Engine revision 6491c7518f
    • Dart version 2.12.0 (build 2.12.0-120.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.5981.155
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```
</details>
<details>
 <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

import 'package:firebase_performance/firebase_performance.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Performance example",
      home: Scaffold(
        appBar: AppBar(
          title: const Text("Performance example"),
        ),
        body: Center(
          child: RaisedButton(
            child: const Text("Create metric"),
            onPressed: () {
              HttpMetric metric = FirebasePerformance.instance.newHttpMetric('https://google.com/?q=1%2C2%2C3', HttpMethod.Get);
              print(metric.url);
            },
          ),
        ),
      ),
    );
  }
}
```
</details>

```
D/ViewRootImpl@6ee7591[MainActivity](15694): ViewPostIme pointer 0
D/ViewRootImpl@6ee7591[MainActivity](15694): ViewPostIme pointer 1
I/flutter (15694): https://google.com/?q=1%2C2%2C3
```
What version of `firebase_performance` are using? Your `flutter pub deps -- --style=compact` output only points to a config issue with your Flutter SDK.
Thank you

**Comment by shinsenter** [comment]
@markusaksli-nc 
I am using firebase_performance: 0.4.3 (on the issue title) and lastest stable version of Flutter (1.22.4).

So far, the HttpMetrit works well on iOS.
