### ISSUE TITLE
🐛 [firebase_analytics] Cannot pass List inside logEvent parameters

### ISSUE THREAD

**Issue by monisnap-julien** [FirebaseExtended/flutterfire#4353]
## Bug report

**Describe the bug**
When passing an object of dart type `List` to the `logEvent` function, it causes an error due to passing an object that is converted to `ArrayList` in Java (Android side). The following is logged in the console :

```
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): java.lang.IllegalArgumentException: Unsupported value type: java.util.ArrayList
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at io.flutter.plugins.firebaseanalytics.FirebaseAnalyticsPlugin.createBundleFromMap(FirebaseAnalyticsPlugin.java:188)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at io.flutter.plugins.firebaseanalytics.FirebaseAnalyticsPlugin.handleLogEvent(FirebaseAnalyticsPlugin.java:118)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at io.flutter.plugins.firebaseanalytics.FirebaseAnalyticsPlugin.onMethodCall(FirebaseAnalyticsPlugin.java:84)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#plugins.flutter.io/firebase_analytics(20572): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (20572): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, Unsupported value type: java.util.ArrayList, null, java.lang.IllegalArgumentException: Unsupported value type: java.util.ArrayList
```

### Steps to reproduce

1. Call the function `logEvent` with `begin_checkout` as `event` and the following object in `parameters` :
```
{
  currency: 'USD',
  items: []
}
```

2. You should see the same error as described before in the console

### Expected behavior

We should be able to pass `List` to this function, in order to send the BEGIN_CHECKOUT event (described in Firebase analytics documentation [here](https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event.html#BEGIN_CHECKOUT) )

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H15 darwin-x64, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
 
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.51.1)
[✓] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.4
monisnap_v2 2.0.0+21

dependencies:
- app_settings 4.0.4 [flutter]
- apple_sign_in 0.1.0 [flutter]
- cached_network_image 2.3.2+1 [flutter flutter_cache_manager octo_image]
- clipboard 0.1.2+8 [flutter]
- contacts_service 0.4.6 [flutter collection quiver]
- cupertino_icons 1.0.0
- device_info 0.4.2+9 [flutter device_info_platform_interface]
- diacritic 0.1.1
- dio 3.0.10 [http_parser path]
- facebook_app_events 0.7.1 [flutter]
- file_picker 2.0.13 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 6.3.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.1+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- flare_flutter 2.0.6 [flutter flare_dart meta]
- flip_card 0.4.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_custom_tabs 0.6.0 [flutter url_launcher]
- flutter_dotenv 2.1.0 [flutter meta]
- flutter_google_places 0.2.6 [flutter rxdart google_maps_webservice http]
- flutter_html 1.1.1 [html csslib css_colors video_player chewie webview_flutter chewie_audio flutter_svg flutter]
- flutter_inappwebview 4.0.0+4 [flutter uuid mime]
- flutter_libphonenumber 0.3.9 [flutter devicelocale]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_picker 1.1.5 [flutter]
- flutter_speed_dial 1.2.5 [flutter]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- get_it 4.0.4 [async meta]
- google_maps_webservice 0.0.18 [http meta]
- google_sign_in 4.5.5 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- intl 0.16.1 [path]
- json_annotation 3.1.0
- keyboard_visibility 0.5.6 [flutter]
- libphonenumber 1.0.2 [flutter meta]
- logging 0.11.4
- onesignal_flutter 2.6.1 [flutter]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- provider 4.3.2+2 [flutter nested collection]
- random_color 1.0.5 [flutter]
- rive 0.0.7 [flutter graphs meta]
- scratcher 1.4.0 [flutter]
- shake 0.1.0 [sensors flutter]
- share 0.6.5+4 [meta mime flutter]
- shared_preferences 0.5.12+2 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 1.1.2 [flutter]
- sms_autofill 1.2.6 [pin_input_text_field flutter]
- url_launcher 5.7.7 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- uuid 2.2.2 [crypto convert]
- webview_flutter 1.0.5 [flutter]

dev dependencies:
- build_runner 1.10.3 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- dotted_border 1.0.6 [flutter path_drawing]
- flutter_launcher_icons 0.7.5 [image args yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 3.5.0 [analyzer build build_config json_annotation meta path source_gen]

transitive dependencies:
- _fe_analyzer_shared 11.0.0 [meta]
- analyzer 0.40.4 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.5.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.4.2 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.0.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- chewie 0.12.0 [video_player cupertino_icons wakelock flutter]
- chewie_audio 1.1.1 [video_player cupertino_icons flutter]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- css_colors 1.0.2 [flutter]
- csslib 0.16.2 [source_span]
- dart_style 1.3.8 [analyzer args path source_span]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- devicelocale 0.3.3 [flutter]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.2 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.1 [flutter meta collection firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flare_dart 2.3.4
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 1.4.2 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 0.2.0
- html 0.14.0+4 [csslib source_span]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.18 [archive xml meta]
- import_js_library 1.0.2 [flutter html flutter_web_plugins js]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.21 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- pin_input_text_field 3.1.1 [flutter]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.3 [matcher meta]
- rxdart 0.24.1
- sensors 0.4.2+6 [flutter]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.1+2 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+2 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+3 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- vector_math 2.1.0-nullsafety.3
- video_player 1.0.1 [meta video_player_platform_interface video_player_web flutter]
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4+1 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock 0.2.1+1 [flutter meta wakelock_platform_interface wakelock_web]
- wakelock_platform_interface 0.1.0+1 [flutter meta]
- wakelock_web 0.1.0+3 [flutter flutter_web_plugins import_js_library js wakelock_platform_interface]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by monisnap-julien** [comment]
On Android side, I've managed to make it work by modifying locally the `FirebaseAnalyticsPlugin.java` file adding an `else if` statement in the `createBundleFromMap` function. It now look like this : 

```java
private static Bundle createBundleFromMap(Map<String, Object> map) {
    if (map == null) {
      return null;
    }

    Bundle bundle = new Bundle();
    for (Map.Entry<String, Object> jsonParam : map.entrySet()) {
      final Object value = jsonParam.getValue();
      final String key = jsonParam.getKey();
      if (value instanceof String) {
        bundle.putString(key, (String) value);
      } else if (value instanceof Integer) {
        bundle.putInt(key, (Integer) value);
      } else if (value instanceof Long) {
        bundle.putLong(key, (Long) value);
      } else if (value instanceof Double) {
        bundle.putDouble(key, (Double) value);
      } else if (value instanceof Boolean) {
        bundle.putBoolean(key, (Boolean) value);
      
      // Added below ⬇️
      } else if (value instanceof ArrayList) {
        Bundle[] myBundleArray = new Bundle[((ArrayList) value).size()];
        for (int i = 0; i < ((ArrayList) value).size(); i++)
        {
          Map<String, Object> test = ((Map<String, Object>) ((ArrayList) value).get(i));
          myBundleArray[i] = createBundleFromMap(test);
        }

        bundle.putParcelableArray(key, myBundleArray);

      // Added above ⬆️
      } else {
        throw new IllegalArgumentException(
            "Unsupported value type: " + value.getClass().getCanonicalName());
      }
    }
    return bundle;
  }
```

Do you think it could be added in the library to fix this issue ? I will also test on an iOS device to see if the the problem is specific to Android.

**Comment by darshankawar** [comment]
@monisnap-julien 
There's similar open issue describing your case, https://github.com/FirebaseExtended/flutterfire/issues/2835
Does your issue resemble it ?

**Comment by monisnap-julien** [comment]
@darshankawar
Yes that is the same issue indeed.

**Comment by darshankawar** [comment]
@monisnap-julien 
You may need to follow-up in that issue and ask for any updates there.
I am going ahead and closing this as duplicate. If you disagree, write in comments and I'll reopen it.
Thanks.
