### ISSUE TITLE
firebase_auth signInWithEmailAndPassword NullPointerException

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#436]
Hi,

i fail to signin users in my sample app. I activated the auth method email in firebase and also imported the services json (working already perfect with firestore)  

Calling this firebase method returns the exception you can see below:
`await FirebaseAuth.instance.signInWithEmailAndPassword(email: _email, password: _password);`

Exception:
```
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInWithCredential(FirebaseAuthPlugin.java:405)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:107)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/firebase_auth(12545): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (12545): Error: PlatformException(error, Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase.auth.AuthCredential)' on a null object reference, null)
W/IInputConnectionWrapper(12545): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(12545): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(12545): getTextAfterCursor on inactive InputConnection
```
```yml
google_sign_in: ^4.0.1+1
firebase_auth: ^0.8.1+1
```
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-DE)
    • Flutter version 1.0.0 at /Users/cm/flutter/sdk
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/cm/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)


```

**Comment by pinkfish** [comment]
Is there any way to fix this?  I am getting it too.  I think it might be because my user has google sigin and email/auth credentials setup.

i am also getting a tight loop from somewhere where it keeps saying:
D/FirebaseAuth(23800): Notifying id token listeners about a sign-out event.
D/FirebaseAuth(23800): Notifying auth state listeners about a sign-out event.

Wondering if it is perhaps a client auth issue?  It keeps telling me about the null user over and over again.
