### ISSUE TITLE
firebase_ml_vision: 0.5.1+1 does not work

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#437]
## Steps to Reproduce

1. Add `firebase_ml_vision: 0.5.1+1` to `pubspec.yaml` along with `firebase_core: ^0.3.0+2`, `firebase_auth: ^0.8.1+1` and `firebase_messaging: 3.0.1`
2. Run App `flutter clean`, `flutter packages get`, `flutter run ..`
3. I also tried `cd ios && pod update`, `pod install` and `pod update GoogleAppMeasurement`

## Logs

`flutter run` output : 
```
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A firebase_ml_vision
      - FBSDKLoginKit
      - Firebase
      - Flutter
      - GoogleAnalytics
      - camera
      - device_info
      - firebase_auth
      - firebase_core
      - firebase_messaging
      - flutter_facebook_login
      - google_sign_in
      - image_picker
      - multi_image_picker
      - path_provider
      - shared_preferences

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    -> Fetching podspec for `firebase_ml_vision` from `.symlinks/plugins/firebase_ml_vision/ios`
    -> Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
    -> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
      In snapshot (Podfile.lock):
        GoogleAppMeasurement (= 5.5.0)

      In Podfile:
        firebase_ml_vision (from `.symlinks/plugins/firebase_ml_vision/ios`) was resolved to 0.1.1, which depends on
          GoogleAppMeasurement (~> 5.3.0)

    It seems like you've changed the constraints of dependency `GoogleAppMeasurement` inside your development pod `firebase_ml_vision`.
    You should run `pod update GoogleAppMeasurement` to apply changes you've made.

    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'

Error running pod install
Error launching application on iPhone X.
```

`pod update GoogleAppMeasurement` and `pod update` output:

```
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
Fetching podspec for `firebase_ml_vision` from `.symlinks/plugins/firebase_ml_vision/ios`
Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 0.0.1, which depends on
      Firebase/Core was resolved to 5.16.0, which depends on
        FirebaseAnalytics (= 5.5.0) was resolved to 5.5.0, which depends on
          GoogleAppMeasurement (= 5.5.0)

    firebase_ml_vision (from `.symlinks/plugins/firebase_ml_vision/ios`) was resolved to 0.1.1, which depends on
      GoogleAppMeasurement (~> 5.3.0)
```

`pod install` output:
```
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
Fetching podspec for `firebase_ml_vision` from `.symlinks/plugins/firebase_ml_vision/ios`
Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In snapshot (Podfile.lock):
    GoogleAppMeasurement (= 5.5.0)

  In Podfile:
    firebase_ml_vision (from `.symlinks/plugins/firebase_ml_vision/ios`) was resolved to 0.1.1, which depends on
      GoogleAppMeasurement (~> 5.3.0)

It seems like you've changed the constraints of dependency `GoogleAppMeasurement` inside your development pod `firebase_ml_vision`.
You should run `pod update GoogleAppMeasurement` to apply changes you've made.
```

```
flutter doctor -v

[✓] Flutter (Channel master, v1.2.1-pre.10, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 1.2.1-pre.10 at /Users/jonathansudhakar/projects/flutter
    • Framework revision bb5663d2d8 (3 weeks ago), 2019-01-27 09:43:09 -0800
    • Engine revision 9b6d5031a3
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 a5030ed92f)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jonathansudhakar/Library/Android/sdk
    • Android NDK at /Users/jonathansudhakar/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone X • 27940593-9086-4C39-BE4B-CDF2E880B41F • ios • iOS 12.1 (simulator)

• No issues found!

```

pubspec.yaml

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: 1.0.1
  image_picker: 0.5.0
  multi_image_picker: ^3.0.11
  shared_preferences: 0.5.0
  flutter_facebook_login: 1.2.0
  google_sign_in: ^4.0.0
  font_awesome_flutter: ^8.2.0
  device_info: ^0.4.0
  http: ^0.12.0+1
  camera: ^0.3.0
  path_provider: 0.5.0+1
  uuid: 2.0.0
  autocomplete_textfield: 1.6.4
  flutter_rating: ^0.0.2

  firebase_core: ^0.3.0+2
  firebase_auth: ^0.8.1+1
  firebase_messaging: 3.0.1
  firebase_ml_vision: 0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
```

**Comment by leafs1** [comment]
How would I fix this issue on a Windows machine?
