### ISSUE TITLE
🐛 [firebase_dynamic_links] No implementation found for method FirebaseDynamicLinks#getInitialLink

### ISSUE THREAD

**Issue by Eufranio** [FirebaseExtended/flutterfire#4378]
## Bug report

**Describe the bug**
When launching my app, I constantly get errors saying that `MissingPluginException(No implementation found for method FirebaseDynamicLinks#getInitialLink on channel plugins.flutter.io/firebase_dynamic_links)`. **This is happening on flutter web.**

Full stacktrace:
```
Error: MissingPluginException(No implementation found for method FirebaseDynamicLinks#getInitialLink on channel plugins.flutter.io/firebase_dynamic_links)
    at Object.throw_ [as throw] (http://localhost:5000/dart_sdk.js:4348:11)
    at MethodChannel._invokeMethod (http://localhost:5000/packages/flutter/src/services/system_channels.dart.lib.js:943:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:5000/dart_sdk.js:37956:33
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37810:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:5000/dart_sdk.js:32771:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33319:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33357:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:33199:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:33222:35)
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:38071:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:38077:13)
    at http://localhost:5000/dart_sdk.js:33574:9
```

### Steps to reproduce

1. Install the latest version of firebase_dynamic_links

### Expected behavior

The plugin should load with no errors.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [versÃ£o 10.0.19041.630], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0-29.10.beta
Flutter SDK 1.24.0-10.2.pre
MoradaDosSonhos 1.0.0+8a

dependencies:
- apple_sign_in 0.1.0 [flutter]
- auto_size_text 2.1.0 [flutter]
- bloc_pattern 2.5.1 [flutter]
- carousel_slider 2.3.1 [flutter]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cpfcnpj 1.0.3
- cupertino_icons 1.0.1+1
- currency_text_input_formatter 0.3.1 [flutter intl]
- datetime_picker_formfield 1.0.0 [flutter intl]
- device_info 1.0.0 [flutter device_info_platform_interface]
- dio 3.0.10 [http_parser path]
- faker 1.3.0
- file_picker 2.1.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 6.3.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.4 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_dynamic_links 0.6.3 [flutter firebase_core]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- firebase_storage 5.2.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_absolute_path 1.0.6 [flutter]
- flutter_appavailability 0.0.21 [flutter]
- flutter_auth_buttons 0.10.0 [flutter]
- flutter_automation 1.4.0 [flutter args yaml path http]
- flutter_device_locale 0.4.0 [flutter flutter_web_plugins plugin_platform_interface]
- flutter_google_places 0.2.6 [flutter rxdart google_maps_webservice http]
- flutter_local_notifications 3.0.2 [flutter platform flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_pdfview 1.0.3+8 [flutter]
- geocoding 1.0.5 [flutter geocoding_platform_interface url_launcher]
- geolocator 6.1.13 [flutter geolocator_platform_interface]
- get_it 5.0.1 [async meta]
- google_fonts 1.1.1 [flutter http path_provider crypto pedantic]
- google_maps_flutter 1.0.6 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_sign_in 4.5.6 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- image_picker 0.6.7+14 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- lipsum 1.0.1
- mailer 3.2.1 [async logging intl mime path pedantic]
- mask_text_input_formatter 1.1.0 [flutter]
- multi_image_picker 4.7.14 [flutter meta]
- package_info 0.4.3+2 [flutter]
- password_strength 0.1.3
- path 1.8.0-nullsafety.3
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pdf 1.12.0 [archive barcode crypto image meta path_parsing utf vector_math]
- pdf_render 0.68.0 [flutter device_info vector_math]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- provider 4.3.2+3 [collection flutter nested]
- random_string 2.1.0
- rxdart 0.24.1
- share_extend 1.1.9 [meta flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- tuple 1.0.3 [quiver]
- tutorial_coach_mark 0.5.1 [flutter]
- wiredash 0.3.0 [flutter file http http_parser path_provider provider shared_preferences]

dev dependencies:
- flutter_launcher_icons 0.8.1 [image args yaml path]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed
_data]
- intl_translation 0.17.10+1 [analyzer args dart_style intl path petitparser]

transitive dependencies:
- _fe_analyzer_shared 7.0.0 [meta]
- analyzer 0.39.17 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.3 [collection]
- barcode 1.17.1 [meta qr]
- boolean_selector 2.1.0-nullsafety.3 [source_span string_scanner]
- characters 1.1.0-nullsafety.5
- charcode 1.2.0-nullsafety.3
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.3
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.5
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0-nullsafety.3 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.4 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_platform_interface 1.0.2 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+1 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- geocoding_platform_interface 1.0.1+1 [flutter meta plugin_platform_interface]
- geolocator_platform_interface 1.0.8 [flutter meta plugin_platform_interface vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_maps_flutter_platform_interface 1.0.5 [flutter meta plugin_platform_interface stream_transform]
- google_maps_webservice 0.0.18 [http meta]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.14.0+4 [csslib source_span]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- intl 0.16.1 [path]
- js 0.6.3-nullsafety.3
- logging 0.11.4
- matcher 0.12.10-nullsafety.3 [stack_trace]
- meta 1.3.0-nullsafety.6
- mime 0.9.7
- nested 0.0.4 [flutter]
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- package_config 1.9.3 [path charcode]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- qr 1.3.0 [meta]
- quiver 2.1.5 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.4 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.6 [path]
- stream_channel 2.1.0-nullsafety.3 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.3 [charcode source_span]
- term_glyph 1.2.0-nullsafety.3
- test_api 0.2.19-nullsafety.6 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.5.9 [path]
- typed_data 1.3.0-nullsafety.5 [collection]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- utf 0.9.0+5
- vector_math 2.1.0-nullsafety.5
- watcher 0.9.7+15 [async path pedantic]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]

```

</details>

---

**Comment by shatanikmahanty** [comment]
In the readme of the repo it is mentioned that firebase dynamic links are not supported for web that is why you are getting this error

**Comment by darshankawar** [comment]
@Eufranio 
`firebase_dynamic_links` is not supported on web yet. Check out [this](https://firebase.flutter.dev/) list for your reference.
You may need to remove that plugin from your code and run again.
Closing this as non-issue. If you disagree, write in comments and I'll reopen it.

**Comment by Eufranio** [comment]
Is there a place where I can follow the status of the development of the web version, if it is being developed?

**Comment by shatanikmahanty** [comment]
If you want named route for example hostname.com/home or you want to pass variables through url you can use [Fluro](https://pub.dev/packages/fluro) or [Get](https://pub.dev/packages/get) package
