### ISSUE TITLE
🐛 [firebase_auth] Instantiation of JsonResponse failed! class d.b.b.b.d.g.do

### ISSUE THREAD

**Issue by drandell** [FirebaseExtended/flutterfire#4389]
## Bug report

**Describe the bug**
Running my application in release mode, i get the following error message when trying to authenticate using firebaseAuth.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: [firebase_auth/unknown] com.google.firebase.o:
 An internal error has occurred. [ Instantiation of JsonResponse failed! class d.b.b.b.d.g.do ]
E/flutter (29324): #0      catchPlatformException (package:firebase_auth_platform_interface/src/method_channel/utils/exception.dart
:20)
E/flutter (29324): #1      _rootRunUnary (dart:async/zone.dart:1198)
E/flutter (29324): #2      _CustomZone.runUnary (dart:async/zone.dart:1100)
E/flutter (29324): #3      _FutureListener.handleError (dart:async/future_impl.dart:160)
E/flutter (29324): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708)
E/flutter (29324): #5      Future._propagateToListeners (dart:async/future_impl.dart:729)
E/flutter (29324): #6      Future._completeError (dart:async/future_impl.dart:537)
E/flutter (29324): #7      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47)
E/flutter (29324): #8      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart)
E/flutter (29324): <asynchronous suspension>
```

### Steps to reproduce

1. flutter run --release
2. Use firebase auth example code 

### Expected behavior

Login working fine in debug mode in emulator and on device. Should work in release mode.

---

## Additional context

build.gradle
<details><summary>Click To Expand</summary>

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.1'
        classpath 'com.google.gms:google-services:4.2.0'  // Google Services plugin
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

</details>

app/build.gradle
<details><summary>Click To Expand</summary>

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    throw new GradleException("versionCode not found. Define flutter.versionCode in the local.properties file.")
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    throw new GradleException("versionName not found. Define flutter.versionName in the local.properties file.")
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'  // Google Services plugin
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
        checkReleaseBuilds false 
    }

    defaultConfig {
        applicationId "com.wizsoft.yapq"
        minSdkVersion 16
        targetSdkVersion 29
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
       release {
           storeFile file("../key.jks")
            storePassword = "$System.env.KEY_PASSWORD"
            keyAlias = "$System.env.KEY_ALIAS"
            keyPassword = "$System.env.ALIAS_PASSWORD"
       }
   }

    buildTypes {
        release {
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type.
            minifyEnabled true
            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources true
//
//            // Includes the default ProGuard rules files that are packaged with
//            // the Android Gradle plugin. To learn more, go to the section about
//            // R8 configuration files.
//            proguardFiles getDefaultProguardFile(
//                    'proguard-android-optimize.txt'),
//                    'proguard-rules.pro'

            // Signing with the release key
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.android.support:multidex:1.0.3' // use latest version
    implementation "androidx.multidex:multidex:2.0.0"
    // Import the Firebase BoM
    implementation platform('com.google.firebase:firebase-bom:26.1.1')
    // Declare the dependency for the Firebase SDK for Google Analytics
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    // Also declare the dependency for the Google Play services library and specify its version
    // implementation 'com.google.android.gms:play-services-auth:19.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
```
</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 32-bit edition (version 1.52.0)
[√] Connected device (1 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.5
yapq 2.0.0+15

dependencies:
- appwrite 0.3.0-dev.2 [meta path_provider package_info dio cookie_jar dio_cookie_manager flutter_web_auth universal_html flutter]
- auth_buttons 0.0.4 [flutter]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface clo
ud_firestore_web]
- cupertino_icons 1.0.0
- firebase_admob 0.10.3 [meta flutter firebase_core]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web fl
utter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_dynamic_links 0.6.3 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_login_facebook 0.4.0+1 [flutter list_ext]
- get 3.22.2 [flutter]
- google_sign_in 4.5.6 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- gradient_widgets 0.5.2 [flutter]
- http 0.12.2 [http_parser path pedantic]
- in_app_purchase 0.3.4+16 [async collection flutter json_annotation meta]
- provider 4.3.2+3 [collection flutter nested]
- searchable_dropdown 1.1.3 [flutter]
- share 0.6.5+4 [meta mime flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos
 shared_preferences_web shared_preferences_windows]
- smooth_page_indicator 0.2.0 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode col
lection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platfor
m_interface js]
- collection 1.15.0-nullsafety.3
- cookie_jar 1.0.1
- csslib 0.16.2 [source_span]
- dio 3.0.10 [http_parser path]
- dio_cookie_manager 1.0.0 [cookie_jar dio]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platfo
rm_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_auth 0.2.4 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.1+1 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.14.0+4 [csslib source_span]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.2
- json_annotation 3.0.1
- list_ext 0.1.14 [quiver collection]
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- package_info 0.4.3+2 [flutter]
- path 1.8.0-nullsafety.1
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.0
- platform 2.2.1
- plugin_platform_interface 1.0.2 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.3 [matcher meta]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_inter
face path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner t
erm_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- universal_html 1.2.3 [async charcode collection csslib html meta typed_data universal_io zone_local]
- universal_io 1.0.1 [meta zone_local]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.4 [ffi]
- xdg_directories 0.1.0 [path process flutter]
- zone_local 0.1.2
```

</details>

---

**Comment by drandell** [comment]
I've ended up creating a brand new project and importing some of the newer config into my old project (it was rather out of date).
