### ISSUE TITLE
🐛 [cloud_firestore] Query that ordered by __name__ and limited to last fail 

### ISSUE THREAD

**Issue by tlserver** [FirebaseExtended/flutterfire#4398]
## Bug report

`collection.orderBy(FieldPath.documentId).limitToLast(x)` should only required a single-field index, which should be generated automatically . However, when listened to the snapshot steam, it failed with message: 
`W/Firestore(12654): (21.7.1) [Firestore]: Listen for Query(target=Query(*Omitted_Collection_Path* order by -__name__);limitType=LIMIT_TO_LAST) failed: Status{code=FAILED_PRECONDITION, description=The query requires an index. You can create it here: *Omitted link*, cause=null}`

Also the link for creating index is not work:
![image](https://user-images.githubusercontent.com/8895426/102091549-f21e1000-3e59-11eb-99ad-cc4d3d5d59df.png)

---

## Additional context

`orderBy(FieldPath.documentId, descending: true)` is also fail with the same error message.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale zh-HK)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
- _fe_analyzer_shared 7.0.0 [meta]
- analyzer 0.39.17 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- ansicolor 1.0.5
- args 1.6.0
- asn1lib 0.6.5
- async 2.5.0-nullsafety.1 [collection]
- basic_utils 2.6.3 [http logging json_annotation pointycastle asn1lib convert crypto]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.0 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- console_log_handler 1.1.6 [logging intl ansicolor]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 2.1.3 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_compass 0.5.0 [flutter rxdart]
- flutter_image 3.0.0 [flutter]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_map 0.10.1+1 [flutter tuple latlong positioned_tap_detector transparent_image async flutter_image cached_network_image sqflite path_provider vector_math proj4dart meta]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- geolocator 6.1.6 [flutter geolocator_platform_interface]
- geolocator_platform_interface 1.0.8 [flutter meta plugin_platform_interface vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- html 0.14.0+4 [csslib source_span]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.2
- json_annotation 3.0.1
- latlong 0.6.1 [logging console_log_handler validate intl]
- lists 0.1.6
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mgrs_dart 1.0.1 [unicode]
- nested 0.0.4 [flutter]
- node_interop 1.2.0 [js]
- node_io 1.1.1 [node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 1.0.2
- positioned_tap_detector 1.0.3 [flutter]
- process 3.0.13 [file intl meta path platform]
- proj4dart 1.0.5 [mgrs_dart wkt_parser meta]
- pub_semver 1.4.4 [collection]
- quiver 2.1.5 [matcher meta]
- random_string 2.1.0
- rxdart 0.24.1
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- syncfusion_flutter_core 18.3.50 [flutter pedantic]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.5.9 [path]
- transparent_image 1.0.0
- typed_data 1.3.0-nullsafety.3 [collection]
- unicode 0.2.4 [lists]
- uuid 2.2.2 [crypto convert]
- validate 1.7.0
- vector_math 2.1.0-nullsafety.3
- vin_decoder 0.1.2 [meta basic_utils http random_string]
- watcher 0.9.7+15 [async path pedantic]
- win32 1.7.3 [ffi]
- wkt_parser 1.0.7
- xdg_directories 0.1.2 [meta path process]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by darshankawar** [comment]
@tlserver 
Can you provide a complete minimal reproducible code sample ?
Also can you try to query like `Firestore.instance.collection('').orderBy('').orderBy(FiledPath.documentId).limitToLast(x)` ?

**Comment by tlserver** [comment]
A complete minimal reproducible code sample here. Please create a collection call `DebugCollection` and add some empty documents into it before running this code.
```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(App());
}

class App extends StatelessWidget {
  const App({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: FutureBuilder(
          future: Firebase.initializeApp(),
          builder: (BuildContext context, AsyncSnapshot<FirebaseApp> snapshot) {
            if (snapshot.hasData)
              return StreamBuilder(
                stream: FirebaseFirestore.instance.collection('DebugCollection').orderBy(FieldPath.documentId).limitToLast(6).snapshots(),
                builder: (_, AsyncSnapshot<QuerySnapshot> snapshot) {
                  if (snapshot.hasData)
                    return ListView.builder(
                      itemBuilder: (BuildContext context, int index) {
                        return ListTile(
                          title: Text(snapshot.data.docs[index].id),
                        );
                      },
                      itemCount: snapshot.data.size,
                    );
                  return SizedBox.shrink();
                },
              );
            return SizedBox.shrink();
          },
        ),
      ),
    );
  }
}
```

**Comment by tlserver** [comment]
`Firestore.instance.collection('').orderBy('').orderBy(FiledPath.documentId).limitToLast(x)` throw exception:
```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building FutureBuilder<FirebaseApp>(dirty, state: _FutureBuilderState<FirebaseApp>#f30e8):
a collectionPath path must be a non-empty string
'package:cloud_firestore/src/firestore.dart':
Failed assertion: line 70 pos 12: 'collectionPath.isNotEmpty'

The relevant error-causing widget was: 
  FutureBuilder<FirebaseApp> *********************************** file path omitted ***********************************
When the exception was thrown, this was the stack: 
#2      FirebaseFirestore.collection (package:cloud_firestore/src/firestore.dart:70:12)
#3      App.build.<anonymous closure> (package:bug_report_sample/main.dart:23:52)
#4      _FutureBuilderState.build (package:flutter/src/widgets/async.dart:751:55)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
...
====================================================================================================
```
`FirebaseFirestore.instance.collection('DebugCollection').orderBy('').orderBy(FieldPath.documentId).limitToLast(6)` also throw `'package:cloud_firestore_platform_interface/src/field_path.dart': Failed assertion: line 44 pos 12: 'path.isNotEmpty': is not true.`

**Comment by darshankawar** [comment]
@tlserver 
Thanks for the reproducible code sample. I was able to replicate the issue on latest stable.

`W/Firestore(13272): (21.4.3) [Firestore]: Listen for Query(target=Query(DebugCollection order by -__name__);limitType=LIMIT_TO_LAST) failed: Status{code=FAILED_PRECONDITION, description=The query requires an index.`

Following the link to create an index, throws an error while creating one:

<img width="630" alt="Screenshot 2020-12-16 at 1 31 34 PM" src="https://user-images.githubusercontent.com/67046386/102321244-64e6d280-3fa3-11eb-88bb-f10b95d7f97d.png">
<img width="623" alt="Screenshot 2020-12-16 at 1 31 47 PM" src="https://user-images.githubusercontent.com/67046386/102321251-67e1c300-3fa3-11eb-93f7-dee7d51dab53.png">

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (6 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                            •
      android-x86 • Android 11 (API 30) (emulator)
    • Darshan's iphone (mobile)   • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios         • iOS 14.2

• No issues found!



```

</details>

Curious though, what should be the expected behavior in your case ? App to compile properly without throwing the said error ?

**Comment by tlserver** [comment]
I want to listen to the snapshot steam of the last (largest ID) 7 documents in a collection. When a new document, which has a ID larger than the current largest ID, has been created, the snapshot should include the new document instead of the old one.

**Comment by tlserver** [comment]
Currently, it only load the data in local cache correctly, but cannot receive any data from cloud

**Comment by tlserver** [comment]
Because of this exception, the app cannot download data from cloud by this kind of queries. Any workaround for the current status?

**Comment by russellwheatley** [comment]
Hey @tlserver, as far as I can tell, this isn't a bug. You cannot perform a `desc` query on `__name__` property (This is the `documentId` property name under the hood). When you invoke the `limitToLast` method, it makes the `orderBy` query `desc`. Example:

```dart
_firestore
  .collection('DebugCollection')
  .orderBy(FieldPath.documentId)
  // "limitToLast" method call makes orderBy query "desc" and takes the top 6 results.
  .limitToLast(6)
  .snapshots()
``` 

I can't find any documentation which confirms this, except this [SO](https://stackoverflow.com/a/52119324/5681607) answer from a former Firebase DevRel.

The advice given in that answer would be to store the `id` as a prop in each document and use that to `orderBy`.
