### ISSUE TITLE
🐛 [firebase_core] Accessing hidden method Lsun/misc/Unsafe

### ISSUE THREAD

**Issue by casvanluijtelaar** [FirebaseExtended/flutterfire#4418]
## Bug report

**Describe the bug**
after updating all firebase dependencies to the new ones (firebase_core usage etc...), terminal started being spammed with 
`Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)`
and similar. 

### Steps to reproduce

took an existing project and migrated it to the new firebase plugins:
```
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_storage: ^5.2.0
  cloud_firestore: ^0.14.4
```

### Expected behavior

app behaves like normal. constant warning are being thrown in the console, downing out any useful debug messages.

---

## Additional context

this is not a breaking bug, it seems like one of these plugins is using outdated / unsafe operations? Haven't run into any point where this breaks the functionality of the app, but it's something to look into 

console:
<details><summary>Click To Expand</summary>

```
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
       |W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
       /W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
I/chatty  (17078): uid=10307(com.rvised.communication) FirestoreWorker identical 3 lines
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/d.communicatio(17078): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 1.22.4, on Microsoft Windows [Version 10.0.18363.1256], locale en-GB)
    • Flutter version 1.22.4 at D:\ProgramData\Android\flutter
    • Framework revision 1aafb3a8b9 (5 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\ProgramData\android
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = D:\ProgramData\Android\sdk
    • ANDROID_SDK_ROOT = D:\ProgramData\Android\sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_201\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.49.1)
    • VS Code at C:\Users\casva\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] VS Code, 64-bit edition (version 1.47.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • GM1925 (mobile) • 192.168.0.233:5555 • android-arm64 • Android 10 (API 29)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
- adaptive_dialog 0.9.3 [flutter animations meta]
- blurhash 0.1.0 [string_validator flutter]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- connectivity 0.4.9 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- countup 0.1.2 [flutter]
- device_preview 0.4.8 [font_awesome_flutter http freezed_annotation json_annotation flutter flutter_localizations meta shared_preferences shared_preferences_macos]
- file_picker 1.13.0+1 [flutter flutter_plugin_android_lifecycle file_picker_platform_interface]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_storage 5.2.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- fl_chart 0.12.0 [flutter path_drawing equatable]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_datetime_picker 1.4.0 [flutter]
- flutter_document_picker 4.0.0 [flutter]
- flutter_sliding_up_panel 1.1.0+1 [flutter]
- get 3.4.1 [flutter]
- get_it 5.0.1 [async meta]
- giphy_picker 1.0.8 [flutter http]
- image 2.1.14 [archive xml]
- image_picker 0.6.7+4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- infinite_scroll_pagination 1.1.1 [flutter]
- intl 0.16.1 [path]
- intl_phone_number_input 0.4.6+2 [flutter libphonenumber equatable]
- open_file 3.0.1 [flutter ffi]
- photo_view 0.9.2 [flutter]
- pin_code_fields 4.0.0 [flutter]
- provider 4.3.2+2 [flutter nested collection]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- table_calendar 2.2.3 [flutter intl simple_gesture_detector]
- url_launcher 5.7.2 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- vertical_calendar 1.0.1+6 [flutter intl]

transitive dependencies:
- animations 1.1.2 [flutter]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.4.2 [collection]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.1.3
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- connectivity_for_web 0.3.0 [connectivity_platform_interface js flutter_web_plugins flutter]
- connectivity_macos 0.1.0+3 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- equatable 1.2.0 [collection meta]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- file_picker_platform_interface 1.3.1 [flutter plugin_platform_interface]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_storage_platform_interface 1.0.2 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+1 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 0.10.11
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 1.0.8 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- font_awesome_flutter 8.10.0 [flutter]
- freezed_annotation 0.11.0+1 [collection json_annotation meta]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.0 [flutter meta http plugin_platform_interface]
- js 0.6.2
- json_annotation 3.1.1
- libphonenumber 1.0.1 [flutter built_value]
- matcher 0.12.9 [stack_trace]
- meta 1.3.0-nullsafety.3
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.0
- petitparser 3.0.4 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.2 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.3 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- simple_gesture_detector 0.1.4 [flutter]
- sky_engine 0.0.99
- source_span 1.7.0 [charcode collection meta path term_glyph]
- stack_trace 1.9.5 [path]
- string_scanner 1.0.5 [charcode meta source_span]
- string_validator 0.1.4
- term_glyph 1.1.0
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.4+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.3 [ffi]
- xdg_directories 0.1.0 [path process flutter]
- xml 4.2.0 [collection convert meta petitparser]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Don't have a repro case for this but I've seen it in a lot of logs in [other issues](https://github.com/FirebaseExtended/flutterfire/issues?q=is%3Aissue+%22Accessing+hidden+method+Lsun%2Fmisc%2FUnsafe%22).

**Comment by casvanluijtelaar** [comment]
might be unrelated, but 

```
W/ConnectionTracker(17476): Exception thrown while unbinding    
W/ConnectionTracker(17476): java.lang.IllegalArgumentException: Service not registered: lu@2024e52
W/ConnectionTracker(17476):     at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1766)
W/ConnectionTracker(17476):     at android.app.ContextImpl.unbindService(ContextImpl.java:1810)
W/ConnectionTracker(17476):     at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(17476):     at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):1)
W/ConnectionTracker(17476):     at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):2)
W/ConnectionTracker(17476):     at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):9)
W/ConnectionTracker(17476):     at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):3)
W/ConnectionTracker(17476):     at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):3)
W/ConnectionTracker(17476):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(17476):     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(17476):     at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516081@20.45.16 (120400-0):5)
```
seems to show up from time to time too, since migrating.

**Comment by casvanluijtelaar** [comment]
seems to be very much related, if not the same as https://github.com/FirebaseExtended/flutterfire/issues/4090? can be closed?

**Comment by markusaksli-nc** [comment]
It could be related but these messages are different enough to be considered separate issues I think. One of the members can close this if it's just due to the same upstream issue.

**Comment by flakerimi** [comment]
Its related with this too https://github.com/flutter/flutter/issues/27095

**Comment by zaenury** [comment]
You can fix this by turning off the backup.
Add this tag on your file "android > app > src > debug > AndroidManifest.xml":

    <application android:allowBackup="false">

Here is some information about your problem https://developer.android.com/guide/topics/data/autobackup .
