### ISSUE TITLE
🐛 [firebase_auth] [web] Getting an exception when trying to create new users without getting logged out

### ISSUE THREAD

**Issue by devj3ns** [FirebaseExtended/flutterfire#4454]
## Bug report

**Describe the bug**
In my Flutter Web App I am trying to create a new user without getting logged out from my current account. Unfortuantely I am getting the following error when trying to delete the created second app again (which I used to create the new user). I already tried different versions of firebase js.

``` 
Expected a value of type 'JSObject<I>', but got one of type 'NativeJavaScriptObject'
```

This is my code:
``` dart
var secondApp = await Firebase.initializeApp(name: 'secondApp', options: Firebase.app().options);
var secondInstance = firebase_auth.FirebaseAuth.instanceFor(app: newApp);

var userCredential = await secondInstance.createUserWithEmailAndPassword(email: email, password: password);

await secondInstance.signOut();
await secondApp.delete(); // <-- this line is responsible for the exception
``` 

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.19042.685], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.51.1)
[√] Connected device (3 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0-29.10.beta
Flutter SDK 1.24.0-10.2.pre
my_app 1.0.0+1

dependencies:
- another_flushbar 1.10.8 [flutter]
- appointment_repository 1.0.0 [flutter firebase_core cloud_firestore equatable]
- authentication_repository 1.0.0 [flutter firebase_core firebase_auth meta equatable dartz]
- bloc 6.1.1 [meta]
- dartz 0.9.2
- datetime_picker_formfield 1.0.0 [flutter intl]
- equatable 1.2.5 [collection meta]
- feed_repository 1.0.0 [flutter firebase_core cloud_firestore firebase_storage equatable]
- file_picker 2.1.4 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.1.1 [flutter bloc provider]
- flutter_hooks 0.15.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_spinkit 4.1.2+1 [flutter]
- font_awesome_flutter 8.11.0 [flutter]
- google_fonts 1.1.1 [flutter http path_provider crypto pedantic]
- notification_repository 1.0.0 [flutter firebase_core firebase_messaging http]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- user_repository 1.0.0 [flutter firebase_core cloud_firestore equatable]

dev dependencies:
- flutter_launcher_icons 0.8.1 [image args yaml path]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.3 [collection]
- boolean_selector 2.1.0-nullsafety.3 [source_span string_scanner]
- characters 1.1.0-nullsafety.5
- charcode 1.2.0-nullsafety.3
- clock 1.1.0-nullsafety.3
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.5
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0-nullsafety.3 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_messaging 8.0.0-dev.11 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- firebase_messaging_platform_interface 1.0.0-dev.7 [flutter meta firebase_core plugin_platform_interface]
- firebase_messaging_web 0.1.0-dev.2 [flutter flutter_web_plugins meta firebase_core firebase_core_web firebase_messaging_platform_interface js service_worker]
- firebase_storage 5.2.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- firebase_storage_platform_interface 1.0.2 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+1 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- intl 0.16.1 [path]
- js 0.6.3-nullsafety.3
- matcher 0.12.10-nullsafety.3 [stack_trace]
- meta 1.3.0-nullsafety.6
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.3
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- provider 4.3.2+3 [collection flutter nested]
- quiver 2.1.5 [matcher meta]
- service_worker 0.2.4 [js]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.4 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.6 [path]
- stream_channel 2.1.0-nullsafety.3 [async]
- string_scanner 1.1.0-nullsafety.3 [charcode source_span]
- term_glyph 1.2.0-nullsafety.3
- test_api 0.2.19-nullsafety.6 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.5 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0-nullsafety.5
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @devj3ns 
I can't reproduce this issue on the latest master `1.26.0-2.0.pre.103` with `firebase_auth: ^0.18.4+1`.
```html
  </script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js"></script>
  <script>
```
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.26.0-2.0.pre.117, on Microsoft Windows [Version 10.0.19041.685], locale et-EE)
    • Flutter version 1.26.0-2.0.pre.117 at C:\Development\flutter_master
    • Framework revision 15c009b805 (8 hours ago), 2020-12-22 20:09:03 -0500
    • Engine revision b7cd3f8e70
    • Dart version 2.12.0 (build 2.12.0-173.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.5981.155
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.685]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
</details>
<details>
 <summary>Code sample</summary>

```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(AuthExampleApp());
}

class AuthExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Example App',
      theme: ThemeData.dark(),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Firebase Example App"),
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          RaisedButton(
            child: const Text('Create and delete second app'),
            onPressed: () async {
              var secondApp = await Firebase.initializeApp(name: 'secondApp', options: Firebase.app().options);
              await secondApp.delete();
            },
          ),
          RaisedButton(
            child: const Text('Create user in second app and delete'),
            onPressed: () async {
              var secondApp = await Firebase.initializeApp(name: 'secondApp', options: Firebase.app().options);
              var secondInstance = FirebaseAuth.instanceFor(app: secondApp);

              print(secondInstance.currentUser.toString());
              await secondInstance.createUserWithEmailAndPassword(email: "a@b.com", password: "password");
              print(secondInstance.currentUser.toString());

              await secondInstance.signOut();
              await secondApp.delete();
            },
          ),
        ],
      ),
    );
  }
}
```
</details>

Can you also see the issue with this minimal code sample? Could you provide the full error and stacktrace in `flutter run -v`?
Thank you

**Comment by devj3ns** [comment]
@markusaksli-nc Hey, thanks for your help so far.

I tried your code snippet in a new project and it works fine. I dont understand why its not working in my project...

This is the complete error I get:

```
Error: Expected a value of type 'JSObject<I>', but got one of type 'NativeJavaScriptObject'
    at Object.throw_ [as throw] (http://localhost:62694/dart_sdk.js:4354:11)
    at Object.castError (http://localhost:62694/dart_sdk.js:4325:15)
    at Object.cast [as as] (http://localhost:62694/dart_sdk.js:4641:17)
    at dart.LegacyType.new.as (http://localhost:62694/dart_sdk.js:6232:60)
    at Object.getFirebaseAuthException (http://localhost:62694/packages/firebase_auth_web/src/utils/web_utils.dart.lib.js:118:116)
    at firebase_auth_web.FirebaseAuthWeb.new.createUserWithEmailAndPassword (http://localhost:62694/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:122:32)
    at createUserWithEmailAndPassword.throw (<anonymous>)
    at http://localhost:62694/dart_sdk.js:38006:38
    at _RootZone.runBinary (http://localhost:62694/dart_sdk.js:37859:58)
    at _FutureListener.thenAwait.handleError (http://localhost:62694/dart_sdk.js:32827:48)
    at handleError (http://localhost:62694/dart_sdk.js:33379:51)
    at Function._propagateToListeners (http://localhost:62694/dart_sdk.js:33405:17)
    at _Future.new.[_completeError] (http://localhost:62694/dart_sdk.js:33251:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:62694/dart_sdk.js:33290:31)
    at Object._microtaskLoop (http://localhost:62694/dart_sdk.js:38115:13)
    at _startMicrotaskLoop (http://localhost:62694/dart_sdk.js:38121:13)
    at http://localhost:62694/dart_sdk.js:33618:9
```

Btw: I upgraded to Flutter version 1.25.0-8.1.pre in the beta channel. But this doesnt change anything.

And this is the original code I am using (for simplicity I removed the try and catch)
```
Future<Either<CreatedUserData, CreateUserFailure>> registerUserByName({
    @required String firstName,
    @required String lastName,
  }) async {
   
    var newApp = await Firebase.initializeApp(name: 'newApp', options: Firebase.app().options);

    var newInstance = firebase_auth.FirebaseAuth.instanceFor(app: newApp);

    var username = firstName.trim() + lastName.trim();
    var password = generateRandomPassword(length: 10); 

    var userCredential = await newInstance.createUserWithEmailAndPassword(email: username.toFirebaseAuthEmail(), password: password);

    await newInstance.signOut();
    await newApp.delete(); //when I remove this line it works

    var createdUserData = CreatedUserData(
      userId: userCredential.user.uid,
      password: password,
      name: '$firstName $lastName',
      username: username,
    );

    return left(createdUserData);
}

extension on String {
  String toFirebaseAuthEmail() {
    return '${this}@myapp.com';
  }

  String fromFirebaseAuthEmail() {
    return replaceAll('@myapp.com', '');
  }
}

String generateRandomPassword({int length}) {
  var r = Random();
  const _chars =
      'AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890';
  return List.generate(length, (index) => _chars[r.nextInt(_chars.length)])
      .join();
}
```

Thanks in advance!

**Comment by markusaksli-nc** [comment]
If it worked in a new project there is likely something wrong with the current project config. If you used older versions of the firebase plugins before the config would need to be updated according to https://firebase.flutter.dev/docs/migration. It would still be hard to tell what exactly is broken. The important part is that this isn't an issue with the plugin itself or your exact code.

The exact contents created by `flutter create` have likely changed quite a bit since you created the project with the older flutter version. Unless you have any native code or elaborate setup you don't want to repeat you could just use the old dart code in the new project (flutter create --org com.myorg appname to set up the same identifier).

**Comment by devj3ns** [comment]
Hey @markusaksli-nc 

I created a new flutter project and after a bit of debugging I found out that the exception is not thrown when deleting the second app but when trying to create a new user in the second app when the second app was used and deleted before.

**Steps to reproduce:**
-Use the code below and start it on the web
-Press the button (creates a new user in a new app and deletes the app afterwards) --> works fine
-Press the button again --> throws the exception (which you can see in my last comment)

Could you please try to reproduce it? Because I think it does not have something to do with my project config.

Thanks in advance :) 

<details>
<summary>Code to reproduce</summary>
<p>

```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(AuthExampleApp());
}

class AuthExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Example App',
      theme: ThemeData.dark(),
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Firebase Example App"),
      ),
      body: Center(
        child: RaisedButton(
          child: const Text(
              'Create new user in second app and delete app afterwards'),
          onPressed: () async {
            print('Button was pressed, current apps: ${Firebase.apps}');

            var secondApp = await Firebase.initializeApp(
                name: 'secondApp', options: Firebase.app().options);
            var secondInstance = FirebaseAuth.instanceFor(app: secondApp);

            print(
                'secondApp and secondInstance created, current apps:  ${Firebase.apps}');

            print('Trying to create the user in the second instance...');

            await secondInstance.createUserWithEmailAndPassword(
                email: "test${DateTime.now().second}@test.com",
                password: "password");

            print(secondInstance.currentUser.toString());
            print("Deleting the app...");
            print(Firebase.apps);

            await secondInstance.signOut();
            await secondApp.delete();

            print("App deleted. current apps:  ${Firebase.apps}");
          },
        ),
      ),
    );
  }
}
```
</p>
</details>

**Comment by markusaksli-nc** [comment]
I was able to reproduce it by pressing it twice on web. Does not repro on Android. Same as before, latest master `1.26.0-2.0.pre.200` with `firebase_auth: ^0.18.4+1`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.26.0-2.0.pre.200, on Microsoft Windows [Version 10.0.19041.685], locale et-EE)
    • Flutter version 1.26.0-2.0.pre.200 at C:\Development\flutter_master
    • Framework revision d0e9959a46 (29 hours ago), 2021-01-05 22:14:03 -0500
    • Engine revision e115066dcd
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.685]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
```
</details>


Thanks for figuring it out!

**Comment by russellwheatley** [comment]
I recreated your error on the web platform:
```js
var firebaseConfig = {
  // config
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);

var second = firebase.initializeApp(firebaseConfig, 'secondApp');

var secondAuth = second.auth();

export async function called() {
  console.log('still here??');
  await secondAuth.createUserWithEmailAndPassword(
    `fake@email.io${Date.now()}`,
    'blahblah'
  );

  console.log('secondAuth.currentUser', secondAuth.currentUser);

  await secondAuth.signOut();

  await second.delete();
}

document.getElementById('button-id').onclick = async () => {
  await called(); 
};
```

It reproduces the exact same error received using flutter web:
```
FirebaseError: Firebase: Firebase App named 'secondApp' already deleted (app/app-deleted).
```

This is the behaviour of the `firebase-js-sdk`, and it appears you cannot create an app with the same name as a previously deleted app.

You might want to raise an issue on the `firebase-js-sdk` [here](https://github.com/firebase/firebase-js-sdk) and raise inconsistent behaviour if it is different on android and iOS.

**Comment by devj3ns** [comment]
Thanks for the investigation @russellwheatley. I created an issue at the `firebase-js-sdk` repository.
