### ISSUE TITLE
🐛 [cloud_firestore] DocumentReference in nested object seems being not parsed properly

### ISSUE THREAD

**Issue by canisterism** [FirebaseExtended/flutterfire#4538]
## Bug report

DocumentReference in nested object seems being not parsed properly.

### Steps to reproduce

My document is like this;

```
- recentReviews (List)
  - profile (Map)
    - ref(Reference)
```
![image](https://user-images.githubusercontent.com/33423125/103415156-3fbdab00-4bc4-11eb-9442-27400457ed34.png)

Then you fetch this document and parse with this;
```dart
(data['profile'] as Map<String, dynamic>)['ref'] as DocumentReference
```
And you get this error.
```dart
flutter: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'DocumentReference' in type cast
...
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
#4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#6      new List.of (dart:core-patch/array_patch.dart:50:28)
#7      new List.from (dart:core-patch/array_patch.dart:36:19)
...
#10     MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
#11     ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
```
The `ref` seems to be parsed just as Map<String, dynamic>, not DocumentReference.

```dart
> (data['profile'] as Map<String, dynamic>)['ref']
Map (3 items)
0:"_firestore" -> Map (8 items)
1:"_path" -> Map (1 item)
2:"_converter" -> Map (0 items)
```

DateTime seems to be parsed wrongly, too.

```dart
> data['updatedAt']
Map (2 items)
0:"_seconds" -> 1608556932
1:"_nanoseconds" -> 362000000
```
### Expected behavior

The `ref` is parsed as DocumentReference.

---

## Additional context

N/A

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```                
FVM: Running version 1.26.0-1.0.pre
[✓] Flutter (Channel unknown, 1.26.0-1.0.pre, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en-JP)
    • Flutter version 1.26.0-1.0.pre at /Users/otanihiroki/fvm/versions/1.26.0-1.0.pre
    • Framework revision 63062a6443 (3 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/otanihiroki/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • B45BAE51-8D90-4F76-822D-D04B9962AD84 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0-141.0.dev
Flutter SDK 1.26.0-1.0.pre
clip_games 1.0.0+1

dependencies:
- algolia 0.1.7 [meta http uuid]
- cloud_firestore 0.14.1+3 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 1.0.2
- firebase_auth 0.18.1+2 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.0+1 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_hooks 0.14.1 [flutter]
- flutter_rating_bar 3.2.0+1 [flutter]
- freezed 0.12.2 [analyzer build build_config meta source_gen freezed_annotation]
- google_sign_in 4.5.6 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- hooks_riverpod 0.11.2 [flutter_riverpod riverpod flutter flutter_hooks collection state_notifier]
- modal_bottom_sheet 1.0.0+1 [flutter]
- state_notifier 0.6.0 [meta]

dev dependencies:
- build_runner 1.10.11 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed_annotation 0.12.0 [collection json_annotation meta]
- json_annotation 3.1.1

dependency overrides:
- analyzer 0.40.4 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]

transitive dependencies:
- _fe_analyzer_shared 11.0.0 [meta]
- args 1.6.0
- async 2.5.0-nullsafety.3 [collection]
- boolean_selector 2.1.0-nullsafety.3 [source_span string_scanner]
- build 1.5.2 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.4.4 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.0.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.5
- charcode 1.2.0-nullsafety.3
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.1.4 [path]
- clock 1.1.0-nullsafety.3
- cloud_firestore_platform_interface 2.1.2 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.0+4 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.5
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- dart_style 1.3.10 [analyzer args path source_span]
- fake_async 1.2.0-nullsafety.3 [clock collection]
- file 5.2.1 [intl meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_auth_platform_interface 2.1.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.1+1 [flutter flutter_web_plugins firebase meta http_parser intl firebase_core firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- fixnum 0.10.11
- flutter_riverpod 0.11.2 [flutter collection riverpod state_notifier meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 0.2.0
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3-nullsafety.3
- logging 0.11.4
- matcher 0.12.10-nullsafety.3 [stack_trace]
- meta 1.3.0-nullsafety.6
- mime 0.9.7
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.3
- pedantic 1.9.2 [meta]
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.7 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.5 [matcher meta]
- riverpod 0.11.2 [meta collection freezed_annotation state_notifier]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.4 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.6 [path]
- stream_channel 2.1.0-nullsafety.3 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.3 [charcode source_span]
- term_glyph 1.2.0-nullsafety.3
- test_api 0.2.19-nullsafety.6 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0-nullsafety.5 [collection]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.5
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- yaml 2.2.1 [charcode collection string_scanner source_span]```

</details>

---

**Comment by canisterism** [comment]
Sorry, this is my fault.
The data was fetched from algolia. The non-parsed record was a record copied to aloglia's index from firestore.
Algolia can't understand DocumentReference so DocumentReference is parsed just as Map.
I close this issue.
