### ISSUE TITLE
🐛 [firebase_auth] Problem logging out Macos

### ISSUE THREAD

**Issue by ReniDelonzek** [FirebaseExtended/flutterfire#4608]
## Bug report

**Describe the bug**
When executing the logout command on Macos, the following error is thrown on the console

> [firebase_auth/keychain-error] An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered
flutter: #0      catchPlatformException
package:firebase_auth_platform_interface/…/utils/exception.dart:20
#1      _rootRunUnary (dart:async/zone.dart:1194:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1097:19)
#3      _FutureListener.handleError (dart:async/future_impl.dart:167:20)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:715:47)
#5      Future._propagateToListeners (dart:async/future_impl.dart:736:24)
#6      Future._completeError (dart:async/future_impl.dart:544:5)
#7      _completeOnAsyncError (dart:async-patch/async_patch.dart:264:13)
#8      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
package:flutter/…/services/platform_channel.dart:1
<asynchronous suspension>

### Steps to reproduce

1. Log in
2. Call `await FirebaseAuth.instance.signOut();`

### Expected behavior

That logout is performed correctly

### Version

```firebase_auth: ^0.18.4+1```
 
### Flutter doctor

<details><summary>Click to expand</summary>
```
[✓] Flutter (Channel dev, 1.26.0-1.0.pre, on Mac OS X 10.15.7 19H114 darwin-x64, locale pt-BR)
    • Flutter version 1.26.0-1.0.pre at /Users/reni/Downloads/Programas/flutter
    • Framework revision 63062a6443 (4 weeks ago), 2020-12-13 23:19:13 +0800
    • Engine revision 4797b06652
    • Dart version 2.12.0 (build 2.12.0-141.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/reni/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/reni/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554                        • android-x86    • Android
      10 (API 29) (emulator)
    • iPhone 12 Pro Max (mobile)         • FA985302-62C3-4B19-9277-AE30900062A2 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)                    • macos                                • darwin-x64     • Mac OS
      X 10.15.7 19H114 darwin-x64
    • Chrome (web)                       • chrome                               • web-javascript • Google
      Chrome 87.0.4280.141

• No issues found!
```
</details>

**Comment by markusaksli-nc** [comment]
Hi @ReniDelonzek 
I'm not seeing this using the official example on the latest master `1.26.0-2.0.pre.275` with `firebase_auth: ^0.18.4+1`.
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on macOS 11.1 20C69 darwin-arm, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.275 at /Users/nevercode/development/flutter_master
    • Framework revision d9044a8a61 (2 days ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (4 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.3
    • iPhone 12 Pro Max (mobile)  • 09D9E93F-A98D-4735-B6E6-6E57F9CD01D8     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 11.1 20C69 darwin-arm
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
</details>

It seems like the error has to do with keychain sharing. Could you try to see if adding the Keychain Sharing capability in Xcode fixes the issue for you?
Thank you

**Comment by ReniDelonzek** [comment]
For some reason I was unable to play after restarting. I will try to see if there is anything else involved that is causing this problem

**Comment by markusaksli-nc** [comment]
Sorry the bot is not cooperating here

**Comment by ReniDelonzek** [comment]
I can't reproduce this problem anymore, it will close for now
