### ISSUE TITLE
🐛 [firebase_ml_vision] FirebaseVisionDocumentText.getText() null object reference

### ISSUE THREAD

**Issue by atnegrete** [FirebaseExtended/flutterfire#4616]
## Bug report

**Describe the bug**
Crashes entire app on Android (have not tested iOS)

Tested versions: 0.9.7, 0.9.8 and 0.9.10

Error stacktrace
```

E/AndroidRuntime( 7093): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.ml.vision.document.FirebaseVisionDocumentText.getText()' on a null object reference
E/AndroidRuntime( 7093): 	at io.flutter.plugins.firebasemlvision.DocumentTextRecognizer$2.onSuccess(DocumentTextRecognizer.java:47)
E/AndroidRuntime( 7093): 	at io.flutter.plugins.firebasemlvision.DocumentTextRecognizer$2.onSuccess(DocumentTextRecognizer.java:43)
E/AndroidRuntime( 7093): 	at com.google.android.gms.tasks.zzn.run(Unknown Source:4)
E/AndroidRuntime( 7093): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime( 7093): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7093): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 7093): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime( 7093): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7093): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime( 7093): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Steps to reproduce

1. Select an image with no text on it, ie a picture of your foot
2.  final firebaseImage = FirebaseVisionImage.fromFile(image);
3. final visionText = await cloudDocumentTextRecognizer.processImage(firebaseImage);

### Expected behavior

The response contains no text blocks.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.2, on Microsoft Windows [Version 10.0.18363.1256], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2018.1)
[√] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
- cloud_firestore 0.13.7 [flutter meta firebase_core cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 1.0.0
- dio 3.0.10 [http_parser path]
- firebase_admob 0.9.3+4 [meta platform flutter firebase_core]
- firebase_analytics 5.0.11 [meta flutter]
- firebase_auth 0.15.5+3 [meta firebase_core firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.4.5 [firebase_core_platform_interface flutter meta firebase_core_web]
- firebase_messaging 5.1.8 [meta platform flutter]
- firebase_ml_vision 0.9.10 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_spinkit 4.1.2+1 [flutter]
- image_picker 0.6.7+14 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- in_app_review 1.0.4 [flutter in_app_review_platform_interface]
- in_app_update 1.1.14 [flutter]
- injector 1.0.9 [meta]
- intl 0.16.1 [path]
- provider 4.3.2+2 [flutter nested collection]
- pull_to_refresh 1.6.3 [flutter]
- sailor 0.7.1 [flutter]
- string_similarity 1.1.0
- toast 0.1.5 [flutter]
- xml2json 4.4.0 [xml]

dev dependencies:
- flutter_launcher_icons 0.7.5 [image args yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 1.1.2 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.1.1+2 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase 7.3.2 [http http_parser js]
- firebase_auth_platform_interface 1.1.8 [flutter meta plugin_platform_interface]
- firebase_auth_web 0.1.3+1 [firebase_auth_platform_interface flutter flutter_web_plugins firebase http_parser meta js]
- firebase_core_platform_interface 1.0.4 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.1.1+2 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- in_app_review_platform_interface 1.0.5 [flutter url_launcher plugin_platform_interface platform]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.1
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.5 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0-nullsafety.3
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @atnegrete 
Could you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you
