### ISSUE TITLE
[firebase_messaging] Unexpected exception retrieving FCM token on Android devices without Google Services

### ISSUE THREAD

**Issue by muccy** [FirebaseExtended/flutterfire#4636]
## Bug report

**Describe the bug**
When you make an attempt to get the FCM token, you receive this uncaught exception:
```
'_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'String' in type cast
#0      new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:89:26)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#2      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:88:11)
#3      platformExceptionToFirebaseException
#4      convertPlatformException
#5      MethodChannelFirebaseMessaging.getToken
#6      FirebaseMessaging.getToken
```

While https://github.com/FirebaseExtended/flutterfire/issues/4088 has been closed, the problem has not been solved yet and I found a way to reproduce it on Android Emulator...

### Steps to reproduce

1. Create an AVD without Google Play Services
2. Call `FirebaseMessaging.instance.getToken()`
4. See the exception

### Expected behavior

`getToken` method is not marked to throw exceptions. It should throw a documented exception or return null.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.1 20C69 darwin-x64, locale it-IT)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.4
yummy_app_kit 0.1.4

dependencies:
- app_environment 0.0.1 [flutter]
- app_settings 4.0.4 [flutter]
- auto_size_text 2.1.0 [flutter]
- cupertino_icons 0.1.3
- easy_localization 2.3.3 [flutter intl shared_preferences args path flutter_localizations]
- event_bus 1.1.1
- flick_video_player 0.1.1 [flutter video_player provider wakelock]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_markdown 0.4.4 [flutter markdown meta path]
- geolocator 6.1.13 [flutter geolocator_platform_interface]
- google_api_availability 2.0.4 [flutter]
- google_maps_flutter 1.0.10 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- intl 0.16.1 [path]
- json_annotation 3.1.1
- map_launcher 0.12.2 [flutter flutter_svg]
- mobile_ordering 0.0.3 [flutter flutter_localizations collection cupertino_icons json_annotation intl flutter_markdown yummy_datastore yummy_header_footer json_api_fetch]
- native_pdf_view 3.9.0 [flutter extended_image synchronized native_pdf_renderer]
- package_info 0.4.3+2 [flutter]
- path 1.8.0-nullsafety.1
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- provider 4.3.2+3 [collection flutter nested]
- qr_flutter 3.2.0 [flutter qr]
- screen 0.0.5 [flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- store_redirect 1.0.2 [flutter]
- udp 0.0.4 [flutter http json_annotation push_notifications json_api_fetch]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- version 1.2.0
- video_player 0.10.12+5 [meta video_player_platform_interface video_player_web flutter]
- webview_flutter 1.0.7 [flutter]
- yummy_datastore 0.0.3 [flutter meta encrypt]
- yummy_header_footer 0.0.9 [flutter yummy_core_models yummy_core_ui]

dev dependencies:
- build_runner 1.10.12 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 3.5.1 [analyzer build build_config json_annotation meta path source_gen]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.1 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- asn1lib 0.8.1
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.6.1 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.5 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.5 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.2 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.6 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- cached_network_image 2.5.0 [flutter flutter_cache_manager octo_image]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- dart_style 1.3.10 [analyzer args path source_span]
- device_info 1.0.0 [flutter device_info_platform_interface]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- encrypt 4.1.0 [args asn1lib clock collection crypto pointycastle]
- extended_image 1.5.0 [flutter extended_image_library meta]
- extended_image_library 0.3.1 [flutter path_provider http_client_helper crypto path]
- extension 0.1.1
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 6.0.0-nullsafety.2 [meta path]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_driver 0.0.0 [file json_rpc_2 meta path web_socket_channel vm_service_client webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async matcher platform process pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- font_awesome_flutter 8.11.0 [flutter]
- fuchsia_remote_debug_protocol 0.0.0 [json_rpc_2 process web_socket_channel flutter_test flutter_driver archive args async boolean_selector charcode clock collection convert crypto fake_async file matcher meta path platform pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math vm_service_client webdriver]
- geolocator_platform_interface 1.0.8 [flutter meta plugin_platform_interface vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_maps_flutter_platform_interface 1.0.5 [flutter meta plugin_platform_interface stream_transform]
- graphs 0.2.0
- http 0.12.2 [http_parser path pedantic]
- http_client_helper 0.2.1 [http]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- icons_helper 1.0.6 [flutter font_awesome_flutter flutter_driver]
- image 2.1.19 [archive xml meta]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_api_fetch 0.0.2 [flutter http]
- json_rpc_2 2.2.2 [stack_trace stream_channel]
- logging 0.11.4
- markdown 2.1.8 [args charcode meta]
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- native_pdf_renderer 2.4.0 [flutter flutter_web_plugins device_info uuid image js meta extension synchronized]
- nested 0.0.4 [flutter]
- node_interop 1.2.1 [js]
- node_io 1.1.1 [node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 3.0.0-nullsafety.2
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 2.0.0
- pool 1.4.0 [async stack_trace]
- process 4.0.0-nullsafety.2 [file path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.7 [checked_yaml json_annotation pub_semver yaml]
- push_notifications 0.0.6 [flutter json_annotation]
- qr 1.3.0 [meta]
- quiver 2.1.5 [matcher meta]
- rxdart 0.25.0
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- smart_image 0.0.11 [flutter cached_network_image icons_helper]
- source_gen 0.9.10+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- sync_http 0.2.0
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4+1 [flutter flutter_web_plugins meta video_player_platform_interface]
- vm_service_client 0.2.6+2 [async collection json_rpc_2 pub_semver source_span stack_trace stream_channel web_socket_channel]
- wakelock 0.1.4+2 [flutter]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
- yummy_core_models 0.0.3 [flutter json_annotation]
- yummy_core_ui 0.0.7 [flutter smart_image]
```

</details>

---

**Comment by markusaksli-nc** [comment]
I was able to reproduce this with an Android 10.0 emulator without Google APIs. It probably makes sense that it doesn't work but the error message isn't very useful (but some debug messages before it are). Tested on the latest master `1.26.0-2.0.pre.296` with `firebase_messaging: ^8.0.0-dev.12` using the official example.
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 1.26.0-2.0.pre.296, on Microsoft Windows [Version 10.0.19041.685], locale et-EE)
    • Flutter version 1.26.0-2.0.pre.296 at C:\Development\flutter_master
    • Framework revision 737496e8db (7 hours ago), 2021-01-12 02:54:03 -0500
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 10 (API 29) (emulator)
    • Windows (desktop)                     • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.685]
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)                            • edge          • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
```
</details>

<details>
 <summary>Logs</summary>

```console
E/eglCodecCommon( 3607): glUtilsParamSize: unknow param 0x000082da
I/FLTFireMsgService( 3607): FlutterFirebaseMessagingBackgroundService started!
W/FirebaseInstanceId( 3607): Failed to find package android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms
W/Metadata( 3607): Failed to find package android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms
E/Metadata( 3607): Google Play services missing or without correct permission.
E/flutter ( 3607): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'String' in type cast
E/flutter ( 3607): #0      new LinkedHashMap.from.<anonymous closure> (dart:collection/linked_hash_map.dart:89:26)
E/flutter ( 3607): #1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:397:8)
E/flutter ( 3607): #2      new LinkedHashMap.from (dart:collection/linked_hash_map.dart:88:11)
E/flutter ( 3607): #3      platformExceptionToFirebaseException (package:firebase_messaging_platform_interface/src/method_channel/utils/exception.dart:26:9)
E/flutter ( 3607): #4      convertPlatformException (package:firebase_messaging_platform_interface/src/method_channel/utils/exception.dart:15:10)
E/flutter ( 3607): #5      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:227:13)
E/flutter ( 3607): <asynchronous suspension>
E/flutter ( 3607):
```
</details>

Thanks for narrowing down the cause. I think we can track the issue here instead of opening the old one.
