### ISSUE TITLE
Firebase sdk latest version

### ISSUE THREAD

**Issue by maxweo** [FirebaseExtended/flutterfire#4695]
## Bug report

**Describe the bug**
When i update the firebase sdk latest versions in app/build.gradle in my flutter App, i got error in  terminal

### Steps to reproduce
`dependencies {
    // Import the BoM for the Firebase platform
    implementation platform('com.google.firebase:firebase-bom:26.2.0')
    // Declare the dependency for the Analytics library
    // When using the BoM, you don't specify versions in Firebase library dependencies

    testImplementation 'junit:junit:4.13.1'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-messaging'
    implementation "androidx.core:core:1.3.2"
}`

```
W/ConnectionTracker( 7210): Exception thrown while unbinding
W/ConnectionTracker( 7210): java.lang.IllegalArgumentException: Service not registered: ls@6e1de7a
W/ConnectionTracker( 7210): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1586)
W/ConnectionTracker( 7210): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1692)
W/ConnectionTracker( 7210): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
W/ConnectionTracker( 7210): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):1)
W/ConnectionTracker( 7210): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):2)
W/ConnectionTracker( 7210): 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):9)
W/ConnectionTracker( 7210): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):3)
W/ConnectionTracker( 7210): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):3)
W/ConnectionTracker( 7210): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
W/ConnectionTracker( 7210): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker( 7210): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):5)
```

---

## Additional context

I encounter this problem as soon as I update the Sdk of Firebase CloudFirestore, Auth, messaging, but when I use the old versions I do not have this error  like

```
dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
    implementation 'com.google.firebase:firebase-auth:19.3.2'
    implementation 'com.google.firebase:firebase-firestore:21.6.0'
    implementation 'com.google.firebase:firebase-messaging:20.2.4'
    implementation 'com.onesignal:OneSignal:3.15.3'
    implementation "androidx.core:core:1.3.1"
}
```
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [version 10.0.18363.1082], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.52.1)
[√] Connected device (1 available)

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.0
Flutter SDK 1.22.0
skf 1.0.0+1

dependencies:
- animate_do 1.7.5 [flutter]
- animated_text 1.0.2 [flutter]
- animated_text_kit 2.5.4 [flutter characters]
- awesome_dialog 1.3.0 [flutter simple_animations flare_flutter]
- cached_network_image 2.5.0 [flutter flutter_cache_manager octo_image]
- carousel_slider 2.3.1 [flutter]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- concentric_transition 0.1.1 [flutter]
- connectivity 2.0.2 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- cupertino_icons 1.0.0
- date_time_picker 1.1.1 [flutter intl]
- date_util 0.1.4
- device_preview 0.4.8 [font_awesome_flutter http freezed_annotation json_annotation flutter flutter_localizations meta shared_preferences shared_preferences_macos]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_storage 4.0.1 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_animated_dialog 1.2.0 [flutter]
- flutter_arc_speed_dial 1.0.3 [flutter]
- flutter_custom_clippers 1.1.2 [flutter]
- flutter_icons 1.1.0 [flutter]
- flutter_local_notifications 3.0.3 [flutter platform flutter_local_notifications_platform_interface timezone]
- flutter_page_transition 0.1.6 [flutter]
- flutter_speed_dial 1.2.5 [flutter]
- flutter_spinkit 4.1.2+1 [flutter]
- flutter_styled_toast 1.4.0+1 [flutter flutter_localizations]
- fluttertoast 4.0.1 [flutter flutter_web_plugins]
- image_picker 0.6.7+21 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intent 1.4.0 [flutter]
- marquee 1.6.1 [flutter fading_edge_scrollview]
- phone_number 0.6.3 [flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- steps 1.0.1 [flutter]
- timeline_list 0.0.5 [flutter]
- upgrader 0.11.2 [flutter device_info flutter_device_locale http package_info shared_preferences url_launcher version xml]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_
scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- connectivity_for_web 0.3.1+4 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+7 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- device_info 0.4.2+10 [flutter device_info_platform_interface]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- fading_edge_scrollview 1.1.4 [flutter]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flare_dart 2.3.4
- flare_flutter 2.0.6 [flutter flare_dart meta]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_device_locale 0.4.0 [flutter flutter_web_plugins plugin_platform_interface]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- font_awesome_flutter 8.11.0 [flutter]
- freezed_annotation 0.11.0+1 [collection json_annotation meta]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- intl 0.16.1 [path]
- js 0.6.2
- json_annotation 3.1.1
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_info 0.4.3+2 [flutter]
- path 1.8.0-nullsafety.1
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- rxdart 0.25.0
- sa_v1_migration 1.1.2 [flutter]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- simple_animations 2.4.2 [flutter supercharged sa_v1_migration pedantic]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.1+2 [flutter sqflite_common path]
- sqflite_common 1.0.3 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- supercharged 1.12.0 [supercharged_dart flutter]
- supercharged_dart 1.4.0
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.5.9 [path]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- version 1.2.0
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
```

</details>

---

**Comment by maxweo** [comment]
> ## Bug report
> **Describe the bug**
> When i update the firebase sdk latest versions in app/build.gradle in my flutter App, i got error in terminal
> 
> ### Steps to reproduce
> `dependencies {
> // Import the BoM for the Firebase platform
> implementation platform('com.google.firebase:firebase-bom:26.2.0')
> // Declare the dependency for the Analytics library
> // When using the BoM, you don't specify versions in Firebase library dependencies
> 
> ```
> testImplementation 'junit:junit:4.13.1'
> androidTestImplementation 'androidx.test:runner:1.3.0'
> androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
> implementation 'com.google.firebase:firebase-analytics'
> implementation 'com.google.firebase:firebase-auth'
> implementation 'com.google.firebase:firebase-firestore'
> implementation 'com.google.firebase:firebase-messaging'
> implementation "androidx.core:core:1.3.2"
> ```
> 
> }`
> 
> Steps to reproduce the behavior:
> 
> `W/ConnectionTracker( 7210): Exception thrown while unbinding W/ConnectionTracker( 7210): java.lang.IllegalArgumentException: Service not registered: ls@6e1de7a W/ConnectionTracker( 7210): at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1586) W/ConnectionTracker( 7210): at android.app.ContextImpl.unbindService(ContextImpl.java:1692) W/ConnectionTracker( 7210): at android.content.ContextWrapper.unbindService(ContextWrapper.java:717) W/ConnectionTracker( 7210): at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):1) W/ConnectionTracker( 7210): at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):2) W/ConnectionTracker( 7210): at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):9) W/ConnectionTracker( 7210): at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):3) W/ConnectionTracker( 7210): at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):3) W/ConnectionTracker( 7210): at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) W/ConnectionTracker( 7210): at java.util.concurrent.FutureTask.run(FutureTask.java:266) W/ConnectionTracker( 7210): at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204714066@20.47.14 (100406-0):5)`
> 
> ## Additional context
> I encounter this problem as soon as I update the Sdk of Firebase CloudFirestore, Auth, messaging, but when I use the old versions I do not have this error like
> 
> ```
> dependencies {
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'androidx.test:runner:1.3.0'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
>     implementation 'com.google.firebase:firebase-auth:19.3.2'
>     implementation 'com.google.firebase:firebase-firestore:21.6.0'
>     implementation 'com.google.firebase:firebase-messaging:20.2.4'
>     implementation 'com.onesignal:OneSignal:3.15.3'
>     implementation "androidx.core:core:1.3.1"
> }
> ```
> 
> ### Flutter doctor
> Run `flutter doctor` and paste the output below:
> 
> Click To Expand
> ### Flutter dependencies
> Run `flutter pub deps -- --style=compact` and paste the output below:
> 
> Click To Expand

I was able to resolve the issue I was getting by following new installations of FlutterFire. Thank you !

**Comment by markusaksli-nc** [comment]
Hi @maxweo 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4090.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
