### ISSUE TITLE
🐛 [firebase_auth] [BUG] java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/browser/customtabs/CustomTabsIntent$Builder

### ISSUE THREAD

**Issue by bhanuka96** [FirebaseExtended/flutterfire#4708]
App crash after upgrade firebase plugins.

**Log** 

```
D/ViewRootImpl@772f307[MainActivity]( 3336): ViewPostIme pointer 0
D/ViewRootImpl@772f307[MainActivity]( 3336): ViewPostIme pointer 1
E/zzf     ( 3336): Problem retrieving SafetyNet Token: 7: 
D/ViewRootImpl@772f307[MainActivity]( 3336): MSG_WINDOW_FOCUS_CHANGED 0
W/zzdk    ( 3336): keyset not found, will generate a new one
W/zzdk    ( 3336): java.io.FileNotFoundException: can't read keyset; the pref value GenericIdpKeyset does not exist
W/zzdk    ( 3336): 	at com.google.android.gms.internal.firebase-auth-api.zzdo.zzc(com.google.firebase:firebase-auth@@20.0.1:10)
W/zzdk    ( 3336): 	at com.google.android.gms.internal.firebase-auth-api.zzdo.zzb(com.google.firebase:firebase-auth@@20.0.1:1)
W/zzdk    ( 3336): 	at com.google.android.gms.internal.firebase-auth-api.zzat.zzi(com.google.firebase:firebase-auth@@20.0.1:1)
W/zzdk    ( 3336): 	at com.google.android.gms.internal.firebase-auth-api.zzdj.zzi(com.google.firebase:firebase-auth@@20.0.1:1)
W/zzdk    ( 3336): 	at com.google.android.gms.internal.firebase-auth-api.zzdj.zzd(com.google.firebase:firebase-auth@@20.0.1:2)
W/zzdk    ( 3336): 	at com.google.firebase.auth.internal.zzk.<init>(com.google.firebase:firebase-auth@@20.0.1:7)
W/zzdk    ( 3336): 	at com.google.firebase.auth.internal.zzk.zza(com.google.firebase:firebase-auth@@20.0.1:3)
W/zzdk    ( 3336): 	at com.google.firebase.auth.internal.RecaptchaActivity.zzd(com.google.firebase:firebase-auth@@20.0.1:9)
W/zzdk    ( 3336): 	at com.google.android.gms.internal.firebase-auth-api.zzth.<init>(com.google.firebase:firebase-auth@@20.0.1:13)
W/zzdk    ( 3336): 	at com.google.firebase.auth.internal.RecaptchaActivity.onResume(com.google.firebase:firebase-auth@@20.0.1:43)
W/zzdk    ( 3336): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
W/zzdk    ( 3336): 	at android.app.Activity.performResume(Activity.java:7361)
W/zzdk    ( 3336): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
W/zzdk    ( 3336): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
W/zzdk    ( 3336): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
W/zzdk    ( 3336): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
W/zzdk    ( 3336): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
W/zzdk    ( 3336): 	at android.os.Handler.dispatchMessage(Handler.java:105)
W/zzdk    ( 3336): 	at android.os.Looper.loop(Looper.java:164)
W/zzdk    ( 3336): 	at android.app.ActivityThread.main(ActivityThread.java:6942)
W/zzdk    ( 3336): 	at java.lang.reflect.Method.invoke(Native Method)
W/zzdk    ( 3336): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
W/zzdk    ( 3336): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
W/System  ( 3336): Ignoring header X-Firebase-Locale because its value was null.
D/InputTransport( 3336): Input channel constructed: fd=95
I/System.out( 3336): (HTTPLog)-Static: isSBSettingEnabled false
D/ViewRootImpl@f16cb43[RecaptchaActivity]( 3336): setView = DecorView@e1c2f9[RecaptchaActivity] TM=true MM=false
I/System.out( 3336): (HTTPLog)-Static: isSBSettingEnabled false
D/ViewRootImpl@f16cb43[RecaptchaActivity]( 3336): dispatchAttachedToWindow
V/Surface ( 3336): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@f16cb43[RecaptchaActivity]( 3336): Relayout returned: old=[0,0][0,0] new=[0,0][1080,1920] result=0x7 surface={valid=true 480665407488} changed=true
D/OpenGLRenderer( 3336): eglCreateWindowSurface = 0x6fece55540
W/Activity( 3336): AppLock checkAppLockState locked:false verifying:false pkgName = com.yellochat.dev isInMultiWindowMode:false showWhenLocked:false
D/ViewRootImpl@f16cb43[RecaptchaActivity]( 3336): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
D/ViewRootImpl@f16cb43[RecaptchaActivity]( 3336): MSG_WINDOW_FOCUS_CHANGED 1
V/InputMethodManager( 3336): Starting input: tba=android.view.inputmethod.EditorInfo@566ddec nm : com.yellochat.dev ic=null
I/InputMethodManager( 3336): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 3336): Input channel constructed: fd=129
D/InputTransport( 3336): Input channel destroyed: fd=96
D/AndroidRuntime( 3336): Shutting down VM
E/AndroidRuntime( 3336): FATAL EXCEPTION: main
E/AndroidRuntime( 3336): Process: com.yellochat.dev, PID: 3336
E/AndroidRuntime( 3336): java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/browser/customtabs/CustomTabsIntent$Builder;
E/AndroidRuntime( 3336): 	at com.google.firebase.auth.internal.RecaptchaActivity.zza(com.google.firebase:firebase-auth@@20.0.1:13)
E/AndroidRuntime( 3336): 	at com.google.android.gms.internal.firebase-auth-api.zzth.zzb(com.google.firebase:firebase-auth@@20.0.1:7)
E/AndroidRuntime( 3336): 	at com.google.android.gms.internal.firebase-auth-api.zzth.onPostExecute(Unknown Source:2)
E/AndroidRuntime( 3336): 	at android.os.AsyncTask.finish(AsyncTask.java:695)
E/AndroidRuntime( 3336): 	at android.os.AsyncTask.-wrap1(Unknown Source:0)
E/AndroidRuntime( 3336): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
E/AndroidRuntime( 3336): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 3336): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 3336): 	at android.app.ActivityThread.main(ActivityThread.java:6942)
E/AndroidRuntime( 3336): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3336): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime( 3336): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime( 3336): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.browser.customtabs.CustomTabsIntent$Builder" on path: DexPathList[[zip file "/data/app/com.yellochat.dev-_VW8wvzSrpGLWw8FnqANLA==/base.apk"],nativeLibraryDirectories=[/data/app/com.yellochat.dev-_VW8wvzSrpGLWw8FnqANLA==/lib/arm64, /data/app/com.yellochat.dev-_VW8wvzSrpGLWw8FnqANLA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
E/AndroidRuntime( 3336): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
E/AndroidRuntime( 3336): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 3336): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 3336): 	... 12 more
```

**Flutter doctor -v**

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-LK)
    • Flutter version 1.22.5 at /Users/bhanukaisuru/flutter
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/bhanukaisuru/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9245
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • SM C701F (mobile) • b4d0901d • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

All packages

```
 cached_network_image: ^2.5.0
  carousel_slider: ^2.3.1
  cloud_firestore: ^0.16.0
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.0
  device_info: '>=1.0.0 <2.0.0'
  emoji_picker: ^0.1.0
  file_picker: ^2.1.5+1
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_database: ^6.0.0
  firebase_dynamic_links: ^0.7.0+1
  firebase_messaging: ^8.0.0-dev.14
  firebase_remote_config: ^0.6.0
  firebase_storage: ^7.0.0
  flutter_google_places: ^0.2.6
  flutter_html: ^1.2.0
  flutter_keyboard_visibility: ^4.0.2
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.1
  flutter_sound: ^7.5.1+2
  fluttertoast: ^7.1.6
  geocoder: ^0.2.1
  geolocator: ^6.1.13
  get_it: ^5.0.4
  google_maps_webservice: ^0.0.19
  image_picker: ^0.6.7+21
  intl: ^0.16.0
  just_audio: ^0.6.5
  lottie: ^0.7.0+1
  mapbox_search: ^2.0.1+1
  navigation_history_observer: ^1.0.3+1
  open_file: ^3.0.3
  package_info: ^0.4.3+2
  path_provider: ^1.6.27
  permission_handler: ^5.0.1+1
  photo_view: ^0.10.3
  provider: ^4.3.2+4
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  smooth_page_indicator: ^0.2.0
  strings: ^0.1.4
  transparent_image: ^1.0.0
  url_launcher: ^5.7.10
```

**app build gradle**

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-messaging:21.0.1'
    }
```

**android build**

```
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
```

**Comment by bhanuka96** [comment]
I add this line to the `build`. Now it's working. but navigate to the browser and then redirect to the app. It's happening when I upgrade from `0.18.4+1` to `0.20.0+1`

`implementation "androidx.browser:browser:1.2.0"`

**Comment by markusaksli-nc** [comment]
Hi @bhanuka96 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4651.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
