### ISSUE TITLE
[firebase_auth] anonymous sign in fails with NPE

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#474]
I am trying to do anonymous sign in to Firebase:

```dart
class _MyHomePageState extends State<MyHomePage> {
  final FirebaseAuth _auth = FirebaseAuth.instance;

  @override
  void initState() {
    super.initState();
    _handleSignIn();
  }

  Future<FirebaseUser> _handleSignIn() async {
    final FirebaseUser user = await _auth.signInAnonymously();
    print("signed in " + user.displayName);
    return user;
  }
}
```
The exception is:
```
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInAnonymously()' on a null object reference
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleSignInAnonymously(FirebaseAuthPlugin.java:292)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:86)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at android.app.ActivityThread.main(ActivityThread.java:6776)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
E/MethodChannel#plugins.flutter.io/firebase_auth(15551): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
E/flutter (15551): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (15551): PlatformException(error, Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.firebase.auth.FirebaseAuth.signInAnonymously()' on a null object reference, null)
E/flutter (15551): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter (15551): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:292:18)
E/flutter (15551): <asynchronous suspension>
E/flutter (15551): #2      FirebaseAuth.signInAnonymously (file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.0+1/lib/src/firebase_auth.dart:85:10)
E/flutter (15551): <asynchronous suspension>
E/flutter (15551): #3      _MyHomePageState._handleSignIn (package:shopping_list_flutter/main.dart:98:43)
E/flutter (15551): <asynchronous suspension>
E/flutter (15551): #4      _MyHomePageState.initState (package:shopping_list_flutter/main.dart:67:5)
E/flutter (15551): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter (15551): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (15551): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (15551): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (15551): #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (15551): #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (15551): #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (15551): #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (15551): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (15551): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (15551): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter (15551): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (15551): #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (15551): #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (15551): #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter (15551): #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (15551): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter (15551): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter (15551): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter (15551): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter (15551): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter (15551): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter (15551): #42     Element.updateChild (packag
```
Dependencies are:
```
  firebase_auth: ^0.8.0+1
  google_sign_in: ^4.0.0
```
Doctor:
```
C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (9 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:/Android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:/Android_sdk
    • Java binary at: C:\Program Files\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • SM A310F • 310084d1272f13c7 • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.
Process finished with exit code 0
```
The log says Flutter plugins not installed but in fact they are installed.

**Comment by kroikie** [comment]
@autolainen

The issue at https://github.com/flutter/flutter/issues/27300 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @autolainen
Did the proposed solutions [[1](https://github.com/flutter/flutter/issues/27300#issuecomment-507060063), [2](https://github.com/flutter/flutter/issues/27300#issuecomment-528680075)] worked? 
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by sgehrman** [comment]
I have the same problem.  I tried those two options mentioned.
