### ISSUE TITLE
🐛 [Cloud_Firestore] For Android I'm unable to Build the APK

### ISSUE THREAD

**Issue by TakeAchance365** [FirebaseExtended/flutterfire#4793]
## Bug report

**Describe the bug**

### Steps to reproduce

here is the main Firebase Code I have used in my app and to give you and better idea the app runs great on IOS and so the only problem that i am Having is With the Android Version 
```
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:haleyvillehigh/Main_App/App_Pages/Facultyandstaffpage/Loading/Loading.dart';
import 'package:haleyvillehigh/Main_App/Sendmail/Sendmail.dart';


void main() {
  runApp(Admintab());
}

class Admintab extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
        home: LoadFirebase());
  }
}

class LoadFirebase extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      // Initialize FlutterFire
      future: Firebase.initializeApp(),
      builder: (context, snapshot) {
        // Check for errors
        if (snapshot.hasError) {
          return LoadingError();
        }

        // Once complete, show your application
        if (snapshot.connectionState == ConnectionState.done) {
          return MyHomePage();
        }

        // Otherwise, show something whilst waiting for initialization to complete
        return Loading();
      },
    );
  }
}

class LoadingError extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Container(
           
            child: Text('Loading problem... Please try again...')));
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
       
        body: FirebaseMessages());
  }
}

class FirebaseMessages extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    CollectionReference messages =
        FirebaseFirestore.instance.collection('administration');

    return StreamBuilder<QuerySnapshot>(
      stream: messages.snapshots(),
      builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
        if (snapshot.hasError) {
          return Text('Administration Info failed to load. ');
        }

        if (snapshot.connectionState == ConnectionState.waiting) {
          return Loading();
        }

         return new ListView(
          children: snapshot.data.docs.map((DocumentSnapshot document) {
            return new ListTile(
              leading: Image.network(document.data()["profilepic"]),
              title: new Text(document.data()['name']),
              subtitle: new Text(document.data()['job']),
              trailing: RaisedButton.icon(
                textColor: Colors.white,
                color: Colors.red,
                icon: Icon(Icons.mail),onPressed: () {
                        customLaunch(document.data()["schoolemail"]);
                      }, label: Text("Email Me"),
            ));
          }).toList(),
        );
      },
    );
      
    
  }
}
```

### Expected behavior

For the Android App to Build the APK and run the app and I'm also using a physical device running Android Os 4.1.2 

## Additional context

I'm using Visual Studio Code and when I would start debugging in the debug console I will get this 

```
Launching lib/main.dart on MAGNUS01111116048791 in debug mode...
lib/main.dart
E/AndroidRuntime(22657): FATAL EXCEPTION: main
E/AndroidRuntime(22657): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(22657): at android.app.ActivityThread.installProvider(ActivityThread.java:4673)
E/AndroidRuntime(22657): at android.app.ActivityThread.installContentProviders(ActivityThread.java:4300)
E/AndroidRuntime(22657): at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4242)
E/AndroidRuntime(22657): at android.app.ActivityThread.access$1300(ActivityThread.java:133)
E/AndroidRuntime(22657): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
E/AndroidRuntime(22657): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22657): at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(22657): at android.app.ActivityThread.main(ActivityThread.java:4855)
E/AndroidRuntime(22657): at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(22657): at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(22657): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(22657): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime(22657): at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(22657): Caused by: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(22657): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
E/AndroidRuntime(22657): at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/AndroidRuntime(22657): at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/AndroidRuntime(22657): at android.app.ActivityThread.installProvider(ActivityThread.java:4658)
E/AndroidRuntime(22657): ... 12 more
E/AndroidRuntime(22924): FATAL EXCEPTION: main
E/AndroidRuntime(22924): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(22924): at android.app.ActivityThread.installProvider(ActivityThread.java:4673)
E/AndroidRuntime(22924): at android.app.ActivityThread.installContentProviders(ActivityThread.java:4300)
E/AndroidRuntime(22924): at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4242)
E/AndroidRuntime(22924): at android.app.ActivityThread.access$1300(ActivityThread.java:133)
E/AndroidRuntime(22924): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
E/AndroidRuntime(22924): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22924): at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(22924): at android.app.ActivityThread.main(ActivityThread.java:4855)
E/AndroidRuntime(22924): at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(22924): at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(22924): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(22924): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime(22924): at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(22924): Caused by: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(22924): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
E/AndroidRuntime(22924): at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/AndroidRuntime(22924): at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/AndroidRuntime(22924): at android.app.ActivityThread.installProvider(ActivityThread.java:4658)
E/AndroidRuntime(22924): ... 12 more
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
E/AndroidRuntime(23134): FATAL EXCEPTION: main
E/AndroidRuntime(23134): java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(23134): at android.app.ActivityThread.installProvider(ActivityThread.java:4673)
E/AndroidRuntime(23134): at android.app.ActivityThread.installContentProviders(ActivityThread.java:4300)
E/AndroidRuntime(23134): at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4242)
E/AndroidRuntime(23134): at android.app.ActivityThread.access$1300(ActivityThread.java:133)
E/AndroidRuntime(23134): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
E/AndroidRuntime(23134): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23134): at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(23134): at android.app.ActivityThread.main(ActivityThread.java:4855)
E/AndroidRuntime(23134): at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(23134): at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(23134): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime(23134): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime(23134): at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(23134): Caused by: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
E/AndroidRuntime(23134): at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
E/AndroidRuntime(23134): at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
E/AndroidRuntime(23134): at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
E/AndroidRuntime(23134): at android.app.ActivityThread.installProvider(ActivityThread.java:4658)
E/AndroidRuntime(23134): ... 12 more
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Chances-Mini:haleyvillehigh charris$ flutter doctor
Doctor summary (to see all details, run flutter
doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1
    20C69 darwin-arm, locale en-US)
 
Checking Android licenses is taking an unexpectedly Checking Android licenses is taking an unexpectedly Checking Android licenses is taking an unexpectedly Checking Android licenses is taking an unexpectedly Checking Android licenses is taking an unexpectedly 
Chances-Mini:haleyvillehigh charris$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1
    20C69 darwin-arm, locale en-US)
    • Flutter version 1.22.5 at
      /Users/charris/Documents/Development/flutter
    • Framework revision 7891006299 (6 weeks ago),
      2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
Checking Android licenses is taking an unexpectedly Checking Android licenses is taking an unexpectedly Checking Android licenses is taking an unexpectedly Checking Android licenses is taking an unexpectedly Checking Android licenses is taking an unexpectedly Checking Android licenses is taking an unexpectedly Checking Android licenses is taking an unexpectedly                                                     [✓] Android toolchain - develop for Android devices
    (Android SDK version 30.0.2)
    • Android SDK at
      /Users/charris/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/
      java
    • Java version OpenJDK Runtime Environment
      (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at
      /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    ✗ Flutter plugin not installed; this adds
      Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart
      specific functionality.
    • Java version OpenJDK Runtime Environment
      (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio
      Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • MAGNUS01111116048791 (mobile) •
      MAGNUS01111116048791 • android-arm • Android
      4.1.2 (API 16)

! Doctor found issues in 1 category.
Chances-Mini:haleyvillehigh charris$ 
```
</details>

---

### Flutter dependencies
<details>
 <summary>Logs</summary>

```console
dependencies:
- app_info 0.0.1 [flutter]
- cached_network_image 2.5.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 0.16.0 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 1.0.0
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.4.0+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- font_awesome_flutter 8.11.0 [flutter]
- http 0.12.2 [http_parser path pedantic]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- webfeed 0.6.0 [xml intl]
- webview_flutter 1.0.7 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 3.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.6 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.1 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- intl 0.16.1 [path]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- octo_image 0.3.0 [flutter flutter_blurhash]
- path 1.8.0-nullsafety.1
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- rxdart 0.25.0
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.2+2 [flutter sqflite_common path]
- sqflite_common 1.0.3 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
Chances-Mini:haleyvillehigh charris$ 
```
</details>

**Comment by TakeAchance365** [comment]
and if you would like me to I can upload my project to GitHub like it is right now and give you permission to it so you can play around with it if that would be more help to everyone to figure out what is happening

**Comment by markusaksli-nc** [comment]
Hi @TakeAchance365 
Could you please try adding multiDex https://firebase.flutter.dev/docs/installation/android#enabling-multidex
Thank you

**Comment by TakeAchance365** [comment]
Hi @markusaksli-nc I have already tried that and it didn't work here is the code if your wondering I've done and researched everything that I can think of so getting help here has truly felt like my last thing to do 
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.haleyvillestudios.haleyvillehigh"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:26.3.0')
    implementation 'com.google.firebase:firebase-analytics'
    

}

**Comment by TakeAchance365** [comment]
@markusaksli-nc I Recompiled it again and I got the samething plus this part 

![Screen Shot 2021-01-25 at 6 09 53 PM](https://user-images.githubusercontent.com/45086315/105781674-8d65d300-5f38-11eb-9212-d96a087e2c48.png)

**Comment by markusaksli-nc** [comment]
It seems you have not added
```gradle
implementation 'com.android.support:multidex:1.0.3'
```
to the dependencies as shown in the documentation.

**Comment by TakeAchance365** [comment]
hey guys sorry I've been sick but I think I fixed the problem I had to add some more code to the main.dart file plus what @markusaksli-nc  said about the implementation 'com.android.support:multidex:1.0.3' but here is the code that made it work 

import 'package:flutter/material.dart';

// Import the firebase_core plugin
import 'package:firebase_core/firebase_core.dart';
import 'package:hhsapp/Main_App/Pages/Homepage/Homepage.dart';
import 'package:hhsapp/Main_App/Services/Loading/HHS_MainApp_LoadError_Page/MainApp_Errorpage.dart';



void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(HHSMainapp());
}

class HHSMainapp extends StatefulWidget {
  _HHSMainappState createState() => _HHSMainappState();
}

class _HHSMainappState extends State<HHSMainapp> {
  // Set default `_initialized` and `_error` state to false
  bool _initialized = false;
  bool _error = false;

  // Define an async function to initialize FlutterFire
  void initializeFlutterFire() async {
    try {
      // Wait for Firebase to initialize and set `_initialized` state to true
      await Firebase.initializeApp();
      setState(() {
        _initialized = true;
      });
    } catch(e) {
      // Set `_error` state to true if Firebase initialization fails
      setState(() {
        _error = true;
      });
    }
  }

  @override
  void initState() {
    initializeFlutterFire();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // Show error message if initialization failed
    if(_error) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: MainappError(),
      );
    }

    // Show a loader until FlutterFire is initialized
    if (!_initialized) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Homepage(),
      );
    }

    return Homepage();
  }
}
