### ISSUE TITLE
🐛 [cloud_firestore] Null Pointer Exception related to TransactionStreamHandler.java showing in v0.16.0

### ISSUE THREAD

**Issue by mk-dev-1** [FirebaseExtended/flutterfire#4872]
## Bug report

**Describe the bug**

Since upgrading all firebase plugins to the latest version, I am seeing the below error message quite regularly in Crashlytics and Google Play Console.

Google Play Console
```java
java.lang.NullPointerException: 
  at io.flutter.plugins.firebase.firestore.streamhandler.TransactionStreamHandler.a (TransactionStreamHandler.java:90)
  at io.flutter.plugins.firebase.firestore.streamhandler.-$$Lambda$TransactionStreamHandler$uqlCFFZFR0Oy4NBxOz-rIuvJUN8.onComplete (-.java:6)
  at com.google.android.gms.tasks.zzi.run (zzi.java:23)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at com.google.android.gms.internal.tasks.zzb.dispatchMessage (zzb.java)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8167)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
```

Crashlytics:
```java
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
       at io.flutter.plugins.firebase.firestore.streamhandler.TransactionStreamHandler.a(TransactionStreamHandler.java:90)
       at io.flutter.plugins.firebase.firestore.streamhandler.-$$Lambda$TransactionStreamHandler$uqlCFFZFR0Oy4NBxOz-rIuvJUN8.onComplete(-.java:6)
       at com.google.android.gms.tasks.zzi.run(zzi.java:23)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.google.android.gms.internal.tasks.zzb.dispatchMessage(zzb.java)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

### Steps to reproduce

I'm afraid I am still unsure how to reproduce the error. No Firebase / cloud_firestore related code has changed on my side since I have upgraded to the latest version. All I have is the reported error, I can't even reproduce it myself. There are no results on StackOverflow on this either that could indicate it is related to my code. There currently is exactly one occasion where my app actively uses transactions (it's that low because of historic issues related to offline handling with transactions):

```dart
return FirebaseFirestore.instance.runTransaction transaction) async {
      DocumentSnapshot snapshot = await transaction.get(reference);
      if (snapshot.exists) {
        transaction.update(reference, {field: FieldValue.increment(value)});
      }
});
```

### Expected behavior

This error should not exist.

---

## pubspec.yaml

<details><summary>Click To Expand</summary>

```
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  apple_sign_in: ^0.1.0
  auto_size_text: ^2.1.0
  **cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0**
  connectivity: 0.4.3+7
  csv: ^4.1.0
  cupertino_icons: ^1.0.0
  currency: ^0.0.5
  device_info: ^1.0.0
  file_picker: ^2.1.5+1
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0
  firebase_crashlytics: ^0.4.0
  firebase_remote_config: ^0.6.0
  firebase_storage: ^7.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_calendar_carousel: ^1.4.11
  flutter_downloader: ^1.1.9
  flutter_inapp_purchase: ^3.0.0
  flutter_layouts: ^0.0.2+1
  flutter_local_notifications: ^3.0.3
  flutter_native_timezone: ^1.0.4
  get_it: ^5.0.4
  google_sign_in: ^4.5.9
  http: ^0.12.1
  in_app_review: ^1.0.2
  intl: ^0.16.0
  intl_translation: 
  json_annotation: ^3.0.0
  onesignal_flutter: ^2.6.1
  package_info: ^0.4.0+6
  path_provider: ^1.6.27
  permission_handler: ^5.0.1+1
  purchases_flutter: ^2.0.0
  quick_actions: ^0.4.0+6
  rx_command: ^5.0.2
  share: ^0.6.2+1
  shared_preferences: ^0.5.12+4
  syncfusion_flutter_charts: ^18.4.34
  timezone: ^0.5.6
  url_launcher: ^5.1.2
```

</details>

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

(I am unsure why it looks like it does. Android Studio is there, everything's working as expected...)
Running `flutter doctor --android-licenses` throws an error...
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.5
health 1.47.0+145

dependencies:
- apple_sign_in 0.1.0 [flutter]
- auto_size_text 2.1.0 [flutter]
- cloud_firestore 0.16.0 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_functions 0.9.0 [meta flutter firebase_core firebase_core_platform_interface cloud_functions_platform_interface cloud_functions_web]
- connectivity 0.4.3+7 [flutter meta]
- csv 4.1.0
- cupertino_icons 1.0.0
- currency 0.0.5
- device_info 1.0.0 [flutter device_info_platform_interface]
- file_picker 2.1.5+1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 7.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.20.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_crashlytics 0.4.0+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_remote_config 0.6.0 [flutter firebase_core]
- firebase_storage 7.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_calendar_carousel 1.5.2 [intl flutter]
- flutter_downloader 1.5.2 [flutter]
- flutter_inapp_purchase 3.0.1 [http meta flutter platform]
- flutter_layouts 0.0.2+1 [flutter]
- flutter_local_notifications 3.0.3 [flutter platform flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_native_timezone 1.0.4 [flutter]
- get_it 5.0.4 [async meta]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- in_app_review 1.0.4 [flutter in_app_review_platform_interface]
- intl 0.16.1 [path]
- intl_translation 0.17.10+1 [analyzer args dart_style intl path petitparser]
- json_annotation 3.1.1
- onesignal_flutter 2.6.2 [flutter]
- package_info 0.4.3+2 [flutter]
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- purchases_flutter 2.0.0 [flutter]
- quick_actions 0.4.0+10 [flutter meta]
- rx_command 5.3.0 [rxdart quiver_hashcode]
- share 0.6.5+4 [meta mime flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- syncfusion_flutter_charts 18.4.35 [flutter intl vector_math syncfusion_flutter_core]
- timezone 0.5.9 [path]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]

dev dependencies:
- build_runner 1.10.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- json_serializable 3.5.1 [analyzer build build_config json_annotation meta path source_gen]

transitive dependencies:
- _fe_analyzer_shared 7.0.0 [meta]
- analyzer 0.39.17 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- args 1.6.0
- async 2.4.2 [collection]
- build 1.3.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.6 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.3.11 [analyzer build crypto graphs logging path package_config pub_semver]
- build_runner_core 6.0.1 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.1.3
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- cloud_firestore_platform_interface 3.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 4.0.1 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 3.1.3 [firebase_core firebase_core_web cloud_functions_platform_interface flutter flutter_web_plugins http_parser meta js]
- code_builder 3.6.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 3.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+6 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.6 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_platform_interface 1.0.4 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+3 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 0.10.11
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 0.2.0
- html 0.14.0+4 [csslib source_span]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- in_app_review_platform_interface 1.0.5 [flutter url_launcher plugin_platform_interface platform]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- logging 0.11.4
- matcher 0.12.9 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.7 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.5 [matcher meta]
- quiver_hashcode 2.0.0
- rxdart 0.25.0
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+2 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.7.0 [charcode collection meta path term_glyph]
- stack_trace 1.9.6 [path]
- stream_channel 2.0.0 [async]
- stream_transform 1.2.0
- string_scanner 1.0.5 [charcode meta source_span]
- syncfusion_flutter_core 18.4.35+1 [flutter]
- term_glyph 1.1.0
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0-nullsafety.3
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by russellwheatley** [comment]
I believe this should've been fixed in #4209. Will reopen if this is not the case.
