### ISSUE TITLE
Error: [firebase_auth/unknown] An unknown error occurred: NoSuchMethodError: tried to call a non-function, such as null: 'this.jsObject.useEmulator'

### ISSUE THREAD

**Issue by slateandchalk** [FirebaseExtended/flutterfire#4894]
## Bug report

I try to use emulator for auth. Android device is working fine. but, IOS and web showing error.

<details><summary>Console Log</summary>

```
Error: [firebase_auth/unknown] An unknown error occurred: NoSuchMethodError: tried to call a non-function, such as null: 'this.jsObject.useEmulator'
    at Object.throw_ [as throw] (http://localhost:53344/dart_sdk.js:4361:11)
    at firebase_auth_web.FirebaseAuthWeb.new.useEmulator (http://localhost:53344/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:371:23)
    at useEmulator.next (<anonymous>)
    at runBody (http://localhost:53344/dart_sdk.js:38027:34)
    at Object._async [as async] (http://localhost:53344/dart_sdk.js:38058:7)
    at firebase_auth_web.FirebaseAuthWeb.new.useEmulator (http://localhost:53344/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:365:20)
    at firebase_auth.FirebaseAuth.__.useEmulator (http://localhost:53344/packages/firebase_auth/firebase_auth.dart.lib.js:128:32)
    at useEmulator.next (<anonymous>)
    at runBody (http://localhost:53344/dart_sdk.js:38027:34)
    at Object._async [as async] (http://localhost:53344/dart_sdk.js:38058:7)
    at firebase_auth.FirebaseAuth.__.useEmulator (http://localhost:53344/packages/firebase_auth/firebase_auth.dart.lib.js:111:20)
    at main$ (http://localhost:53344/packages/sac_flutter/main.dart.lib.js:607:49)
    at main$.next (<anonymous>)
    at http://localhost:53344/dart_sdk.js:38007:33
    at _RootZone.runUnary (http://localhost:53344/dart_sdk.js:37861:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:53344/dart_sdk.js:32822:29)
    at handleValueCallback (http://localhost:53344/dart_sdk.js:33370:49)
    at Function._propagateToListeners (http://localhost:53344/dart_sdk.js:33408:17)
    at _Future.new.[_completeWithValue] (http://localhost:53344/dart_sdk.js:33250:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53344/dart_sdk.js:33273:35)
    at Object._microtaskLoop (http://localhost:53344/dart_sdk.js:38122:13)
    at _startMicrotaskLoop (http://localhost:53344/dart_sdk.js:38128:13)
    at http://localhost:53344/dart_sdk.js:33625:9
```

</details>

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0-133.7.beta
Flutter SDK 1.25.0-8.3.pre
sac_flutter 1.0.0+1

dependencies:
- cupertino_icons 1.0.2
- firebase_auth 0.21.0-1.1.nullsafety.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 0.8.0-1.0.nullsafety.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_signin_button 1.1.0 [flutter font_awesome_flutter]
- google_sign_in 5.0.0-nullsafety [google_sign_in_platform_interface flutter meta]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- integration_test 0.9.2+2 [flutter flutter_driver flutter_test path test_core vm_service _fe_analyzer_shared analyzer archive args async boolean_selector characters charcode cli_util clock collection convert coverage crypto fake_async file glob io js logging matcher meta node_interop node_io package_config pool pub_semver source_map_stack_trace source_maps source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math watcher webdriver yaml]

transitive dependencies:
- _fe_analyzer_shared 12.0.0 [meta]
- analyzer 0.40.6 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.3 [collection]
- boolean_selector 2.1.0-nullsafety.3 [source_span string_scanner]
- characters 1.1.0-nullsafety.5
- charcode 1.2.0-nullsafety.3
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.3
- collection 1.15.0-nullsafety.5
- convert 2.1.1 [charcode typed_data]
- coverage 0.14.2 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0-nullsafety.3 [clock collection]
- file 6.0.0-nullsafety.4 [meta path]
- firebase_auth_platform_interface 4.0.0-1.1.nullsafety.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 0.4.0-1.1.nullsafety.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0-1.0.nullsafety.0 [flutter meta plugin_platform_interface]
- firebase_core_web 0.3.0-1.0.nullsafety.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_driver 0.0.0 [file meta path vm_service webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async json_rpc_2 matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math web_socket_channel]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 8.11.0 [flutter]
- fuchsia_remote_debug_protocol 0.0.0 [json_rpc_2 process web_socket_channel flutter_test flutter_driver archive args async boolean_selector charcode clock collection convert crypto fake_async file matcher meta path platform source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math vm_service webdriver]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 2.0.0-nullsafety [flutter meta quiver]
- http_parser 4.0.0-nullsafety [charcode collection source_span string_scanner typed_data]
- intl 0.17.0-nullsafety.2 [clock path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3-nullsafety.3
- json_rpc_2 2.2.2 [stack_trace stream_channel]
- logging 0.11.4
- matcher 0.12.10-nullsafety.3 [stack_trace]
- meta 1.3.0-nullsafety.6
- node_interop 1.2.1 [js]
- node_io 1.1.1 [node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.3
- pedantic 1.10.0-nullsafety.3
- platform 3.0.0-nullsafety.4
- plugin_platform_interface 1.1.0-nullsafety.1 [meta]
- pool 1.5.0-nullsafety.3 [async stack_trace]
- process 4.0.0-nullsafety.4 [file path platform]
- pub_semver 1.4.4 [collection]
- quiver 3.0.0-nullsafety.3 [matcher]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0-nullsafety.4 [path stack_trace source_maps]
- source_maps 0.10.10-nullsafety.3 [source_span]
- source_span 1.8.0-nullsafety.4 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.6 [path]
- stream_channel 2.1.0-nullsafety.3 [async]
- string_scanner 1.1.0-nullsafety.3 [charcode source_span]
- sync_http 0.2.0
- term_glyph 1.2.0-nullsafety.3
- test_api 0.2.19-nullsafety.6 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.12-nullsafety.9 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.0-nullsafety.5 [collection]
- vector_math 2.1.0-nullsafety.5
- vm_service 5.5.0 [meta]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- yaml 2.2.1 [charcode collection string_scanner source_span]

```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @slateandchalk 
There's an open issue addressing the support for auth emulator https://github.com/FirebaseExtended/flutterfire/issues/3980.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by wtfiwtz** [comment]
https://github.com/FirebaseExtended/flutterfire/pull/5171/files
