### ISSUE TITLE
🐛 [firebase_ml_vision] Release Apk Build Issue

### ISSUE THREAD

**Issue by farsuller** [FirebaseExtended/flutterfire#4960]
**Here's my gradle and pubspec**
<img width="533" alt="app-gradle" src="https://user-images.githubusercontent.com/64140869/107048773-46af8d00-6804-11eb-8806-183a649995f7.PNG">
<img width="217" alt="pubspec" src="https://user-images.githubusercontent.com/64140869/107048785-4a431400-6804-11eb-8710-9e72dd3330fb.PNG">

**I have issue on flutter build apk release, then I tried appbundle release its successfully build..**
<img width="562" alt="1" src="https://user-images.githubusercontent.com/64140869/107048637-254ea100-6804-11eb-99fe-de64dea7f2d9.PNG">

**Here's the flutter build apk --release --verbose**
<img width="520" alt="2" src="https://user-images.githubusercontent.com/64140869/107048454-eddff480-6803-11eb-9787-bd0f902b2b2d.PNG">

```
C:\Users\....\flutter build apk --release --verbose
[ +330 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9b2d32b605630f28625709ebd9d78ab3016b2bf6
[        ] executing: [C:\flutter/] git tag --points-at HEAD
[  +41 ms] Exit code 0 from: git tag --points-at HEAD
[   +1 ms] 1.22.6
[  +19 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\flutter/] git ls-remote --get-url origin
[  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +125 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +38 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +12 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +93 ms] Found plugin camera at C:\flutter\.pub-cache\hosted\pub.dartlang.org\camera-0.7.0+2\
[   +9 ms] Found plugin cloud_firestore at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0\
[   +3 ms] Found plugin cloud_firestore_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+1\
[   +3 ms] Found plugin connectivity at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-2.0.2\
[   +2 ms] Found plugin connectivity_for_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_for_web-0.3.1+4\
[   +1 ms] Found plugin connectivity_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+7\
[  +10 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.0+1\
[   +3 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.2+6\
[   +1 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +3 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +2 ms] Found plugin firebase_ml_vision at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_ml_vision-0.10.0\
[   +8 ms] Found plugin flutter_plugin_android_lifecycle at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[   +7 ms] Found plugin image_picker at C:\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+22\
[   +8 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.27\
[   +1 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +2 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +2 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[  +13 ms] Found plugin tflite_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\tflite_flutter-0.5.0\
[   +2 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.10\
[   +1 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+4\
[   +1 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+9\
[   +2 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.5+3\
[   +1 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-0.0.1+3\
[ +224 ms] Found plugin camera at C:\flutter\.pub-cache\hosted\pub.dartlang.org\camera-0.7.0+2\
[   +3 ms] Found plugin cloud_firestore at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.16.0\
[   +1 ms] Found plugin cloud_firestore_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.3.0+1\
[   +1 ms] Found plugin connectivity at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-2.0.2\
[   +1 ms] Found plugin connectivity_for_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_for_web-0.3.1+4\
[   +1 ms] Found plugin connectivity_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\connectivity_macos-0.1.0+7\
[   +6 ms] Found plugin firebase_auth at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.20.0+1\
[   +1 ms] Found plugin firebase_auth_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.3.2+6\
[   +1 ms] Found plugin firebase_core at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.7.0\
[   +1 ms] Found plugin firebase_core_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.2.1+3\
[   +1 ms] Found plugin firebase_ml_vision at C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_ml_vision-0.10.0\
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at C:\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.11\
[   +5 ms] Found plugin image_picker at C:\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.7+22\
[   +5 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.27\
[   +1 ms] Found plugin path_provider_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-0.0.1+2\
[   +1 ms] Found plugin path_provider_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+8\
[   +1 ms] Found plugin path_provider_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-0.0.4+3\
[   +8 ms] Found plugin tflite_flutter at C:\flutter\.pub-cache\hosted\pub.dartlang.org\tflite_flutter-0.5.0\
[   +1 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.7.10\
[   +1 ms] Found plugin url_launcher_linux at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_linux-0.0.1+4\
[   +1 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+9\
[   +2 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.5+3\
[   +1 ms] Found plugin url_launcher_windows at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_windows-0.0.1+3\
[  +14 ms] Generating C:\Users\Service Unit\Desktop\FlutterProjects\lifegiver_batasan\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +33 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[   +1 ms] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
[        ]     To generate an app bundle, run:
[        ]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[        ]         Learn more on: https://developer.android.com/guide/app-bundle
[        ]     To split the APKs per ABI, run:
[        ]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[        ]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[  +15 ms] Running Gradle task 'assembleRelease'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from C:\Users\Service Unit\Desktop\FlutterProjects\lifegiver_batasan\android\gradlew.bat.
[   +1 ms] C:\Users\Service Unit\Desktop\FlutterProjects\lifegiver_batasan\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +7 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +71 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_242-release"
           OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
           OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
[   +3 ms] executing: [C:\Users\Service Unit\Desktop\FlutterProjects\lifegiver_batasan\android/] C:\Users\Service
Unit\Desktop\FlutterProjects\lifegiver_batasan\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib\main.dart
-Ptrack-widget-creation=true -Pshrink=true -Ptree-shake-icons=true assembleRelease
[+1838 ms] > Configure project :app
[   +1 ms] WARNING: The option setting 'android.enableR8=true' is deprecated.
[        ] It will be removed in version 5.0 of the Android Gradle plugin.
[        ] You will no longer be able to disable R8
[ +896 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[   +1 ms] Could not determine the dependencies of task ':app:lintVitalRelease'.
[        ] > Could not resolve all artifacts for configuration ':app:debugAndroidTestCompileClasspath'.
[        ]    > Could not find com.google.firebase:firebase-ml-vision:.
[        ]      Required by:
[        ]          project :app > project :firebase_ml_vision
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 2s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
[ +530 ms] Running Gradle task 'assembleRelease'... (completed in 3.4s)
[   +6 ms] "flutter apk" took 3,971ms.
[   +4 ms] Gradle task assembleRelease failed with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
           #1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:416:7)
           #2      _rootRunUnary (dart:async/zone.dart:1198:47)
           #3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #7      Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
           #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
           #10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
           #11     _rootRunUnary (dart:async/zone.dart:1198:47)
           #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
           #13     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
           #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
           #15     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
           #16     Future._completeWithValue (dart:async/future_impl.dart:529:5)
           #17     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
           #18     _rootRun (dart:async/zone.dart:1190:13)
           #19     _CustomZone.run (dart:async/zone.dart:1093:19)
           #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
           #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
           #22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
           
           
[ +266 ms] ensureAnalyticsSent: 264ms
[   +7 ms] Running shutdown hooks
[   +2 ms] Shutdown hooks complete
[   +2 ms] exiting with code 1

```

**Comment by markusaksli-nc** [comment]
Hi @farsuller 
Could you please provide your `flutter doctor -v`, `flutter pub deps -- --style=compact` and `app/build.gradle`?
Thank you

**Comment by catalin-apostu** [comment]
Hi @farsuller,

A workaround would be to add the dependency in your `android/app/build.gradle`:
`implementation 'com.google.firebase:firebase-ml-vision:24.1.0' `

Another workaround would be to downgrade to `firebase_ml_vision: ^0.9.10`, where this problem does not exist.

@markusaksli-nc 
I think, after my short analysis, the underlying problem is that the dependency changes in `firebase_ml_vision_0.10.0/android/build.gradle` do not work properly.

Besides the build failure (mentioned by @farsuller), the dependency changes bring along an APK build problem too, namely that the ML Vision libs for face recognition are automatically packed in the APK, even if I did not specify this. This increased my APK size with almost 30 MB.

APK when using `firebase_ml_vision: ^0.10.0`

<img width="864" alt="image" src="https://user-images.githubusercontent.com/23329491/108097206-22fd0a00-7082-11eb-8c56-e975611745e4.png">

vs APK when using `firebase_ml_vision: ^0.9.10`

<img width="864" alt="image" src="https://user-images.githubusercontent.com/23329491/108097312-43c55f80-7082-11eb-8e06-90e728e85251.png">

In both cases my `android/app/build.gradle` contains
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    // Firebase Crashlytics
    implementation 'com.google.firebase:firebase-crashlytics:17.3.1'
    // Firebase Cloud Messaging
    implementation 'com.google.firebase:firebase-messaging:21.0.1'
    // Firebase ML Vision
    implementation 'com.google.firebase:firebase-ml-vision:24.1.0'
    implementation 'com.google.firebase:firebase-ml-vision-barcode-model:16.1.2'
    // TODO: Remove workaround for incompatible dependency versions
    // See: https://firebase.google.com/support/release-notes/android#mlkit-self-serve-fixes
    implementation 'com.google.android.gms:play-services-vision:20.1.0'
    implementation 'com.google.android.gms:play-services-vision-common:19.1.0'

    testImplementation 'junit:junit:4.13.1'

    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
```

What do you think?

**Comment by markusaksli-nc** [comment]
Yeah that does appear to be the case, it's being tracked in https://github.com/FirebaseExtended/flutterfire/issues/4767
