### ISSUE TITLE
[cloud_firestore] NNBD upgrade "No implementation found for method listen"

### ISSUE THREAD

**Issue by amumm** [FirebaseExtended/flutterfire#4966]
## Bug report
Upgrade to cloud_firestore: ^0.17.0-1.0.nullsafety.0, run program, throws exception when listening on changes from a document.

exception:
```
E/DartMessenger(28588): Uncaught exception in binary message listener
E/DartMessenger(28588): java.lang.NullPointerException: Provided settings must not be null.
E/DartMessenger(28588): 	at com.google.firebase.firestore.util.Preconditions.checkNotNull(Preconditions.java:147)
E/DartMessenger(28588): 	at com.google.firebase.firestore.FirebaseFirestore.setFirestoreSettings(FirebaseFirestore.java:193)
E/DartMessenger(28588): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readFirestoreInstance(FlutterFirebaseFirestoreMessageCodec.java:241)
E/DartMessenger(28588): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readValueOfType(FlutterFirebaseFirestoreMessageCodec.java:205)
E/DartMessenger(28588): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
E/DartMessenger(28588): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readValueOfType(FlutterFirebaseFirestoreMessageCodec.java:182)
E/DartMessenger(28588): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
E/DartMessenger(28588): 	at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:410)
E/DartMessenger(28588): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readValueOfType(FlutterFirebaseFirestoreMessageCodec.java:224)
E/DartMessenger(28588): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
E/DartMessenger(28588): 	at io.flutter.plugin.common.StandardMethodCodec.decodeMethodCall(StandardMethodCodec.java:48)
E/DartMessenger(28588): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:165)
E/DartMessenger(28588): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/DartMessenger(28588): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/DartMessenger(28588): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/DartMessenger(28588): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/DartMessenger(28588): 	at android.os.Looper.loop(Looper.java:160)
E/DartMessenger(28588): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/DartMessenger(28588): 	at java.lang.reflect.Method.invoke(Native Method)
E/DartMessenger(28588): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/DartMessenger(28588): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

════════ Exception caught by services library ══════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel plugins.flutter.io/firebase_firestore/document/d697b0cc-c814-4687-a258-125545ef4ff3:
MissingPluginException(No implementation found for method listen on channel plugins.flutter.io/firebase_firestore/document/d697b0cc-c814-4687-a258-125545ef4ff3)

When the exception was thrown, this was the stack
#0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:156
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure>
package:flutter/…/services/platform_channel.dart:545
<asynchronous suspension>

```
Downgrade to cloud_firestore: ^0.16.0 - all works again.

### Steps to reproduce
 `return collection.doc(payload.id).snapshots().map((event) => event.data());`

Here's the failing dependencies with the working versions commented out

```
  firebase_core: ^0.8.0-1.0.nullsafety.1
  cloud_firestore: ^0.17.0-1.0.nullsafety.0
  firebase_auth: ^0.21.0-1.1.nullsafety.1
  # firebase_core: ^0.7.0
  # cloud_firestore: ^0.16.0
  # firebase_auth: 0.20.0+1
  provider: ^5.0.0-nullsafety.3
  bloc: ^7.0.0-nullsafety.1
  flutter_bloc: ^7.0.0-nullsafety.1
  equatable: ^2.0.0-nullsafety.1
  uuid: ^3.0.0-nullsafety.0
```

**Comment by markusaksli-nc** [comment]
Hi @amumm 
There's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/4948 and you have mentioned this there already.
Please follow up on that issue, I'm closing the current one as a duplicate.
Thank you
