### ISSUE TITLE
🐛 [firebase_ml_vision] Example ML Vision app crashing due to old camera plugin version crash

### ISSUE THREAD

**Issue by Saad29** [FirebaseExtended/flutterfire#5117]
## Bug report

I am building an app for text recognition using firebase ml vision plugin according to the [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision/example) provided. The app keeps repeatedly crashing on a Xiaomi 10T device running Android 10 (API 29). According to the logs the [Camera plugin](https://pub.dev/packages/camera/versions/0.5.6+1) crashes due to some Java threading issue. On upgrading to a later version of the Camera plugin, other issues arise with camera resolution and crashes related to reading of image files from the device captured by the app. 

### Steps to reproduce

1. Clone the repo for firebase flutter fire and run the ml vision [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_ml_vision/example).
2. Run the camera preview scanner sample. Switch camera multiple times
4. At some moment the app crashes with the exception '**java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread**.' 

### Expected behavior

The app should not crash due to the camera plugin. The fire vision example is incompatible with the newer versions of the camera plugin.

---

## Additional context

The ML Vision example uses the version 0.5.6+1 of the plugin, which is quite different from the latest Version [0.7.0+2](https://pub.dev/packages/camera). The issue seems to have been resolved in the later versions , details can be found [here](https://github.com/flutter/flutter/issues/72340).  But as I mentioned, it is incompatible with the sample ml vision app.

I have experienced the crash only once on a Samsung S9+ device. On the Xiaomi 10T it happens everytime.

---
### Log

<details><summary>Click To Expand</summary>

```
E/AndroidRuntime(28359): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-24-thread-1
E/AndroidRuntime(28359): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:992)
E/AndroidRuntime(28359): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:736)
E/AndroidRuntime(28359): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:72)
E/AndroidRuntime(28359): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:363)
E/AndroidRuntime(28359): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:168)
E/AndroidRuntime(28359): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:221)
E/AndroidRuntime(28359): 	at io.flutter.plugins.camera.DartMessenger.send(DartMessenger.java:49)
E/AndroidRuntime(28359): 	at io.flutter.plugins.camera.Camera$4.onConfigured(Camera.java:323)
E/AndroidRuntime(28359): 	at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$0$CallbackProxies$SessionStateCallbackProxy(CallbackProxies.java:53)
E/AndroidRuntime(28359): 	at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Osypoky6AfL3P2-TeDw.run(Unknown Source:4)
E/AndroidRuntime(28359): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(28359): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(28359): 	at java.lang.Thread.run(Thread.java:919)
D/TransportRuntime.SQLiteEventStore(28359): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler(28359): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=1977562718 in 1000ms(Backend next call timestamp 1614079420871). Attempt 1
W/ActivityThread(28359): SCHED: com.example.app/.MainActivity [71, r=67542ms, a=27165ms, w=1181170ms]
I/Process (28359): Sending signal. PID: 28359 SIG: 9
Lost connection to device.
```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel dev, 1.27.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.685], locale en-GB)
    • Flutter version 1.27.0-4.0.pre at C:\flutter\flutter_windows_1.22.1-stable\flutter
    • Framework revision f8cd24de95 (7 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\AndroidSDK
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\AndroidSDK
    • ANDROID_SDK_ROOT = C:\AndroidSDK\
    • Java binary at: C:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\AndroidStudio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • M2007J3SY (mobile) • 4c4179bf • android-arm64  • Android 10 (API 29)
    • Chrome (web)       • chrome   • web-javascript • Google Chrome 88.0.4324.182
    • Edge (web)         • edge     • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!

```

</details>

---

**Comment by rish07** [comment]
@markusaksli-nc Please take a look at the PR. The issue seems to be fixed in that

**Comment by panmari** [comment]
I upgraded the camera plugin to 0.8.1, so I think this can be closed.
