### ISSUE TITLE
🐛 [firebase_auth] Fatal Exception after updating firebase packages

### ISSUE THREAD

**Issue by codingwiththiago** [FirebaseExtended/flutterfire#5118]
## Bug report

Yesterday I decided to update the Firebase packages that Im using (auth, core, remote_config, crashlytics and performance). 
After that, the application builds, but it shows an error right before initializing. 

<details><summary>Click To Expand</summary>

```
E/AndroidRuntime(21098): FATAL EXCEPTION: main
E/AndroidRuntime(21098): Process: br.com.rdsaude.healthPlatform.android.staging, PID: 21098
E/AndroidRuntime(21098): java.lang.VerifyError: Verifier rejected class com.google.firebase.auth.internal.zzbg: com.google.firebase.auth.internal.zzx com.google.firebase.auth.internal.zzbg.zzf(org.json.JSONObject) failed to verify: com.google.firebase.auth.internal.zzx com.google.firebase.auth.internal.zzbg.zzf(org.json.JSONObject): [0x48] 'this' arg must be initialized
E/AndroidRuntime(21098):  com.google.firebase.auth.FirebaseUser com.google.firebase.auth.internal.zzbg.zzb() failed to verify: com.google.firebase.auth.FirebaseUser com.google.firebase.auth.internal.zzbg.zzb(): [0x16] 'this' arg must be initialized (declaration of 'com.google.firebase.auth.internal.zzbg' appears in /data/app/br.com.rdsaude.healthPlatform.android.staging-4DhuSaMlJ7Zez1KW54R05Q==/base.apk!classes4.dex)
E/AndroidRuntime(21098): 	at com.google.firebase.auth.FirebaseAuth.<init>(com.google.firebase:firebase-auth@@20.0.1:4)
E/AndroidRuntime(21098): 	at com.google.firebase.auth.internal.zzv.<init>(com.google.firebase:firebase-auth@@20.0.1:1)
E/AndroidRuntime(21098): 	at com.google.firebase.auth.zzv.create(com.google.firebase:firebase-auth@@20.0.1:2)
E/AndroidRuntime(21098): 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0(ComponentRuntime.java:132)
E/AndroidRuntime(21098): 	at com.google.firebase.components.ComponentRuntime$$Lambda$1.get(Unknown Source:4)
E/AndroidRuntime(21098): 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
E/AndroidRuntime(21098): 	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:291)
E/AndroidRuntime(21098): 	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:281)
E/AndroidRuntime(21098): 	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:584)
E/AndroidRuntime(21098): 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:303)
E/AndroidRuntime(21098): 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:267)
E/AndroidRuntime(21098): 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:252)
E/AndroidRuntime(21098): 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
E/AndroidRuntime(21098): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2117)
E/AndroidRuntime(21098): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2091)
E/AndroidRuntime(21098): 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
E/AndroidRuntime(21098): 	at android.app.ActivityThread.installProvider(ActivityThread.java:7187)
E/AndroidRuntime(21098): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6670)
E/AndroidRuntime(21098): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6565)
E/AndroidRuntime(21098): 	at android.app.ActivityThread.access$1400(ActivityThread.java:224)
E/AndroidRuntime(21098): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1887)
E/AndroidRuntime(21098): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(21098): 	at android.os.Looper.loop(Looper.java:224)
E/AndroidRuntime(21098): 	at android.app.ActivityThread.main(ActivityThread.java:7560)
E/AndroidRuntime(21098): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21098): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/AndroidRuntime(21098): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

</details>

### Steps to reproduce

I had update the packages from these versions: 
```
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_crashlytics: ^0.2.4
  firebase_remote_config: ^0.4.2
  firebase_performance: ^0.4.3
```
To these versions: 
```
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_performance: ^0.5.0+1
  firebase_remote_config: ^0.6.0
```

After that, I runned a `flutter clean` and tried to build, without success.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.5
Flutter SDK 1.22.6
health_platform_app 1.0.5+9

dependencies:
- auto_size_text 2.1.0 [flutter]
- bloc 6.1.0 [meta]
- cached_network_image 2.4.1 [flutter flutter_cache_manager octo_image]
- connectivity 0.4.9+5 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- credit_card_type_detector 1.1.0
- cupertino_icons 1.0.0
- dartz 0.9.2
- dotted_border 1.0.6 [flutter path_drawing]
- equatable 1.2.5 [collection meta]
- firebase_auth 0.20.1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.4.0+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_performance 0.5.0+1 [flutter firebase_core]
- firebase_remote_config 0.6.0 [flutter firebase_core]
- floor 0.18.0 [path sqflite sqflite_common_ffi floor_annotation meta flutter]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.0.6 [flutter bloc provider]
- flutter_html 1.1.1 [html csslib css_colors video_player chewie webview_flutter chewie_audio flutter_svg flutter]
- flutter_inappwebview 4.0.0+4 [flutter uuid mime]
- flutter_launcher_icons 0.8.1 [image args yaml path]
- flutter_platform_widgets 0.71.0 [flutter]
- flutter_secure_storage 3.3.5 [meta flutter]
- flutter_staggered_grid_view 0.3.2 [flutter]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- flutter_uxcam 1.2.1 [flutter flutter_driver]
- flutter_webview_plugin 0.3.11 [flutter]
- freezed_annotation 0.12.0 [collection json_annotation meta]
- get_it 4.0.4 [async meta]
- hive 1.4.4+1 [meta crypto]
- hive_flutter 0.3.1 [flutter hive path_provider path]
- http 0.12.2 [http_parser path pedantic]
- http_interceptor 0.3.3 [flutter http meta]
- intl 0.16.1 [path]
- json_serializable 3.5.0 [analyzer build build_config json_annotation meta path source_gen]
- mask_text_input_formatter 1.1.0 [flutter]
- material_design_icons_flutter 4.0.5755 [flutter]
- onesignal_flutter 2.6.2 [flutter]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- shared_preferences 0.5.12+2 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]

dev dependencies:
- bloc_test 7.1.0 [bloc test meta mockito]
- build_runner 1.10.13 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- effective_dart 1.2.4
- floor_generator 0.18.0 [analyzer build code_builder meta source_gen build_config collection dartx floor_annotation]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 0.12.7 [analyzer build build_config meta source_gen freezed_annotation]
- hive_generator 0.7.3 [build source_gen hive analyzer dartx]
- mockito 4.1.3 [analyzer build code_builder collection dart_style matcher meta source_gen test_api]

transitive dependencies:
- _fe_analyzer_shared 12.0.0 [meta]
- analyzer 0.40.6 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.5.2 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.4.4 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.0.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- chewie 0.12.0 [video_player cupertino_icons wakelock flutter]
- chewie_audio 1.1.1 [video_player cupertino_icons flutter]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- connectivity_for_web 0.3.1+2 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+5 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- coverage 0.14.2 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- css_colors 1.0.2 [flutter]
- csslib 0.16.2 [source_span]
- dart_style 1.3.10 [analyzer args path source_span]
- dartx 0.5.0 [collection path crypto characters time meta]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 6.0.0-nullsafety.2 [meta path]
- firebase_auth_platform_interface 3.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.6 [flutter meta collection firebase_core plugin_platform_interface]
- fixnum 0.10.11
- floor_annotation 0.11.0 [meta]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_driver 0.0.0 [file json_rpc_2 meta path web_socket_channel vm_service_client webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async matcher platform process pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [json_rpc_2 process web_socket_channel flutter_test flutter_driver archive args async boolean_selector charcode clock collection convert crypto fake_async file matcher meta path platform pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math vm_service_client webdriver]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- html 0.14.0+4 [csslib source_span]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- import_js_library 1.0.2 [flutter html flutter_web_plugins js]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3-nullsafety.2
- json_annotation 3.1.0
- json_rpc_2 2.2.2 [stack_trace stream_channel]
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- node_preamble 1.4.13
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.22 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.10.0-nullsafety.2
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 3.0.0-nullsafety.2
- plugin_platform_interface 1.0.3 [meta]
- pool 1.5.0-nullsafety.2 [async stack_trace]
- process 4.0.0-nullsafety.2 [file path platform]
- provider 4.3.2+2 [flutter nested collection]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.3 [matcher meta]
- rxdart 0.24.1
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.1 [path shelf shelf_static]
- shelf_static 0.2.9+2 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.1.0-nullsafety.3 [path stack_trace source_maps]
- source_maps 0.10.10-nullsafety.2 [source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.1+2 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- sqflite_common_ffi 1.1.1+2 [sqlite3 sqflite_common synchronized path meta]
- sqlite3 0.1.8 [collection ffi meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- sync_http 0.2.0
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test 1.16.0-nullsafety.5 [analyzer async boolean_selector coverage http http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.12-nullsafety.5 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- time 1.3.0
- timing 0.1.1+2 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- video_player 1.0.1 [meta video_player_platform_interface video_player_web flutter]
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4+1 [flutter flutter_web_plugins meta video_player_platform_interface]
- vm_service 5.5.0 [meta]
- vm_service_client 0.2.6+2 [async collection json_rpc_2 pub_semver source_span stack_trace stream_channel web_socket_channel]
- wakelock 0.2.1+1 [flutter meta wakelock_platform_interface wakelock_web]
- wakelock_platform_interface 0.1.0+1 [flutter meta]
- wakelock_web 0.1.0+3 [flutter flutter_web_plugins import_js_library js wakelock_platform_interface]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 0.7.5 [logging]
- webview_flutter 1.0.7 [flutter]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @codingwiththiago 
Could you reduce this to a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? Presumably, this should happen when just initializing core with auth.
If you `flutter create` a new project and add the dependencies does the issue reproduce?
Thank you
