### ISSUE TITLE
🐛 [cloud_firestore] get() occur error in web

### ISSUE THREAD

**Issue by hatano0x06** [FirebaseExtended/flutterfire#5190]
## Bug report

**Describe the bug**

(CollectionReference).get() occur error in web 

error message is this
```
Error: Expected a value of type 'String', but got one of type 'FirebaseException'
    at Object.throw_ [as throw] (http://localhost:52646/dart_sdk.js:5334:11)
    at Object.castError (http://localhost:52646/dart_sdk.js:5305:15)
    at Object.cast [as as] (http://localhost:52646/dart_sdk.js:5621:17)
    at dart.LegacyType.new.as (http://localhost:52646/dart_sdk.js:7219:60)
    at http://localhost:52646/packages/mangaplotter/main.dart.lib.js:799:48
    at Object._rootRunBinary (http://localhost:52646/dart_sdk.js:39389:14)
    at _RootZone.runBinary (http://localhost:52646/dart_sdk.js:38895:20)
    at http://localhost:52646/dart_sdk.js:39526:20
    at async._CustomZone.new.handleUncaughtError (http://localhost:52646/dart_sdk.js:38516:14)
    at Function._propagateToListeners (http://localhost:52646/dart_sdk.js:34373:30)
    at _Future.new.[_completeWithValue] (http://localhost:52646/dart_sdk.js:34315:23)
    at http://localhost:52646/dart_sdk.js:34338:35
    at _rootRun (http://localhost:52646/dart_sdk.js:39361:14)
    at async._CustomZone.new.run (http://localhost:52646/dart_sdk.js:38531:14)
    at async._CustomZone.new.runGuarded (http://localhost:52646/dart_sdk.js:38431:14)
    at async._AsyncCallbackEntry.new.callback (http://localhost:52646/dart_sdk.js:38485:33)
    at Object._microtaskLoop (http://localhost:52646/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:52646/dart_sdk.js:39182:13)
    at http://localhost:52646/dart_sdk.js:34689:9
```
the version of cloud_firestore is 
pubspec.yaml
```
firebase_core: ^0.7.0
cloud_firestore: ^0.16.0+1
```

web/index,html
```
  <script src="https://www.gstatic.com/firebasejs/8.2.7/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.2.7/firebase-firestore.js"></script>
```

### Steps to reproduce

1. Please set to the version listed above
2. write source code with
```
FirebaseFirestore.instance.collection("aaa").get();
```
3. run with `flutter run -d chrome --web-renderer=canvaskit`

### Expected behavior
Can get collection data with no error

---

## Additional context

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel beta, 1.26.0-17.8.pre, on Microsoft Windows [Version 10.0.19042.804], locale ja-JP)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.53.2)
[√] Connected device (2 available)
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0-259.16.beta
Flutter SDK 1.26.0-17.8.pre
mangaplotter 3.21.3

dependencies:
- auto_animated 2.1.0 [flutter visibility_detector]
- cloud_firestore 0.16.0+1 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- configurable_expansion_tile 1.0.0 [flutter]
- connectivity_plus 0.8.1 [flutter meta connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- cupertino_icons 1.0.2
- device_info 1.0.0 [flutter device_info_platform_interface]
- dotted_border 1.0.7 [flutter path_drawing]
- dynamic_color_theme 1.1.1 [flutter flutter_colorpicker shared_preferences]
- email_validator 1.0.6
- encrypt 4.1.0 [args asn1lib clock collection crypto pointycastle]
- esys_flutter_share 1.0.2 [flutter path_provider]
- expandable 4.1.4 [flutter]
- file_picker 2.1.6 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 7.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.20.1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_auth_oauth 0.2.4 [flutter firebase_auth firebase_auth_oauth_platform_interface firebase_auth_oauth_web firebase_core]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.4.0+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_storage 7.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_cupertino_date_picker 1.0.12 [flutter]
- flutter_email_sender 3.0.1 [flutter]
- flutter_facebook_login 3.0.0 [flutter flutter_web_plugins collection]
- flutter_image 3.0.0 [flutter]
- flutter_inapp_purchase 3.0.1 [http meta flutter platform]
- flutter_keyboard_visibility 4.0.3 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_local_notifications 4.0.1+1 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_page_indicator 0.0.3 [flutter]
- flutter_reorderable_list 0.1.5 [flutter]
- flutter_signin_button 1.1.0 [flutter font_awesome_flutter]
- flutter_staggered_animations 0.1.2 [flutter]
- flutter_twitter 1.1.3 [flutter]
- flutter_typeahead 2.0.0 [flutter flutter_keyboard_visibility]
- fluttertoast 7.1.8 [flutter flutter_web_plugins]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- html_unescape 1.0.2
- http 0.12.2 [http_parser path pedantic]
- image_cropper 1.3.1 [flutter]
- image_picker 0.6.7+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- image_size_getter 0.2.1 [collection hashcodes]
- keyboard_service 1.0.4 [flutter]
- outline_material_icons 0.1.1 [flutter]
- package_info_plus 0.5.0 [flutter package_info_plus_platform_interface package_info_plus_web package_info_plus_macos]
- passcode_screen 1.2.2+1 [flutter]
- path_provider 1.6.14 [flutter path_provider_platform_interface path_provider_macos path_provider_linux]
- permission_handler 5.1.0+2 [flutter meta permission_handler_platform_interface]
- photo_view 0.10.3 [flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 2.5.4 [meta flutter]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- svg_path_parser 0.1.1 [string_scanner flutter]
- timezone 0.6.1 [path]
- transformer_page_view 0.1.6 [flutter]
- tutorial_coach_mark 0.6.0+1 [flutter]
- universal_html 1.2.4 [async charcode collection csslib html meta typed_data universal_io zone_local]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- web_browser_detect 1.0.4+1 [flutter universal_html]

dev dependencies:
- flutter_driver 0.0.0 [file meta path vm_service webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_launcher_icons 0.7.5 [image args yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- test 1.16.0-nullsafety.19 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

dependency overrides:
- intl 0.17.0-nullsafety.2 [clock path]
- platform 3.0.0-nullsafety.1

transitive dependencies:
- _fe_analyzer_shared 7.0.0 [meta]
- analyzer 0.39.17 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- asn1lib 0.8.1
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- cli_util 0.2.0 [path]
- clock 1.1.0
- cloud_firestore_platform_interface 3.0.2 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0
- connectivity_plus_linux 0.3.1 [flutter connectivity_plus_platform_interface dbus meta]
- connectivity_plus_macos 0.4.1 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 0.4.1 [flutter meta plugin_platform_interface]
- connectivity_plus_web 0.6.1 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 0.1.1 [connectivity_plus_platform_interface flutter]
- convert 2.1.1 [charcode typed_data]
- coverage 0.14.1 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dbus 0.1.2 [args meta xml]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0 [clock collection]
- ffi 0.1.3
- file 6.0.0 [meta path]
- firebase 7.3.2 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_oauth_platform_interface 0.2.2 [flutter firebase_auth firebase_core]
- firebase_auth_oauth_web 0.2.2 [flutter flutter_web_plugins firebase firebase_auth firebase_auth_oauth_platform_interface firebase_core js]
- firebase_auth_platform_interface 3.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.6 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_platform_interface 1.0.4 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+3 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_colorpicker 0.3.5 [flutter]
- flutter_keyboard_visibility_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 1.0.1 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.9 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 8.8.1 [flutter]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- hashcodes 1.0.0
- html 0.14.0+3 [csslib source_span]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.18 [archive xml meta]
- image_picker_platform_interface 1.1.0 [flutter meta http plugin_platform_interface]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3
- logging 0.11.4
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 0.9.7
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- node_preamble 1.4.12
- package_config 1.9.3 [path charcode]
- package_info_plus_macos 0.1.0 [flutter]
- package_info_plus_platform_interface 0.1.0 [flutter meta plugin_platform_interface]
- package_info_plus_web 0.1.0 [http package_info_plus_platform_interface platform_detect flutter flutter_web_plugins meta]
- path 1.8.0
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.10.0-nullsafety.2
- permission_handler_platform_interface 2.0.2 [flutter meta plugin_platform_interface]
- petitparser 3.0.4 [meta]
- platform_detect 1.4.0 [meta pub_semver]
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 2.0.0
- pool 1.5.0 [async stack_trace]
- process 4.0.0 [file path platform]
- pub_semver 1.4.4 [collection]
- quiver 2.1.3 [matcher meta]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.0 [path shelf shelf_static]
- shelf_static 0.2.8 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.2.0
- synchronized 2.2.0+2
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.12-nullsafety.17 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.0 [collection]
- universal_io 1.0.2 [crypto meta zone_local]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- vector_math 2.1.0
- visibility_detector 0.1.5 [flutter]
- vm_service 5.5.0 [meta]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 0.7.3 [logging]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
- zone_local 0.1.2
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @hatano0x06 
Could you please see if the error persists if you use the web version `7.20.0` indicated in the official documentation?
https://firebase.flutter.dev/docs/firestore/overview#3-web-only-add-the-sdk
Thank you

**Comment by hatano0x06** [comment]
@markusaksli-nc 
thank you!
I solve it

**Comment by markusaksli-nc** [comment]
Closing this as solved
