### ISSUE TITLE
🐛 [firebase_auth 1.0.0] UserInfo.uid can be null

### ISSUE THREAD

**Issue by markusaksli-nc** [FirebaseExtended/flutterfire#5218]
## Bug report

**Describe the bug**
Only saw this when logging in using phone auth. Ran into this when https://github.com/FirebaseExtended/flutterfire/pull/4635 tried to get the `provider.uid`. This can also be reproduced if you just add
```dart
for (var provider in _auth.currentUser.providerData) print(provider);
```
after the sign-in at
https://github.com/FirebaseExtended/flutterfire/blob/48f7dd7f919bde3e5ed1c73d5c5e27458b51e5dd/packages/firebase_auth/firebase_auth/example/lib/signin_page.dart#L446-L453

Obviously, this will cause the null check at 
https://github.com/FirebaseExtended/flutterfire/blob/48f7dd7f919bde3e5ed1c73d5c5e27458b51e5dd/packages/firebase_auth/firebase_auth_platform_interface/lib/src/user_info.dart#L52
to raise an exception.

https://dart.dev/null-safety/tour#using-variables-and-expressions

>  Important: If you aren’t positive that a value is non-null, don’t use the ! operator.

### Steps to reproduce

1. Sign in using phone auth
2. Do anything that tries to get the phone provider `uid` such as getting it or calling `toString`
3. `Unhandled Exception: Null check operator used on a null value`

### Expected behavior

Maybe this shouldn't get a null or maybe it should be nullable.

---

## Additional context

Reproduces on both Android and iOS

```
D/FirebaseAuth(25545): Notifying id token listeners about user ( TBuZt3I487P1kamSdZUCSPCACsH2 ).
D/FirebaseAuth(25545): Notifying auth state listeners about user ( TBuZt3I487P1kamSdZUCSPCACsH2 ).
E/flutter (25545): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
E/flutter (25545): #0      UserInfo.uid (package:firebase_auth_platform_interface/src/user_info.dart:52:24)
E/flutter (25545): #1      UserInfo.toString (package:firebase_auth_platform_interface/src/user_info.dart:57:144)
E/flutter (25545): #2      print (dart:core/print.dart:9:24)
E/flutter (25545): #3      _PhoneSignInSectionState._verifyPhoneNumber.<anonymous closure> (package:triage/signin_page.dart:672:60)
E/flutter (25545): <asynchronous suspension>
E/flutter (25545): 
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel master, 2.1.0-11.0.pre.98, on Microsoft Windows [Version 10.0.19041.804], locale et-EE)
    • Flutter version 2.1.0-11.0.pre.98 at C:\Development\flutter_master
    • Framework revision 2f7d9d3d26 (6 hours ago), 2021-03-04 03:25:49 -0500
    • Engine revision 91120b358a
    • Dart version 2.13.0 (build 2.13.0-101.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.804]
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.0-101.0.dev
Flutter SDK 2.1.0-11.0.pre.98
triage 1.0.0+1

dependencies:
- firebase_auth 1.0.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 0.8.0 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_signin_button 2.0.0-nullsafety.0 [flutter font_awesome_flutter]
- google_sign_in 5.0.0 [google_sign_in_platform_interface google_sign_in_web flutter meta]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 9.0.0-nullsafety [flutter]
- google_sign_in_platform_interface 2.0.0 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- quiver 3.0.0 [matcher]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by bhavin-concetto** [comment]
@markusaksli-nc  any temporary workaround?

**Comment by markusaksli-nc** [comment]
Maybe you can put it in a try/catch and try to catch it? But even if that works you have to do it everywhere you want to access the provider uid. The alternative is to just try to edit the package source to make it nullable, use your edited source, and submit a PR.

**Comment by bhavin-concetto** [comment]
@markusaksli-nc I updated the whole project with sdk: ">=2.12.0 <3.0.0" and it is working for me now.

**Comment by markusaksli-nc** [comment]
That's great, at least it works on sound null-safety. Currently, the problem is that the official example hasn't been migrated yet.
https://github.com/FirebaseExtended/flutterfire/blob/e508917e72701812cf979360dd5f522d500e2ca8/packages/firebase_auth/firebase_auth/example/lib/main.dart#L5

**Comment by Vitor-Bukovitz** [comment]
any update? same issue here

**Comment by guness** [comment]
same issue when using `FirebaseUser#toString`. here is the stacktrace:

```
#0      UserInfo.uid (package:firebase_auth_platform_interface/src/user_info.dart:52:24)
#1      UserInfo.toString (package:firebase_auth_platform_interface/src/user_info.dart:57:144)
#2      StringBuffer.write (dart:core-patch/string_buffer_patch.dart:64:22)
#3      StringBuffer.writeAll (dart:core-patch/string_buffer_patch.dart:102:7)
#4      IterableBase.iterableToFullString (dart:collection/iterable.dart:267:14)
#5      ListBase.listToString (dart:collection/list.dart:43:20)
#6      List.toString (dart:core-patch/growable_array.dart:489:33)
#7      _StringBase._interpolate (dart:core-patch/string_patch.dart:855:19)
#8      User.toString (package:firebase_auth/src/user.dart:357:5)
```

**Comment by lukepighetti** [comment]
I am getting this on `Firebase.initializeApp()`

```
_CastError (Null check operator used on a null value)
```

**Comment by pankaj-nikam** [comment]
I am getting this on Android device without null safety.

**Comment by kevjose** [comment]
any update on this? same issue here

**Comment by MALDRU** [comment]
Modificacion de: firebase_auth: ^1.0.3

Hola, les comparto una solucion, se que no es la correcta, pero si necesitan solventar ese error rapidamente modifiquen este archivo: "user_info.dart"

{SDK_FLUTTER}\.pub-cache\hosted\pub.dartlang.org\firebase_auth_platform_interface-4.0.2\lib\src\user_info.dart

Busquen el getter: uid, aproximadamente linea 51

y cambien el ! por el operador ? les debe quedar asi:

`String get uid {`
`return _data['uid']??'';`
`}`

Vuelvan a compilar y les deberia funcionar.

Cabe aclarar que esta solucion solo aplica para solventar el error si estan en produccion, de lo contrario esperar a que solventen este error, o crear una peticion de cambio.

**Comment by lukepighetti** [comment]
I was having this issue because I wasn't calling WidgetsFlutterBinding.ensureInitialized method

**Comment by balasubramanian1612s** [comment]
Someone, please provide a solution, Experiencing the same issue..

**Comment by Salakar** [comment]
Quick fix available for this one @rrousselGit @russellwheatley - changing `UserInfo.uid` to be nullable
