### ISSUE TITLE
🐛 [remote_config] java.lang.IllegalArgumentException: Unsupported value: com.google.firebase.remoteconfig.internal.FirebaseRemoteConfigInfoImpl

### ISSUE THREAD

**Issue by jimmyff** [FirebaseExtended/flutterfire#5222]
## Bug report

After upgrading my app to use Flutter 2.0, and the latest firebase packages (firebase_core 1.0.0, firebase_remote_config 0.9.0-dev.0). My app starts initialising but the instantly crashes with the following error: 

```
D/AndroidRuntime( 7514): Shutting down VM
E/AndroidRuntime( 7514): FATAL EXCEPTION: main
E/AndroidRuntime( 7514): Process: com.rocketware.onescene, PID: 7514
E/AndroidRuntime( 7514): java.lang.IllegalArgumentException: Unsupported value: com.google.firebase.remoteconfig.internal.FirebaseRemoteConfigInfoImpl@39b686
E/AndroidRuntime( 7514): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:276)
E/AndroidRuntime( 7514): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
E/AndroidRuntime( 7514): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime( 7514): 	at io.flutter.plugins.firebase.firebaseremoteconfig.FirebaseRemoteConfigPlugin.lambda$onMethodCall$2(FirebaseRemoteConfigPlugin.java:167)
E/AndroidRuntime( 7514): 	at io.flutter.plugins.firebase.firebaseremoteconfig.-$$Lambda$FirebaseRemoteConfigPlugin$G3sJbc89zgSFW2R5fKq_9HoTj0c.onComplete(Unknown Source:2)
E/AndroidRuntime( 7514): 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@17.0.2:4)
E/AndroidRuntime( 7514): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 7514): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7514): 	at com.google.android.gms.internal.tasks.zzb.dispatchMessage(com.google.android.gms:play-services-tasks@@17.0.2:6)
E/AndroidRuntime( 7514): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 7514): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime( 7514): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7514): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 7514): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process ( 7514): Sending signal. PID: 7514 SIG: 9
Lost connection to device.
Exited (sigterm)

```

---

## Additional context

I have included the full output I get when launching my app as there are lots of mentions of deprecated API's. Here is a sample:
```
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_remote_config-0.9.0-dev.0\android\src\main\java\io\flutter\plugins\firebase\firebaseremoteconfig\FirebaseRemoteConfigPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
<details><summary>Click To Expand</summary>

```
Running "flutter pub get" in os_app...
Launching lib\main.dart on Pixel 5 in debug mode...
 lib\main.dart
D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7+3\android\src\main\java\io\flutter\plugins\sharedpreferences\SharedPreferencesPlugin.java:18: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                                ^
1 warning
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_analytics-5.0.15\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.0.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_functions-1.0.0\android\src\main\java\io\flutter\plugins\firebase\functions\FlutterFirebaseFunctionsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-8.0.0\android\src\main\java\io\flutter\plugins\firebase\storage\FlutterFirebaseStoragePlugin.java:38: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {

                                                ^
1 warning
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.0.0\android\src\main\java\io\flutter\plugins\firebase\auth\FlutterFirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_remote_config-0.9.0-dev.0\android\src\main\java\io\flutter\plugins\firebase\firebaseremoteconfig\FirebaseRemoteConfigPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\emoji_picker-0.1.0\android\src\main\java\com\jeffg\emoji_picker\EmojiPickerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-1.0.0\android\src\main\java\io\flutter\plugins\firebase\firestore\FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-1.0.0\android\src\main\java\io\flutter\plugins\firebase\firestore\streamhandler\TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\streams_channel-0.3.0\android\src\main\java\app\loup\streams_channel\StreamsChannelPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.5.9\android\src\main\java\io\flutter\plugins\googlesignin\GoogleSignInPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\image_cropper-1.3.1\android\src\main\java\vn\hunghd\flutter\plugins\imagecropper\ImageCropperPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: D:\dev\sdks\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.1\android\src\main\java\io\flutter\plugins\pathprovider\PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
√ Built build\app\outputs\flutter-apk\app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:55916/szdZKGkl0tY=/ws
I/flutter ( 7514): 14:24 Firebase/FINE: Init firebase...
D/FRCPlugin( 7514): Sending fetchTimeout: 60
I/flutter ( 7514): 14:98 ReduxLogging/INFO: {Action: Instance of 'InitAction', State: StoreState, ts: 2021-03-04 16:49:14.096931}
I/flutter ( 7514): Loading locale: en
I/flutter ( 7514): UiWrapper, child: Navigator-[LabeledGlobalKey<NavigatorState>#73d8e]
I/flutter ( 7514): 14:79 ReduxLogging/INFO: {Action: Instance of 'AppRoutingAction', State: StoreState, ts: 2021-03-04 16:49:14.798812}
I/flutter ( 7514): 14:80 ReduxLogging/INFO: {Action: Instance of 'AppRoutingAction', State: StoreState, ts: 2021-03-04 16:49:14.800235}
I/flutter ( 7514): 15:12 Firebase/FINE: Initalising remote config...
D/FRCPlugin( 7514): Sending fetchTimeout: 60
D/AndroidRuntime( 7514): Shutting down VM
E/AndroidRuntime( 7514): FATAL EXCEPTION: main
E/AndroidRuntime( 7514): Process: com.rocketware.onescene, PID: 7514
E/AndroidRuntime( 7514): java.lang.IllegalArgumentException: Unsupported value: com.google.firebase.remoteconfig.internal.FirebaseRemoteConfigInfoImpl@39b686
E/AndroidRuntime( 7514): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:276)
E/AndroidRuntime( 7514): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
E/AndroidRuntime( 7514): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime( 7514): 	at io.flutter.plugins.firebase.firebaseremoteconfig.FirebaseRemoteConfigPlugin.lambda$onMethodCall$2(FirebaseRemoteConfigPlugin.java:167)
E/AndroidRuntime( 7514): 	at io.flutter.plugins.firebase.firebaseremoteconfig.-$$Lambda$FirebaseRemoteConfigPlugin$G3sJbc89zgSFW2R5fKq_9HoTj0c.onComplete(Unknown Source:2)
E/AndroidRuntime( 7514): 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@17.0.2:4)
E/AndroidRuntime( 7514): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 7514): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7514): 	at com.google.android.gms.internal.tasks.zzb.dispatchMessage(com.google.android.gms:play-services-tasks@@17.0.2:6)
E/AndroidRuntime( 7514): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 7514): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime( 7514): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7514): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 7514): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process ( 7514): Sending signal. PID: 7514 SIG: 9
Lost connection to device.
Exited (sigterm)

```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.0.0, on Microsoft Windows [Version 10.0.19042.804],
    locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)     
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more      details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code, 64-bit edition (version 1.52.1)
[√] Connected device (4 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0
Flutter SDK 2.0.0
onesceneapp 1.0.0+1

dependencies:
- badges 1.1.6 [flutter]
- bitmap 0.0.6 [flutter ffi]
- blurhash_dart 0.2.3
- chroma 0.1.0 [vector_math logging image]
- cloud_firestore 1.0.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_firestore_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_functions 1.0.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- confetti 0.5.4+1 [flutter random_color vector_math]
- cupertino_icons 0.1.3
- device_info 2.0.0 [flutter device_info_platform_interface]
- dotted_border 1.0.7 [flutter path_drawing]
- emoji_picker 0.1.0 [flutter shared_preferences]
- encrypt 3.2.0 [asn1lib collection pointycastle args]
- equatable 1.2.6 [collection meta]
- exif 0.1.5 [args collection convert sprintf]
- firebase_analytics 5.0.15 [meta flutter firebase_analytics_platform_interface]     
- firebase_auth 1.0.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.0.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 0.9.0-dev.0 [flutter firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface]
- firebase_storage 8.0.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]       
- flutter_image 3.0.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_page_transition 0.1.6 [flutter]
- flutter_redux 0.7.0 [meta redux flutter]
- flutter_redux_navigation 0.6.0 [flutter redux]
- geolocation 1.1.2 [flutter streams_channel]
- get_ip 0.4.0 [flutter]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- googleapis 1.0.0 [_discoveryapis_commons http]
- googleapis_auth 1.0.0 [crypto http]
- great_circle_distance 1.0.1
- image 3.0.1 [archive meta xml]
- image_cropper 1.3.1 [flutter]
- image_picker 0.6.5+3 [flutter flutter_plugin_android_lifecycle]
- in_app_purchase 0.3.5+1 [async collection flutter json_annotation meta]
- intl 0.17.0 [clock path]
- logging 0.11.4
- mdi 3.0.0 [flutter]
- meta 1.3.0
- onescene_brand 1.0.0 [flutter os_core]
- os_core 0.0.1 [redux redux_logging quiver_hashcode intl uuid http encrypt key_value_store built_value built_collection quiver archive recase]
- package_info 2.0.0 [flutter]
- palette_generator 0.2.3 [flutter collection path]
- path_provider 1.6.1 [flutter platform meta]
- quiver 2.1.5 [matcher meta]
- recase 3.0.1
- redux 4.0.0+3
- redux_logging 0.4.0 [redux logging]
- reorderables 0.3.2 [flutter]
- settings_ui 0.6.0 [flutter]
- shared_preferences 0.5.7+3 [meta flutter shared_preferences_platform_interface shared_preferences_macos shared_preferences_web]
- uuid 3.0.1 [crypto]
- video_player 0.10.12+5 [meta video_player_platform_interface video_player_web flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math 
async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- _discoveryapis_commons 0.2.1 [http]
- archive 3.1.2 [crypto path]
- args 1.6.0
- asn1lib 0.5.15
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- built_collection 5.0.0
- built_value 8.0.0 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_web 1.0.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.0 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.0 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- crypto 3.0.0 [collection typed_data]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]      
- fake_async 1.2.0 [clock collection]
- ffi 0.1.3
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]    
- firebase_core_web 1.0.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 0.2.0-dev.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_storage_platform_interface 2.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.0 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.13.0 [http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]      
- js 0.6.3
- json_annotation 3.1.1
- key_value_store 1.0.0
- matcher 0.12.10 [stack_trace]
- path 1.8.0
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- pedantic 1.11.0
- petitparser 4.0.2 [meta]
- platform 2.2.1
- plugin_platform_interface 2.0.0 [meta]
- pointycastle 1.0.2
- quiver_hashcode 2.0.0
- random_color 1.0.5 [flutter]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]  
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sprintf 4.1.0
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- streams_channel 0.3.0 [flutter]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4+1 [flutter flutter_web_plugins meta video_player_platform_interface]
- xml 5.0.2 [collection meta petitparser]
```

</details>

---

Thanks

**Comment by markusaksli-nc** [comment]
Hi @jimmyff 
I'm not seeing this with the official example. What code exactly triggers the behavior? Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by jimmyff** [comment]
Okay, I've fixed it by commenting out:
```dart
await remoteConfig.ensureInitialized();
```

No idea why that was breaking so catastrophically but I'll just move on without using this.

**Comment by leidig54** [comment]
Same issue here. Fatal error causing complete crash. Also fixed by removing 

`await remoteConfig.ensureInitialized();`

```
D/AndroidRuntime( 6201): Shutting down VM
E/AndroidRuntime( 6201): FATAL EXCEPTION: main
E/AndroidRuntime( 6201): Process: com.oto.tinnitus, PID: 6201
E/AndroidRuntime( 6201): java.lang.IllegalArgumentException: Unsupported value: com.google.firebase.remoteconfig.internal.FirebaseRemoteConfigInfoImpl@807ed4
E/AndroidRuntime( 6201): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:278)
E/AndroidRuntime( 6201): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:59)
E/AndroidRuntime( 6201): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime( 6201): 	at io.flutter.plugins.firebase.firebaseremoteconfig.FirebaseRemoteConfigPlugin.lambda$onMethodCall$2(FirebaseRemoteConfigPlugin.java:167)
E/AndroidRuntime( 6201): 	at io.flutter.plugins.firebase.firebaseremoteconfig.-$$Lambda$FirebaseRemoteConfigPlugin$Y3AzL-9dhsU_xc4t8Quuo-SGtq8.onComplete(Unknown Source:2)
E/AndroidRuntime( 6201): 	at com.google.android.gms.tasks.zzj.run(com.google.android.gms:play-services-tasks@@17.1.0:4)
E/AndroidRuntime( 6201): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 6201): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 6201): 	at com.google.android.gms.internal.tasks.zzb.dispatchMessage(com.google.android.gms:play-services-tasks@@17.1.0:6)
E/AndroidRuntime( 6201): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 6201): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/AndroidRuntime( 6201): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6201): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime( 6201): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

Only occurs on android (Samsung Galaxy S8).

Using   

`firebase_remote_config: ^0.8.0-dev.0`

**Comment by markusaksli-nc** [comment]
Seeing this as well on `ensureInitialized` with `firebase_remote_config: ^0.9.0-dev.0` on the latest master `2.1.0-11.0.pre.145`.
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 2.1.0-11.0.pre.145, on Microsoft Windows [Version 10.0.19041.804], locale et-EE)
    • Flutter version 2.1.0-11.0.pre.145 at C:\Development\flutter_master
    • Framework revision a0ba646408 (2 days ago), 2021-03-05 22:09:03 -0500
    • Engine revision f751d04fa0
    • Dart version 2.13.0 (build 2.13.0-107.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.804]
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 88.0.705.81

• No issues found!
```
</details>

**Comment by snowb1shop** [comment]
Same issue here

**Comment by Salakar** [comment]
A fix is on the way for this.
