### ISSUE TITLE
🐛 [Firestore] Error after null safety migration (Web App)

### ISSUE THREAD

**Issue by boosey** [FirebaseExtended/flutterfire#5228]
My application is working fine before null safety migration. Afterwards I get a runtime error when attempting to read a record, 
```
Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'
```
Thrown on:
```
var s = await FirebaseFirestore.instance
  .collection('cautions')
  .snapshots()
  .first;
```
This is the stacktrace:
```
Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'
at Object.throw_ [as throw] (http://localhost:54863/dart_sdk.js:5032:11)
at http://localhost:54863/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:397:19
at Object._checkAndCall (http://localhost:54863/dart_sdk.js:5237:16)
at Object.dcall (http://localhost:54863/dart_sdk.js:5242:17)
at Object._invokeErrorHandler (http://localhost:54863/dart_sdk.js:37273:19)
at _HandleErrorStream.new.[_handleError] (http://localhost:54863/dart_sdk.js:35175:19)
at _ForwardingStreamSubscription.new.[_handleError] (http://localhost:54863/dart_sdk.js:34993:38)
at _RootZone.runBinaryGuarded (http://localhost:54863/dart_sdk.js:37034:11)
at sendError (http://localhost:54863/dart_sdk.js:30966:26)
at _ForwardingStreamSubscription.new.[_sendError] (http://localhost:54863/dart_sdk.js:30983:11)
at _ForwardingStreamSubscription.new.[_addError] (http://localhost:54863/dart_sdk.js:30909:27)
at _ForwardingStreamSubscription.new.[_addError] (http://localhost:54863/dart_sdk.js:34968:25)
at Object._addErrorWithReplacement (http://localhost:54863/dart_sdk.js:37469:20)
at _MapStream.new.[_handleData] (http://localhost:54863/dart_sdk.js:35081:19)
at _ForwardingStreamSubscription.new.[_handleData] (http://localhost:54863/dart_sdk.js:34990:37)
at _RootZone.runUnaryGuarded (http://localhost:54863/dart_sdk.js:37018:11)
at _BroadcastSubscription.new.[_sendData] (http://localhost:54863/dart_sdk.js:30952:22)
at _BroadcastSubscription.new.[_add] (http://localhost:54863/dart_sdk.js:30901:26)
at _SyncBroadcastStreamController.new.[_sendData] (http://localhost:54863/dart_sdk.js:31595:34)
at _SyncBroadcastStreamController.new.add (http://localhost:54863/dart_sdk.js:31394:24)
at http://localhost:54863/packages/cloud_firestore_web/src/interop/utils/utils.dart.lib.js:535:30
at Object._checkAndCall (http://localhost:54863/dart_sdk.js:5237:16)
at Object.dcall (http://localhost:54863/dart_sdk.js:5242:17)
at Array.ret (http://localhost:54863/dart_sdk.js:57497:21)
at next (https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js:1:280446)
at https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js:1:228287
Application finished.
Exited (sigterm) 
```

**Comment by boosey** [comment]
Tried with iOS simulator as the target. Received the following:
```
    [!] CocoaPods could not find compatible versions for pod "cloud_firestore":
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`)
    Specs satisfying the `cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`)` dependency were found, but they required a higher minimum deployment target.
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'

```

**Comment by markusaksli-nc** [comment]
Hi @boosey 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5050.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
