### ISSUE TITLE
🐛 [cloud_firestore] Upgrading to Flutter 2.0 breaks my existing web projects with FirebaseFirestore. 

### ISSUE THREAD

**Issue by Nulligma** [FirebaseExtended/flutterfire#5294]
## Bug report

**Describe the bug**

My projects which were working fine before updating to flutter 2.0 are now having problem in web but running perfectly fine on my android devices. Before updating they were running perfectly on web & mobile.

### Steps to reproduce

A simple Standalone code of my projects which is getting problem is as follows:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: StreamBuilder(
          stream: FirebaseAuth.instance.idTokenChanges(),
          builder: (BuildContext context, AsyncSnapshot<User?> snapshot) {
            if (snapshot.hasError) {
              return Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Icon(
                    Icons.error_outline,
                    color: Colors.red,
                    size: 60,
                  ),
                  Padding(
                    padding: const EdgeInsets.only(top: 16),
                    child: Text('Error: ${snapshot.error}'),
                  )
                ],
              );
            } else if (!snapshot.hasData)
              return _AutoLogin();
            else if (snapshot.hasData) return _AppManager();

            return Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: <Widget>[
                SizedBox(
                  child: const CircularProgressIndicator(),
                  width: 60,
                  height: 60,
                ),
                const Padding(
                  padding: EdgeInsets.only(top: 16),
                  child: Text('Waiting for connection...'),
                )
              ],
            );
          },
        ));
  }
}

enum AppState {
  loading,
  databaseSetupPending,
  uploadingDatabase,
  databaseSetuped,
  databaseDownloading,
  ready
}

class _AppManager extends StatefulWidget {
  @override
  __AppManagerState createState() => __AppManagerState();
}

class __AppManagerState extends State<_AppManager> {
  late AppState appState;

  @override
  void initState() {
    super.initState();
    appState = AppState.loading;
    loadData();
  }

  void loadData() async {
    QuerySnapshot val =
        await FirebaseFirestore.instance.collection("AppData").get();

    setState(() {
      if (val.docs.length == 0)
        appState = AppState.databaseSetupPending;
      else
        appState = AppState.databaseDownloading;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(appState.toString()),
      ),
    );
  }
}

class _AutoLogin extends StatefulWidget {
  @override
  __AutoLoginState createState() => __AutoLoginState();
}

class __AutoLoginState extends State<_AutoLogin> {
  bool isLogingIn = false;
  @override
  void initState() {
    super.initState();
  }

  void login() async {
    try {
      await FirebaseAuth.instance.signInWithEmailAndPassword(
          email: "shantanu@gmail.com", password: "123456");
    } on FirebaseAuthException catch (e) {
      print(e.message);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: isLogingIn
            ? CircularProgressIndicator()
            : TextButton(
                onPressed: () {
                  setState(() {
                    isLogingIn = true;
                  });
                  login();
                },
                child: Text("login")),
      ),
    );
  }
}
```

and my index.html file is as follows:

```html
  <script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-firestore.js"></script>
  <script>
    var firebaseConfig = {
      apiKey: "*******************************",
      authDomain: "*******************************",
      projectId: "*******************************",
      storageBucket: "*******************************",
      messagingSenderId: "*******************************",
      appId: "**************************************************************",
      measurementId: "*******************************"
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>
```

### Expected behavior

Expected results: I wanted to see the firebase - firestore's collection by name "AppData" has any document or not

instead 
I get the following error while being on code FirebaseFirestore.instance.collection("AppData").get();

```
Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'
    at Object.throw_ [as throw] (http://localhost:60662/dart_sdk.js:5032:11)
    at collection_reference_web.CollectionReferenceWeb.new.get (http://localhost:60662/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:370:23)
    at get.next (<anonymous>)
    at http://localhost:60662/dart_sdk.js:37210:33
    at _RootZone.runUnary (http://localhost:60662/dart_sdk.js:37081:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:60662/dart_sdk.js:32337:29)
    at handleValueCallback (http://localhost:60662/dart_sdk.js:32864:49)
    at Function._propagateToListeners (http://localhost:60662/dart_sdk.js:32902:17)
    at _Future.new.[_completeWithValue] (http://localhost:60662/dart_sdk.js:32750:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60662/dart_sdk.js:32771:35)
    at Object._microtaskLoop (http://localhost:60662/dart_sdk.js:37333:13)
    at _startMicrotaskLoop (http://localhost:60662/dart_sdk.js:37339:13)
    at http://localhost:60662/dart_sdk.js:33110:9
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter doctor -v
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.804],
    locale en-IN)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (5 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
    • Android SDK at C:\Users\shant\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)   
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor     
      --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe      

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.54.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.45 
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter pub deps -- --style=compact
Dart SDK 2.12.0
Flutter SDK 2.0.1
youtube_clone 1.0.0+1

dependencies:
- cloud_firestore 1.0.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.2
- firebase_auth 1.0.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]       

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math 
async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]    
- firebase_core_web 1.0.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]      
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @Nulligma 
This issue was already fixed. Please use the latest `cloud_firestore: ^1.0.1`
Thank you

**Comment by Nulligma** [comment]
Updating to cloud_firestore: ^1.0.1 gives me new error on same line of code
```
Error: [cloud_firestore/unknown] NoSuchMethodError: invalid member on null: 'includeMetadataChanges'
    at Object.throw_ [as throw] (http://localhost:56741/dart_sdk.js:5032:11)
    at collection_reference_web.CollectionReferenceWeb.new.get (http://localhost:56741/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:370:23)
    at get.next (<anonymous>)
    at http://localhost:56741/dart_sdk.js:37210:33
    at _RootZone.runUnary (http://localhost:56741/dart_sdk.js:37081:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:56741/dart_sdk.js:32337:29)
    at handleValueCallback (http://localhost:56741/dart_sdk.js:32864:49)
    at Function._propagateToListeners (http://localhost:56741/dart_sdk.js:32902:17)
Launching lib\main.dart on Chrome in debug mode...
lib\main.dart:1
    at _Future.new.[_completeWithValue] (http://localhost:56741/dart_sdk.js:32750:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:56741/dart_sdk.js:32771:35)
    at Object._microtaskLoop (http://localhost:56741/dart_sdk.js:37333:13)
    at _startMicrotaskLoop (http://localhost:56741/dart_sdk.js:37339:13)
    at http://localhost:56741/dart_sdk.js:33110:9

```

**Comment by markusaksli-nc** [comment]
This is because you are using far newer JS SDK imports in `index.html` than what is recommended in the official documentation https://firebase.flutter.dev/docs/firestore/overview#3-web-only-add-the-sdk

See https://github.com/FirebaseExtended/flutterfire/issues/4127
