### ISSUE TITLE
[firebase_ml_vision] couldn't find "libflutter.so"

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#530]
## Steps to Reproduce

1. Create default flutter application.
2. Add firebase_ml_vision (usually you would need more configuration, but its not needed here.)
3. Build and install app-release manually (debugging works for some reason)
3. Crash.

## Logs

```
12-23 18:14:29.040  8412  8412 D AndroidRuntime: Shutting down VM
12-23 18:14:29.041  8412  8412 E AndroidRuntime: FATAL EXCEPTION: main
12-23 18:14:29.041  8412  8412 E AndroidRuntime: Process: com.example.testing, PID: 8412
12-23 18:14:29.041  8412  8412 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.testing-X1ZUWC74HSQhdltA8gO6cQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.testing-X1ZUWC74HSQhdltA8gO6cQ==/lib/x86, /data/app/com.example.testing-X1ZUWC74HSQhdltA8gO6cQ==/base.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so"
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1669)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:157)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:134)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-23 18:14:29.041  8412  8412 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by kroikie** [comment]
@MichaelPriebe

The issue at https://github.com/flutter/flutter/issues/25722 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @MichaelPriebe
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
