### ISSUE TITLE
Unexpected Firebase Error

### ISSUE THREAD

**Issue by prihodulkin** [FirebaseExtended/flutterfire#5339]
Error: [cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'
    at Object.throw_ [as throw] (http://localhost:56195/dart_sdk.js:5032:11)
    at http://localhost:56195/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:397:19
    at Object._checkAndCall (http://localhost:56195/dart_sdk.js:5237:16)
    at Object.dcall (http://localhost:56195/dart_sdk.js:5242:17)
    at Object._invokeErrorHandler (http://localhost:56195/dart_sdk.js:37273:19)
    at _HandleErrorStream.new.[_handleError] (http://localhost:56195/dart_sdk.js:35175:19)
    at _ForwardingStreamSubscription.new.[_handleError] (http://localhost:56195/dart_sdk.js:34993:38)

**Comment by markusaksli-nc** [comment]
Hi @prihodulkin 
You probably just need to use the latest version of could firestore.
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.
