### ISSUE TITLE
🐛 [firebase_authentication] userChanges stream does not emit the signed in user after page reload when using the FirebaseAuth emulator (web)

### ISSUE THREAD

**Issue by zepol-yerffej** [FirebaseExtended/flutterfire#5372]
## Bug report

On Flutter Web, the userChanges stream from a FirebaseAuth instance never emits the signed in user after a page reload.  Instead, it only emits null. With the MWE below, the app gets stuck on the loading page.

**Update 1:** It appears that the issue only occurs when using the Firebase Auth emulator.

**Update 2:** The issue goes away if you remove the cloud_firestore dependency from the project's pubspec.yaml file.

### Steps to reproduce

<details><summary>Source code</summary>

```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(App());
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      initialRoute: '/loading',
      onGenerateRoute: (settings) {
        switch (settings.name) {
          case '/error':
            return MaterialPageRoute(builder: (_) => ErrorScreen());
          case '/loading':
            return MaterialPageRoute(builder: (_) => LoadingScreen());
          case '/signin':
            return MaterialPageRoute(builder: (_) => SignInScreen());
          case '/welcome':
            return MaterialPageRoute(builder: (_) => WelcomeScreen());
          default:
            return MaterialPageRoute(
                builder: (_) => Center(child: Text('Unknown route')));
        }
      },
    );
  }
}

class ErrorScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Center(
        child: Text('An error occurred.'),
      ),
    );
  }
}

class LoadingScreen extends StatefulWidget {
  @override
  _LoadingScreenState createState() => _LoadingScreenState();
}

class _LoadingScreenState extends State<LoadingScreen> {
  @override
  void initState() {
    init();
    super.initState();
  }

  init() async {
    try {
      await Firebase.initializeApp();
      if (kDebugMode) {
        await FirebaseAuth.instance.useEmulator('http://localhost:1001');
      }

      final preferences = await SharedPreferences.getInstance();
      bool signedIn = preferences.getBool('IS_SIGNED_IN') ?? false;

      String landingPath = '/signin';

      if (signedIn) {
        landingPath = '/welcome';
        // Wait for the userChanges to emit a non-null element.
        await FirebaseAuth.instance
            .userChanges()
            .firstWhere((user) => user != null);
      }

      Navigator.of(context).pushReplacementNamed(landingPath);
    } catch (error) {
      print(error);
      Navigator.of(context).pushReplacementNamed('/error');
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Center(
        child: Text('Loading...'),
      ),
    );
  }
}

class SignInScreen extends StatelessWidget {
  final _emailController = TextEditingController();
  final _passwordController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            TextField(
              controller: _emailController,
              decoration: InputDecoration(labelText: 'Email address'),
            ),
            TextField(
              decoration: InputDecoration(labelText: 'Password'),
              obscureText: true,
              controller: _passwordController,
            ),
            ElevatedButton(
              onPressed: () => _submit(context),
              child: Text('SIGN IN'),
            ),
          ],
        ),
      ),
    );
  }

  void _submit(BuildContext context) async {
    final email = _emailController.text;
    final password = _passwordController.text;
    FirebaseAuth.instance
        .signInWithEmailAndPassword(email: email, password: password)
        .then((credential) async {
      final preferences = await SharedPreferences.getInstance();
      await preferences.setBool('IS_SIGNED_IN', true);

      Navigator.of(context).pushReplacementNamed('/welcome');
    });
  }
}

class WelcomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          children: [
            Text('Welcome!'),
            ElevatedButton(
              onPressed: () => _signOut(context),
              child: Text('SIGN OUT'),
            )
          ],
        ),
      ),
    );
  }

  void _signOut(BuildContext context) {
    FirebaseAuth.instance.signOut().then((_) async {
      final preferences = await SharedPreferences.getInstance();
      await preferences.setBool('IS_SIGNED_IN', false);

      Navigator.of(context).pushReplacementNamed('/signin');
    });
  }
}
```
</details>

1. **Ensure that the cloud_firestore dependency is included in the pubspec.yaml file**.
2. Start the auth emulator.
3. Run the reproducible example above.
4. Sign in.
5. Reload the page.
6. See error or incorrect behavior

### Expected behavior

The stream should emit the signed in user even after a browser page reload. The app in the example above should navigate to the welcome screen if there is a signed in user.

---

## Additional context

If it helps, I'm using version 8.3.0 of the Firebase Javascript libraries in my `index.html` file. Also, I'm only targeting the web platform, so please ignore the issues raised by the flutter doctor below.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.0.2, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.2 at C:\flutter\flutter_windows_2.0.2-stable
    • Framework revision 8962f6dc68 (5 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\lopez\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.54

! Doctor found issues in 2 categories.

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```

Dart SDK 2.12.1
Flutter SDK 2.0.2
my_app 1.0.0+1

dependencies:
- cloud_firestore 1.0.1 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_linkify 4.1.0 [flutter linkify]
- flutter_svg 0.19.3 [flutter meta path_drawing vector_math xml]
- google_fonts 2.0.0 [flutter http path_provider crypto]
- provider 5.0.0 [collection flutter nested]
- shared_preferences 2.0.4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- url_launcher 6.0.2 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.1 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- crypto 3.0.0 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.0 [http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- linkify 3.0.0
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- path 1.8.0
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 3.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.1.0 [file path platform]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]\

```

</details>

**Comment by zepol-yerffej** [comment]
**Update:** It looks like the issue only occurs when I am using the Firebase auth emulator. The app is behaving as expected after commenting out these lines:

```
  if (kDebugMode) {
    await FirebaseAuth.instance.useEmulator('http://localhost:1001');
  }
```

**Comment by zepol-yerffej** [comment]
Looking at my browser's console, I noticed that the app is trying to make a POST request to a Google URL:

![image](https://user-images.githubusercontent.com/75958174/111432817-770a1580-8738-11eb-81e1-448efa75232a.png)

Please excuse my ignorance, but why would the SDK call an online API when I meant to use the local emulator?

**Comment by markusaksli-nc** [comment]
Hi @zepol-yerffej 
I tried to reproduce this but I'm not seeing it using `firebase-tools` `9.6.1` with 
```yaml
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  shared_preferences: ^2.0.5
```
```html
  <script src="https://www.gstatic.com/firebasejs/8.3.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.3.0/firebase-auth.js"></script>
```
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 2.1.0-13.0.pre.133, on Microsoft Windows [Version 10.0.19041.867], locale et-EE)
    • Flutter version 2.1.0-13.0.pre.133 at C:\Development\flutter_master
    • Framework revision 4c0a8e01c1 (10 hours ago), 2021-03-16 18:43:03 -0700
    • Engine revision 525271dd80
    • Dart version 2.13.0 (build 2.13.0-143.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin version 54.0.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!
```
</details>

What version of `firebase-tools` are you on?
Thank you

**Comment by zepol-yerffej** [comment]
Odd. I am using 9.6.1 as well.

**Comment by zepol-yerffej** [comment]
I ran the app just now and I noticed that my browser's console have these error/warnings logged:

![image](https://user-images.githubusercontent.com/75958174/111463424-8732ec80-875a-11eb-9b40-d05175e8a3f6.png)

Is this the culprit?

**Comment by markusaksli-nc** [comment]
Well you are using a different port than the default one for auth emulator (9099), does this happen if you use the default one instead?

**Comment by zepol-yerffej** [comment]
Yes, it still does.

**Comment by markusaksli-nc** [comment]
Could you try to see if the behavior is different with a different browser?

**Comment by zepol-yerffej** [comment]
I've tried both Chrome and Chromium Edge. The issue persists on both browsers on my device.

**Comment by oldpilgrim** [comment]
Can confirm I have this problem too - only happens when auth is emulated.

In fact, this may not be related, but I noticed the auth emulator throws the following error when the app is loaded

```
Error: [firebase_auth/unknown] An unknown error occurred: TypeError: Cannot read property 'then' of undefined
    at Object.throw_ [as throw] (http://localhost:63017/dart_sdk.js:5334:11)
    at firebase_auth_web.FirebaseAuthWeb.new.useEmulator (http://localhost:63017/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:386:23)
    at useEmulator.throw (<anonymous>)
    at http://localhost:63017/dart_sdk.js:39038:38
    at _RootZone.runBinary (http://localhost:63017/dart_sdk.js:38894:58)
    at _FutureListener.thenAwait.handleError (http://localhost:63017/dart_sdk.js:33887:48)
    at handleError (http://localhost:63017/dart_sdk.js:34451:51)
    at Function._propagateToListeners (http://localhost:63017/dart_sdk.js:34477:17)
    at _Future.new.[_completeError] (http://localhost:63017/dart_sdk.js:34323:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:63017/dart_sdk.js:34362:31)
    at Object._microtaskLoop (http://localhost:63017/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:63017/dart_sdk.js:39182:13)
    at http://localhost:63017/dart_sdk.js:34689:9
```

**Comment by zepol-yerffej** [comment]
@oldpilgrim Have you found a workaround for this?

**Comment by markusaksli-nc** [comment]
Could you try to run `flutter clean` and rebuild?

Since our versions are all the same I don't really get where the difference is coming from here.

**Comment by zepol-yerffej** [comment]
@markusaksli-nc I just did and it's still not working.

**Comment by markusaksli-nc** [comment]
It has to be because of the errors you are seeing in the developer console since I'm not seeing anything like that. Clearly, some resources are failing to resolve which is causing the issue.

Any ideas @mikehardy ?

**Comment by oldpilgrim** [comment]
@zepol-yerffej I did find a workaround, which was to initialise the emulator in javascript in index.html lol

```
    // some code that initialises firebase config

    if (location.hostname === "localhost") {
      firebase.auth().useEmulator("http://localhost:9099");
    }
```

I guess this pins down the problem to flutterfire and not the JS SDK or the emulator tools

**Comment by zepol-yerffej** [comment]
@markusaksli-nc The problem goes away after removing the `cloud_firestore` dependency from my pubspec.yaml file. I also do  not get the errors in the browser console after doing this.

**Comment by zepol-yerffej** [comment]
I've updated the steps on how to reproduce the issue.

**Comment by oldpilgrim** [comment]
Interesting, I don't use cloud firestore and the issue still occurs for me.

To follow up on an earlier post:

> I ran the app just now and I noticed that my browser's console have these error/warnings logged:
> 
> ![image](https://user-images.githubusercontent.com/75958174/111463424-8732ec80-875a-11eb-9b40-d05175e8a3f6.png)
> 
> Is this the culprit?

It appears that flutterfire is trying to post to the following endpoint after reloading, 

`https://www.googleapis.com/identitytoolkit/v3/relyingparty/getAccountInfo?key=my_api_key`

i.e. fetching a real account instead of from the emulator. Maybe this is the issue.

**Comment by mikehardy** [comment]
> @zepol-yerffej I did find a workaround, which was to initialise the emulator in javascript in index.html lol
> 
> ```
>     // some code that initialises firebase config
> 
>     if (location.hostname === "localhost") {
>       firebase.auth().useEmulator("http://localhost:9099");
>     }
> ```
> 
> I guess this pins down the problem to flutterfire and not the JS SDK or the emulator tools

This is how it is implemented for testing and how I tested it for web - you have to set it for emulator first thing iirc

**Comment by oldpilgrim** [comment]
> This is how it is implemented for testing and how I tested it for web - you have to set it for emulator first thing iirc

Ah ok, yeah that makes sense tbh. Thanks for clarifying!

**Comment by zepol-yerffej** [comment]
> Edit: my hypothesis is that when the page is reloaded, flutterfire is not instrumented _in time_ to talk to the emulators, so it tries to fetch real credentials instead. However, instrumenting the emulators in JS in advance sidesteps this problem.
> 
> It's just a wild guess though as I don't know how flutterfire works under the hood.

That's what I am wondering too. Why is the SDK calling an online API when I need to use the auth emulator?

**Comment by mikehardy** [comment]
> That's what I am wondering too. Why is the SDK calling an online API when I need to use the auth emulator?

Perhaps because you have not asked it to use the emulator soon enough?

Upstream docs: https://firebase.google.com/docs/reference/js/firebase.auth.Auth#useemulator

> Modify this Auth instance to communicate with the Firebase Auth emulator. **This must be called synchronously immediately following the first call to firebase.auth()**. Do not use with production credentials as emulator traffic is not encrypted.

(emphasis added)

And in this repo: 

https://github.com/mikehardy/flutterfire/blob/a9914e8edbfd504e3453308fd6df3bec7d7aab5b/packages/firebase_auth/firebase_auth_web/lib/src/interop/auth.dart#L612-L619

```dart
  /// Configures the Auth instance to work with a local emulator
  ///
  /// Call with [origin] like 'http://localhost:9099'
  ///
  /// Note: must be called before using auth methods, do not use
  /// with production credentials as local connections are unencrypted
  Future useEmulator(String origin) =>
      handleThenable(jsObject.useEmulator(origin));
```

**Comment by zepol-yerffej** [comment]
I'm not sure how I can call `useEmulator()` sooner than what I have done in my example. It's literally called immediately after I initialized Firebase in my dart code.

Like what @oldpilgrim said, calling useEmulator() in JavaScript fixes the problem. I strongly believe that this should be mentioned in the official FlutterFire guide if this is the only way we can get Firebase Auth working properly when using the emulator. I never would've thought of doing that if I only relied on reading the official guide.

**Comment by mikehardy** [comment]
@zepol-yerffej if I understand correctly the docs here are all open source - I'm not familiar with the exact page you think could use the note but if you are you could hit the edit button on github and the github web UI makes document change suggestions the work of just a minute or two

**Comment by markusaksli-nc** [comment]
@zepol-yerffej In terms of how to call `useEmulator` sooner you can just add the call before `runApp` in main like
```dart
const bool USE_EMULATOR = true;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  if(USE_EMULATOR){
    await FirebaseAuth.instance.useEmulator('http://localhost:9099');
  }
  runApp(AuthExampleApp());
}
```
However this or the index.html workaround don't seem necessary since I didn't run into this issue with your code and nothing in `index.html` to configure the emulator. Not sure it should be added to the documentation if we can't reproduce the issue?

**Comment by pauldemarco** [comment]
Still experiencing this issue with latest version of firebase_auth ^3.1.0.

`getAccountInfo` is calling the google apis endpoint and not to the firebase_emulator:
```
{
  "error": {
    "code": 400,
    "message": "INVALID_ID_TOKEN",
    "errors": [
      {
        "message": "INVALID_ID_TOKEN",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

**Comment by russellwheatley** [comment]
The [docs](https://firebase.flutter.dev/docs/auth/usage#emulator-usage) already have a hint that the emulator is to be called immediately. There is nothing more to action on this issue.
