### ISSUE TITLE
🐛 [cloud_firestore] Exception UNAVAILABLE after toggling the internet connection

### ISSUE THREAD

**Issue by kestasb** [FirebaseExtended/flutterfire#5374]
## Bug report

We use `cloud_firestore` plugin in our app and we're receiving many reports from our app's users that data sometimes stops syncing. Firestore throws the following exception:

```
PlatformException(firebase_firestore, UNAVAILABLE: Unable to resolve host firestore.googleapis.com, {code: unavailable, message: The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.}, null)
```

We were finally able to reproduce it on Android physical device.

### Steps to reproduce

1. Build `cloud_firestore` example app from flutterfire on a physical Android device. 
<details><summary>_onLike method was modified to include timeout</summary>

```
_onLike(int current) async {
    // Increment the "like" count straight away to show feedback to the user.
    setState(() {
      _likes = current + 1;
    });

    try {
      // Return and set the updated "likes" count from the transaction
      int newLikes = await FirebaseFirestore.instance
          .runTransaction<int>((transaction) async {
        DocumentSnapshot txSnapshot = await transaction.get(widget.reference);

        if (!txSnapshot.exists) {
          throw Exception("Document does not exist!");
        }

        int updatedLikes = (txSnapshot.data()['likes'] ?? 0) + 1;
        transaction.update(widget.reference, {'likes': updatedLikes});
        return updatedLikes;
      }).timeout(const Duration(seconds: 5), onTimeout: () {
        print("onTimeout");
        throw Exception("onTimeout!");
      });

      // Update with the real count once the transaction has completed.
      setState(() {
        _likes = newLikes;
      });
    } catch (e, s) {
      print(s);
      print("Failed to update likes for document! $e");

      // If the transaction fails, revert back to the old count
      setState(() {
        _likes = current;
      });
    }
  }
```

</details>

2. When the app is opened, toggle the internet connection several times from WiFi to mobile data and vice versa. The most reliable way to reproduce the problem is by finishing the toggling process with the following sequence: turn off WiFi, turn on mobile data, turn on WiFi and turn off mobile data. (It may take several attempts)
3. Try to tap on a heart icon to add a like, it should fail and the following stack trace should appear:

```
W/Firestore(15363): (22.0.1) [WatchStream]: (48de14) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(15363): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:436)
W/Firestore(15363): 	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:272)
W/Firestore(15363): 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:228)
W/Firestore(15363): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Firestore(15363): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Firestore(15363): 	at java.lang.Thread.run(Thread.java:923)
W/Firestore(15363): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(15363): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
W/Firestore(15363): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/Firestore(15363): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
W/Firestore(15363): 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:646)
W/Firestore(15363): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:404)
W/Firestore(15363): 	... 5 more
W/Firestore(15363): }.
I/ViewRootImpl@6e3fdd0[FlutterActivity](15363): ViewPostIme pointer 0
I/ViewRootImpl(15363): updatePointerIcon pointerType = 1002, calling pid = 15363
D/InputManager(15363): setPointerIconType iconId = 1002, callingPid = 15363
I/ViewRootImpl@6e3fdd0[FlutterActivity](15363): ViewPostIme pointer 1
I/flutter (15363): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
I/flutter (15363): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
I/flutter (15363): <asynchronous suspension>
I/flutter (15363): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358:43)
I/flutter (15363): <asynchronous suspension>
I/flutter (15363): #3      MethodChannelTransaction.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_transaction.dart:45:41)
I/flutter (15363): <asynchronous suspension>
I/flutter (15363): #4      Transaction.get (package:cloud_firestore/src/transaction.dart:26:9)
I/flutter (15363): <asynchronous suspension>
I/flutter (15363): #5      _Likes._onLike.<anonymous closure> (package:cloud_firestore_example/main.dart:318:39)
I/flutter (15363): <asynchronous suspension>
I/flutter (15363): #6      FirebaseFirestore.runTransaction.<anonymous closure> (package:cloud_firestore/src/firestore.dart:167:16)
I/flutter (15363): <asynchronous suspension>
I/flutter (15363): #7      MethodChannelFirebaseFirestore.runTransaction.<anonymous closure> (package:cloud_firestore_platform_interface/src/method_channel/method_channel
I/flutter (15363): Failed to update likes for document! PlatformException(firebase_firestore, UNAVAILABLE: Unable to resolve host firestore.googleapis.com, {code: unavailable, message: The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.}, null)
I/ViewRootImpl(15363): updatePointerIcon pointerType = 1002, calling pid = 15363
D/InputManager(15363): setPointerIconType iconId = 1002, callingPid = 15363
W/Firestore(15363): (22.0.1) [WatchStream]: (48de14) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(15363): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:436)
W/Firestore(15363): 	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:272)
W/Firestore(15363): 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:228)
W/Firestore(15363): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Firestore(15363): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Firestore(15363): 	at java.lang.Thread.run(Thread.java:923)
W/Firestore(15363): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(15363): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
W/Firestore(15363): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/Firestore(15363): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
W/Firestore(15363): 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:646)
W/Firestore(15363): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:404)
W/Firestore(15363): 	... 5 more
W/Firestore(15363): }.
```

4. All the following attempts to add a like results in a timeout:
```
Failed to update likes for document! Exception: onTimeout!
```

For some reason, sort actions which fetch data from Firestore still work. To make everything work again just turn the internet connection off/on.

### Expected behavior

Firestore connection status should update according to the internet connection status.

---

## Additional context

We managed to reproduce this issue on Samsung Galaxy S10e device with Android 11.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-LT)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)
• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0-259.16.beta
Flutter SDK 1.26.0-17.8.pre
cloud_firestore_example 0.0.0

dependencies:
- cloud_firestore 0.16.0+1 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- drive 0.0.1-6.0.pre [test_api flutter_test flutter_driver cli_util stack_trace universal_platform source_map_stack_trace flutter]
- flutter_driver 0.0.0 [file meta path vm_service webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- pedantic 1.11.0
- test 1.16.5 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

dependency overrides:
- cloud_firestore_platform_interface 3.0.2 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.2 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- cli_util 0.1.4 [path]
- clock 1.1.0
- cloud_firestore_web 0.3.0+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- coverage 0.15.2 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0 [clock collection]
- file 6.0.0 [meta path]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.0.0 [async collection file path pedantic string_scanner]
- http_multi_server 3.0.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- logging 1.0.0
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- node_preamble 1.4.13
- package_config 1.9.3 [path charcode]
- path 1.8.0
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.0.0 [file path platform]
- pub_semver 2.0.0 [collection]
- quiver 2.1.5 [matcher meta]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.1 [path shelf shelf_static]
- shelf_static 0.2.9+2 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.2.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.15 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.0 [collection]
- universal_platform 0.1.3
- vector_math 2.1.0
- vm_service 5.5.0 [meta]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.0.0 [logging]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @kestasb 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5374.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Comment by kestasb** [comment]
Hi @markusaksli-nc 
You referenced the issue #5374, which is this one. I wrote a comment in the #2753 issue. Since it is a critical issue for our app and I haven't received any reply to that comment, I decided to create a new issue with reproducible steps to get more attention to this problem.
Let me know if I should still write a comment in the issue you intended to reference.

**Comment by markusaksli-nc** [comment]
Sorry got my issue urls mixed up, meant https://github.com/FirebaseExtended/flutterfire/issues/3615

Feel free to comment there with this information

**Comment by frankyvij** [comment]
@kestasb do you have a potential solution for this? Is this a FirebaseAuth problem?

**Comment by kestasb** [comment]
@frankyvij I haven't found any solution yet. As someone from Firebase wrote in #2753 it's not a FlutterFire issue, but an issue of Firebase Android SDK, so we need to raise a new issue there. I found similar issues in Firebase Android SDK without any solution, so I didn't bother creating a new one.

**Comment by frankyvij** [comment]
I wonder if it is only a few of us who are having this problem. In my case, when the user opens the app after a while when the app was in the background, he will not be able to establish a connection for about 10-20 seconds. I am not sure if this is the expected behavior. I also see a similar "Unable to resolve host "firestore.googleapis.com": No address associated with hostname" error in the logs.
