### ISSUE TITLE
🐛 [firebase_auth] [google_sign_in] MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)

### ISSUE THREAD

**Issue by bwobst** [FirebaseExtended/flutterfire#5444]
## Bug report

When a user opens the Flutter macOS application, they are presented with a login screen where they can only log in with Google. When the user clicks the button to log in with Google, nothing happens on the UI, but this error is logged to the console:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)
#0        MethodChannel._invokeMethod        package:flutter/…/services/platform_channel.dart:156
#1        GoogleSignIn._callMethod           package:google_sign_in/google_sign_in.dart:231
#2        GoogleSignIn.signIn.isCanceled     package:google_sign_in/google_sign_in.dart:1
```

### Steps to reproduce

1. Clone [this](https://github.com/bwobst/sage_flutter_macos) repo.
1. You'll need to generate a `GoogleService-Info.plist` in Firebase and add it to `Runner/Runner/` via Xcode by opening `macos/Runner.xcodeproj`. The bundle ID of this app is `com.example.sageFlutterMacos`.
1. `cd` into the directory and run `flutter run -d macos`.
1. Click the "Login with Google" button.
1. Observe the error mentioned above.

### Expected behavior

Open a separate window to authenticate the user via Google.

---

### Missing plugin registration?
[This ticket](https://github.com/flutter/flutter/issues/10912#issuecomment-310499594) asks whether  `GeneratedPluginRegistrant.swift` includes the plugin in question. Granted, it's referring to iOS, but I assume would hold true for a macOS Flutter application. It does not include any references to the Google sign in dependency. Definitely seems suspect.
```
//
//  Generated file. Do not edit.
//

import FlutterMacOS
import Foundation

import cloud_firestore
import firebase_auth
import firebase_core

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
  FLTFirebaseFirestorePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseFirestorePlugin"))
  FLTFirebaseAuthPlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseAuthPlugin"))
  FLTFirebaseCorePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseCorePlugin"))
}

```

### Other devices
The expected behavior works without issue on the following devices:
* Pixel XL (API 29)
* iOS Simulator (iPhone 12 Pro Max)
* Chrome web

### Just read the instructions
I followed the [official macOS installation documentation](https://firebase.flutter.dev/docs/installation/macos) and reviewed it multiple times to make sure I wasn't missing anything.

### Additional logs
Starting up the Flutter macOS application shows these logs:
```
Downloading darwin-x64/FlutterMacOS.framework tools...
Downloading darwin-x64-profile/FlutterMacOS.framework tools...
Downloading darwin-x64-profile tools...
Downloading darwin-x64-release/FlutterMacOS.framework tools...
Downloading darwin-x64-release tools...
Running "flutter pub get" in sage_flutter...
Launching lib/main.dart on macOS in debug mode...
lib/main.dart:1
ld: warning: dylib (/Users/brianwobst/code/sage/sage_flutter/build/macos/Build/Products/Debug/BoringSSL-GRPC/openssl_grpc.framework/openssl_grpc) was built for newer macOS version (10.12) than being linked (10.9)
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
Connecting to VM Service at ws://127.0.0.1:54674/ke0TkYpUYAQ=/ws
```
I've previously mucked around with the Pods Xcode project to clear the `dylib` warning above, but still got the same `MissingPluginException` error.

Clicking the "Login with Google" button outputs the error in the first section.

### Null safety
I'm running this project with null safety enabled.

---

### Flutter doctor

I tried on both the `stable` and `master` channels. All behavior and runtime log output was identical.

<details><summary>channel: stable</summary>

```
Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (5 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

[✓] Flutter (Channel stable, 2.0.3, on macOS 11.3 20E5210c darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)
```

</details>

<details><summary>channel: master</summary>

```
Flutter 2.1.0-13.0.pre.223 • channel master • https://github.com/flutter/flutter.git
Framework • revision 891511d58f (71 minutes ago) • 2021-03-23 14:57:01 -0700
Engine • revision d59a01d2d3
Tools • Dart 2.13.0 (build 2.13.0-150.0.dev)

[✓] Flutter (Channel master, 2.1.0-13.0.pre.223, on macOS 11.3 20E5210c darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)
```

</details>

---

### Flutter dependencies

<details><summary>channel: stable</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.3
sage_flutter 1.0.0+1

dependencies:
- cloud_firestore 1.0.2 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- fl_chart 0.30.0 [flutter equatable pedantic]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 9.0.0 [flutter]
- google_sign_in 5.0.1 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- provider 5.0.0 [collection flutter nested]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.2 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- equatable 2.0.0 [collection meta]
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- path 1.8.0
- pedantic 1.11.0
- plugin_platform_interface 2.0.0 [meta]
- quiver 3.0.0 [matcher]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by bwobst** [comment]
[google_sign_in](https://pub.dev/packages/google_sign_in) doesn't support desktop yet.
