### ISSUE TITLE
TypeError: dart.global.firebase.auth is not a function

### ISSUE THREAD

**Issue by bcagarwal** [FirebaseExtended/flutterfire#5451]
Hi,

I created a simple Flutter Web project in VS Code with "Anonymous Sign". I am using Firebase Auth and the anonymous sign-in works fine with iOS simulator and Android emulator, but when I am running the same for web, I am getting 

The below is the error message when I use a try/catch block

```
NoSuchMethodError: tried to call a non-function, such as null: 'dart.global.firebase.auth'
```
The below is the stacktrace when I run the app without try/catch.

**Stacktrace**:

```
TypeError: dart.global.firebase.auth is not a function
    at Object.getAuthInstance (http://localhost:59963/packages/firebase_auth_web/src/interop/auth.dart.lib.js:974:70)
    at new firebase_auth_web.FirebaseAuthWeb.new (http://localhost:59963/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:432:27)
    at firebase_auth_web.FirebaseAuthWeb.__.delegateFor (http://localhost:59963/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:75:14)
    at Function.instanceFor (http://localhost:59963/packages/firebase_auth_platform_interface/src/types.dart.lib.js:1520:77)
    at firebase_auth.FirebaseAuth.__.get [_delegate] (http://localhost:59963/packages/firebase_auth/firebase_auth.dart.lib.js:100:135)
    at firebase_auth.FirebaseAuth.__.signInAnonymously (http://localhost:59963/packages/firebase_auth/firebase_auth.dart.lib.js:246:68)
    at signInAnonymously.next (<anonymous>)
    at runBody (http://localhost:59963/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:59963/dart_sdk.js:37260:7)
    at firebase_auth.FirebaseAuth.__.signInAnonymously (http://localhost:59963/packages/firebase_auth/firebase_auth.dart.lib.js:245:20)
    at _signInAnonymously (http://localhost:59963/packages/time_tracker/app/sign_in/sign_in_page.dart.lib.js:702:74)
    at _signInAnonymously.next (<anonymous>)
    at runBody (http://localhost:59963/dart_sdk.js:37229:34)
    at Object._async [as async] (http://localhost:59963/dart_sdk.js:37260:7)
    at sign_in_page.SignInPage.new.[_signInAnonymously] (http://localhost:59963/packages/time_tracker/app/sign_in/sign_in_page.dart.lib.js:701:20)
at ink_well._InkResponseState.new.[_handleTap] (http://localhost:59963/packages/flutter/src/material/icon_button.dart.lib.js:50084:42)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:59963/packages/flutter/src/gestures/recognizer.dart.lib.js:201:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:59963/packages/flutter/src/gestures/tap.dart.lib.js:417:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:59963/packages/flutter/src/gestures/tap.dart.lib.js:223:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:59963/packages/flutter/src/gestures/tap.dart.lib.js:169:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:59963/packages/flutter/src/gestures/recognizer.dart.lib.js:456:16)
    at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:59963/packages/flutter/src/gestures/pointer_router.dart.lib.js:103:9)
    at http://localhost:59963/packages/flutter/src/gestures/pointer_router.dart.lib.js:138:26
    at LinkedMap.new.forEach (http://localhost:59963/dart_sdk.js:25048:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:59963/packages/flutter/src/gestures/pointer_router.dart.lib.js:135:29)
    at pointer_router.PointerRouter.new.route (http://localhost:59963/packages/flutter/src/gestures/pointer_router.dart.lib.js:127:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:330:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:313:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:59963/packages/flutter/src/rendering/layer.dart.lib.js:6071:13)
at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately] (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:284:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:257:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:246:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:59963/packages/flutter/src/gestures/binding.dart.lib.js:236:65)
    at Object.invoke1 (http://localhost:59963/dart_sdk.js:173249:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:59963/dart_sdk.js:155201:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:59963/dart_sdk.js:155815:49)
    at http://localhost:59963/dart_sdk.js:156224:26
    at http://localhost:59963/dart_sdk.js:156183:16
    at http://localhost:59963/dart_sdk.js:155908:11
```

**code**:

```
Future<void> _signInAnonymously() async {
      final userCredentials =  await FirebaseAuth.instance.signInAnonymously();
      print('${userCredentials.user!.uid}');
  }
```

I searched online to find a solution to this problem and could not find any concrete solution. I then found the similar issue in this github link 

https://github.com/FirebaseExtended/flutterfire/issues/2860

And moved all the firebase related stuff under **head** tag, but it did not help me to fix the issue.

The below is the content of my **index.html** file

```
<!DOCTYPE html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    Fore more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
  -->
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="time_tracker">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>time_tracker</title>
  <link rel="manifest" href="manifest.json">
  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="https://www.gstatic.com/firebasejs/8.3.1/firebase-app.js"></script>


  <!-- TODO: Add SDKs for Firebase products that you want to use
      https://firebase.google.com/docs/web/setup#available-libraries -->

  <script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
      //**My Firebase Config**
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>
</head>
<body> 
  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```
**pubspec.yaml** entries for sdk and firebase version

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
```

**Flutter Doctor**

This is the output of flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
```

**\<Path\>** is user path on my mac.

And the output of **flutter doctor -v**:

```
[✓] Flutter (Channel beta, 2.0.1, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.0.1 at **<Path>**/flutter
    • Framework revision c5a4b4029c (3 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at **<Path>**/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found
```

The out of of  **flutter run -d chrome --verbose**:

**\<Path\>** is user path where the flutter is running/ path of the librabry on my mac.

```
[ +129 ms] executing: [**<Path>**/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +82 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +5 ms] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[   +1 ms] executing: [**<Path>**/flutter/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[  +86 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] 2.0.1
[  +69 ms] executing: [**<Path>**/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [**<Path>**/flutter/] git ls-remote --get-url origin
[  +20 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +81 ms] executing: [**<Path>**/flutter/] git rev-parse --abbrev-ref HEAD
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +16 ms] executing: sw_vers -productName
[  +29 ms] Exit code 0 from: sw_vers -productName
[        ] macOS
[        ] executing: sw_vers -productVersion
[  +31 ms] Exit code 0 from: sw_vers -productVersion
[        ] 11.2.3
[        ] executing: sw_vers -buildVersion
[  +31 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 20D91
[  +11 ms] executing: sysctl hw.optional.arm64
[  +29 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[ +131 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +109 ms] executing: **<Path>**/Library/Android/sdk/platform-tools/adb devices -l
[  +11 ms] executing: /usr/bin/xcode-select --print-path
[  +18 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[  +24 ms] executing: sysctl hw.optional.arm64
[  +28 ms] Exit code 1 from: sysctl hw.optional.arm64
[   +1 ms] sysctl: unknown oid 'hw.optional.arm64'
[        ] executing: xcrun xcodebuild -version
[+1536 ms] Exit code 0 from: xcrun xcodebuild -version
[        ] Xcode 12.2
           Build version 12B45b
[   +5 ms] executing: xcrun xcdevice list --timeout 2
[   +7 ms] xcrun simctl list --json devices
[        ] executing: xcrun simctl list --json devices
[  +27 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +133 ms] executing: **<Path>**/Library/Android/sdk/platform-tools/adb devices -l
[        ] executing: xcrun xcdevice list --timeout 2
[        ] xcrun simctl list --json devices
[        ] executing: xcrun simctl list --json devices
[  +27 ms] Skipping pub get: version match.
[  +68 ms] Found plugin firebase_auth at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
[  +29 ms] Found plugin firebase_auth_web at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.2/
[   +6 ms] Found plugin firebase_core at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.1/
[  +10 ms] Found plugin firebase_core_web at
**<Path>**flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.1/
[ +225 ms] Found plugin firebase_auth at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
[   +5 ms] Found plugin firebase_auth_web at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.2/
[   +7 ms] Found plugin firebase_core at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.1/
[   +5 ms] Found plugin firebase_core_web at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.1/
[  +80 ms] Generating
**<Path>**/projects/time_tracker/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +191 ms] List of devices attached
[   +7 ms] List of devices attached
[ +255 ms] Launching lib/main.dart on Chrome in debug mode...
[  +58 ms] {
             "devices" : {
               "com.apple.CoreSimulator.SimRuntime.watchOS-7-1" : [

               ],
               "com.apple.CoreSimulator.SimRuntime.tvOS-14-2" : [

               ],
               "com.apple.CoreSimulator.SimRuntime.iOS-14-2" : [
                 {
                   "dataPath" :
                   "\**<Path>**/Library\/Developer\/CoreSimulator\/Devices\/E305E2BA-3EC2-4720-B6D5-8324B0541A40\/data",
                   "logPath" : "\**<Path>**/Library\/Logs\/CoreSimulator\/E305E2BA-3EC2-4720-B6D5-8324B0541A40",
                   "udid" : "E305E2BA-3EC2-4720-B6D5-8324B0541A40",
                   "isAvailable" : true,
                   "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus",
                   "state" : "Shutdown",
                   "name" : "iPhone 8 Plus"
                 }
               ]
             }
           }
[   +8 ms] {
             "devices" : {
               "com.apple.CoreSimulator.SimRuntime.watchOS-7-1" : [

               ],
               "com.apple.CoreSimulator.SimRuntime.tvOS-14-2" : [

               ],
               "com.apple.CoreSimulator.SimRuntime.iOS-14-2" : [
                 {
                   "dataPath" :
                   "\**<Path>**/Library\/Developer\/CoreSimulator\/Devices\/E305E2BA-3EC2-4720-B6D5-8324B0541A40\/data",
                   "logPath" : "\**<Path>**/Library\/Logs\/CoreSimulator\/E305E2BA-3EC2-4720-B6D5-8324B0541A40",
                   "udid" : "E305E2BA-3EC2-4720-B6D5-8324B0541A40",
                   "isAvailable" : true,
                   "deviceTypeIdentifier" : "com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus",
                   "state" : "Shutdown",
                   "name" : "iPhone 8 Plus"
                 }
               ]
             }
           }
[ +280 ms] Updating assets
[ +304 ms] Waiting for connection from debug service on Chrome...
[  +38 ms] Found plugin firebase_auth at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
[  +32 ms] Found plugin firebase_auth_web at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.2/
[  +18 ms] Found plugin firebase_core at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.1/
[  +32 ms] Found plugin firebase_core_web at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.1/
[  +99 ms] Found plugin firebase_auth at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-1.0.1/
[   +4 ms] Found plugin firebase_auth_web at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-1.0.2/
[   +3 ms] Found plugin firebase_core at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.1/
[   +3 ms] Found plugin firebase_core_web at
**<Path>**/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.0.1/
[ +241 ms] <- reset
[  +31 ms] **<Path>**/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
**<Path>**/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
**<Path>**/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
/var/folders/lp/pvh80_qj7696l8dkw4lbkfx00000gn/T/flutter_tools.ATjcfg/flutter_tool.tA0W0X/app.dill --libraries-spec
file://**<Path>**/flutter/bin/cache/flutter_web_sdk/libraries.json --packages
**<Path>**/projects/time_tracker/.dart_tool/package_config.json -Ddart.vm.profile=false
-Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root
/var/folders/lp/pvh80_qj7696l8dkw4lbkfx00000gn/T/flutter_tools.ATjcfg/flutter_tools.qrvpH1 --filesystem-scheme org-dartlang-app
--initialize-from-dill build/b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file://**<Path>**/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +52 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+2713 ms] [
                      {
                        "simulator" : true,
                        "operatingSystemVersion" : "14.2 (18B79)",
                        "available" : true,
                        "platform" : "com.apple.platform.iphonesimulator",
                        "modelCode" : "iPhone10,5",
                        "identifier" : "E305E2BA-3EC2-4720-B6D5-8324B0541A40",
                        "architecture" : "x86_64",
                        "modelUTI" : "com.apple.iphone-8-plus-2",
                        "modelName" : "iPhone 8 Plus",
                        "name" : "iPhone 8 Plus"
                      }
                    ]
[   +5 ms] [
             {
               "simulator" : true,
               "operatingSystemVersion" : "14.2 (18B79)",
               "available" : true,
               "platform" : "com.apple.platform.iphonesimulator",
               "modelCode" : "iPhone10,5",
               "identifier" : "E305E2BA-3EC2-4720-B6D5-8324B0541A40",
               "architecture" : "x86_64",
               "modelUTI" : "com.apple.iphone-8-plus-2",
               "modelName" : "iPhone 8 Plus",
               "name" : "iPhone 8 Plus"
             }
           ]
[+31620 ms] Waiting for connection from debug service on Chrome... (completed in 34.9s)
[   +1 ms] Synced 30.5MB.
[        ] <- accept
[        ] Caching compiled dill
[ +180 ms] Using Google Chrome 89.0.4389.90 

[+7319 ms] [CHROME]:
[   +2 ms] [CHROME]:DevTools listening on ws://127.0.0.1:59539/devtools/browser/abe2d0a8-fa39-4981-b74b-e72514bc5866
[+1717 ms] DwdsInjector: Received request for entrypoint at http://localhost:59513/main_module.bootstrap.js
[  +39 ms] MetadataProvider: Loading debug metadata...
[  +47 ms] MetadataProvider: Loaded debug metadata
[  +31 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:59513/main_module.bootstrap.js
[+3699 ms] DevHandler: Debug service listening on ws://127.0.0.1:59563/Fh39UhRgdjE=/ws

[  +21 ms] Debug service listening on ws://127.0.0.1:59563/Fh39UhRgdjE=/ws
[        ] 💪 Running with sound null safety 💪
[   +4 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
```

[flutter web app error.docx](https://github.com/FirebaseExtended/flutterfire/files/6198295/flutter.web.app.error.docx)
.

**Comment by markusaksli-nc** [comment]
Hi @bcagarwal 
Please add the JS SDK imports indicated in the official documentation.
https://firebase.flutter.dev/docs/auth/overview#3-web-only-add-the-sdk
The issue you linked is very old and there is no need to add these into `head` as far as I am aware.
Thank you

**Comment by bcagarwal** [comment]
@markusaksli-nc Thank you so much for your help. I moved the firebase related stuff under ```body``` and added the firebase-auth JavaScript SDK to the ```index.html```. And the issue is fixed. 

Do we have to add the respective Firebase JavaScript SDK in ```index.html``` always if we plan to use any?

**Comment by markusaksli-nc** [comment]
Yep, as always you can take a look at the steps for each package https://firebase.flutter.dev/docs (except for some that we haven't added there yet).

And about the version - we test against a fixed Firebase JS SDK version (currently 7.20.0) so if you use a newer version you might run into issues.

**Comment by bcagarwal** [comment]
@markusaksli-nc I am using 8.3.1 as suggested during the app setup in Firebase console. As you are suggesting, it is better to use 7.20.0. In that case, will the below version in ```pubsec.yaml``` work fine with 7.20.0?

```
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
```

**Comment by markusaksli-nc** [comment]
It is better to use 7.20.0 and it will work with the latest versions of all of the FlutterFire packages since that's what we test against to make sure it works. That being said if the latest JS SDK works feel free to use it, just know that the FlutterFire implementation will be unstable on it.

On `8.3.1` I'm not currently aware of any issues for `firebase_auth` but there is at least one known issue on `cloud_firestore` that prevents users from using any JS SDK version above 8.0.0 https://github.com/FirebaseExtended/flutterfire/issues/4127

**Comment by bcagarwal** [comment]
My apologies for responding late. Thank you so much for your reply. I will use 7.20.0 and continue my development. 
I would like to contribute to Firebase, if possible. May be I will start with small minor testing/coding and build my capability under your guidance to take up major things when I am ready. Please let me know if it is possible and guide me to build my capability.

**Comment by markusaksli-nc** [comment]
The best way to do that is to just work on any issue you feel you can fix and then submit a PR and get feedback on it. Also the contributors guide https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md

**Comment by bcagarwal** [comment]
Thank you for your reply. I will check if I can fix any issue with my limited knowledge. 

On a side note, I am trying to add "Sign in Google" functionality in the Web Project and I am getting 
```
"ClientID not set. Either set it on a <meta name=\"google-signin-client_id\" content=\"CLIENT_ID\" /> tag, or pass clientId when calling init()"
```

I googled for this error and found that I need to create an **OAuth client ID** in the Google Cloud Platform as per the step mentioned in the below link. 

https://developers.google.com/identity/sign-in/web/sign-in#before_you_begin

Is that correct? Please guide me.
