### ISSUE TITLE
🐛 [firebase_messaging] "Notifications are not allowed for this application" issue on MacOS

### ISSUE THREAD

**Issue by subhash279** [FirebaseExtended/flutterfire#5473]
## Bug report

**Describe the bug**
Call `firebaseMessaging.requestPermission` on MacOS and it returns an error.
`2021-03-25 18:46:00.242 podurama[97864:1343340] FLTFirebaseMessaging: An error occurred while calling method Messaging#requestPermission, errorOrNil => {
    NSLocalizedDescription = "Notifications are not allowed for this application";
}
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [firebase_messaging/unknown] Notifications are not allowed for this application
#0      MethodChannelFirebaseMessaging.requestPermission (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:280:7)
<asynchronous suspension>
#1      _notificationSettings._generalNotificationSettings.<anonymous closure> (package:podcastApp/presentation/Tabs/Account/notificationSettings.dart:271:19)
<asynchronous suspension>`

### Steps to reproduce

1. Call `firebaseMessaging.requestPermission` on MacOS and it returns an error.

### Expected behavior

It should show the user prompt to allow/disable notifications.

---

## Additional context

-

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.3 20E5196f darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0
Flutter SDK 2.0.1
podcastApp 1.8.8+1

dependencies:
- audio_service 0.17.0-nullsafety.0 [audio_session rxdart flutter_isolate flutter_cache_manager js flutter flutter_web_plugins]
- better_player 0.0.63 [flutter cupertino_icons wakelock pedantic meta flutter_widget_from_html_core visibility_detector path_provider collection]
- cached_network_image 3.0.0-nullsafety [flutter flutter_cache_manager octo_image]
- carousel_slider 2.3.4 [flutter]
- cloud_firestore 1.0.2 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- connectivity 3.0.3 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- convert 2.1.1 [charcode typed_data]
- crypto 3.0.0 [collection typed_data]
- cupertino_icons 1.0.2
- dart_chromecast 0.2.4 [protobuf protoc_plugin cli_util args xml logging multicast_dns]
- device_info 0.4.2+6 [flutter]
- dio 4.0.0-prev3 [http_parser path]
- email_validator 1.0.6
- file_picker 1.10.0 [flutter flutter_plugin_android_lifecycle]
- file_selector 0.8.2 [flutter file_selector_platform_interface file_selector_web]
- file_selector_macos 0.0.4 [flutter]
- firebase_analytics 7.1.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_crashlytics 1.0.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 9.0.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.6.0 [flutter firebase_core]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_downloader 1.5.2 [flutter]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_html 2.0.0-nullsafety.0 [html csslib css_colors flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter]
- flutter_mdns_plugin 0.0.2 [flutter]
- flutter_rating_bar 4.0.0 [flutter]
- flutter_redux 0.7.0 [meta redux flutter]
- flutter_reorderable_list 0.1.5 [flutter]
- flutter_slidable 0.5.7 [flutter]
- flutter_sparkline 0.1.0 [flutter]
- flutter_staggered_animations 0.1.3 [flutter]
- font_awesome_flutter 8.12.0 [flutter]
- fuzzy 0.2.4 [latinize meta]
- get 3.26.0 [flutter]
- google_sign_in 5.0.1 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- hive 2.0.0 [meta crypto]
- hive_flutter 1.0.0 [flutter hive path_provider path]
- html_unescape 2.0.0
- http 0.13.0 [http_parser meta path pedantic]
- instabug_flutter 9.1.8 [flutter stack_trace meta]
- intl 0.17.0 [clock path]
- intro_views_flutter 2.9.0 [flutter]
- just_audio 0.7.0 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- material_segmented_control 2.1.1+1 [flutter]
- memoize 2.0.0
- meta 1.3.0
- minimize_app 0.1.1 [flutter]
- modal_bottom_sheet 1.0.0+1 [flutter]
- package_info 0.4.3+4 [flutter]
- palette_generator 0.2.3 [flutter collection path]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_ex 1.0.1 [flutter]
- permission_handler 6.1.1 [flutter meta permission_handler_platform_interface]
- pull_to_refresh 1.6.4 [flutter]
- readmore 1.0.1 [flutter]
- redux 4.0.0+3
- redux_thunk 0.3.0 [redux]
- share_plus 2.0.0 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 1.1.2 [flutter]
- sign_in_with_apple 3.0.0 [flutter meta]
- slugify2 0.2.1
- styled_widget 0.2.2 [flutter]
- system_info 0.1.3 [file_utils path]
- theme_provider 0.5.0 [flutter shared_preferences]
- transparent_image 1.0.0
- url_launcher 6.0.2 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
- uuid 3.0.2 [crypto]
- wakelock 0.4.0 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web]
- webview_flutter 2.0.2 [flutter]

dev dependencies:
- build_runner 1.11.5 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_native_splash 1.1.5+1 [image meta path xml yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- hive_generator 1.0.0 [build source_gen hive analyzer]
- mockito 3.0.2 [collection matcher meta test]
- test 1.16.5 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

dependency overrides:
- audio_session 0.1.0 [flutter flutter_web_plugins rxdart]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.2 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.2 [crypto path]
- args 1.6.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 1.6.2 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.6 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.3 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.10 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- chewie 1.0.0 [cupertino_icons flutter video_player wakelock]
- chewie_audio 1.2.0 [cupertino_icons flutter video_player]
- cli_util 0.2.0 [path]
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.2 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- connectivity_for_web 0.4.0 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.2.0 [flutter]
- connectivity_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- coverage 0.15.2 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.1+1 [flutter meta]
- css_colors 1.1.0 [flutter]
- csslib 0.17.0 [source_span]
- dart_style 1.3.12 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- file_selector_platform_interface 2.0.2 [flutter meta http plugin_platform_interface cross_file]
- file_selector_web 0.8.1 [file_selector_platform_interface flutter flutter_web_plugins meta]
- file_utils 0.1.4 [globbing path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.2.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.0.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 2.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 2.0.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.2 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_blurhash 0.5.4-nullsafety.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.0-nullsafety.2 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_isolate 2.0.0 [flutter uuid]
- flutter_layout_grid 1.0.0-nullsafety.6 [flutter collection meta quiver]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_svg 0.21.0-nullsafety.0 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- flutter_widget_from_html_core 0.6.0-rc.2021031201 [flutter html]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- globbing 0.3.1 [path]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 0.2.0
- html 0.15.0 [csslib source_span]
- http_multi_server 2.2.0 [async]
- image 3.0.2 [archive meta xml]
- io 0.3.5 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- just_audio_platform_interface 3.0.0 [flutter plugin_platform_interface]
- just_audio_web 0.3.0 [just_audio_platform_interface flutter flutter_web_plugins]
- latinize 0.0.2
- logging 0.11.4
- matcher 0.12.10 [stack_trace]
- mime 1.0.0
- multicast_dns 0.2.2 [meta]
- node_preamble 1.4.13
- octo_image 1.0.0-nullsafety.1 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0
- path_drawing 0.5.0-nullsafety.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0-nullsafety.0 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- permission_handler_platform_interface 3.1.1 [flutter meta plugin_platform_interface]
- petitparser 4.0.2 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- protobuf 2.0.0 [fixnum]
- protoc_plugin 20.0.0 [fixnum path protobuf dart_style]
- pub_semver 2.0.0 [collection]
- pubspec_parse 0.1.8 [checked_yaml json_annotation pub_semver yaml]
- quiver 3.0.0 [matcher]
- rxdart 0.26.0
- share_plus_linux 2.0.0 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.0 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.0 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.0 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.0 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.1 [path shelf shelf_static]
- shelf_static 0.2.9+2 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 0.9.10+3 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.15 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- video_player 2.0.2 [meta video_player_platform_interface video_player_web flutter flutter_test]
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.0 [flutter flutter_web_plugins meta video_player_platform_interface]
- visibility_detector 0.2.0-nullsafety.1 [flutter]
- vm_service 6.1.0+1
- wakelock_macos 0.1.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.0 [flutter meta]
- wakelock_web 0.2.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- webkit_inspection_protocol 0.7.5 [logging]
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.0.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment]
The error should go away if you enable notifications from `System Preferences > Notifications`. I understand why this isn't ideal. Not sure if this is an issue with the native SDK or how this should work. 

Labelling this as reproducible with `firebase_messaging: ^9.1.0`
<details>
 <summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.1.0-13.0.pre.287, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
    • Flutter version 2.1.0-13.0.pre.287 at /Users/nevercode/development/flutter_master
    • Framework revision bc2c7954db (9 hours ago), 2021-03-25 20:55:16 -0700
    • Engine revision b5e15d055d
    • Dart version 2.13.0 (build 2.13.0-162.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (4 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.4.1
    • iPhone 12 Pro Max (mobile)  • 42B7F3DF-3053-419B-BA8F-FF1218F7A174     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 89.0.4389.90
    ! Error: Nevercode’s iPhone is busy: Copying cache files from device. Xcode will continue when Nevercode’s iPhone is finished. (code -10)

• No issues found!
```
</details>

**Comment by subhash279** [comment]
@markusaksli-nc thanks for the response. But as you said this is not ideal. Also while testing the app will not appear in `System Preferences > Notifications`. So I am not sure if there is way to test if it's even working.

**Comment by efraespada** [comment]
Same problem here.

**Comment by efraespada** [comment]
In my case, I just enabled the notifications for my app in the System Preferences but I guess the request method should launch a popup asking for that permission.

**Comment by jayjah** [comment]
Even in version 
```
firebase_messaging: 10.0.2
```

Actually while debugging it's not possible to enable notifications per system settings as app is not installed as an usual macos app, at least for me.

**Comment by mauricio-ms** [comment]
Set the `Product Name` with english characters and if you wish to use non-english characters set the `CFBundleDisplayName` at `Info.plist`

**Comment by kulture-rob-snider** [comment]
I am getting the same issue when running locally on Apple silicon with 11.1.0

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-US)
    • Flutter version 2.5.3 at /Users/rob/developement/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/rob/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • A82FF32E-7605-4548-9FA1-6A81F0DC3B47 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 96.0.4664.55

• No issues found!
```
