### ISSUE TITLE
🐛 [cloud_firestore] Cloud Firestore for WEB is throwing [cloud_firestore/permission-denied] Missing or insufficient permissions.

### ISSUE THREAD

**Issue by Bartozo** [FirebaseExtended/flutterfire#5495]
## Bug report

**Describe the bug**
I can't get access to Cloud Firestore database for my Web application. It throws me an error [cloud_firestore/permission-denied] Missing or insufficient permissions. I made sure that rules in Firestore are set to public.

I have tried using different channels (beta/stable) with different plugin version from 1.0.0 to 1.0.3 and nothing helped.

### Steps to reproduce

1. Create flutter project for web application.
2. Import required plugins:
```
  firebase_core: "^1.0.2"
  cloud_firestore: "^1.0.3"
  firebase_auth: "^1.0.1"
```
4. Add required scripts to index.html:
```
  <script src="https://www.gstatic.com/firebasejs/8.3.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.3.1/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.3.1/firebase-auth.js"></script>

  <script>
    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    var firebaseConfig = {
      apiKey: "...",
      authDomain:  "...",
      projectId:  "...",
      storageBucket:  "...",
      messagingSenderId:  "...",
      appId: "...",
      measurementId: "..."
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>
```
5. Initializer FlutterFire.
6. Login to the application.
7. Request any data from the firestore.
8. See the error [cloud_firestore/permission-denied] Missing or insufficient permissions.
### Expected behavior

Request returns the data from Firestore for authenticated user.

---

## Additional context

My pubspec.yaml:
```
  name: my_app_name
  description: description
  publish_to: 'none' # Remove this line if you wish to publish to pub.dev
  
  version: 1.0.0+1
  
  environment:
    sdk: '>=2.12.0 <3.0.0'
  
  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.2
    percent_indicator: ^3.3.0-nullsafety.1
    bubble: ^1.2.1
    firebase_core: "^1.0.2"
    cloud_firestore: "^1.0.3"
    firebase_auth: "^1.0.1"
    get_it: ^6.0.0
    provider: ^5.0.0
  
  flutter:
    uses-material-design: true
    assets:
       - assets/

```
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.6 19G2005 darwin-x64, locale en-PL)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] Connected device (1 available)

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.3
my_app_name 1.0.0+1

dependencies:
- bubble 1.2.1 [flutter]
- cloud_firestore 1.0.3 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.2
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- get_it 6.0.0 [async collection]
- percent_indicator 3.3.0-nullsafety.1 [flutter]
- provider 5.0.0 [collection flutter nested]

```

</details>

---

### Firestore rules

Rules set for Firestore in Firebase console:

<details><summary>Click To Expand</summary>

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if
          request.time < timestamp.date(2021, 4, 25);
    }
  }
}

```

</details>

---

### Code

Code to save a data:

<details><summary>Click To Expand</summary>

```

class AddUser extends StatelessWidget {
  final String fullName;
  final String company;
  final int age;

  AddUser(this.fullName, this.company, this.age);

  @override
  Widget build(BuildContext context) {
    // Create a CollectionReference called users that references the firestore collection
    CollectionReference users = FirebaseFirestore.instance.collection('users');

    Future<void> addUser() {
      // Call the user's CollectionReference to add a new user
      return users
          .add({
            'full_name': fullName, 
            'company': company, 
            'age': age // 42
          })
          .then((value) => print("User Added"))
          .catchError((error) => print("Failed to add user: $error"));
    }

    return TextButton(
      onPressed: addUser,
      child: Text(
        "Add User",
      ),
    );
  }
}

```
And for requesting the data data:

<details><summary>Click To Expand</summary>

```
class GetUserName extends StatelessWidget {
  final String documentId;

  GetUserName(this.documentId);

  @override
  Widget build(BuildContext context) {
    CollectionReference users = FirebaseFirestore.instance.collection('users');

    return FutureBuilder<DocumentSnapshot>(
      future: users.doc(documentId).get(),
      builder:
          (BuildContext context, AsyncSnapshot<DocumentSnapshot> snapshot) {

        if (snapshot.hasError) {
          return Text("Something went wrong");
        }

        if (snapshot.connectionState == ConnectionState.done) {
          Map<String, dynamic> data = snapshot.data.data();
          return Text("Full Name: ${data['full_name']} ${data['last_name']}");
        }

        return Text("loading");
      },
    );
  }
}

```

**Comment by MeAtPros** [comment]
I got the same issue. Any help? I need quick solution for my app.

**Comment by brandonhub** [comment]
Can you paste your security rules?

**Comment by Bartozo** [comment]
> Can you paste your security rules?

Please read the whole ticket and check Firestore rules section.

**Comment by markusaksli-nc** [comment]
Hi @Bartozo 
Does the issue persist if you use the officially recommended JS SDK version?
https://firebase.flutter.dev/docs/firestore/overview#3-web-only-add-the-sdk
Do the requests go through on other platforms?
Thank you

**Comment by Ehesp** [comment]
You can also quickly check whether this is a security issue or not by modifying your index.html file to call the document/collection:

```
	  <script src="https://www.gstatic.com/firebasejs/8.3.1/firebase-app.js"></script>
	  <script src="https://www.gstatic.com/firebasejs/8.3.1/firebase-firestore.js"></script>
	  <script src="https://www.gstatic.com/firebasejs/8.3.1/firebase-auth.js"></script>
	  
	  <script>
	  // Your web app's Firebase configuration
	  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
	  var firebaseConfig = {
	    apiKey: "...",
	    authDomain:  "...",
	    projectId:  "...",
	    storageBucket:  "...",
	    messagingSenderId:  "...",
	    appId: "...",
	    measurementId: "..."
	  };
	  // Initialize Firebase
	  firebase.initializeApp(firebaseConfig);


      // Check JS SDK can connect
      firebase.firestore().collection('foo').doc('bar').get().then(console.log).catch(console.log)
	  </script>
```

**Comment by oldpilgrim** [comment]
@Ehesp you are right, the console log shows that it is a security issue and not flutterfire.

```
FirebaseError: Missing or insufficient permissions.
    at new oi (https://www.gstatic.com/firebasejs/8.3.1/firebase-firestore.js:1:52322)
    at https://www.gstatic.com/firebasejs/8.3.1/firebase-firestore.js:1:194599
    at Ll.onMessage (https://www.gstatic.com/firebasejs/8.3.1/firebase-firestore.js:1:195417)
    at https://www.gstatic.com/firebasejs/8.3.1/firebase-firestore.js:1:193468
    at https://www.gstatic.com/firebasejs/8.3.1/firebase-firestore.js:1:193887
    at https://www.gstatic.com/firebasejs/8.3.1/firebase-firestore.js:1:267815
```

However, I still don't understand what's wrong with my security rules, I've set everything to public...

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write;
    }
  }
}
```

**Comment by oldpilgrim** [comment]
Ok I just figured out the problem, #3095 gave me a hint.

Basically, the problem is I was using auth emulator for web. Once I signed out of the auth emulator, everything is good and there are no errors. So the error was likely due to the auth emulator sending bogus credentials, which somehow messed up the security.

@Bartozo I'm not sure if this solves your problem as you may not be using the auth emulator.

**Comment by Bartozo** [comment]
Sorry for late respond from me. I was testing Firestore with native android project and it also gave me the same error. I was able to fix my problem by doing these steps.

1. Recreate whole project in firebase console. (This helped me to connect to example native android app, just to make sure everything works fine from the firebase side).
2. Import new firebase config to your index.html file
3. Change version of previously added Firebase JS SDK

from:
`<script src="https://www.gstatic.com/firebasejs/8.3.1/firebase-firestore.js"></script>`
to:
`  <script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-firestore.js"></script>`

**Comment by darshankawar** [comment]
Closing this as resolved, based on your comment above.
