### ISSUE TITLE
🐛 [Firebase_Auth] Phone Auth error with recaptcha on Flutter Web

### ISSUE THREAD

**Issue by dopecoder** [FirebaseExtended/flutterfire#5500]
## Bug report

**Phone auth on flutter web doesn't work as intended**
Once the captcha verification is complete, the UI has a circular loading indicator looping forever and also sometimes spits the following error.

```
TypeError: Cannot read property 'style' of null
    at Array.<anonymous> (https://www.gstatic.com/recaptcha/releases/5mNs27FP3uLBP3KBPib88r1g/recaptcha__en.js:371:206)
    at qd.<anonymous> (https://www.gstatic.com/recaptcha/releases/5mNs27FP3uLBP3KBPib88r1g/recaptcha__en.js:368:244)
```
### Steps to reproduce

1. Once the call to signInWithPhoneNumber is called, 
2. The captcha verifier starts and once the captcha is submitted
3. That UI has a circular loading indicator looping forever

### Expected behavior

This  circular loading indicator looping forever needs to close so that the OTP page can be displayed and `.confirm()` can be called.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.1
Flutter SDK 2.0.2
resignal 1.0.0+1

dependencies:
- auto_route 0.6.9 [flutter meta]
- badges 1.2.0 [flutter]
- cloud_firestore 0.16.0+1 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 1.0.2
- dartz 0.9.2
- easy_alert 0.0.8 [flutter]
- feather_icons_flutter 4.7.4 [flutter]
- ferry 0.9.4 [gql rxdart gql_link gql_exec meta collection hive built_value ferry_exec normalize ferry_cache]
- ferry_hive_store 0.3.2 [hive ferry_store rxdart collection]
- firebase_analytics 7.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.20.1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_messaging 8.0.0-dev.15 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.1.3 [flutter bloc provider]
- flutter_hooks 0.15.0 [flutter]
- flutter_slidable 0.5.7 [flutter]
- flutter_svg 0.19.3 [flutter meta path_drawing vector_math xml]
- fluttertoast 7.1.8 [flutter flutter_web_plugins]
- freezed_annotation 0.12.0 [collection json_annotation meta]
- get_it 5.0.6 [async meta]
- google_nav_bar 4.0.2 [flutter]
- hasura_cache_interceptor 1.0.0-dev.4 [uuid hasura_connect]
- hasura_connect 2.0.1 [async dartz http meta websocket string_validator uuid]
- hive 1.5.0-pre [meta crypto]
- hive_flutter 0.3.1 [flutter hive path_provider path]
- implicitly_animated_reorderable_list 0.3.2 [flutter async meta]
- injectable 1.1.2 [get_it]
- intl 0.16.1 [path]
- json_annotation 3.1.1
- kt_dart 0.8.0 [meta]
- line_icons 1.3.2 [flutter]
- meta 1.3.0
- mockito 4.1.4 [analyzer build code_builder collection dart_style matcher meta source_gen test_api]
- modal_bottom_sheet 1.0.0+1 [flutter]
- provider 4.3.3 [collection flutter nested]
- reorderables 0.3.2 [flutter]
- resignal_gql 0.0.0 [path ferry gql_http_link hive ferry_hive_store gql_websocket_link web_socket_channel]
- responsive_screen 1.0.0 [flutter]
- rxdart 0.25.0
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shared_preferences_cache_interceptor 1.0.0-dev.3 [shared_preferences hasura_cache_interceptor flutter]
- slide_to_act 2.0.1 [flutter]
- styled_widget 0.2.2 [flutter]
- time 1.4.1
- timeline_tile 1.0.0 [flutter]
- uuid 2.2.2 [crypto convert]
- validators 2.0.1 [vin_decoder]

dev dependencies:
- auto_route_generator 0.6.9 [build source_gen analyzer path build_runner auto_route]
- bloc_test 7.1.0 [bloc test meta mockito]
- build_runner 1.10.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- ferry_generator 0.3.3 [gql gql_build gql_code_builder built_collection code_builder build path ferry_exec]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 0.12.2 [analyzer build build_config meta source_gen freezed_annotation]
- hive_generator 0.8.2 [build source_gen hive analyzer dartx]
- injectable_generator 1.0.5 [build source_gen path glob analyzer injectable collection]
- json_serializable 3.5.1 [analyzer build build_config json_annotation meta path source_gen]
- lint 1.5.3

dependency overrides:
- analyzer 0.41.2 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- hasura_cache_interceptor 1.0.0-dev.4 [uuid hasura_connect]
- hasura_connect 2.0.1 [async dartz http meta websocket string_validator uuid]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- args 1.6.0
- async 2.5.0 [collection]
- basic_utils 2.7.1 [http logging json_annotation pointycastle convert crypto]
- bloc 6.1.3 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 1.3.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.3.11 [analyzer build crypto graphs logging path package_config pub_semver]
- build_runner_core 6.0.1 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- built_value_generator 7.1.0 [analyzer build build_config built_collection built_value source_gen quiver]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0
- cloud_firestore_platform_interface 3.0.2 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- coverage 0.15.2 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- dart_style 1.3.6 [analyzer args path source_span]
- dartx 0.5.0 [collection path crypto characters time meta]
- fake_async 1.2.0 [clock collection]
- ferry_cache 0.4.3 [ferry_exec meta rxdart normalize ferry_store collection]
- ferry_exec 0.0.3 [gql gql_exec gql_link meta collection async]
- ferry_store 0.3.2 [rxdart collection]
- ffi 1.0.0
- file 5.2.1 [intl meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 3.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_messaging_platform_interface 1.0.0-dev.10 [flutter meta firebase_core plugin_platform_interface]
- firebase_messaging_web 0.1.0-dev.6 [flutter flutter_web_plugins meta firebase_core firebase_core_web firebase_messaging_platform_interface js service_worker]
- fixnum 0.10.11
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- gql 0.12.5-alpha+1615272573372 [source_span meta collection]
- gql_build 0.1.4+2 [analyzer gql path glob build gql_code_builder code_builder dart_style built_value built_value_generator built_collection yaml]
- gql_code_builder 0.1.4+1 [analyzer gql code_builder meta built_collection built_value path recase gql_exec]
- gql_exec 0.2.6-alpha+1615272573382 [gql meta collection]
- gql_http_link 0.3.2 [meta gql gql_exec gql_link http http_parser]
- gql_link 0.3.2-alpha+1615272573392 [meta gql gql_exec]
- gql_websocket_link 0.2.1-alpha+1615272573400 [gql gql_exec gql_link meta rxdart uuid_enhanced web_socket_channel]
- graphs 0.2.0
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- io 0.3.5 [meta path string_scanner]
- js 0.6.3
- logging 0.11.4
- matcher 0.12.10 [stack_trace]
- mime 0.9.7
- nested 1.0.0 [flutter]
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- node_preamble 1.4.13
- normalize 0.4.7 [gql meta]
- package_config 1.9.3 [path charcode]
- path 1.8.0
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.28 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.5 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 3.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 2.0.1
- pool 1.5.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.8 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.5 [matcher meta]
- random_string 2.1.0
- recase 3.0.1
- service_worker 0.2.4 [js]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.1 [path shelf shelf_static]
- shelf_static 0.2.9+2 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0 [charcode source_span]
- string_validator 0.1.4
- term_glyph 1.2.0
- test 1.16.5 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.15 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0 [collection]
- uuid_enhanced 3.0.2 [crypto convert collection]
- vector_math 2.1.0
- vin_decoder 0.1.3 [meta basic_utils http random_string]
- vm_service 6.1.0+1
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- webkit_inspection_protocol 0.7.5 [logging]
- websocket 0.0.5
- win32 2.0.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @dopecoder 
Does this behavior persist if you use the latest version of the package `firebase_auth: ^1.0.1`?
Could you provide your `index.html` (without the sensitive info)?
Thank you
