### ISSUE TITLE
getting FATAL EXCEPTION: FirebaseMLHandler

### ISSUE THREAD

**Issue by wahyu-handayani** [FirebaseExtended/flutterfire#5509]
I am using firebase_ml_vision package and I run it in debug mode and it works well, but after apps being uploaded to play store I get an error, here is the log
```
FATAL EXCEPTION: FirebaseMLHandler
E/AndroidRuntime(24669): Process: com.myapp.okeapp, PID: 24669
E/AndroidRuntime(24669): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/base.apk", zip file "/data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/split_config.armeabi_v7a.apk", zip file "/data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/split_config.en.apk", zip file "/data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/split_config.in.apk", zip file "/data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/split_config.ms.apk", zip file "/data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/lib/arm, /data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/base.apk!/lib/armeabi-v7a, /data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/split_config.en.apk!/lib/armeabi-v7a, /data/app/com.myapp.okeappm-d6ybbg5_noEkgkSlVrKIkg==/split_config.in.apk!/lib/armeabi-v7a, /data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/split_config.ms.apk!/lib/armeabi-v7a, /data/app/com.myapp.okeapp-d6ybbg5_noEkgkSlVrKIkg==/split_config.xhdpi.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]] couldn't find "libface_detector_v2_jni.so"
E/AndroidRuntime(24669): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/AndroidRuntime(24669): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime(24669): 	at java.lang.System.loadLibrary(System.java:1667)
E/AndroidRuntime(24669): 	at com.google.android.gms.vision.EngineManager.zza(Unknown Source:3)
E/AndroidRuntime(24669): 	at com.google.android.gms.vision.face.ChimeraNativeBaseFaceDetectorCreator.newFaceDetector(Unknown Source:21)
E/AndroidRuntime(24669): 	at com.google.android.gms.vision.face.internal.client.c.a(Unknown Source:31)
E/AndroidRuntime(24669): 	at c.b.a.a.g.k.y7.d(Unknown Source:55)
E/AndroidRuntime(24669): 	at com.google.android.gms.vision.face.internal.client.c.<init>(Unknown Source:9)
E/AndroidRuntime(24669): 	at com.google.android.gms.vision.face.c$a.a(Unknown Source:39)
E/AndroidRuntime(24669): 	at c.b.a.a.g.f.ha.c(Unknown Source:209)
E/AndroidRuntime(24669): 	at c.b.a.a.g.f.n9.c(Unknown Source:9)
E/AndroidRuntime(24669): 	at c.b.a.a.g.f.p9.a(Unknown Source:74)
E/AndroidRuntime(24669): 	at c.b.a.a.g.f.p9.call(Unknown Source:0)
E/AndroidRuntime(24669): 	at c.b.a.a.g.f.c9.a(Unknown Source:0)
E/AndroidRuntime(24669): 	at c.b.a.a.g.f.e9.run(Unknown Source:4)
E/AndroidRuntime(24669): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(24669): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(24669): 	at c.b.a.a.g.f.p.dispatchMessage(Unknown Source:0)
E/AndroidRuntime(24669): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(24669): 	at android.os.HandlerThread.run(HandlerThread.java:67)

```
is there a way to handle it

**Comment by markusaksli-nc** [comment]
Hi @wahyu-handayani 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by wahyu-handayani** [comment]
@markusaksli-nc I am so sorry for taking a long time to reply, this case have already solved. I have a backup repo project in my github, so I solve it by removing my android folder and change it with android folder from my backup repo. Thank you for your response and I am so sorry to reply it very late

**Comment by darshankawar** [comment]
Closing this as resolved based on your comment above.
