### ISSUE TITLE
🐛 [firebase_crashlytics] Firebase Crashlytics crashes on Android 11 while initializing `okhttp` client.

### ISSUE THREAD

**Issue by Hasilt** [FirebaseExtended/flutterfire#5511]
## Bug report

**Describe the bug**
I'm using legacy version of `firebase_crashlytics` (v 0.4.0+1 - the one before nullsafety). Users getting `Fatal Exception: java.lang.ExceptionInInitializerError` after installing the app from play store (users are seeing that the app crashed/ the app is keep stopping error on their phone). And, the issue is only observed in devices running with android 11 (I checked the crashlytics web portal - 100% crash reports are coming from android 11). 

Further going through stack trace I found out that the error is coming from `okhttp` android library. Then, I checked `okhttp` library and found that there was an issue and it is already fixed in `okhttp` version 3.14.7 [changelogs](https://square.github.io/okhttp/changelog_3x/#version-3147).

I'm not well versed with android native, so I couldn't find what version of `okhttp` is used by the crashlytics plugin. A simple version bump would fix this issue, or is there any other workarounds available? 

#### Update on 31st March 2021
There are crashes still reporting even after updating to latest version of `firebase_core` (1.0.2)

## Crashlytics Stack trace

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:207)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:5)
       at com.google.firebase.crashlytics.internal.network.HttpRequest.<clinit>(HttpRequest.java:2)
       at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java)
       at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.a(AbstractSpiCall.java:8)
       at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.a(DefaultSettingsSpiCall.java:6)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.a(SettingsController.java:13)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.a(SettingsController.java:2)
       at com.google.android.gms.tasks.zzp.run(zzp.java:12)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:2)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:5)
       at java.lang.Thread.run(Thread.java:923)
```

```
Caused by java.lang.IllegalStateException: Expected Android API level 21+ but was 30
       at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.java:117)
       at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.java:2)
       at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.java)
       at okhttp3.internal.platform.Platform.<clinit>(Platform.java:10)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:207)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:5)
       at com.google.firebase.crashlytics.internal.network.HttpRequest.<clinit>(HttpRequest.java:2)
       at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java)
       at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.a(AbstractSpiCall.java:8)
       at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.a(DefaultSettingsSpiCall.java:6)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.a(SettingsController.java:13)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.a(SettingsController.java:2)
       at com.google.android.gms.tasks.zzp.run(zzp.java:12)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:2)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:5)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by russellwheatley** [comment]
Hey @Hasilt, there isn't a lot we can do about this issue if it's a bug from the native SDKs. This library is only a thin wrapper. On top of that, if the user doesn't update the app, the bug will continue to persist. The only thing I can recommend is to use the latest package versions, and to try some method of [prompting the user to update the app](https://stackoverflow.com/questions/19244305/force-update-of-an-android-app-when-a-new-version-is-available).
