### ISSUE TITLE
CocoaPods could not find compatible versions for pod "Firebase/Database" and also CocoaPods could not find compatible versions for pod "FirebaseCore":

### ISSUE THREAD

**Issue by dfields186** [FirebaseExtended/flutterfire#5538]
I've run into this issue and tried all the various recommended "cleaning" and re-installing solutions but nothing seems to work to resolve these errors and this is preventing compiling the code on any and all iOS platforms.  The full error message below:
```
[!] CocoaPods could not find compatible versions for pod "Firebase/Database":
                 In Podfile:
                   firebase_database (from `.symlinks/plugins/firebase_database/ios`) was resolved to 6.0.0, which depends on
                     Firebase/Database (= 7.3.0)
           
                   flutter_geofire (from `.symlinks/plugins/flutter_geofire/ios`) was resolved to 0.0.1, which depends on
                     GeoFire (~> 4.0) was resolved to 4.1.0, which depends on
                       Firebase/Database (~> 6.0)
           
               CocoaPods could not find compatible versions for pod "FirebaseCore":
                 In Podfile:
                   firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.7.0, which depends on
                     Firebase/CoreOnly (= 7.3.0) was resolved to 7.3.0, which depends on
                       FirebaseCore (= 7.3.0)
           
                   firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 8.0.0-dev.15, which depends on
                     Firebase/Messaging (= 7.3.0) was resolved to 7.3.0, which depends on
                       FirebaseMessaging (~> 7.3.0) was resolved to 7.3.0, which depends on
                         FirebaseCore (~> 7.0)


[  +91 ms] Error output from CocoaPods:
           ↳
[   +1 ms] 
               [!] Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your
Podfile. See
               `https://guides.cocoapods.org/syntax/podfile.html#platform`.
           
[  +10 ms] Error running pod install
[   +5 ms] Error launching application on iPhone 8 Plus.
[+9838 ms] "flutter run" took 27,783ms.
[   +8 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:12:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:659:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1037:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[ +116 ms] ensureAnalyticsSent: 114ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +4 ms] Shutdown hooks complete
[        ] exiting with code 1
```

[flutter-run-v-output.txt](https://github.com/FirebaseExtended/flutterfire/files/6238398/flutter-run-v-output.txt)

**Comment by markusaksli-nc** [comment]
Hi @dfields186 
You are running into this because you are using a mismatch of different packages with incompatible version constraints. For example you are using the old core version but the previous messaging dev version. These are incompatible because of an updated minimum iOS deployment target.
Please use the latest versions of all of the firebase packages and the conflicts should be resolved.
Thank you
