### ISSUE TITLE
🐛 [Crashlytics] iOS build crashes when adding crashlytics

### ISSUE THREAD

**Issue by KSLiquid** [FirebaseExtended/flutterfire#5660]
## Bug report

**Describe the bug**
I migrated my existing app to null safety, including Crashlytics 1.0.0.
It worked fine on Android, but on iOS I cannot build any longer.

Even when creating a new flutter app from scratch I still have the same problem.

The error:
```
In file included from
    /Users/benjaminweber/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-1.0.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.
    m:5:
    /Users/benjaminweber/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-1.0.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.
    h:8:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    While building module 'firebase_core' imported from
    /Users/benjaminweber/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-1.0.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.
    h:12:
    In file included from <module-includes>:1:
    In file included from /Users/benjaminweber/source/Booksharing/app/booksharing/ios/Pods/Target Support
    Files/firebase_core/firebase_core-umbrella.h:13:
    /Users/benjaminweber/development/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.2/ios/Classes/FLTFirebaseCorePlugin.h:8:9: fatal
    error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    2 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro.
```

### Steps to reproduce

1. Create a new flutter app with flutter create
2.  In Podfile: uncomment and change platform :ios, '9.0' to 10.0 
3. Add the dependencies to pubspec.yaml:
```
firebase_core: ^1.0.2
firebase_crashlytics: ^1.0.0
```
4. Follow the instructions under https://firebase.flutter.dev/docs/crashlytics/overview/ to setup iOS
5. flutter run

### Expected behavior

I expected the app to run.
---

## Additional context

I've searched for hours and tried everything I found on the internet, e.g.

Flutter clean
Flutter pub get
Flutter pub upgrade

Rm -r -f pods
rm -r -f runner.xcodeproj/project.xcworkspace
Rm podfile.lock

rm -rf ~/Library/Developer/Xcode/DerivedData/
rm -rf ~/Library/Caches/CocoaPods/
rm -rf ~/Applications/flutter/.pub-cache/
pod cache clean --all
pod deintegrate

Pod update
pod install --repo-update
flutter run

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/benjaminweber/development/flutter
    • Framework revision b1395592de (2 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] Connected device (3 available)
    • MyRealiPhone (mobile)  • 379b967bb17aa779d9db993cf9a4e935e416fb28 • ios            • iOS 14.4.2
    • iPhone 12 Pro (mobile) • 83807CDC-4D07-454C-9160-28FB046212AA     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- cupertino_icons 1.0.2
- firebase_core 1.0.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 1.0.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 2.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0```

</details>

---

Edit: Added modification in podfile as step to reproduce

**Comment by KSLiquid** [comment]
I just figured out that it works with the flutter dev-channel. When I switch back to stable, it is broken again.

**Comment by isorensen** [comment]
+1 for me. It seems that many `'Flutter/Flutter.h' file not found` are happening with latest version of Flutter. And in my case, only `firebase_crashlytics` is throwing this error. Below is my `flutter doctor -v` in case it helps:

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale en-BR)
    • Flutter version 2.0.4 at /Users/eduardosorensen/developer/flutter
    • Framework revision b1395592de (3 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eduardosorensen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iSorensen (mobile) • 55f8acd1b63b1bd15ae4ad33c35e59babe82368c • ios            • iOS 14.4.2
    • macOS (desktop)    • macos                                    • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                                   • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by isorensen** [comment]
Worth to mention that in Flutter 2.0.2 is building successfully. Just downgraded to it, and it built.

```
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-x64, locale en-BR)
    • Flutter version 2.0.2 at /Users/eduardosorensen/developer/flutter
    • Framework revision 8962f6dc68 (3 weeks ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/eduardosorensen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iSorensen (mobile) • 55f8acd1b63b1bd15ae4ad33c35e59babe82368c • ios            • iOS 14.4.2
    • macOS (desktop)    • macos                                    • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)       • chrome                                   • web-javascript • Google Chrome 89.0.4389.114

• No issues found!
```

**Comment by isorensen** [comment]
https://github.com/flutter/flutter/issues/70895 is probably related.

**Comment by MichalDanielDobrzanski** [comment]
@isorensen I don't think so. It is old and contains custom, not working solutions. This is the real problem: [https://github.com/flutter/flutter/issues/79575](https://github.com/flutter/flutter/issues/79575)

**Comment by kuromukira** [comment]
Any workaround for this?

**Comment by KSLiquid** [comment]
I can confirm that flutter 2.0.2 works

**Comment by veresvit** [comment]
@kuromukira
Workaround for Flutter 2.0.4 is to use firebase_crashlytics from git instead of pub.dev. This seems to work (ref to the currently latest commit):
```
  firebase_crashlytics:
    git:
      url: git://github.com/FirebaseExtended/flutterfire.git
      path: packages/firebase_crashlytics/firebase_crashlytics
      ref: 200b8ca8f1c452e4249fb791e53cc55e786ac768
```

**Comment by MichalDanielDobrzanski** [comment]
Another workaround which I have found and it worked is this: 
https://stackoverflow.com/a/66943848/4150337

**Comment by darshankawar** [comment]
I am able to replicate the error on latest stable (2.0.4):

<details>
<summary>console log</summary>

```
Running pod install...                                              3.3s
Running Xcode build...                                                  
Xcode build done.                                            9.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from /Users/dhs/documents/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-1.0.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.m:5:
    /Users/dhs/documents/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-1.0.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.h:8:9: fatal error: 'Flutter/Flutter.h' file
    not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    While building module 'firebase_core' imported from
    /Users/dhs/documents/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-1.0.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.h:12:
    In file included from <module-includes>:1:
    In file included from /Users/dhs/Documents/NCFlutter/cl_bug/ios/Pods/Target Support Files/firebase_core/firebase_core-umbrella.h:13:
    /Users/dhs/documents/fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.0.2/ios/Classes/FLTFirebaseCorePlugin.h:8:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    2 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'Flutter' from
    project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.
dhs@Dhss-MacBook-Pro cl_bug % 

```

</details>

Although not straightaway after following the steps to replicate mentioned above. Initially, I received below error:

```
[   +2 ms] Error output from CocoaPods:
           ↳
[   +1 ms] 
               [!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile.
See
               `https://guides.cocoapods.org/syntax/podfile.html#platform`.
           
[   +5 ms] Error running pod install
[   +1 ms] Error launching application on iPhone 12 Pro Max.
[+2236 ms] "flutter run" took 10,922ms.
[   +4 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
           
           
[ +131 ms] ensureAnalyticsSent: 83ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[   +6 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
dhs@Dhss-MacBook-Pro cl_bug % 
```

So when I uncommented and changed `platform :ios, '9.0'` to `10.0` and ran `flutter run`, I got the same error as mentioned.

Also, not replicable on Stable 2.0.3 wherein, the same steps compiled and launched the newly created app properly:

```
Running pod install...                                              9.7s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        10.1s
Xcode build done.                                           35.9s
Syncing files to device iPhone 12 Pro Max...                        64ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:53361/By_XTKZNrBo=/
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64, locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (4 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin
        usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by KSLiquid** [comment]
> I am able to replicate the error on latest stable (2.0.4):
> 
> console log
> Although not straightaway after following the steps to replicate mentioned above. Initially, I received below error:
> 
> ```
> [   +2 ms] Error output from CocoaPods:
>            ↳
> [   +1 ms] 
>                [!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile.
> See
>                `https://guides.cocoapods.org/syntax/podfile.html#platform`.
>            
> [   +5 ms] Error running pod install
> [   +1 ms] Error launching application on iPhone 12 Pro Max.
> [+2236 ms] "flutter run" took 10,922ms.
> [   +4 ms] 
>            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
>            #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:644:9)
>            <asynchronous suspension>
>            #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
>            <asynchronous suspension>
>            #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
>            <asynchronous suspension>
>            #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
>            <asynchronous suspension>
>            #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
>            <asynchronous suspension>
>            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
>            <asynchronous suspension>
>            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
>            <asynchronous suspension>
>            #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
>            <asynchronous suspension>
>            #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
>            <asynchronous suspension>
>            #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
>            <asynchronous suspension>
>            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
>            <asynchronous suspension>
>            #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
>            <asynchronous suspension>
>            #16     main (package:flutter_tools/executable.dart:90:3)
>            <asynchronous suspension>
>            
>            
> [ +131 ms] ensureAnalyticsSent: 83ms
> [   +2 ms] Running shutdown hooks
> [        ] Shutdown hook priority 4
> [   +6 ms] Shutdown hooks complete
> [   +1 ms] exiting with code 1
> dhs@Dhss-MacBook-Pro cl_bug % 
> ```
> 
> So when I uncommented and changed `platform :ios, '9.0'` to `10.0` and ran `flutter run`, I got the same error as mentioned.
> 
> Also, not replicable on Stable 2.0.3 wherein, the same steps compiled and launched the newly created app properly:
> 
> ```
> Running pod install...                                              9.7s
> Running Xcode build...                                                  
>  └─Compiling, linking and signing...                        10.1s
> Xcode build done.                                           35.9s
> Syncing files to device iPhone 12 Pro Max...                        64ms
> 
> Flutter run key commands.
> r Hot reload. 🔥🔥🔥
> R Hot restart.
> h Repeat this help message.
> d Detach (terminate "flutter run" but leave application running).
> c Clear the screen
> q Quit (terminate the application on the device).
> An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:53361/By_XTKZNrBo=/
> ```
> 
> flutter doctor -v

Sorry! I had to make this step as well, but failed to mention it in "steps to reproduce". Added it now.

**Comment by wujek-srujek** [comment]
I have the same issue after updating to Flutter 2.0.4. I'm using fvm and so was able to test with multiple Flutter versions and 2.0.4 always fails, and 2.0.3, 2.0.2, 2.0.1 and 2.0.0 always work.

**Comment by edgarfroes** [comment]
The weird thing is that I didn't got this error with my project. It was migrated from 1.x to 2.0.4, and it compiled succesfully. Only in my new project, already created in 2.0.X, this bug occurs.

**Comment by wujek-srujek** [comment]
There is a new version of firebase_crashlytics, 2.0.0, where they fixed a bug about a failing dependency on the Flutter framework. When you update building with 2.0.4 works fine.

**Comment by Salakar** [comment]
As above, the latest version should now be working.

**Comment by cymel600** [comment]
Hi, I solve this issue using new versión of Crashlytics Null Safety. 
firebase_core: "^1.0.3"
firebase_crashlytics: "^2.0.0"

https://firebase.flutter.dev/docs/crashlytics/overview/

I used Flutter 2.1.0-13.0.pre.451 • channel master • https://github.com/flutter/flutter.git

**Comment by Benjamin-Frost** [comment]
Thanks a lot for this answer. I was stuck on this for a while and finally was able to figure this out thanks to you @kuromukira.

> @kuromukira
> Workaround for Flutter 2.0.4 is to use firebase_crashlytics from git instead of pub.dev. This seems to work (ref to the currently latest commit):
> 
> ```
>   firebase_crashlytics:
>     git:
>       url: git://github.com/FirebaseExtended/flutterfire.git
>       path: packages/firebase_crashlytics/firebase_crashlytics
>       ref: 200b8ca8f1c452e4249fb791e53cc55e786ac768
> ```

Also note: As of now the problem that was causing this behavior has been fixed and is published on pub.dev. There is no longer a need to use the workaround in the pubspec.lock file. Just use:

```
firebase_crashlytics: ^2.0.0
```

in your pubspec.yaml 👍
