### ISSUE TITLE
🐛 [FIREBASE_AUTH] Exception has occurred. "Error: unsupported_event

### ISSUE THREAD

**Issue by samuk190** [FirebaseExtended/flutterfire#5662]
## Bug report

**Describe the bug**
when I run this or authStateChanges I get this error on flutter web if I enable "get all exceptions on vscode"

    FirebaseAuth.instance.userChanges().listen((User? user) {
      if (user == null) {
        userf = null;
      } else {
        userf = user;
      }
    });
    print("Gettei user $userf");
    return userf;
    
    
    I can get same error by running     await FirebaseAuth.instance.authStateChanges().first;

Strange but even after setting persistence to local, FirebaseAuth instance only returns null.
I'm using null safety and latest version 8.3.2
    
### Steps to reproduce

2. '...'
4. See error or incorrect behavior

Exception has occurred.
"Error: unsupported_event
    at https://www.gstatic.com/firebasejs/8.3.2/firebase-auth.js:1:104874"
```



### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [versÃ£o 10.0.19042.867], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.54.3)
[√] Connected device (2 available)</summary>

```
Exception has occurred.
"Error: unsupported_event
    at https://www.gstatic.com/firebasejs/8.3.2/firebase-auth.js:1:104874"
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```

</details>

---

**Comment by darshankawar** [comment]
> if I enable "get all exceptions on vscode"

@samuk190 If you disable it, does the same exception occurs or not ?

If you run your code normally (ie, without making any setting changes on vscode), does it work properly ?

Also, to properly address this, can you provide a minimal complete reproducible code sample and `flutter pub deps -- --style=compact` that we can directly use ?

**Comment by samuk190** [comment]
> 
> 
> > if I enable "get all exceptions on vscode"
> 
> @samuk190 If you disable it, does the same exception occurs or not ?
> 
> If you run your code normally (ie, without making any setting changes on vscode), does it work properly ?
> 
> Also, to properly address this, can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and `flutter pub deps -- --style=compact` that we can directly use ?

Hello, Yes if I run normally without catching exceptions it doesnt crash or shows that error. So it seems at the start of the application firebase method is being called before finish initialization causing that exception. 
(Maybe its missing an Future inside firebase_auth package to wait core initializate??)
It is something that can  bother alot if I want to see if something is broke in my code and it shows that firebase error instead.
 
```


Dart SDK 2.12.2
Flutter SDK 2.0.3
login_flutter_mobx_updated 1.0.0+1

dependencies:
- cupertino_icons 1.0.2
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]       
- flutter_mobx 2.0.0 [flutter mobx]
- flutter_modular 3.0.2+1 [flutter_modular_annotations triple flutter]
- google_sign_in 5.0.1 [google_sign_in_platform_interface google_sign_in_web flutter 
meta]
- mobx 2.0.1 [meta]

dev dependencies:
- build_runner 1.12.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_modular_test 1.0.1 [flutter_modular flutter]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math 
async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- mobx_codegen 2.0.1+2 [analyzer build build_resolvers meta mobx path source_gen]    

transitive dependencies:
- _fe_analyzer_shared 19.0.0 [meta]
- analyzer 1.3.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- args 2.0.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.0 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.7 [checked_yaml json_annotation meta path pubspec_parse yaml]     
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]      
- build_resolvers 2.0.0 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform]
- build_runner_core 6.1.12 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.0 [analyzer args path pub_semver source_span]
- dartz 0.10.0-nullsafety.1
- fake_async 1.2.0 [clock collection]
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]    
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_modular_annotations 0.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 1.0.0
- http_multi_server 3.0.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]      
- intl 0.17.0 [clock path]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- package_config 2.0.0 [path]
- path 1.8.0
- pedantic 1.11.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]      
- quiver 3.0.0 [matcher]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- triple 1.0.1 [meta async dartz]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.0.0 [async crypto stream_channel]
- yaml 3.1.0 [collection source_span string_scanner]
```

**Comment by darshankawar** [comment]
@samuk190 
Check [this](https://github.com/FirebaseExtended/flutterfire/issues/4348) issue and confirm if it resemble / similar to yours.

**Comment by samuk190** [comment]
> 
> 
> @samuk190
> Check [this](https://github.com/FirebaseExtended/flutterfire/issues/4348) issue and confirm if it resemble / similar to yours.

I think its related (collateral) but in my case I set persistence.Local so I don't have that issue where "authStateChanges().listen sometimes not triggered when signed in or out." 
I think fixing this bug will fix both issues.

**Comment by nelsondani** [comment]
[1237]()

**Comment by darshankawar** [comment]
@samuk190 
Can you provide a complete minimal reproducible code sample that shows this exception and we can directly use to verify this issue ?
