### ISSUE TITLE
🐛 [firebase_auth] [web]: SignInWithPhoneNumber throws `Unexpected null value` error

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [FirebaseExtended/flutterfire#5666]
## Bug report

The process of registering a user with a phone number on the web doesn't work.

### Steps to reproduce

1. Create a flutter project
2. Add firebase app
3. Follow steps of adding phone number auth on web
4. When you try to register a user, it does not work

I use this code:

```dart
Future<ConfirmationResult> sendVerificationCodeWeb({
    @required String phoneNumber,
  }) async {
    ConfirmationResult confirmationResult =
        await _firebaseAuth.signInWithPhoneNumber(phoneNumber);

    return confirmationResult;
  }

  Future<void> verifyPhoneNumberWeb({
    @required ConfirmationResult confirmationResult,
    @required String verificationCode,
    @required String phoneNumber,
    String firstName,
    String lastName,
    String sNumber,
  }) async {
    await confirmationResult.confirm(
      verificationCode,
    );

    if (firstName != null && lastName != null && sNumber != null) {
      await _registerUserInDb(
        firstName: firstName,
        lastName: lastName,
        phoneNumber: phoneNumber,
        sNumber: sNumber,
      );
    } else {
      await populateCurrentUser();
    }
  }
```

What gets printed in the console:

```bash
TypeError: Cannot read property 'style' of null
    at Array.<anonymous> (https://www.gstatic.com/recaptcha/releases/bfvuz6tShG5aoZp4K4zPVf5t/recaptcha__en.js:358:34)
    at Hd.<anonymous> (https://www.gstatic.com/recaptcha/releases/bfvuz6tShG5aoZp4K4zPVf5t/recaptcha__en.js:132:36)
NoSuchMethodError: invalid member on null: '_get'
```

### Expected behavior

The user should be registered and good to go.

---

## Additional context

I found this when trying to dig in the source code
![image](https://user-images.githubusercontent.com/41989385/113590747-af1bbe80-963b-11eb-97e5-e446f9266080.png)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PS C:\Users\yazee> flutter doctor -v
[✓] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.3 at Y:\extra\flutter
    • Framework revision 4d7946a68d (3 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\yazee\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\yazee\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30907.101
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] IntelliJ IDEA Community Edition (version 2020.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.6912

[✓] VS Code, 64-bit edition (version 1.54.3)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 89.0.774.68

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PS c:\PATH_TO_PROJECT\arrowad_grade_eleven> flutter pub deps -- --style=compact
Dart SDK 2.12.2
Flutter SDK 2.0.3
arrowad_grade_eleven 0.0.1+1

dependencies:
- auto_route 1.0.2 [flutter path collection]
- cloud_firestore 1.0.3 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- flash 1.5.1 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- get_it 6.0.0 [async collection]
- injectable 1.2.2 [get_it]
- stacked 2.0.2 [flutter get_it meta provider collection]

dev dependencies:
- auto_route_generator 1.0.2 [build source_gen analyzer path build_runner code_builder dart_style auto_route]
- build_runner 1.12.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel 
yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- injectable_generator 1.2.2 [build source_gen path glob analyzer code_builder dart_style injectable collection]

transitive dependencies:
- _fe_analyzer_shared 19.0.0 [meta]
- analyzer 1.3.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- args 1.6.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.0 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.7 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.0 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform]
- build_runner_core 6.1.12 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.3 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.0 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 1.0.0
- http_multi_server 2.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- io 0.3.5 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- package_config 2.0.0 [path]
- path 1.8.0
- pedantic 1.11.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- provider 5.0.0 [collection flutter nested]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
I was able to replicate this using latest stable.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.0.4 at /Users/dhs/documents/fluttersdk/flutter
    • Framework revision b1395592de (4 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • Mac OS X 10.15.4 19E2269
      darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.114

! Doctor found issues in 1 category.

```

</details>

**Comment by YazeedAlKhalaf** [comment]
Any plans to solve this issue? The docs state web is supported in phone auth but seems not 🙈

**Comment by YazeedAlKhalaf** [comment]
Hey all, update time;

**Web progress**:

 1. 🟢 `Core` Web
	   **Status**: complete, shipped 🚢 .
 2. 🟢 `Cloud Firestore` Web
       **Status**: complete, shipped 🚢 .
	- This added in the follow new feature changes;
      - `FirebaseFirestore.enablePersistence` now accepts `PersistenceSettings`
      - support for `PersistenceSettings`
      - support for `FirebaseFirestore.clearPersistence`
      - support for `FirebaseFirestore.terminate`
      - support for `FirebaseFirestore.waitForPendingWrites`
      - support for `SetOptions.mergeFields`
      - `GetOptions` support for querying against server/cache
      - support for `Query.limitToLast`
      - support for `FirebaseFirestore.snapshotsInSync`
 3. 🟢 `Authentication` Web
       **Status**: complete, shipped 🚢 .
	- This added in the follow new feature changes;
      - support for `EmailAuthProvider.credentialWithLink`
      - support for `FirebaseAuth.setSettings`
      - support for `User.tenantId`
      - `FirebaseAuthException` now supports `email` & `credential` properties
      - `ActionCodeInfo` now supports `previousEmail` field
 5. 🟢 `Cloud Storage` Web
       **Status**: complete, shipped 🚢 .
	- Cloud Storage did not support Web previously, so this is a new platform being supported.
 6. 🟢 `Cloud Functions` Web
       **Status**: complete, shipped 🚢 .
 7. 🟡 `Cloud Messaging (FCM)` Web
       **Status**: complete, pending review & additional testing (dev release soon).

-----

## What's next?

Null safety support for all the above packages. More on this soon.

_Originally posted by @Salakar in https://github.com/FirebaseExtended/flutterfire/issues/2582#issuecomment-734318141_

@Salakar The authentication in web with phone number doesn't work, not implemented

**Comment by darshankawar** [comment]
> Any plans to solve this issue? The docs state web is supported in phone auth but seems not 🙈

@YazeedAlKhalaf Please see my repro comment. I was able to sign in properly but then get the `null value` error.

**Comment by Ehesp** [comment]
Will get this looked into. Can you confirm which version of the Firebase JS SDK you are using please?

**Comment by Ehesp** [comment]
Also, worth noting 

```
TypeError: Cannot read property 'style' of null
    at Array.<anonymous> (https://www.gstatic.com/recaptcha/releases/bfvuz6tShG5aoZp4K4zPVf5t/recaptcha__en.js:358:34)
    at Hd.<anonymous> (https://www.gstatic.com/recaptcha/releases/bfvuz6tShG5aoZp4K4zPVf5t/recaptcha__en.js:132:36)
NoSuchMethodError: invalid member on null: '_get'
```

This is unrelated to FlutterFire (I think). I can't imagine it'll have any impact on the actual issue here.

**Comment by russellwheatley** [comment]
`confirm()` has already been implemented on auth web, I've updated the auth example so people know how to use it [here](https://github.com/FirebaseExtended/flutterfire/pull/6476).
