### ISSUE TITLE
The following NoSuchMethodError was thrown building Builder: The getter 'uid' was called on null. Receiver: null Tried calling: uid

### ISSUE THREAD

**Issue by eshun4** [FirebaseExtended/flutterfire#5679]
```
import 'dart:async';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:rideboard/models/user.dart';
import 'package:rideboard/services/Navigation%20Settings/User%20Navigation%20Settings/route_generator.dart';
import 'package:rideboard/services/appData.dart';
import 'package:rideboard/ui/Screens/User%20Screens/Login_Screen.dart';
import 'package:rideboard/ui/components/Configmaps.dart';
import 'ui/components/constants.dart';
import 'package:provider/provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  currentfirebaseUser = await FirebaseAuth.instance.currentUser;
  runApp(Rideboard());
}

String _fdbUrl1 = "database url";
DatabaseReference usersRef =
    FirebaseDatabase(databaseURL: _fdbUrl1).reference().child("Users");
String _fdbUrl2 = "database url";
DatabaseReference driversRef =
    FirebaseDatabase(databaseURL: _fdbUrl2).reference().child("Drivers");
DatabaseReference newRequestsRef =
    FirebaseDatabase.instance.reference().child("Ride Requests");

DatabaseReference rideRequestsRef =
    driversRef.child(currentfirebaseUser.uid).child('newRide');

class Rideboard extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (context) => AppData(),
      child: MaterialApp(
        initialRoute: (currentfirebaseUser == null) ? '/Login' : "/Rider",
        onGenerateRoute: RouteGenerator.generateRoute,
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          scaffoldBackgroundColor: kthemeColor.withOpacity(0.2),
          textTheme: ktextTheme,
        ),
      ),
    );
  }
}

class LoadingScreen extends StatefulWidget {
  @override
  _LoadingScreenState createState() => _LoadingScreenState();
}

class _LoadingScreenState extends State<LoadingScreen> {
  //Initializes the Timer
  @override
  void initState() {
    super.initState();

    Timer(
      Duration(seconds: 10),
      () => Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => LoginScreen(),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Stack(
      fit: StackFit.expand,
      children: [
        Container(
          decoration: BoxDecoration(
            image: DecorationImage(
                image: AssetImage(
                  'assets/PATTERN3.png',
                ),
                fit: BoxFit.cover),
          ),
        ),
        Column(
          mainAxisAlignment: MainAxisAlignment.spaceAround,
          children: [
            SizedBox(height: 20),
            Image.asset(
              'assets/logo.png',
              scale: 4.5,
            ),
            Text('Hitch a ride Asap!', style: kSplashScreen),
            SizedBox(height: 30),
            SpinKitWave(
              itemBuilder: (context, index) {
                return DecoratedBox(
                  decoration: BoxDecoration(
                    color: index.isEven ? Color(0xFF0A1768) : Colors.blue,
                  ),
                );
              },
            ),
            SizedBox(
              height: 30,
            ),
            Text('By Kofi Junior Eshun', style: kMyName)
          ],
        )
      ],
    ));
  }
}

Please take a look at my stacktrace too. It points out where the error is but I have tried using stream builder and and if or else statments but still its not working

//══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Builder:
The getter 'uid' was called on null.
Receiver: null
Tried calling: uid

The relevant error-causing widget was:
  MaterialApp file:///D:/App%20Development/Main%20Projects/rideboard/lib/main.dart:39:14

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      new _RiderPageState (package:rideboard/ui/Screens/User%20Screens/Rider_Screen.dart:61:39)
#2      RiderPage.createState (package:rideboard/ui/Screens/User%20Screens/Rider_Screen.dart:38:36)
#3      new StatefulElement (package:flutter/src/widgets/framework.dart:4584:24)
#4      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:916:38)
...     Normal element mounting (166 frames)
#170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3541:14)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3306:18)
#172    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5561:32)
#173    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6105:17)
#174    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#175    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#176    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#177    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#178    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#179    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#182    ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#185    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#186    ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#187    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
#188    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#189    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#190    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#192    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#193    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#194    StatefulElement.update (package:flutter/src/widgets/framework.dart:4699:5)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#196    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#197    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#198    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5981:14)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#201    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#202    ProxyElement.update (package:flutter/src/widgets/framework.dart:4843:5)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:3293:15)
#204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4520:16)
#205    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4667:11)
#206    Element.rebuild (package:flutter/src/widgets/framework.dart:4189:5)
#207    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2694:33)
#208    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:873:21)
#209    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#210    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#211    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#212    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
#216    _invoke (dart:ui/hooks.dart:161:10)
#217    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
#218    _drawFrame (dart:ui/hooks.dart:120:31)
(elided 3 frames from dart:async)
```

**Comment by darshankawar** [comment]
@eshun4 
From your code below, you are doing:

```
DatabaseReference rideRequestsRef =
    driversRef.child(currentfirebaseUser.uid).child('newRide');
```
And seems the firebaseUser is null and hence the error.
You first need to check if the currentfirebaseUser is null or not and then proceed with your further implementation.

Closing this as not a Flutterfire issue but code implementation. You may ask this question on support channels like StackOverflow to get help. 
If you disagree, write in comments and I'll reopen it.
Thanks.
