### ISSUE TITLE
🐛 [Firebase Storage] Unable to load metadata from files with custom metadata

### ISSUE THREAD

**Issue by andrewjallenuoft** [FirebaseExtended/flutterfire#5744]
## Bug report

**Describe the bug**
Whenever a file has any custom metadata, firebase storage throws a type mismatch error when trying to load that files metadata. 

The error is: 
[firebase_storage/unknown] Expected a value of type 'Map<String, String>?', but got one of type 'IdentityMap<String, dynamic>'

Custom metadata was set both through the node.js admin client as well as Google Cloud Console. The error occurs as soon as any custom metadata is present (though key 'firebaseStorageDownloadTokens' seems to be fine, but this doesn't seem to be considered as custom metadata by the Firebase Storage on flutter).

### Steps to reproduce

1. Upload a file to Firebase Storage
2. Set custom metadata on the file, either through the Google Cloud Console or the node.js admin client. Custom metadata can be any <string, string> pair that isn't a reserved key
3. Firebase Storage on flutter will now fail to load the metadata of that file if queried via getMetadata(), i.e. `FirebaseStorage.instance.ref(filePath).getMetadata()`. The error will be: [firebase_storage/unknown] Expected a value of type 'Map<String, String>?', but got one of type 'IdentityMap<String, dynamic>'

![image](https://user-images.githubusercontent.com/32487067/114392413-a4f44580-9b90-11eb-8069-1a683866ff55.png)

For example, saving a file with this metadata will cause an error. If the custom metadata is removed, the error no longer occurs.

### Expected behavior

The custom metadata to be loaded successfully as a Map<String, String>

---

## Additional context

Occurring on Web. Untested on other platforms.

firebase_storage: ^8.0.3
firebase_core: ^1.0.3

Flutter version 2.0.4
Dart SDK constraints >=2.10.5 <3.0.0

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.4
project 1.0.0+1

dependencies:
- another_flushbar 1.10.17 [pedantic flutter]
- auto_size_text 2.1.0 [flutter]
- badges 1.2.0 [flutter]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- carousel_slider 3.0.0 [flutter]
- cloud_firestore 1.0.4 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 1.0.3 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- file_picker 3.0.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 7.1.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.0.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 8.0.3 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fluro 2.0.3 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_easyloading 3.0.0 [flutter flutter_spinkit]
- flutter_form_builder 5.0.0 [flutter flutter_localizations datetime_picker_formfield dropdown_search flutter_colorpicker flutter_chips_input flutter_datetime_picker flutter_touch_spin flutter_typeahead intl rating_bar signature validators]
- flutter_login 1.1.0 [flutter font_awesome_flutter provider transformer_page_view another_flushbar quiver pedantic]
- flutter_spinkit 5.0.0 [flutter]
- freezed_annotation 0.12.0 [collection json_annotation meta]
- google_fonts 2.0.0 [flutter http path_provider crypto]
- grouped_list 4.0.0 [flutter]
- hovering 1.0.4 [flutter]
- http 0.13.1 [http_parser meta path pedantic]
- image_picker 0.7.4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- intl 0.17.0 [clock path]
- json_serializable 3.5.1 [analyzer build build_config json_annotation meta path source_gen]
- logger 1.0.0
- modal_bottom_sheet 2.0.0 [flutter]
- rxdart 0.26.0
- scoped_model 1.1.0 [flutter]
- streaming_shared_preferences 1.0.2 [flutter shared_preferences meta]
- stripe_sdk 4.0.3 [flutter http url_launcher mask_text_input_formatter flutter_slidable simple_animations supercharged awesome_card uni_links credit_card_validator]
- url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
- url_strategy 0.2.0 [flutter_web_plugins]
- uuid 3.0.4 [crypto]

dev dependencies:
- build_runner 1.11.5 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- effective_dart 1.3.1
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 0.12.7 [analyzer build build_config meta source_gen freezed_annotation]

dependency overrides:
- image 3.0.2 [archive meta xml]
- json_annotation 3.1.1
- vin_decoder 0.2.0-nullsafety [basic_utils http random_string]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.2 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- awesome_card 1.1.5 [flutter]
- basic_utils 3.0.0-nullsafety.3 [http logging json_annotation pointycastle convert crypto]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 1.6.2 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.6 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.3 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.10 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.4 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.1 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.3 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- credit_card_type_detector 1.1.0
- credit_card_validator 1.2.0 [credit_card_type_detector]
- crypto 3.0.0 [collection typed_data]
- dart_style 1.3.12 [analyzer args path pub_semver source_span]
- datetime_picker_formfield 2.0.0 [flutter intl]
- dropdown_search 0.5.0 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.2.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.0.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.5 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.3 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.0 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_chips_input 1.9.5 [flutter]
- flutter_colorpicker 0.4.0 [flutter]
- flutter_datetime_picker 1.5.0 [flutter]
- flutter_keyboard_visibility 5.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_slidable 0.5.7 [flutter]
- flutter_touch_spin 2.0.0-nullsafety.1 [flutter intl]
- flutter_typeahead 3.1.1 [flutter flutter_keyboard_visibility]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 9.0.0 [flutter]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 0.2.0
- http_multi_server 2.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 2.0.1 [flutter meta http plugin_platform_interface]
- io 0.3.5 [meta path string_scanner]
- js 0.6.3
- logging 1.0.1
- mask_text_input_formatter 1.2.1 [flutter]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.0.2 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pointycastle 3.0.1 [collection]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- provider 5.0.0 [collection flutter nested]
- pub_semver 2.0.0 [collection]
- pubspec_parse 0.1.8 [checked_yaml json_annotation pub_semver yaml]
- quiver 3.0.0 [matcher]
- random_string 2.2.0-nullsafety
- rating_bar 0.2.0 [flutter]
- sa_v1_migration 1.1.2 [flutter]
- shared_preferences 0.5.7+3 [meta flutter shared_preferences_platform_interface shared_preferences_macos shared_preferences_web]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- signature 3.2.1 [flutter image]
- simple_animations 2.5.1 [flutter supercharged sa_v1_migration pedantic]
- sky_engine 0.0.99
- source_gen 0.9.10+3 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- supercharged 1.12.0 [supercharged_dart flutter]
- supercharged_dart 1.4.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+3 [json_annotation]
- transformer_page_view 0.1.6 [flutter]
- typed_data 1.3.0 [collection]
- uni_links 0.4.0 [flutter]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- validators 2.0.1 [vin_decoder]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.0.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]```

</details>

---

**Comment by markusaksli-nc** [comment]
Seems to be a web issue specifically. Works fine on Android at least.
```yaml
  firebase_core: ^1.0.3
  firebase_storage: ^8.0.3
```
```html
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-storage.js"></script>
```
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 2.1.0-13.0.pre.587, on Microsoft Windows [Version 10.0.19041.867], locale et-EE)
    • Flutter version 2.1.0-13.0.pre.587 at C:\Development\flutter_master
    • Framework revision 0fdc4e8805 (10 hours ago), 2021-04-12 18:50:00 -0700
    • Engine revision 8863afff16
    • Dart version 2.13.0 (build 2.13.0-222.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119
    • Flutter plugin version 55.0.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.6693.111
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.867]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 89.0.774.63

! Doctor found issues in 1 category.
```
</details>
<details>
 <summary>Logs</summary>

```
Error: [firebase_storage/unknown] Expected a value of type 'Map<String, String>?', but got one of type 'IdentityMap<String, dynamic>'
    at Object.throw_ [as throw] (http://localhost:54519/dart_sdk.js:5344:11)
    at reference_web.ReferenceWeb.new.getMetadata (http://localhost:54519/packages/firebase_storage_web/src/reference_web.dart.lib.js:111:23)
    at getMetadata.next (<anonymous>)
    at http://localhost:54519/dart_sdk.js:39201:33
    at _RootZone.runUnary (http://localhost:54519/dart_sdk.js:39058:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:54519/dart_sdk.js:34044:29)
    at handleValueCallback (http://localhost:54519/dart_sdk.js:34604:49)
    at Function._propagateToListeners (http://localhost:54519/dart_sdk.js:34642:17)
    at _Future.new.[_completeWithValue] (http://localhost:54519/dart_sdk.js:34484:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54519/dart_sdk.js:34507:35)
    at Object._microtaskLoop (http://localhost:54519/dart_sdk.js:39345:13)
    at _startMicrotaskLoop (http://localhost:54519/dart_sdk.js:39351:13)
    at http://localhost:54519/dart_sdk.js:34858:9
```
</details>

**Comment by jeromecaudoux** [comment]
I encountered the same issue and found out that `flutter build web --release` seems to fix it.
I hope this can help to resolve this bug.

```
  firebase_core: "^1.0.4"
  firebase_storage: "^8.0.4"
  
  <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-storage.js"></script>
```

**Comment by russellwheatley** [comment]
i've just tested on the Firebase Storage emulator using the latest firebase_storage plugin version, and it does appear to be fixed now.
