### ISSUE TITLE
🐛 `[firebase_ml_vision]` the app crushes at random when used with `camera` plugin

### ISSUE THREAD

**Issue by eyalkutz** [FirebaseExtended/flutterfire#5746]
## Bug report

**Describe the bug**
When streaming video from the camera to `firebase_ml_vision` the crushes at random because of some internal plugin error. This issue does not occur when using the camera without `firebase_ml_vision`.

### Steps to reproduce

1. Open the app (code will be linked)
2. move the camera around a little bit and wait a while
3. the app will crush seemingly at random

### Expected behavior

the app should have recognized nd printed aany qr codes in the image (without ever crashing of course)

---

## Additional context

The crash is definitely caused by `firebase_ml_vision` because it does not occur when using the camera alone

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19041.867], locale en-001)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.0)
[√] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.3
filma 1.0.0+1

dependencies:
- animations 1.1.2 [flutter]
- async 2.5.0 [collection]
- cached_network_image 2.4.1 [flutter flutter_cache_manager octo_image]
- camera 0.7.0+2 [flutter camera_platform_interface pedantic quiver]
- cloud_firestore 0.16.0 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_functions 0.9.0 [meta flutter firebase_core firebase_core_platform_interface cloud_functions_platform_interface cloud_functions_web]
- copy_with_extension 1.4.0
- cupertino_icons 0.1.3
- firebase_auth 0.20.1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_ml_vision 0.10.0 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_cache_manager 2.1.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_riverpod 0.12.1 [collection flutter meta riverpod state_notifier]
- http 0.12.2 [http_parser path pedantic]
- qr_flutter 3.2.0 [flutter qr]
- quiver 2.1.5 [matcher meta]

dev dependencies:
- build_runner 1.10.7 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- copy_with_extension_gen 1.4.0 [analyzer build source_gen copy_with_extension]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 3.5.1 [analyzer build build_config json_annotation meta path source_gen]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.1 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- boolean_selector 2.1.0 [source_span string_scanner]
- build 1.5.2 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.4 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.4.4 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- camera_platform_interface 1.5.0 [flutter meta plugin_platform_interface cross_file stream_transform]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0
- cloud_firestore_platform_interface 3.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 4.0.1 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 3.1.3 [firebase_core firebase_core_web cloud_functions_platform_interface flutter flutter_web_plugins http_parser meta js]
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- cross_file 0.1.0 [flutter http meta]
- crypto 2.1.5 [collection convert typed_data]
- dart_style 1.3.10 [analyzer args path source_span]
- fake_async 1.2.0 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 3.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- freezed_annotation 0.12.0 [collection json_annotation meta]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3
- json_annotation 3.1.1
- logging 0.11.4
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 0.9.7
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- qr 1.3.0 [meta]
- riverpod 0.12.1 [collection freezed_annotation meta state_notifier]
- rxdart 0.24.1
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.9 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- state_notifier 0.6.0 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+2 [json_annotation]
- typed_data 1.3.0 [collection]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---
code for the app: https://gist.github.com/eyalkutz/52dc0e216622ce1333fa3ee35aac18e0

**Comment by eyalkutz** [comment]
I have opened an issue in the flutter repo which was closed and I was directed here: 
https://github.com/flutter/flutter/issues/79037

**Comment by markusaksli-nc** [comment]
Hi @eyalkutz 
Well, the issue is just that you run out of memory. I would ask you to attach the crash logs but I'm guessing it's something like this
```
E/AndroidRuntime(29861): Process: com.nevercode.triage, PID: 29861
E/AndroidRuntime(29861): java.lang.OutOfMemoryError: Failed to allocate a 3686624 byte allocation with 3612096 free bytes and 3MB until OOM, max allowed footprint 268435456, growth limit 268435456
E/AndroidRuntime(29861): 	at java.util.Arrays.copyOf(Arrays.java:3164)
E/AndroidRuntime(29861): 	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
E/AndroidRuntime(29861): 	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
E/AndroidRuntime(29861): 	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
...
```
This is pretty much expected if you use the max resolution on a good smartphone camera and run detection on every image. You can take a look at the official example to see how to do this more sensibly.
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_ml_vision/example/lib/material_barcode_scanner.dart
Thank you
