### ISSUE TITLE
🐛 [cloud_firestore, firebase_auth] iOS cannot access firestore in idTokenChanges() stream listener

### ISSUE THREAD

**Issue by petoknm** [FirebaseExtended/flutterfire#5764]
## Bug report

I am making an authenticated cloud firestore request to create a document after a user signs in. Works fine on Android, but on iOS it throws:

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation. 
#0      MethodChannelDocumentReference.set  package:cloud_firestore_platform_interface/…/method_channel/method_channel_document_reference.dart:43 <asynchronous suspension> 
#1      FirebaseChatCore.createUserInFirestore  package:flutter_firebase_chat_core/src/firebase_chat_core.dart:94 <asynchronous suspension> 
#2      new AuthCubit.<anonymous closure>  package:formfirst/cubits/auth.dart:43 <asynchronous suspension> 
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: [cloud_firestore/permission-denied] The caller does not have permission to execute the specified operation. 
#0      MethodChannelDocumentReference.set  package:cloud_firestore_platform_interface/…/method_channel/method_channel_document_reference.dart:43 <asynchronous suspension> 
#1      FirebaseChatCore.createUserInFirestore  package:flutter_firebase_chat_core/src/firebase_chat_core.dart:94 <asynchronous suspension> 
#2      new AuthCubit.<anonymous closure>  package:formfirst/cubits/auth.dart:43 <asynchronous suspension>
```

### Steps to reproduce

```dart
auth.idTokenChanges().listen((user) async {
  if (user != null) {
    ...
    await FirebaseFirestore.instance.collection('users').doc(user.id).set({...});
  }
});
```

### Expected behavior

I expect iOS and Android to work the same way. (ideally both of them working using this example of making authenticated calls inside the idTokenChanges() stream listener.)

---

## Additional context

I was trying to figure out whether the auth/user for firebase is stored on the native plugin side or on the dart side. But it seems that creating a document directly calls a method channel, so I'm assuming that on Android the user/auth token gets stored before calling the idTokenChanges() listeners, and on iOS it might be getting saved only after notifying listeners. But that's just my speculation at this point.

---

## Deps:

```
firebase_core: 1.0.3
firebase_auth: 1.0.3
cloud_firestore: 1.0.4
```

## More info

```bash
$ flutter doctor -v
[✓] Flutter (Channel stable, 2.0.4, on Linux, locale en_DK.UTF-8)
    • Flutter version 2.0.4 at /home/peter/Programming/flutter
    • Framework revision b1395592de (13 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/peter/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio
    • Android Studio at /opt/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

```bash
$ flutter pub deps -- --style=compact
Dart SDK 2.12.2
Flutter SDK 2.0.4
formfirst 0.5.3+20

dependencies:
- badges 2.0.0-nullsafety.1 [flutter]
- better_player 0.0.64 [flutter cupertino_icons wakelock pedantic meta flutter_widget_from_html_core visibility_detector path_provider collection]
- bloc 7.0.0 [meta]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- camera 0.8.1 [flutter camera_platform_interface pedantic quiver]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- dio 4.0.0 [http_parser path]
- duration 3.0.6
- email_validator 2.0.1
- equatable 2.0.0 [collection meta]
- firebase_analytics 8.0.0-dev.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.0.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.0.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 9.1.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.0.0 [flutter bloc provider]
- flutter_blue 0.8.0 [flutter convert protobuf rxdart collection meta]
- flutter_chat_ui 1.0.0 [flutter flutter_chat_types flutter_link_previewer intl photo_view]
- flutter_firebase_chat_core 1.0.0 [flutter cloud_firestore firebase_auth flutter_chat_types meta]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_markdown 0.6.1 [flutter markdown meta path]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- flutter_sound 8.0.1+11 [path_provider logger recase uuid provider flutter_spinkit path synchronized flutter flutter_sound_platform_interface flutter_sound_web]
- flutter_svg 0.21.0+1 [flutter meta path_drawing vector_math xml]
- google_fonts 2.0.0 [flutter http path_provider crypto]
- google_sign_in 5.0.1 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- hive 2.0.2 [meta crypto]
- hive_flutter 1.0.0 [flutter hive path_provider path]
- image_picker 0.7.4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- intl 0.17.0 [clock path]
- json_annotation 4.0.1
- meta 1.3.0
- overlay_support 1.2.0 [flutter async]
- path 1.8.0
- provider 5.0.0 [collection flutter nested]
- recase 4.0.0-nullsafety.0
- replay_bloc 0.0.1 [bloc]
- rxdart 0.26.0
- share 2.0.1 [meta mime flutter]
- sign_in_with_apple 3.0.0 [flutter meta]
- time 2.0.0
- uuid 3.0.4 [crypto]
- video_compress 3.0.0 [flutter]
- wakelock 0.5.0+2 [flutter meta wakelock_macos wakelock_windows wakelock_platform_interface wakelock_web]
- yaml 3.1.0 [collection source_span string_scanner]

dev dependencies:
- build_runner 1.12.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- hive_generator 1.0.1 [build source_gen hive analyzer]
- json_serializable 4.1.0 [analyzer build build_config collection json_annotation meta path source_gen]
- pedantic 1.11.0
- test 1.16.5 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _fe_analyzer_shared 20.0.0 [meta]
- analyzer 1.4.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.0 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.7 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.0 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform]
- build_runner_core 6.1.12 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- camera_platform_interface 2.0.1 [flutter meta plugin_platform_interface cross_file stream_transform]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore 1.0.4 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_firestore_platform_interface 4.0.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.4 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- convert 3.0.0 [typed_data]
- coverage 1.0.2 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.1+1 [flutter meta]
- csslib 0.17.0 [source_span]
- cupertino_icons 1.0.2
- dart_style 2.0.0 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.0-dev.0 [flutter meta]
- firebase_analytics_web 0.3.0-dev.0 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.0.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.5 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 2.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_chat_types 2.0.7 [meta]
- flutter_link_previewer 1.0.4 [flutter flutter_chat_types flutter_linkify html http linkify meta url_launcher]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_sound_platform_interface 8.0.1+11 [flutter meta plugin_platform_interface]
- flutter_sound_web 8.0.1+11 [flutter_sound_platform_interface flutter flutter_web_plugins meta js]
- flutter_spinkit 5.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- flutter_widget_from_html_core 0.6.0 [csslib flutter html]
- font_awesome_flutter 9.0.0 [flutter]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 1.0.0
- html 0.15.0 [csslib source_span]
- http 0.13.1 [http_parser meta path pedantic]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.0.1 [flutter meta http plugin_platform_interface]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- linkify 4.0.0
- logger 1.0.0
- logging 1.0.1
- markdown 4.0.0 [args charcode meta]
- matcher 0.12.10 [stack_trace]
- mime 1.0.0
- nested 1.0.0 [flutter]
- node_preamble 1.4.13
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- path_drawing 0.5.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0 [vector_math meta]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- petitparser 4.1.0 [meta]
- photo_view 0.11.1 [flutter]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- protobuf 2.0.0 [fixnum]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1 [matcher]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.0.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.15 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- visibility_detector 0.2.0 [flutter]
- vm_service 6.2.0
- wakelock_macos 0.1.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.0 [flutter meta]
- wakelock_web 0.2.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.1.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.0.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.0.0 [logging]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
```

**Comment by markusaksli-nc** [comment]
Hi @petoknm 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Could you also provide the full error you get?
Thank you

**Comment by petoknm** [comment]
@markusaksli-nc I updated the issue

**Comment by Duc56789** [comment]
Fff

**Comment by markusaksli-nc** [comment]
Could this be coming from your firestore rules?

**Comment by Duc56789** [comment]
Được gửi từ iPhone của tôi

**Comment by petoknm** [comment]
@markusaksli-nc I just checked my firebase rules and they were blocked not because of a missing authentication but because of the document payload being different on iOS.

**Comment by Duc56789** [comment]
BFF
