### ISSUE TITLE
🐛 [firebase_remote_config] Internal remote config fetch error on iOS

### ISSUE THREAD

**Issue by b-jan** [FirebaseExtended/flutterfire#5781]
## Bug report

My app is crashing on start on iOS only. Firebase Remote config seems to be responsible for the crash.
I use the last null safety package of `firebase_remote_config`.

## Additional context

`flutter run` logs:

```
Launching lib/main.dart on iPhone in debug mode...
Signing iOS app for device deployment using developer
identity: "Apple Development: Baptiste JAN
(XXXXXXXXX)"
Running pod install...                                             10,4s
Running Xcode build...
 └─Compiling, linking and signing...                        27,5s
Xcode build done.
85,3s
Installing and launching...                                        24,2s
flutter: [debug] release: com.app.myApp@1.0.0+1    flutter: AuthenticationStarted()                       Syncing files to device iPhone...                                  239ms

💪 Running with sound null safety 💪
flutter: Transition { currentState: AuthenticationInitial(), event: AuthenticationStarted(), nextState: AuthenticationFailure() }
[firebase_remote_config/internal] internal remote config fetch error

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannelFirebaseRemoteConfig.fetchAndActivate (package:firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart:145:29)
<asynchronous suspension>
#3      RemoteConfig.fetchAndActivate (package:firebase_remote_config/src/remote_config.dart:86:26)
<asynchronous suspension>
#4      versionCheck (package:my_app/ui/settings/remote_config.dart:30:5)
<asynchronous suspension>
#5      _SplashScreenState.afterFirstLayout (package:my_app/ui/screens/splash_screen.dart:16:25)
<asynchronous suspension>
```

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS
    X 10.15.7 19H2 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android
    devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.55.1)
[✓] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.3
dunk_app 3.0.0+24

dependencies:
- after_layout 1.1.0 [flutter]
- audioplayers 0.18.3 [uuid path_provider flutter flutter_web_plugins]
- bloc 7.0.0 [meta]
- carousel_slider 4.0.0-nullsafety.0 [flutter]
- collection 1.15.0
- country_code_picker 2.0.1 [flutter modal_bottom_sheet collection universal_platform]
- crypto 3.0.1 [collection typed_data]
- equatable 2.0.0 [collection meta]
- firebase_analytics 8.0.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.1.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.0 [firebase_core flutter]
- firebase_messaging 9.1.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 0.10.0-dev.0 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.0.0 [flutter bloc provider]
- flutter_compass 0.6.0 [flutter rxdart]
- flutter_dotenv 4.0.0-nullsafety.0 [flutter]
- flutter_facebook_auth 3.3.2+2 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_local_notifications 5.0.0+1 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_rating_bar 4.0.0 [flutter]
- geolocator 7.0.3 [flutter geolocator_platform_interface geolocator_web]
- google_maps_flutter 2.0.3 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_maps_webservice 0.0.20-nullsafety.4 [http meta json_annotation]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- graphql 5.0.0-nullsafety.4 [meta path gql gql_exec gql_link gql_http_link gql_transform_link gql_error_link gql_dedupe_link hive normalize http collection web_socket_channel stream_channel rxdart uuid]
- http 0.13.1 [http_parser meta path pedantic]
- hydrated_bloc 7.0.0 [bloc hive meta synchronized]
- image_picker 0.7.4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- package_info 2.0.0 [flutter]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pull_to_refresh 1.6.4-nullsafety.0 [flutter]
- sensors 2.0.0 [flutter]
- sentry_flutter 4.1.0-nullsafety.1 [flutter flutter_web_plugins sentry package_info]
- share 2.0.1 [meta mime flutter]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 3.0.0 [flutter meta]
- transparent_image 2.0.0
- url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
- uuid 3.0.4 [crypto]
- vibration 1.7.4-nullsafety.0 [flutter vibration_web]

dev dependencies:
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]

transitive dependencies:
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.0 [flutter meta]
- firebase_analytics_web 0.3.0 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.1.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.6 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 0.3.0-dev.0 [firebase_core flutter meta plugin_platform_interface]
- flutter_facebook_auth_platform_interface 2.4.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.4.1+1 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- geolocator_platform_interface 2.0.2 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.3 [flutter flutter_web_plugins geolocator_platform_interface]
- google_maps_flutter_platform_interface 2.0.4 [flutter meta plugin_platform_interface stream_transform collection]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- gql 0.13.0-nullsafety.2 [collection meta source_span]
- gql_dedupe_link 2.0.0-nullsafety.1 [meta gql_exec gql_link async]
- gql_error_link 0.2.0-nullsafety.1 [async gql_exec gql_link meta]
- gql_exec 0.3.0-nullsafety.2 [collection meta gql]
- gql_http_link 0.4.0-nullsafety.1 [meta gql gql_exec gql_link http http_parser]
- gql_link 0.4.0-nullsafety.3 [meta gql gql_exec]
- gql_transform_link 0.2.0-nullsafety.1 [gql_exec gql_link]
- hive 2.0.3 [meta crypto]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.1.0 [flutter meta http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- modal_bottom_sheet 2.0.0 [flutter]
- nested 1.0.0 [flutter]
- normalize 0.5.1-0.1.nullsafety.0 [gql collection]
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- provider 5.0.0 [collection flutter nested]
- quiver 3.0.1 [matcher]
- rxdart 0.26.0
- sentry 4.1.0-nullsafety.1 [http meta stack_trace uuid]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- timezone 0.7.0 [path]
- typed_data 1.3.0 [collection]
- universal_platform 1.0.0-nullsafety
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- vibration_web 1.6.3-nullsafety.0 [flutter flutter_web_plugins]
- web_socket_channel 2.0.0 [async crypto stream_channel]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Wasn't able to reproduce this using the official example with
```yaml
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.3
  firebase_remote_config: ^0.10.0-dev.0
```
<details>
 <summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.2.0-11.0.pre.103, on macOS 11.2.3 20D91
    darwin-arm, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.103 at
      /Users/nevercode/development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f0c9710493 (34 hours ago), 2021-04-13 20:29:40 -0500
    • Engine revision 04cd0db032
    • Dart version 2.13.0 (build 2.13.0-232.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```
</details>

**Comment by b-jan** [comment]
I don't know what happened but I cannot reproduce anymore...

Closing the issue.
