### ISSUE TITLE
🐛 [firebase_messaging] Failed to get FIS auth token

### ISSUE THREAD

**Issue by realkimmy** [FirebaseExtended/flutterfire#5814]
## Bug report

**Describe the bug**
I run the application on the Android emulator, and got an error.

```
E/FirebaseInstanceId( 7623): Failed to get FIS auth token
E/FirebaseInstanceId( 7623): java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseInstanceId( 7623): 	at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
E/FirebaseInstanceId( 7623): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:23)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.iid.GmsRpc.setDefaultAttributesToBundle(com.google.firebase:firebase-iid@@21.0.1:11)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.iid.GmsRpc.startRpc(com.google.firebase:firebase-iid@@21.0.1:1)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.iid.GmsRpc.getToken(com.google.firebase:firebase-iid@@21.0.1:1)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$1$FirebaseInstanceId(Unknown Source:2)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.iid.FirebaseInstanceId$$Lambda$3.start(Unknown Source:8)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.iid.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-iid@@21.0.1:7)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$2$FirebaseInstanceId(Unknown Source:33)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.iid.FirebaseInstanceId$$Lambda$0.then(Unknown Source:6)
E/FirebaseInstanceId( 7623): 	at com.google.android.gms.tasks.zzf.run(Unknown Source:2)
E/FirebaseInstanceId( 7623): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseInstanceId( 7623): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseInstanceId( 7623): 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
E/FirebaseInstanceId( 7623): 	at java.lang.Thread.run(Thread.java:923)
E/FirebaseInstanceId( 7623): Caused by: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseInstanceId( 7623): 	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:200)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:533)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:388)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:377)
E/FirebaseInstanceId( 7623): 	at com.google.firebase.installations.FirebaseInstallations$$Lambda$4.run(Unknown Source:4)
E/FirebaseInstanceId( 7623): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseInstanceId( 7623): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseInstanceId( 7623): 	... 1 more
E/FirebaseInstanceId( 7623): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
    • Flutter version 2.0.4 at /Users/ying/flutter
    • Framework revision b1395592de (2 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/ying/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /Users/ying/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 55.0.5
    • Dart plugin version 211.6693.108

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554             • android-x86    • Android 11 (API 30) (emulator)
    • WY's iPhone (mobile)        • 00008020-000A1D110A32002E • ios            • iOS 14.4.2
    • macOS (desktop)             • macos                     • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)                • chrome                    • web-javascript • Google Chrome 90.0.4430.72

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.4
gitter 1.2.0+5

dependencies:
- adaptive_dialog 0.10.0+5 [animations flutter meta]
- animations 2.0.0 [flutter]
- bot_toast 4.0.1 [flutter]
- bubble_tab_indicator 0.1.6 [flutter]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- collection 1.15.0
- cupertino_back_gesture 0.1.0 [flutter]
- cupertino_icons 1.0.2
- device_info 2.0.0 [flutter device_info_platform_interface]
- dio 4.0.0 [http_parser path]
- dio_http_cache 0.3.0-nullsafety.0 [crypto dio flutter json_serializable path quiver sqflite]
- dots_indicator 2.0.0 [flutter]
- expandable 5.0.1 [flutter]
- extended_text 5.0.5 [extended_text_library flutter]
- firebase_messaging 9.1.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.0.0 [flutter bloc provider]
- flutter_colorpicker 0.4.0 [flutter]
- flutter_highlight 0.7.0 [flutter highlight]
- flutter_inappwebview 5.0.5+3 [flutter]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_local_notifications 5.0.0+1 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_markdown 0.6.1 [flutter markdown meta path]
- flutter_native_splash 1.1.7+1 [image meta path xml yaml]
- flutter_slidable 0.6.0 [flutter]
- flutter_staggered_grid_view 0.4.0 [flutter]
- flutter_sticky_header 0.6.0 [flutter value_layout_builder]
- flutter_svg 0.21.0+1 [flutter meta path_drawing vector_math xml]
- flutter_widget_from_html 0.6.0 [flutter flutter_widget_from_html_core fwfh_cached_network_image fwfh_chewie fwfh_svg fwfh_url_launcher fwfh_webview html]
- font_awesome_flutter 9.0.0 [flutter]
- google_fonts 2.0.0 [flutter http path_provider crypto]
- graphql_flutter 5.0.0-nullsafety.2 [graphql gql_exec flutter meta path_provider path connectivity hive plugin_platform_interface]
- http 0.13.1 [http_parser meta path pedantic]
- hydrated_bloc 7.0.0 [bloc hive meta synchronized]
- intl 0.17.0 [clock path]
- json_annotation 4.0.1
- localstorage 4.0.0+1 [flutter path_provider]
- lottie 1.0.1 [archive characters charcode collection flutter logging meta path vector_math]
- open_appstore 1.0.2 [flutter]
- package_info 2.0.0 [flutter]
- pretty_dio_logger 1.2.0-beta-1 [dio]
- provider 5.0.0 [collection flutter nested]
- rate_my_app 1.1.0+1 [shared_preferences flutter_rating_bar pedantic flutter]
- sentry_flutter 5.0.0 [flutter flutter_web_plugins sentry package_info_plus]
- share 2.0.0 [meta mime flutter]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- splashscreen 1.4.0 [flutter]
- url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
- vibration 1.7.4-nullsafety.0 [flutter vibration_web]
- webview_flutter 2.0.4 [flutter]

dev dependencies:
- build_runner 1.12.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 4.1.0 [analyzer build build_config collection json_annotation meta path source_gen]
- pedantic 1.11.0

transitive dependencies:
- _fe_analyzer_shared 20.0.0 [meta]
- analyzer 1.4.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- bloc 7.0.0 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.0 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.7 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.0 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform]
- build_runner_core 6.1.12 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- chewie 1.0.0 [cupertino_icons flutter video_player wakelock]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- connectivity 3.0.3 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- connectivity_for_web 0.4.0 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.2.0 [flutter]
- connectivity_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.0 [source_span]
- dart_style 2.0.0 [analyzer args path pub_semver source_span]
- device_info_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- extended_text_library 5.0.2 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_rating_bar 4.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- flutter_widget_from_html_core 0.6.0 [csslib flutter html]
- fwfh_cached_network_image 0.6.0 [cached_network_image flutter flutter_widget_from_html_core]
- fwfh_chewie 0.6.0 [chewie flutter flutter_widget_from_html_core video_player]
- fwfh_svg 0.6.0 [flutter flutter_svg flutter_widget_from_html_core]
- fwfh_url_launcher 0.6.0 [flutter flutter_widget_from_html_core url_launcher]
- fwfh_webview 0.6.0 [flutter flutter_widget_from_html_core webview_flutter]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- gql 0.13.0-nullsafety.2 [collection meta source_span]
- gql_dedupe_link 2.0.0-nullsafety.1 [meta gql_exec gql_link async]
- gql_error_link 0.2.0-nullsafety.1 [async gql_exec gql_link meta]
- gql_exec 0.3.0-nullsafety.2 [collection meta gql]
- gql_http_link 0.4.0-nullsafety.1 [meta gql gql_exec gql_link http http_parser]
- gql_link 0.4.0-nullsafety.3 [meta gql gql_exec]
- gql_transform_link 0.2.0-nullsafety.1 [gql_exec gql_link]
- graphql 5.0.0-nullsafety.4 [meta path gql gql_exec gql_link gql_http_link gql_transform_link gql_error_link gql_dedupe_link hive normalize http collection web_socket_channel stream_channel rxdart uuid]
- graphs 1.0.0
- highlight 0.7.0 [collection]
- hive 2.0.2 [meta crypto]
- html 0.15.0 [csslib source_span]
- http_multi_server 2.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3
- linkify 4.0.0
- logging 1.0.1
- markdown 4.0.0 [args charcode meta]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- normalize 0.5.1-0.1.nullsafety.0 [gql collection]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- package_info_plus 1.0.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.0 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.0.0 [flutter]
- package_info_plus_platform_interface 1.0.0 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.0 [http package_info_plus_platform_interface flutter flutter_web_plugins meta]
- package_info_plus_windows 1.0.0 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 0.5.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0 [vector_math meta]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.1.0 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1 [matcher]
- rxdart 0.26.0
- sentry 5.0.0 [http meta stack_trace uuid]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- uuid 3.0.4 [crypto]
- value_layout_builder 0.3.1 [flutter]
- vector_math 2.1.0
- vibration_web 1.6.3-nullsafety.0 [flutter flutter_web_plugins]
- video_player 2.1.1 [meta video_player_platform_interface video_player_web flutter flutter_test]
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.0 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock 0.4.0 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web]
- wakelock_macos 0.1.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.0 [flutter meta]
- wakelock_web 0.2.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.0.0 [async crypto stream_channel]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @realkimmy 
What code triggers this exception?
Thank you

**Comment by realkimmy** [comment]
Very strange, no error is reported now. But I cannot receive notifications on the Android emulator.

**Comment by markusaksli-nc** [comment]
Are you running the official example? If not can you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by realkimmy** [comment]
```
E/chromium( 8392): [ERROR:cookie_manager.cc(137)] Strict Secure Cookie policy does not allow setting a secure cookie for http://googleads.g.doubleclick.net/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.
E/FirebaseInstanceId( 8392): Failed to get FIS auth token
E/FirebaseInstanceId( 8392): java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseInstanceId( 8392): 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@17.1.0:69)
E/FirebaseInstanceId( 8392): 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.1.0:23)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.iid.GmsRpc.setDefaultAttributesToBundle(com.google.firebase:firebase-iid@@21.0.1:11)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.iid.GmsRpc.startRpc(com.google.firebase:firebase-iid@@21.0.1:1)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.iid.GmsRpc.getToken(com.google.firebase:firebase-iid@@21.0.1:1)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$1$FirebaseInstanceId(Unknown Source:2)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.iid.FirebaseInstanceId$$Lambda$3.start(Unknown Source:8)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.iid.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-iid@@21.0.1:7)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.iid.FirebaseInstanceId.lambda$getInstanceId$2$FirebaseInstanceId(Unknown Source:33)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.iid.FirebaseInstanceId$$Lambda$0.then(Unknown Source:6)
E/FirebaseInstanceId( 8392): 	at com.google.android.gms.tasks.zzf.run(com.google.android.gms:play-services-tasks@@17.1.0:2)
E/FirebaseInstanceId( 8392): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseInstanceId( 8392): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseInstanceId( 8392): 	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.3.0:6)
E/FirebaseInstanceId( 8392): 	at java.lang.Thread.run(Thread.java:923)
E/FirebaseInstanceId( 8392): Caused by: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseInstanceId( 8392): 	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:200)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:533)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:388)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:377)
E/FirebaseInstanceId( 8392): 	at com.google.firebase.installations.FirebaseInstallations$$Lambda$4.run(Unknown Source:4)
E/FirebaseInstanceId( 8392): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseInstanceId( 8392): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseInstanceId( 8392): 	... 1 more
E/FirebaseInstanceId( 8392): Topic sync or token retrieval failed on hard failure exceptions: AUTHENTICATION_FAILED. Won't retry the operation.
```

**Comment by markusaksli-nc** [comment]
Same question as before
