### ISSUE TITLE
flutter_admob crashed app due to multiDex

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#583]
i use the newest version of firebase_admob plugin, when i add multiDex
```xml
defaultConfig {
    multiDexEnabled true
    ......
}
```
and
```xml
implementation 'com.android.support:multidex:1.0.3'
```
it crashed, due to
```shell
1-08 05:06:54.923 6139-6139/com.vpngo.flutterapp E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAdsInitProvider" on path: /data/app/com.vpngo.flutterapp-2.apk
        at android.app.ActivityThread.installProvider(ActivityThread.java:4822)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4432)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
        at android.app.ActivityThread.access$1300(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.MobileAdsInitProvider" on path: /data/app/com.vpngo.flutterapp-2.apk
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4807)
```

**Comment by kroikie** [comment]
@ErosZy

The issue at https://github.com/flutter/flutter/issues/24091 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @ErosZy
Did the proposed [solution ](https://github.com/flutter/flutter/issues/24091#issuecomment-478576034)worked for you?
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
