### ISSUE TITLE
🐛 [firebase_crashlytics] `flutter build appbundle` builds app that uses private API's

### ISSUE THREAD

**Issue by stijnster** [FirebaseExtended/flutterfire#5850]
We have recently updated our app (previously built on flutter 1.x, updated to 2.0.4).

**$ flutter doctor -v**
```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-BE)
    • Flutter version 2.0.4 at /Users/smath/Work/flutter
    • Framework revision b1395592de (12 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/smath/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
```

**Pubspec.yaml**
```
version: 1.1.0+29

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  http: ^0.13.1
  webview_flutter: ^2.0.4
  flutter_svg: ^0.21.0
  package_info: ^2.0.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  firebase_analytics: ^7.1.1
  firebase_crashlytics: ^2.0.0
  firebase_messaging: ^9.1.1
  devicelocale: ^0.4.1
  simple_connectivity: ^0.1.1
  share: '^2.0.1'
  uni_links: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

When we run an appbundle build (`flutter clean; flutter build appbundle`) and upload the bundle to the Google Play Store, the pre-launch report returns with 2 errors and 2 warnings, regarding the use of private API's;

```
Errors;
Non-SDK API Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V
Non-SDK API Lcom/android/org/conscrypt/ConscryptEngineSocket;->setUseSessionTickets(Z)V

Warnings;
Non-SDK API Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B
Non-SDK API Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V
```

I've looked at the stack trace from the pre-launch report and at the bottom I see a reference to `com.google.firebase.crashlytics` (see stack trace below this email).

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V
at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
at java.lang.Class.getDeclaredMethodInternal(Native Method)
at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
at java.lang.Class.getMethod(Class.java:2066)
at java.lang.Class.getMethod(Class.java:1693)
at f.g0.j.e.a(Unknown Source:1)
at f.g0.j.e.a(Unknown Source:7)
at f.g0.j.e.b(Unknown Source:4)
at f.g0.j.e.c(Unknown Source:0)
at f.g0.j.a.a(Unknown Source:23)
at f.g0.f.c.a(Unknown Source:62)
at f.g0.f.c.a(Unknown Source:54)
at f.g0.f.c.a(Unknown Source:178)
at f.g0.f.g.a(Unknown Source:222)
at f.g0.f.g.a(Unknown Source:0)
at f.g0.f.g.a(Unknown Source:22)
at f.g0.f.a.a(Unknown Source:25)
at f.g0.g.g.a(Unknown Source:158)
at f.g0.g.g.a(Unknown Source:6)
at f.g0.e.a.a(Unknown Source:124)
at f.g0.g.g.a(Unknown Source:158)
at f.g0.g.g.a(Unknown Source:6)
at f.g0.g.a.a(Unknown Source:161)
at f.g0.g.g.a(Unknown Source:158)
at f.g0.g.j.a(Unknown Source:48)
at f.g0.g.g.a(Unknown Source:158)
at f.g0.g.g.a(Unknown Source:6)
at f.y.b(Unknown Source:115)
at f.y.j(Unknown Source:31)
at com.google.firebase.crashlytics.d.k.b.a(Unknown Source:10)
at com.google.firebase.crashlytics.d.p.j.d.a(Unknown Source:61)
at com.google.firebase.crashlytics.d.p.d$a.a(Unknown Source:13)
at com.google.firebase.crashlytics.d.p.d$a.a(Unknown Source:2)
at b.b.a.b.i.y.run(Unknown Source:12)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.firebase.crashlytics.d.h.w$a$a.a(Unknown Source:2)
at com.google.firebase.crashlytics.d.h.d.run(Unknown Source:5)
at java.lang.Thread.run(Thread.java:923)
```

We had filed this issue earlier on the main flutter issue tracker, but they redirected us here (https://github.com/flutter/flutter/issues/80715).

In the meantime, we upgraded to flutter 2.0.5, updated all dependencies and launched the prelaunch report again, but the same errors and warnings remain.

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 2.0.5, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-BE)
    • Flutter version 2.0.5 at /Users/smath/Work/flutter
    • Framework revision adc687823a (4 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/smath/Library/Android/sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```

**Pubspec.yaml**
```
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  http: ^0.13.1
  webview_flutter: ^2.0.4
  flutter_svg: ^0.21.0
  package_info: ^2.0.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  firebase_analytics: ^8.0.0
  firebase_crashlytics: ^2.0.0
  firebase_messaging: ^9.1.1
  devicelocale: ^0.4.1
  simple_connectivity: ^0.1.1
  share: '^2.0.1'
  uni_links: ^0.4.0
```

**Comment by marcqtan** [comment]
same issue here. here's the complete log:

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at okhttp3.internal.platform.OptionalMethod.getPublicMethod(OptionalMethod.java:164)
	at okhttp3.internal.platform.OptionalMethod.getMethod(OptionalMethod.java:149)
	at okhttp3.internal.platform.OptionalMethod.invokeOptional(OptionalMethod.java:66)
	at okhttp3.internal.platform.OptionalMethod.invokeOptionalWithoutCheckedException(OptionalMethod.java:86)
	at okhttp3.internal.platform.AndroidPlatform.configureTlsExtensions(AndroidPlatform.java:123)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:314)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall.execute(RealCall.java:92)
	at com.google.firebase.crashlytics.internal.network.HttpRequest.execute(HttpRequest.java:129)
	at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:86)
	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
	at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
	at com.google.android.gms.tasks.zzp.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:60)
	at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by stijnster** [comment]
Just finished a build with Flutter 2.0.6 and the updated `firebase_crashlytics` 2.0.2, ran the report, but still the same issues.

**Comment by pinkminds** [comment]
Exactly the same issue. +1

**Comment by marcqtan** [comment]
any updates?

**Comment by robbysoerya** [comment]
same issue

**Comment by ToddBrawn** [comment]
Same issue.

**Comment by russellwheatley** [comment]
This isn't something we have control over I'm afraid. Flutterfire is just a wrapper around the official Firebase Crashlytics SDK. I would say you have a couple of options as far as I can tell. You can either take it to the official android sdk and find out if they can upgrade the problem dependency causing the problem (which appears to be `conscrypt`? judging from your report). Or you can try and upgrade it yourself, [this SO article](https://stackoverflow.com/questions/67409917/strictmode-policy-violation-android-os-strictmode-nonsdkapiusedviolation-lcom) may be able to point you in the right direction. Hope this helps.
