### ISSUE TITLE
admob plugin causes Android to crash on startup

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#591]
When I add the ad_mob (firebase_admob: ^0.6.1+1) Android emulator crashing before any code executes. As soon as I take it out, it works. I tried to start LogCat, but no logs are generated (I am using VS Code)

I have the following plugins working successfully with firebase
flutter_crashlytics: ^0.1.1
firebase_analytics: ^1.0.4

But ad_mob just won't work.

**Comment by tonypottera24** [comment]
In my case, it crash when using android emulator without google play.
`I/DynamiteModule( 2982): Selected local version of com.google.android.gms.ads.dynamite
W/Ads     ( 2982): #007 Could not call remote method. @28
W/Ads     ( 2982): com.google.android.gms.internal.ads.zzayz: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Failed to instantiate module class: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
W/Ads     ( 2982):      at com.google.android.gms.internal.ads.zzayx.zza(com.google.android.gms:play-services-ads-lite@@18.3.0:3)
W/Ads     ( 2982):      at com.google.android.gms.internal.ads.zzaku.zza(com.google.android.gms:play-services-ads-lite@@18.3.0:17)
W/Ads     ( 2982):      at com.google.android.gms.internal.ads.zzaku.zzd(com.google.android.gms:play-services-ads-lite@@18.3.0:44)
W/Ads     ( 2982):      at com.google.android.gms.internal.ads.zzakt.run(com.google.android.gms:play-services-ads-lite@@18.3.0)
W/Ads     ( 2982):      at java.lang.Thread.run(Thread.java:856)
W/Ads     ( 2982): Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Failed to instantiate module class: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
W/Ads     ( 2982):      at com.google.android.gms.dynamite.DynamiteModule.instantiate(Unknown Source)
W/Ads     ( 2982):      at com.google.android.gms.internal.ads.zzayx.zza(com.google.android.gms:play-services-ads-lite@@18.3.0:1)
W/Ads     ( 2982):      ... 4 more
W/Ads     ( 2982): Caused by: java.lang.ClassNotFoundException: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
W/Ads     ( 2982):      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
W/Ads     ( 2982):      at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
W/Ads     ( 2982):      at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
W/Ads     ( 2982):      at com.google.android.gms.dynamite.DynamiteModule.instantiate(Unknown Source)
W/Ads     ( 2982):      ... 5 more`
