### ISSUE TITLE
🐛 [cloud_firestore] NullPointerException after Android Activity is destroyed

### ISSUE THREAD

**Issue by audkar** [FirebaseExtended/flutterfire#5914]
## Bug report

**Describe the bug**
ANDROID: Sometimes NPE exception is thrown after Activity is destroyed.

### Steps to reproduce

This is not 100% reproducible. Happens only on rare occations

1. Do some action with Firestore. I have no subscriptions in app. Only simple `get()/set()`.
2. Close activity with back button. _(Activity gets destroyed, but app is still running)_

### Expected behavior

Not crash

---

## Additional context

Activity is destroyed. But app is kept in background state
![image](https://user-images.githubusercontent.com/1947112/115959034-d830c000-a512-11eb-9885-ceecd67141af.png)

App is very simple. Single activity and no services.

### Stacktrace

<details><summary>Click To Expand</summary>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
    at io.flutter.plugins.firebase.firestore.u.m.h(TransactionStreamHandler.java:8)
    at io.flutter.plugins.firebase.firestore.u.m.i
    at io.flutter.plugins.firebase.firestore.u.e.a
    at b.a.a.a.i.r.run
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.2.0-10.1.pre, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.0-211.6.beta
Flutter SDK 2.2.0-10.1.pre
app 1.0.0+1

dependencies:
- async 2.5.0 [collection]
- cloud_firestore 1.0.6 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.2
- firebase_auth 1.1.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.4 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.1 [firebase_core flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.0.0 [flutter hive path_provider path]
- intl 0.17.0 [clock path]
- provider 5.0.0 [collection flutter nested]
- rxdart 0.26.0
- sentry_flutter 5.0.0 [flutter flutter_web_plugins sentry package_info_plus]
- uuid 3.0.4 [crypto]

dev dependencies:
- build_runner 2.0.1 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime package_config path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- hive_generator 1.1.0 [build source_gen hive analyzer source_helper]
- pedantic 1.11.0

transitive dependencies:
- _fe_analyzer_shared 21.0.0 [meta]
- analyzer 1.5.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.0.0
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.1 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform]
- build_runner_core 7.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.2 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.6 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.0.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.0 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 2.0.0
- http 0.13.1 [http_parser meta path pedantic]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- package_config 2.0.0 [path]
- package_info_plus 1.0.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.0 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.1.0 [flutter]
- package_info_plus_platform_interface 1.0.0 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.0 [http package_info_plus_platform_interface flutter flutter_web_plugins meta]
- package_info_plus_windows 1.0.0 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- sentry 5.0.0 [http meta stack_trace uuid]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_helper 1.1.0 [analyzer collection source_gen]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.0.0 [async crypto stream_channel]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment]
This seems like it should have been fixed in the rework a while ago.

https://github.com/FirebaseExtended/flutterfire/issues/143 https://github.com/FirebaseExtended/flutterfire/issues/2293

Is this coming from old versions of your app?

**Comment by audkar** [comment]
Dependency: `cloud_firestore 1.0.6`

**Comment by russellwheatley** [comment]
Hey @audkar, are you still seeing this bug on the latest version?

**Comment by audkar** [comment]
Sorry I don't have an answer, we decided not to proceed with Flutter

**Comment by russellwheatley** [comment]
Thanks for letting me know, closing for now. Will reopen if a user confirms this bug still persists.

**Comment by RaghuMudem** [comment]
Hi, This issues is still present with the version cloud_firestore: ^2.5.0. 
Is there any changes in latest version cloud_firestore: ^2.5.2 towards to fix the issue.

This is NOT reproducible with the devices or emulator. This can be seen in my firebase crashlytics console. I can only provide the logs from the crashlytics console. Please provide the solution to fix the issue. 

**Error screen:**
![image](https://user-images.githubusercontent.com/42538820/133414751-2f498b3a-c1ae-4fbc-9ba4-6c60b7d47dc6.png)

**Error Logs:**
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
io.flutter.plugins.firebase.firestore.streamhandler.TransactionStreamHandler.lambda$onListen$3$TransactionStreamHandler (TransactionStreamHandler.java:151)
io.flutter.plugins.firebase.firestore.streamhandler.-$$Lambda$TransactionStreamHandler$uqlCFFZFR0Oy4NBxOz-rIuvJUN8.onComplete (Unknown Source:6)
com.google.android.gms.tasks.zzj.run (com.google.android.gms:play-services-tasks@@17.1.0:4)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
com.google.android.gms.internal.tasks.zzb.dispatchMessage (com.google.android.gms:play-services-tasks@@17.1.0:6)
android.os.Looper.loop (Looper.java:246)
android.app.ActivityThread.main (ActivityThread.java:8595)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:602)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```
