### ISSUE TITLE
🐛 [firebase_storage/unknown] An unknown error occurred 'only on Android'

### ISSUE THREAD

**Issue by temzints** [FirebaseExtended/flutterfire#5960]
## Bug report

**Describe the bug**
When downloading file from firebase storage to Android phone giving IOException. iOS works perfectly fine

### Steps to reproduce

```dart
import 'package:firebase_storage/firebase_storage.dart';
import 'package:path_provider/path_provider.dart';

downloadFile(){
    FirebaseStorage storage = FirebaseStorage.instance;
    final appDocDir = await getApplicationDocumentsDirectory();

    final infoDownload = File('${appDocDir.path}/2021/01/en/info.json');

    await storage
          .ref('2021/01/en/info.json')
          .writeToFile(infoDownload);
}
```

### Expected behavior

On iOS it works and writes to app directory to path '2021/01/en/info.json'. But on Android its giving me this error message
<details><summary>Error Log</summary>

```

E/FileDownloadTask( 3329): Exception occurred during file write.  Aborting.
E/FileDownloadTask( 3329): java.io.IOException: No such file or directory
E/FileDownloadTask( 3329): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
E/FileDownloadTask( 3329): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
E/FileDownloadTask( 3329): 	at java.io.File.createNewFile(File.java:1008)
E/FileDownloadTask( 3329): 	at com.google.firebase.storage.FileDownloadTask.processResponse(FileDownloadTask.java:135)
E/FileDownloadTask( 3329): 	at com.google.firebase.storage.FileDownloadTask.run(FileDownloadTask.java:226)
E/FileDownloadTask( 3329): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7(StorageTask.java:1072)
E/FileDownloadTask( 3329): 	at com.google.firebase.storage.StorageTask$$Lambda$12.run(Unknown Source:2)
E/FileDownloadTask( 3329): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FileDownloadTask( 3329): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FileDownloadTask( 3329): 	at java.lang.Thread.run(Thread.java:919)
E/StorageException( 3329): StorageException has occurred.
E/StorageException( 3329): An unknown error occurred, please check the HTTP result code and inner exception for server response.
E/StorageException( 3329):  Code: -13000 HttpResult: 200
E/StorageException( 3329): No such file or directory
E/StorageException( 3329): java.io.IOException: No such file or directory
E/StorageException( 3329): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
E/StorageException( 3329): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
E/StorageException( 3329): 	at java.io.File.createNewFile(File.java:1008)
E/StorageException( 3329): 	at com.google.firebase.storage.FileDownloadTask.processResponse(FileDownloadTask.java:135)
E/StorageException( 3329): 	at com.google.firebase.storage.FileDownloadTask.run(FileDownloadTask.java:226)
E/StorageException( 3329): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7(StorageTask.java:1072)
E/StorageException( 3329): 	at com.google.firebase.storage.StorageTask$$Lambda$12.run(Unknown Source:2)
E/StorageException( 3329): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/StorageException( 3329): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/StorageException( 3329): 	at java.lang.Thread.run(Thread.java:919)
E/StorageException( 3329): StorageException has occurred.
E/StorageException( 3329): An unknown error occurred, please check the HTTP result code and inner exception for server response.
E/StorageException( 3329):  Code: -13000 HttpResult: 200
E/StorageException( 3329): No such file or directory
E/StorageException( 3329): java.io.IOException: No such file or directory
E/StorageException( 3329): 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
E/StorageException( 3329): 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
E/StorageException( 3329): 	at java.io.File.createNewFile(File.java:1008)
E/StorageException( 3329): 	at com.google.firebase.storage.FileDownloadTask.processResponse(FileDownloadTask.java:135)
E/StorageException( 3329): 	at com.google.firebase.storage.FileDownloadTask.run(FileDownloadTask.java:226)
E/StorageException( 3329): 	at com.google.firebase.storage.StorageTask.lambda$getRunnable$7(StorageTask.java:1072)
E/StorageException( 3329): 	at com.google.firebase.storage.StorageTask$$Lambda$12.run(Unknown Source:2)
E/StorageException( 3329): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/StorageException( 3329): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/StorageException( 3329): 	at java.lang.Thread.run(Thread.java:919)
[LOG] [firebase_storage/unknown] An unknown error occurred
```

</details>

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.1 20C69 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.3
Flutter SDK 2.0.5
downloadTest 1.0.0+1

dependencies:
- carousel_slider 4.0.0-nullsafety.0 [flutter]
- cloud_firestore 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.2
- firebase_auth 1.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 8.0.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_facebook_auth 3.3.3+1 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_html 2.0.0-nullsafety.0 [html csslib css_colors flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter]
- flutter_local_notifications 5.0.0+2 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_markdown 0.6.1 [flutter markdown meta path]
- get 4.1.4 [flutter]
- get_storage 2.0.2 [flutter get path_provider]
- intl 0.17.0 [clock path]
- markdown 4.0.0 [args charcode meta]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
- webview_flutter 2.0.4 [flutter]
- youtube_player_flutter 8.0.0 [flutter flutter_inappwebview]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- lint 1.5.3
- pedantic 1.11.0

transitive dependencies:
- args 2.1.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- chewie 1.0.0 [cupertino_icons flutter video_player wakelock]
- chewie_audio 1.2.0 [cupertino_icons flutter video_player]
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.7 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- css_colors 1.1.0 [flutter]
- csslib 0.17.0 [source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.2.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.5 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_facebook_auth_platform_interface 2.4.2 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.4.2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_inappwebview 5.3.2 [flutter]
- flutter_layout_grid 1.0.1 [flutter collection meta quiver]
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_svg 0.21.0+1 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- html 0.15.0 [csslib source_span]
- http 0.13.1 [http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- path_drawing 0.5.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- quiver 3.0.1 [matcher]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- video_player 2.1.1 [meta video_player_platform_interface video_player_web flutter flutter_test]
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.0 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock 0.4.0 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web]
- wakelock_macos 0.1.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.0 [flutter meta]
- wakelock_web 0.2.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @temzints 
Isn't this because the directories in the path for the file don't yet exist?
Does the issue happen if you just try to write the file in an existing directory?
Thank you

**Comment by temzints** [comment]
The directory on the phone doesn't exists yet, on iOS it creates the directory and downloads into it. I tried `final infoDownload = File('${appDocDir.path}/2021/01/en/info.json').create(recursive: true);` on Android still doesn't work

**Comment by markusaksli-nc** [comment]
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by temzints** [comment]
Okay I found the problem. On iOS when you call `storage.ref().writeToFile()` it creates the file and downloads it no need for `file.create()` but on Android the file must be created beforehand. The reason why it wasn't working was I had `file.exists()` checking for cached file and when I use create it checks if exists but doesn't check the length/size of the file, workaround would be `if(await file.exists())` then check the size of the file with `if(await file.length() == 0)` then on Android call `storage.ref().writeToFile(await file.create(recursive:true))`

**Comment by markusaksli-nc** [comment]
Yeah thats probably a limitation of `dart:io` method calls on both native filesystems anyway though so it's not really something we can change.
