### ISSUE TITLE
🐛 [realtime_database] nullable  type not handled properly  ( firebase_database: ^7.0.0-dev.1)

### ISSUE THREAD

**Issue by RR-Reddy** [FirebaseExtended/flutterfire#6002]
## Bug report

**Describe the bug**
Unhandled Exception: Null check operator used on a null value

### Error Log
![Screenshot 2021-05-03 at 8 03 57 AM](https://user-images.githubusercontent.com/32235964/116837179-f4a1bc00-abe6-11eb-8dd2-e8969581b8d3.png)

**getting above error in line no:42**

### issue with code  ( line no:36 and line no: 42)
![Screenshot 2021-05-03 at 8 05 14 AM](https://user-images.githubusercontent.com/32235964/116837238-2fa3ef80-abe7-11eb-97d5-1a00d87b291a.png)

**Comment by markusaksli-nc** [comment]
Hi @RR-Reddy 
Could you please provide your `flutter doctor -v`, `flutter pub deps -- --style=compact` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by RR-Reddy** [comment]
@markusaksli-nc

**Comment by markusaksli-nc** [comment]
It certainly does look weird that it is nullable but expected non-null when no checks have been performed

**Comment by Ali1Ammar** [comment]
```dart
  final res = await ref.runTransaction((mutableData) async {
      if (
          (mutableData.value as Map)["state"] == "none") {
        mutableData.value = {"state": "waiting"};
        return mutableData;
      } else {
        mutableData.value = {"state": "none"};
        return mutableData;
      }
    });
```

error log 
```
Reloaded 146 of 2375 libraries in 2,533ms.
E/MethodCallHandlerImpl( 4516): Unable to commit Snapshot update. Transaction failed.
E/MethodCallHandlerImpl( 4516): java.util.concurrent.ExecutionException: java.lang.Exception: Error code: error
E/MethodCallHandlerImpl( 4516): Error message: type 'Null' is not a subtype of type 'String'
E/MethodCallHandlerImpl( 4516): Error details: null
E/MethodCallHandlerImpl( 4516): 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@17.1.0:69)
E/MethodCallHandlerImpl( 4516): 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.1.0:33)
E/MethodCallHandlerImpl( 4516): 	at io.flutter.plugins.firebase.database.MethodCallHandlerImpl$1.doTransaction(MethodCallHandlerImpl.java:433)
E/MethodCallHandlerImpl( 4516): 	at com.google.firebase.database.core.Repo.startTransaction(Repo.java:915)
E/MethodCallHandlerImpl( 4516): 	at com.google.firebase.database.DatabaseReference$4.run(DatabaseReference.java:492)
E/MethodCallHandlerImpl( 4516): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/MethodCallHandlerImpl( 4516): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/MethodCallHandlerImpl( 4516): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/MethodCallHandlerImpl( 4516): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/MethodCallHandlerImpl( 4516): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/MethodCallHandlerImpl( 4516): 	at java.lang.Thread.run(Thread.java:919)
E/MethodCallHandlerImpl( 4516): Caused by: java.lang.Exception: Error code: error
E/MethodCallHandlerImpl( 4516): Error message: type 'Null' is not a subtype of type 'String'
E/MethodCallHandlerImpl( 4516): Error details: null
E/MethodCallHandlerImpl( 4516): 	at io.flutter.plugins.firebase.database.MethodCallHandlerImpl$1$1$1.error(MethodCallHandlerImpl.java:417)
E/MethodCallHandlerImpl( 4516): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:212)
E/MethodCallHandlerImpl( 4516): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:105)
E/MethodCallHandlerImpl( 4516): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:829)
E/MethodCallHandlerImpl( 4516): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodCallHandlerImpl( 4516): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodCallHandlerImpl( 4516): 	at android.os.Looper.loop(Looper.java:174)
E/MethodCallHandlerImpl( 4516): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodCallHandlerImpl( 4516): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodCallHandlerImpl( 4516): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodCallHandlerImpl( 4516): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 4516): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
[38;5;244mE/flutter ( 4516): #0      new DataSnapshot._fromJson[39;49m
[38;5;244mE/flutter ( 4516): #1      DatabaseReference.runTransaction.toTransactionResult[39;49m
[38;5;244mE/flutter ( 4516): #2      DatabaseReference.runTransaction.<anonymous closure>[39;49m
[38;5;244mE/flutter ( 4516): #3      _rootRunUnary (dart:async/zone.dart:1362:47)[39;49m
[38;5;244mE/flutter ( 4516): #4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)[39;49m
[38;5;244mE/flutter ( 4516): #5      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)[39;49m
[38;5;244mE/flutter ( 4516): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)[39;49m
[38;5;244mE/flutter ( 4516): #7      Future._propagateToListeners (dart:async/future_impl.dart:733:32)[39;49m
[38;5;244mE/flutter ( 4516): #8      Future._completeWithValue (dart:async/future_impl.dart:539:5)[39;49m
[38;5;244mE/flutter ( 4516): #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:254:13)[39;49m
[38;5;244mE/flutter ( 4516): #10     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)[39;49m
E/flutter ( 4516): <asynchronous suspension>
E/flutter ( 4516):
```

using firebase_database: ^7.0.0-dev.2

**Comment by Ali1Ammar** [comment]
using firebase_database: ^7.0.0-dev.2
  code sample :

   ```dart
    final FirebaseDatabase database = FirebaseDatabase.instance;
    final ref = database.reference().child("test");
    await ref.runTransaction((mutableData) async {
      mutableData.value={"v":"vala"};
      return mutableData;
    });
```
error log
```
Reloaded 146 of 2375 libraries in 2,305ms.
E/flutter ( 4516): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
[38;5;244mE/flutter ( 4516): #0      new DataSnapshot._fromJson[39;49m
[38;5;244mE/flutter ( 4516): #1      DatabaseReference.runTransaction.toTransactionResult[39;49m
[38;5;244mE/flutter ( 4516): #2      DatabaseReference.runTransaction.<anonymous closure>[39;49m
[38;5;244mE/flutter ( 4516): #3      _rootRunUnary (dart:async/zone.dart:1362:47)[39;49m
[38;5;244mE/flutter ( 4516): #4      _CustomZone.runUnary (dart:async/zone.dart:1265:19)[39;49m
[38;5;244mE/flutter ( 4516): #5      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)[39;49m
[38;5;244mE/flutter ( 4516): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)[39;49m
[38;5;244mE/flutter ( 4516): #7      Future._propagateToListeners (dart:async/future_impl.dart:733:32)[39;49m
[38;5;244mE/flutter ( 4516): #8      Future._completeWithValue (dart:async/future_impl.dart:539:5)[39;49m
[38;5;244mE/flutter ( 4516): #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:254:13)[39;49m
[38;5;244mE/flutter ( 4516): #10     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)[39;49m
E/flutter ( 4516): <asynchronous suspension>
E/flutter ( 4516):
```

data is update in firebase

**Comment by RR-Reddy** [comment]
This issue is blocking sound null safety migration or running app with sound null safety feature

**Comment by Ali1Ammar** [comment]
> This issue is blocking sound null safety migration or running app with sound null safety feature

@RR-Reddy 
clone the repo and add to if condition in line 41
&& childsKey != null

 i use it for developing only i don't know if it will case any problems in future

**Comment by rrousselGit** [comment]
I was able to reproduce the issue and pushed a fix. Thanks for the report!

**Comment by RR-Reddy** [comment]
Great
