### ISSUE TITLE
🐛 [firebase_messaging] Bad state: Cannot add new events while doing an addStream

### ISSUE THREAD

**Issue by sm2017** [FirebaseExtended/flutterfire#6009]
## Bug report

**Describe the bug**
I listen to `onMessage`, `onMessageOpenedApp` and `onTokenRefresh` once user logged in and cancel listening once user logged out, when a user logged in then out and again logged in I call listener twice, in the second listening of   `onMessage` and `onMessageOpenedApp` (`onTokenRefresh` is OK and has no bug) I get the following error

```
I/flutter (15168): Bad state: Cannot add new events while doing an addStream
I/flutter (15168): #0      _BroadcastStreamController.addStream (dart:async/broadcast_stream_controller.dart:276:24)
I/flutter (15168): #1      Stream.pipe (dart:async/stream.dart:698:27)
I/flutter (15168): #2      FirebaseMessaging._onMessageController.<anonymous closure> (package:firebase_messaging/src/messaging.dart:61:21)
I/flutter (15168): #3      _runGuarded (dart:async/stream_controller.dart:773:24)
I/flutter (15168): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
I/flutter (15168): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
I/flutter (15168): #6      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
```

```
I/flutter (15168): Bad state: Cannot add new events while doing an addStream
I/flutter (15168): #0      _BroadcastStreamController.addStream (dart:async/broadcast_stream_controller.dart:276:24)
I/flutter (15168): #1      Stream.pipe (dart:async/stream.dart:698:27)
I/flutter (15168): #2      FirebaseMessaging._onMessageOpenedAppController.<anonymous closure> (package:firebase_messaging/src/messaging.dart:79:30)
I/flutter (15168): #3      _runGuarded (dart:async/stream_controller.dart:773:24)
I/flutter (15168): #4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207:7)
I/flutter (15168): #5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:786:19)
I/flutter (15168): #6      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
```

### Steps to reproduce

```dart
Future<void> _firebaseMessagingForegroundHandler(RemoteMessage message) async {};
void _onMessageOpenedApp(RemoteMessage message) {};

Future<void>test() async {
  StreamSubscription<RemoteMessage> _onMessageSubscription;
  StreamSubscription<RemoteMessage> _onMessageOpenedAppSubscription;
  
  _onMessageSubscription = FirebaseMessaging.onMessage.listen(_firebaseMessagingForegroundHandler);
  _onMessageOpenedAppSubscription = FirebaseMessaging.onMessageOpenedApp.listen(_onMessageOpenedApp);
  
  await Future.delayed(Duration(seconds: 2));
  await _onMessageSubscription.cancel();
  await _onMessageOpenedAppSubscription.cancel();
  await Future.delayed(Duration(seconds: 2));

  _onMessageSubscription = FirebaseMessaging.onMessage.listen(_firebaseMessagingForegroundHandler);
  _onMessageOpenedAppSubscription = FirebaseMessaging.onMessageOpenedApp.listen(_onMessageOpenedApp);
}
```

### Expected behavior

I think nothing it wrong and we can listen multiple time as `StreamController` is `broadcast`

---

## Additional context

Nothing

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.18363.1500], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.0 [flutter meta]
- firebase_analytics_web 0.3.0 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.0.2 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 2.1.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.6 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]

```

</details>

---

**Comment by markusaksli-nc** [comment]
Reproducible with `firebase_messaging: ^9.1.3`
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.3.0-1.0.pre.205, on Microsoft Windows [Version 10.0.19041.928], locale et-EE)
    • Flutter version 2.3.0-1.0.pre.205 at C:\Development\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 96e4b47f5d (24 hours ago), 2021-05-02 07:24:01 -0700
    • Engine revision 3e578c6e0d
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119
    • Flutter plugin version 55.1.1
    • Dart plugin version 201.9380
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.928]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!
```
</details>

**Comment by acoutts** [comment]
Seems like if you access the stream with `.asBroadcastStream()` then it doesn't throw the errors:

```dart
    _firebaseMessagingOnMessageSubscription = FirebaseMessaging.onMessage
        .asBroadcastStream()
        .listen(onMessage);

    _firebaseMessagingOnResumeSubscription = FirebaseMessaging
        .onMessageOpenedApp
        .asBroadcastStream()
        .listen(onResume);
```

**Comment by sm2017** [comment]
It's defined as broadcast in source https://github.com/FirebaseExtended/flutterfire/blob/4594db947acb9a94fc802cf30dc94af7573548ac/packages/firebase_messaging/firebase_messaging/lib/src/messaging.dart#L57
