### ISSUE TITLE
🐛 [CLOUD FUNCTION] Email Undefined (UNAUTHENTICATED)

### ISSUE THREAD

**Issue by gOzaru** [FirebaseExtended/flutterfire#6078]
## Bug report

**Describe the bug**
Derived data from snapshot returns "Email" Undefined. 
The correct way and new ones to derived data from snapshot is: `snapshot.email` 
It is not `snapshot.data().email`, right? 
But this once again always return "Undefined Email and UID"'
Overall, it says: UNAUTHENTICATED. 
I had set permission to allow AllUsers for Cloud Functions Invoker. 

### Firebase Version 9.10.2
I just updated to latest Firebase version using this command `npm install firebase-tools`
Pubdev in Flutter are: 
- cloud_functions: ^1.0.6
- cloud_firestore: ^1.0.5
- firebase_auth: ^1.1.3
- firebase_core: ^1.0.3

### Steps to reproduce
1. Use Firestore for Cloud Functions to create new data in Firestore using onCreate(async (snaps, context))
2. Set this function in Cloud Functions to allow AllUsers
3. Call it from Flutter using callable method
3. Run and try to sign up as a new User

### Expected behavior
It should get the email data from there. 

This is the function I used in node.js
===============================
```
exports.addServerUser = functions.firestore.document("Budiman/Server/Users/{uid}").onCreate(async (snaps, context) => {
  const uid = context.params.uid;
  const email = snaps.email;
  const name = snaps.name;

  const device = snaps.device;
  const type = snaps.type;
  const model = snaps.model;
  const version = snaps.version;

  const addUser = await adminDB.collection("Budiman/Server/Users").doc(uid).set({
    "name": name,
    "email": email,
    "uid": uid,
    "role": role,
    "device_id": device,
  });

  return Promise.all(addUser).then(() => {
    return {
      status: "Success",
      code: code,
    };
  }).catch((error) => {
    return {
      status: "Error",
      message: "Error adding User: " + error,
    };
  });
```
###This is a function I used to call in Flutter
```
    Map<String, dynamic> userData = {
      "name": name,
      "email": email,
      "uid": uid,
      "device_id": deviceID,
      "type": deviceType,
      "model": deviceModel,
      "version": deviceVersion,
    };

    HttpsCallable callable = functions.httpsCallable('addServerUser');
    await callable.call(userData).then((response) async {
      if (response.data['status'] == 'Success') {
        print("Added a new User to database");
        print("$deviceID");
        print("$deviceModel");
        print("$deviceType");
        print("Version $deviceVersion");
        print("User is using a physical device");
        if (response.data['code'] == 1) {
          await welcomeUser(1);
        } else if (response.data['code'] == 2) {
          await welcomeUser(2);
        } else if (response.data['code'] == 3) {
          await welcomeUser(3);
        }
      } else if (response.data['status'] == 'Fail') {
        print("Unauthorized User is trying to access the App");
        await unAuthorizedUser();
      }
    });
```
---
### Screenshot
[Link to screenshot](https://pasteboard.co/K0UoD5I.jpg)
---
---
### Flutter doctor
<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.5 at G:\Flutter
    • Framework revision adc687823a (3 weeks ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at G:\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = G:\SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.56.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • Redmi 6A (mobile) • 148e971a7d2b • android-arm    • Android 9 (API 28)
    • Chrome (web)      • chrome       • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge         • web-javascript • Microsoft Edge 89.0.774.68

• No issues found!
```
</details>

---

### Flutter dependencies
<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.3
Flutter SDK 2.0.5
server_had 1.0.0+1

dependencies:
- audio_service 0.17.0 [audio_session rxdart flutter_isolate flutter_cache_manager js flutter flutter_web_plugins]
- cloud_firestore 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 1.0.6 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.2
- device_info 2.0.0 [flutter device_info_platform_interface]
- file_picker 3.0.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_auth 1.1.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 8.0.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_screenutil 5.0.0 [flutter]
- flutter_svg 0.21.0+1 [flutter meta path_drawing vector_math xml]
- font_awesome_flutter 9.0.0 [flutter]
- get 4.1.4 [flutter]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- just_audio 0.7.4 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- money2 2.0.3 [intl meta]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- async 2.5.0 [collection]
- audio_session 0.1.0 [flutter flutter_web_plugins rxdart]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.7 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.3 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.5 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.5 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_cache_manager 3.0.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_isolate 2.0.0 [flutter uuid]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.13.2 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- intl 0.17.0 [clock path]
- js 0.6.3
- just_audio_platform_interface 3.0.0 [flutter plugin_platform_interface]
- just_audio_web 0.3.1 [just_audio_platform_interface flutter flutter_web_plugins]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- path_drawing 0.5.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0 [vector_math meta]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- quiver 3.0.1 [matcher]
- rxdart 0.26.0
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
```
</details>

---

**Comment by markusaksli-nc** [comment]
Hi @gOzaru 
Could you please paste the error logs?
Please refrain from using screenshots in general as they make referencing or searching for the issue much harder.
Thank you

**Comment by gOzaru** [comment]
```
Exception has occurred.
FirebaseFunctionsException ([firebase_functions/unauthenticated] UNAUTHENTICATED

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
#2      MethodChannelHttpsCallable.call (package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart:22:24)
<asynchronous suspension>
#3      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:34:37)
<asynchronous suspension>
#4      FirebaseController.createNewUser.<anonymous closure> (package:server_had/controller/firebase.dart)
<asynchronous suspension>
)
```

**Comment by gOzaru** [comment]
Does this error come from a wrong way to derive the data parsed in the Cloud Function? 
As I had set permission to all functions to allow AllUsers using Cloud Function Invoker role. 
I wondered why I can't get the value from data parsed???
Is this correct way to get data for Cloud Firestore trigger onCreate?
  ```
  const uid = context.params.uid;
  const email = snaps.email;
  const name = snaps.name;
```

**Comment by gOzaru** [comment]
I just trying the Cloud Function Testing Mode: 
These are the results of the parsing data: 
```
functions.firestore.document("Felix/Server/Users/{uid}").onCreate(async (snaps, context) => {
	const uid = context.auth.uid; //this is FAIL
	const uid = snaps.uid; //this is FAIL
	const uid = context.params.uid; //this is FAIL too
	
	const code = snaps.data["code"]; //this is FAIL
	const code = snaps.code; //this is FAIL too
	const code = snaps.data().code //this is FAIL too
}
```
What actually happen to this Cloud Functions???

**Comment by gOzaru** [comment]
I used a debug on my Cloud Functions, and found out this error: 
```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message>
<StringToSign>GET 1620709828 /gcf-upload-us-central1-e5bde4ee-1b4a-4399-a2ce-41cd77a659d2/10e792cf-7ee5-4ae1-a107-aa5f85b9d7ad.zip</StringToSign>
</Error>
```

**Comment by gOzaru** [comment]
It seems if the Credential from the Custom Token has any problem, then the parsed data inside the context will be undefined:
```
functions.firestore.document("Budiman/Server/Users/{uid}").onCreate(async (snaps, context) {

});
```
I hope I can get the way to solve this Custom Token Authorization. 
Hopefully there is a tutorial about this.
