### ISSUE TITLE
core.dart.lib.js:42:101 Flutter web build - blank page and stops on web_entrypoint.dart file

### ISSUE THREAD

**Issue by mklepaczko** [FirebaseExtended/flutterfire#6110]
## Bug report

I'm trying to build a Flutter web for my app project.

After passing "Flutter Create ." and trying to run in Chrome it shows a blank page and stops on the web_entrypoint.dart file.
Project was create about a year ago. Same problem on a second project I also create about 6 months ago.
I created a new test project now and the problem does not appear.

![Zrzut ekranu 2021-05-7 o 17 13 58](https://user-images.githubusercontent.com/52317336/117812245-db8db080-b261-11eb-8e92-2638106e9e14.png)

flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale pl-PL)
    • Flutter version 2.0.6 at /users/michalklepaczko/flutter
    • Framework revision 1d9032c7e1 (9 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/michalklepaczko/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.56.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • SM T515 (mobile) • R52MB0NQSPD • android-arm    • Android 10 (API 29)
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 90.0.4430.93

• No issues found!

 I recently updated all the project to null safety. Here is the info from the flutter run -d chrome -v

[+25506 ms] Waiting for connection from debug service on Chrome... (completed in 29,8s)
[        ] Synced 36.9MB.
[        ] <- accept
[        ] Caching compiled dill
[ +395 ms] Using Google Chrome 90.0.4430.93 

[+11840 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:53288/devtools/browser/dcdcb7ce-67c1-48dc-a6fc-7b36b9c67b2c
[+1219 ms] DwdsInjector: Received request for entrypoint at http://localhost:53259/main_module.bootstrap.js
[  +17 ms] MetadataProvider: Loading debug metadata...
[  +25 ms] MetadataProvider: Loaded debug metadata
[  +13 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:53259/main_module.bootstrap.js
[+4467 ms] DevHandler: Debug service listening on ws://127.0.0.1:53310/xxdkUe_Bg4M=/ws

[  +14 ms] Debug service listening on ws://127.0.0.1:53310/xxdkUe_Bg4M=/ws
[   +1 ms] 💪 Running with sound null safety 💪
[   +4 ms] 🔥  To hot restart changes while running, press "r" or "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[  +55 ms] TypeError: Cannot read property 'app' of undefined
               at Object.app$ [as app] (http://localhost:53259/packages/firebase_core_web/src/interop/core.dart.lib.js:42:101)
               at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:53259/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:865:64)
               at Function.registerWith (http://localhost:53259/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:788:73)
               at Object.registerPlugins (http://localhost:53259/packages/quiqer_service_provider/generated_plugin_registrant.dart.lib.js:37:46)
               at main (http://localhost:53259/web_entrypoint.dart.lib.js:41:35)
               at main.next (<anonymous>)
               at runBody (http://localhost:53259/dart_sdk.js:37228:34)
               at Object._async [as async] (http://localhost:53259/dart_sdk.js:37259:7)
               at main$ (http://localhost:53259/web_entrypoint.dart.lib.js:40:18)
               at http://localhost:53259/main_module.bootstrap.js:19:10
               at Array.forEach (<anonymous>)
               at window.$dartRunMain (http://localhost:53259/main_module.bootstrap.js:18:32)
               at <anonymous>:1:8
               at Object.runMain (http://localhost:53259/dwds/src/injected/client.js:8656:21)
               at http://localhost:53259/dwds/src/injected/client.js:22068:19
               at _wrapJsFunctionForAsync_closure.$protected (http://localhost:53259/dwds/src/injected/client.js:3830:15)
               at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:53259/dwds/src/injected/client.js:10905:12)
               at Object._asyncStartSync (http://localhost:53259/dwds/src/injected/client.js:3794:20)
               at main__closure1.$call$body$main__closure (http://localhost:53259/dwds/src/injected/client.js:22080:16)
               at main__closure1.call$1 (http://localhost:53259/dwds/src/injected/client.js:22007:19)
               at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:53259/dwds/src/injected/client.js:4153:16)
               at _CustomZone.runUnary$2$2 (http://localhost:53259/dwds/src/injected/client.js:12136:39)
               at _CustomZone.runUnaryGuarded$1$2 (http://localhost:53259/dwds/src/injected/client.js:12068:14)
               at _ControllerSubscription._sendData$1 (http://localhost:53259/dwds/src/injected/client.js:11697:19)
               at _DelayedData.perform$1 (http://localhost:53259/dwds/src/injected/client.js:11849:59)
               at _PendingEvents_schedule_closure.call$0 (http://localhost:53259/dwds/src/injected/client.js:11898:14)
               at Object._microtaskLoop (http://localhost:53259/dwds/src/injected/client.js:3990:24)
               at StaticClosure._startMicrotaskLoop (http://localhost:53259/dwds/src/injected/client.js:3996:11)
               at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:53259/dwds/src/injected/client.js:10774:9)
               at invokeClosure (http://localhost:53259/dwds/src/injected/client.js:1250:26)
               at MutationObserver.<anonymous> (http://localhost:53259/dwds/src/injected/client.js:1269:18)

**Comment by markusaksli-nc** [comment]
Hi @mklepaczko 
What does this have to do with Firebase?
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? Does some firebase code at startup trigger the exception?
Thank you

**Comment by markusaksli-nc** [comment]
It looks like the error is coming during plugin registration for the firestore web plugin. Have you followed all of the setup steps?
https://firebase.flutter.dev/docs/installation/web
https://firebase.flutter.dev/docs/firestore/overview#3-web-only-add-the-sdk

**Comment by mklepaczko** [comment]
Yes I did. Here is my index.html:

<!DOCTYPE html>
<html>
<head>
  
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="xxxxx">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>xxxxx</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>


<script src="/__/firebase/8.5.0/firebase-app.js"></script>


     <script src="/__/firebase/8.5.0/firebase-firestore.js"></script>
     <script src="/__/firebase/8.5.0/firebase-analytics.js"></script>
     <script src="/__/firebase/8.5.0/firebase-messaging.js"></script>
     <script src="/__/firebase/8.5.0/firebase-storage.js"></script>
     <script src="/__/firebase/8.5.0/firebase-auth.js"></script>


<script src="/__/firebase/init.js"></script>

  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>

I also tried with the CDN and firebaseConfig map but same result

**Comment by markusaksli-nc** [comment]
Why do the sdk refs start with `/__/`?
The SDKs should be from
```
  <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-messaging.js"></script>
```

Also the official tested and supported version of the firebase web SDKs is `8.4.1`. You can use a newer version if you want but it isn't tested yet.

**Comment by mklepaczko** [comment]
Well... it's all from the official firebase docs...

https://firebase.google.com/docs/web/setup

OK I will switch and try again.

**Comment by markusaksli-nc** [comment]
Those are from the native firebase web app setup. Please refer to the FlutterFire documentation whenever you setup the flutter implementation of firebase packages.
https://firebase.flutter.dev/docs/overview

**Comment by mklepaczko** [comment]
Well, this is quite confusing then, especially with the Firebase console info.
Updating to version 8.4.1 and using CDN solved the problem.
Thanks for your help!
