### ISSUE TITLE
🐛 [firebase_auth] `IncompatibleClassChangeError`

### ISSUE THREAD

**Issue by ItzNotABug** [FirebaseExtended/flutterfire#6148]
## Bug report

**Describe the bug**
As soon as the `verifyPhoneNumber` triggers a reCaptcha test (sometimes not required),\
the app crashes instantly with the below stack-trace:
```
FATAL EXCEPTION: GoogleApiHandler
E/AndroidRuntime(10822): Process: com.app.test, PID: 10822
E/AndroidRuntime(10822): java.lang.IncompatibleClassChangeError: Found class com.google.android.gms.auth.api.phone.SmsRetrieverClient, but interface was expected (declaration of 'com.google.android.gms.auth.api.phone.SmsRetrieverClient' appears in /data/app/~~O1OQSVswb36VloNHm5AcPw==/com.app.test-OlpMv3pGUGBlcQXTIRaXfg==/base.apk)
E/AndroidRuntime(10822): 	at com.google.android.gms.internal.firebase-auth-api.zzvu.zzb(com.google.firebase:firebase-auth@@21.0.0:15)
E/AndroidRuntime(10822): 	at com.google.android.gms.internal.firebase-auth-api.zztw.zzu(com.google.firebase:firebase-auth@@21.0.0:13)
E/AndroidRuntime(10822): 	at com.google.android.gms.internal.firebase-auth-api.zzto.zzd(com.google.firebase:firebase-auth@@21.0.0:3)
E/AndroidRuntime(10822): 	at com.google.android.gms.internal.firebase-auth-api.zztn.accept(Unknown Source:6)
E/AndroidRuntime(10822): 	at com.google.android.gms.common.api.internal.zacj.doExecute(com.google.android.gms:play-services-base@@17.1.0:2)
E/AndroidRuntime(10822): 	at com.google.android.gms.common.api.internal.zaf.zac(com.google.android.gms:play-services-base@@17.1.0:6)
E/AndroidRuntime(10822): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.1.0:167)
E/AndroidRuntime(10822): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(com.google.android.gms:play-services-base@@17.1.0:139)
E/AndroidRuntime(10822): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.1.0:105)
E/AndroidRuntime(10822): 	at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@17.1.0:145)
E/AndroidRuntime(10822): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10822): 	at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:8)
E/AndroidRuntime(10822): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(10822): 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Steps to reproduce

1. Input Phone Number & fire `verifyPhoneNumber`

### Expected behavior

Should not crash

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3.1 20E241 darwin-x64, locale en-IN)
    • Flutter version 2.0.6 at /Users/itznotabug/FlutterCore/flutter
    • Framework revision 1d9032c7e1 (2 weeks ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/itznotabug/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 90.0.4430.212

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.3
Flutter SDK 2.0.6
app 1.0.0+1

dependencies:
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 2.1.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- country_code_picker 2.0.1 [flutter modal_bottom_sheet collection universal_platform]
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.3
- device_info 2.0.0 [flutter device_info_platform_interface]
- expandable_page_view 1.0.4 [flutter]
- faker 1.3.0
- firebase_auth 1.1.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_spinkit 5.0.0 [flutter]
- flutter_staggered_grid_view 0.4.0 [flutter]
- font_awesome_flutter 9.0.0 [flutter]
- get 4.1.4 [flutter]
- google_sign_in 5.0.3 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- modal_progress_hud 0.1.3 [flutter]
- pin_code_fields 7.1.0 [flutter]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 3.0.0 [flutter meta]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.0.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.0.1 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.2.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.0.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- modal_bottom_sheet 2.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- quiver 3.0.1 [matcher]
- rxdart 0.26.0
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- universal_platform 1.0.0-nullsafety
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
```

</details>

---

**Comment by harrowmykel** [comment]
I am currently expriencing the same thing. Does anyone know how to fix this?

**Comment by markusaksli-nc** [comment]
Haven't been able to reproduce this with the official example

**Comment by ItzNotABug** [comment]
@markusaksli-nc Encountered this crash on a MI A2, Samsung A70 as well as on the Android Emulator on 11.

**Comment by harrowmykel** [comment]
Hi @ItzNotABug  I believe this bug has been fixed in the latest google service version.
Update your android/build.gradle with

buildscript {
    repositories {        
        //...
        google()
    }

    dependencies {
        //...
        classpath 'com.google.gms:google-services:4.3.8'
    }
}

**Comment by ItzNotABug** [comment]
Thanks for the update @harrowmykel\
It was indeed a bug in the `phone-auth` library, more info. [here](https://firebase.google.com/support/release-notes/android#auth_v21-0-1)\
This seems to be fixed in the latest `firebase-bom:28.0.1` update.

Closing this issue now.

**Comment by markusaksli-nc** [comment]
Why are you setting the native android sdk version manually? The FlutterFire plugins already set this version internally.
https://github.com/FirebaseExtended/flutterfire/blob/4b893b13664f39643fb8cd3d42c5e8d260e9fd82/packages/firebase_core/firebase_core/android/gradle.properties#L2

If at all possible you should avoid overriding this manually because it will lead to issues like this.

Also using `com.google.gms:google-services:4.3.8` instead of the recommended `com.google.gms:google-services:4.3.3` has also been known to cause issues before. Please try to follow the official tested and supported versions mentioned in the official documentation at https://firebase.flutter.dev/docs/installation/android.

**Comment by ItzNotABug** [comment]
@markusaksli-nc I'm not sure why the internally defined version did not properly update the firebase bom version.

Might have been the issue that I had not directly added ` firebase_core` as the dependency.
But afaik, the transitive should've added that.

Anyway, thanks for the info.
