### ISSUE TITLE
tried to call a non-function, such as null: 'dart.global.firebase.auth'

### ISSUE THREAD

**Issue by SavanRajyaguru** [FirebaseExtended/flutterfire#6158]
Hi, I am collage Student and I working on Flutter web project. I was trying to login with Email or Password and Google authentication but its shows me this error.

> ### **flutter run -d chrome --verbose**

```
[ +199 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +213 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] d72bfb8d073c6cf943a6637290dd3f8cdad11831
[   +2 ms] executing: [C:\src\flutter/] git tag --points-at d72bfb8d073c6cf943a6637290dd3f8cdad11831
[ +311 ms] Exit code 0 from: git tag --points-at d72bfb8d073c6cf943a6637290dd3f8cdad11831
[   +1 ms] 2.3.0-0.1.pre
[  +15 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +140 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[   +1 ms] executing: [C:\src\flutter/] git ls-remote --get-url origin
[ +131 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +230 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[ +135 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] dev
[ +151 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +115 ms] executing: C:\Users\Savan Rajyaguru\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +109 ms] List of devices attached
[  +18 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +291 ms] Skipping pub get: version match.
[  +58 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.1.4\
[  +20 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.2\
[   +6 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.1.1\
[   +8 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.3\
[   +6 ms] Found plugin google_sign_in at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.0.3\
[   +8 ms] Found plugin google_sign_in_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0\
[  +24 ms] Found plugin path_provider_linux at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[  +10 ms] Found plugin path_provider_windows at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +17 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +8 ms] Found plugin shared_preferences_linux at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +5 ms] Found plugin shared_preferences_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[  +14 ms] Found plugin shared_preferences_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +5 ms] Found plugin shared_preferences_windows at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[ +523 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.1.4\
[   +4 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.2\
[   +2 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.1.1\
[   +2 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.3\
[   +2 ms] Found plugin google_sign_in at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.0.3\
[   +3 ms] Found plugin google_sign_in_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0\
[   +5 ms] Found plugin path_provider_linux at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +2 ms] Found plugin path_provider_windows at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[   +5 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +2 ms] Found plugin shared_preferences_linux at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +2 ms] Found plugin shared_preferences_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +4 ms] Found plugin shared_preferences_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +3 ms] Found plugin shared_preferences_windows at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[  +32 ms] Generating S:\Firebase Flutter
App\discortweb\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +296 ms] Launching lib\main.dart on Chrome in debug mode...
[ +241 ms] Updating assets
[ +376 ms] Manifest contained wildcard assets. Inserting missing file into build graph to force rerun. for more
information see #56466.
[  +16 ms] Waiting for connection from debug service on Chrome...
[  +42 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.1.4\
[  +10 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.2\
[   +9 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.1.1\
[  +11 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.3\
[   +5 ms] Found plugin google_sign_in at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.0.3\
[   +6 ms] Found plugin google_sign_in_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0\
[  +18 ms] Found plugin path_provider_linux at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[  +12 ms] Found plugin path_provider_windows at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +15 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +7 ms] Found plugin shared_preferences_linux at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[  +11 ms] Found plugin shared_preferences_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +7 ms] Found plugin shared_preferences_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +4 ms] Found plugin shared_preferences_windows at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[  +70 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-1.1.4\
[   +5 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-1.1.2\
[   +3 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.1.1\
[   +5 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.3\
[   +3 ms] Found plugin google_sign_in at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-5.0.3\
[   +5 ms] Found plugin google_sign_in_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in_web-0.10.0\
[  +11 ms] Found plugin path_provider_linux at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.0.0\
[   +7 ms] Found plugin path_provider_windows at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.1\
[  +10 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-2.0.5\
[   +3 ms] Found plugin shared_preferences_linux at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_linux-2.0.0\
[   +4 ms] Found plugin shared_preferences_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-2.0.0\
[   +7 ms] Found plugin shared_preferences_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-2.0.0\
[   +4 ms] Found plugin shared_preferences_windows at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_windows-2.0.0\
[ +292 ms] <- reset
[  +21 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\src\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
--experimental-emit-debug-metadata -DFLUTTER_WEB_AUTO_DETECT=true --output-dill
C:\Users\SAVANR~1\AppData\Local\Temp\flutter_tools.d48fc00e\flutter_tool.5b1a2061\app.dill --libraries-spec
file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages S:\Firebase Flutter
App\discortweb\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts
--track-widget-creation --filesystem-root
C:\Users\SAVANR~1\AppData\Local\Temp\flutter_tools.d48fc00e\flutter_tools.ca335e30 --filesystem-scheme org-dartlang-app
--initialize-from-dill build\b1b715402d823b7fd5c2b68d2edcb2ce.cache.dill.track.dill --platform
file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk_sound.dill --sound-null-safety
[  +41 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+27808 ms] Waiting for connection from debug service on Chrome... (completed in 28.5s)
[   +2 ms] Synced 30.4MB.
[   +1 ms] <- accept
[   +1 ms] Caching compiled dill
[+1452 ms] [CHROME]:
[  +10 ms] [CHROME]:DevTools listening on ws://127.0.0.1:52832/devtools/browser/5f06e39f-d285-4341-a565-58702a28d611
[+1201 ms] DwdsInjector: Received request for entrypoint at http://localhost:52805/main_module.bootstrap.js
[  +13 ms] MetadataProvider: Loading debug metadata...
[  +29 ms] MetadataProvider: Loaded debug metadata (sound null safety)
[  +21 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:52805/main_module.bootstrap.js
[+12299 ms] ChromeProxyService: Initializing expression compiler for main_module.bootstrap.js with sound null safety:
true
[  +78 ms] DevHandler: Debug service listening on ws://127.0.0.1:52861/B6ROwsayAYw=/ws

[  +37 ms] This app is linked to the debug service: ws://127.0.0.1:52861/B6ROwsayAYw=/ws
[  +19 ms] Debug service listening on ws://127.0.0.1:52861/B6ROwsayAYw=/ws
[   +2 ms]  Running with sound null safety 
[   +8 ms]   To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[   +3 ms] An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:52861/B6ROwsayAYw=
[+2432 ms] The Flutter DevTools debugger and profiler on Chrome is available at:
                    http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A52861%2FB6ROwsayAYw%3D
[+4515 ms] TypeError: dart.global.firebase.auth is not a function
                        at Object.getAuthInstance
(http://localhost:52805/packages/firebase_auth_web/src/interop/auth.dart.lib.js:830:70)
                        at new firebase_auth_web.FirebaseAuthWeb.new
                        (http://localhost:52805/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:412:27)
                        at firebase_auth_web.FirebaseAuthWeb.__.delegateFor
                        (http://localhost:52805/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:67:14)
                        at Function.instanceFor
                        (http://localhost:52805/packages/firebase_auth_platform_interface/src/types.dart.lib.js:1364:77)
                        at firebase_auth.FirebaseAuth.__.get [_delegate]
                        (http://localhost:52805/packages/firebase_auth/firebase_auth.dart.lib.js:88:135)
                        at firebase_auth.FirebaseAuth.__.get currentUser [as currentUser]
                        (http://localhost:52805/packages/firebase_auth/firebase_auth.dart.lib.js:100:15)
                        at getUser (http://localhost:52805/packages/discortweb/Module/Authentication.dart.lib.js:132:39)
                        at getUser.next (<anonymous>)
                        at http://localhost:52805/dart_sdk.js:37388:33
                        at _RootZone.runUnary (http://localhost:52805/dart_sdk.js:37259:59)
                        at _FutureListener.thenAwait.handleValue (http://localhost:52805/dart_sdk.js:32515:29)
                        at handleValueCallback (http://localhost:52805/dart_sdk.js:33042:49)
                        at Function._propagateToListeners (http://localhost:52805/dart_sdk.js:33080:17)
                        at _Future.new.[_completeWithValue] (http://localhost:52805/dart_sdk.js:32928:23)
                        at async._AsyncCallbackEntry.new.callback (http://localhost:52805/dart_sdk.js:32949:35)
                        at Object._microtaskLoop (http://localhost:52805/dart_sdk.js:37511:13)
                        at _startMicrotaskLoop (http://localhost:52805/dart_sdk.js:37517:13)
                        at http://localhost:52805/dart_sdk.js:33288:9
```

> ### **index.js**

```
<!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>

  <!-- TODO: Add SDKs for Firebase products that you want to use
       https://firebase.google.com/docs/web/setup#available-libraries -->

  <script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
      //webinfo
    };
    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>

```

**When I press any button like Login or Sign up then it shows me this error**

```
[+32086 ms] NoSuchMethodError: tried to call a non-function, such as null: 'dart.global.firebase.auth'
[   +2 ms] null
```

**Comment by markusaksli-nc** [comment]
Hi @SavanRajyaguru 
Please follow the official documentation on how to setup the packages for the platform you are using.
https://firebase.flutter.dev/docs/installation/web
https://firebase.flutter.dev/docs/auth/overview#3-web-only-add-the-sdk
Thank you
