### ISSUE TITLE
flutterfirebasecoreplugin-java-uses-or-overrides-a-deprecated-api error with latest flutter version 2.2.0 and latest Apis

### ISSUE THREAD

**Issue by akmichael** [FirebaseExtended/flutterfire#6207]
I am getting "flutterfirebasecoreplugin-java-uses-or-overrides-a-deprecated-api" error. Even though I have new stable flutter version and latest firebase plugins. I also tried (**_flutter pub get, flutter pub upgrade, flutter clean_**) commands as suggested in other stackoverflow queries but didnt help. How to fix this issue?

project configurations

build.grade

 minSdkVersion 27
 targetSdkVersion 30
 compileSdkVersion 30
 multiDexEnabled true

Flutter version **2.2.0**

dependencies:

 firebase_core: ^1.2.0
 firebase_messaging: ^10.0.0
 flutter_local_notifications: ^5.0.0+4

Error
```

D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java:71: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(PluginRegistry.Registrar registrar) {
                                                ^
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java:189: warning: [deprecation] setDataCollectionDefaultEnabled(boolean) in FirebaseApp has been deprecated
          firebaseApp.setDataCollectionDefaultEnabled(enabled);
                     ^
2 warnings
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.0\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingPlugin.java:32: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.0\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingBackgroundExecutor.java:42: warning: [deprecation] PluginRegistrantCallback in PluginRegistry has been deprecated
  private static io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
                                                        ^
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.0\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingBackgroundExecutor.java:62: warning: [deprecation] PluginRegistrantCallback in PluginRegistry has been deprecated
      io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback callback) {
                                             ^
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.0\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingBackgroundExecutor.java:169: warning: [deprecation] FlutterMain in io.flutter.view has been deprecated
          io.flutter.view.FlutterMain.startInitialization(ContextHolder.getApplicationContext());
                         ^
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.0\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingBackgroundExecutor.java:170: warning: [deprecation] FlutterMain in io.flutter.view has been deprecated
          io.flutter.view.FlutterMain.ensureInitializationCompleteAsync(
                         ^
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.0\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingBackgroundExecutor.java:175: warning: [deprecation] FlutterMain in io.flutter.view has been deprecated
                String appBundlePath = io.flutter.view.FlutterMain.findAppBundlePath();
                                                      ^
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-10.0.0\android\src\main\java\io\flutter\plugins\firebase\messaging\FlutterFirebaseMessagingPlugin.java:52: warning: [deprecation] Registrar in PluginRegistry has been deprecated
  public static void registerWith(Registrar registrar) {
                                  ^
7 warnings
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-5.0.0+4\android\src\main\java\com\dexterous\flutterlocalnotifications\FlutterLocalNotificationsPlugin.java:80: warning: [deprecation] Registrar in PluginRegistry has been deprecated
import io.flutter.plugin.common.PluginRegistry.Registrar;
                                              ^
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-5.0.0+4\android\src\main\java\com\dexterous\flutterlocalnotifications\FlutterLocalNotificationsPlugin.java:81: warning: [deprecation] FlutterMain in io.flutter.view has been deprecated
import io.flutter.view.FlutterMain;
                      ^
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-5.0.0+4\android\src\main\java\com\dexterous\flutterlocalnotifications\FlutterLocalNotificationsPlugin.java:133: warning: [deprecation] Registrar in PluginRegistry has been deprecated
    public static void registerWith(Registrar registrar) {
                                    ^
D:\source\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_local_notifications-5.0.0+4\android\src\main\java\com\dexterous\flutterlocalnotifications\FlutterLocalNotificationsPlugin.java:482: warning: [deprecation] FlutterMain in io.flutter.view has been deprecated
                    AssetFileDescriptor assetFileDescriptor = context.getAssets().openFd(FlutterMain.getLookupKeyForAsset(iconPath));
                                                                                         ^
4 warnings
```

**Comment by darshankawar** [comment]
@akmichael 
Are you able to build your app with the listed plugins or not ?
The log you listed seems to be warnings. 

Can you show us the log which contains `flutterfirebasecoreplugin-java-uses-or-overrides-a-deprecated-api` error ?

**Comment by akmichael** [comment]
@darshankawar 

even if i skip this warnings, firecore not getting intialized.

error: E/flutter (28128): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: [core/not-initialized] Firebase has not been correctly initialized. Have you added the "google-services.json" file to the project? 

I tried tips mentioned here https://github.com/FirebaseExtended/flutterfire/issues/3967. (created project and flutter build apk --debug, flutter build apk --profile, flutter build apk --release). Didn't help.

**Comment by darshankawar** [comment]
@akmichael 
Please double check if you have correct firebase setup along with core plugin, https://firebase.flutter.dev/docs/overview/

**Comment by anchal-td** [comment]
I am facing the same issue from yesterday. Release build got failed but debug build is working fine.

**Comment by akmichael** [comment]
@darshankawar  yes, followed setup, created several new projects and didnot work.

```
android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.anand.firestbasemessage"
        minSdkVersion 27
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

}
 
dependencies {
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-analytics'
    implementation platform('com.google.firebase:firebase-bom:28.0.1')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```
```

 dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath 'com.google.gms:google-services:4.3.8'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

```

```

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

const AndroidNotificationChannel channel = AndroidNotificationChannel(
    'high_importance_channel', // id
    'High Importance Notifications', // title
    'This channel is used for important notifications.', // description
    importance: Importance.high,
    playSound: true);

final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
FlutterLocalNotificationsPlugin();

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print('A bg message just showed up :  ${message.messageId}');
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  await flutterLocalNotificationsPlugin
      .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);

  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: true,
    badge: true,
    sound: true,
  );
  runApp(MyApp());
}

```
```

E/flutter (21287): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [core/not-initialized] Firebase has not been correctly initialized. Have you added the "google-services.json" file to the project? 
E/flutter (21287):     
E/flutter (21287): View the Android Installation documentation for more information: https://firebase.flutter.dev/docs/installation/android
E/flutter (21287): 
E/flutter (21287): #0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:88:9)
E/flutter (21287): <asynchronous suspension>
E/flutter (21287): #1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:41:31)
E/flutter (21287): <asynchronous suspension>
E/flutter (21287): #2      main (package:firestbasemessage/main.dart:23:3)
E/flutter (21287): <asynchronous suspension>
E/flutter (21287): 

```

**Comment by darshankawar** [comment]
@akmichael 
Is it happening in debug or release mode for you ?

**Comment by akmichael** [comment]
@darshankawar in debug mode.

**Comment by akmichael** [comment]
@darshankawar ,

oops. really sorry. I missed this. apply plugin: 'com.google.gms.google-services' :(.

thanks for your support and sorry wasting your time.
