### ISSUE TITLE
🐛 [cloud_functions] java.util.concurrent.ExecutionException

### ISSUE THREAD

**Issue by otopba** [FirebaseExtended/flutterfire#6253]
## Bug report

When Cloud Functions are called, sometimes there is an Exception:

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: [firebase_functions/unknown] java.util.concurrent.ExecutionException: 1 out of 2 underlying tasks failed

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:177)
<asynchronous suspension>
#2      MethodChannelHttpsCallable.call (package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart:22)
<asynchronous suspension>
#3      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:34)
<asynchronous suspension>
#4      PurchaseService._updateUserSubscribed (package:word_daily/services/purchase_service.dart:266)
<asynchronous suspension>
#5      PurchaseService._init.<anonymous closure> (package:word_daily/services/purchase_service.dart:124)
<asynchronous suspension>
. Error thrown null.
       at MethodChannelHttpsCallable.call(MethodChannelHttpsCallable.java:38)
       at HttpsCallable.call(HttpsCallable.java:34)
       at PurchaseService._updateUserSubscribed(PurchaseService.java:266)
       at PurchaseService._init.<fn>(_init.java:124)
```

### Steps to reproduce

I don't know how to reproduce this. I see errors in Crashlytics

### Expected behavior

No errors

## Additional context

![image](https://user-images.githubusercontent.com/4225279/119788459-d3c54180-beda-11eb-8a22-6f46fd98cf6e.png)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
➜  client git:(master) flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.3.0-12.1.pre, on macOS 11.3 20E232 darwin-x64, locale en-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Android Studio (version 4.2)
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
➜  client git:(master) flutter pub deps -- --style=compact
Dart SDK 2.14.0-edge.a527411e5100a0a4f48c4009087a1b988aa784af
Flutter SDK 2.3.0-12.1.pre
word_daily 0.2.2+99

dependencies:
- amplitude_flutter 3.1.0 [flutter]
- another_flushbar 1.10.22 [pedantic flutter]
- async 2.7.0 [collection meta]
- built_value 8.0.6 [built_collection collection fixnum]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 2.2.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 1.1.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.3
- device_info 2.0.1 [flutter device_info_platform_interface]
- firebase_analytics 8.1.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.2.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.0.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 2.0.4 [firebase_core flutter]
- firebase_messaging 10.0.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 0.10.0 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- firebase_storage 8.1.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- floor 1.1.0 [floor_annotation flutter meta path sqflite sqflite_common_ffi]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_email_sender 5.0.0 [flutter]
- flutter_inapp_purchase 5.0.1 [http meta flutter platform]
- flutter_local_notifications 6.0.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_native_timezone 1.1.0 [flutter_web_plugins flutter js]
- flutter_phoenix 1.0.0 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- google_sign_in 5.0.4 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- horizontal_blocked_scroll_physics 3.0.0 [flutter pedantic]
- intl 0.17.1-nullsafety.3 [clock path]
- intl_translation 0.17.10+1 [analyzer args dart_style intl path petitparser]
- launch_options 0.0.1 [flutter]
- mime 1.0.0
- optimist_dev_common 1.7.0 [flutter http intl share json_api built_value f_logs strings]
- package_info 2.0.1 [flutter]
- permission_handler 8.0.0+2 [flutter meta permission_handler_platform_interface]
- provider 5.0.0 [collection flutter nested]
- pull_to_refresh 2.0.0 [flutter]
- scroll_to_index 2.0.0 [flutter]
- shake 1.0.0 [sensors flutter]
- share 2.0.2 [meta mime flutter]
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 3.0.0 [flutter meta]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- video_player 2.1.3 [meta video_player_platform_interface video_player_web flutter flutter_test]
- visibility_detector 0.2.0 [flutter]
- vk_bridge 1.3.1 [js built_value built_collection rxdart meta]
- wakelock 0.5.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- workmanager 0.4.0 [flutter]

dev dependencies:
- build_runner 2.0.4 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- built_value_generator 8.0.6 [analyzer build build_config built_collection built_value source_gen quiver]
- fake_cloud_firestore 1.1.0 [flutter cloud_firestore cloud_firestore_platform_interface collection plugin_platform_interface quiver]
- floor_generator 1.1.0 [analyzer build build_config code_builder collection floor_annotation meta source_gen]
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_native_splash 1.1.8+4 [image meta path xml yaml universal_io]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- mockito 5.0.9 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]

dependency overrides:
- analyzer 1.7.1 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- args 2.1.0
- async 2.7.0 [collection meta]
- cloud_firestore 2.2.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_firestore_platform_interface 5.1.0 [collection firebase_core flutter meta plugin_platform_interface]
- dart_style 2.0.1 [analyzer args path pub_semver source_span]
- firebase_core 1.2.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.1-nullsafety.3 [clock path]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- petitparser 4.1.0 [meta]
- plugin_platform_interface 2.0.0 [meta]

transitive dependencies:
- _fe_analyzer_shared 22.0.0 [meta]
- archive 3.1.2 [crypto path]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.2 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_web 2.1.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.5 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.7 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.0.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- f_logs 2.0.0 [flutter sembast path_provider intl xxtea meta path stack_trace]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.0
- file 6.1.1 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.2.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.0.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 0.3.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_storage_platform_interface 2.1.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.1.0 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- floor_annotation 1.0.0 [meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.2 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_local_notifications_platform_interface 4.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- frontend_server_client 2.1.0 [async path]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 2.0.0
- http_multi_server 3.0.1 [async]
- image 3.0.2 [archive meta xml]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- json_api 4.3.0 [http http_parser]
- lists 1.0.0 [meta]
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- permission_handler_platform_interface 3.5.0 [flutter meta plugin_platform_interface]
- platform 3.0.0
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1 [matcher]
- rxdart 0.27.0
- sembast 3.0.2 [meta path synchronized pedantic]
- sensors 2.0.1 [flutter]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.4 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- sqflite_common_ffi 2.0.0 [sqlite3 sqflite_common synchronized path meta]
- sqlite3 1.1.1 [collection ffi meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- strings 0.2.1 [characters unicode]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- unicode 0.3.0 [lists]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_windows 0.0.1+3 [flutter]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.0 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock_macos 0.1.0+1 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.1+1 [flutter meta]
- wakelock_web 0.2.0+1 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.1.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.1.1 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.1 [collection meta petitparser]
- xxtea 2.1.0
- yaml 3.1.0 [collection source_span string_scanner]

```

</details>

---

**Comment by darshankawar** [comment]
@otopba 
Is this occurring in debug or in release mode ? Do you see any pattern for this exception ? 

Can you check with plugin's [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions/example) and see if you get same exception ?

**Comment by otopba** [comment]
@darshankawar 
This happens in release mode. Unfortunately, the example is not reproduced. I think that there are some nuances of the work of my application directly. For example, my application may have several isolates at the same time

**Comment by darshankawar** [comment]
@otopba 
It'd be great if you could come up with a sample code that uses isolates and which may help to trigger this issue, so that we can address it properly.

**Comment by otopba** [comment]
@darshankawar 
Okay. I will try to reproduce
