### ISSUE TITLE
🐛 [cloud_firestore] Cloud Firestore not retrying the query when network is back online

### ISSUE THREAD

**Issue by Tom3652** [FirebaseExtended/flutterfire#6361]
## Bug report

**Bug Description**

When making a query to Cloud Firestore with a very low / offline connection, and the ```GetOptions(source: Source.server)``` attribute set, the query ends as an error and doesn't retry / continue when the device is back online.

I am using ```cloud_firestore: ^2.2.2``` and ```firebase_core: ^1.3.0```.

### Steps to reproduce

1. Setup a new project with Firebase
2. Add a Cloud Firestore Database and create a fake "test" collection with at least one fake document.
3. Run the sample code example
4. Turn off your device network when the app is launched
5. Click on "Start query"
6. Put the device network back ON
7. See that the ProgressIndicator is loading forever 
8. See the following error in the logs :

```
W/Firestore( 3165): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
E/flutter ( 3165): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
E/flutter ( 3165): #0      MethodChannelQuery.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:108:7)
E/flutter ( 3165): <asynchronous suspension>
E/flutter ( 3165): #1      _JsonQuery.get (package:cloud_firestore/src/query.dart:389:9)
E/flutter ( 3165): <asynchronous suspension>
E/flutter ( 3165): 
```

To go further : At step .4 / .5 you can also reproduce this by losing connection after the query has started. As Firestore is actually fast, it requires a bigger query (document content) and another phone that is sharing connection (4G) for instance, to "Start query" and turn off sharing connection right after : in other words, reverse step 5 and 4.

### Expected behavior

I expect Cloud Firestore to retry / end the query when the device is back online.
It is stated in the documentation and even in the error log that a retry will happen when the device will be *"able to successfully connect to the backend"*.
Maybe i am totally mistaken and Firestore is only supposed to go back online but without retrying anything (past queries)... And we need to make a new call ourselves ?
If so, then i will close this issue.

### Sample project

Here is a sample project but it requires you have a FirebaseApp setup with Cloud Firestore and any ```Collection``` or ```Documents```  to query with any ```Query``` :

```
import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FirestoreTestPage(),
    );
  }
}


class FirestoreTestPage extends StatefulWidget {

  @override
  _FirestoreTestPageState createState() => _FirestoreTestPageState();
}

class _FirestoreTestPageState extends State<FirestoreTestPage> {

  bool inProgress = false;
  String text = "Hello World !";

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          child: inProgress ? Container(
              alignment: Alignment.center,
              width: 50,
              height: 50,
              child: CircularProgressIndicator()) : Container(
            width: 100,
            height: 100,
            alignment: Alignment.center,
            child: Text(text),
          )
        ),
        Align(
          alignment: Alignment.bottomCenter,
          child: ElevatedButton(onPressed: () {
            setState(() {
              inProgress = true;
            });
            FirebaseFirestore.instance.collection("test").get(GetOptions(source: Source.server)).then((value) {
              print("Query is done !");
              setState(() {
                text = "Query is done.";
                inProgress = false;
              });
            });
          }, child: Text("Start query"),
          ),
        )
      ],
    );
  }
}
```

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (3 available)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.1
Flutter SDK 2.2.1
test_project 1.0.0+1

dependencies:
- cloud_firestore 2.2.2 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.1.2 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.1.2 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by markusaksli-nc** [comment]
Well, it's not possible for the data to be "returned" when the connection resumes because the future completes with an error. The reason your sample behaves as if the future never resolves is that you have no error handling (such as `await` inside `try`/`catch` or `onError` after `then`, using a `FutureBuilder`, etc).  This is actually why you need to have error handling to update your app state or provide appropriate feedback if promises resolve with an error.

The updated version of your code would be something like this:
```dart
import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: HomePage(),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FirestoreTestPage(),
    );
  }
}

class FirestoreTestPage extends StatefulWidget {
  @override
  _FirestoreTestPageState createState() => _FirestoreTestPageState();
}

class _FirestoreTestPageState extends State<FirestoreTestPage> {
  Future? query;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          alignment: Alignment.center,
          child: query == null
              ? Container(alignment: Alignment.center, child: const Text("Start query"))
              : FutureBuilder(
                  future: query,
                  builder: (context, snapshot) {
                    String message = snapshot.connectionState.toString();
                    if (snapshot.hasData) {
                      message += '\nQuery returned: ${snapshot.data}';
                    }
                    if (snapshot.hasError) {
                      message += '\nQuery ran into error: ${snapshot.error}';
                    }
                    print('FutureBuilder: $message');
                    return Text(message);
                  }),
        ),
        Align(
          alignment: Alignment.bottomCenter,
          child: ElevatedButton(
            onPressed: () async {
              setState(() {
                query = FirebaseFirestore.instance.collection("test").get(GetOptions(source: Source.server));
              });
              tryAwaitQuery();
              registerQueryAsyncCallbacks();
            },
            child: Text("Start query"),
          ),
        )
      ],
    );
  }

  Future<void> tryAwaitQuery() async {
    try {
      var data = await query;
      print("await resolved with $data");
    } catch (e) {
      print("await completed with error $e");
    }
    print("await completed");
  }

  Future<void> registerQueryAsyncCallbacks() async {
    query!.then((value) => print("then resolved with value $value")).catchError((e) => print("then ran into error $e"));
    print('Registered then callback');
  }
}
```
I added all the examples of how to handle this situation.

It isn't very prudent to design around some ambiguous moment when the connection resumes. This would lead to unresolved futures lingering on threads and the connection might resume when the promises have become invalid (such as when the relevant app state has already been disposed).

Hope this helps clear things up.
