### ISSUE TITLE
🐛 [cloud_firestore][web] Getting exception when trying to use the Firebase Emulator Suite

### ISSUE THREAD

**Issue by devj3ns** [FirebaseExtended/flutterfire#6394]
## Bug report

**Describe the bug**
When using the Firebase Emulator Suite on the web I get the following exception (on the android emulator it is working):

```dart
The following NativeJavaScriptObject object was thrown building BlocBuilder<AuthenticationCubit, AuthenticationState>(dirty, dependencies: [_InheritedProviderScope<AuthenticationCubit>], state: _BlocBuilderBaseState<AuthenticationCubit, AuthenticationState>#0c9d0):
  FirebaseError: [code=failed-precondition]: Firestore has already been started and its settings can no longer be changed. You can only modify settings before calling any other methods on a Firestore object.

The relevant error-causing widget was: 
  BlocBuilder<AuthenticationCubit, AuthenticationState> file:///C:/Users/my_name/GoogleDrive/Work/FlutterProjects/project_name/lib/app.dart:30:16
When the exception was thrown, this was the stack: 
https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js 1:48453                                           new xr
https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js 1:265710                                          _setSettings
https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js 1:308443                                          settings
packages/cloud_firestore_web/src/interop/firestore.dart 99:16                                                    settings
packages/cloud_firestore_web/cloud_firestore_web.dart 118:21                                                     set settings
```

This is an excerpt of my code in my user repository:

```dart
final FirebaseFirestore _firebaseFirestore = kDebugMode
      ? (FirebaseFirestore.instance
        ..settings = Settings(
          host: defaultTargetPlatform == TargetPlatform.android
              ? '10.0.2.2:8080'
              : 'localhost:8080',
          sslEnabled: false,
        ))
      : FirebaseFirestore.instance;
      
```

I also tried to move the code for changing the settings to my main.dart file (which is not ideal because I don't want to have a firebase firestore dependency there), but then I get this exception on hot reload:

```dart
FirebaseError: Firestore has already been started and its settings can no longer be changed. You can only modify settings before calling any other methods on a Firestore object.
    at new xr (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:48453)
    at yp.rp._setSettings (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:265710)
    at Sg.settings (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:308443)
    at firestore.Firestore._fromJsObject.settings (http://localhost:54521/packages/cloud_firestore_web/src/interop/utils/utils.dart.lib.js:215:28)
    at cloud_firestore_web.FirebaseFirestoreWeb.new.set settings [as settings] (http://localhost:54521/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:741:29)
    at cloud_firestore.FirebaseFirestore.__.set settings [as settings] (http://localhost:54521/packages/cloud_firestore/cloud_firestore.dart.lib.js:1391:33)
    at main (http://localhost:54521/packages/nestwaerme_kita_app/main.dart.lib.js:51:61)
    at main.next (<anonymous>)
    at http://localhost:54521/dart_sdk.js:37374:33
    at _RootZone.runUnary (http://localhost:54521/dart_sdk.js:37245:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:54521/dart_sdk.js:32501:29)
    at handleValueCallback (http://localhost:54521/dart_sdk.js:33028:49)
    at Function._propagateToListeners (http://localhost:54521/dart_sdk.js:33066:17)
    at _Future.new.[_completeWithValue] (http://localhost:54521/dart_sdk.js:32914:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54521/dart_sdk.js:32935:35)
    at Object._microtaskLoop (http://localhost:54521/dart_sdk.js:37497:13)
    at _startMicrotaskLoop (http://localhost:54521/dart_sdk.js:37503:13)
    at http://localhost:54521/dart_sdk.js:33274:9
```

### Steps to reproduce

1. Configure a project to use the Firebase Emulator Suite.
2. Start it on the web

### Expected behaviour
It should work exactly like on android, without exceptions.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19042.1052], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1.0)
[✓] VS Code (version 1.57.0)
[✓] Connected device (2 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.0
Flutter SDK 2.2.0
project_name 1.0.1+11

dependencies:
- absence_repository 2.0.0 [flutter firebase_core cloud_firestore equatable csv intl flutter_extensions]
- appointment_repository 2.0.0 [flutter firebase_core cloud_firestore equatable flutter_extensions]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 2.2.2 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- datetime_picker_formfield 2.0.0 [flutter intl]
- feed_repository 2.0.0 [flutter firebase_core cloud_firestore firebase_storage equatable flutter_extensions]
- file_picker 3.0.2+2 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_crashlytics 2.0.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flash 2.0.0 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.0.1 [flutter bloc provider]
- flutter_extensions 1.0.0 [flutter intl]
- flutter_hooks 0.17.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- font_awesome_flutter 9.1.0 [flutter]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- google_nav_bar 5.0.0 [flutter font_awesome_flutter]
- intl 0.17.0 [clock path]
- notification_repository 2.0.0 [flutter firebase_core firebase_messaging shared_preferences http]
- pdf_flutter 1.2.0 [flutter flutter_cache_manager http path_provider]
- url_launcher 6.0.6 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- url_strategy 0.2.0 [flutter_web_plugins]
- user_repository 2.0.0 [flutter firebase_core firebase_auth firebase_storage cloud_firestore cloud_functions equatable flutter_secure_storage flutter_extensions]

dev dependencies:
- dart_code_metrics 4.0.0-dev.3 [analyzer analyzer_plugin ansicolor args collection crypto file glob html meta path quiver source_span yaml]
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- pedantic 1.11.0

transitive dependencies:
- _fe_analyzer_shared 22.0.0 [meta]
- analyzer 1.7.1 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- analyzer_plugin 0.6.0 [analyzer collection dart_style pub_semver]
- ansicolor 2.0.1
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.6.1 [meta collection]
- bloc 7.0.0 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.1.2 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.1.2 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions 1.1.1 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cloud_functions_platform_interface 5.0.6 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.8 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.0 [source_span]
- csv 5.0.0
- dart_style 2.0.1 [analyzer args path pub_semver source_span]
- equatable 2.0.2 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.1 [meta path]
- firebase_auth 1.4.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_platform_interface 4.3.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.3.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.0.5 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging 10.0.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_messaging_platform_interface 3.0.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage 8.1.2 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- firebase_storage_platform_interface 2.1.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.1.1 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_secure_storage 4.2.0 [meta flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- html 0.15.0 [csslib source_span]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- path 1.8.0
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- provider 5.0.0 [collection flutter nested]
- pub_semver 2.0.0 [collection]
- quiver 3.0.1 [matcher]
- rxdart 0.27.1
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- win32 2.1.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

```

</details>

---

**Comment by devj3ns** [comment]
Related to https://github.com/FirebaseExtended/flutterfire/issues/6216 and https://github.com/FirebaseExtended/flutterfire/issues/5224

**Comment by markusaksli-nc** [comment]
Hi @devj3ns 
Could this be an issue with `bloc` or your code? I tried this with just a basic example and it worked without errors.
<details>
 <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

bool USE_FIRESTORE_EMULATOR = true;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  if (USE_FIRESTORE_EMULATOR) {
    FirebaseFirestore.instance.settings = const Settings(
      host: 'localhost:8080',
      sslEnabled: false,
      persistenceEnabled: false,
    );
  }
  runApp(FirestoreExampleApp());
}

class FirestoreExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firestore Example App',
      theme: ThemeData.dark(),
      home: const Scaffold(
        body: Center(child: Body()),
      ),
    );
  }
}

class Body extends StatelessWidget {
  const Body({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        ElevatedButton(
          onPressed: () async {
            await FirebaseFirestore.instance.doc("test/test").set({"key": "value "});
          },
          child: const Text("Set"),
        ),
        ElevatedButton(
            onPressed: () async {
              print((await FirebaseFirestore.instance.doc("test/test").get()).data());
            },
            child: const Text("Get")),
      ],
    );
  }
}
```
</details>

Thank you

**Comment by devj3ns** [comment]
Thanks for the quick response @markusaksli-nc!

For me, the bug is reproducible with the code you posted above.

### Steps to reproduce:
1. Start the emulator
2. Run the app in the web
3. Press on set and then on get
4. Press hot reload

```dart
FirebaseError: Firestore has already been started and its settings can no longer be changed. You can only modify settings before calling any other methods on a Firestore object.
    at new xr (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:48453)
    at yp.rp._setSettings (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:265710)
    at Sg.settings (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:308443)
    at firestore.Firestore._fromJsObject.settings (http://localhost:50618/packages/cloud_firestore_web/src/interop/utils/utils.dart.lib.js:215:28)
    at cloud_firestore_web.FirebaseFirestoreWeb.new.set settings [as settings] (http://localhost:50618/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:741:29)
    at cloud_firestore.FirebaseFirestore.__.set settings [as settings] (http://localhost:50618/packages/cloud_firestore/cloud_firestore.dart.lib.js:1391:33)
    at main$ (http://localhost:50618/packages/firebase_emulator_test/main.dart.lib.js:518:61)
    at main$.next (<anonymous>)
    at http://localhost:50618/dart_sdk.js:37374:33
    at _RootZone.runUnary (http://localhost:50618/dart_sdk.js:37245:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:50618/dart_sdk.js:32501:29)
    at handleValueCallback (http://localhost:50618/dart_sdk.js:33028:49)
    at Function._propagateToListeners (http://localhost:50618/dart_sdk.js:33066:17)
    at _Future.new.[_completeWithValue] (http://localhost:50618/dart_sdk.js:32914:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50618/dart_sdk.js:32935:35)
    at Object._microtaskLoop (http://localhost:50618/dart_sdk.js:37497:13)
    at _startMicrotaskLoop (http://localhost:50618/dart_sdk.js:37503:13)
    at http://localhost:50618/dart_sdk.js:33274:9
```


I am using version 8.6.1 of `firebase-firestore.js`, which one did you use?

**Comment by markusaksli-nc** [comment]
If you meant just the hot reload issue then there is already an open issue for that https://github.com/FirebaseExtended/flutterfire/issues/6216.
