### ISSUE TITLE
🐛 [PLUGIN_NAME_HERE] Error: spawn npm --prefix "%RESOURCE_DIR%" run lint ENOENT

### ISSUE THREAD

**Issue by Patrick386** [FirebaseExtended/flutterfire#6396]
PC: Windows 10

I am working on a flutter web project.

Is there a workaround for this issue that keeps happening?
There are many problems with resolving Cloud Functions errors.
Determining where the error is is also complicated.
Is there any good way?

eslint looks more complicated. It looks like you need a guide that suits your environment.

```
i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint .


C:\Dev\Projects\functions\index.js
  9:41  error  Parsing error: Unexpected token =>

✖ 1 problem (1 error, 0 warnings)

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm --prefix "%RESOURCE_DIR%" run lint ENOENT
    at notFoundError (C:\Users\SintPatrick\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\eno
ent.js:6:26)
    at verifyENOENT (C:\Users\SintPatrick\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\lib\enoe
nt.js:40:16)
    at ChildProcess.cp.emit (C:\Users\SintPatrick\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\
lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\Users\SintPatrick\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\cross-env\node_modules\cross-spawn\
lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn npm --prefix "%RESOURCE_DIR%" run lint',
  path: 'npm --prefix "%RESOURCE_DIR%" run lint',
  spawnargs: []
}

Error: functions predeploy error: Command terminated with non-zero exit code1
```

**Package.json**
```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase emulators:start --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "14"
  },
  "main": "index.js",
  "dependencies": {
    "firebase-admin": "^9.8.0",
    "firebase-functions": "^3.14.1"
  },
  "devDependencies": {
    "eslint": "^7.6.0",
    "eslint-config-google": "^0.14.0",
    "firebase-functions-test": "^0.2.0"
  },
  "private": true
}

```

**Comment by markusaksli-nc** [comment]
Hi @Patrick386 
It looks like this is better suited for https://firebase.google.com/support
This repository just wraps the native Firebase SDKs so they could be used from Flutter but you are having issues with the backend side of cloud functions.
Thank you
