### ISSUE TITLE
🐛 [cloud_functions] "Unauthenticated" when calling http function from release build

### ISSUE THREAD

**Issue by felixwortmann** [FirebaseExtended/flutterfire#6474]
## Bug report

Calling a HTTP Function via the plugin does not work in release mode.<br>
I am using a physical Oneplus 7 Pro.<br>
When I call the function while running in debug, everything works as expected, when I run the exact same code again in release mode, I get this error:
```
I/flutter ( 7650): api error: [firebase_functions/unauthenticated] Unauthenticated
I/flutter ( 7650): 
I/flutter ( 7650): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
I/flutter ( 7650): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
I/flutter ( 7650): <asynchronous suspension>
I/flutter ( 7650): #2      MethodChannelHttpsCallable.call (package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart:22)
I/flutter ( 7650): <asynchronous suspension>
I/flutter ( 7650): #3      HttpsCallable.call (package:cloud_functions/src/https_callable.dart:34)
I/flutter ( 7650): <asynchronous suspension>
```
I am using `cloud_functions: 1.1.2`

### Output of flutter doctor
```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by felixwortmann** [comment]
Some more info: I am logged into a FirebaseAuth account when I test this. Also I just deployed it to a test track in the PlayStore and it works there. Maybe this can help to resolve the issue.

**Comment by darshankawar** [comment]
@felixwortmann 
Does the error occur if you are not using the FirebaseAuth account ?
Can you try the official plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_functions/cloud_functions/example) in release mode to see if it persists ?

Thanks.

**Comment by felixwortmann** [comment]
> Does the error occur if you are not using the FirebaseAuth account ?
What do you mean by that? I am logged into FirebaseAuth. If I use:
```dart
print(FirebaseAuth.instance.currentUser);
```
it returns the logged in user.

**Comment by darshankawar** [comment]
@felixwortmann 
I just wanted to check first if directly using the plugin example also throws the same error for you.
I tried it on web in release mode and it didn't throw the error.
Can you please provide a minimal code sample using firebaseauth that we can use to replicate this ?
Thanks.

**Comment by felixwortmann** [comment]
So for the example: Do I have to setup another firebase project? Because the example already includes a `google-services.json` and `GoogleService-Info.plist`. <br>
I tried it just out of the box and I get ` ERROR: [firebase_functions/internal] Response is not a valid JSON object`<br>
Tested on: physical android device in release and debug.<br>
I also tested on web in release, it also threw `ERROR: [firebase_functions/internal]` but it did not show more as error msg.

**Comment by felixwortmann** [comment]
Am I right to assume that without any additional setup everything should work the same on an emulator and a physical device?

**Comment by felixwortmann** [comment]
Ok, I just set the function permission to `allow unauthenticated`. It seems to be working now. I am guessing that the whole "release/debug" confusion came because the permission does not switch instantly. <br>
Now it is still open why I am "unauthenticated" even though I am logged into a FirebaseAuth account. <br>
Also would it be safe to just leave the function with `allow unauthenticated`? Are there any security guidelines on that?

**Comment by darshankawar** [comment]
@felixwortmann 
Thanks for digging into it. The function you are using, is it available for `allUsers` or only to `authenticatedUsers` ?
If the latter, then I guess that's why you are getting `unauthenticated` error ?
If you haven't tried already, can you use `allUsers` and check if it helps to resolve ?

**Comment by felixwortmann** [comment]
If I set the function to allUsers, it works.
If it is only set to allAuthenticatedUsers, it does not.
However I do not understand why that is the case since I am authenticated.

**Comment by darshankawar** [comment]
@felixwortmann 
Can you provide more details around how are you calling the functions ?
Can you try by creating a new function as in the example in your app, like below:

```
exports.example = functions.https.onCall((data, context) => {
  return ["Apple", "Banana", "Cherry", "Date", "Fig", "Grapes"];
});
```

And then run it as below:

```
Future<void> getFruit() async {
    final callable = CloudFunctions.instance.getHttpsCallable(
      functionName: 'claim_uid',
    );
    final results = await callable.call();
    List fruit =
        results.data; // ["Apple", "Banana", "Cherry", "Date", "Fig", "Grapes"]

    print('$fruit');
  }
```

**Comment by felixwortmann** [comment]
Ok, I just tested that. It throws the same error: `Unhandled Exception: [firebase_functions/unauthenticated] `. I executed this:
```dart
final callable = FirebaseFunctions.instance.httpsCallable(
  'example', //that is what I named the function 
);
final results = await callable.call<dynamic>(); //throws Unhandled Exception: [firebase_functions/unauthenticated] UNAUTHENTICATED
final dynamic fruit = results
    .data; // ["Apple", "Banana", "Cherry", "Date", "Fig", "Grapes"]
print('$fruit');
```
You might notice that I used `FirebaseFunctions.instance.httpsCallable` instead of `CloudFunctions.instance.getHttpsCallable` and I actually do not know why that is different (`CloudFunctions` does not seem to exist for me)<br>
Obviously now I used `allAuthenticatedUsers` as permission for the function.

**Comment by darshankawar** [comment]
@felixwortmann 
You can check the authentication in your function by checking for the existence of `context.auth` like below:

```
// Checking that the user is authenticated.
if (!context.auth) {
  // Throwing an HttpsError so that the client gets the error details.
  throw new functions.https.HttpsError('failed-precondition', 'The function must be called ' +
      'while authenticated.');
}
```

**Comment by felixwortmann** [comment]
I do not actually understand how you use
```dart
context.auth
```
to get if someone is authenticated. <br><br>If I use
```dart
print(FirebaseAuth.instance.currentUser);
```
I get the data for my account so I am authenticated.

**Comment by felixwortmann** [comment]
I just remembered that I did enable AppCheck recently. It should not enforce anything though since I did not configure anything like that. Could this still have something todo with that?

**Comment by darshankawar** [comment]
I am not too familiar with AppCheck and it's impact on other plugins yet as I didn't get a chance to go through.

There have been below similar reported issues:

https://github.com/FirebaseExtended/flutterfire/issues/187
https://github.com/FirebaseExtended/flutterfire/issues/3692
https://github.com/FirebaseExtended/flutterfire/issues/3335
https://github.com/FirebaseExtended/flutterfire/issues/2374

Please go through them and check if they help.

**Comment by felixwortmann** [comment]
Sadly none of these could really help me because I tried pretty much all of them already.
<br>
I just tried this:
```js
// Checking that the user is authenticated.
if (!context.auth) {
  // Throwing an HttpsError so that the client gets the error details.
  throw new functions.https.HttpsError('failed-precondition', 'The function must be called ' +
      'while authenticated.');
}
```
And it does not throw.
if I return the user with
```js
return context.auth
```
it returns a valid user. This means that the user is passed to the backend. <br> Could it be related to some quotas for the firebase functions that are automatically limited at some point? Can I look them up somewhere?

**Comment by darshankawar** [comment]
@felixwortmann 
Probably the plugin doesn't send any authentication details and the state may be handled by the internal sdk. Please see if you get any reference here: https://firebase.google.com/docs/functions

**Comment by felixwortmann** [comment]
I am not quite sure what you mean by that. If I check in my flutter app, I can see a valid user. If I check on the server side in my cloud function, I can see a valid user. If I turn the function permission to `allAuthenticatedUsers`, it does not work anymore.

**Comment by darshankawar** [comment]
I ran out of ideas to provide you now to try out :-) Keeping it open for further insights from team.

**Comment by felixwortmann** [comment]
Are there any security guidelines on this? When is it safe to use `allUsers`? Or is it just always bad practice?

**Comment by cngeru** [comment]
Getting it in debug... Any fix ?

**Comment by cngeru** [comment]
@felixwortmann Did you get a workaround?

**Comment by felixwortmann** [comment]
@cngeru not really. The function seems to work most of the time (on a physical device in release mode). I this fixed but it is just really hard to reproduce since it works most of the time (sometimes it just doesn't). Also I just do not have the time rn.

**Comment by cngeru** [comment]
Did you have to alter anything for it to work on release. Or just adding it in `main` is okay ?

**Comment by felixwortmann** [comment]
@cngeru basically I changed the permission to allUsers. Otherwise I just followed the docs. Sometimes you have to give it a few minutes / hours if it does not work. I don't know why that is the case though.

**Comment by gOzaru** [comment]
Have you checked whether the Firebase SDK is added correctly to build.gradle???
Since I just updated it a few minutes ago and all Unauthenticated messages are gone now. 
Give it a try. 
Check it in Project Settings > General > Your Apps > See SDK Instructions

**Comment by felixwortmann** [comment]
@gOzaru what exactly do I have to add? I added `com.google.gms:google-services:4.3.8` and `com.google.firebase:firebase-crashlytics-gradle:2.3.0` (which I do not think is needed for functions) as dependencies. Also all other firebase products run flawlessly. Am I missing something

**Comment by aboutmydreams** [comment]
I have same problem, @felixwortmann  have u solve it ?

**Comment by felixwortmann** [comment]
@aboutmydreams sadly not, it is really weired, because it works most times on the released version, never on a simulator. It is also very inconsistent if it works or not.
