### ISSUE TITLE
[📚] Crashlytics example from docs not working

### ISSUE THREAD

**Issue by wujek-srujek** [FirebaseExtended/flutterfire#6498]
The example under https://firebase.flutter.dev/docs/crashlytics/usage#zoned-errors (the example with `runZonedGuarded`) causes the following error:

```
E/flutter (30175): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: [core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()
E/flutter (30175): #0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:122)
E/flutter (30175): #1      Firebase.app (package:firebase_core/src/firebase.dart:54)
E/flutter (30175): #2      FirebaseCrashlytics.instance (package:firebase_crashlytics/src/firebase_crashlytics.dart:32)
E/flutter (30175): #3      main (package:time_it/main.dart:27)
E/flutter (30175): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142)
E/flutter (30175): #5      _rootRun (dart:async/zone.dart:1354)
E/flutter (30175): #6      _CustomZone.run (dart:async/zone.dart:1258)
E/flutter (30175): #7      _runZoned (dart:async/zone.dart:1789)
E/flutter (30175): #8      runZonedGuarded (dart:async/zone.dart:1777)
E/flutter (30175): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138)
E/flutter (30175): #10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283)
E/flutter (30175): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
E/flutter (30175): 
```

The snippet works only when I move these two lines:
```dart
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();
```
outside of the `runZonedGuarded` block, like this:

```dart
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();

  await runZonedGuarded<Future<void>>(() async {
     ...
  }, FirebaseCrashlytics.instance.recordError);
```

**Comment by Patil2099** [comment]
I would love to take this up
