### ISSUE TITLE
🐛 [firebase_messaging: ^10.0.3] Failed to get FIS auth token

### ISSUE THREAD

**Issue by arasu33** [FirebaseExtended/flutterfire#6550]
## Bug report

Failed to get FIS auth token
```
 java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@17.2.0:69)
 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.2.0:23)
 	at com.google.firebase.messaging.GmsRpc.setDefaultAttributesToBundle(com.google.firebase:firebase-messaging@@22.0.0:11)
 	at com.google.firebase.messaging.GmsRpc.startRpc(com.google.firebase:firebase-messaging@@22.0.0:1)
 	at com.google.firebase.messaging.GmsRpc.getToken(com.google.firebase:firebase-messaging@@22.0.0:2)
 	at com.google.firebase.messaging.FirebaseMessaging.lambda$blockingGetToken$8$FirebaseMessaging(com.google.firebase:firebase-messaging@@22.0.0:1)
 	at com.google.firebase.messaging.FirebaseMessaging$$Lambda$9.start(Unknown Source:4)
 	at com.google.firebase.messaging.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-messaging@@22.0.0:6)
 	at com.google.firebase.messaging.FirebaseMessaging.lambda$blockingGetToken$9$FirebaseMessaging(com.google.firebase:firebase-messaging@@22.0.0:1)
 	at com.google.firebase.messaging.FirebaseMessaging$$Lambda$8.then(Unknown Source:4)
 	at com.google.android.gms.tasks.zzf.run(com.google.android.gms:play-services-tasks@@17.2.0:2)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.5.0:6)
 	at java.lang.Thread.run(Thread.java:923)
 Caused by: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
 	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:158)
 	at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:533)
 	at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:388)
 	at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2$FirebaseInstallations(FirebaseInstallations.java:377)
 	at com.google.firebase.installations.-$$Lambda$FirebaseInstallations$VZq1h0TBcWNH8Y5yY86ujrFFyLo.run(Unknown Source:4)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 ```

### Steps to reproduce

1. After adding SHA1 key , Downloaded google-services.json file in app folder.
2. Added firebase_messaging: ^10.0.3
3. Added firebase_core: ^1.3.0
4. And added following code in main.dart
<details><summary>Click To Expand</summary>

```dart
 await Firebase.initializeApp();
 FirebaseMessaging messaging = FirebaseMessaging.instance;
    String tokenStr;
    messaging.getToken().then((token) {
      tokenStr = token;
    }).timeout(Duration(seconds: 5), onTimeout: () {
      tokenStr = '';
    }).catchError((error) {
      tokenStr = '';
    }).whenComplete(() {
      print("####----" + tokenStr);
    });

```

</details>
5. When i try to run the code i am getting the above mentioned error.

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio
    ✗ Unable to find bundled Java version.
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.57.1)
[✓] Connected device (4 available)
```

</details>

**Comment by markusaksli-nc** [comment]
Hi @arasu33 
Seems like a connection issue? Have you tested this on multiple devices or in different networks. You could also contact https://firebase.google.com/support
Thank you

**Comment by arasu33** [comment]
Hi @markusaksli-nc ,

I tried with different devices like pixel 4a, samsung and redmi  and also emulator as well. Checked with Different  networks as well... But i got the same error. Is there a way to find which will led to this error....

**Comment by markusaksli-nc** [comment]
Could you try running the official example?
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example

**Comment by arasu33** [comment]
@markusaksli-nc  Example working fine.

**Comment by arasu33** [comment]
@markusaksli-nc  ... Issues with my multiple package with various suffix. Finally i am able to get the solution, by updating the correct packages for the app....
