### ISSUE TITLE
🐛 [firebase_auth] Flutter Web firebase_auth error

### ISSUE THREAD

**Issue by hanumanjiblog** [FirebaseExtended/flutterfire#6637]
firebase_auth google login not working on web. Please replay with correct code.
flutter run -d chrome --web-hostname localhost --web-port 5000

Code--
```
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';

void main() {
  runApp(MyApp());
}

final FirebaseAuth _auth = FirebaseAuth.instance;
final GoogleSignIn googleSignIn = GoogleSignIn();

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        home: Scaffold(
      body: Center(
        child: TextButton(
          onPressed: () async {
            print(await signInWithGoogle());
          },
          child: Text('data'),
        ),
      ),
    ));
  }
}

Future signInWithGoogle() async {
  await Firebase.initializeApp();
  final GoogleSignInAccount? googleSignInAccount = await googleSignIn.signIn();
  final GoogleSignInAuthentication googleSignInAuthentication = await googleSignInAccount!.authentication;

  final AuthCredential credential = GoogleAuthProvider.credential(
    accessToken: googleSignInAuthentication.accessToken,
    idToken: googleSignInAuthentication.idToken,
  );
  final UserCredential userCredential = await _auth.signInWithCredential(credential);
  final User? user = userCredential.user;

  if (user != null)
    return user;
  else
    return false;
}

```

```
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  google_sign_in: ^5.0.4
```
```
<!DOCTYPE html>
<html>
  <head>
    <base href="/" />
    <meta charset="UTF-8" />
    <meta content="IE=Edge" http-equiv="X-UA-Compatible" />
    <meta name="description" content="A new Flutter project." />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="apple-mobile-web-app-title" content="google_signin" />
    <link rel="apple-touch-icon" href="icons/Icon-192.png" />
    <title>google_signin</title>
    <link rel="manifest" href="manifest.json" />
    <meta name="google-signin-client_id" content="" />
  </head>
  <body>
    <!---->
    <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/7.5.0/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/8.7.1/firebase-analytics.js"></script>
    <script>
      var firebaseConfig = {
        apiKey: "",
        authDomain: "",
        projectId: "",
        storageBucket: "",
        messagingSenderId: "",
        appId: "",
        measurementId: "",
      };
      firebase.initializeApp(firebaseConfig);
      firebase.analytics();
    </script>
    <!---->

    <script>
      var serviceWorkerVersion = null;
      var scriptLoaded = false;
      function loadMainDartJs() {
        if (scriptLoaded) {
          return;
        }
        scriptLoaded = true;
        var scriptTag = document.createElement("script");
        scriptTag.src = "main.dart.js";
        scriptTag.type = "application/javascript";
        document.body.append(scriptTag);
      }

      if ("serviceWorker" in navigator) {
        // Service workers are supported. Use them.
        window.addEventListener("load", function () {
          // Wait for registration to finish before dropping the <script> tag.
          // Otherwise, the browser will load the script multiple times,
          // potentially different versions.
          var serviceWorkerUrl = "flutter_service_worker.js?v=" + serviceWorkerVersion;
          navigator.serviceWorker.register(serviceWorkerUrl).then((reg) => {
            function waitForActivation(serviceWorker) {
              serviceWorker.addEventListener("statechange", () => {
                if (serviceWorker.state == "activated") {
                  console.log("Installed new service worker.");
                  loadMainDartJs();
                }
              });
            }
            if (!reg.active && (reg.installing || reg.waiting)) {
              // No active web worker and we have installed or are installing
              // one for the first time. Simply wait for it to activate.
              waitForActivation(reg.installing ?? reg.waiting);
            } else if (!reg.active.scriptURL.endsWith(serviceWorkerVersion)) {
              // When the app updates the serviceWorkerVersion changes, so we
              // need to ask the service worker to update.
              console.log("New service worker available.");
              reg.update();
              waitForActivation(reg.installing);
            } else {
              // Existing service worker is still good.
              console.log("Loading app from service worker.");
              loadMainDartJs();
            }
          });

          // If service worker doesn't succeed in a reasonable amount of time,
          // fallback to plaint <script> tag.
          setTimeout(() => {
            if (!scriptLoaded) {
              console.warn("Failed to load app from service worker. Falling back to plain <script> tag.");
              loadMainDartJs();
            }
          }, 4000);
        });
      } else {
        // Service workers not supported. Just drop the <script> tag.
        loadMainDartJs();
      }
    </script>
  </body>
</html>

```
Error--
```
flutter run -d chrome --web-hostname localhost --web-port 5000
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             40.4s
This app is linked to the debug service: ws://127.0.0.1:65264/2xhCOqlHxuE=/ws
Debug service listening on ws://127.0.0.1:65264/2xhCOqlHxuE=/ws

 Running with sound null safety

  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
TypeError: dart.global.firebase.auth is not a function
    at Object.getAuthInstance
    (http://localhost:5000/packages/firebase_auth_web/src/interop/auth.dart.lib.js:838:70)
    at new firebase_auth_web.FirebaseAuthWeb.new
    (http://localhost:5000/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:421:27)     
    at firebase_auth_web.FirebaseAuthWeb.__.delegateFor
    (http://localhost:5000/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:67:14)      
    at Function.instanceFor
    (http://localhost:5000/packages/firebase_auth_platform_interface/src/types.dart.lib.js:1387:    77)
    at firebase_auth.FirebaseAuth.__.get [_delegate]
    (http://localhost:5000/packages/firebase_auth/firebase_auth.dart.lib.js:88:135)
    at firebase_auth.FirebaseAuth.__.signInWithCredential
    (http://localhost:5000/packages/firebase_auth/firebase_auth.dart.lib.js:238:68)
    at signInWithCredential.next (<anonymous>)
    at runBody (http://localhost:5000/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:5000/dart_sdk.js:37453:7)
    at firebase_auth.FirebaseAuth.__.signInWithCredential
    (http://localhost:5000/packages/firebase_auth/firebase_auth.dart.lib.js:237:20)
    at signInWithGoogle (http://localhost:5000/packages/google_signin/main.dart.lib.js:208:46)  
    at signInWithGoogle.next (<anonymous>)
    at http://localhost:5000/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:5000/dart_sdk.js:32530:29)       
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:32943:23)
    at http://localhost:5000/dart_sdk.js:32194:46
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:32824:27)      
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37532:13)
    at http://localhost:5000/dart_sdk.js:33303:9

Performing hot restart...                                          431ms
Restarted application in 436ms.
TypeError: dart.global.firebase.auth is not a function
    at Object.getAuthInstance
    (http://localhost:5000/packages/firebase_auth_web/src/interop/auth.dart.lib.js:838:70)      
    at new firebase_auth_web.FirebaseAuthWeb.new
    (http://localhost:5000/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:421:27)     
    at firebase_auth_web.FirebaseAuthWeb.__.delegateFor
    (http://localhost:5000/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:67:14)      
    at Function.instanceFor
    (http://localhost:5000/packages/firebase_auth_platform_interface/src/types.dart.lib.js:1387:    77)
    at firebase_auth.FirebaseAuth.__.get [_delegate]
    (http://localhost:5000/packages/firebase_auth/firebase_auth.dart.lib.js:88:135)
    at firebase_auth.FirebaseAuth.__.signInWithCredential
    (http://localhost:5000/packages/firebase_auth/firebase_auth.dart.lib.js:238:68)
    at signInWithCredential.next (<anonymous>)
    at runBody (http://localhost:5000/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:5000/dart_sdk.js:37453:7)
    at firebase_auth.FirebaseAuth.__.signInWithCredential
    (http://localhost:5000/packages/firebase_auth/firebase_auth.dart.lib.js:237:20)
    at signInWithGoogle (http://localhost:5000/packages/google_signin/main.dart.lib.js:208:46)  
    at signInWithGoogle.next (<anonymous>)
    at http://localhost:5000/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:5000/dart_sdk.js:32530:29)        
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:5000/dart_sdk.js:32943:23)
    at http://localhost:5000/dart_sdk.js:32194:46
    at _RootZone.runUnary (http://localhost:5000/dart_sdk.js:37274:59)
    at _FutureListener.then.handleValue (http://localhost:5000/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:5000/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:5000/dart_sdk.js:33095:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:5000/dart_sdk.js:32824:27)       
    at Object._microtaskLoop (http://localhost:5000/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:5000/dart_sdk.js:37532:13)
    at http://localhost:5000/dart_sdk.js:33303:9
```

**Comment by omymy1** [comment]
Yes, I am also facing same problem, Please Current the code copy paste here.

**Comment by markusaksli-nc** [comment]
Hi @hanumanjiblog 
Please follow https://firebase.flutter.dev/docs/installation/web and https://firebase.flutter.dev/docs/auth/overview#3-web-only-add-the-sdk and let me know if the issue persists with the same versions.
Thank you
