### ISSUE TITLE
🐛 [cloud_firestore] Error when trying to get document that contains Blob on web (Firestore treats Blob as GeoPoint)

### ISSUE THREAD

**Issue by andrejvujic** [FirebaseExtended/flutterfire#6709]
## Bug report

**Describe the bug**
This bug is only present on Flutter web. Everytime I try to fetch a document that contains a Blob an exception is thrown. I think that it is treating the Blob as a GeoPoint and that causes the exception. The following exception is thrown:
```
Error: NoSuchMethodError: '<Unexpected Null Value>'
method not found
Receiver: null
Arguments: []
    at Object.throw_ [as throw] (http://localhost:60634/dart_sdk.js:5348:11)
    at Object.throwNullValueError (http://localhost:60634/dart_sdk.js:5314:15)
    at Object._notNull [as notNull] (http://localhost:60634/dart_sdk.js:5667:25)
    at new geo_point.GeoPoint.new (http://localhost:60634/packages/cloud_firestore_platform_interface/src/geo_point.dart.lib.js:44:16)    
    at Function.valueDecode (http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:656:16)
    at http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:644:43
    at LinkedMap.new.updateAll (http://localhost:60634/dart_sdk.js:21775:28)
    at Function.decodeMapData (http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:642:25)
    at MappedListIterable.new.valueDecode (http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:664:43)
    at MappedListIterable.new.elementAt (http://localhost:60634/dart_sdk.js:22933:25)
    at ListIterator.new.moveNext (http://localhost:60634/dart_sdk.js:22728:55)
    at JsIterator.next (http://localhost:60634/dart_sdk.js:7072:21)
    at Function.of (http://localhost:60634/dart_sdk.js:45499:18)
    at MappedListIterable.new.toList (http://localhost:60634/dart_sdk.js:22535:26)
    at Function.decodeArrayData (http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:652:78)
    at Function.valueDecode (http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:666:43)
    at http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:644:43
    at LinkedMap.new.updateAll (http://localhost:60634/dart_sdk.js:21775:28)
    at Function.decodeMapData (http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:642:25)
    at Function.valueDecode (http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:664:43)
    at http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:644:43
    at LinkedMap.new.updateAll (http://localhost:60634/dart_sdk.js:21775:28)
    at Function.decodeMapData (http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:642:25)
    at Object.convertWebDocumentSnapshot (http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:688:211)
    at document_reference_web.DocumentReferenceWeb.new.get (http://localhost:60634/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:513:26)
    at get.next (<anonymous>)
    at http://localhost:60634/dart_sdk.js:39230:33
    at _RootZone.runUnary (http://localhost:60634/dart_sdk.js:39087:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:60634/dart_sdk.js:34073:29)
    at handleValueCallback (http://localhost:60634/dart_sdk.js:34633:49)
    at Function._propagateToListeners (http://localhost:60634/dart_sdk.js:34671:17)
    at _Future.new.[_completeWithValue] (http://localhost:60634/dart_sdk.js:34513:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60634/dart_sdk.js:34536:35)
    at Object._microtaskLoop (http://localhost:60634/dart_sdk.js:39374:13)
    at _startMicrotaskLoop (http://localhost:60634/dart_sdk.js:39380:13)
    at http://localhost:60634/dart_sdk.js:34887:9
```

### Steps to reproduce

1. Create a Firestore collection
2. Create a document that contains a Blob in the collection
3. Now try to get the document

### Expected behavior

If everything worked fine you should get a `DocumentSnapshot` that contains data about the document.

### Sample project

---

`web/index.html` content:

<details><summary>Click To Expand</summary>

```html
<!DOCTYPE html>
<html>
<head>
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="A new Flutter project.">

  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="testing">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>testing</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>

  <!-- NOTE: I've tried using version 8.8.0 for all SDKs and it doesn't work neither -->
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js"></script>
  
  <script>
    var firebaseConfig = {
      apiKey: "xxxxx",
      authDomain: "xxxxx",
      projectId: "xxxxx",
      storageBucket: "xxxxx",
      messagingSenderId: "xxxxx",
      appId: "xxxxx",
      measurementId: "xxxxx"
    };
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
  </script>
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```

</details>

--- 

`pubspec.yaml` content:

<details><summary>Click To Expand</summary>

```yaml
name: testing
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core:
  firebase_auth:
  cloud_firestore:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
```

</details>

---

`lib/main.dart` content:

<details><summary>Click To Expand</summary>

```dart
import 'dart:typed_data';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(
    MyApp(),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final _auth = FirebaseAuth.instance;
  final _firestore = FirebaseFirestore.instance;
  Uint8List _bytes;
  Map<String, dynamic> _data;
  String _error;

  Future<void> uploadDocument(
    FirebaseAuth auth,
    FirebaseFirestore firestore,
    Uint8List bytes,
  ) async {
    if (auth.currentUser == null) {
      await auth.signInAnonymously();
    }

    final images = FirebaseFirestore.instance.collection('images');

    await images.doc('image').set(
      {
        'blob': Blob(bytes),
      },
    );
  }

  Future<void> getDocument(
    FirebaseFirestore firestore,
  ) async {
    final images = FirebaseFirestore.instance.collection('images');

    try {
      final document = await images.doc('image').get();
      if (!document.exists) return;

      final data = document.data();
      setState(() => _data = data);
    } catch (e) {
      setState(() => _error = '${e.toString()}\n${e.stackTrace.toString()}');
      rethrow;
    }
  }

  Future<void> pickImage() async {
    final picker = ImagePicker();

    final file = await picker.pickImage(source: ImageSource.gallery);

    if (file == null) return;

    final Uint8List bytes = await file.readAsBytes();
    setState(() => _bytes = bytes);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter web: CloudFirestore issue'),
      ),
      body: SingleChildScrollView(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const SizedBox(height: 64.0),
              Container(
                width: 100.0,
                height: 100.0,
                child: _bytes == null
                    ? Placeholder()
                    : Image.memory(
                        _bytes,
                      ),
              ),
              const SizedBox(height: 64.0),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: <Widget>[
                  ElevatedButton(
                    onPressed: pickImage,
                    child: const Text(
                      'Pick image',
                    ),
                  ),
                  ElevatedButton(
                    onPressed: _bytes == null
                        ? null
                        : () => uploadDocument(
                              _auth,
                              _firestore,
                              _bytes,
                            ),
                    child: const Text(
                      'Upload document',
                    ),
                  ),
                  ElevatedButton(
                    onPressed: () => getDocument(
                      _firestore,
                    ),
                    child: const Text(
                      'Get document',
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 64.0),
              Text('Document content:\n$_data\n\n\nError:\n$_error'),
            ],
          ),
        ),
      ),
    );
  }
}
```

</details>

---

Before running project:

1. Create Firebase project and add web app
2. Enable Authentication
3. Enable Anonymous Sign-in
4. Enable Firestore
5. Make read access avalible to everyone and write access only to authenticated users
6. Run `flutter pub get`
### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.58.2)
[√] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.4
Flutter SDK 2.2.3
testing 1.0.0+1

dependencies:
- cloud_firestore 2.4.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.2
- firebase_auth 3.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- image_picker 0.8.2 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.3.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.3.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- cross_file 0.3.1+4 [flutter meta]
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 6.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.1 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.2.0 [flutter http meta plugin_platform_interface cross_file]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- pedantic 1.11.1
- plugin_platform_interface 2.0.1 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by markusaksli-nc** [comment]
Was able to reproduce this on web (and not on mobile).
```html
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js"></script
```
```yaml
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
```
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.4.0-5.0.pre.203, on Microsoft Windows [Version 10.0.19041.1110], locale et-EE)
    • Flutter version 2.4.0-5.0.pre.203 at C:\Development\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 738ce43d97 (7 hours ago), 2021-07-26 23:40:49 -0700
    • Engine revision 717d55cdd4
    • Dart version 2.14.0 (build 2.14.0-354.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7486908\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.2)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\202.7486908
    • Flutter plugin version 58.0.1
    • Dart plugin version 202.8531
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.7628.21
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.1110]
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 92.0.4515.107
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.67

• No issues found!
```
</details>

**Comment by andrejvujic** [comment]
Hello Markus, thanks for reviewing my issue. I hope it will be fixed soon, as storing Blobs in Firestore is a required feature in my Flutter web app.

**Comment by russellwheatley** [comment]
Closing this in favour of tracking here: https://github.com/FirebaseExtended/flutterfire/issues/3865. Please check that issue for updates.

**Comment by andrejvujic** [comment]
That issue has been active for over 10 months and it hasn't been fixed yet.
