### ISSUE TITLE
[firebase_auth] FlutterFirebaseAuthPlugin crash! Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod

### ISSUE THREAD

**Issue by a1111198** [FirebaseExtended/flutterfire#6726]
## Bug report
I am using Firebase_auth: 20.0.1 and getting this null reference error in released mode. Not getting in debug mode.

## Stack Traces
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object, io.flutter.plugin.common.MethodChannel$Result)' on a null object reference
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin$3.onCodeAutoRetrievalTimeOut(FlutterFirebaseAuthPlugin.java:856)
       at com.google.android.gms.internal.firebase-auth-api.zzvk.onCodeAutoRetrievalTimeOut(zzvk.java:2)
       at com.google.android.gms.internal.firebase-auth-api.zzuw.zza(zzuw.java:1)
       at com.google.android.gms.internal.firebase-auth-api.zzuy.run(zzuy.java:3)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.google.android.gms.internal.tasks.zzb.dispatchMessage(zzb.java:6)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7948)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

```
### Steps to reproduce
a similar issue is posted here but not going towards any end.
[here](https://github.com/flutter/flutter/issues/70813)
---

**Comment by markusaksli-nc** [comment]
Hi @a1111198 
Please use the latest version of the plugin `firebase_auth: ^3.0.1`. This was fixed in https://github.com/FirebaseExtended/flutterfire/pull/4643
Thank you

**Comment by a1111198** [comment]
I have not upgraded my project to flutter2. so is there any solution around it?

**Comment by markusaksli-nc** [comment]
The solution has already been implemented as I explained. If there is an issue with any plugin you use, the only way you can get a solution is to upgrade to a newer fixed version anyway. You ought to upgrade to flutter 2 for the stability and functionality improvements anyway.
