### ISSUE TITLE
[firebase_storage] partsFromHttp always returning null with some URLs

### ISSUE THREAD

**Issue by Eufranio** [FirebaseExtended/flutterfire#6773]
## Bug report

**Describe the bug**
When calling `storage.refFromURL(url)`, partsFromHttpUrl is called, but throws an error when parsing some URLs. May be related to https://github.com/FirebaseExtended/flutterfire/issues/4727. Example URL: `https://storage.googleapis.com/dochealthdev.appspot.com/pdf/4lqA70lYwfRgH1krOevw6mLMgPs2_162613790513241`

### Steps to reproduce

1. Call `storage.refFromURL('https://storage.googleapis.com/dochealthdev.appspot.com/pdf/4lqA70lYwfRgH1krOevw6mLMgPs2_162613790513241')`.

### Expected behavior

I expect the command to be executed correctly.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PS D:\Dev\IdeaProjects\dochealth> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 2.3.0-24.1.pre, on Microsoft Windows [versÃ£o 10.0.19043.1110], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PS D:\Dev\IdeaProjects\dochealth> flutter pub deps -- --style=compact
Dart SDK 2.14.0-188.5.beta
Flutter SDK 2.3.0-24.1.pre
DocHealth 1.1.55+64

dependencies:
- auto_size_text 2.1.0 [flutter]
- bloc_pattern 3.0.0 [flutter]
- carousel_slider 4.0.0 [flutter]
- characters 1.1.0
- cloud_firestore 2.0.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platfor
m_interface flutter meta]
- cloud_functions 3.0.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platfor
m_interface flutter]
- csv 5.0.0
- cupertino_icons 1.0.2
- device_info 2.0.2 [flutter device_info_platform_interface]
- diacritic 0.1.3
- dio 4.0.0 [http_parser path]
- dotted_border 2.0.0 [flutter path_drawing]
- drag_and_drop_lists 0.3.2 [flutter]
- faker 2.0.0 [crypto]
- file_picker 3.0.1 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 8.0.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta
]
- firebase_auth 3.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_inte
rface flutter meta]
- firebase_core 1.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.0.6 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interfac
e flutter stack_trace]
- firebase_dynamic_links 2.0.2 [firebase_core flutter]
- firebase_messaging 10.0.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface f
irebase_messaging_web flutter meta]
- fl_chart 0.36.1 [flutter equatable pedantic]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_auth_buttons 0.10.0 [flutter]
- flutter_local_notifications 8.0.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_masked_text 0.8.0 [flutter]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- flutter_pdfview 1.0.4 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- font_awesome_flutter 9.0.0 [flutter]
- fullscreen 1.0.3 [flutter]
- geolocator 7.4.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web]
- get_it 7.1.3 [async collection]
- google_sign_in 5.0.4 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- image_picker 0.8.3 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface
]
- lipsum 1.0.1
- mailer 5.0.0 [async logging intl mime path pedantic meta]
- mask_text_input_formatter 2.0.0 [flutter]
- multi_image_picker 4.8.01 [flutter meta]
- native_pdf_view 4.1.0 [flutter photo_view synchronized native_pdf_renderer]
- package_info 2.0.2 [flutter]
- password_strength 0.2.0
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provid
er_windows]
- pdf 3.3.0 [archive barcode crypto image meta path_parsing vector_math xml]
- pdf_render 1.0.9 [flutter flutter_web_plugins device_info js plugin_platform_interface vector_math]
- permission_handler 8.1.4+2 [flutter meta permission_handler_platform_interface]
- provider 5.0.0 [collection flutter nested]
- random_string 2.1.0
- rxdart 0.27.0
- share_extend 2.0.0 [meta flutter]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_pref
erences_macos shared_preferences_web shared_preferences_windows]
- the_apple_sign_in 1.1.1 [flutter]
- timezone 0.7.0 [path]
- tutorial_coach_mark 1.0.0 [flutter]
- wiredash 0.7.0+1 [file flutter http http_parser path_provider shared_preferences]

dev dependencies:
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector charact
ers charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- mockito 5.0.9 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- test 1.17.5 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_co
nfig path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_c
hannel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

dependency overrides:
- firebase_storage 10.0.1 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface fireb
ase_storage_web flutter]
- photo_view 0.11.1 [flutter]

transitive dependencies:
- _fe_analyzer_shared 21.0.0 [meta]
- analyzer 1.5.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver s
ource_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.7.0 [collection meta]
- barcode 2.1.0 [meta qr]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.2 [analyzer async convert crypto glob logging meta path]
- built_collection 5.0.0
- built_value 8.0.6 [built_collection collection fixnum]
- charcode 1.2.0
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.0.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web
_plugins js]
- cloud_functions_platform_interface 5.0.8 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.10 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_we
b_plugins js]
- code_builder 4.0.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- coverage 1.0.2 [args logging package_config path source_maps stack_trace vm_service]
- cross_file 0.3.1+4 [flutter meta]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.1 [analyzer args path pub_semver source_span]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- equatable 2.0.0 [collection meta]
- extension 0.2.0
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.0 [flutter meta]
- firebase_analytics_web 0.3.0 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 6.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plu
gins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.0.6 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.0.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.3 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutt
er_web_plugins js meta]
- firebase_storage_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.0.0 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flu
tter_web_plugins http js meta]
- fixnum 1.0.0
- flutter_local_notifications_platform_interface 4.0.1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- frontend_server_client 2.1.0 [async path]
- geolocator_android 1.0.0 [flutter geolocator_platform_interface]
- geolocator_apple 1.0.0 [flutter geolocator_platform_interface]
- geolocator_platform_interface 2.3.2 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.6 [flutter flutter_web_plugins geolocator_platform_interface]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.13.2 [async http_parser meta path pedantic]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.1.2 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.2.0 [flutter http meta plugin_platform_interface cross_file]
- intl 0.17.0 [clock path]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.4.0
- mime 1.0.0
- native_pdf_renderer 3.1.0 [flutter flutter_web_plugins device_info uuid image js meta extension synchronized]
- nested 1.0.0 [flutter]
- node_preamble 2.0.0
- package_config 2.0.0 [path]
- path_drawing 0.5.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- permission_handler_platform_interface 3.6.1 [flutter meta plugin_platform_interface]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- qr 2.0.0 [meta]
- quiver 3.0.1 [matcher]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_plat
form_interface path_provider_windows]
- shelf 1.1.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.0.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.0 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term
_glyph matcher]
- test_core 0.3.25 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta pa
ckage_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_servic
e yaml matcher test_api]
- typed_data 1.3.0 [collection]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- vm_service 6.2.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.0.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.0.0 [logging]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

```

</details>

---

**Comment by darshankawar** [comment]
@Eufranio 
I am unable to replicate the issue you mentioned. Verified using plugin's official [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) and on latest stable version, I was able to upload local file (image and pdf) as well as a string without any issues.

<img width="688" alt="Screenshot 2021-08-06 at 3 28 55 PM" src="https://user-images.githubusercontent.com/67046386/128493793-077cc41e-9c9e-4962-9b85-a6df2d8919af.png">

You may try the same example and see if it still doesn't work for you.

**Comment by Eufranio** [comment]
> @Eufranio
> I am unable to replicate the issue you mentioned. Verified using plugin's official [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage/firebase_storage/example) and on latest stable version, I was able to upload local file (image and pdf) as well as a string without any issues.
> 
> <img alt="Screenshot 2021-08-06 at 3 28 55 PM" width="688" src="https://user-images.githubusercontent.com/67046386/128493793-077cc41e-9c9e-4962-9b85-a6df2d8919af.png">
> 
> You may try the same example and see if it still doesn't work for you.

Did you try with the example URL I provided?

**Comment by darshankawar** [comment]
@Eufranio 
With that, I get below error:

`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:firebase_storage/src/firebase_storage.dart': Failed assertion: line 120 pos 14: 'parts != null': url could not be parsed, ensure it's a valid storage url`

**Comment by Eufranio** [comment]
@darshankawar yeah that's the error of this bug report. The expected behavior would be no exception, the method should be executed and return correctly.

**Comment by darshankawar** [comment]
Thanks. Below is the exception I get using the url provided by OP:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: 'package:firebase_storage/src/firebase_storage.dart': Failed assertion: line 120 pos 14: 'parts != null': url could not be parsed, ensure it's a valid storage url
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      FirebaseStorage.refFromURL (package:firebase_storage/src/firebase_storage.dart:120:14)
#3      _TaskManager.uploadFile (package:triage/main.dart:79:10)
#4      _TaskManager.handleUploadType (package:triage/main.dart:127:50)
<asynchronous suspension>
Lost connection to device.

```
Verified on latest master (2.5.0-6.0.pre.21) with [latest](https://pub.dev/packages/firebase_storage/install) plugin version. 

Although, the exception doesn't occur using our triage example url. 

Similar issue was raised earlier, https://github.com/FirebaseExtended/flutterfire/issues/4727

cc: @russellwheatley
