### ISSUE TITLE
🐛 [cloud_firestore] FieldPath.documentId is throwing an error with whereNotIn query.

### ISSUE THREAD

**Issue by muddi900** [FirebaseExtended/flutterfire#6789]
## Bug report

I am building an app that queries if a user has been invited to a certain event.

```
myCollectionReference.where(FIeldPath.documentId, whereNotIn: invitees)./*other queries*/
```

The error on iOS is:

```
Reloaded 4 of 1141 libraries in 854ms.
An error occurred while parsing query arguments, this is most likely an error with this SDK. (
	0   CoreFoundation                      0x00000001117cafba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x0000000111674ff5 objc_exception_throw + 48
	2   FirebaseFirestore                   0x000000010cd3a54a _ZN8firebase9firestore4util16ObjcThrowHandlerENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 554
	3   FirebaseFirestore                   0x000000010cd39935 _ZN8firebase9firestore4util5ThrowENS1_13ExceptionTypeEPKcS4_iRKNSt3__112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE + 53
	4   FirebaseFirestore                   0x000000010cd5a7f8 _ZN8firebase9firestore4util20ThrowInvalidArgumentIJEEEvPKcDpRKT_ + 56
	5   FirebaseFirestore                   0x000000010d00fe8e _ZNK8firebase9firestore3api5Query27ParseExpectedReferenceValueERKNS0_5model10FieldValueERKNSt3__18functionIFNS7_12basic_stringIcNS7_11char_traitsIcEENS7_9allocatorIcEEEEvEEE + 126
	6   FirebaseFirestore                   0x000000010d00f71f _ZNK8fireb
Lost connection to device.
Exited (sigterm)
```

The app crashes on iOS.
 

The error on Android:
```
E/FLTFirestoreMsgCodec( 2798): An error occurred while parsing query arguments, this is most likely an error with this SDK.
E/FLTFirestoreMsgCodec( 2798): java.lang.IllegalArgumentException: Invalid query. When querying with FieldPath.documentId() you must provide a valid document ID, but it was an empty string.
E/FLTFirestoreMsgCodec( 2798): 	at com.google.firebase.firestore.Query.parseDocumentIdValue(Query.java:451)
E/FLTFirestoreMsgCodec( 2798): 	at com.google.firebase.firestore.Query.whereHelper(Query.java:415)
E/FLTFirestoreMsgCodec( 2798): 	at com.google.firebase.firestore.Query.whereNotIn(Query.java:388)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readFirestoreQuery(FlutterFirebaseFirestoreMessageCodec.java:375)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readValueOfType(FlutterFirebaseFirestoreMessageCodec.java:239)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:410)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readValueOfType(FlutterFirebaseFirestoreMessageCodec.java:256)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugin.common.StandardMethodCodec.decodeMethodCall(StandardMethodCodec.java:48)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:165)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/FLTFirestoreMsgCodec( 2798): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FLTFirestoreMsgCodec( 2798): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/FLTFirestoreMsgCodec( 2798): 	at android.os.Looper.loop(Looper.java:183)
E/FLTFirestoreMsgCodec( 2798): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/FLTFirestoreMsgCodec( 2798): 	at java.lang.reflect.Method.invoke(Native Method)
E/FLTFirestoreMsgCodec( 2798): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/FLTFirestoreMsgCodec( 2798): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Reloaded 4 of 1141 libraries in 1,192ms.

════════ Exception caught by services library ══════════════════════════════════
The following PlatformException was thrown while de-activating platform stream on channel plugins.flutter.io/firebase_firestore/query/a9479295-df8f-41b6-9826-af3b3ea70152:
PlatformException(error, No active stream to cancel, null, null)

When the exception was thrown, this was the stack
#0      StandardMethodCodec.decodeEnvelope
#1      MethodChannel._invokeMethod
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure>
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════
E/FLTFirestoreMsgCodec( 2798): An error occurred while parsing query arguments, this is most likely an error with this SDK.
E/FLTFirestoreMsgCodec( 2798): java.lang.IllegalArgumentException: Invalid query. When querying with FieldPath.documentId() you must provide a valid document ID, but it was an empty string.
E/FLTFirestoreMsgCodec( 2798): 	at com.google.firebase.firestore.Query.parseDocumentIdValue(Query.java:451)
E/FLTFirestoreMsgCodec( 2798): 	at com.google.firebase.firestore.Query.whereHelper(Query.java:415)
E/FLTFirestoreMsgCodec( 2798): 	at com.google.firebase.firestore.Query.whereNotIn(Query.java:388)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readFirestoreQuery(FlutterFirebaseFirestoreMessageCodec.java:375)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readValueOfType(FlutterFirebaseFirestoreMessageCodec.java:239)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:410)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readValueOfType(FlutterFirebaseFirestoreMessageCodec.java:256)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugin.common.StandardMethodCodec.decodeMethodCall(StandardMethodCodec.java:48)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:165)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/FLTFirestoreMsgCodec( 2798): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/FLTFirestoreMsgCodec( 2798): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/FLTFirestoreMsgCodec( 2798): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/FLTFirestoreMsgCodec( 2798): 	at android.os.Looper.loop(Looper.java:183)
E/FLTFirestoreMsgCodec( 2798): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/FLTFirestoreMsgCodec( 2798): 	at java.lang.reflect.Method.invoke(Native Method)
E/FLTFirestoreMsgCodec( 2798): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/FLTFirestoreMsgCodec( 2798): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): Failed to open event stream
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): java.lang.IllegalArgumentException: An error occurred while parsing query arguments, see native logs for more information. Please report this issue.
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at io.flutter.plugins.firebase.firestore.streamhandler.QuerySnapshotsStreamHandler.onListen(QuerySnapshotsStreamHandler.java:31)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:188)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at android.os.Looper.loop(Looper.java:183)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/EventChannel#plugins.flutter.io/firebase_firestore/query/0c045f52-ead9-4a1e-9d5c-be5c896292ae( 2798): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

════════ Exception caught by services library ══════════════════════════════════
PlatformException(error, An error occurred while parsing query arguments, see native logs for more information. Please report this issue., null, null)
════════════════════════════════════════════════════════════════════════════════

```
The android app gets stuck in the `ConnectionState.waiting` state.

Removing the FieldPath query fixes the issue on both target devices.

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.4 20F71 darwin-arm, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.0)
[✓] Connected device (3 available)
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
dependencies:
- cached_network_image 3.1.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cloud_firestore 2.3.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- firebase_auth 2.0.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 10.0.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- image_picker 0.8.1+4 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- location 4.3.0 [flutter location_platform_interface location_web]
- mapbox_api 1.0.0 [http]
- modal_bottom_sheet 2.0.0 [flutter]
- url_launcher 6.0.6 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- validators 3.0.0
- webview_flutter 2.0.8 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.0 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.2.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.2.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- cross_file 0.3.1+4 [flutter meta]
- crypto 3.0.1 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 5.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 2.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.0.0 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.0 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.2.0 [flutter http meta plugin_platform_interface cross_file]
- intl 0.17.0 [clock path]
- js 0.6.3
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- path 1.8.0
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.3 [file path platform]
- rxdart 0.27.1
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
```

</details>

---

**Comment by darshankawar** [comment]
@muddi900 
Since you didn't provide the complete query, `myCollectionReference.where(FIeldPath.documentId, whereNotIn: invitees)./*other queries*/`, but I am assuming you would be using `orderBy`.  If so, please note that, `whereNotIn` being an inequality filter, the following `orderBy` has to be on the same field.
For example, in your query, you are using `whereNotIn` on `documentId`, so the `orderBy` also has to be on`documentId`.

Please try this and check if it works for you.

**Comment by muddi900** [comment]
I am not using orderBy. The full query is:

```
firestore
                        .collection('users')
                        .where(FieldPath.documentId, whereNotIn: invitees)
                        .where(
                          'tennis_level',
                          isGreaterThanOrEqualTo: minLevel.toDouble(),
                        )
                        .where(
                          'tennis_level',
                          isLessThanOrEqualTo: maxLevel.toDouble(),
                        )
                        .where(
                          'days_available.' + day.toLowerCase(),
                          isEqualTo: true,
                        )
                        .snapshots(),
```

I have added the field path query at the end as well.

**Comment by darshankawar** [comment]
Thanks @muddi900 for the complete query. 
I tried using the same on our sample app like below but it didn't throw the exception, maybe it's not completely hitting the error point.

```
final moviesRef = FirebaseFirestore.instance
    .collection('firestore_example_app').where(FieldPath.documentId, whereNotIn: ['Fantasy'])
.where('category').snapshots();
```

Can you also provide a complete reproducible code sample along with structure of your firestore db that we can mimic to properly verify this ?

**Comment by muddi900** [comment]
I can't provide a complete reproducible code, unfortunately. I have been testing on firebase local emulator. I will test this on live and report back.

**Comment by darshankawar** [comment]
I tried on firebase local emulator using same [query](https://github.com/FirebaseExtended/flutterfire/issues/6789#issuecomment-896738264), but still wasn't able to see the error, maybe it doesn't match the exact db setup. Maybe a sample db setup would be helpful to properly replicate at our end.
