### ISSUE TITLE
🐛 [Firebase Storage] Web Firebase upload not working

### ISSUE THREAD

**Issue by InfinityCoder88** [FirebaseExtended/flutterfire#6795]
Hi, my friends, I'm trying to upload images from a web-based app to firebase storage but I'm not able to can you please guide me on how to fix this issue please, thanks in advance!

**Platform**
- [Chrome] Web
- [Mac OS Big Sur: 11.4 (20F71)] Desktop (Go)

**pubspec.yaml**
```yaml
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.1.1
  firebase_database: ^7.0.0
  file_picker: ^3.0.4
```
**Platform OS version**
Mac OS Big Sur: 11.4 (20F71)

**How are you picking?**
WEB

Please, post the snippet here
```dart
   chooseAndUploadWeb() async {
    pickedFileWeb = await FilePicker.platform.pickFiles();

    if (pickedFileWeb != null) {
      //PlatformFile file = pickedFileWeb.files.first;

      Uint8List fileBytes = pickedFileWeb.files.first.bytes;
      String fileName = pickedFileWeb.files.first.name;

      await fireStorage.FirebaseStorage.instance
          .ref('uploads/$fileName')
          .putData(fileBytes);

      // fireStorage.Reference reference = fireStorage.FirebaseStorage.instance
      //     .ref()
      //     .child('Uploads$getUserName$fileName');
      // fireStorage.UploadTask uploadTask = reference.putData(fileBytes);
      // fireStorage.TaskSnapshot storageSnapShot =
      //     await uploadTask.whenComplete(() {
      //   //Navigator.pop(showDialog().asStream());
      // });

      // await storageSnapShot.ref.getDownloadURL().then((url) {
      //   print('IMAGE URL: ' + url);
      //   tyreImage = url;
      // });

      // print(file.name);
      // //print(file.bytes);
      // print(file.size);
      // print(file.extension);
      // print(file.path);
    } else {
      // User canceled the picker
      print('User canceled the picker!');
    }
  }`
```

**Error Log**
```
TypeError: appImpl.storage is not a function
    at Object.getStorageInstance (http://localhost:51531/packages/firebase_storage_web/src/interop/storage.dart.lib.js:781:65)
    at new firebase_storage_web.FirebaseStorageWeb.new (http://localhost:51531/packages/firebase_storage_web/src/reference_web.dart.lib.js:272:33)
    at firebase_storage_web.FirebaseStorageWeb._nullInstance.delegateFor (http://localhost:51531/packages/firebase_storage_web/src/reference_web.dart.lib.js:218:14)
    at Function.instanceFor (http://localhost:51531/packages/firebase_storage_platform_interface/src/platform_interface/platform_interface_task_snapshot.dart.lib.js:975:83)
    at firebase_storage.FirebaseStorage.__.get [_delegate] (http://localhost:51531/packages/firebase_storage/firebase_storage.dart.lib.js:88:120)
    at firebase_storage.FirebaseStorage.__.ref (http://localhost:51531/packages/firebase_storage/firebase_storage.dart.lib.js:128:58)
    at HomeScreen._HomeScreenState.new._alegeSiUploadWeb (http://localhost:51531/packages/flutter_app/garage_3.dart.lib.js:11574:59)
    at _alegeSiUploadWeb.next (<anonymous>)
    at http://localhost:51531/dart_sdk.js:39230:33
    at _RootZone.runUnary (http://localhost:51531/dart_sdk.js:39087:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:51531/dart_sdk.js:34073:29)
    at handleValueCallback (http://localhost:51531/dart_sdk.js:34633:49)
    at Function._propagateToListeners (http://localhost:51531/dart_sdk.js:34671:17)
    at _Future.new.[_completeWithValue] (http://localhost:51531/dart_sdk.js:34513:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:51531/dart_sdk.js:34536:35)
    at Object._microtaskLoop (http://localhost:51531/dart_sdk.js:39374:13)
    at _startMicrotaskLoop (http://localhost:51531/dart_sdk.js:39380:13)
    at http://localhost:51531/dart_sdk.js:34887:9
```

**Screenshots and/or video**
<img width="1922" alt="Screen Shot 2021-08-03 at 13 06 07" src="https://user-images.githubusercontent.com/6507433/128013200-1028965a-593d-4835-b5e3-15e75b8bd8ea.png">

<img width="603" alt="Screen Shot 2021-08-04 at 19 35 59" src="https://user-images.githubusercontent.com/6507433/128236244-412fe647-f432-4dd2-b9c0-008c6c902042.png">

Yes I do @kekko7072 
<img width="929" alt="Screen Shot 2021-08-04 at 22 08 19" src="https://user-images.githubusercontent.com/6507433/128255103-8733a64d-3701-4b4f-bc8f-e9f3f5fa4ba0.png">

**Flutter Version details**
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-AU)
    • Flutter version 2.2.3 at /Users/InfinityCoder/Documents/flutter
    • Framework revision f4abaa0735 (5 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/InfinityCoder/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131

• No issues found!
```

**Comment by kekko7072** [comment]
I Will try today to find the bug. If I found nothing i Will post a working code.

**Comment by kekko7072** [comment]
@InfinityCoder88  some more info: 
1) Is the storage working on other platforms? As iOS or Android. If not , can you check in firebase if storage roles ( you find them as in firestore ) maybe is blocked by rules. 

2) can you try to print the file's bites and disable the storage code and see if it print the bites. 

3) I don't see nothing grammatically wrong so tomorrow I will try running your code in on of my project with working.

**Comment by markusaksli-nc** [comment]
Hi @InfinityCoder88 
Have you completed https://firebase.flutter.dev/docs/installation/web
Does the issue reproduce on the latest `firebase_storage: ^10.0.1`?
Thank you

**Comment by kekko7072** [comment]
@InfinityCoder88 if you want this is my working code:

```
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;

List<PlatformFile>? _paths;

///THIS open the file explorer
 void _openFileExplorer() async {
    try {
      FilePickerResult? picked = await FilePicker.platform.pickFiles();

      if (picked != null) {
        if (kIsWeb) {
          uploadFile(picked.files.first.bytes!, picked.files.first.extension!);
        } else {
          uploadFile(await File(picked.files.first.path!).readAsBytes(),
              picked.files.first.extension!);
        }
      }
    } on PlatformException catch (e) {
      print("ERROR Unsupported operation" + e.toString());
    } catch (e) {
      print('ERROR' + e.toString());
    }
  }

///THIS upload the file to the storage
  Future<void> uploadFile(Uint8List _data, String extension) async {
    firebase_storage.Reference reference = firebase_storage
        .FirebaseStorage.instance
        .ref('docs/namefile.$extension');

///This shows the status of the upload
    firebase_storage.TaskSnapshot uploadTask = await reference.putData(_data);

///Download url of the file
    String url = await uploadTask.ref.getDownloadURL();

   
    if (uploadTask.state == firebase_storage.TaskState.success) {
     print('done');
    } else {
      print(uploadTask.state);
    }
  }

///BUTTON to invoke the upload
CupertinoButton(  onPressed: () => _openFileExplorer(), child: Text(  "Upload" ),
```

**Comment by InfinityCoder88** [comment]
Thanks @kekko7072 it working now, thanks a lot!!!

**Comment by kekko7072** [comment]
@InfinityCoder88 I'm glad it worked! Please close the issue.

**Comment by markusaksli-nc** [comment]
Closing this as solved
