### ISSUE TITLE
🐛 [cloud_firestore] DocumentSnapshot not working with StreamTransformer

### ISSUE THREAD

**Issue by pazhut** [FirebaseExtended/flutterfire#6798]
My code looks as follow:
```dart
  Stream<PackList> getPackingList(String? id) {
    CollectionReference packingList = _firestore.collection('packingList');

    late Stream documentStream;

    try{
      documentStream = packingList.doc(id).snapshots().transform(
          StreamTransformer<DocumentSnapshot,PackList>.fromHandlers(
              handleData: (DocumentSnapshot documentSnapshot,EventSink<PackList> sink) => mapDocumentToPackList(documentSnapshot,sink)
          )
      );
    } catch(err) {
      print(err);
    }

    documentStream.listen((event) {print(event);});
    return documentStream as Stream<PackList>;
  }
```
i am getting the following error:
```
flutter: type '_StreamHandlerTransformer<DocumentSnapshot<Object?>, PackList>' is not a subtype of type 'StreamTransformer<DocumentSnapshot<Map<String, dynamic>>, dynamic>' of 'streamTransformer'
flutter: #0      LateError._throwLocalNotInitialized (dart:_internal-patch/internal_patch.dart:208:5)
#1      DatabaseProvider.getPackingList (package:pack_me/providers/FireStoreProvider.dart:203:5)
#2      DataBaseRepository.getPackingList (package:pack_me/repositories/DatabaseRepository.dart:22:59)
#3      PackingListBloc.mapGetPackingList (package:pack_me/blocs/packinglist/packing_list_bloc.dart:68:26)
<asynchronous suspension>
```
found many asking about this but no answer yet

can you please help?
```
Flutter Dr:[✓] Flutter (Channel beta, 2.2.2, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-CA)
    • Flutter version 2.2.2 at /Users/pazhutmann/Work/flutter
    • Framework revision d79295af24 (9 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3
```

**Comment by markusaksli-nc** [comment]
Hi @pazhut 
Have you tried declaring the `DocumentSnapshot` in the `StreamTransformer` with the explicit type `DocumentSnapshot<Map<String, dynamic>>`?
Thank you

**Comment by pazhut** [comment]
confirming that the following is working:

return packingList.doc(id).snapshots().transform(
    StreamTransformer<DocumentSnapshot<Map<String,
dynamic>>,PackList>.fromHandlers(
        handleData: (DocumentSnapshot
documentSnapshot,EventSink<PackList> sink) =>
mapDocumentToPackList(documentSnapshot,sink)
    )
);


Thanks for your support

**Comment by markusaksli-nc** [comment]
Glad it helped, closing the issue as solved.
