### ISSUE TITLE
🐛 [firebase_core] Can't use emulator in `integration_test`

### ISSUE THREAD

**Issue by eyalkutz** [FirebaseExtended/flutterfire#6833]
## Bug report

**Describe the bug**
Trying to use the firebase emulator in an integration test results in an error: ```Unhandled Exception: Bad state: Can't call test() once tests have begun running.```

### Steps to reproduce

1. create a flutter project
2. add firebase
3. start the emulator
4. run the following before some test:
```dart
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  // change host and port to match your firebase emulator
  const host = '192.168.0.110';
  firestore.useFirestoreEmulator(host, 8080);
  await auth.useAuthEmulator(host, 9099);
  functions.useFunctionsEmulator(host, 5001);
```

### Expected behavior

I expected the app to connect to the emulator and run the tests

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-001)
    • Flutter version 2.2.3 at C:\developement\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\developement\AndroidSdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\developement\AndroidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\אייל קוץ\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 92.0.902.73

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.4
Flutter SDK 2.2.3
filma 1.0.0+1

dependencies:
- animations 2.0.0 [flutter]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- camera 0.8.1+3 [camera_platform_interface flutter pedantic quiver]
- cloud_firestore 2.4.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.0.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- copy_with_extension 2.0.2
- cupertino_icons 1.0.3
- firebase_auth 3.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_riverpod 0.14.0+3 [collection flutter meta riverpod state_notifier]
- http 0.13.3 [async http_parser meta path pedantic]
- qr_code_scanner 0.5.1 [js flutter flutter_web_plugins]
- qr_flutter 4.0.0 [flutter qr]
- quiver 3.0.1 [matcher]

dev dependencies:
- build_runner 2.0.5 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- copy_with_extension_gen 2.0.2 [analyzer build source_gen copy_with_extension]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service archive async boolean_selector characters charcode clock collection crypto fake_async file matcher meta 
source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math webdriver]
- json_serializable 4.1.3 [analyzer build build_config collection json_annotation meta path source_gen]
- schemafull_firestore_annotations 0.0.1
- schemafull_firestore_generator 0.0.1 [path source_gen code_builder schemafull_firestore_annotations built_collection analyzer build]

transitive dependencies:
- _fe_analyzer_shared 22.0.0 [meta]
- analyzer 1.7.1 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.1.0
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.2 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.3 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.1.0
- built_value 8.0.5 [built_collection collection fixnum]
- camera_platform_interface 2.0.1 [flutter meta plugin_platform_interface cross_file stream_transform]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.3.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.3.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.8 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.10 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.0.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- cross_file 0.3.1+1 [flutter meta]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.1 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 6.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- freezed_annotation 0.14.2 [collection json_annotation meta]
- frontend_server_client 2.1.0 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 2.0.0
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 2.0.0 [meta]
- riverpod 0.14.0+3 [collection freezed_annotation meta state_notifier]
- rxdart 0.26.0
- shelf 1.1.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.2 [analyzer async build dart_style glob meta path pedantic source_span yaml]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.0 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.3.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- vm_service 6.2.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Hi @eyalkutz 
Are you sure this is not just coming from your testing code? It doesn't really look like it should have anything to do with the firebase plugins here.
If you just run the lines you mentioned is it enough to reproduce the issue?
If so can it be isolated to just one of the plugins?
Thank you

**Comment by eyalkutz** [comment]
@markusaksli-nc the error still shows when I only run this:
```dart
void main() async{
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  testWidgets('test',(tester) async{
    expect(1,1);
  });
}
```

**Comment by nilsreichardt** [comment]
Maybe you need also to call  `WidgetsFlutterBinding.ensureInitialized();`

**Comment by eyalkutz** [comment]
@nilsreichardt it did not work.

I changed the code to:
```dart
void main() async{
  WidgetsFlutterBinding.ensureInitialized();
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  testWidgets('test',(tester) async{
    expect(1,1);
  });
}
```
and the error changed to:
```Unhandled Exception: 'package:integration_test/integration_test.dart': Failed assertion: line 146 pos 12: 'WidgetsBinding.instance is IntegrationTestWidgetsFlutterBinding': is not true.```

It seems that flutter does not want me to call ```WidgetsFlutterBinding.ensureInitialized();``` in an integration test. I think I am only supposed to use ```IntegrationTestWidgetsFlutterBinding.ensureInitialized();```.

**Comment by markusaksli-nc** [comment]
Could you provide the full stacktrace of the error?

**Comment by eyalkutz** [comment]
@markusaksli-nc 
```
E/flutter ( 4594): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: Can't call test() once tests have begun running.
E/flutter ( 4594): #0      Declarer._checkNotBuilt (package:test_api/src/backend/declarer.dart:320:5)
E/flutter ( 4594): #1      Declarer.test (package:test_api/src/backend/declarer.dart:165:5)
E/flutter ( 4594): #2      test (package:flutter_test/src/test_compat.dart:167:13)
E/flutter ( 4594): #3      testWidgets (package:flutter_test/src/widget_tester.dart:138:5)
E/flutter ( 4594): #4      main (file:///C:/developement/filma_parent/filma/integration_test/sign_in_test.dart:86:3)
```

**Comment by markusaksli-nc** [comment]
I wasn't able to reproduce the issue with just this code, the test passes without issues.
```dart
import 'package:firebase_core/firebase_core.dart';
import 'package:integration_test/integration_test.dart';
import 'package:flutter_test/flutter_test.dart';

void main() async {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  testWidgets('test', (tester) async {
    expect(1, 1);
  });
}
```

```yaml
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.4.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
```
Are you sure this isn't occurring in one of your other tests?

**Comment by eyalkutz** [comment]
@markusaksli-nc after commenting out all of my existing test code and copy-pasting the code from your last comment just to be sure I am not missing anything I can again confirm that an error shows up that says:
```Unhandled Exception: Bad state: Can't call test() once tests have begun running.```
and the stack trace points to this line:
```dart
  testWidgets('test', (tester) async {
```

**Comment by markusaksli-nc** [comment]
Labeling based on the report for now

**Comment by russellwheatley** [comment]
Hey @eyalkutz, we have a [testing](https://firebase.flutter.dev/docs/testing/testing#integration-tests-using-the-firestore-emulator) document or you can even inspect the [test_driver](https://github.com/FirebaseExtended/flutterfire/tree/b9771f29df80dad53bf5734255ed62517ff9c20b/tests/test_driver) we have setup for Flutterfire. 

Let me know if you have already resolved the issue.
