### ISSUE TITLE
🐛 [cloud_firestore] Firestore emulator fatal crash on hot restart

### ISSUE THREAD

**Issue by KristianBalaj** [FirebaseExtended/flutterfire#6841]
## Bug report

On **web platform running using the emulators**, when running the project for the first time, everything works.
The problem is when I do the hot restart a following error shows up and the app stops working:

<details> 
<summary>console error</summary> 

```console
FirebaseError: Firestore has already been started and its settings can no longer be changed. You can only modify settings before calling any other methods on a Firestore object.
    at new xr (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:48453)
    at yp.rp._setSettings (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:265710)
    at https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:308734
    at Sg.useEmulator (https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js:1:309580)
    at firestore.Firestore._fromJsObject.useEmulator (http://localhost:55876/packages/cloud_firestore_web/src/interop/utils/utils.dart.lib.js:221:28)
    at cloud_firestore_web.FirebaseFirestoreWeb.new.useEmulator (http://localhost:55876/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:747:34)
    at cloud_firestore.FirebaseFirestore.__.useFirestoreEmulator (http://localhost:55876/packages/cloud_firestore/cloud_firestore.dart.lib.js:1378:26)
    at main (http://localhost:55876/packages/bottleshopdeliveryapp/main_web_dev.dart.lib.js:99:50)
    at main.next (<anonymous>)
    at http://localhost:55876/dart_sdk.js:37403:33
    at _RootZone.runUnary (http://localhost:55876/dart_sdk.js:37274:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:55876/dart_sdk.js:32530:29)
    at handleValueCallback (http://localhost:55876/dart_sdk.js:33057:49)
    at Function._propagateToListeners (http://localhost:55876/dart_sdk.js:33095:17)
    at _Future.new.[_completeWithValue] (http://localhost:55876/dart_sdk.js:32943:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55876/dart_sdk.js:32964:35)
    at Object._microtaskLoop (http://localhost:55876/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:55876/dart_sdk.js:37532:13)
    at http://localhost:55876/dart_sdk.js:33303:9
```

</details>

Next, I have to stop the running application and run it again. The hot reload/restart is not working with the firebase.

### Steps to reproduce

Use the following code snipped in your `main` function to use the emulators:

<details> 
<summary>firebase related part of main function</summary>

```dart
.
.
.
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();

await FirebaseAuth.instance
    .useAuthEmulator('localhost', AppEnvironment.devFirebaseAuthPort);
final host = defaultTargetPlatform == TargetPlatform.android
    ? '10.0.2.2'
    : 'localhost';
FirebaseFirestore.instance
    .useFirestoreEmulator(host, AppEnvironment.devFirestorePort);
FirebaseFunctions.instance.useFunctionsEmulator(
  'localhost',
  AppEnvironment.devFunctionsPort,
);
.
.
.
```

</details>

With following package versions in pubspec.yaml

<details> 
<summary>package versions</summary>

```
firebase_core: ^1.5.0
  firebase_messaging: ^10.0.4
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.5.0
  firebase_crashlytics: ^2.1.1
  firebase_analytics: ^8.2.0
  firebase_storage: ^10.0.1
  cloud_functions: ^3.0.0
```

</details>

Following configuration in the emulators.

<details> 
<summary>firebase.json</summary>

```json
{
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ],
    "source": "functions"
  },
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    "functions": {
      "port": 5001
    },
    "firestore": {
      "port": 8000
    },
    "ui": {
      "enabled": true
    },
    "auth": {
      "port": 9000
    }
  }
}
```
</details>

### Expected behavior

The hot reload/restart should work with the emulators.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details> 
<summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.5 20G71 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/kristian/Documents/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/kristian/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 15.0.2+7-27)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.59.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 92.0.4515.131
```

</details>

**Comment by markusaksli-nc** [comment]
Hi @KristianBalaj 
There's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/6216.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you
