### ISSUE TITLE
[📚] I can't use where.isNotEqualTo on flutter_web

### ISSUE THREAD

**Issue by rameklesia** [FirebaseExtended/flutterfire#6849]
![Screenshot_11](https://user-images.githubusercontent.com/70551597/130065425-b511f4f2-4cd9-4d3d-88de-bc7df46b33a1.png)

I can't use where.isNotEqualTo on flutter_web but on android its normal
Code => final query = await users
            .where('keyName',
                isEqualTo: '${text.substring(0, 1).toUpperCase()}')
            .where('email', isNotEqualTo: '${authC.user.value.email!}')
            .get();

Error=> Error: [cloud_firestore/invalid-argument] Invalid value "!=" provided to function Query.where() for its second argument. Acceptable values: <, <=, ==, >=, >, array-contains, in, array-contains-any
    at Object.throw_ [as throw] (http://localhost:7573/dart_sdk.js:5041:11)
    at http://localhost:7573/packages/firebase_core/src/internals.dart.lib.js:81:63
    at _RootZone.runUnary (http://localhost:7573/dart_sdk.js:37274:59)
    at _FutureListener.catchError.handleError (http://localhost:7573/dart_sdk.js:32542:48)
    at handleError (http://localhost:7573/dart_sdk.js:33073:51)
    at Function._propagateToListeners (http://localhost:7573/dart_sdk.js:33099:17)
    at _Future.new.[_completeError] (http://localhost:7573/dart_sdk.js:32949:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:7573/dart_sdk.js:32985:31)
    at Object._microtaskLoop (http://localhost:7573/dart_sdk.js:37526:13)
    at _startMicrotaskLoop (http://localhost:7573/dart_sdk.js:37532:13)
    at http://localhost:7573/dart_sdk.js:33303:9

**Comment by rameklesia** [comment]
Any idea

**Comment by markusaksli-nc** [comment]
Hi @rameklesia 
This looks like a bug report rather than a documentation issue. Please file a new bug report and fill out the template. Also, refrain from using screenshots, and instead please just copy and paste the text in a code block.
Thank you
