### ISSUE TITLE
🐛 [firebase_messaging] NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference

### ISSUE THREAD

**Issue by talent-apps** [FirebaseExtended/flutterfire#6998]
## Bug report

We see the following crash in production:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
       at androidx.localbroadcastmanager.content.LocalBroadcastManager.a(LocalBroadcastManager.java:9)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingPlugin.onDetachedFromEngine(FlutterFirebaseMessagingPlugin.java:4)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:118)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:16)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:11)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:10)
       at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:31)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:90)
       at io.flutter.embedding.android.FlutterActivity.release(FlutterActivity.java:7)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:11)
       at android.app.Activity.performDestroy(Activity.java:8468)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5614)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5674)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8587)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
**This issue happens on multiple Android devices and multiple API versions**

Looking at the plugin code, it seems that `ContextHolder.applicationContext` is `null` and hence `LocalBroadcastManager.getInstance` crashes.

`ContextHolder.applicationContext` is initialized in `FlutterFirebaseMessagingInitProvider`'s `onCreate` method and in `FlutterFirebaseMessagingReceiver`'s `onReceive` method.
 Both are probably not called in this scenario.
 
 The problematic piece of code is:
 ```
  @Override
  public void onAttachedToEngine(FlutterPluginBinding binding) {
    onAttachedToEngine(binding.getApplicationContext(), binding.getBinaryMessenger());
  }

  @Override
  public void onDetachedFromEngine(@NonNull FlutterPluginBinding binding) {
    LocalBroadcastManager.getInstance(ContextHolder.getApplicationContext())
        .unregisterReceiver(this);
  }
 ```

Maybe `onDetachedFromEngine` should also use `binding.getApplicationContext()` instead of `ContextHolder.applicationContext`, just like `onAttachedToEngine`?

**Comment by markusaksli-nc** [comment]
Hi @talent-apps 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by talent-apps** [comment]
Output of `flutter doctor -v`:
```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
    • Flutter version 2.5.0 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (6 days ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\XXX\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\XXX\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.0)
    • VS Code at C:\Users\XXX\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.26.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 93.0.4577.63
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```

@markusaksli-nc 
This crash is a pure Android issue.
Please check our suggested fix. It seems pretty straight forward and could eliminate this crash.

**Comment by markusaksli-nc** [comment]
Since it's a production crash and you have ap proposed fix I can label it. Although have you tried implementing the fix yourself or have you considered submitting a PR?

**Comment by talent-apps** [comment]
@markusaksli-nc 
The overhead to send a PR with one line is just too much.

**Comment by talent-apps** [comment]
@kolotum Thanks for the PR.
