### ISSUE TITLE
🐛 [CLOUD_FIRESTORE] CollectionGroup queries do not generate error message with link for creating index 

### ISSUE THREAD

**Issue by jtmuller5** [FirebaseExtended/flutterfire#7010]
## Bug report

**Describe the bug**
As described in the [documentation](https://firebase.google.com/docs/firestore/query-data/indexing#create_a_missing_index_through_an_error_message), if the required index doesn't exist for your query, an error message with a link to create the index should be displayed in your console. This seems to work fine for regular Collection queries but not for _some_ [CollectionGroup queries](https://firebase.google.com/docs/firestore/query-data/index-overview#queries_supported_by_collection_group_indexes). @Salakar 

I've found that the error message will not be generated if the CollectionGroup query does not have a 'where' clause. If you just try to query a CollectionGroup and order the results, there is no error message.

I found this [other related issue](https://github.com/FirebaseExtended/flutterfire/issues/4545) but it's closed now.

### Steps to reproduce

1. Setup a Flutter app and connect it to a Firebase project
2. Create a collection called 'users' in Firestore
2. Underneath each user document create a collection called 'posts'
3. Add some documents to each collection. For each post document, add a timestamp field called 'timePosted'
4. Query the CollectionGroup 'posts' and order the results by 'timePosted'
`FirebaseFirestore.instance
        .collectionGroup('posts')
        .orderBy('timePosted', descending: true)
        .limit(100)
        .snapshots(); `

5. Attempt to build a ListView using the data from the query above.
```
StreamBuilder<QuerySnapshot<Map<String, dynamic>>>(
                  stream: model.exploreStream,
                  builder: (context, snapshot) {
                    if (snapshot.hasData) {
                      return SliverList(
                        delegate: SliverChildBuilderDelegate(
                          (BuildContext context, int index) {
                            return Builder(builder: (context) {
                              Post post = Post.fromJson(snapshot.data!.docs[index].data());
                              return Entry.opacity(
                                  duration: const Duration(milliseconds: 500),
                                  child: PostCard(post: post));
                            });
                          },
                          childCount: snapshot.data!.docs.length,
                        ),
                      );
                    } else{
                      return SliverToBoxAdapter(
                        child: Container(),
                      ) ;                    }
                  }),
```

Because there is no index for this CollectionGroup query, the UI should not render. At this point the error message with the link to generate the index should appear in the console but it doesn't.

The index for this example should look like this:

![image](https://user-images.githubusercontent.com/47997351/133613832-931bbfe3-bc99-4136-a6d6-58e3b2b7a9d3.png)

### Expected behavior

An error message would be generated with a link to create the CollectionGroup query.

### Sample project

https://github.com/jtmuller5/fractio

Log in with any email/password combo and swipe to the 'Explore' tab. There are currently 4 posts that should display.

---

## Additional context

I've also been seeing the following error message when the query tries to run:
`W/Firestore( 1086): (23.0.3) [WatchStream]: (f0d0df7) Stream closed with status: Status{code=NOT_FOUND, description=Target id not found: 40, cause=null}.`

Another weird thing is that sometimes the UI will flash and show some of the requested documents. When I create the index manually the flashing stops and the UI is rendered as expected.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.22454.1000], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.8.5)
[√] Android Studio (version 4.1)
[√] Android Studio (version 4.2)
[√] Connected device (4 available)

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.0
Flutter SDK 2.5.0
fractio 1.0.0+1

dependencies:
- auto_route 2.3.2 [flutter path collection]
- blurhash 1.0.0 [flutter blurhash_web]
- cached_network_image 3.1.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cloud_firestore 2.5.2 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.0.2 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- connectivity_plus 1.1.0 [flutter meta connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- detectable_text_field 2.0.2 [flutter]
- device_info_plus 2.1.0 [flutter device_info_plus_platform_interface device_info_plus_linux device_info_plus_macos device_info_plus_web device_info_plus_windows]
- dots_indicator 2.0.0 [flutter]
- entry 0.0.5 [flutter flutter_web_plugins simple_animations]
- firebase_auth 3.1.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.9 [firebase_core flutter]
- firebase_messaging 10.0.7 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 0.10.0+5 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- firebase_storage 10.0.3 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_hooks 0.17.0 [flutter]
- flutter_portal 0.4.0 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- gap 2.0.0 [flutter]
- get_it 7.2.0 [async collection]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- google_mobile_ads 0.13.4 [meta flutter]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- image_picker 0.8.4 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- injectable 1.5.0 [get_it]
- json_serializable 5.0.0 [analyzer build build_config collection json_annotation meta path source_gen source_helper]
- mullr_components 0.0.1 [flutter auto_route cloud_firestore crypto connectivity_plus device_info encrypt entry firebase_auth firebase_crashlytics firebase_messaging firebase_remote_config flex_color_picker fluttertoast font_awesome_flutter gap get_it google_fonts google_sign_in hive dart_jsonwebtoken local
_auth mask_text_input_formatter package_info_plus pointycastle rsa_encrypt shared_preferences sign_in_with_apple stacked steel_crypt timeago url_launcher flutter_secure_storage]
- share_plus 2.1.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- sliver_tools 0.2.5 [flutter]
- stacked 2.2.5 [flutter get_it meta provider collection universal_io]
- stacked_hooks 0.2.1 [flutter flutter_hooks provider]
- transparent_image 2.0.0
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher 6.0.10 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- wiredash 0.7.0+1 [file flutter http http_parser path_provider shared_preferences]

dev dependencies:
- auto_route_generator 2.3.2 [build source_gen analyzer path build_runner code_builder dart_style auto_route]
- build_runner 2.1.2 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket
 stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_lints 1.0.4 [lints]
- flutter_native_splash 1.2.3 [args image meta path xml yaml universal_io]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- hive_generator 1.1.1 [build source_gen hive analyzer source_helper]
- injectable_generator 1.5.2 [build source_gen path glob analyzer code_builder dart_style injectable collection]
- json_annotation 4.1.0 [meta]

transitive dependencies:
- _fe_analyzer_shared 25.0.0 [meta]
- analyzer 2.2.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.2.0
- asn1lib 1.0.2
- async 2.8.1 [collection meta]
- blurhash_dart 1.0.2 [image]
- blurhash_web 1.0.0 [blurhash_dart image flutter flutter_web_plugins]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.1.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.1.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.3 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.4.2 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.10 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.12 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- connectivity_plus_linux 1.1.0 [flutter connectivity_plus_platform_interface dbus meta nm]
- connectivity_plus_macos 1.1.0 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.1.0 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.1.0+1 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.1.0 [connectivity_plus_platform_interface flutter]
- convert 3.0.1 [typed_data]
- cross_file 0.3.1+5 [flutter meta]
- crypto 3.0.1 [collection typed_data]
- dart_jsonwebtoken 2.3.0 [crypto pointycastle convert collection]
- dart_style 2.1.0 [analyzer args path pub_semver source_span]
- dbus 0.5.6 [args ffi meta pedantic xml]
- device_info 2.0.2 [flutter device_info_platform_interface]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- device_info_plus_linux 2.1.0 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.1.0 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.1.0 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.0 [device_info_plus_platform_interface ffi flutter win32]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.1.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics 2.2.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_crashlytics_platform_interface 3.1.2 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.0.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.5 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 0.3.0+5 [firebase_core flutter meta plugin_platform_interface]
- firebase_storage_platform_interface 4.0.2 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.0.2 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- flex_color_picker 2.1.2 [flutter]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.3 [flutter]
- flutter_secure_storage 4.2.1 [meta flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- fluttertoast 8.0.8 [flutter flutter_web_plugins]
- font_awesome_flutter 9.1.0 [flutter]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- google_sign_in 5.1.0 [flutter google_sign_in_platform_interface google_sign_in_web meta]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0+2 [flutter flutter_web_plugins google_sign_in_platform_interface js meta]
- graphs 2.0.0
- http 0.13.3 [async http_parser meta path pedantic]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.1.3 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- intl 0.17.0 [clock path]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- lints 1.0.1
- local_auth 1.1.7 [flutter flutter_plugin_android_lifecycle intl meta platform]
- logging 1.0.1
- mask_text_input_formatter 2.0.0 [flutter]
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- nm 0.3.0 [dbus]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- package_info_plus 1.0.6 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.1.1 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.3 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_provider 2.0.3 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_linux 2.0.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.2.0 [meta]
- platform 3.0.2
- plugin_platform_interface 2.0.1 [meta]
- pointycastle 3.3.4 [collection convert js]
- pool 1.5.0 [async stack_trace]
- process 4.2.3 [file path platform]
- provider 5.0.0 [collection flutter nested]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1 [matcher]
- rsa_encrypt 2.0.0 [flutter asn1lib pointycastle]
- rxdart 0.27.2
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.2 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.1 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences 2.0.7 [flutter meta shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 2.0.2 [file meta flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.2 [flutter file meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sign_in_with_apple 3.0.0 [flutter meta]
- simple_animations 3.1.1 [flutter supercharged pedantic]
- sky_engine 0.0.99
- source_gen 1.1.0 [analyzer async build dart_style glob meta path pedantic source_span yaml]
- source_helper 1.2.1 [analyzer collection source_gen]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.0.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- steel_crypt 3.0.0+1 [args pointycastle]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- supercharged 2.0.0 [supercharged_dart flutter]
- supercharged_dart 2.0.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timeago 3.1.0
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.2 [flutter]
- url_launcher_macos 2.0.2 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.2.9 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.2.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment]
Seems reproducible with `cloud_firestore: ^2.5.3`
```dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  print(await FirebaseFirestore.instance.collectionGroup('posts').orderBy('time', descending: true).limit(100).get());
}
```
```
E/flutter ( 6959): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [cloud_firestore/failed-precondition] Operation was rejected because the system is not in a state required for the operation's execution. If performing a query, ensure it has been indexed via the Firebase console.
E/flutter ( 6959): #0      MethodChannelQuery.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:109:7)
E/flutter ( 6959): <asynchronous suspension>
E/flutter ( 6959): #1      _JsonQuery.get (package:cloud_firestore/src/query.dart:390:9)
E/flutter ( 6959): <asynchronous suspension>
E/flutter ( 6959): #2      main (package:triage/main.dart:18:9)
E/flutter ( 6959): <asynchronous suspension>
E/flutter ( 6959): 
```\<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.6.0-6.0.pre.128, on Microsoft Windows [Version 10.0.19043.1165], locale en-GB)
    • Flutter version 2.6.0-6.0.pre.128 at C:\Development\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fa9790ca47 (2 hours ago), 2021-09-17 01:37:03 -0400
    • Engine revision e70febab63
    • Dart version 2.15.0 (build 2.15.0-118.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7678000\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31624.102
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\203.7678000
    • Flutter plugin version 60.1.2
    • Dart plugin version 203.8292
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1165]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 93.0.961.47

• No issues found!
```
</details>
