### ISSUE TITLE
[firebase_database][firebase_animated_list] the method 'insertItem' was called on null

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#712]
here's my widget

```dart
Widget build(BuildContext context) {
    return FirebaseAnimatedList(
      query: FirebaseDatabase.instance
          .reference()
          .child('/users2/$uid/projects')
          .orderByChild('folder')
          .equalTo(null)
          .limitToLast(100),
      sort: (a, b) => (b.key).compareTo(a.key),
      itemBuilder: (_, snap, _animation, index) {
        Project project = Project(snap);

        return FadeTransition(
          opacity: _animation,
          child: Dismissible(
            onDismissed: (d) => _dismiss(d, project),
            key: Key(project.id),
            child: ProjectListItem(project: project),
          ),
        );
      },
    );
  }
```

here's my client side fanout that is triggering this (get new items from public ref, store to private ref)

```dart
  _fanout() async {
    /// get last key
    var snap = await ref.child('projects').orderByKey().limitToLast(1).once();

    /// listen for last 50 since last key
    FirebaseDatabase.instance
        .reference()
        .child('projects')
        .orderByKey()
        .startAt(snap.value?.keys?.first ?? '1')
        .limitToLast(50)
        .onChildAdded
        .listen((Event e) {
      DataSnapshot snap = e.snapshot;
      String pid = snap.key;

      print('update');

      Map<String, dynamic> value = Map.castFrom(snap.value);
      User.instance.ref.child('projects/$pid/').update(value);
    });
```

and here is the error I get every time a new item is pushed to my ref

```
NoSuchMethodError: The method 'insertItem' was called on null.
Receiver: null
Tried calling: insertItem(0, duration: Instance of 'Duration')
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      FirebaseAnimatedListState._onChildAdded (package:firebase_database/ui/firebase_animated_list.dart:176:35)
#2      FirebaseSortedList._onChildAdded (package:firebase_database/ui/firebase_sorted_list.dart:90:5)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330:11)
#5      _DelayedData.perform (dart:async/stream_impl.dart:578:14)
#6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694:11)
#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

note: this only happens when the values from my copy function are coming in quickly. Race condition? If I put in a breakpoint I can get thru all values without triggering this error.

**Comment by kroikie** [comment]
@lukepighetti

The issue at https://github.com/flutter/flutter/issues/20523 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by GrahamDi** [comment]
@kroikie @BondarenkoStas I am also experiencing this on occasion. I am using FirebaseAnimatedList in a chat app and when messages are being exchanged quickly, this error appears:

> [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'insertItem' was called on null. E/flutter (20599): Receiver: null E/flutter (20599): Tried calling: insertItem(0, duration: Instance of 'Duration') 

I also suspect it is a race problem.

**Comment by Salakar** [comment]
Given the age of this issue and there has been a few releases since; I'm going to close this issue in favour of trying the latest release and reporting a new issue with reproducible code if this is still occurring.
