### ISSUE TITLE
🐛 [firebase_messaging] onBackgroundMessage method Is not working

### ISSUE THREAD

**Issue by singlakaran** [FirebaseExtended/flutterfire#7200]
## Bug report

**Describe the bug**
when the app is terminate in android and the notification comes then `onBackgroundMessage` gives an error.

```
E/flutter ( 6200): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 6200): #0      MethodChannelFirebaseMessaging.registerBackgroundMessageHandler (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:180:53)
E/flutter ( 6200): #1      FirebaseMessagingPlatform.onBackgroundMessage= (package:firebase_messaging_platform_interface/src/platform_interface/platform_interface_messaging.dart:102:16)
E/flutter ( 6200): #2      FirebaseMessaging.onBackgroundMessage (package:firebase_messaging/src/messaging.dart:73:31)
```

### Steps to reproduce

 simply use, it always reproduces

### Expected behavior

when a notification comes then the method should execute the function inside `onBackgroundMessage`.

### Sample project

```
 FirebaseMessaging.onBackgroundMessage((message) async {
      print('alalal');
      localNotification.navigate(context, message,
          notificationType: NotificationType.onLaunch);
    });
   ```

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.6 20G165 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.3
Flutter SDK 2.2.2
riyaz_guru 1.1.14+75

dependencies:
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 2.2.2 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- conreality_headset 0.2.0 [flutter]
- cupertino_icons 1.0.3
- date_format 2.0.2
- device_info 2.0.2 [flutter device_info_platform_interface]
- dio 4.0.0 [http_parser path]
- firebase_analytics 8.1.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.7.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 10.0.8 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 0.10.0+2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- fl_chart 0.36.2 [flutter equatable pedantic]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.0.1 [flutter bloc provider]
- flutter_image_compress 1.0.0 [flutter]
- flutter_keyboard_visibility 5.0.2 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_local_notifications 6.0.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_sound 8.1.4 [path_provider logger recase uuid provider flutter_spinkit path synchronized flutter flutter_sound_platform_interface flutter_sound_web]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- fluttertoast 8.0.7 [flutter flutter_web_plugins]
- google_sign_in 5.0.4 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker 0.8.1+1 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- json_annotation 4.0.1
- lottie 1.0.1 [archive characters charcode collection flutter logging meta path vector_math]
- moor_flutter 4.0.0 [moor sqflite path flutter]
- path 1.8.0
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
```

</details>

---

**Comment by basnetjiten** [comment]
Hi, onInitialLink() is not working on the flutter version 2.2.3. I am using firebase_dynamic_links: ^2.0.10; It works when app is installed but when coming from the play it does not work.

**Comment by Farrukh997** [comment]
Hi, guys. Has anyone solved the problem with overriding onBackgroundHandler?

**Comment by Farrukh997** [comment]
Hi, I found a solution it is in here [https://firebase.flutter.dev/docs/messaging/usage/#background-messages](url). It was happening because of writing Function for the handler as anonymous or not writing it at the top level before class.

**Comment by uc-dve** [comment]
I have added this code on AndroidManifest.xml  and now onBackgroundMessage is working fine even if the app is terminated

```
<meta-data
    android:name="flutterEmbedding"
    android:value="2" />
<meta-data
    android:name="com.google.firebase.messaging.default_notification_channel_id"
    android:value="@string/default_notification_channel_id" />
```
    

Now I can receive background messages in main.dart
```
FirebaseMessaging.onBackgroundMessage(backgroundMessageHandler);
static Future<void> backgroundMessageHandler(message) async {
  print(message);
}
```
