### ISSUE TITLE
🐛 [firebase_core] Firebase: No Firebase App '[DEFAULT]'

### ISSUE THREAD

**Issue by cyberpwnn** [FirebaseExtended/flutterfire#7270]
## Bug report

**Describe the bug**
Using Firebase.initializeApp() or not using it doesnt make a difference, fails to load.

main.dart
```dart
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:myguide/ui/screen/home.dart';
import 'package:myguide/ui/screen/login.dart';

late final FirebaseApp firebaseApp;

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  Firebase.initializeApp()
      .then((app) => firebaseApp = app)
      .then((_) => FirebaseAppCheck.instance.activate(
          webRecaptchaSiteKey: '6LdRiP8cAAAAAAcplxBPieXdqrKy0-S2c9pYq1yC'))
      .then((_) {
    print("App: $firebaseApp");
  }).then((_) => runApp(GetMaterialApp(
            title: "MyGuide",
            themeMode: ThemeMode.system,
            theme: ThemeData(),
            darkTheme: ThemeData(),
            scrollBehavior: const ScrollBehavior().copyWith(
              dragDevices: {
                PointerDeviceKind.mouse,
                PointerDeviceKind.stylus,
                PointerDeviceKind.touch
              },
            ),
            color: Colors.blue,
            initialRoute: "/login",
            getPages: [
              GetPage(name: "/", page: () => const HomeScreen()),
              GetPage(name: "/login", page: () => const LoginScreen())
            ],
          )));
}
```

index.html (GH formatter isnt great with html)
https://www.toptal.com/developers/hastebin/cebaconuso.html

### Steps to reproduce

1. Make app
2. Run
```
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
This app is linked to the debug service: ws://127.0.0.1:57463/A-iUhesScGM=/ws
Debug service listening on ws://127.0.0.1:57463/A-iUhesScGM=/ws

 Running with sound null safety 
Debug service listening on ws://127.0.0.1:57463/A-iUhesScGM=/ws
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at Object.u [as app] (https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js:1:18836)
    at Object.app$ [as app] (http://localhost:57424/packages/firebase_core_web/src/interop/core.dart.lib.js:31:101)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:57424/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:833:64)
    at Function.registerWith (http://localhost:57424/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:745:73)
    at Object.registerPlugins (http://localhost:57424/packages/myguide/generated_plugin_registrant.dart.lib.js:21:46)
    at main (http://localhost:57424/web_entrypoint.dart.lib.js:31:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:57424/dart_sdk.js:38659:34)
    at Object._async [as async] (http://localhost:57424/dart_sdk.js:38690:7)
    at main$ (http://localhost:57424/web_entrypoint.dart.lib.js:30:18)
    at http://localhost:57424/main_module.bootstrap.js:19:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:57424/main_module.bootstrap.js:18:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:57424/dwds/src/injected/client.js:8452:21)
    at http://localhost:57424/dwds/src/injected/client.js:24130:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:57424/dwds/src/injected/client.js:4461:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:57424/dwds/src/injected/client.js:11511:12)
    at Object._asyncStartSync (http://localhost:57424/dwds/src/injected/client.js:4425:20)
    at main__closure3.$call$body$main__closure (http://localhost:57424/dwds/src/injected/client.js:24142:16)
    at main__closure3.call$1 (http://localhost:57424/dwds/src/injected/client.js:24069:19)
    at StaticClosure._rootRunUnary (http://localhost:57424/dwds/src/injected/client.js:4823:18)
    at _CustomZone.runUnary$2$2 (http://localhost:57424/dwds/src/injected/client.js:12879:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57424/dwds/src/injected/client.js:12826:14)
    at _ForwardingStreamSubscription._sendData$1 (http://localhost:57424/dwds/src/injected/client.js:12416:19)
    at _ForwardingStreamSubscription._add$1 (http://localhost:57424/dwds/src/injected/client.js:12362:15)
    at _ForwardingStreamSubscription._add$1 (http://localhost:57424/dwds/src/injected/client.js:12695:12)
    at _MapStream._handleData$2 (http://localhost:57424/dwds/src/injected/client.js:12756:12)
    at _ForwardingStreamSubscription._handleData$1 (http://localhost:57424/dwds/src/injected/client.js:12721:20)
    at Object.eval (eval at Closure_forwardCallTo (http://localhost:57424/dwds/src/injected/client.js:1701:14), <anonymous>:3:44)
    at StaticClosure._rootRunUnary (http://localhost:57424/dwds/src/injected/client.js:4823:18)
    at _CustomZone.runUnary$2$2 (http://localhost:57424/dwds/src/injected/client.js:12879:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57424/dwds/src/injected/client.js:12826:14)
    at _ControllerSubscription._sendData$1 (http://localhost:57424/dwds/src/injected/client.js:12416:19)
    at _ControllerSubscription._add$1 (http://localhost:57424/dwds/src/injected/client.js:12362:15)
    at _SyncStreamController._sendData$1 (http://localhost:57424/dwds/src/injected/client.js:12201:32)
    at _SyncStreamController.add$1 (http://localhost:57424/dwds/src/injected/client.js:12082:15)
    at Object.eval (eval at Closure_forwardInterceptedCallTo (http://localhost:57424/dwds/src/injected/client.js:1781:14), <anonymous>:3:45)
    at StaticClosure._rootRunUnary (http://localhost:57424/dwds/src/injected/client.js:4823:18)
    at _CustomZone.runUnary$2$2 (http://localhost:57424/dwds/src/injected/client.js:12879:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57424/dwds/src/injected/client.js:12826:14)
    at _ControllerSubscription._sendData$1 (http://localhost:57424/dwds/src/injected/client.js:12416:19)
    at _ControllerSubscription._add$1 (http://localhost:57424/dwds/src/injected/client.js:12362:15)
    at _SyncStreamController._sendData$1 (http://localhost:57424/dwds/src/injected/client.js:12201:32)
    at _SyncStreamController.add$1 (http://localhost:57424/dwds/src/injected/client.js:12082:15)
    at _GuaranteeSink.add$1 (http://localhost:57424/dwds/src/injected/client.js:23581:25)
    at HtmlWebSocketChannel_closure1.call$1 (http://localhost:57424/dwds/src/injected/client.js:23874:60)
    at _EventStreamSubscription_closure.call$1 (http://localhost:57424/dwds/src/injected/client.js:18042:26)
    at StaticClosure._rootRunUnary (http://localhost:57424/dwds/src/injected/client.js:4829:16)
    at _CustomZone.runUnary$2$2 (http://localhost:57424/dwds/src/injected/client.js:12879:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57424/dwds/src/injected/client.js:12826:14)
    at _CustomZone_bindUnaryCallbackGuarded_closure.call$1 (http://localhost:57424/dwds/src/injected/client.js:13016:25)
    at invokeClosure (http://localhost:57424/dwds/src/injected/client.js:1524:26)
    at WebSocket.<anonymous> (http://localhost:57424/dwds/src/injected/client.js:1543:18)
```

I'm pretty sure im missing some configuration setup for web, but this breaks only in web, seems to work fine with Android.

### Expected behavior

Firebase working

### Sample project

I have provided all of the code required to test this, though it's really just the setup of firebase, It doesnt work.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19043.1237], locale en-US)
    • Flutter version 2.5.0 at C:\Users\cyberpwn\Documents\development\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (7 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\cyberpwn\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Java\jdk-16.0.2\bin\java
    • Java version Java(TM) SE Runtime Environment (build 16.0.2+7-67)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
    • IntelliJ at C:\Users\cyberpwn\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\212.5457.46
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5486

[√] VS Code (version 1.61.2)
    • VS Code at C:\Users\cyberpwn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 93.0.961.47

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.0
Flutter SDK 2.5.0
myguide 1.0.0+1

dependencies:
- cloud_firestore 2.5.4 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.0.5 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- cupertino_icons 1.0.3
- firebase_app_check 0.0.2+3 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.1.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.2.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_database 8.0.1 [firebase_core firebase_database_platform_interface firebase_database_web flutter]
- firebase_messaging 10.0.9 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.7.1+2 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 0.11.0+2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- firebase_storage 10.0.6 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- get 4.3.8 [flutter]
- reactive_forms 10.6.2 [flutter intl]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.4.4 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.12 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.14 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase 9.0.2 [http http_parser js]
- firebase_app_check_platform_interface 0.0.1+7 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.1+7 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.1.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.1.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_platform_interface 0.1.0+1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.1.0+1 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_messaging_platform_interface 3.0.7 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.0.1+5 [firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.0.1+1 [firebase firebase_performance_platform_interface flutter flutter_web_plugins]
- firebase_remote_config_platform_interface 0.3.0+7 [firebase_core flutter meta plugin_platform_interface]
- firebase_storage_platform_interface 4.0.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.0.4 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.0.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

**Comment by darshankawar** [comment]
@cyberpwnn 
Just wondering if this could be due to `app_check` ? Can you try without that plugin and relevant code and see if you still get same error ?

**Comment by cyberpwnn** [comment]
@darshankawar Have you tried it? Can you provide a simple example of how someone would properly setup flutterfire for web? Following the documentation as far as it was written. No, app check does not change a thing (actually, app check doesnt even work anyways)
