### ISSUE TITLE
🐛 [firebase_messaging] Invalid certificate for server (iOS)

### ISSUE THREAD

**Issue by matiszz** [FirebaseExtended/flutterfire#7291]
## Bug report

**Describe the bug**
Trying to implement Firebase Messaging, it works well on Android, but I get this error when running it on iOS:
```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: [firebase_messaging/unknown] The certificate 
for this server is invalid. You might be connecting to a server that is pretending to be 
“device-provisioning.googleapis.com” which could put your confidential information at risk.
```
I need this to send push notifications to my device, and I cannot do it as this is not initializing properly.

<details><summary>Whole error</summary>

```shell
8.8.0 - [Firebase/Analytics][I-ACS023220] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
8.8.0 - [Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID *ID-DELETED*. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
Connection 1: default TLS Trust evaluation failed(-9814)
Connection 1: TLS Trust encountered error 3:-9814
Connection 1: encountered error(3:-9814)
Connection 1: unable to determine interface type without an established connection
Task <*deleted*>.<1> HTTP load failed, 0/0 bytes (error code: -1202 [3:-9814])

... [many lines the same]

Task <*deleted*>.<1> finished with error [-1202] Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be “firebaselogging-pa.googleapis.com” which could put your confidential information at risk." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=(
    "<cert(*ID-DELETED*) s: upload.video.google.com i: GTS CA 1C3>",
    "<cert(*ID-DELETED*) s: GTS CA 1C3 i: GTS Root R1>",
    "<cert(*ID-DELETED*) s: GTS Root R1 i: GlobalSign Root CA>"
), NSErrorClientCertificateStateKey=0, NSErrorFailingURLKey=https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog, NSErrorFailingURLStringKey=https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog, NSUnderlyingError=0x283920510 {Error Domain=kCFErrorDomainCFNetwork Code=-1202 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: *ID-DELETED*>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9814, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9814, kCFStreamPropertySSLPeerCertificates=(
    "<cert(*ID-DELETED*) s: upload.video.google.com i: GTS CA 1C3>",
    "<cert(*ID-DELETED*) s: GTS CA 1C3 i: GTS Root R1>",
    "<cert(*ID-DELETED*) s: GTS Root R1 i: GlobalSign Root CA>"
)}}, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <*deleted*>.<1>"
),


... [Many other lines of the same]

FLTFirebaseMessaging: An error occurred while calling method Messaging#getToken, errorOrNil => {
    NSErrorClientCertificateStateKey = 0;
    NSErrorFailingURLKey = "https://device-provisioning.googleapis.com/checkin";
    NSErrorFailingURLStringKey = "https://device-provisioning.googleapis.com/checkin";
    NSErrorPeerCertificateChainKey =     (
        "<cert(*ID-DELETED*) s: upload.video.google.com i: GTS CA 1C3>",
        "<cert(*ID-DELETED*) s: GTS CA 1C3 i: GTS Root R1>",
        "<cert(*ID-DELETED*) s: GTS Root R1 i: GlobalSign Root CA>"
    );
    NSLocalizedDescription = "The certificate for this server is invalid. You might be connecting to a server that is pretending to be \U201cdevice-provisioning.googleapis.com\U201d which could put your confidential information at risk.";
    NSLocalizedRecoverySuggestion = "Would you like to connect to the server anyway?";
    NSURLErrorFailingURLPeerTrustErrorKey = "<SecTrustRef: *ID-DELETED*>";
    NSUnderlyingError = "Error Domain=kCFErrorDomainCFNetwork Code=-1202 \"(null)\" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTrustRef: *ID-DELETED*>, _kCFNetworkCFStreamSSLErrorOriginalValue=-9814, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9814, kCFStreamPropertySSLPeerCertificates=(\n    \"<cert(*ID-DELETED*) s: upload.video.google.com i: GTS CA 1C3>\",\n    \"<cert(*ID-DELETED*) s: GTS CA 1C3 i: GTS Root R1>\",\n    \"<cert(*ID-DELETED*) s: GTS Root R1 i: GlobalSign Root CA>\"\n)}";
    "_NSURLErrorFailingURLSessionTaskErrorKey" = "LocalDataTask <*ID-DELETED*>.<2>";
    "_NSURLErrorRelatedURLSessionTaskErrorKey" =     (
        "LocalDataTask <*ID-DELETED*>.<2>"
    );
    "_kCFStreamErrorCodeKey" = "-9814";
    "_kCFStreamErrorDomainKey" = 3;
}
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: [firebase_messaging/unknown] The certificate for this server is invalid. You might be connecting to a server that is pretending to be “device-provisioning.googleapis.com” which could put your confidential information at risk.
#0      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:229:7)
<asynchronous suspension>
#1      main._savePushToken (package:my_app/main.dart:79:21)
<asynchronous suspension>
#2      main._askPushNotificationsPermissions (package:my_app/main.dart:108:5)
<asynchronous suspension>
#3      main._configurePushNotifications (package:my_app/main.dart:243:5)
<asynchronous suspension>
#4      main (package:my_app/main.dart:250:3)
<asynchronous suspension>
```
</details>

### Steps to reproduce

1. Create an app following the documentation.
2. Add `NSAppTransportSecurity` to `Info.plist` as suggested [here](https://stackoverflow.com/questions/32755674/ios9-getting-error-an-ssl-error-has-occurred-and-a-secure-connection-to-the-ser).
3. Run the app.

### Expected behavior

It should correctly initiate the app, and I should be able to send Push Notifications to my device.

### Sample project

I cannot provide the whole example. I can provide the `main.dart`:

<details><summary>Click To Expand</summary>

```dart
import 'dart:async';
import 'dart:convert';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/link.dart';
import 'package:url_launcher/url_launcher.dart';
import 'src/app.dart';

const AndroidNotificationChannel channel = AndroidNotificationChannel(
  'MyApp',
  'Notifications',
  importance: Importance.max,
);

final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

RemoteMessage? resultMessage;

Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print("Handling a background message: ${message.messageId}");
}

RequestProvider _provider = RequestProvider();

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SharedPreferences prefs = await SharedPreferences.getInstance();
  await Firebase.initializeApp();

  runApp(/* ... */ );

  _savePushToken(FirebaseMessaging messaging) async {
    String? token = await messaging.getToken();
    if (token != null) {
      print("Push Token: " + token);
    }
  }

  _askPushNotificationsPermissions() async {
    FirebaseMessaging messaging = FirebaseMessaging.instance;
    NotificationSettings settings = await messaging.requestPermission(...);
    await _savePushToken(messaging);
    print('User granted permission: ${settings.authorizationStatus}');
  }

  Future _showNotification(RemoteMessage message) async {
    RemoteNotification? notification = message.notification;
    AndroidNotification? android = message.notification?.android;
    resultMessage = message;

    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(...);
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails();

    var platformChannelSpecifics = new NotificationDetails(
      android: androidPlatformChannelSpecifics,
      iOS: iOSPlatformChannelSpecifics,
    );

    if (notification != null && android != null) {
      await flutterLocalNotificationsPlugin.show(
        notification.hashCode,
        notification.title,
        notification.body,
        platformChannelSpecifics,
      );
    }
  }

  void _handleNotificationOpened(message) {
      /* ... */
  }

  Future onSelectNotification(String? payload) async {
    _handleNotificationOpened(resultMessage);
  }

  Future<void> _onPushNotificationsSetup() async {
    var initializationSettingsAndroid = new AndroidInitializationSettings('@mipmap/ic_launcher');
    var initializationSettingsIOS = new IOSInitializationSettings();

    var initializationSettings = new InitializationSettings(
      android: initializationSettingsAndroid,
      iOS: initializationSettingsIOS,
    );

    flutterLocalNotificationsPlugin.initialize(initializationSettings, onSelectNotification: onSelectNotification);

    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);
  }

  _listenForegroundNotifications() async {
    await _onPushNotificationsSetup();

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print('Got a message whilst in the foreground!');
      print('Message data: ${message.data}');

      if (message.notification != null) {
        print('Message also contained a notification: ${message.notification}');
      }
      _showNotification(message);
    });
  }

  _handleNotificationClick() async {
    _onPushNotificationsSetup();
    FirebaseMessaging.onMessageOpenedApp.listen((message) async {
      print('Message clicked!');
      RemoteMessage? initialMessage = await FirebaseMessaging.instance.getInitialMessage();
      if (initialMessage != null) {
        _handleNotificationOpened(message);
      }
    });
  }

  _listenTerminated() async {
    _onPushNotificationsSetup();
    FirebaseMessaging.instance.getInitialMessage().then((message) => {
          if (message != null) {_handleNotificationOpened(message)}
        });
  }

  _listenBackgroundNotifications() async {
    FirebaseMessaging.onBackgroundMessage(
      _firebaseMessagingBackgroundHandler,
    );
  }

  _configurePushNotifications() async {
    await _askPushNotificationsPermissions();
    await _listenTerminated();
    await _handleNotificationClick();
    await _listenForegroundNotifications();
    await _listenBackgroundNotifications();
  }

  await _configurePushNotifications();
}
```
</details>
---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.2, on macOS 12.0.1 21A559 darwin-arm, locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.3
Flutter SDK 2.5.2
my_app 1.1.53

dependencies:
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.3
- dio 4.0.1 [http_parser path]
- dropdown_search 1.0.4 [flutter]
- expandable_text 2.2.0 [flutter]
- firebase_analytics 8.3.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_core 1.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 10.0.9 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_dotenv 5.0.2 [flutter]
- flutter_html 2.1.5 [html csslib flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter_math_fork collection numerus flutter]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_local_notifications 9.0.1 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_spinkit 5.1.0 [flutter]
- http 0.13.4 [async http_parser meta path]
- image_picker 0.8.4+3 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- intl 0.17.0 [clock path]
- intl_phone_field 2.1.0 [flutter]
- jwt_decode 0.3.1
- location 4.3.0 [flutter location_platform_interface location_web]
- mailto 2.0.0
- multi_select_flutter 4.0.0 [flutter collection]
- package_info 2.0.2 [flutter]
- page_indicator 0.4.1 [flutter]
- shared_preferences 2.0.8 [flutter meta shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- url_launcher 6.0.12 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.6 [crypto path]
- args 2.3.0
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- chewie 1.2.2 [cupertino_icons flutter provider video_player wakelock]
- chewie_audio 1.2.0 [cupertino_icons flutter video_player]
- clock 1.1.0
- collection 1.15.0
- cross_file 0.3.2 [flutter js meta]
- csslib 0.17.1 [source_span]
- dbus 0.5.6 [args ffi meta pedantic xml]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.2 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.7 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_layout_grid 1.0.3 [flutter collection meta quiver]
- flutter_local_notifications_linux 0.3.0 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_math_fork 0.3.3+1 [flutter flutter_svg provider meta collection tuple]
- flutter_plugin_android_lifecycle 2.0.4 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.8 [archive meta xml]
- image_picker_for_web 2.1.4 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- js 0.6.3
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- nested 1.0.0 [flutter]
- numerus 1.1.1
- path 1.8.0
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.1.0 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- process 4.2.4 [file path platform]
- provider 5.0.0 [collection flutter nested]
- quiver 3.0.1+1 [matcher]
- shared_preferences_linux 2.0.2 [file meta flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.2 [flutter file meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.2 [flutter]
- url_launcher_macos 2.0.2 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- vector_math 2.1.0
- video_player 2.2.6 [flutter meta video_player_platform_interface video_player_web html]
- video_player_platform_interface 4.2.0 [flutter flutter_test meta]
- video_player_web 2.0.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- webview_flutter 2.1.2 [flutter webview_flutter_platform_interface webview_flutter_android webview_flutter_wkwebview]
- webview_flutter_android 2.1.0 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.2.0 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.1.0 [flutter webview_flutter_platform_interface]
- win32 2.2.10 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
> 2\. Add `NSAppTransportSecurity` to `Info.plist` as suggested [here](https://stackoverflow.com/questions/32755674/ios9-getting-error-an-ssl-error-has-occurred-and-a-secure-connection-to-the-ser).

This suggestion seems to be from StackOverflow, but the plugin's [readMe](https://pub.dev/packages/firebase_messaging) doesn't mention to add anything like that. Also check and confirm if you have followed all instructions listed [here](https://firebase.flutter.dev/docs/messaging/overview/#4-apple-integration).

**Comment by matiszz** [comment]
The error without the StackOverflow suggestion is the following:

```shell
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: [firebase_messaging/unknown] An SSL error has occurred and a secure connection to the server cannot be made.
#0      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:229:7)
<asynchronous suspension>
#1      main._savePushToken (package:ensayos_app/main.dart:79:21)
<asynchronous suspension>
#2      main._askPushNotificationsPermissions (package:ensayos_app/main.dart:108:5)
<asynchronous suspension>
#3      main._configurePushNotifications (package:ensayos_app/main.dart:243:5)
<asynchronous suspension>
```

And yes, I've followed all the steps in the instructions.

**Comment by darshankawar** [comment]
@matiszz 
Check [this](https://github.com/FirebaseExtended/flutterfire/discussions/5705) discussion thread and see if it sounds similar to your case. Also check underlying comments in it for possible solutions mentioned.

**Comment by matiszz** [comment]
This is somehow embarrassing. Apparently, if you have the wrong date on your iPhone, Apple doesn't allow you to connect to the Internet. It was an old iPhone that I was using so I never used it to go on the Internet. [This answer](https://stackoverflow.com/questions/69485088/error-apns-device-token-not-set-before-retrieving-fcm-token-for-sender-id) made me realize.

**Comment by matiszz** [comment]
-
