### ISSUE TITLE
🐛 [firebase/auth] "An unknown error has occurred" calling signInWithCredential

### ISSUE THREAD

**Issue by shawnlauzon** [FirebaseExtended/flutterfire#7316]
## Bug report

**Describe the bug**
I am integrating with a not-common OAuth provider "hivesigner.com" and want to integrate with Firebase Auth, as I will also be allowing signin with Twitter, Facebook, Apple, etc. When I call `signInWithCredential` and pass in my accessToken, I receive an error. 

### Steps to reproduce

1. Obtain access token from hivesigner
2. Make call as follows to create credential
```
      final oauthCredential = OAuthProvider("hivesigner.com").credential(
        accessToken: accessToken,
        rawNonce: rawNonce,
      );
```
3. Pass credential to firebase:
```
        await _firebaseAuth.signInWithCredential(oauthCredential);
```

4. Get the following response:
```
FLTFirebaseAuth: An error occurred while calling method Auth#signInWithCredential, errorOrNil => (null)
flutter: Failed firebaseAuthException [firebase_auth/unknown] An unknown error has occurred.
flutter: #0      MethodChannelFirebaseAuth.signInWithCredential (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:448:7)
<asynchronous suspension>
#1      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:497:7)
<asynchronous suspension>
#2      AuthenticationRepository.logInWithHivesigner (package:authentication_repository/src/authentication_repository.dart:310:9)
<asynchronous suspension>
#3      LoginCubit.logInWithHivesigner (package:leomobile/login/cubit/login_cubit.dart:52:7)
<asynchronous suspension>
#4      _HivesignerLoginButton.build.<anonymous closure> (package:leomobile/login/view/login_form.dart:80:15)
<asynchronous suspension>
```

### Expected behavior

I expect to receive a proper UserCredentials object.

### Sample project

If needed, I can provide something, but I don't think it is needed.
---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.61.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
authentication_repository 0.0.1

dependencies:
- cache 1.0.0
- crypto 3.0.1 [collection typed_data]
- equatable 2.0.3 [collection meta]
- firebase_auth 3.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- http 0.13.4 [async http_parser meta path]
- json_annotation 4.1.0 [meta]
- meta 1.7.0
- sign_in_with_apple 3.2.0 [flutter meta]
- very_good_analysis 2.4.0

dev dependencies:
- build_runner 2.1.4 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 5.0.2 [analyzer build build_config collection json_annotation meta path source_gen source_helper]
- mocktail 0.2.0 [collection matcher test]

transitive dependencies:
- _fe_analyzer_shared 26.0.0 [meta]
- analyzer 2.3.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- args 2.3.0
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.3 [built_collection collection fixnum meta]
- characters 1.1.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.3 [meta path]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- coverage 1.0.3 [args logging package_config path source_maps stack_trace vm_service]
- dart_style 2.2.0 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.2.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.1.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.2.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 2.1.0 [collection]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- logging 1.0.2
- matcher 0.12.10 [stack_trace]
- mime 1.0.0
- node_preamble 2.0.1
- package_config 2.0.2 [path]
- path 1.8.0
- pedantic 1.11.1
- plugin_platform_interface 2.0.2 [meta]
- pool 1.5.0 [async stack_trace]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.1.0 [checked_yaml collection json_annotation pub_semver yaml]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.1.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.0 [analyzer collection source_gen]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test 1.17.10 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.0 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- vm_service 7.3.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.0.0 [logging]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by hhh123456789** [comment]
I got the same error. Make sure your desired method is enabled in the firebase console eg. anonymous sign-in.

**Comment by darshankawar** [comment]
@shawnlauzon 
Please check above comment and see if it helps to resolve.

**Comment by shawnlauzon** [comment]
I just enabled anonymous sign-in because it was not enabled.

![image](https://user-images.githubusercontent.com/611529/140786193-33ad796c-c82f-4fc6-9806-185a19393498.png)

Unfortunately, still the same problem.

**Comment by darshankawar** [comment]
> I am integrating with a not-common OAuth provider "hivesigner.com"

I think the issue stems from here, as this is regarded as a custom OAuthflow and may not necessarily work / compatible with `firebase_auth`. 

> #2      AuthenticationRepository.logInWithHivesigner (package:authentication_repository/src/authentication_repository.dart:310:9)
> <asynchronous suspension>
> #3      LoginCubit.logInWithHivesigner (package:leomobile/login/cubit/login_cubit.dart:52:7)
> <asynchronous suspension>
> #4      _HivesignerLoginButton.build.<anonymous closure> (package:leomobile/login/view/login_form.dart:80:15)
> <asynchronous suspension>

The error log also seems to be pointing to the third party package you are using. There's a third party plugin that you may try https://pub.dev/packages/firebase_auth_oauth and see if it helps in your case, because the custom OAuthflow as I mentioned earlier, may have something to do with the error you are getting.

**Comment by shawnlauzon** [comment]
Actually `authentication_repository` is my own code as well, just separated into a different package.

> may not necessarily work / compatible with `firebase_auth`

This is what I'm confused about. It seems like there is support for generic OAuth providers, but in that case there should't be a problem with something being incompatible; or if it is incompatible, I should be able to create an adapter to make it compatible, if the error was more detailed than "unknown error".

> There's a third party plugin that you may try https://pub.dev/packages/firebase_auth_oauth and see if it helps in your case

I will try that out and report back here.

**Comment by darshankawar** [comment]
> if the error was more detailed than "unknown error".

yeah, the error maybe a bit general that may lead to confusion, but you may confirm using the plugin and see what you get.

**Comment by shawnlauzon** [comment]
Sorry for the slow reply. I tried the package you mentioned and it didn't work for me. TBH I don't remember what the failure was, but it was even further from working.

I decided to skip trying to integrate the auth flow into firebase and am just managing it myself.

**Comment by darshankawar** [comment]
Thanks for the update. I'll close this for now. If you get a concrete steps to replicate (even better if without any 3rd party plugins), please write in comments and I'll reopen it and address accordingly.
