### ISSUE TITLE
🐛 [Flutter FCM] App crashes when receiving message

### ISSUE THREAD

**Issue by bruchano** [FirebaseExtended/flutterfire#7348]
## Bug report

**Describe the bug**
I was using FCM plugin for my Flutter app. However, whenever I send a new cloud message to the Android Emulator and the emulator receives it (no matter foreground or background message), the app crashes.

### Steps to reproduce

1. Flutter run app with android emulator
2. Go to Firebase Console Cloud Messaging
3. Send new notification to android app
4. Android emulator receives message and crash

Running app
![Screenshot_1636632803](https://user-images.githubusercontent.com/74987219/141297562-5c9e66f1-c831-4282-95cb-52062f614cc3.png)
Receives message
![Screenshot_1636632957](https://user-images.githubusercontent.com/74987219/141297584-0b0812b6-f961-46ea-ac94-cd6f0a0df409.png)

Debug Console:
```
D/FLTFireMsgReceiver( 8228): broadcast received for message
I/flutter ( 8228): foreground
I/flutter ( 8228): 0:1636632854251799%2b0490362b049036
I/flutter ( 8228): null
I/flutter ( 8228): 711822868495
I/flutter ( 8228): {}
I/flutter ( 8228): false
I/flutter ( 8228): Test Android
I/flutter ( 8228): test text

W/example.hellow( 8228): Accessing hidden method Landroid/os/WorkSource;->add(I)Z (unsupported,test-api, reflection, allowed)
W/example.hellow( 8228): Accessing hidden method Landroid/os/WorkSource;->add(ILjava/lang/String;)Z (unsupported,test-api, reflection, allowed)
W/example.hellow( 8228): Accessing hidden method Landroid/os/WorkSource;->get(I)I (unsupported, reflection, allowed)
W/example.hellow( 8228): Accessing hidden method Landroid/os/WorkSource;->getName(I)Ljava/lang/String; (unsupported, reflection, allowed)
D/AndroidRuntime( 8228): Shutting down VM
E/AndroidRuntime( 8228): FATAL EXCEPTION: main
E/AndroidRuntime( 8228): Process: com.example.hellowl, PID: 8228
E/AndroidRuntime( 8228): java.lang.RuntimeException: Unable to create service com.example.hellowl.java.MyFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.example.hellowl.java.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/~~m2wXxo8ihTZ-TNkyljYqQw==/com.example.hellowl-48CVy5Uq-xJXZsPPi5pLjA==/base.apk"],nativeLibraryDirectories=[/data/app/~~m2wXxo8ihTZ-TNkyljYqQw==/com.example.hellowl-48CVy5Uq-xJXZsPPi5pLjA==/lib/arm64, /data/app/~~m2wXxo8ihTZ-TNkyljYqQw==/com.example.hellowl-48CVy5Uq-xJXZsPPi5pLjA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 8228): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
E/AndroidRuntime( 8228): 	at android.app.ActivityThread.access$1700(ActivityThread.java:247)
E/AndroidRuntime( 8228): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
E/AndroidRuntime( 8228): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8228): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 8228): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 8228): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime( 8228): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8228): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 8228): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime( 8228): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.hellowl.java.MyFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/~~m2wXxo8ihTZ-TNkyljYqQw==/com.example.hellowl-48CVy5Uq-xJXZsPPi5pLjA==/base.apk"],nativeLibraryDirectories=[/data/app/~~m2wXxo8ihTZ-TNkyljYqQw==/com.example.hellowl-48CVy5Uq-xJXZsPPi5pLjA==/lib/arm64, /data/app/~~m2wXxo8ihTZ-TNkyljYqQw==/com.example.hellowl-48CVy5Uq-xJXZsPPi5pLjA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime( 8228): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
E/AndroidRuntime( 8228): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 8228): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 8228): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime( 8228): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
E/AndroidRuntime( 8228): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4469)
E/AndroidRuntime( 8228): 	... 9 more
I/Process ( 8228): Sending signal. PID: 8228 SIG: 9
ERROR - 2021-11-11 20:15:42.558095
PUT /XaoYWHtzMrU=/
Error thrown by handler.
Connection closed before full header was received
package:shelf/shelf_io.dart 114:16  handleRequest
Lost connection to device.

```

### Expected behavior

Receive notification for navigation

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.1)
[✓] Connected device (2 available)

• No issues found!

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
hellowl 1.0.0+1

dependencies:
- chewie 1.2.2 [cupertino_icons flutter provider video_player wakelock]
- cloud_firestore 3.1.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.3
- email_validator 2.0.1
- emoji_picker_flutter 1.0.7 [flutter shared_preferences]
- file_picker 4.0.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path]
- firebase_analytics 8.3.3 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 3.1.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.11 [firebase_core flutter]
- firebase_messaging 11.1.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.0.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_easyloading 3.0.3 [flutter flutter_spinkit]
- flutter_html 2.1.4 [html csslib flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter_math_fork collection numerus flutter]
- flutter_keyboard_visibility 5.1.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_local_notifications 9.0.0 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- google_mobile_ads 0.13.2 [meta flutter]
- image_picker 0.8.3+2 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- linkify 4.1.0
- mailto 2.0.0
- path 1.8.0
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pay 1.0.6 [flutter flutter_localizations pay_android pay_ios pay_platform_interface meta]
- provider 5.0.0 [collection flutter nested]
- rxdart 0.27.2
- scrollable_positioned_list 0.2.0-nullsafety.0 [flutter collection]
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- textfield_tags 1.4.2 [flutter]
- toggle_switch 1.2.0 [flutter]
- url_launcher 6.0.10 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.2.3 [flutter meta video_player_platform_interface video_player_web]
- webview_flutter 2.1.2 [flutter webview_flutter_platform_interface webview_flutter_android webview_flutter_wkwebview]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- args 2.3.0
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- chewie_audio 1.2.0 [cupertino_icons flutter video_player]
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.5 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.5.0 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- cross_file 0.3.1+4 [flutter meta]
- csslib 0.17.0 [source_span]
- dbus 0.5.6 [args ffi meta pedantic xml]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 6.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.1.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.1.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.2.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.9 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.1.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.0.3 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_layout_grid 1.0.3 [flutter collection meta quiver]
- flutter_local_notifications_linux 0.3.0 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_math_fork 0.3.3+1 [flutter flutter_svg provider meta collection tuple]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- html 0.15.0 [csslib source_span]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.3 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.3.0 [flutter http meta plugin_platform_interface cross_file]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- nested 1.0.0 [flutter]
- numerus 1.1.1
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.0.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pay_android 1.0.5 [flutter flutter_localizations pay_platform_interface flutter_svg]
- pay_ios 1.0.5 [flutter pay_platform_interface]
- pay_platform_interface 1.0.2 [flutter yaml]
- pedantic 1.11.1
- petitparser 4.3.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.1 [meta]
- process 4.2.3 [file path platform]
- quiver 3.0.1 [matcher]
- shared_preferences_linux 2.0.2 [file meta flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.1 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.2 [flutter file meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.2 [flutter]
- url_launcher_macos 2.0.2 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- vector_math 2.1.0
- video_player_platform_interface 4.2.0 [flutter flutter_test meta]
- video_player_web 2.0.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- webview_flutter_android 2.0.15 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.0.0 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.0.14 [flutter webview_flutter_platform_interface]
- win32 2.2.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by bruchano** [comment]
solved

**Comment by bara1982** [comment]
> solved

Hi @bruchano I have the same issue how did you solved it?

thanks

**Comment by bruchano** [comment]
Forgot how I solved that. But I believe it should be caused by the sdk version or the packages version. You might follow the documentation and reinstall the package. Also check: https://stackoverflow.com/questions/40561289/fcm-integration-getting-the-exception to see it that solves

**Comment by bruchano** [comment]
> > solved
> 
> Hi @bruchano I have the same issue how did you solved it?
> 
> thanks

Forgot how I solved that. But I believe it should either be caused by the sdk version or the packages version. You might follow the documentation and reinstall the package. Also check: https://stackoverflow.com/questions/40561289/fcm-integration-getting-the-exception to see it that solves
