### ISSUE TITLE
🐛 [firebase_performance] iOS crashes and Android throws an error on a hot restart after 0.7.0+8

### ISSUE THREAD

**Issue by MattisBrizard** [FirebaseExtended/flutterfire#7369]
### Steps to reproduce

1. Add `firebase_performance` package
2. Call `FirebasePerformance.instance` somewhere in the code
3. Hot restart the app

---

## Additional context

This is a regression on the changes made by this [PR](https://github.com/flutter/plugins/pull/1763) for this [issue](https://github.com/flutter/flutter/issues/34165).
The fix was to clear the handler list.

This [PR](https://github.com/FirebaseExtended/flutterfire/pull/6851) introduces the regression by removing the clearing of the handlers, resulting in an Exception with message "Object for handle already exists: %s".

**Comment by darshankawar** [comment]
@MattisBrizard 
Can you check if [this](https://github.com/FirebaseExtended/flutterfire/issues/7060) issue is same as yours ? because just running the plugin [example](https://pub.dev/packages/firebase_performance/example) using latest plugin version gives me below error on startup:

```
When the exception was thrown, this was the stack: 
#0      MethodChannelFirebase.app (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:147:5)
#1      Firebase.app (package:firebase_core/src/firebase.dart:55:41)
#2      new FirebasePerformance._ (package:firebase_performance/src/firebase_performance.dart:13:24)
#3      FirebasePerformance.instance (package:firebase_performance/src/firebase_performance.dart:18:67)
#4      FirebasePerformance.instance (package:firebase_performance/src/firebase_performance.dart)
#5      new _MyAppState (package:triage/main.dart:53:58)
#6      MyApp.createState (package:triage/main.dart:21:32)
#7      new StatefulElement (package:flutter/src/widgets/framework.dart:4677:25)
#8      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:737:38)
#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3626:40)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1198:16)
#12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1167:5)
#13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1112:18)
#14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1111:13)
#16     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:944:7)
#17     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:924:7)
(elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

```

While the same works using `^0.6.0+2` plugin version.
