### ISSUE TITLE
🐛 [firebase_dynamic_links] App crash when using FlutterFragmentActivity

### ISSUE THREAD

**Issue by HeshamErfanMDLabs** [FirebaseExtended/flutterfire#7375]
## Bug report

**Describe the bug**
Using (Extending) FlutterFragmentActivity (which is needed by this [flutter_stripe](https://pub.dev/packages/flutter_stripe) package) crashes the app when used with firebase_dynamic_links

This error is shown when trying to resume the app from background using a dynamic link
`The internal FlutterEngine created by FlutterFragment has been attached to by another activity. To persist a FlutterEngine beyond the ownership of this activity, explicitly create a FlutterEngine`

### Steps to reproduce

1. Extend FlutterFragmentActivity in MainActivity.java.
2. Implement firebase_dynamic_links.
3. Open the app using a dynamic link

### Expected behavior
App opens normally

---

## Additional context

**Smartphone / tablet**
 - Device: [Redmi note 6 pro]
 - OS: [Android 9]
 - Package version: [2.0.1]
 - Flutter version [2.5.3]
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1)
[√] VS Code (version 1.51.1)
[√] Connected device (3 available)

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.0
Flutter SDK 2.5.0
new_gene 2.6.0+105

dependencies:
- after_layout 1.1.0 [flutter]
- another_flushbar 1.10.25 [pedantic flutter]
- audio_service 0.18.1 [audio_service_platform_interface audio_service_web audio_session rxdart flutter_cache_manager clock js flutter flutter_web_plugins]
- audioplayers 0.20.1 [uuid path_provider http flutter flutter_web_plugins]
- auto_size_text 3.0.0 [flutter]
- better_player 0.0.76 [flutter cupertino_icons wakelock pedantic meta flutter_widget_from_html_core visibility_detector path_provider collection xml]
- bloc 7.2.1 [meta]
- cached_network_image 3.1.0+1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- country_pickers 2.0.0 [flutter]
- cupertino_icons 1.0.4
- data_connection_checker 0.3.4
- dio 4.0.1 [http_parser path]
- dots_indicator 2.0.0 [flutter]
- equatable 2.0.3 [collection meta]
- firebase_analytics 8.3.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 3.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.3.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 2.0.11 [firebase_core flutter]
- firebase_messaging 11.1.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.7.1+4 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 0.10.0+5 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- flare_flutter 3.0.2 [collection flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.3.3 [flutter bloc provider]
- flutter_branch_sdk 3.5.0 [flutter flutter_web_plugins plugin_platform_interface js]
- flutter_facebook_auth 3.5.6 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_qr_reader 1.0.5 [flutter]
- flutter_sim_country_code 0.1.1 [flutter]
- flutter_staggered_animations 1.0.0 [flutter]
- flutter_statusbarcolor_ns 0.3.0-nullsafety [flutter]
- flutter_stripe 2.0.2 [flutter stripe_android stripe_ios stripe_platform_interface]
- flutter_swiper_null_safety 1.0.2 [flutter]
- flutter_unity_widget 0.1.6+8 [flutter]
- flutter_windowmanager 0.2.0 [flutter]
- fluttertoast 8.0.8 [flutter flutter_web_plugins]
- font_awesome_flutter 9.2.0 [flutter]
- google_api_availability 3.0.1 [flutter meta]
- google_sign_in 5.2.1 [flutter google_sign_in_platform_interface google_sign_in_web meta]
- image_picker 0.8.4+4 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- in_app_review 2.0.3 [flutter in_app_review_platform_interface]
- just_audio 0.9.16 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- libphonenumber 2.0.2 [flutter meta]
- modal_bottom_sheet 2.0.0 [flutter]
- package_info 2.0.2 [flutter]
- permission_handler 8.1.6 [flutter meta permission_handler_platform_interface]
- pin_code_fields 7.3.0 [flutter]
- purchases_flutter 3.5.0 [flutter collection]
- root_check 0.0.2+1 [flutter]
- rsa_encrypt 2.0.0 [flutter asn1lib pointycastle]
- rxdart 0.27.2
- share 2.0.4 [meta mime flutter]
- shared_preferences 2.0.8 [flutter meta shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shimmer 2.0.0 [flutter]
- syncfusion_flutter_pdfviewer 19.3.48-beta [flutter vector_math async http syncfusion_flutter_pdfviewer_platform_interface syncfusion_flutter_pdfviewer_web syncfusion_flutter_pdfviewer_
macos syncfusion_flutter_core syncfusion_flutter_pdf]
- twitter_login 4.0.1 [flutter crypto http]
- url_launcher 6.0.12 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- validators 3.0.0
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- webview_flutter 2.3.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- zendesk 1.0.2 [flutter]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_
scanner term_glyph typed_data]

transitive dependencies:
- asn1lib 1.0.2
- async 2.8.1 [collection meta]
- audio_service_platform_interface 0.1.0 [flutter plugin_platform_interface meta]
- audio_service_web 0.1.1 [audio_service_platform_interface rxdart js flutter flutter_web_plugins]
- audio_session 0.1.6+1 [flutter flutter_web_plugins rxdart meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.1.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- convert 3.0.1 [typed_data]
- cross_file 0.3.2 [flutter js meta]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.1 [source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.2 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 6.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.2.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.1.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.2.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.6 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.0.9 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.1.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.0.1+7 [firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.0.2 [firebase firebase_performance_platform_interface flutter flutter_web_plugins]
- firebase_remote_config_platform_interface 0.3.0+7 [firebase_core flutter meta plugin_platform_interface]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.3 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_facebook_auth_platform_interface 2.7.0 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.6.0+2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_plugin_android_lifecycle 2.0.4 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- flutter_widget_from_html_core 0.7.0 [csslib flutter html]
- freezed_annotation 0.14.3 [collection json_annotation meta]
- google_sign_in_platform_interface 2.1.0 [flutter meta quiver]
- google_sign_in_web 0.10.0+3 [flutter flutter_web_plugins google_sign_in_platform_interface js meta]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.4 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- in_app_review_platform_interface 2.0.2 [flutter url_launcher plugin_platform_interface platform]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.3.0 [meta]
- just_audio_platform_interface 4.0.0 [flutter plugin_platform_interface]
- just_audio_web 0.4.2 [just_audio_platform_interface flutter flutter_web_plugins]
- lints 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- mime 1.0.1
- nested 1.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- path 1.8.0
- path_provider 2.0.6 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_linux 2.1.0 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- pointycastle 3.3.5 [collection convert js]
- process 4.2.4 [file path platform]
- provider 6.0.1 [collection flutter nested]
- quiver 3.0.1+1 [matcher]
- shared_preferences_linux 2.0.2 [file meta flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.2 [flutter file meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.0.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- stripe_android 2.0.2 [flutter]
- stripe_ios 2.0.2 [flutter]
- stripe_platform_interface 2.0.2 [flutter freezed_annotation json_annotation meta plugin_platform_interface]
- syncfusion_flutter_core 19.3.48 [vector_math flutter]
- syncfusion_flutter_pdf 19.3.48-beta [flutter intl xml syncfusion_flutter_core crypto convert]
- syncfusion_flutter_pdfviewer_macos 19.3.48-beta [flutter syncfusion_flutter_pdfviewer_platform_interface]
- syncfusion_flutter_pdfviewer_platform_interface 19.3.48-beta [flutter plugin_platform_interface]
- syncfusion_flutter_pdfviewer_web 19.3.48-beta [flutter flutter_web_plugins js meta syncfusion_flutter_pdfviewer_platform_interface]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.2 [flutter]
- url_launcher_macos 2.0.2 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.5 [crypto]
- vector_math 2.1.0
- visibility_detector 0.2.2 [flutter]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- webview_flutter_android 2.2.1 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.4.0 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.2.0 [flutter webview_flutter_platform_interface]
- win32 2.2.10 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
```

</details>

---

**Comment by darshankawar** [comment]
@HeshamErfanMDLabs 
Thanks for the report. I see that you are on a bit older version of stable and of the plugin. Can you upgrade both to latest (stable 2.5.3) and plugin (3.0.1) and see if you still get same behavior ?
If issue persists, can you also provide full verbose log of the issue that shows the crash entries in it ?

**Comment by HeshamErfanMDLabs** [comment]
Thanks for your reply.
Upgrading to flutter 2.5.3 and firebase_dynamic_links 3.0.1 didn't solve the issue.
The console shows the following error
```D/AndroidRuntime(29443): Shutting down VM
E/AndroidRuntime(29443): FATAL EXCEPTION: main
E/AndroidRuntime(29443): Process: com.jeelapp.android, PID: 29443
E/AndroidRuntime(29443): java.lang.AssertionError: The internal FlutterEngine created by FlutterFragment{de08470} (77c878ec-d2f0-4e2f-84e0-1a3a8f2e4f2c id=0x245a3c5c tag=flutter_fragment) has been attached to by another activity. To persist a FlutterEngine beyond the ownership of this activity, explicitly create a FlutterEngine
E/AndroidRuntime(29443): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.detachFromFlutterEngine(FlutterActivityAndFragmentDelegate.java:590)
E/AndroidRuntime(29443): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.attachToActivity(FlutterEngineConnectionRegistry.java:335)
E/AndroidRuntime(29443): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:176)
E/AndroidRuntime(29443): 	at io.flutter.embedding.android.FlutterFragment.onAttach(FlutterFragment.java:745)
E/AndroidRuntime(29443): 	at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
E/AndroidRuntime(29443): 	at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
E/AndroidRuntime(29443): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
E/AndroidRuntime(29443): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime(29443): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime(29443): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
E/AndroidRuntime(29443): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
E/AndroidRuntime(29443): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
E/AndroidRuntime(29443): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
E/AndroidRuntime(29443): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
E/AndroidRuntime(29443): 	at com.jeelapp.android.MainActivity.onStart(MainActivity.java:405)
E/AndroidRuntime(29443): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1392)
E/AndroidRuntime(29443): 	at android.app.Activity.performStart(Activity.java:7252)
E/AndroidRuntime(29443): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
E/AndroidRuntime(29443): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
E/AndroidRuntime(29443): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
E/AndroidRuntime(29443): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
E/AndroidRuntime(29443): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime(29443): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
E/AndroidRuntime(29443): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29443): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(29443): 	at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(29443): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29443): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(29443): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
W/jeelapp.androi(29443): Unknown chunk type '200'.
I/Process (29443): Sending signal. PID: 29443 SIG: 9```

**Comment by maheshmnj** [comment]
@HeshamErfanMDLabs please share the complete logs of `flutter run -v` (preferably in a text file).
