### ISSUE TITLE
Firebase Messaging : Failed to get FIS auth token [firebase_messaging/unknown] java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR 

### ISSUE THREAD

**Issue by Harshil-d** [FirebaseExtended/flutterfire#7383]
I have a requirement to transfer my whole project from one account to another account ( first I create a project in my private account and start developing, now I want to transfer it to my company account and make it public).

so I create a new project in the new account and start with an android application, First I delete the android app from the old project then create an app with the same package name in the new project. and I simply replace my google-services.json on my android project.

after that run project, firebase authentication is running. but on generating the FCM token, I got an error. (it's been 7 hours since deleted the app from an old project.)

FCM_TOKEN = (await _firebaseMessaging.getToken())!;

get below error on getToken() call function. how can I solve it?

```
Failed to get FIS auth token
E/FirebaseMessaging( 6483): java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseMessaging( 6483): 	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@17.2.1:5)
E/FirebaseMessaging( 6483): 	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@17.2.1:8)
E/FirebaseMessaging( 6483): 	at com.google.firebase.messaging.GmsRpc.setDefaultAttributesToBundle(com.google.firebase:firebase-messaging@@23.0.0:10)
E/FirebaseMessaging( 6483): 	at com.google.firebase.messaging.GmsRpc.startRpc(com.google.firebase:firebase-messaging@@23.0.0:1)
E/FirebaseMessaging( 6483): 	at com.google.firebase.messaging.GmsRpc.getToken(com.google.firebase:firebase-messaging@@23.0.0:1)
E/FirebaseMessaging( 6483): 	at com.google.firebase.messaging.FirebaseMessaging.lambda$blockingGetToken$9$com-google-firebase-messaging-FirebaseMessaging(com.google.firebase:firebase-messaging@@23.0.0:1)
E/FirebaseMessaging( 6483): 	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda5.start(Unknown Source:6)
E/FirebaseMessaging( 6483): 	at com.google.firebase.messaging.RequestDeduplicator.getOrStartGetTokenRequest(com.google.firebase:firebase-messaging@@23.0.0:6)
E/FirebaseMessaging( 6483): 	at com.google.firebase.messaging.FirebaseMessaging.blockingGetToken(com.google.firebase:firebase-messaging@@23.0.0:7)
E/FirebaseMessaging( 6483): 	at com.google.firebase.messaging.FirebaseMessaging.lambda$getToken$3$com-google-firebase-messaging-FirebaseMessaging(com.google.firebase:firebase-messaging@@23.0.0:1)
E/FirebaseMessaging( 6483): 	at com.google.firebase.messaging.FirebaseMessaging$$ExternalSyntheticLambda10.run(Unknown Source:4)
E/FirebaseMessaging( 6483): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/FirebaseMessaging( 6483): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FirebaseMessaging( 6483): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/FirebaseMessaging( 6483): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseMessaging( 6483): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseMessaging( 6483): 	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@17.6.0:2)
E/FirebaseMessaging( 6483): 	at java.lang.Thread.run(Thread.java:923)
E/FirebaseMessaging( 6483): Caused by: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.
E/FirebaseMessaging( 6483): 	at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.createFirebaseInstallation(FirebaseInstallationServiceClient.java:158)
E/FirebaseMessaging( 6483): 	at com.google.firebase.installations.FirebaseInstallations.registerFidWithServer(FirebaseInstallations.java:533)
E/FirebaseMessaging( 6483): 	at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:388)
E/FirebaseMessaging( 6483): 	at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2$FirebaseInstallations(FirebaseInstallations.java:377)
E/FirebaseMessaging( 6483): 	at com.google.firebase.installations.-$$Lambda$FirebaseInstallations$VZq1h0TBcWNH8Y5yY86ujrFFyLo.run(Unknown Source:4)
E/FirebaseMessaging( 6483): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FirebaseMessaging( 6483): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FirebaseMessaging( 6483): 	... 1 more
```

**Comment by infocodiste** [comment]
I'm also getting the same error "java.io.IOException: FIS_AUTH_ERROR"

**Comment by darshankawar** [comment]
@Harshil-d 
This doesn't seem to be an issue with the messaging plugin, but could be due to combination of your setup / configuration that you mentioned and firebase itself. For your reference, there have been similar issues reported with solutions. Check them and see if any of them helps to resolve issue at your end:

https://github.com/FirebaseExtended/flutterfire/issues/2120
https://github.com/FirebaseExtended/flutterfire/issues/3163
https://github.com/FirebaseExtended/flutterfire/issues/6550
https://github.com/FirebaseExtended/flutterfire/issues/7072
https://stackoverflow.com/a/60567987
