### ISSUE TITLE
🐛 [Firebase_auth] Microsoft log in android: FirebaseAuthError, An internal error has occurred. [ INVALID_APP_ID ]

### ISSUE THREAD

**Issue by prggTheProgrammer** [FirebaseExtended/flutterfire#7394]
## Bug report
edit: the test project described below works, I'm checking the diffrences between this test and my real program with the error.

**Describe the bug**
I am trying to intergrate microsoft log in in to my flutter project. It already works on web and ios but it gives FirebaseAuthError, An internal error has occurred. [ INVALID_APP_ID ] when I try it on android.

**Full error:**
```console
W/System  (14532): Ignoring header X-Firebase-Locale because its value was null.
W/[project_name](14532): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
W/[project_name](14532): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
W/[project_name](14532): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
I/[project_name](14532): Background young concurrent copying GC freed 5765(507KB) AllocSpace objects, 4(208KB) LOS objects, 12% free, 3780KB/4326KB, paused 1.630ms total 238.415ms
W/[project_name](14532): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
W/[project_name](14532): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
W/[project_name](14532): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
E/FirebaseAuth(14532): [GetAuthDomainTask] Error getting project config. Failed with INVALID_APP_ID 400
I/[project_name](14532): Background young concurrent copying GC freed 6394(397KB) AllocSpace objects, 2(104KB) LOS objects, 14% free, 3689KB/4326KB, paused 693us total 208.422ms
E/flutter (14532): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(FirebaseAuthError, An internal error has occurred. [ INVALID_APP_ID ], com.google.firebase.FirebaseException: An internal error has occurred. [ INVALID_APP_ID ]
E/flutter (14532): 	at com.google.android.gms.internal.firebase-auth-api.zzto.zza(com.google.firebase:firebase-auth@@21.0.1:4)
E/flutter (14532): 	at com.google.firebase.auth.internal.zzav.onReceive(com.google.firebase:firebase-auth@@21.0.1:19)
E/flutter (14532): 	at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
E/flutter (14532): 	at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
E/flutter (14532): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/flutter (14532): 	at android.os.Looper.loop(Looper.java:223)
E/flutter (14532): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (14532): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14532): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (14532): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (14532): , null)
E/flutter (14532): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (14532): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (14532): <asynchronous suspension>
E/flutter (14532): #2      MethodChannelFirebaseAuthOAuth.signInOAuth (package:firebase_auth_oauth_platform_interface/method_channel_firebase_auth_oauth.dart:44:18)
E/flutter (14532): <asynchronous suspension>
E/flutter (14532): #3      MyPage.signinWithMicrosoft (package:schoolstrijd/microsoft_auth.dart:35:12)
E/flutter (14532): <asynchronous suspension>
E/flutter (14532): 
```

### Steps to reproduce

1. flutter create bug
2. cd bug/android
3. gradlew signinreport
4. get sha-1 and sha-256
5. change  applicationId in app/build.gradle
6. Stuff outside of flutter:
- Created a new app registration in microsft azure portal
- added a secret
- added the redirect url for android with the hash converted from running gradlew singinreport and the package name
- copied client-id and client-secret to firebase
- Added sha-1 and sha-256 certificate fingerprints to android app in firebase console
- downloaded google-services.json and added it to /android/app
7. add dependencies to pubspec.yaml:
```
firebase_auth: ^3.0.1
firebase_auth_oauth: ^1.0.3
```
8. Use this porgram:
<details><summary>Click To Expand</summary>

```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:firebase_auth_oauth/firebase_auth_oauth.dart';
import 'package:firebase_core/firebase_core.dart';

void main(){
  runApp(MicrosoftApp());
}

class MicrosoftApp extends StatelessWidget{
  @override
  Widget build(BuildContext context) {
    Firebase.initializeApp();
    return MaterialApp(
      title: "Testing microsoft autentication",
      home: MyPage(),
    );
  }
}

class MyPage extends StatelessWidget {
  OAuthCredential? cred;

  Widget build(BuildContext context) {
    return Center(child: TextButton(
      onPressed: signinWithMicrosoft,
      child: Text("Sing in"),
    ),
    );
  }


  void signinWithMicrosoft() async {
    cred = await FirebaseAuthOAuth().signInOAuth(
        "microsoft.com", ["email openid", "profile", "People.Read"],
        {'tenant': 'X-X-X-X-X'});
   print("Signed in with microsft: $cred");
  }
}
```

</details>

### Expected behavior

When I press the sign in button, I expected it to go to google show the microsoft sign-in and then redirect back to the app and print the credentialds.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by maheshmnj** [comment]
Hi @prggTheProgrammer, looking at the code sample it looks like you are using a third-party plugin [firebase_auth_oauth](https://github.com/amrfarid140/firebase_auth_oauth), Issues related to it must be filed with the maintainer.

Closing as this isn't an issue with flutterfire if you disagree feel free to write in the comments and I will reopen it.

Thank you.

**Comment by prggTheProgrammer** [comment]
Thanks I will make an issue there. Just so you the sample already works and I used that to make my project work, but it is still a bit weird and does not always work.
