### ISSUE TITLE
🐛 [firebase_storage] SocketException: OS Error: Connection reset by peer, errno = 104, address = firebasestorage.googleapis.com, port = 48310

### ISSUE THREAD

**Issue by ctykaya** [FirebaseExtended/flutterfire#7403]
Cannot display any network image that are uploaded to Firebase Storage. Throws socket exception.
When I connect with VPN all everything works as expected. 
There is general problem in TURKEY. Other developers around Turkey report the same problem.

Also trying to get download url throw an exception. Sign in or Sign out result is same.
Here is the log:
```
W/ExponenentialBackoff( 6677): network unavailable, sleeping.
E/StorageUtil( 6677): error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.
W/NetworkRequest( 6677): no auth token for request
W/NetworkRequest( 6677): No App Check token for request.
V/NativeCrypto( 6677): SSL handshake aborted: ssl=0xb4000073a73c4988: I/O error during system call, Connection reset by peer
W/NetworkRequest( 6677): error sending network request GET https://firebasestorage.googleapis.com/v0/b/aradiginhersey.appspot.com/o/ads%2FyXTZ4QWAjWjvcxPTbqCz%2FIMG-20211027-WA0031.jpg
W/NetworkRequest( 6677): javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xb4000073a73c4988: I/O error during system call, Connection reset by peer
W/NetworkRequest( 6677): 	at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/NetworkRequest( 6677): 	at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@214218046@21.42.18 (150400-410302452):6)
W/NetworkRequest( 6677): 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@214218046@21.42.18 (150400-410302452):16)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
W/NetworkRequest( 6677): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
W/NetworkRequest( 6677): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:417)
W/NetworkRequest( 6677): 	at com.google.firebase.storage.network.NetworkRequest.performRequestStart(NetworkRequest.java:250)
W/NetworkRequest( 6677): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:270)
W/NetworkRequest( 6677): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:289)
W/NetworkRequest( 6677): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:113)
W/NetworkRequest( 6677): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:68)
W/NetworkRequest( 6677): 	at com.google.firebase.storage.GetDownloadUrlTask.run(GetDownloadUrlTask.java:77)
W/NetworkRequest( 6677): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/NetworkRequest( 6677): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/NetworkRequest( 6677): 	at java.lang.Thread.run(Thread.java:923)
```

### Steps to reproduce
1. Create a Project
2. Add network image widget
Example: `Image.network("https://firebasestorage.googleapis.com/v0/b/aradiginhersey.appspot.com/o/ads%2FyXTZ4QWAjWjvcxPTbqCz%2FIMG-20211027-WA0040.jpg?alt=media&token=b0fa40ff-92ca-4e1a-8d68-82ea25db7470")`
3. See the error on screen.
4. This image can be displayed on browser.
### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Package Version: firebase_storage: ^10.1.0

[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale tr-TR)
• Flutter version 2.5.3 at /Volumes/ExtremeSSD/Sdklar/flutter
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 18116933e7 (5 weeks ago), 2021-10-15 10:46:35 -0700
• Engine revision d3ea636dc5
• Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
• Android SDK at /Volumes/ExtremeSSD/Sdklar/Android/sdk
• Platform android-31, build-tools 31.0.0
• Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 12.4, Build version 12D4e
• CocoaPods version 1.11.2

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.59.1)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.62.3)
• VS Code at /Volumes/ExtremeSSD/Uygulamalar/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] VS Code (version 1.47.3)
• VS Code at /Volumes/ExtremeSSD/Yedekler/Downloads/Visual Studio Code.app/Contents
• Flutter extension can be installed from:
🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
• Redmi Note 9 Pro (mobile) • 7c575471 • android-arm64 • Android 11 (API 30)
• macOS (desktop) • macos • darwin-x64 • Mac OS X 10.15.7 19H15 darwin-x64
• Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
image_test 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- lints 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- path 1.8.0
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0

```

</details>

---

Cloud anyone help?

**Comment by ersanKolay** [comment]
I faced the same error. It's about Google Servers. When I conveyed this situation to them, they stated that they were aware of it and that they were working to fix the problem. For now, the situation has improved with the Turkcell internet provider, but the problem continues for TurkTelekom. I hope it will be fixed soon.

**Comment by maheshmnj** [comment]
Hi @ctykaya, Thanks for filing the issue.

> When I connect with VPN all everything works as excepted.

So this seems to be an issue with your ISP, Unfortunately, the plugin has no control over this.  Closing this issue as invalid if you disagree feel free to write in the comments and I will reopen it.

Thank you.
