### ISSUE TITLE
🐛 [cloud_firestore] Firestore or Firebase_auth do not work after deploying to Google Play

### ISSUE THREAD

**Issue by YuriiVasylyshyn** [FirebaseExtended/flutterfire#7429]
## Bug report

**Describe the bug**

I've tried to upload signed app bundle for internal testing on play console and faced the issue 'The caller does not have permission to execute the specified operation.' (also happens for apk file). However app work fine on debug mode and release. Also i've tried on real devices and emulators to run app by `flutter run` command and by installing apk and it works well. Issue happens only when trying to upload any of file types to PlayConsole.
Updating firestore rules also do not help.

Sample of service created:
```
class FirebaseDatabaseManager {
  static final FirebaseFirestore firestore = FirebaseFirestore.instance;
  static const String _usersDB = 'Users';

  static CollectionReference getUsersCollection() {
    return firestore.collection(_usersDB);
  }
}
```
Sample of using:
```
    await FirebaseDatabaseManager.getUsersCollection() 
        .doc(deviceId)
        .update({'showNotifications': turnNotifications});
```

### Steps to reproduce

1. Go to 'Android Studio'
2. Generate signed .aab or .apk file
3. Upload for internal testing on Google Play Console
4. Push download link and install app through the Play Market on emulator or real device
5. Run app and face the issue.

### Expected behavior

Should update or set data to firestore without any problem

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale
    uk-UA)
    • Flutter version 2.5.3 at
      /Users/yura_vasylyshyn/documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (6 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/yura_vasylyshyn/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 31) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 96.0.4664.55

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
dexfolio 1.0.4+47

dependencies:
- bottom_sheet 1.0.3 [flutter]
- cached_network_image 3.1.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cloud_firestore 3.1.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- device_info 2.0.2 [flutter device_info_platform_interface]
- dio 4.0.3 [http_parser path]
- extended_text 7.0.0 [extended_text_library flutter]
- firebase_analytics 8.3.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 3.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.3.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 11.1.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_remote_config 0.11.0+2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_keyboard_visibility 5.1.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keychain 2.1.0 [flutter]
- flutter_local_notifications 8.2.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- flutter_switch 0.3.2 [flutter]
- form_field_validator 1.1.0 [flutter intl]
- freshchat_sdk 0.9.2 [flutter]
- get 4.3.8 [flutter]
- internet_connection_checker 0.0.1+3
- intl 0.17.0 [clock path]
- json_annotation 4.3.0 [meta]
- keyboard_attachable 2.0.1 [flutter flutter_keyboard_visibility]
- number_display 3.0.0
- package_info_plus 1.0.6 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- pie_chart 5.1.0 [flutter]
- pointycastle 3.3.4 [collection convert js]
- retrofit 2.2.0 [dio meta]
- shared_preferences 2.0.8 [flutter meta shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- syncfusion_flutter_charts 19.3.48 [flutter intl vector_math syncfusion_flutter_core]
- url_launcher 6.0.12 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.4 [crypto]
- validators 3.0.0

dev dependencies:
- build_runner 2.1.5 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 6.0.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- pedantic 1.11.1
- retrofit_generator 2.2.0 [dio source_gen built_collection code_builder tuple retrofit analyzer dart_style build]

dependency overrides:
- convert 3.0.1 [typed_data]

transitive dependencies:
- _fe_analyzer_shared 26.0.0 [meta]
- analyzer 2.3.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- args 2.3.0
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.1.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.5 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.5.0 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.0 [analyzer args path pub_semver source_span]
- device_info_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- extended_text_library 7.0.0 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 6.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.2.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.1.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.2.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.6 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.0.9 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.1.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_remote_config_platform_interface 0.3.0+7 [firebase_core flutter meta plugin_platform_interface]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_local_notifications_platform_interface 4.0.1 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.0 [async collection file path pedantic string_scanner]
- graphs 2.1.0 [collection]
- http 0.13.3 [async http_parser meta path pedantic]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- logging 1.0.2
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- mime 1.0.0
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.1.1 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.3 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- petitparser 4.3.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.1.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1 [matcher]
- rxdart 0.27.2
- shared_preferences_linux 2.0.2 [file meta flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.2 [flutter file meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.1.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.0 [analyzer collection source_gen]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- syncfusion_flutter_core 19.3.48 [vector_math flutter]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- timing 1.0.0 [json_annotation]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.1 [flutter]
- url_launcher_macos 2.0.1 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.2 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.1 [flutter]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by YuriiVasylyshyn** [comment]
UPDATE: Maybe issue can be connected to anonymous sign in, as I use it before calling firestore.

**Comment by darshankawar** [comment]
@YuriiVasylyshyn 
The issue you are getting `'The caller does not have permission to execute the specified operation.'` can you provide the entire error log showing it ?
Did you confirm that the database rules are correct to handle release versions of the app ?
Can you also confirm if you are setting `currentUser` before `authStateChanges` ?

**Comment by YuriiVasylyshyn** [comment]
@darshankawar 
1. Log:
```
E/flutter (16225): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [cloud_firestore/permission-denied] The 
caller does not have permission to execute the specified operation.
E/flutter (16225): #0      MethodChannelDocumentReference.update (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:60)
E/flutter (16225): <asynchronous suspension>
E/flutter (16225): #1      AlertController.showPortfolio (package:dexfolio/app/modules/alerts/controllers/alert_controller.dart:37)
E/flutter (16225): <asynchronous suspension>
E/flutter (16225):
```
2. It works well till Friday 26.11.2021, no changes were made. We have a released app version working well, we decided to launch open testing and pushed new update then it stops working.
Rules code:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read: if request.auth.uid != null;
    }
    
    match /Users/{deviceId} {
      allow update: if request.auth != null && request.auth.uid == resource.data.uid;
    }
    
    match /Users/{deviceId}/tokens/{document=**}{
    	allow update: if get(/databases/$(database)/documents/Users/$(deviceId)).data.uid 
      									== request.auth.uid;
    }
  }
}
```
3.  First of all I create an auth instance
`static final FirebaseAuth _auth = FirebaseAuth.instance;`
  
  and then call anonymous sign in:
```
    static Future<User?> signInAnon() async {
    try {
      final result = await _auth.signInAnonymously();
      final user = result.user;
      Session.set('uid', user?.uid);
      return user;
    } catch (e) {
      return null;
    }
  }
```

**Comment by YuriiVasylyshyn** [comment]
@darshankawar any ideas?

**Comment by YuriiVasylyshyn** [comment]
@darshankawar Fixed, need to update signing methods in `android/build.gradle` file. Works fine now
