### ISSUE TITLE
🐛 [firebase_messaging] App keeps crashing since new version

### ISSUE THREAD

**Issue by LasseRosenow** [FirebaseExtended/flutterfire#7443]
## Bug report

**Describe the bug**
Since the last update, I started to get many crashes on hundreds of devices. A few weeks ago everything was fine.

```

Fatal Exception: android.os.BadParcelableException: Parcelable protocol requires subclassing from Parcelable on class com.google.firebase.messaging.n0
       at android.os.Parcel.readParcelableCreator(Parcel.java:3353)
       at android.os.Parcel.readParcelable(Parcel.java:3284)
       at android.os.Parcel.readValue(Parcel.java:3186)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.Bundle.getParcelable(Bundle.java:1001)
       at android.content.Intent.getParcelableExtra(Intent.java:8917)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:22)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:2)
       at io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingBackgroundService$MMnhHFRTKULlQAZ4ruNMt0KzQOI.run(-.java:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

### Steps to reproduce

1. Use the current Firebase Messaging version (11.1.0)
2. Use the background service I guess?

### Expected behavior

There shouldn't be crashes.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel master, 2.6.0-12.0.pre.826, on Microsoft Windows [Version 10.0.22000.348], locale de-DE)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2021.2)
[√] VS Code (version 1.62.3)
[√] Connected device (2 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.0-42.0.dev
Flutter SDK 2.6.0-12.0.pre.826
schulinfoapp 2.0.3+203000

dependencies:
- animations 2.0.2 [flutter]
- artemis 7.2.6-beta [build_config code_builder build collection dart_style equatable glob gql_code_builder gql_dedupe_link gql_exec gql_http_link gql_link gql http json_annotation path recase source_gen yaml]
- cached_network_image 3.1.0+1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- collection 1.15.0
- cupertino_icons 1.0.4
- equatable 2.0.3 [collection meta]
- firebase_analytics 8.3.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_core 1.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.3.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 11.1.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.7.1+4 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_cache_manager 3.1.3 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_local_notifications 9.1.4 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_pdfview 1.2.1 [flutter]
- flutter_svg 0.23.0+1 [flutter meta path_drawing vector_math xml]
- flutter_web_browser 0.15.0 [flutter]
- gql 0.13.1-alpha+1633799193898 [collection meta source_span]
- graphql_flutter 5.0.0 [graphql gql_exec flutter meta path_provider path connectivity_plus hive plugin_platform_interface]
- hive 2.0.4 [meta crypto]
- http 0.13.4 [async http_parser meta path]
- intl 0.17.0 [clock path]
- json_serializable 6.0.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- jwt_decoder 2.0.1
- meta 1.7.0
- mutex 3.0.0
- oauth2 2.0.0 [collection crypto http http_parser]
- os_detect 2.0.0
- package_info 2.0.2 [flutter]
- path_provider 2.0.7 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- provider 6.0.1 [collection flutter nested]
- quick_actions 0.6.0+8 [flutter meta quick_actions_platform_interface]
- share 2.0.4 [meta mime flutter]
- shared_preferences 2.0.9 [flutter meta shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- uni_links 0.5.1 [flutter uni_links_platform_interface uni_links_web]
- url_launcher 6.0.15 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- build_runner 2.1.5 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf s
helf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- _fe_analyzer_shared 28.0.0 [meta]
- analyzer 2.5.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.2 [crypto path]
- args 2.2.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.2 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.3 [meta path]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- connectivity_plus 1.1.0 [flutter meta connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- connectivity_plus_linux 1.1.0 [flutter connectivity_plus_platform_interface dbus meta nm]
- connectivity_plus_macos 1.1.0 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.1.0 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.1.0+1 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.1.0 [connectivity_plus_platform_interface flutter]
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.0 [analyzer args path pub_semver source_span]
- dbus 0.5.6 [args ffi meta pedantic xml]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_core_platform_interface 4.1.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.2.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.6 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.0.9 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.1.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.0.1+7 [firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.0.2 [firebase firebase_performance_platform_interface flutter flutter_web_plugins]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_local_notifications_linux 0.3.0 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- gql_code_builder 0.3.0-alpha+1633799193964 [analyzer built_collection built_value code_builder collection gql gql_exec path]
- gql_dedupe_link 2.0.0 [meta gql_exec gql_link async]
- gql_error_link 0.2.0 [async gql_exec gql_link meta]
- gql_exec 0.3.1-alpha+1633799193908 [collection gql meta]
- gql_http_link 0.4.0 [meta gql gql_exec gql_link http http_parser]
- gql_link 0.4.0 [meta gql gql_exec]
- gql_transform_link 0.2.0 [gql_exec gql_link]
- graphql 5.0.0 [meta path gql gql_exec gql_link gql_http_link gql_transform_link gql_error_link gql_dedupe_link hive normalize http collection web_socket_channel stream_channel rxdart uuid]
- graphs 2.0.0
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.3.0 [meta]
- lints 1.0.1
- logging 1.0.1
- matcher 0.12.11 [stack_trace]
- mime 1.0.0
- nested 1.0.0 [flutter]
- nm 0.3.0 [dbus]
- normalize 0.5.5 [gql collection]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_android 2.0.8 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.0.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.2.0 [meta]
- platform 3.0.2
- plugin_platform_interface 2.0.1 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.3 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- quick_actions_platform_interface 1.0.0 [flutter meta plugin_platform_interface]
- recase 4.0.0
- rxdart 0.26.0
- shared_preferences_android 2.0.9 [flutter meta shared_preferences_platform_interface]
- shared_preferences_ios 2.0.8 [flutter meta shared_preferences_platform_interface]
- shared_preferences_linux 2.0.3 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.3 [file flutter meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.1.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.0 [analyzer collection source_gen]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.0.1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.7 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- uni_links_platform_interface 1.0.0 [flutter plugin_platform_interface]
- uni_links_web 0.1.0 [flutter flutter_web_plugins uni_links_platform_interface]
- url_launcher_linux 2.0.1 [flutter]
- url_launcher_macos 2.0.1 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.4 [crypto]
- vector_math 2.1.1
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.2.7 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.2.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

```

</details>

---

**Comment by darshankawar** [comment]
@LasseRosenow 
Thanks for the report. I tried the official plugin [example](https://pub.dev/packages/firebase_messaging/example) on latest master, but didn't see the crash. Can you provide exact steps to replicate so that we can investigate this better ?

**Comment by LasseRosenow** [comment]
My problem is l, I cannot reproduce it myself eithe, but since my last update I am getting hundreds of crash reports on firebase crashlytics from my users all having this issue :(

**Comment by LasseRosenow** [comment]
It seems to happen when the app is not open I guess. They are getting this "the app "..." Keeps repeatedly crashing" window

**Comment by darshankawar** [comment]
Although it's tough to find the exact root-cause based on the logs, but I am guessing the exception is triggered when the app goes in background or is minimized, `FlutterFirebaseMessagingBackgroundExecutor.java:22`.

Did you simply upgrade the plugin to latest or made any updates to the code as well ? because the log is pointing to native Parcelable library but we won't know exactly what could be causing it.

**Comment by LasseRosenow** [comment]
I only updated a few plugins, but I released a new version yesterday where I downgraded only the firebase plugins back to the last version that I know that worked. So in a week or so I could report if this resolves the issue or not :)

**Comment by darshankawar** [comment]
sounds good. I'll add `blocked` label for now. Meantime I'll try to dig more into the logs and see what I can find.

**Comment by LasseRosenow** [comment]
I have some new information.

![image](https://user-images.githubusercontent.com/10547444/144444800-07a28461-2bf0-44d0-98be-1f251ee1a947.png)

So version 2.1.0 is the new release of my app with the old firebase dependencies, but it still has this issue. So it might be something else 🤔  Also in general the total amount of crashes is going down very fast, so maybe it was some issue in google play services or something like that? 🤔

**Comment by darshankawar** [comment]
@LasseRosenow 
May be that's coming from native Android in combination with messaging (specially when app goes in background). Would be good to get a pattern that leads to such logs so that we can dig deep a bit more.

**Comment by iampawan** [comment]
I am also facing a similar issue 

Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000000000006a8

`Crashed: com.apple.main-thread
0  Flutter                        0x3b8404 (Missing)
1  Flutter                        0x3e464 (Missing)
2  Flutter                        0x3c1f0 (Missing)
3  Flutter                        0x3c67ac (Missing)
4  Flutter                        0x3c6150 (Missing)
5  Flutter                        0x12b2c (Missing)
6  Flutter                        0xf1cc (Missing)
7  CoreFoundation                 0x2aed8 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 28
8  CoreFoundation                 0xc6b8c ___CFXRegistrationPost_block_invoke + 52
9  CoreFoundation                 0x99f44 _CFXRegistrationPost + 456
10 CoreFoundation                 0x40d44 _CFXNotificationPost + 716
11 Foundation                     0x1a628 -[NSNotificationCenter postNotificationName:object:userInfo:] + 96
12 UIKitCore                      0xf50e9c -[UIApplication _terminateWithStatus:] + 300
13 UIKitCore                      0x63bd14 -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:] + 128
14 UIKitCore                      0x830c5c -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:] + 224
15 UIKitCore                      0xf4dae4 -[UIApplication workspaceShouldExit:withTransitionContext:] + 212
16 FrontBoardServices             0x4fc38 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2 + 80
17 FrontBoardServices             0xa6b4 -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] + 240
18 FrontBoardServices             0x4fbd0 __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke + 132
19 libdispatch.dylib              0x4660 _dispatch_client_callout + 20
20 libdispatch.dylib              0x8118 _dispatch_block_invoke_direct + 264
21 FrontBoardServices             0xbf94 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 48
22 FrontBoardServices             0xb3d4 -[FBSSerialQueue _targetQueue_performNextIfPossible] + 220
23 FrontBoardServices             0xf9e4 -[FBSSerialQueue _performNextFromRunLoopSource] + 28
24 CoreFoundation                 0xbb020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
25 CoreFoundation                 0xcbce0 __CFRunLoopDoSource0 + 208
26 CoreFoundation                 0x5fe8 __CFRunLoopDoSources0 + 268
27 CoreFoundation                 0xb7f4 __CFRunLoopRun + 820
28 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
29 GraphicsServices               0x138c GSEventRunModal + 164
30 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
31 UIKitCore                      0x2987f4 UIApplicationMain + 2092
32 Runner                         0x8424 main + 10 (AppDelegate.swift:10)
33 ???                            0x102ef1a24 (Missing)`

**Comment by tigertore** [comment]
We also see these crashes and here is a fresh one:
```
Android 11 Galaxy S21 Ultra 5G 10 Jan 2022, 08:35:37

Fatal Exception: android.os.BadParcelableException: Parcelable protocol requires subclassing from Parcelable on class com.google.firebase.messaging.n0
       at android.os.Parcel.readParcelableCreator(Parcel.java:3353)
       at android.os.Parcel.readParcelable(Parcel.java:3284)
       at android.os.Parcel.readValue(Parcel.java:3186)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
       at android.os.BaseBundle.unparcel(BaseBundle.java:236)
       at android.os.Bundle.getParcelable(Bundle.java:1001)
       at android.content.Intent.getParcelableExtra(Intent.java:8917)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:232)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:146)
       at io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingBackgroundService$Xwr7miWP5q7fXU_MF_VIsLV14t0.run(-.java:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)


```
I have looked at other threads and we always find these:

_**firebase-installations-executor-1
firebase-installations-executor-2**_

They are both parked, but they indicate that some installation or update has been going on.
Can it be, that this gives some kind of conflict ?

**Comment by tigertore** [comment]
@darshankawar 
Any updates on this ?

**Comment by aldychris** [comment]
Also have this issue on our crashlytic dashboard
```
Fatal Exception: android.os.BadParcelableException
Parcelable protocol requires subclassing from Parcelable on class com.google.firebase.messaging.n0

Fatal Exception: android.os.BadParcelableException: Parcelable protocol requires subclassing from Parcelable on class com.google.firebase.messaging.n0
       at android.os.Parcel.readParcelableCreator(Parcel.java:2830)
       at android.os.Parcel.readParcelable(Parcel.java:2781)
       at android.os.Parcel.readValue(Parcel.java:2684)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
       at android.os.BaseBundle.unparcel(BaseBundle.java:232)
       at android.os.Bundle.getParcelable(Bundle.java:940)
       at android.content.Intent.getParcelableExtra(Intent.java:7534)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundExecutor.executeDartCallbackInBackgroundIsolate(FlutterFirebaseMessagingBackgroundExecutor.java:232)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.lambda$onHandleWork$0(FlutterFirebaseMessagingBackgroundService.java:146)
       at io.flutter.plugins.firebase.messaging.-$$Lambda$FlutterFirebaseMessagingBackgroundService$MMnhHFRTKULlQAZ4ruNMt0KzQOI.run(lambda:4)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:239)
       at android.app.ActivityThread.main(ActivityThread.java:7227)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)
```
We are using 
```
  firebase_core: 1.12.0
  firebase_messaging: 11.2.6
```
Any workaround for this crash?
