### ISSUE TITLE
🐛 [firebase_auth] firebase_auth/account-exists-with-different-credential

### ISSUE THREAD

**Issue by SebghatYusuf** [FirebaseExtended/flutterfire#7457]
## Bug report

I'm trying to allow my app users to sign in using their Facebook and Google accounts, Google sign-in works perfectly but Facebook is showing an error of having multiple accounts. it should allow my users to sign in multiple times with the same account and firebase id 

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [firebase_auth/account-exists-with-different-credential] An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.
E/flutter (24141): #0      MethodChannelFirebaseAuth.signInWithCredential (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:447)
E/flutter (24141): <asynchronous suspension>
E/flutter (24141): #1      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:455)
E/flutter (24141): <asynchronous suspension>
E/flutter (24141): #2      _LoginScreenState.signInWithFacebook (package:DVH/pages/login.dart:220)
E/flutter (24141): <asynchronous suspension>
```

### Steps to reproduce

1. create a sample project 
2. setup firebase auth and social auth with firebase (facebook) 
3. try to signin with your facebook 
*for me even for the first time it didn't work, because I was checking for emailVerified to let the user sign in. so, I believe the account was created and after first approach now I can't login. 

4. See error or incorrect behavior

### Expected behavior

should let users log in with having only one account instead of having multiple accounts. 

## Additional context

here is code snippet: 
```
 Future<void> signInWithFacebook() async {
    debugPrint("logging in with fb");
    setLoading(true);
    var provider = Provider.of<AppProvider>(context, listen: false);
    var dbProvider = Provider.of<DBProvider>(context, listen: false);

    final LoginResult result = await FacebookAuth.i.login(permissions: [
      'email',
      'public_profile'
    ]); // by default we request the email and the public profile

    if (result.status == LoginStatus.success) {
      // you are logged
      final AccessToken accessToken = result.accessToken!;
      final firebaseAuthCred = FacebookAuthProvider.credential(
        accessToken.token,
      );
      UserCredential user = await FirebaseAuth.instance.signInWithCredential(
        firebaseAuthCred,
      );
      debugPrint(user.user.toString());
      if (user.user!.email != null) {
        debugPrint('user $user');
        debugPrint("addtional ${user.additionalUserInfo}");
        await getUserDetails(user, provider, dbProvider, 'Facebook');
      } else {
        socialLoginMsg = 'Can\'t login with Facebook at the moment';
        setLoading(false);
      }
    } else {
      setLoading(false);
      debugPrint("FB LOGIN FAILED ${result.status} ${result.message}");
      FirebaseCrashlytics.instance
          .log("FB login result: ${result.status} ${result.message}");
      setState(() {
        socialLoginMsg = 'An error occured.';
      });
    }
  }
```
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale
    en-AF)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (4 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
DVH 1.2.5+20

dependencies:
- camera 0.9.4+1 [camera_platform_interface camera_web flutter pedantic quiver flutter_plugin_android_lifecycle]
- country_code_picker 2.0.2 [flutter modal_bottom_sheet collection universal_platform]
- cupertino_icons 1.0.3
- dart_ipify 1.1.0 [http]
- device_info_plus 3.0.1 [flutter device_info_plus_platform_interface device_info_plus_linux device_info_plus_macos device_info_plus_web device_info_plus_windows]
- dio 4.0.0 [http_parser path]
- dotted_border 2.0.0 [flutter path_drawing]
- double_back_to_close_app 2.0.1 [flutter]
- easy_mask 2.0.1 [flutter]
- email_validator 2.0.1
- encrypt 5.0.0 [args asn1lib clock collection crypto pointycastle]
- faker 2.0.0 [crypto]
- filesize 2.0.1
- firebase_auth 2.0.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.1.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 3.0.1 [firebase_core flutter]
- firebase_messaging 10.0.8 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.7.0+7 [firebase_core flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_dotenv 5.0.0 [flutter]
- flutter_facebook_auth 3.5.0 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_icons 1.1.1-nullsafety.0 [flutter]
- flutter_multi_formatter 2.3.2 [flutter collection base58check bech32]
- flutter_spinkit 5.0.0 [flutter]
- flutter_stripe 2.0.1 [flutter stripe_android stripe_ios stripe_platform_interface]
- fluttertoast 8.0.8 [flutter flutter_web_plugins]
- get 4.1.4 [flutter]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- google_ml_kit 0.7.2 [flutter]
- google_sign_in 5.0.4 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- http 0.13.3 [async http_parser meta path pedantic]
- image 3.0.8 [archive meta xml]
- image_picker 0.7.5+4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- intl 0.17.0 [clock path]
- livechatt 1.2.0 [flutter]
- open_file 3.2.1 [flutter ffi]
- package_info_plus 1.3.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- path 1.8.0
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 8.1.4+2 [flutter meta permission_handler_platform_interface]
- provider 5.0.0 [collection flutter nested]
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- url_launcher 6.0.9 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- webview_flutter 2.1.1 [flutter webview_flutter_platform_interface webview_flutter_android webview_flutter_wkwebview]

dev dependencies:
- build_runner 2.1.5 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_native_splash 1.2.4 [args image meta path xml yaml universal_io]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- hive_generator 1.1.1 [build source_gen hive analyzer source_helper]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service archive async boolean_selector characters charcode clock collection crypto fake_async file matcher meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math webdriver]

transitive dependencies:
- _fe_analyzer_shared 30.0.0 [meta]
- analyzer 2.7.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.2 [crypto path]
- args 2.3.0
- asn1lib 1.0.2
- async 2.8.1 [collection meta]
- base58check 2.0.0 [crypto collection]
- bech32 0.2.1 [convert]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.3 [built_collection collection fixnum meta]
- camera_platform_interface 2.1.1 [cross_file flutter meta plugin_platform_interface stream_transform]
- camera_web 0.2.1+1 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.1.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- cross_file 0.3.1+1 [flutter meta]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.0 [analyzer args path pub_semver source_span]
- device_info_plus_linux 2.1.0 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.1.0 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.1.0 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.0 [device_info_plus_platform_interface ffi flutter win32]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 5.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 2.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.1.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.2.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.0.6 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.6 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_facebook_auth_platform_interface 2.7.0 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.6.0+2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_plugin_android_lifecycle 2.0.3 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- freezed_annotation 0.14.3 [collection json_annotation meta]
- frontend_server_client 2.1.2 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.0.2 [async collection file path string_scanner]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 2.1.0 [collection]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.3 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.3.0 [meta]
- logging 1.0.2
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- mime 1.0.1
- modal_bottom_sheet 2.0.0 [flutter]
- nested 1.0.0 [flutter]
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.2.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.6.1 [flutter meta plugin_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pointycastle 3.1.3 [collection convert]
- pool 1.5.0 [async stack_trace]
- process 4.2.3 [file path platform]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.1.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1 [matcher]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.1.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.0 [analyzer collection source_gen]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- stripe_android 2.0.0 [flutter]
- stripe_ios 2.0.0 [flutter]
- stripe_platform_interface 2.0.0 [flutter freezed_annotation json_annotation meta plugin_platform_interface]
- sync_http 0.3.0
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- universal_platform 1.0.0+1
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- vm_service 7.1.1
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- webview_flutter_android 2.0.15 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.0.0 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.0.14 [flutter webview_flutter_platform_interface]
- win32 2.2.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
@SebghatYusuf 
Are you logging in with Google account first and then with Facebook ?
If so, then the exception you are getting is an expected behavior. For more details, check [this](https://github.com/FirebaseExtended/flutterfire/issues/4612#issuecomment-782107867) issue comment and see if it helps to resolve your issue.

**Comment by SebghatYusuf** [comment]
@darshankawar I think yes I'm using the same google account.

**Comment by SebghatYusuf** [comment]
@darshankawar, as I can see, [this](https://github.com/FirebaseExtended/flutterfire/issues/4612#issuecomment-758572375) comment says after linking it works fine, now how can I link these two Google & Facebook auth providers?

**Comment by SebghatYusuf** [comment]
Was able to link between those two providers and now I can log in using Facebook & Google with having the same account.

**Comment by innocenty-lab** [comment]
> Was able to link between those two providers and now I can log in using Facebook & Google with having the same account.

hello, how do you handle it? can i see it please?

**Comment by SebghatYusuf** [comment]
@innocenty-lab, sure I'll send you the code snippet.
