### ISSUE TITLE
🐛 [cloud_firestore] Crashed java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by JAICHANGPARK** [FirebaseExtended/flutterfire#7494]
## Package Info
- cloud_firestore: ^3.1.2

## Crash Report

```
E/AndroidRuntime(24237): java.lang.ExceptionInInitializerError
E/AndroidRuntime(24237):        at j.b.O1.o.forTarget(Unknown Source:0)
E/AndroidRuntime(24237):        at j.b.O1.p.a(:1)
E/AndroidRuntime(24237):        at j.b.K0.b(:2)
E/AndroidRuntime(24237):        at com.google.firebase.firestore.remote.GrpcCallProvider.initChannel(Unknown Source:37)
E/AndroidRuntime(24237):        at com.google.firebase.firestore.remote.GrpcCallProvider.c(:1)
E/AndroidRuntime(24237):        at com.google.firebase.firestore.remote.r.call(Unknown Source:2)
E/AndroidRuntime(24237):        at e.h.a.c.j.T.run(Unknown Source:4)
E/AndroidRuntime(24237):        at com.google.firebase.firestore.util.ThrottledForwardingExecutor.a(:1)
E/AndroidRuntime(24237):        at com.google.firebase.firestore.util.o.run(Unknown Source:4)
E/AndroidRuntime(24237):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(24237):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(24237):        at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime(24237): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: j.b.L1.values []
E/AndroidRuntime(24237):        at java.lang.Enum.enumValues(Enum.java:270)
E/AndroidRuntime(24237):        at java.lang.Enum.access$000(Enum.java:61)
E/AndroidRuntime(24237):        at java.lang.Enum$1.create(Enum.java:277)
E/AndroidRuntime(24237):        at java.lang.Enum$1.create(Enum.java:275)
E/AndroidRuntime(24237):        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(24237):        at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime(24237):        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
E/AndroidRuntime(24237):        at java.util.EnumSet.getUniverse(EnumSet.java:407)
E/AndroidRuntime(24237):        at java.util.EnumSet.noneOf(EnumSet.java:109)
E/AndroidRuntime(24237):        at java.util.EnumSet.of(EnumSet.java:235)
E/AndroidRuntime(24237):        at j.b.O1.o.<clinit>(Unknown Source:102)
E/AndroidRuntime(24237):        ... 12 more
E/AndroidRuntime(24237): Caused by: java.lang.NoSuchMethodException: j.b.L1.values []
E/AndroidRuntime(24237):        at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime(24237):        at java.lang.Class.getDeclaredMethod(Class.java:2050)
E/AndroidRuntime(24237):        at java.lang.Enum.enumValues(Enum.java:267)
E/AndroidRuntime(24237):        ... 22 more

```

![image](https://user-images.githubusercontent.com/19484515/145130384-2a52b190-95ef-44f6-8f6f-9407cce9a874.png)

### Flutter doctor

```
[✓] Flutter (Channel master, 2.6.0-12.0.pre.946, on macOS 12.0.1 21A559 darwin-arm,
    locale ko-KR)
    • Flutter version 2.6.0-12.0.pre.946 at /Users/jeffrey/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3af6b2f604 (3 hours ago), 2021-12-07 13:41:35 -0800
    • Engine revision 66a281107b
    • Dart version 2.16.0 (build 2.16.0-80.0.dev)
    • DevTools version 2.9.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/jeffrey/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 63.0.3
    • Dart plugin version 212.5632

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • SM P610 (mobile) • R54R305ADGH • android-arm64  • Android 11 (API 30)
    • macOS (desktop)  • macos       • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)     • chrome      • web-javascript • Google Chrome 96.0.4664.55

• No issues found!

```

### build.gradle
```
buildscript {
    ext.kotlin_version = '1.6.0'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

### app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'


def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}


android {
    compileSdkVersion 31

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.angelrobotics.app"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

configurations.all {
    resolutionStrategy {
        force 'androidx.core:core:1.6.0'
        force 'androidx.core:core-ktx:1.6.0'
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:28.3.1')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.android.gms:play-services-basement:17.6.0'
}

```

**Comment by darshankawar** [comment]
@JAICHANGPARK 
Try setting `minifyEnabled` and `shrinkResources` to `false` and see if it helps to resolve this crash.

**Comment by JAICHANGPARK** [comment]
@darshankawar I solved this problem 
Thanks 🙏
