### ISSUE TITLE
[cloud_functions] Can't build on iOS

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#750]
Hey, having trouble making an iOS applications with firebase cloud_functions plugin:

`flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.6 17G65, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
[✓] Android Studio (version 3.1)
[!] VS Code (version 1.25.1)
[✓] Connected devices (2 available)

! Doctor found issues in 1 category.
```

```yaml
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.11.3+16
  json_annotation: ^0.2.5
  flutter_webview_plugin: ^0.1.6
  firebase_auth: ^0.5.11
  firebase_database: ^1.0.1
  firebase_messaging: ^1.0.3
  cloud_functions: ^0.0.1
  shared_preferences: ^0.4.2
  url_launcher: ^3.0.3
  flutter_iap: ^1.2.1
```

Error:
```
Launching lib/main.dart on iPhone X in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 35QLRQBKZ9
Running pod install...
CocoaPods' output:
↳
      Preparing
    
    Analyzing dependencies
    
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    
    Finding Podfile changes
      - Flutter
      - cloud_functions
      - firebase_auth
      - firebase_core
      - firebase_database
      - firebase_messaging
      - flutter_iap
      - flutter_webview_plugin
      - shared_preferences
      - url_launcher
    
    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `cloud_functions` from `.symlinks/plugins/cloud_functions/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_database` from `.symlinks/plugins/firebase_database/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    -> Fetching podspec for `flutter_iap` from `.symlinks/plugins/flutter_iap/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    
    Resolving dependencies of `Podfile`
    
    Comparing resolved specification to the sandbox manifest
      - Firebase
      - FirebaseAnalytics
      - FirebaseAuth
      - FirebaseCore
      - FirebaseDatabase
      - FirebaseFunctions
      - FirebaseInstanceID
      - FirebaseMessaging
      - Flutter
      - GTMSessionFetcher
      - GoogleToolboxForMac
      - Protobuf
      - cloud_functions
      - firebase_auth
      - firebase_core
      - firebase_database
      - firebase_messaging
      - flutter_iap
      - flutter_webview_plugin
      - leveldb-library
      - nanopb
      - shared_preferences
      - url_launcher
    
    Downloading dependencies
    
    -> Using Firebase (5.4.0)
    
    -> Using FirebaseAnalytics (5.0.1)
    
    -> Using FirebaseAuth (5.0.2)
    
    -> Using FirebaseCore (5.0.5)
    
    -> Using FirebaseDatabase (5.0.2)
    
    -> Using FirebaseFunctions (2.1.0)
    
    -> Using FirebaseInstanceID (3.1.1)
    
    -> Using FirebaseMessaging (3.0.3)
    
    -> Using Flutter (1.0.0)
    
    -> Using GTMSessionFetcher (1.1.15)
    
    -> Using GoogleToolboxForMac (2.1.4)
    
    -> Using Protobuf (3.6.0)
    
    -> Using cloud_functions (0.0.1)
    
    -> Using firebase_auth (0.0.1)
    
    -> Using firebase_core (0.0.1)
    
    -> Using firebase_database (0.0.1)
    
    -> Using firebase_messaging (0.0.1)
    
    -> Using flutter_iap (1.2.0)
    
    -> Using flutter_webview_plugin (0.0.1)
    
    -> Using leveldb-library (1.20)
    
    -> Using nanopb (0.3.8)
    
    -> Using shared_preferences (0.0.1)
    
    -> Using url_launcher (0.0.1)
      - Running pre install hooks
    [!] The 'Pods-Runner' target has transitive dependencies that include static frameworks: (FirebaseFunctions, FirebaseCore, FirebaseAuth, FirebaseDatabase, and FirebaseMessaging)
    
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:87:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:73:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:73:in `block in verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:70:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:70:in `verify_no_static_framework_transitive_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer/xcode/target_validator.rb:36:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:415:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/installer.rb:118:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command/install.rb:41:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
    
    [!] Automatically assigning platform `ios` with version `9.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Finished with error: Error running pod install
```
Any ideas? No problem before adding cloud_functions plugin.

**Comment by kroikie** [comment]
@alamboley

The issue at https://github.com/flutter/flutter/issues/19512 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by Salakar** [comment]
Hey 👋 

Please could you try the new version and see if this is still an issue for you? If it is then please submit a new up to date GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration
