### ISSUE TITLE
🐛 [firebase_analytics] passing null userId gives exception

### ISSUE THREAD

**Issue by deepak786** [FirebaseExtended/flutterfire#7532]
## Bug report

The documentation of firebase_analytics `setUserId` says that
```
/// Sets the user ID property.
///
/// Setting a null [id] removes the user id.
///
/// This feature must be used in accordance with [Google's Privacy Policy][1].
///
/// [1]: https://www.google.com/policies/privacy/
```

but passing the null gives an exception.
```
FirebaseAnalytics.instance.setUserId(id: null);
```

```
E/flutter ( 4628): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(firebase_analytics, null, null, null)
E/flutter ( 4628): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 4628): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 4628): <asynchronous suspension>
E/flutter ( 4628): #2      FirebaseAnalytics.setUserId (package:firebase_analytics/src/firebase_analytics.dart:142:5)
E/flutter ( 4628): <asynchronous suspension>
E/flutter ( 4628): 
```

### Steps to reproduce

1. use version `firebase_analytics: 9.0.2`
2. set the user id as null `FirebaseAnalytics.instance.setUserId(id: null);`
3. see console for the exception.

### Expected behavior

This should not throw an exception. earlier it was working.

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.8.0 at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (21 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/appleapple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 96.0.4664.93

• No issues found!

```
</details>

**Comment by darshankawar** [comment]
Verified this on latest stable and using latest plugin version (^9.0.2) and see the same behavior.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(firebase_analytics, null, null, null)`

**Comment by PlugFox** [comment]
The same at `firebase_analytics: 9.0.2`.
Just replaced `analytics.setUserId(null)` with `analytics.setUserId(id: 'none')` for me as quickfix

**Comment by deepak786** [comment]
@darshankawar I believe the issue is only on Android.
