### ISSUE TITLE
🐛 [firebase_database] refFromUrl throws ArgumentError if databaseURL has end slash

### ISSUE THREAD

**Issue by deepak786** [FirebaseExtended/flutterfire#7536]
## Bug report

A new feature is introduced in `firebase_database` version 9.0.0 `refFromUrl` to get the `DatabaseReference`. This works fine if the `databaseURL` or `app.options.databaseURL` is null or does not end with a slash.
If it ends with a slash then it throws the `ArgumentError`.
 
### Steps to reproduce

Try the following code snippet:
```
WidgetsFlutterBinding.ensureInitialized();
// initialize the firebase
await Firebase.initializeApp();

// default db
var defaultDB = FirebaseDatabase.instanceFor(app: Firebase.app());
defaultDB.refFromURL('https://defaultdb.firebaseio.com/a/b/c'); // it works

// shard db without end slash in the database url
var shardDB1 = FirebaseDatabase.instanceFor(app: Firebase.app(), databaseURL: "https://sharddb.firebaseio.com");
shardDB1.refFromURL("https://sharddb.firebaseio.com/a/b/c"); // this works also

// shard db with end slash in the database url
var shardDB2 = FirebaseDatabase.instanceFor(
  app: Firebase.app(),
  databaseURL: "https://sharddb.firebaseio.com/",
);
shardDB2.refFromURL("https://sharddb.firebaseio.com/a/b/c"); // this will throw the ArgumentError
```

Error
```
The following ArgumentError was thrown while handling a gesture:
Invalid argument (must equal the current FirebaseDatabase instance databaseURL): url: "https://sharddb.firebaseio.com/a/b/c"
```

<details>
<summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.8.0 at /Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (21 hours ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/appleapple/Library/Android/sdk
    • Platform android-31, build-tools 30.0.2
    • ANDROID_HOME = /Users/appleapple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • sdk gphone64 x86 64 (mobile) • emulator-5554 • android-x64    • Android 12 (API 31) (emulator)
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 96.0.4664.93

• No issues found!

```
</details>

**Comment by darshankawar** [comment]
I see the same behavior using latest plugin version (^9.0.2) and on latest stable.

`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Invalid argument (must equal the current FirebaseDatabase instance databaseURL): url: "https://defaultdb.firebaseio.com/a/b/c"
#0      FirebaseDatabase.refFromURL (package:firebase_database/src/firebase_database.dart:100:9)
#1      main (package:triage/main.dart:464:13)
<asynchronous suspension>`
