### ISSUE TITLE
🐛 [firebase_database]android: weird issue

### ISSUE THREAD

**Issue by deepak786** [FirebaseExtended/flutterfire#7556]
## Bug report

I'm facing a very weird issue with `firebase_database: latest` on android.

1. I'm logged in with firebase_auth. 

```dart
FirebaseAuth.instance.currentUser != null;
```
2. The main screen `initState` has a query value listener on the firebase database path.

```dart
  StreamSubscription? _streamSubs;

  @override
  void initState() {
    super.initState();
    _streamSubs =
        FirebaseDatabase.instance.ref('/users/123456').onValue.map((event) {
      return event.snapshot.value;
    }).listen((event) {
      // ...
    });
  }

  @override
  void dispose() {
    _streamSubs?.cancel();
    super.dispose();
  }
```

3. I logged out.

```dart
FirebaseAuth.instance.signOut();
// navigate to login screen
```

4. LoggedIn again without closing the app.

```dart
FirebaseAuth.instance.signInWithEmailAndPassword(email: _email, password: _password);
// you can use any provider.
// navigate to main screen
```
5. Now a new query value listener will be added to the same database path from initState see step 2. 
6. At this time you will see the database error from the previous/stale value listener.

```dart
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [firebase_database/permission-denied] Client doesn't have permission to access the desired data.
E/flutter (17301):
E/flutter (17301):
E/flutter (17301): #0      MethodChannelQuery.observe.<anonymous closure> (package:firebase_database_platform_interface/src/method_channel/method_channel_query.dart:65:21)
E/flutter (17301): #1      _invokeErrorHandler (dart:async/async_error.dart:43:24)
E/flutter (17301): #2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269:9)
E/flutter (17301): #3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
E/flutter (17301): #4      _rootRunBinary (dart:async/zone.dart:1452:47)
E/flutter (17301): #5      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter (17301): #6      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
E/flutter (17301): #7      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter (17301): #8      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:7)
E/flutter (17301): #9      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
E/flutter (17301): #10     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
E/flutter (17301): #11     _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
E/flutter (17301): #12     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
E/flutter (17301): #13     _rootRunBinary (dart:async/zone.dart:1452:47)
E/flutter (17301): #14     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter (17301): #15     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
E/flutter (17301): #16     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter (17301): #17     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:7)
E/flutter (17301): #18     _DelayedError.perform (dart:async/stream_impl.dart:602:14)
E/flutter (17301): #19     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (17301): #20     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (17301): #21     _rootRun (dart:async/zone.dart:1420:47)
E/flutter (17301): #22     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (17301): #23     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (17301): #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (17301): #25     _rootRun (dart:async/zone.dart:1428:13)
E/flutter (17301): #26     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (17301): #27     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (17301): #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (17301): #29     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (17301): #30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (17301):
```

**Note:**
_The rules on the database path will allow accessing the data only if you are logged in._
```
{
  "rules": {
    "users":{
      "$uid": {
        ".read": "$uid === auth.uid",
        ".write": "$uid === auth.uid"
      }
    }
}
```
This issue was not with the `firebase_database` version up to `8.2.0`. 
is this correct behavior? how this will be solved?

**Comment by darshankawar** [comment]
@deepak786 
Can you try the official plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database/firebase_database/example) and see if you get same behavior as you described ?
If either case, can you provide a complete minimal code sample ?
Thanks.

**Comment by rajada1** [comment]
I have the same problem

**Comment by russellwheatley** [comment]
Interesting, seems like a bug with the underlying firebase android sdk, but hard to tell without a reproducible sample.

**Comment by rajada1** [comment]
My problem was that I was using the User currentUser variable = FirebaseAuth.instance.currentUser!;
throughout my project, without noticing the vscode auto-complete, it recommended me and the import has already been done.
Just create a variable User currentUser = FirebaseAuth.instance.currentUser!; for each page that worked normally.

Below is the code, with the problem, if you want to see the solution, uncomment line 29 of home_page.dart
and remove the import on line 5
obs: I setup my project using firebase-cli 

https://github.com/rajada1/sergipe_shop

> @deepak786 Can you try the official plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_database/firebase_database/example) and see if you get same behavior as you described ? If either case, can you provide a complete minimal code sample ? Thanks.

**Comment by deepak786** [comment]
I will create a sample for that.

**Comment by deepak786** [comment]
@darshankawar @russellwheatley 
here is the sample that reproduces the issue 
https://github.com/deepak786/issue_rtdb_7556

**Login:**

```
email: test@yopmail.com
password: 12345678
```

**Video:**
https://drive.google.com/file/d/10p3DnZf3YMeVSMB_TZuQpw0NoypYR_Wh/view?usp=sharing

In this video, you will see that on logout it gave the issue https://github.com/FirebaseExtended/flutterfire/issues/7795 and after login again, it gave the issue https://github.com/FirebaseExtended/flutterfire/issues/7556

**Comment by darshankawar** [comment]
Thanks for the repro code. I ran it on Android device using provided credentials and while trying to logout and then login again, it throws below error:

<details>
<summary> Console error log </summary>

```


I/flutter ( 9638): true
W/libEGL  ( 9638): EGLNativeWindowType 0xc8292008 disconnect failed
W/libEGL  ( 9638): EGLNativeWindowType 0xbe37b008 disconnect failed
E/flutter ( 9638): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [firebase_database/permission-denied] Client doesn't have permission to access the desired data.
E/flutter ( 9638):
E/flutter ( 9638):
E/flutter ( 9638): #0      MethodChannelQuery.observe.<anonymous closure> (package:firebase_database_platform_interface/src/method_channel/method_channel_query.dart:65:21)
E/flutter ( 9638): #1      _invokeErrorHandler (dart:async/async_error.dart:43:24)
E/flutter ( 9638): #2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269:9)
E/flutter ( 9638): #3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
E/flutter ( 9638): #4      _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter ( 9638): #5      _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter ( 9638): #6      _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
E/flutter ( 9638): #7      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter ( 9638): #8      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:7)
E/flutter ( 9638): #9      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:280:7)
E/flutter ( 9638): #10     _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
E/flutter ( 9638): #11     _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
E/flutter ( 9638): #12     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
E/flutter ( 9638): #13     _rootRunBinary (dart:async/zone.dart:1450:47)
E/flutter ( 9638): #14     _CustomZone.runBinary (dart:async/zone.dart:1342:19)
E/flutter ( 9638): #15     _CustomZone.runBinaryGuarded (dart:async/zone.dart:1252:7)
E/flutter ( 9638): #16     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:360:15)
E/flutter ( 9638): #17     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:378:7)
E/flutter ( 9638): #18     _DelayedError.perform (dart:async/stream_impl.dart:602:14)
E/flutter ( 9638): #19     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter ( 9638): #20     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter ( 9638): #21     _rootRun (dart:async/zone.dart:1418:47)
E/flutter ( 9638): #22     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 9638): #23     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 9638): #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 9638): #25     _rootRun (dart:async/zone.dart:1426:13)
E/flutter ( 9638): #26     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 9638): #27     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 9638): #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 9638): #29     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 9638): #30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 9638):
D/FirebaseAuth( 9638): Notifying id token listeners about a sign-out event.
D/FirebaseAuth( 9638): Notifying auth state listeners about a sign-out event.

Another exception was thrown: MissingPluginException(No implementation found for method cancel on channel
/users/cpxudCm68oPKiQupd4hQ4mVgkhz1-[DEFAULT]-null-DatabaseEventType.value-[]#3)
W/SyncTree( 9638): Listen at /users/cpxudCm68oPKiQupd4hQ4mVgkhz1 failed: DatabaseError: This client does not have permission to perform this operation

```

</details>
