### ISSUE TITLE
🐛 [realtime_database] Using emulator, calling goOnline fails to connect after calling goOffline

### ISSUE THREAD

**Issue by muzzah** [FirebaseExtended/flutterfire#7630]
## Bug report

**Describe the bug**

I am using the realtime db emulator which has its socket bound to 0.0.0.0.
I setup the firebase realtime instance in the following way

```
    String host = _getDatabaseHost();
    FirebaseDatabase db = FirebaseDatabase.instanceFor(app: await _initialiseFirebase(), databaseURL: host);
    db.setPersistenceEnabled(true);
    if (kDebugMode) {
      db.useDatabaseEmulator(AppConfiguration.DEV_HOST, int.tryParse(FDB_EMULATOR_PORT));
      db.setLoggingEnabled(true);
    }
    return db;
```

When the app starts, it successfully conencts to the emulator (I check the .info/connected value).

Then I go through the following sequence of calls on the database instance

```
goOnline
goOffline
goOnline
```

The database successfully disconnects after I call goOffline (again I receive the event for the .info/connected listener) but when I call the goOnline method again I get the following error output

```
D/WebSocket(10804): com.google.firebase.database.tubesock.WebSocketException: error while creating socket to ws://0.0.0.0:8083/.ws?ns=siia-dev&v=5&ls=Ipu4XVAulXi8nhbm2IxbIUro8PGkENjr
D/WebSocket(10804): 	at com.google.firebase.database.tubesock.WebSocket.createSocket(WebSocket.java:301)
D/WebSocket(10804): 	at com.google.firebase.database.tubesock.WebSocket.runReader(WebSocket.java:360)
D/WebSocket(10804): 	at com.google.firebase.database.tubesock.WebSocket.access$000(WebSocket.java:47)
D/WebSocket(10804): 	at com.google.firebase.database.tubesock.WebSocket$2.run(WebSocket.java:143)
D/WebSocket(10804): 	at java.lang.Thread.run(Thread.java:761)
D/WebSocket(10804): Caused by: java.net.ConnectException: Connection refused
D/WebSocket(10804): 	at java.net.PlainSocketImpl.socketConnect(Native Method)
D/WebSocket(10804): 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
D/WebSocket(10804): 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:194)
D/WebSocket(10804): 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
D/WebSocket(10804): 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
D/WebSocket(10804): 	at java.net.Socket.connect(Socket.java:586)
D/WebSocket(10804): 	at java.net.Socket.connect(Socket.java:535)
D/WebSocket(10804): 	at java.net.Socket.<init>(Socket.java:427)
D/WebSocket(10804): 	at java.net.Socket.<init>(Socket.java:210)
D/WebSocket(10804): 	at com.google.firebase.database.tubesock.WebSocket.createSocket(WebSocket.java:297)
D/WebSocket(10804): 	... 4 more
```

For some reason, the client tries to connect to the IP the emulator is bound to and not the original Hostname I gave it. The .info/connected value thus is false 

### Steps to reproduce

As per above, setup an instance to an emulator bound to 0.0.0.0 and then call the methods above on the database instance.

### Expected behavior

It should go back online and the .info/connected value should be set to true.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-AU)
    • Flutter version 2.5.3 at /usr/local/Caskroom/flutter/1.22.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (9 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc1)
    • Android SDK at /Users/nobunaga/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.2, Build version 13C90
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.62.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • SM T580 (mobile)                      • 5200b3ddbcfb545b                     • android-arm    • Android 8.1.0 (API 27)
    • Android SDK built for x86 64 (mobile) • emulator-5554                        • android-x64    • Android 7.0 (API 24) (emulator)
    • iPad Air (4th generation) (mobile)    • 61BF146F-06E3-4010-9829-9CDC321EBA27 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
    • Chrome (web)                          • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
siia 1.0.0+1

dependencies:
- animated_bottom_navigation_bar 0.3.2 [flutter]
- animations 2.0.2 [flutter]
- cloud_firestore 3.1.0 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.4
- dotted_border 2.0.0+1 [flutter path_drawing]
- equatable 2.0.3 [collection meta]
- firebase_analytics 8.3.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 3.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.6 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.3.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_database 9.0.4 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- fl_chart 0.40.2 [flutter equatable]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_intro 2.3.1 [flutter]
- flutter_keyboard_visibility 5.1.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_modular 4.2.0 [flutter_modular_annotations triple modular_core meta flutter]
- flutter_redux 0.8.2 [redux flutter]
- flutter_rounded_progress_bar 0.2.0 [flutter]
- flutter_translate 3.0.1 [flutter universal_io]
- form_field_validator 1.1.0 [flutter intl]
- get_it 7.2.0 [async collection]
- googleapis 7.0.0 [_discoveryapis_commons http]
- googleapis_auth 1.3.0 [crypto http http_parser]
- http 0.13.4 [async http_parser meta path]
- im_stepper 0.1.3 [flutter]
- intl 0.17.0 [clock path]
- introduction_screen 2.1.0 [flutter dots_indicator]
- json_annotation 4.3.0 [meta]
- line_awesome_icons 1.0.4+2 [flutter]
- localstorage 4.0.0+1 [flutter path_provider]
- modal_bottom_sheet 2.0.0 [flutter]
- optional 6.1.0+1 [collection]
- path 1.8.0
- path_provider 2.0.7 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- quiver 3.0.1+1 [matcher]
- random_string 2.3.1
- redux 5.0.0
- scroll_to_index 2.1.0 [flutter]
- simple_animations 4.0.1 [flutter flutter_lints collection]
- supercharged 2.1.1 [supercharged_dart flutter]
- universal_platform 1.0.0+1
- web_socket_channel 2.1.0 [async crypto stream_channel]

dev dependencies:
- build_runner 2.1.5 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 6.0.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mockito 5.0.16 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- test 1.17.10 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _discoveryapis_commons 1.0.2 [http http_parser meta]
- _fe_analyzer_shared 30.0.0 [meta]
- analyzer 2.7.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.0
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.5 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.3 [built_collection collection fixnum meta]
- characters 1.1.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.5 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.5.0 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- coverage 1.0.3 [args logging package_config path source_maps stack_trace vm_service]
- dart_style 2.2.0 [analyzer args path pub_semver source_span]
- dots_indicator 2.0.0 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.2 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 6.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.2.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.3 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.6 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_platform_interface 0.2.0+3 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.0+3 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- fixnum 1.0.0
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_lints 1.0.4 [lints]
- flutter_modular_annotations 0.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- graphs 2.1.0 [collection]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- mime 1.0.1
- modular_core 1.2.0 [characters meta modular_interfaces]
- modular_interfaces 1.0.4
- node_preamble 2.0.1
- package_config 2.0.2 [path]
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_android 2.0.9 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.3 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.4 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.1.0 [checked_yaml collection json_annotation pub_semver yaml]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.1.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.0 [analyzer collection source_gen]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- supercharged_dart 2.1.1
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.0 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- triple 1.3.3 [meta async]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- vector_math 2.1.0
- vm_service 7.5.0
- watcher 1.0.1 [async path]
- webkit_inspection_protocol 1.0.0 [logging]
- win32 2.3.0 [ffi]
- xdg_directories 0.2.0 [meta path process]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by muzzah** [comment]
To add to this ridiculous bug, I have confirmed this is the issue by changing the bound host in the firebase.json config file for the emulator to the hostname that resolve to a reachable IP and this issue goes away. I can then call goOnline without any issues and the connection is re-established

**Comment by darshankawar** [comment]
@muzzah 
Looking at the error log you shared:
```

`D/WebSocket(10804): com.google.firebase.database.tubesock.WebSocketException: error while creating socket to ws://0.0.0.0:8083/.ws?ns=siia-dev&v=5&ls=Ipu4XVAulXi8nhbm2IxbIUro8PGkENjr
D/WebSocket(10804): 	at com.google.firebase.database.tubesock.WebSocket.createSocket(WebSocket.java:301)
D/WebSocket(10804): 	at com.google.firebase.database.tubesock.WebSocket.runReader(WebSocket.java:360)
D/WebSocket(10804): 	at com.google.firebase.database.tubesock.WebSocket.access$000(WebSocket.java:47)
D/WebSocket(10804): 	at com.google.firebase.database.tubesock.WebSocket$2.run(WebSocket.java:143)
D/WebSocket(10804): 	at java.lang.Thread.run(Thread.java:761)
D/WebSocket(10804): Caused by: java.net.ConnectException: Connection refused
D/WebSocket(10804): 	at java.net.PlainSocketImpl.socketConnect(Native Method)`
```
It seems to be coming from native firebase and not from flutterfire plugin. I see there's a similar issue in dedicated repo: https://github.com/firebase/firebase-android-sdk/issues/2970 in which you can follow-up.

FlutterFire just sends some data from Dart, which hits the native Firebase SDKs, and sends the data back once they return some data. You'll need to reach out in that repo for further steps.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Comment by muzzah** [comment]
Having gone through that issue, I do not think that is the problem since the connection seems to be re-established before being disconnected again. This issue specifically fails to reconnect at all after a single disconnection as the emulator seems to send some information about the hostname the SDK should reconnect to and since its bound to 0.0.0.0 it fails to reconnect all. This happens on both iOS and Android builds, so should I be submitting this issue to those specific SDKs?
