### ISSUE TITLE
🐛 [cloud_firestore] does not throw exception when the phone is without connection or internet

### ISSUE THREAD

**Issue by insinfo** [FirebaseExtended/flutterfire#7636]
cloud_firestore does not throw exception when the phone is without connection or internet, it puts everything in the log but it does not propagate the exception, it should throw an exception to be treated with a message to give feedback to the user.

```console
PS C:\MyDartProjects\appsescverao\appsescverao> flutter run
Multiple devices found:
ASUS X018D (mobile)          • JBAXB600T149ZSD • android-arm64 • Android 8.1.0 (API 27)
sdk gphone64 x86 64 (mobile) • emulator-5554   • android-x64   • Android 12 (API 31) (emulator)
[1]: ASUS X018D (JBAXB600T149ZSD)
[2]: sdk gphone64 x86 64 (emulator-5554)
Please choose one (To quit, press "q/Q"): 1
Launching lib\main.dart on ASUS X018D in debug mode...
Running Gradle task 'assembleDebug'...                             29,9s
√  Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                16,8s
I/flutter (10303): initHomePageState:
Syncing files to device ASUS X018D...                              950ms

Flutter run key commands.
r Hot reload. 
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

An Observatory debugger and profiler on ASUS X018D is available at: http://127.0.0.1:65071/gLOMsT81hpM=/
The Flutter DevTools debugger and profiler on ASUS X018D is available at: http://127.0.0.1:9101?uri=http://127.0.0.1:65071/gLOMsT81hpM=/
W/DynamiteModule(10303): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(10303): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(10303): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/zygote64(10303): The ClassLoaderContext is a special shared library.
I/zygote64(10303): The ClassLoaderContext is a special shared library.
V/NativeCrypto(10303): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 287 native methods...
D/NetworkSecurityConfig(10303): No Network Security Config specified, using platform default
I/ProviderInstaller(10303): Installed default security provider GmsCore_OpenSSL
W/ManagedChannelImpl(10303): [{0}] Failed to resolve name. status={1}
W/Firestore(10303): (24.0.0) [WatchStream]: (7e2484d) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
W/Firestore(10303):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/Firestore(10303):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/Firestore(10303):     at java.lang.Thread.run(Thread.java:764)
W/Firestore(10303): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(10303):     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
W/Firestore(10303):     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
W/Firestore(10303):     at java.net.InetAddress.getAllByName(InetAddress.java:787)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
W/Firestore(10303):     ... 5 more
W/Firestore(10303): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore(10303):     at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore(10303):     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:59)
W/Firestore(10303):     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
W/Firestore(10303):     ... 9 more
W/Firestore(10303): }.
W/Firestore(10303): (24.0.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
W/Firestore(10303):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/Firestore(10303):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/Firestore(10303):     at java.lang.Thread.run(Thread.java:764)
W/Firestore(10303): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(10303):     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
W/Firestore(10303):     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
W/Firestore(10303):     at java.net.InetAddress.getAllByName(InetAddress.java:787)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
W/Firestore(10303):     ... 5 more
W/Firestore(10303): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore(10303):     at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore(10303):     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:59)
W/Firestore(10303):     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
W/Firestore(10303):     ... 9 more
W/Firestore(10303): }
W/Firestore(10303): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
W/Firestore(10303): (24.0.0) [WatchStream]: (7e2484d) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
W/Firestore(10303):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/Firestore(10303):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/Firestore(10303):     at java.lang.Thread.run(Thread.java:764)
W/Firestore(10303): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(10303):     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
W/Firestore(10303):     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
W/Firestore(10303):     at java.net.InetAddress.getAllByName(InetAddress.java:787)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:631)
W/Firestore(10303):     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)
W/Firestore(10303):     ... 5 more
W/Firestore(10303): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore(10303):     at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore(10303):     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:59)
W/Firestore(10303):     at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
W/Firestore(10303):     ... 9 more
W/Firestore(10303): }.
I/flutter (10303): obteve da API
W/ManagedChannelImpl(10303): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(10303): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(10303): [{0}] Failed to resolve name. status={1}

```

**Comment by darshankawar** [comment]
@insinfo 
Check [this](https://stackoverflow.com/a/63415042) SO answer by former firebase member and see if it answers your question.

**Comment by GMChristo** [comment]
@darshankawar, the answer on this link of stackoverflow has some problems. In one of them, when it did "if (snapshot.empty && snapshot.metadata.fromCache)", the problem is if the list is really empty on the base. Another problem is checking the connection before every access, if the internet is online when I check and in the next moment (access to the firebase) the internet fall, in this case, we return to the original problem.

**Comment by insinfo** [comment]
@darshankawar  the ideal is to have a global option to say whether to throw an exception or not, so that it can be handled by the API user and give feedback to the user, so that the user doesn't see just a list when

@GMChristo I totally agree, checking if you have internet every time you run an operation on the database is an overload, in addition to causing greater latency in displaying the data.

**Comment by darshankawar** [comment]
Thanks for your input. Leaving this issue open and labeling it for further insights from the team.

Related SO link I shared earlier: https://stackoverflow.com/questions/63414747/how-to-catch-client-is-offline-error-in-flutter-firebase-firestore/63415042#63415042

**Comment by russellwheatley** [comment]
Hey folks, Firestore & Database do not throw errors when the users phone is offline by design. They are awaiting (in the hope) that they do come back online and sync up what is local with the remote database. If you would like to change this behaviour, you ought to raise it in the android or iOS SDK repo, but I can't imagine they will change something that is fundamental to Firestore's function. FlutterFire is just a wrapper around both iOS and android SDKs.
