### ISSUE TITLE
🐛 [Cloud Firestore] OnlineStateTracker: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds

### ISSUE THREAD

**Issue by AliYar-Khan** [FirebaseExtended/flutterfire#7663]
## Bug report

**Describe the bug**
I am facing issue while retrieving data from firestore backend. Authentication is working fine. Signed-in user is being retrieved but when I fetch data from cloud firestore it gives the following exception:

```
W/Firestore( 5229): (24.0.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
W/Firestore( 5229): 
W/Firestore( 5229): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
E/flutter ( 5229): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
E/flutter ( 5229): #0      MethodChannelDocumentReference.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:81:7)
E/flutter ( 5229): <asynchronous suspension>
E/flutter ( 5229): #1      _JsonDocumentReference.get (package:cloud_firestore/src/document_reference.dart:146:7)
E/flutter ( 5229): <asynchronous suspension>
E/flutter ( 5229): #2      _LoginPageState._handleLoginWithUsernamePassword.<anonymous closure>.<anonymous closure> (package:wordpress_app/pages/login.dart:59:15)
E/flutter ( 5229): <asynchronous suspension>
E/flutter ( 5229): #3      _LoginPageState._handleLoginWithUsernamePassword.<anonymous closure> (package:wordpress_app/pages/login.dart:55:11)
E/flutter ( 5229): <asynchronous suspension>
E/flutter ( 5229): 
I/m.techgenez.co( 5229): Background young concurrent copying GC freed 104426(4914KB) AllocSpace objects, 9(308KB) LOS objects, 49% free, 5511KB/10MB, paused 444us total 475.401ms
```

### Steps to reproduce

1. Create a new project. Add cloud firestore and Firebase core to the pubspec.yaml.
2. Retrieve data from firestore
4. See error or incorrect behavior

### Expected behavior

Retrieve the data requested from firestore.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19044.1415], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.63.0)
[√] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
app 1.5.0+2

dependencies:
- animated_bottom_navigation_bar 0.3.2 [flutter]
- audioplayers 0.19.1 [uuid path_provider http flutter flutter_web_plugins]
- better_player 0.0.77 [flutter cupertino_icons wakelock pedantic meta flutter_widget_from_html_core visibility_detector path_provider collection xml]
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cloud_firestore 3.1.4 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- dots_indicator 2.0.0 [flutter]
- easy_localization 3.0.0 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- firebase_analytics 8.3.3 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_app_check 0.0.6+2 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 10.0.8 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.2.3 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flare_flutter 3.0.2 [collection flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_facebook_auth 3.5.6+3 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_html 2.1.5 [html csslib flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter_math_fork collection numerus flutter]
- flutter_icons 1.1.1-nullsafety.0 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- flutter_web_browser 0.15.0 [flutter]
- fluttertoast 8.0.8 [flutter flutter_web_plugins]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- google_mobile_ads 0.13.5 [meta flutter]
- google_sign_in 5.2.1 [flutter google_sign_in_platform_interface google_sign_in_web meta]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- html_unescape 2.0.0
- http 0.13.4 [async http_parser meta path]
- image_picker 0.8.4+4 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- intl 0.17.0 [clock path]
- jiffy 4.1.0 [intl]
- launch_review 3.0.1 [flutter]
- loading_indicator 3.0.2 [flutter async]
- md2_tab_indicator 2.0.0 [flutter]
- package_info 2.0.2 [flutter]
- path_provider 2.0.5 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- provider 5.0.0 [collection flutter nested]
- rounded_loading_button 2.0.9 [flutter rxdart]
- share 2.0.4 [meta mime flutter]
- shared_preferences 2.0.8 [flutter meta shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- skeleton_text 3.0.0 [flutter]
- timeago 3.1.0
- twitter_login 4.0.1 [flutter crypto http]
- url_launcher 6.0.12 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- youtube_player_flutter 8.0.0 [flutter flutter_inappwebview]

dev dependencies:
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel strin
g_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.6 [crypto path]
- args 2.3.0
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.1.0
- charcode 1.3.1
- chewie 1.2.2 [cupertino_icons flutter provider video_player wakelock]
- chewie_audio 1.2.0 [cupertino_icons flutter video_player]
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.9 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.4 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- cross_file 0.3.2 [flutter js meta]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.1 [source_span]
- easy_logger 0.0.2 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.2 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_app_check_platform_interface 0.0.3+2 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.5+2 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.1.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.2 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.6 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.6 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.0.10 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.4 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_facebook_auth_platform_interface 2.7.0 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.6.0+2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_inappwebview 5.3.2 [flutter]
- flutter_layout_grid 1.0.3 [flutter collection meta quiver]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_math_fork 0.3.3+1 [flutter flutter_svg provider meta collection tuple]
- flutter_plugin_android_lifecycle 2.0.4 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- flutter_widget_from_html_core 0.7.0 [csslib flutter html]
- google_sign_in_platform_interface 2.1.0 [flutter meta quiver]
- google_sign_in_web 0.10.0+3 [flutter flutter_web_plugins google_sign_in_platform_interface js meta]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.8 [archive meta xml]
- image_picker_for_web 2.1.4 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- numerus 1.1.1
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- path 1.8.0
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.1.0 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- process 4.2.3 [file path platform]
- quiver 3.0.1+1 [matcher]
- rxdart 0.27.2
- shared_preferences_linux 2.0.2 [file meta flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.2 [flutter file meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.0.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.2 [flutter]
- url_launcher_macos 2.0.2 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.5 [crypto]
- vector_math 2.1.0
- video_player 2.2.5 [flutter meta video_player_platform_interface video_player_web html]
- video_player_platform_interface 4.2.0 [flutter flutter_test meta]
- video_player_web 2.0.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- visibility_detector 0.2.2 [flutter]
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- webview_flutter 2.1.1 [flutter webview_flutter_platform_interface webview_flutter_android webview_flutter_wkwebview]
- webview_flutter_android 2.0.15 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.2.0 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.0.14 [flutter webview_flutter_platform_interface]
- win32 2.2.9 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]


```

</details>

---

**Comment by darshankawar** [comment]
@AliYar-Khan 
For `[OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds`, `This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.` error, please follow-up in this discussion thread: https://github.com/FirebaseExtended/flutterfire/discussions/5546

For `The service is currently unavailable.`, follow-up in https://github.com/FirebaseExtended/flutterfire/discussions/5708

Closing this as a duplicate.
