### ISSUE TITLE
🐛 [firebase_storage] .getdata gives weird url and returns 404

### ISSUE THREAD

**Issue by prggTheProgrammer** [FirebaseExtended/flutterfire#7688]
## Bug report

**.getdata fails**
when I call the .getdata method on  a .ref() it doesn't stop loading, but gives no error in the flutter console.
But if I click inspect in google it says: `failed to load resource: https://firebasestorage.googleapis.com/v0/b/%5Bobject%20Object%5D/o/<filename> the server responded with a status of 404 ()`
So I think the problem is that it is not getting the url right, because this is not a good url and returns 404.
The only way I get it to work is to use the whole e.g.  .ref("gs://storage_name/file"), but that is not what is mentioned in the docs (https://firebase.flutter.dev/docs/storage/usage#downloading-files) and this doesn't work on mobile.

### Steps to reproduce

1. Setup your flutter project for chrome
2. add firebase_storage to pubspec.yaml
3. run this program:
```
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_storage/firebase_storage.dart';

void main() async{
  await Firebase.initializeApp();
  var t = await FirebaseStorage.instance.ref("filepath").getData();
  print(t.toString());
}
```
4. inspect in chrome and see the 404 in console
5. And if you change the filepath to the full path, it should work and you should get a list of bytes

### Expected behavior

It should print a list of bytes just like it happens when you do the whole path. If I am supposed to put the whole path, then how do I do it on mobile and then please update the docs

### Sample project

see steps above

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1415], locale nl-NL)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] Connected device (2 available)

• No issues found!
```
</details>

---
### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.15.1
Flutter SDK 2.8.1
schoolstrijd 1.0.0+1

dependencies:
- cloud_firestore 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- excel 2.0.0-null-safety-3 [archive xml equatable]
- firebase_auth 3.1.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_oauth 1.1.0 [flutter firebase_auth firebase_core firebase_auth_oauth_platform_interface firebase_auth_oauth_web]
- firebase_picture_uploader 1.3.1 [flutter cached_network_image firebase_storage firebase_core image image_picker image_cropper shared_preferences path_provider cupertino_icons]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_expandable_table 1.0.0 [flutter linked_scroll_controller flutter_scroll_shadow]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- google_sign_in 5.2.1 [flutter google_sign_in_platform_interface google_sign_in_web meta]
- http 0.13.4 [async http_parser meta path]
- image_cropper 1.4.1 [flutter]
- provider 5.0.0 [collection flutter nested]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanne
r term_glyph typed_data]

transitive dependencies:
- archive 3.1.6 [crypto path]
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- cached_network_image 3.1.0+1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.7 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- cross_file 0.3.2 [flutter js meta]
- crypto 3.0.1 [collection typed_data]
- equatable 2.0.3 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.2 [http http_parser js]
- firebase_auth_oauth_platform_interface 1.0.2 [flutter firebase_auth firebase_core]
- firebase_auth_oauth_web 1.0.2 [flutter flutter_web_plugins firebase firebase_auth firebase_core firebase_auth_oauth_platform_interface js]
- firebase_auth_platform_interface 6.1.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.1.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage 10.0.6 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- firebase_storage_platform_interface 4.0.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.0.4 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.3 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.4 [flutter]
- flutter_scroll_shadow 1.0.1 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 2.1.0 [flutter meta quiver]
- google_sign_in_web 0.10.0+3 [flutter flutter_web_plugins google_sign_in_platform_interface js meta]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.8 [archive meta xml]
- image_picker 0.8.4+4 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- image_picker_for_web 2.1.4 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- intl 0.17.0 [clock path]
- js 0.6.3
- linked_scroll_controller 0.2.0 [flutter]
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- meta 1.7.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- path 1.8.0
- path_provider 2.0.6 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_linux 2.1.0 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- process 4.2.4 [file path platform]
- quiver 3.0.1+1 [matcher]
- rxdart 0.27.2
- shared_preferences 2.0.8 [flutter meta shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 2.0.3 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.3 [file flutter meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.0.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- uuid 3.0.5 [crypto]
- vector_math 2.1.1
- win32 2.2.10 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
```

</details>

---

**Comment by prggTheProgrammer** [comment]
Update: It now gives this error: Error: [firebase_storage/object-not-found] No object exists at the desired reference.
    at Object.throw_ [as throw] (http://localhost:62317/dart_sdk.js:5063:11)
    at http://localhost:62317/packages/firebase_core/src/internals.dart.lib.js:81:63
    at _RootZone.runUnary (http://localhost:62317/dart_sdk.js:40062:59)
    at _FutureListener.catchError.handleError (http://localhost:62317/dart_sdk.js:34996:33)
    at handleError (http://localhost:62317/dart_sdk.js:35567:51)
    at Function._propagateToListeners (http://localhost:62317/dart_sdk.js:35593:17)
    at _Future.new.[_completeError] (http://localhost:62317/dart_sdk.js:35443:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:62317/dart_sdk.js:35479:31)
    at Object._microtaskLoop (http://localhost:62317/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:62317/dart_sdk.js:40336:13)
    at http://localhost:62317/dart_sdk.js:35811:9

**Comment by darshankawar** [comment]
@prggTheProgrammer 
I tried the sample code you shared and incorporated in the plugin's official [example](https://pub.dev/packages/firebase_storage/example) and ran on web using latest stable, but didn't see the issue you mentioned. Also the chrome console doesn't show any error. 

<img width="1198" alt="Screenshot 2021-12-28 at 3 55 16 PM" src="https://user-images.githubusercontent.com/67046386/147556751-a60ab93a-f4db-4362-9011-45fd679c254b.png">



Not sure if I am missing anything to properly replicate it.
Can you try the same example and check if you still get same behavior with it too ?

**Comment by russellwheatley** [comment]
This error code: `firebase_storage/object-not-found` means there isn't anything at the path you have passed into `.ref(<PATH>)` I would double check the path is correct, there might be an issue with special characters for example.

**Comment by prggTheProgrammer** [comment]
@darshankawar Thanks for testing, I am using the manual installation (https://firebase.flutter.dev/docs/manual-installation/web), mabey it has something to do with that.

@russellwheatley, yes I know, I checked it, it works when I use the whole path (but this doesn't work on mobile) but when I remove the gs://... It doesn't work anymore.

**Comment by prggTheProgrammer** [comment]
The problem is already fixed but I was using the old sdk (<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>) instead of (<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-storage.js"></script>)
