### ISSUE TITLE
🐛 [flutterfire configure] Error running flutterfire configure - "Unexpected Character"

### ISSUE THREAD

**Issue by chonghorizons** [FirebaseExtended/flutterfire#7693]
## Bug report

**Describe the bug**

I'm trying to follow the instructions to setup flutterfire CLI here: https://firebase.flutter.dev/docs/overview#using-the-cli

```shell
# Install the CLI if not already done so
dart pub global activate flutterfire_cli

# Run the `configure` command, select a Firebase project and platforms
flutterfire configure
```

And it's giving me an error:

```
⠙ Fetching available Firebase projects...
Unhandled exception:
FormatException: Unexpected character (at character 1)
{
^
```

<details><summary>Click To Expand - full console output</summary>

```
Macs-MacBook-Air:testing_jar howaXXX$ flutterfire --version
0.1.1+2
Macs-MacBook-Air:testing_jar howaXXX$ flutterfire configure
⠙ Fetching available Firebase projects...
Unhandled exception:
FormatException: Unexpected character (at character 1)
{
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1405:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1272:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:937:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:40:10)
#4      JsonDecoder.convert (dart:convert/json.dart:506:36)
#5      runFirebaseCommand (package:flutterfire_cli/src/firebase.dart:95:25)
<asynchronous suspension>
#6      getProjects (package:flutterfire_cli/src/firebase.dart:114:7)
<asynchronous suspension>
#7      ConfigCommand._selectFirebaseProject (package:flutterfire_cli/src/commands/config.dart:159:24)
<asynchronous suspension>
#8      ConfigCommand.run (package:flutterfire_cli/src/commands/config.dart:227:37)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#10     main (file:///Users/howaXXX/.pub-cache/hosted/pub.dartlang.org/flutterfire_cli-0.1.1+2/bin/flutterfire.dart:34:5)
<asynchronous suspension>
Macs-MacBook-Air:testing_jar howaXXX$ 
```

</details>

### Steps to reproduce

On mac osx 12.0.1
1. In terminal, run `dart pub global activate flutterfire_cli`
2. then run `flutterfire configure`
3. See error or incorrect behavior

### Expected behavior

As stated on the [website](https://firebase.flutter.dev/docs/overview#using-the-cli), I'll select the firebase project and app and then a `firebase_options.dart` is generated.

### Sample project

No project. Just terminal.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)

```

</details>

---

### Flutter dependencies

Not applicable. Terminal. No dependencies.

---

**Comment by darshankawar** [comment]
@chonghorizons 
I am on latest stable and ran the same command which ran properly without any issues:

```
Activated flutterfire_cli 0.1.1+2.
dhs@Dhss-MacBook-Pro ios_bug % flutterfire configure
i Found 7 Firebase projects.
? Select a Firebase project to configure your Flutter application with › 
❯ flutter-app-demo-9136a (flutter-app-demo)
  flutter-demo-latest (flutter-demo-latest)
  flutter-nc-demo (flutter-nc-demo)
  ftl-demo-eb6af (ftl-demo)
  test-f3bf9 (test)
  triage-79c7c (google-triage)
  woven-voyage-217607 (flutterci)
  <create a new project>

```

Can you upgrade to latest stable and try again ?

**Comment by chonghorizons** [comment]
@darshankawar . Thank you. 

I upgraded flutter from 2.5.3 to
> [✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale en-US)

**Comment by darshankawar** [comment]
@chonghorizons 
Since this is related to the CLI tool, I suggest you to open this in dedicated repo: https://github.com/invertase/flutterfire_cli/issues

https://firebase.flutter.dev/docs/cli/#reporting-an-issue

Closing from here.
