### ISSUE TITLE
[!] No podspec found for `firebase_core` in `.symlinks/plugins/firebase_core/ios`

### ISSUE THREAD

**Issue by jvegaseg** [FirebaseExtended/flutterfire#7721]
### Describe the bug
Latest firebase libraries doesn't build on iOS.

### Steps to reproduce

1.  Create a flutter app using Android Studio.

2.  Add the following firebase libs:

    _firebase_core: ^1.10.6
    firebase_messaging: ^11.2.4_

3. Run **flutter build ios**

### Expected behavior
The iOS app is built successfully.

## Additional context

Errors:
```
Building com.example.firebase for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: 8NY68CKZV6
Running pod install...                                           1.139ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    [!] No podspec found for `firebase_core` in `.symlinks/plugins/firebase_core/ios`

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:993:in `fetch_external_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:972:in `block (2 levels) in
    fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:971:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:971:in `block in fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:970:in `fetch_external_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:117:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `9.0` on target `Runner` because no platform was specified. Please specify
    a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
```

### flutter doctor -v

```
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale es-ES)
    • Flutter version 2.8.1 at /Users/jvegaseg/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (12 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/jvegaseg/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • ANDROID_HOME = /Users/jvegaseg/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/jvegaseg/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5556                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 13 mini (mobile)            • 1EA75B79-647C-4FAF-8CAA-932D56070826 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 96.0.4664.110

• No issues found!
```

### Flutter dependencies

```
Dart SDK 2.15.1
Flutter SDK 2.8.1
firebase 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- firebase_core 1.10.6 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.2.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.2.3 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.5 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.0.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1

```

### Additional versions

-  **xcode**: 13.2.1
- **pod --version**: 1.11.2
- **sudo gem which cocoapods**: /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods.rb

### Notes

1. Uncommenting in Podfile platform and using:

    _platform :ios, '10.0'_

    generates same error: **_[!] No podspec found for `firebase_core` in `.symlinks/plugins/firebase_core/ios`_**

2. Same results with **pod repo update**

**Comment by darshankawar** [comment]
@jvegaseg 
I tried your steps to replicate on a sample using latest stable and was able to build for iOS without any issues:

```
dhs@Dhss-MacBook-Pro macbug % flutter build ios
Building com.example.macbug for device (ios-release)...
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Found saved certificate choice "Apple Development: Darshan Kawar (AV76JL68FU)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "Apple Development: Darshan Kawar (AV76JL68FU)"
Running pod install...                                              7.1s
Running Xcode build...                                                  
 └─Compiling, linking and signing...                        21.1s
Xcode build done.                                           127.9s
Built /Users/dhs/Documents/NCFlutter/macbug/build/ios/iphoneos/Runner.app.
dhs@Dhss-MacBook-Pro macbug % 

```

Since you seem to be on M1, can you try [this](https://github.com/FirebaseExtended/flutterfire/issues/5984#issuecomment-831081249) solution and see if it helps ?

**Comment by jvegaseg** [comment]
I do not have M1 chip. I had tried that solution before I post this issue without results.
In any case, I have just done it again without any result:

```
sudo arch -x86_64 gem install ffi
Password:
Building native extensions. This could take a while...
Successfully installed ffi-1.15.4
Parsing documentation for ffi-1.15.4
Done installing documentation for ffi after 3 seconds
1 gem installed
➜  firebase cd ios
➜  ios arch -x86_64 pod install --repo-update
Updating local specs repositories
Analyzing dependencies
[!] No podspec found for `firebase_core` in `.symlinks/plugins/firebase_core/ios`
```

**Comment by darshankawar** [comment]
@jvegaseg 
Thanks, then above steps wouldn't be necessary.
Can you provide `ios/podfile`  and `flutter build ios --verbose` ?

**Comment by jvegaseg** [comment]
Of course, here you have it.

Podfile:

```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
```

flutter build ios --verbose log output:
[build.log](https://github.com/FirebaseExtended/flutterfire/files/7788727/build.log)

**Comment by darshankawar** [comment]
@jvegaseg 
Please confirm if you have `deployment target` set to `10` through xcode, as below:

<img width="662" alt="Screenshot 2021-12-30 at 2 19 25 PM" src="https://user-images.githubusercontent.com/67046386/147736277-556e70cb-c08c-4ae6-8299-a81c551eba16.png">

If not, try the same and run again which hopefully should fixe the issue.

**Comment by jvegaseg** [comment]
Same results:

![image](https://user-images.githubusercontent.com/12508470/147738763-47ef8613-de02-4057-831f-5b8011dc8c1b.png)


build log:

[build.log](https://github.com/FirebaseExtended/flutterfire/files/7792301/build.log)

**Comment by darshankawar** [comment]
Also try on below screen:

<img width="739" alt="Screenshot 2021-12-30 at 3 44 46 PM" src="https://user-images.githubusercontent.com/67046386/147742648-997f4b95-e0a9-46a3-a5b9-a38d1dda1c81.png">

**Comment by jvegaseg** [comment]
Same results

**Comment by jvegaseg** [comment]
Here attached logs:
[build.log](https://github.com/FirebaseExtended/flutterfire/files/7792515/build.log)

**Comment by jvegaseg** [comment]
A question, when you tried, were you using Xcode 13.2.1?

**Comment by jvegaseg** [comment]
Now I am downloading 12.5.1 in order to replace 13.2.1.

**Comment by jvegaseg** [comment]
I can not install Xcode 12.5.1 because it is not compatible with macOS Monterey.
So I continue with 13.2.1.

**Comment by jvegaseg** [comment]
if it were a clue, should compile from Xcode?

![image](https://user-images.githubusercontent.com/12508470/147765562-66a75f9a-ac34-42a0-887a-7e0b1b0044ae.png)

**Comment by darshankawar** [comment]
> were you using Xcode 13.2.1?

No, I am on 12.3.

My colleague tried the same on macOS Monterey and although he got a similar error (not exactly the same though), updating the deployment target at above referred locations helped him to get rid of those and he was able to compile properly:



> should it compile from Xcode?

Ideally, it should, yes.  Please try [this](https://github.com/flutter/flutter/issues/94914#issuecomment-992239759) solution and see if it helps.

**Comment by jvegaseg** [comment]
Great. It works!!!!

Steps done:

- Run flutter clean
- Delete .pub-cache from users//Library folder
- Delete .pub-cache from flutter folder
- Delete cache folder from flutter/bin
- Flutter doctor -v
- Flutter pub get

Thanks @darshankawar for your support.

**Comment by darshankawar** [comment]
Glad to know it is resolved. Happy New Year :)
Closing as resolved.
