### ISSUE TITLE
🐛 [firebase-core] configure fails with: Bad state: expecting only one entry for dependency

### ISSUE THREAD

**Issue by arisAlexis** [FirebaseExtended/flutterfire#7751]
## Bug report

**Describe the bug**
Flutterfire configure fails

### Steps to reproduce

1. Follow https://firebase.flutter.dev/docs/overview/
2. run 'flutterfire configure'

### Expected behavior

configuration happens

###Log

Unhandled exception:
Bad state: expecting only one entry for dependency
#0      new DependencyReference.fromJson (package:pubspec/src/dependency.dart:19:9)
#1      new PubSpec.fromJson.<anonymous closure> (package:pubspec/src/pubspec.dart:103:68)
#2      JsonParser.mapValues.<anonymous closure> (package:pubspec/src/json_utils.dart:113:45)
#3      MapMixin.forEach (dart:collection/maps.dart:123:13)
#4      JsonParser.mapValues (package:pubspec/src/json_utils.dart:112:7)
#5      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:103:15)
#6      PubSpec.loadFile (package:pubspec/src/pubspec.dart:121:15)
<asynchronous suspension>
#7      Package.load (package:flutterfire_cli/src/common/package.dart:54:21)
<asynchronous suspension>
#8      FlutterApp.load (package:flutterfire_cli/src/flutter_app.dart:39:21)
<asynchronous suspension>
#9      main (file:///C:/Users/arisg/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutterfire_cli-0.1.1+2/bin/flutterfire.dart:33:24)
<asynchronous suspension>
Unhandled exception:
Bad state: expecting only one entry for dependency
#0      new DependencyReference.fromJson (package:pubspec/src/dependency.dart:19:9)
#1      new PubSpec.fromJson.<anonymous closure> (package:pubspec/src/pubspec.dart:103:68)
#2      JsonParser.mapValues.<anonymous closure> (package:pubspec/src/json_utils.dart:113:45)
#3      MapMixin.forEach (dart:collection/maps.dart:123:13)
#4      JsonParser.mapValues (package:pubspec/src/json_utils.dart:112:7)
#5      new PubSpec.fromJson (package:pubspec/src/pubspec.dart:103:15)
#6      PubSpec.loadFile (package:pubspec/src/pubspec.dart:121:15)
<asynchronous suspension>
#7      Package.load (package:flutterfire_cli/src/common/package.dart:54:21)
<asynchronous suspension>
#8      FlutterApp.load (package:flutterfire_cli/src/flutter_app.dart:39:21)
<asynchronous suspension>
#9      main (file:///C:/Users/arisg/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/flutterfire_cli-0.1.1+2/bin/flutterfire.dart:33:24)
<asynchronous suspension>
---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.19042.1415], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.62.3)
[√] Connected device (2 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.15.1
Flutter SDK 2.8.1
acenotes 1.0.1+5

dependencies:
- cupertino_icons 1.0.4
- file_picker 4.3.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path]
- firebase_core 1.10.6 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_native_splash 1.3.2 [args image meta path xml yaml universal_io]
- intl 0.17.0 [clock path]
- path_provider 2.0.8 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 8.3.0 [flutter meta permission_handler_platform_interface]
- prompt_dialog 1.0.7 [flutter]
- provider 5.0.0 [collection flutter nested]
- purchases_flutter 3.8.0 [flutter collection]
- responsive_sizer 3.0.4+4 [flutter]
- rflutter_alert 2.0.4 [flutter]
- shared_preferences 2.0.11 [flutter meta shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sqflite 2.0.1 [flutter sqflite_common path]
- sqflite_common_porter 0.2.0+1 [path tekartik_common_utils csv sqflite_common_ffi]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.6 [crypto path]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- csv 5.0.1
- cv 0.2.5 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth 3.3.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_platform_interface 6.1.9 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.5 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.3 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.0 [archive meta xml]
- js 0.6.3
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- meta 1.7.0
- nested 1.0.0 [flutter]
- path 1.8.0
- path_provider_android 2.0.11 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.4 [ffi flutter meta path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.4 [flutter meta path_provider_platform_interface]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.4 [ffi flutter meta path path_provider_platform_interface win32]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.0.2 [meta]
- process 4.2.4 [file path platform]
- pub_semver 2.1.0 [collection meta]
- shared_preferences_android 2.0.9 [flutter meta shared_preferences_platform_interface]
- shared_preferences_ios 2.0.8 [flutter meta shared_preferences_platform_interface]
- shared_preferences_linux 2.0.3 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.2 [flutter flutter_web_plugins meta shared_preferences_platform_interface]
- shared_preferences_windows 2.0.3 [file flutter meta path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite_common 2.1.0 [synchronized path meta]
- sqflite_common_ffi 2.1.0 [sqlite3 sqflite_common synchronized path meta]
- sqlite3 1.4.0 [collection ffi meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- tekartik_common_utils 0.13.3 [path logging pub_semver synchronized meta lints cv tekartik_lints]
- tekartik_lints 0.1.2 [lints]
- term_glyph 1.2.0
- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- vector_math 2.1.1
- win32 2.3.3 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
@arisAlexis 
Although I am unable to replicate this issue and since it is related to CLI tool, it has a dedicated repo for tracking: https://github.com/invertase/flutterfire_cli/issues, so please open this issue there.
Closing from here.
