### ISSUE TITLE
🐛 [cloud_firestore] RuntimeException: java.lang.NoSuchMethodException: d.b.J1.values []

### ISSUE THREAD

**Issue by subair-zufi** [FirebaseExtended/flutterfire#7788]
## Bug report

**Describe the bug**

My application works fine on debug mode, and crashes on release mode with this exception:
```
> E/AndroidRuntime(26946): FATAL EXCEPTION: AsyncTask #1
E/AndroidRuntime(26946): Process: com.sirajulhuda.app, PID: 26946
E/AndroidRuntime(26946): java.lang.ExceptionInInitializerError
E/AndroidRuntime(26946):        at d.b.M1.o.forTarget(Unknown Source:0)
E/AndroidRuntime(26946):        at d.b.M1.p.a(:1)
E/AndroidRuntime(26946):        at d.b.J0.b(:2)
E/AndroidRuntime(26946):        at com.google.firebase.firestore.r0.V.e(:2)
E/AndroidRuntime(26946):        at com.google.firebase.firestore.r0.r.call(Unknown Source:2)
E/AndroidRuntime(26946):        at c.b.a.b.j.N.run(Unknown Source:4)
E/AndroidRuntime(26946):        at com.google.firebase.firestore.s0.H.a(:1)
E/AndroidRuntime(26946):        at com.google.firebase.firestore.s0.l.run(Unknown Source:4)
E/AndroidRuntime(26946):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(26946):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(26946):        at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(26946): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: d.b.J1.values []
E/AndroidRuntime(26946):        at java.lang.Enum.enumValues(Enum.java:270)
E/AndroidRuntime(26946):        at java.lang.Enum.access$000(Enum.java:61)
E/AndroidRuntime(26946):        at java.lang.Enum$1.create(Enum.java:277)
E/AndroidRuntime(26946):        at java.lang.Enum$1.create(Enum.java:275)
E/AndroidRuntime(26946):        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(26946):        at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime(26946):        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
E/AndroidRuntime(26946):        at java.util.EnumSet.getUniverse(EnumSet.java:407)
E/AndroidRuntime(26946):        at java.util.EnumSet.noneOf(EnumSet.java:109)
E/AndroidRuntime(26946):        at java.util.EnumSet.of(EnumSet.java:235)
E/AndroidRuntime(26946):        at d.b.M1.o.<clinit>(Unknown Source:102)
E/AndroidRuntime(26946):        ... 11 more
E/AndroidRuntime(26946): Caused by: java.lang.NoSuchMethodException: d.b.J1.values []
E/AndroidRuntime(26946):        at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime(26946):        at java.lang.Class.getDeclaredMethod(Class.java:2050)
E/AndroidRuntime(26946):        at java.lang.Enum.enumValues(Enum.java:267)
E/AndroidRuntime(26946):        ... 21 more
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.7 19H1519 darwin-x64, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[!] Xcode - develop for iOS and macOS (Xcode 12.4)
    ! Flutter recommends a minimum Xcode version of 13.0.0.
      Download the latest version or update via the Mac App Store.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] VS Code (version 1.63.2)
[✓] Connected device (2 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.15.1
Flutter SDK 2.8.1
app 2.0.1+201

dependencies:
- advance_pdf_viewer 2.0.0 [flutter flutter_cache_manager numberpicker path_provider]
- carousel_slider 4.0.0 [flutter]
- cloud_firestore 3.1.5 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- country_picker 2.0.9 [flutter]
- crypto 3.0.1 [collection typed_data]
- dio 4.0.4 [http_parser path]
- dotted_border 2.0.0+2 [flutter path_drawing]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- file_picker 4.2.4 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path]
- firebase_auth 3.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.6 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.2.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 10.2.4 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_inappwebview 5.3.2 [flutter]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- get 4.3.8 [flutter]
- get_storage 2.0.3 [flutter get path_provider]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- image_picker 0.8.4+4 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- infinite_scroll_pagination 3.1.0 [flutter sliver_tools]
- provider 6.0.1 [collection flutter nested]
- rxdart 0.27.3
- syncfusion_flutter_calendar 19.3.57 [flutter timezone syncfusion_flutter_core syncfusion_flutter_datepicker intl]
- url_launcher 6.0.16 [flutter meta url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- youtube_player_flutter 8.0.0 [flutter flutter_inappwebview]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_native_splash 1.3.1 [args image meta path xml yaml universal_io]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.6 [crypto path]
- args 2.3.0
- asn1lib 1.0.3
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.10 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.5 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- cross_file 0.3.2 [flutter js meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 6.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.2.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.3 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.5 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 4.0.11 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.5 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_cache_manager 3.1.3 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.4 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.8 [archive meta xml]
- image_picker_for_web 2.1.4 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- infinite_listview 1.1.0 [flutter]
- intl 0.17.0 [clock path]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- meta 1.7.0
- nested 1.0.0 [flutter]
- numberpicker 2.1.1 [flutter infinite_listview]
- path 1.8.0
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider 2.0.7 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.8 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.3 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.4 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- pointycastle 3.4.0 [collection convert js]
- process 4.2.4 [file path platform]
- sky_engine 0.0.99
- sliver_tools 0.2.5 [flutter]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.0.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- syncfusion_flutter_core 19.3.57 [vector_math flutter]
- syncfusion_flutter_datepicker 19.3.57 [flutter intl syncfusion_flutter_core]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.13 [flutter meta url_launcher_platform_interface]
- url_launcher_ios 6.0.13 [flutter meta url_launcher_platform_interface]
- url_launcher_linux 2.0.2 [flutter]
- url_launcher_macos 2.0.2 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.5 [crypto]
- vector_math 2.1.1
- win32 2.3.0 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by subair-zufi** [comment]
I just fixed adding 
```
            shrinkResources false
            minifyEnabled false
            useProguard false
```
in `buildTypes.release`
