### ISSUE TITLE
 [cloud_functions] flutter build android error

### ISSUE THREAD

**Issue by ldemyanenko** [FirebaseExtended/flutterfire#7868]
We are using Flutter 2.2.3 and  cloud_functions: ^3.2.5.
Current android  targetSdkVersion 30
Currently, on app start on Android platform, we are facing a strange error

```
W/e.getgaston.de(26302): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setUseSessionTickets(Z)V (greylist-max-q,test-api, reflection, denied)
W/OkHttp  (26302): unable to load android socket classes
W/OkHttp  (26302): java.lang.NoSuchMethodException: com.android.org.conscrypt.OpenSSLSocketImpl.setUseSessionTickets [boolean]
W/OkHttp  (26302): 	at java.lang.Class.getMethod(Class.java:2072)
W/OkHttp  (26302): 	at java.lang.Class.getDeclaredMethod(Class.java:2050)
W/OkHttp  (26302): 	at okhttp3.internal.platform.android.AndroidSocketAdapter.<init>(AndroidSocketAdapter.kt:34)
W/OkHttp  (26302): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter.<init>(StandardAndroidSocketAdapter.kt:31)
W/OkHttp  (26302): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported(StandardAndroidSocketAdapter.kt:57)
W/OkHttp  (26302): 	at okhttp3.internal.platform.android.StandardAndroidSocketAdapter$Companion.buildIfSupported$default(StandardAndroidSocketAdapter.kt:50)
W/OkHttp  (26302): 	at okhttp3.internal.platform.AndroidPlatform.<init>(AndroidPlatform.kt:44)
W/OkHttp  (26302): 	at okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported(AndroidPlatform.kt:239)
W/OkHttp  (26302): 	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:211)
W/OkHttp  (26302): 	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:179)
W/OkHttp  (26302): 	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:180)
W/OkHttp  (26302): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
W/OkHttp  (26302): 	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:211)
W/OkHttp  (26302): 	at com.google.firebase.functions.FirebaseFunctions.<init>(FirebaseFunctions.java:94)
W/OkHttp  (26302): 	at com.google.firebase.functions.FunctionsMultiResourceComponent.get(FunctionsMultiResourceComponent.java:49)
W/OkHttp  (26302): 	at com.google.firebase.functions.FirebaseFunctions.getInstance(FirebaseFunctions.java:171)
W/OkHttp  (26302): 	at io.flutter.plugins.firebase.functions.FlutterFirebaseFunctionsPlugin.getFunctions(FlutterFirebaseFunctionsPlugin.java:62)
W/OkHttp  (26302): 	at io.flutter.plugins.firebase.functions.FlutterFirebaseFunctionsPlugin.lambda$httpsFunctionCall$0$FlutterFirebaseFunctionsPlugin(FlutterFirebaseFunctionsPlugin.java:69)
W/OkHttp  (26302): 	at io.flutter.plugins.firebase.functions.FlutterFirebaseFunctionsPlugin$$ExternalSyntheticLambda1.call(Unknown Source:4)
W/OkHttp  (26302): 	at com.google.android.gms.tasks.zzx.run(com.google.android.gms:play-services-tasks@@17.2.1:1)
W/OkHttp  (26302): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/OkHttp  (26302): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/OkHttp  (26302): 	at java.lang.Thread.run(Thread.java:923)
```

It didn't happen previously when we had Flutter 1.22.5 and cloud_functions: ^0.7.0

**Comment by darshankawar** [comment]
@ldemyanenko 
Since 2.2.3 is an old version, can you try the same on latest stable (2.8.1) and see if you still get same exception ?
