### ISSUE TITLE
🐛 [firebase_database] Object? to JSON Model

### ISSUE THREAD

**Issue by lukeirvin** [FirebaseExtended/flutterfire#7899]
I'm working on a real-time Firebase listener to display a list of objects that I want to convert to my Model. 

I'm getting Unhandled Exceptions when trying to convert the data to a Model.

So the core question is, how do I convert `event.snapshot.value` which is an Object? into a Map<String, dynamic> or into JSON that I can use my Model?

Example:

```
_childStreamSub =
          ref.child("ChildABC").child('childKey').onValue.listen(
        (event) {
          setState(() {
                 Map<String, dynamic> data = jsonDecode(jsonEncode(event.snapshot.value));
                 final cleanData = Map<String, dynamic>.from(data);
                 final List<ChildModel> model = cleanData.values
                        .map(
                               (raw) => ChildModel.fromJson(raw),
                        )
                        .toList();
           }
}

```

My Debug Console:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'List<dynamic>' is not a subtype of type 'Map<String, dynamic>'
#0      _PageState._setListeners.<anonymous closure>.<anonymous closure>.<anonymous closure>
package:../pages/test_page.dart:85
#1      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#2      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#3      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#4      new List.of (dart:core-patch/array_patch.dart:50:28)
#5      Iterable.toList (dart:core/iterable.dart:388:12)
#6      _PageState._setListeners.<anonymous closure>.<anonymous closure>
package:../pages/test_page.dart:87
#7      State.setState
package:flutter/…/widgets/framework.dart:1088
#8      _PageState._setListeners.<anonymous closure>
package:../pages/test_page.dart:65
#9      _rootRunUnary (dart:async/zone.dart:1436:47)
#10     _Custom<…>

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: type 'String' is not a subtype of type 'Map<String, dynamic>'
#0      _PageState._setListeners.<anonymous closure>.<anonymous closure>.<anonymous closure>
package:../pages/test_page.dart:85
#1      MappedIterator.moveNext (dart:_internal/iterable.dart:391:20)
#2      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:198:26)
#3      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#4      new List.of (dart:core-patch/array_patch.dart:50:28)
#5      Iterable.toList (dart:core/iterable.dart:388:12)
#6      _PageState._setListeners.<anonymous closure>.<anonymous closure>
package:../pages/test_page.dart:87
#7      State.setState
package:flutter/…/widgets/framework.dart:1088
#8      _PageState._setListeners.<anonymous closure>
package:../pages/test_page.dart:65
#9      _rootRunUnary (dart:async/zone.dart:1436:47)
#10     _CustomZone.ru<…>
```

Version:
firebase_database: ^9.0.0

**Comment by darshankawar** [comment]
@lukeirvin 
Your question is better suited for support channels like StackOverflow, so please ask the same there. 
See this SO link for your reference: https://stackoverflow.com/questions/51854891/error-listdynamic-is-not-a-subtype-of-type-mapstring-dynamic
Closing from here.
