### ISSUE TITLE
[cloud_firestore] error-Invalid argument (dartObject): Could not convert: Instance of 'Duration' 

### ISSUE THREAD

**Issue by behnamsattar** [FirebaseExtended/flutterfire#7913]
Hey @ditman , While doing pagination on flutter web, cloud firestore gives error error-Invalid argument (dartObject): Could not convert: Instance of 'Duration'

```dart
final echoData = {
      MapKeys.storyID: story.id,
      MapKeys.positionTime: position,
};
final batch = firestore.batch();
batch.set(
  firestore.collection(FirestoreCollectionNames.echos).doc(echoID),
  echoData,
);
return batch.commit();
```

It seems like the web version of firestore has some issues regarding conversion of Duration to Timestamp when you're writing to a document.

Here is the top of the stack trace output:
```
Error: Invalid argument (dartObject): Could not convert: Instance of 'Duration'
    at Object.throw_ [as throw] (http://localhost:59970/dart_sdk.js:5063:11)
at Object.jsify (http://localhost:59970/packages/firebase_core_web/src/interop/utils/utils.dart.lib.js:73:17)
at http://localhost:59970/packages/firebase_core_web/src/interop/utils/utils.dart.lib.js:64:92
    at LinkedMap.new.forEach (http://localhost:59970/dart_sdk.js:27297:11)
at Object.jsify (http://localhost:59970/packages/firebase_core_web/src/interop/utils/utils.dart.lib.js:63:27)
at Object.jsify (http://localhost:59970/packages/cloud_firestore_web/src/interop/utils/utils.dart.lib.js:124:18)
at firestore.WriteBatch._fromJsObject.set (http://localhost:59970/packages/cloud_firestore_web/src/interop/utils/utils.dart.lib.js:465:161)
at write_batch_web.WriteBatchWeb.new.set (http://localhost:59970/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:187:36)
at cloud_firestore.WriteBatch.__.set (http://localhost:59970/packages/cloud_firestore/cloud_firestore.dart.lib.js:1922:31)
```

**Comment by darshankawar** [comment]
@behnamsattar 
Can you provide `flutter doctor -v` and a [complete minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that we can use to verify this behavior ?

**Comment by ditman** [comment]
> conversion of Duration to Timestamp

Not sure how you're modeling your data, but a `Duration` is not a `Timestamp`. If you want to store a `Timestamp` in Firebase, you should use a `DateTime` instead.

Here's the [conversion code](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore_web/lib/src/interop/utils/utils.dart#L43-L45) (as you can see, it doesn't handle `Duration`s at all, AFAIK).

> It seems like the web version of firestore has some issues regarding conversion of Duration to Timestamp

Have you tested this code in a mobile app? What's the expected result of your code?

**Comment by behnamsattar** [comment]
@ditman 
> Have you tested this code in a mobile app? What's the expected result/behavior of your code?

I looked back at the code I had from last year where I was saving Duration objects and saw that I converted them to String objects before passing them to Firestore. There is no issue here if there has not been a Duration conversion in place in the first place.
