### ISSUE TITLE
🐛 [firebase_database] Uncaught exception in Firebase Database runloop (20.0.2)

### ISSUE THREAD

**Issue by deepak786** [FirebaseExtended/flutterfire#7958]
Crashlytics shows the following exeption:

```
Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.2). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk
       at com.google.firebase.database.android.AndroidPlatform$1$1.run(AndroidPlatform.java:6)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7631)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

Caused by android.database.sqlite.SQLiteException: cannot rollback - no transaction is active (code 1 SQLITE_ERROR)
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:649)
       at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:441)
       at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:403)
       at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:589)
       at com.google.firebase.database.android.SqlPersistenceStorageEngine.endTransaction(SqlPersistenceStorageEngine.java:2)
       at com.google.firebase.database.core.persistence.DefaultPersistenceManager.runInTransaction(DefaultPersistenceManager.java:37)
       at com.google.firebase.database.core.SyncTree.applyServerOverwrite(SyncTree.java:7)
       at com.google.firebase.database.core.SyncTree.applyServerRangeMerges(SyncTree.java:46)
       at com.google.firebase.database.core.Repo.onRangeMergeUpdate(Repo.java:135)
       at com.google.firebase.database.connection.PersistentConnectionImpl.onDataPush(PersistentConnectionImpl.java:202)
       at com.google.firebase.database.connection.PersistentConnectionImpl.onDataMessage(PersistentConnectionImpl.java:74)
       at com.google.firebase.database.connection.Connection.onDataMessage(Connection.java:39)
       at com.google.firebase.database.connection.Connection.onMessage(Connection.java:25)
       at com.google.firebase.database.connection.WebsocketConnection.appendFrame(WebsocketConnection.java:71)
       at com.google.firebase.database.connection.WebsocketConnection.handleIncomingFrame(WebsocketConnection.java:13)
       at com.google.firebase.database.connection.WebsocketConnection.access$500(WebsocketConnection.java)
       at com.google.firebase.database.connection.WebsocketConnection$WSClientTubesock$2.run(WebsocketConnection.java:6)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**_Note: no reproducible steps._**

**Comment by darshankawar** [comment]
@deepak786 
Looking at the first line of the error:

`Fatal Exception: java.lang.RuntimeException: Uncaught exception in Firebase Database runloop (20.0.2). If you are not already on the latest version of the Firebase SDKs, try updating your dependencies. Should this problem persist, please file a report at https://github.com/firebase/firebase-android-sdk`

It seems to be related to Firebase SDK and not `firebase_database`, so you'll probably need to open this in native [repo](https://github.com/firebase/firebase-android-sdk/issues).

I already see a [similar](https://github.com/firebase/firebase-android-sdk/issues/3074) issue fixed in their SDK and awaiting release I guess: https://github.com/firebase/firebase-android-sdk/issues/3074#issuecomment-972345259

Closing from here as not a flutterfire plugin issue.
