### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'RecaptchaVerifier')

### ISSUE THREAD

**Issue by seanwestfall** [FirebaseExtended/flutterfire#7999]
## Bug report

Getting a TypeError when trying to run the basic `signInWithPhoneNumber` function:

```
TypeError: Cannot read properties of undefined (reading 'RecaptchaVerifier')
    at Function.new
    (http://localhost:50000/packages/firebase_auth_web/src/interop/auth.dart.lib
    .js:858:263)
    at new
    firebase_auth_web_recaptcha_verifier_factory.RecaptchaVerifierFactoryWeb.new
    (http://localhost:50000/packages/firebase_auth_web/src/firebase_auth_web_rec
    aptcha_verifier_factory.dart.lib.js:167:49)
    at
    firebase_auth_web_recaptcha_verifier_factory.RecaptchaVerifierFactoryWeb.__.
    delegateFor
    (http://localhost:50000/packages/firebase_auth_web/src/firebase_auth_web_rec
    aptcha_verifier_factory.dart.lib.js:77:14)
    at Function.new
    (http://localhost:50000/packages/firebase_auth/firebase_auth.dart.lib.js:663
    :94)
    at login_screen._LoginScreenState.new.<anonymous>
    (http://localhost:50000/packages/flutter_restaurant/view/screens/auth/login_
    screen.dart.lib.js:880:146)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:50000/dart_sdk.js:40666:34)
    at Object._async [as async] (http://localhost:50000/dart_sdk.js:40697:7)
    at
    http://localhost:50000/packages/flutter_restaurant/view/screens/auth/login_s
    creen.dart.lib.js:872:652
    at ink_well._InkResponseState.new.[_handleTap]
    (http://localhost:50000/packages/flutter/src/material/icon_button.dart.lib.j
    s:35805:31)
    at tap.TapGestureRecognizer.new.invokeCallback
    (http://localhost:50000/packages/flutter/src/gestures/recognizer.dart.lib.js
    :196:18)
    at tap.TapGestureRecognizer.new.handleTapUp
    (http://localhost:50000/packages/flutter/src/gestures/tap.dart.lib.js:408:40
    )
    at tap.TapGestureRecognizer.new.[_checkUp]
    (http://localhost:50000/packages/flutter/src/gestures/tap.dart.lib.js:214:12
    )
    at tap.TapGestureRecognizer.new.handlePrimaryPointer
    (http://localhost:50000/packages/flutter/src/gestures/tap.dart.lib.js:160:23
    )
    at tap.TapGestureRecognizer.new.handleEvent
    (http://localhost:50000/packages/flutter/src/gestures/recognizer.dart.lib.js
    :456:16)
    at pointer_router.PointerRouter.new.[_dispatch]
    (http://localhost:50000/packages/flutter/src/gestures/pointer_router.dart.li
    b.js:93:9)
    at
    http://localhost:50000/packages/flutter/src/gestures/pointer_router.dart.lib
    .js:128:26
    at LinkedMap.new.forEach (http://localhost:50000/dart_sdk.js:27705:11)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes]
    (http://localhost:50000/packages/flutter/src/gestures/pointer_router.dart.li
    b.js:125:29)
    at pointer_router.PointerRouter.new.route
    (http://localhost:50000/packages/flutter/src/gestures/pointer_router.dart.li
    b.js:117:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent
    (http://localhost:50000/packages/flutter/src/gestures/binding.dart.lib.js:38
    9:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:50000/packages/flutter/src/gestures/binding.dart.lib.js:37
    2:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:50000/packages/flutter/src/rendering/layer.dart.lib.js:546
    8:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately]
    (http://localhost:50000/packages/flutter/src/gestures/binding.dart.lib.js:34
    3:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent
    (http://localhost:50000/packages/flutter/src/gestures/binding.dart.lib.js:31
    6:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue]
    (http://localhost:50000/packages/flutter/src/gestures/binding.dart.lib.js:30
    5:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket]
    (http://localhost:50000/packages/flutter/src/gestures/binding.dart.lib.js:29
    5:65)
    at Object.invoke1 (http://localhost:50000/dart_sdk.js:190712:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket
    (http://localhost:50000/dart_sdk.js:169575:15)
    at _engine.PointerBinding.__.[_onPointerData]
    (http://localhost:50000/dart_sdk.js:170460:49)
    at http://localhost:50000/dart_sdk.js:170919:28
    at http://localhost:50000/dart_sdk.js:170872:16
    at loggedHandler (http://localhost:50000/dart_sdk.js:170564:11)
```

### Steps to reproduce

1. follow https://firebase.flutter.dev/docs/auth/phone#web-signinwithphonenumber exactly
2. run the app 'flutter run', and don't forget to setup `firebaseConfig` for web
4. See the stack trace when you run the `signInWithPhoneNumber` function

### Expected behavior

It should show the recaptcha widget, but it just throws the exception instead.

### Sample project

Example code:
```dart
var body = querySelector('body');
DivElement div = new DivElement();
div.id = "recaptcha-div";
body.children.add(div);

FirebaseAuth auth = FirebaseAuth.instance;
ConfirmationResult confirmationResult = await auth.signInWithPhoneNumber('+1 888 888 8888', RecaptchaVerifier(
  container: 'recaptcha-div',
  size: RecaptchaVerifierSize.compact,
  theme: RecaptchaVerifierTheme.dark,
));
```

---

## Additional context

<details><summary>Click To Expand</summary>

I should mention that I am importing `firebasejs 8.10.0` from the index.html file.

```html
<!DOCTYPE html>
<html>
<head>
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <title></title>
  <link rel="manifest" href="manifest.json">
  <link rel="stylesheet" type="text/css" href="style.css">

  <!--<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">-->

  <link rel="shortcut icon" type="image/png" href="favicon.png"/>


    <!-- // Other stuff -->

    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY_HERE"></script>

</head>
<body>
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
        navigator.serviceWorker.register("/firebase-messaging-sw.js");
      });
    }
  </script>
  <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-messaging.js"></script>

  <img class="center" src="load.gif" />

  <script>
    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    var firebaseConfig = {
      apiKey: '...',
      authDomain: '...',
      projectId: '...',
      storageBucket: "...",
      messagingSenderId: '...',
      appId: '...',
      measurementId: "..."
    };

    // Initialize Firebase
    firebase.initializeApp(firebaseConfig);
  </script>
  <script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```
</details>

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.4 19E287 darwin-x64,
    locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with
        is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.
```

^ this is for the web only, so it's not something I have tried on an actual native device yet.

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
flutter_restaurant 1.0.1+2

dependencies:
- carousel_slider 3.0.0 [flutter]
- connectivity 3.0.3 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- cupertino_icons 1.0.2
- dio 4.0.0-prev3 [http_parser path]
- firebase_auth 3.3.6 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_web 3.3.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.1.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- fluro 2.0.3 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_credit_card 0.1.4 [flutter]
- flutter_local_notifications 5.0.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_stripe 2.0.2 [flutter stripe_android stripe_ios stripe_platform_interface]
- geocoding 2.0.0 [flutter geocoding_platform_interface]
- geolocator 7.0.1 [flutter geolocator_platform_interface geolocator_web]
- get_it 6.0.0 [async collection]
- google_maps_flutter 2.0.3 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_maps_flutter_web 0.3.0 [flutter flutter_web_plugins meta google_maps_flutter_platform_interface google_maps stream_transform sanitize_html]
- http 0.13.4 [async http_parser meta path]
- image 3.0.2 [archive meta xml]
- image_picker 0.7.5+2 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- intl_phone_number_input 0.7.0+2 [flutter meta libphonenumber_plugin equatable collection]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pin_code_fields 7.3.0 [flutter]
- progress_dialog 1.2.4 [flutter]
- provider 5.0.0 [collection flutter nested]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 2.0.0-nullsafety.0 [flutter]
- universal_html 2.0.8 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_ui 0.0.8 [flutter]
- url_launcher 6.0.2 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
- url_strategy 0.2.0 [flutter_web_plugins]
- webview_flutter 2.0.2 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- connectivity_for_web 0.4.0 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.2.0 [flutter]
- connectivity_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.0 [source_span]
- equatable 2.0.3 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 6.1.11 [firebase_core flutter meta plugin_platform_interface]
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- freezed_annotation 0.14.3 [collection json_annotation meta]
- geocoding_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- geolocator_platform_interface 2.0.0 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.1 [flutter flutter_web_plugins geolocator_platform_interface]
- google_maps 5.1.0 [js_wrapping meta]
- google_maps_flutter_platform_interface 2.0.2 [flutter meta plugin_platform_interface stream_transform collection]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.0.1 [flutter meta http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.3
- js_wrapping 0.7.0 [js]
- json_annotation 4.4.0 [meta]
- libphonenumber 2.0.2 [flutter meta]
- libphonenumber_platform_interface 0.3.1 [flutter plugin_platform_interface]
- libphonenumber_plugin 0.2.3 [flutter flutter_web_plugins libphonenumber_platform_interface libphonenumber_web libphonenumber]
- libphonenumber_web 0.2.0+1 [flutter flutter_web_plugins js libphonenumber_platform_interface]
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- nested 1.0.0 [flutter]
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.1.1 [file path platform]
- sanitize_html 2.0.0 [html meta]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- stripe_android 2.0.2 [flutter]
- stripe_ios 2.0.2 [flutter]
- stripe_platform_interface 2.0.2 [flutter freezed_annotation json_annotation meta plugin_platform_interface]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0-nullsafety.0 [path]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.1 [collection meta petitparser]
```

</details>

---

**Comment by darshankawar** [comment]
@seanwestfall 
For some reason, while running the firebase_auth example app on web, I am getting `network error` while trying to `signInWithPhoneNumber`, so I am unable to verify the behavior you reported.

Can you try the plugin's [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example) and see if you still get same error as you reported ?

**Comment by seanwestfall** [comment]
@darshankawar I am also getting the same error on the example app:

```bash
flutter run --web-port 50000
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             24.0s
This app is linked to the debug service: ws://127.0.0.1:50684/US-9cIDOAK8=/ws
Debug service listening on ws://127.0.0.1:50684/US-9cIDOAK8=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:50684/US-9cIDOAK8=
WARNING: You are using the Auth Emulator, which is intended for local testing only.  Do not use with production credentials.
Activating Dart DevTools...                                      2,846ms
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:50684/US-9cIDOAK8=
Error: [firebase_auth/network-request-failed] A network error (such as timeout, interrupted connection or unreachable host) has occurred.
    at Object.throw_ [as throw] (http://localhost:50000/dart_sdk.js:5061:11)
    at firebase_auth_web.FirebaseAuthWeb.new.signInWithPhoneNumber (http://localhost:50000/packages/firebase_auth_web/firebase_auth_web.dart.lib.js:337:23)
    at signInWithPhoneNumber.throw (<anonymous>)
    at http://localhost:50000/dart_sdk.js:38645:38
    at _RootZone.runBinary (http://localhost:50000/dart_sdk.js:38515:59)
    at _FutureListener.thenAwait.handleError (http://localhost:50000/dart_sdk.js:33724:33)
    at handleError (http://localhost:50000/dart_sdk.js:34281:51)
    at Function._propagateToListeners (http://localhost:50000/dart_sdk.js:34307:17)
    at _Future.new.[_completeError] (http://localhost:50000/dart_sdk.js:34157:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:50000/dart_sdk.js:34193:31)
    at Object._microtaskLoop (http://localhost:50000/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:50000/dart_sdk.js:38784:13)
    at http://localhost:50000/dart_sdk.js:34519:9
```
<img width="612" alt="Screen Shot 2022-02-03 at 6 14 11 PM" src="https://user-images.githubusercontent.com/9439906/152461390-a6a73b61-5cd5-43fc-b15a-0fbe00987c3f.png">

I will continue to investigate.

**Comment by darshankawar** [comment]
@seanwestfall 
Thanks. If you could provide a minimal reproducible code or a sample app that we can clone directly and run that triggers the error you reported, would be good.

**Comment by seanwestfall** [comment]
@darshankawar For the previous error, I'm just reporting that I'm getting the same error as you from the main example over at https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example

Though, I copied the code from that example and I did actually get a working example of the phone based authentication working, here is a working example of flutterfire phone auth:
https://github.com/seanwestfall/flutterfire_test

Though, I still haven't found why I am getting the original error from this issue. Will update when I know why.

**Comment by darshankawar** [comment]
Thanks for the update. I tried running your app, but have been getting some compile errors that I'll check.

**Comment by seanwestfall** [comment]
I just pulled it down and I didn't get any compiler errors:
```bash
flutter clean; flutter build web
╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                     ║
║                                                                            ║
║ To update to the latest version, run "flutter upgrade".                    ║
╚════════════════════════════════════════════════════════════════════════════╝


Running "flutter pub get" in flutterfire_test2...                   3.2s

💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                             51.0s
```

are you using a different version of flutter?

```bash
$ flutter --version
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (4 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

**Comment by ndungudedan** [comment]
Try adding this import in your index.html file

`  <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-auth.js"></script>
`

**Comment by chiragpandey15** [comment]
Remove second argument of signInWithPhoneNumber function and add these two lines in your index.html

<script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-app.js"></script>
 <script src="https://www.gstatic.com/firebasejs/8.10.0/firebase-auth.js"></script>

**Comment by seanwestfall** [comment]
@darshankawar @chiragpandey15 @ndungudedan So that worked, it now loads the google captcha thing, thanks guys!

Though, I'm curious as to why this works for my previous project, but it isn't necessary for my example project. I might work on looking into this further.

Should we close this issue then?

**Comment by darshankawar** [comment]
Thanks for the update. Closing this as resolved.
