### ISSUE TITLE
🐛 [firebase_core] Hot Restart: A Firebase App named "secondary" already exists & RuntimeException: Internal error in Cloud Firestore

### ISSUE THREAD

**Issue by Sese-Schneider** [FirebaseExtended/flutterfire#8005]
## Bug report

When registering a secondary app in main, hot restart breaks for the whole app (i.e. if you await the initialization).

**Describe the bug**
This bug was already reported here: https://github.com/FirebaseExtended/flutterfire/issues/7938 by @creativecreatorormaybenot 
However, the fix https://github.com/FirebaseExtended/flutterfire/pull/7953 has no effect and didn't fix the issue for me.

**Furthermore**: Its 50/50 if either my app 
- _freezes_ and a Flutter Crash Report happens.
- **Android** _crashes_ with a Java RuntimeException in `firestore`

Crash reports:
<details>
<summary>Firebase Flutter Crash Report</summary>

```
E/flutter (10551): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [core/duplicate-app] A Firebase App named "secondary" already exists
E/flutter (10551): #0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:128:7)
E/flutter (10551): <asynchronous suspension>
E/flutter (10551): #1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:42:31)
E/flutter (10551): <asynchronous suspension>
E/flutter (10551): #2      Future.wait.<anonymous closure> (dart:async/future.dart)
E/flutter (10551): <asynchronous suspension>
E/flutter (10551): #3      initializeFirebaseApps (package:[REDACTED]_flutter/framework/firebase/init.dart:31:3)
E/flutter (10551): <asynchronous suspension>
E/flutter (10551): #4      main (package:[REDACTED]_flutter/main.dart:22:3)
E/flutter (10551): <asynchronous suspension>
```

</details>
<details>
<summary>Android Crash Report</summary>

```
D/AndroidRuntime( 9833): Shutting down VM
E/AndroidRuntime( 9833): FATAL EXCEPTION: main
E/AndroidRuntime( 9833): Process: [REDACTED], PID: 9833
E/AndroidRuntime( 9833): java.lang.RuntimeException: Internal error in Cloud Firestore (24.0.1).
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:539)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$jx84dqgUsF4ojecSMurRqFLFD1Y.run(Unknown Source:2)
E/AndroidRuntime( 9833): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime( 9833): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 9833): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime( 9833): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime( 9833): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9833): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime( 9833): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime( 9833): Caused by: java.lang.RuntimeException: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:330)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$SynchronizedShutdownAwareExecutor$pKSAgg-ozJ8RbUveSl-44aUfFQw.run(Unknown Source:4)
E/AndroidRuntime( 9833): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AndroidRuntime( 9833): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 9833): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AndroidRuntime( 9833): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 9833): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:234)
E/AndroidRuntime( 9833): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime( 9833): Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY)
E/AndroidRuntime( 9833): 	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
E/AndroidRuntime( 9833): 	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:707)
E/AndroidRuntime( 9833): 	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:325)
E/AndroidRuntime( 9833): 	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:300)
E/AndroidRuntime( 9833): 	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:571)
E/AndroidRuntime( 9833): 	at android.database.sqlite.SQLiteDatabase.beginTransactionWithListener(SQLiteDatabase.java:534)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.local.SQLitePersistence.runTransaction(SQLitePersistence.java:211)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.local.SQLiteOverlayMigrationManager.buildOverlays(SQLiteOverlayMigrationManager.java:46)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.local.SQLiteOverlayMigrationManager.run(SQLiteOverlayMigrationManager.java:42)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.local.LocalStore.start(LocalStore.java:186)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.core.ComponentProvider.initialize(ComponentProvider.java:145)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.core.FirestoreClient.initialize(FirestoreClient.java:273)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.core.FirestoreClient.lambda$new$0$FirestoreClient(FirestoreClient.java:109)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.core.-$$Lambda$FirestoreClient$Eq-cAcb1C1mM4tyiJsLJXZ13tyU.run(Unknown Source:8)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$2(AsyncQueue.java:441)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$Y9GO7zO2DX6MzQJ5TbKtKW_NzO0.call(Unknown Source:2)
E/AndroidRuntime( 9833): 	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.lambda$executeAndReportResult$1(AsyncQueue.java:327)
E/AndroidRuntime( 9833): 	... 8 more
```

</details>

### Steps to reproduce

I have a dependency override in place with the fix on `master`:

```
dependency_overrides:
  firebase_core:
    git:
      url: git@github.com:FirebaseExtended/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: f4a2c2e63e4dd4f888583110cc65ec84dec14dd7
```

See: https://github.com/FirebaseExtended/flutterfire/issues/7938
```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  await Firebase.initializeApp(
    name: 'secondary',
    options: SecondaryFirebaseOptions.currentPlatform,
  );

  runApp(..);
}
```

### Expected behavior

The app can be started, but hot restarts are not possible.

@darshankawar @russellwheatley I think this is a regression to https://github.com/FirebaseExtended/flutterfire/pull/7953

### Versions

<details><summary>Flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22000.434], locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[☠] IntelliJ IDEA Ultimate Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about
      this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
[✓] Connected device (4 available)
```

</details>

`firebase_core: f4a2c2e63e4dd4f888583110cc65ec84dec14dd7`

**Comment by russellwheatley** [comment]
Hey @Sese-Schneider, thanks for the report.  I've just retested in core example and it works fine without duplicate app exception. Could you provide a repro project if you think this does not work, please?

The android crash report is a separate issue that we are aware of and ought to be addressed in the next release 👍

**Comment by creativecreatorormaybenot** [comment]
@russellwheatley I can still reproduce this (e.g. on web).
