### ISSUE TITLE
🐛 Firebase Web isn't initializing.

### ISSUE THREAD

**Issue by rsegecin** [FirebaseExtended/flutterfire#8012]
## Bug report

I've automatically configured firebase project running `flutterfire.bat configure` and using `google_sign_in` package I was able to login in my app running on Android but I'm not even able to initialize firebase web as it throws an error right on `await Firebase.initializeApp`. I've seen that there's another closed thread about this problem #5334 which they say this issue was already fixed but apparently it hasn't. I've tested in both master and stable channels with same result. (I logged with a google just to be sure that the firebase was running correctly, again, it worked on Android but it didn't on Web).

Error thrown at `await Firebase.initializeApp`:

    Error: Expected a value of type 'Object', but got one of type 'Null'
        at Object.throw_ [as throw] (http://localhost:30292/dart_sdk.js:5067:11)
        at Object.castError (http://localhost:30292/dart_sdk.js:5026:15)
        at Object.cast [as as] (http://localhost:30292/dart_sdk.js:5351:17)
        at Function.as (http://localhost:30292/dart_sdk.js:6576:31)
        at firebase_core_web.FirebaseCoreWeb.new.get [_ignoredServiceScripts] (http://localhost:30292/packages/firebase_core_web/firebase_core_web.dart.lib.js:142:65)
        at firebase_core_web.FirebaseCoreWeb.new._initializeCoreRequireJs (http://localhost:30292/packages/firebase_core_web/firebase_core_web.dart.lib.js:187:27)
        at _initializeCoreRequireJs.next (<anonymous>)
        at runBody (http://localhost:30292/dart_sdk.js:40590:34)
        at Object._async [as async] (http://localhost:30292/dart_sdk.js:40621:7)
        at firebase_core_web.FirebaseCoreWeb.new.[_initializeCoreRequireJs] (http://localhost:30292/packages/firebase_core_web/firebase_core_web.dart.lib.js:182:20)
        at firebase_core_web.FirebaseCoreWeb.new.initializeApp (http://localhost:30292/packages/firebase_core_web/firebase_core_web.dart.lib.js:214:47)
        at initializeApp.next (<anonymous>)
        at runBody (http://localhost:30292/dart_sdk.js:40590:34)
        at Object._async [as async] (http://localhost:30292/dart_sdk.js:40621:7)
        at firebase_core_web.FirebaseCoreWeb.new.initializeApp (http://localhost:30292/packages/firebase_core_web/firebase_core_web.dart.lib.js:210:20)
        at initializeApp (http://localhost:30292/packages/firebase_core/firebase_core.dart.lib.js:100:59)
        at initializeApp.next (<anonymous>)
        at runBody (http://localhost:30292/dart_sdk.js:40590:34)
        at Object._async [as async] (http://localhost:30292/dart_sdk.js:40621:7)
        at Function.initializeApp (http://localhost:30292/packages/firebase_core/firebase_core.dart.lib.js:99:20)
        at main (http://localhost:30292/packages/mice_online_app/main.dart.lib.js:576:36)
        at main.next (<anonymous>)
        at http://localhost:30292/dart_sdk.js:40571:33
        at _RootZone.runUnary (http://localhost:30292/dart_sdk.js:40441:59)
        at _FutureListener.thenAwait.handleValue (http://localhost:30292/dart_sdk.js:35363:29)
        at handleValueCallback (http://localhost:30292/dart_sdk.js:35931:49)
        at Function._propagateToListeners (http://localhost:30292/dart_sdk.js:35969:17)
        at _Future.immediate.[_completeWithValue] (http://localhost:30292/dart_sdk.js:35817:23)
        at async._AsyncCallbackEntry.new.callback (http://localhost:30292/dart_sdk.js:35838:35)
        at Object._microtaskLoop (http://localhost:30292/dart_sdk.js:40708:13)
        at _startMicrotaskLoop (http://localhost:30292/dart_sdk.js:40714:13)
        at http://localhost:30292/dart_sdk.js:36191:9

Error thrown at `await Firebase.initializeApp` after running flutter with "--no-sound-null-safety":

    Error: Invalid argument(s): object cannot be a num, string, bool, or null
        at Object.throw_ [as throw] (http://localhost:29886/dart_sdk.js:5391:11)
        at Function.fromBrowserObject (http://localhost:29886/dart_sdk.js:66382:19)
        at firebase_core_web.FirebaseCoreWeb.new.get [_ignoredServiceScripts] (http://localhost:29886/packages/firebase_core_web/firebase_core_web.dart.lib.js:152:35)
        at firebase_core_web.FirebaseCoreWeb.new._initializeCoreRequireJs (http://localhost:29886/packages/firebase_core_web/firebase_core_web.dart.lib.js:199:27)
        at _initializeCoreRequireJs.next (<anonymous>)
        at runBody (http://localhost:29886/dart_sdk.js:43013:34)
        at Object._async [as async] (http://localhost:29886/dart_sdk.js:43044:7)
        at firebase_core_web.FirebaseCoreWeb.new.[_initializeCoreRequireJs] (http://localhost:29886/packages/firebase_core_web/firebase_core_web.dart.lib.js:194:20)
        at firebase_core_web.FirebaseCoreWeb.new.initializeApp (http://localhost:29886/packages/firebase_core_web/firebase_core_web.dart.lib.js:227:47)
        at initializeApp.next (<anonymous>)
        at runBody (http://localhost:29886/dart_sdk.js:43013:34)
        at Object._async [as async] (http://localhost:29886/dart_sdk.js:43044:7)
        at firebase_core_web.FirebaseCoreWeb.new.initializeApp (http://localhost:29886/packages/firebase_core_web/firebase_core_web.dart.lib.js:223:20)
        at initializeApp (http://localhost:29886/packages/firebase_core/firebase_core.dart.lib.js:111:59)
        at initializeApp.next (<anonymous>)
        at runBody (http://localhost:29886/dart_sdk.js:43013:34)
        at Object._async [as async] (http://localhost:29886/dart_sdk.js:43044:7)
        at Function.initializeApp (http://localhost:29886/packages/firebase_core/firebase_core.dart.lib.js:110:20)
        at main (http://localhost:29886/packages/mice_online_app/main.dart.lib.js:609:36)
        at main.next (<anonymous>)
        at http://localhost:29886/dart_sdk.js:42993:33
        at _RootZone.runUnary (http://localhost:29886/dart_sdk.js:42849:58)
        at _FutureListener.thenAwait.handleValue (http://localhost:29886/dart_sdk.js:37417:29)
        at handleValueCallback (http://localhost:29886/dart_sdk.js:38020:49)
        at Function._propagateToListeners (http://localhost:29886/dart_sdk.js:38058:17)
        at _Future.immediate.[_completeWithValue] (http://localhost:29886/dart_sdk.js:37900:23)
        at async._AsyncCallbackEntry.new.callback (http://localhost:29886/dart_sdk.js:37923:35)
        at Object._microtaskLoop (http://localhost:29886/dart_sdk.js:43153:13)
        at _startMicrotaskLoop (http://localhost:29886/dart_sdk.js:43159:13)
        at http://localhost:29886/dart_sdk.js:38289:9

### Steps to reproduce

1. Create a flutter app
2. Configure Firebase 
3. Run app on Web
5. See error.

### Expected behavior

Firebase to initialize for web.

### Sample project

https://gist.github.com/rsegecin/f9cceb81d6bfd6e715badb0a032ae4ec

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.19044.1466], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.3)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.64.0)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.0
Flutter SDK 2.10.0
funtestic 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- firebase_auth 3.3.6 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_web 3.3.7 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- google_sign_in 5.2.3 [flutter google_sign_in_platform_interface google_sign_in_web]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 6.1.11 [firebase_core flutter meta plugin_platform_interface]
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- google_sign_in_platform_interface 2.1.1 [flutter quiver]
- google_sign_in_web 0.10.0+4 [flutter flutter_web_plugins google_sign_in_platform_interface js pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- pedantic 1.11.1
- plugin_platform_interface 2.1.2 [meta]
- quiver 3.0.1+1 [matcher]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
```

</details>

---

**Comment by rsegecin** [comment]
I hope it hasn't taken time of anyone. Apparently it was some corrupted cache, after I did `flutter pub cache repair` its not stuck on `Firebase.initializeApp` anymore, I'm still getting stuck at google sign in though saying that appClientId is null but that is another problem.

**Comment by darshankawar** [comment]
@rsegecin 
I used your code sample and ran it on latest stable on web which compiled and built properly without any issues:

```
dhs@Dhss-MacBook-Pro ios_bug % flutter run -d chrome
Downloading Web SDK...                                             38.8s
Downloading CanvasKit...                                            7.5s
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             21.6s
This app is linked to the debug service: ws://127.0.0.1:52693/sxUjA4jgdeY=/ws
Debug service listening on ws://127.0.0.1:52693/sxUjA4jgdeY=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:52693/sxUjA4jgdeY=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:52693/sxUjA4jgdeY=

```

<img width="785" alt="Screenshot 2022-02-04 at 5 16 48 PM" src="https://user-images.githubusercontent.com/67046386/152524135-b801ba8f-0c16-41bd-b0b3-6cbb1930dc3a.png">

The app I ran was already configured through CLI tool and use `firebaseOptions` inside `main()`.

**Comment by rsegecin** [comment]
were you able to login?

**Comment by isanecat** [comment]
I have the same issue but isn't allowed to share the code.

**Comment by darshankawar** [comment]
> Did you configured with one of your Firebase's Project? Were you able to login? In the debug options check if you're catching all exceptions.

Yes, the firebase project is configured already. Tapping on `login` didn't perform any action and browser console, I don't see any logs.

**Comment by rsegecin** [comment]
> > Did you configured with one of your Firebase's Project? Were you able to login? In the debug options check if you're catching all exceptions.
> 
> Yes, the firebase project is configured already. Tapping on `login` didn't perform any action and browser console, I don't see any logs.

It should print out "you've logged" in the debug console after tapping login and selecting with what google account you want to use for login. But the simply fact that you've checked "All exceptions" and still not getting any errors when seeing the page already bugs me. The code that I posted to test, configured with firebase is all there is. Why it works when I'm running it as android app but not on browser? I've tried to change to dev flutter channel with the same result. I haven't seeing in the documentation any additional steps that I should take for deployment on Web, is it there any?. @isanecat glad to hear that I'm not alone with this problem.

**Comment by rsegecin** [comment]
To continue trying to solve this problem I tried the Manual Configuration and I was able to get much further, up until google sign in itself where I was able to select a google account and signin but on the flutter side the code gets stuck at 

`await FirebaseAuth.instance.signInWithCredential(credential)`

After the user tries to login using google's authentication form from the iframe it tries to save a cookie in the user's browser but it breaks saying:

<img width="577" alt="cookieerror" src="https://user-images.githubusercontent.com/4460859/152880596-73193b63-35ae-47a8-aaf9-c93704d558ca.png">

Which it is a issue already opened here https://github.com/firebase/firebase-js-sdk/issues/2284, and I suspect that's the reason why flutter also breaks.

Anyway, the documentation [here](https://firebase.flutter.dev/docs/overview) should say that Flutter Web should still use Manual Configuration and only after they fix the issue https://github.com/firebase/firebase-js-sdk/issues/2284 flutter google sign for web will be usable.

**Comment by rsegecin** [comment]
Thank you @darshankawar
