### ISSUE TITLE
🐛 [firebase_core] No implementation found for method Firebase#initializeCore when embed to a native iOS app

### ISSUE THREAD

**Issue by SamTienz** [FirebaseExtended/flutterfire#8053]
## Bug report

First, I have a native iOS and Android project.
In native, users login my app with their phone.
I'm using pod Firebase/Auth to finish my app login step.

Now, 
I follow this [Add-to-app](https://docs.flutter.dev/development/add-to-app) to develop some views and features with flutter, and embed to my native app. 

But, when I was trying to replace my old login steps and views with FlutterFire's flutter_core, something wrong.

I'm sure I followed the [step](https://firebase.flutter.dev/docs/overview#initializing-flutterfire) to Initializing my FlutterFire

And I found this issue [#4455](https://github.com/FirebaseExtended/flutterfire/issues/4455), had tried all suggestions in the comments.

but nothing help.

My `main.dart`
``` dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(HomeApp());
}
```

My `HomeApp.dart`
``` dart
class HomeApp extends StatelessWidget {
  const HomeApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    print("Firebase.app() = ${Firebase.app()}");
    return MaterialApp(
      navigatorKey: AppConfig.materialKey,
      title: "Home",
      home: Scaffold(
        appBar: AppBar(
          title: Text("HomePage"),
        ),
        body: Container(),
      ),
    );
  }
}
```

When I was build my app with Xcode, and somewhere init the FlutterViewController without entrypoint, 
the expected behavior will print the `flutter: Firebase.app() = FirebaseApp([DEFAULT])`.

but it just show a blank screen, and log something like below.
### Error log in Xcode

<details><summary>Click To Expand</summary>

```
Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:363:35)
<asynchronous suspension>
#2      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:31:23)
<asynchronous suspension>
#3      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#4      Firebase.initializeApp (package:firebase_core/src/firebase.dart:42:31)
<asynchronous suspension>
#5      main (package:traingeflutter/main.dart:17:3)
<asynchronous suspension>
```

</details>

But if I press the **RUN** Button in AndroidStudio directly, my HomeApp is woking fine.
and print the line `flutter: Firebase.app() = FirebaseApp([DEFAULT])` As expected

### Flutter doctor

My `flutter doctor -v`

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.1 21C52 darwin-x64, locale zh-Hant-TW)
    • Flutter version 2.10.0 at /Users/tien/Library/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5f105a6ca7 (8 days ago), 2022-02-01 14:15:42 -0800
    • Engine revision 776efd2034
    • Dart version 2.16.0
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/tien/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode13_2.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (3 available)
    • Sam Tien 12 Pro (mobile) • 00008101-0011603A3451003A            • ios            • iOS 15.2.1 19C63
    • iPhone 12 Pro (mobile)   • 37218A77-7F02-4A4C-B9B8-7FFAD2080B15 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)             • chrome                               • web-javascript • Google Chrome 98.0.4758.80
    ! Error: Sam Tien 12 Pro is busy: Preparing the watch for development via Sam Tien 12 Pro. Xcode will continue when Sam Tien 12 Pro is finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.0
Flutter SDK 2.10.0
traingeflutter 1.0.0+1

dependencies:
- badges 2.0.2 [flutter]
- charts_flutter 0.12.0 [charts_common collection flutter intl logging meta]
- cupertino_icons 1.0.4
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_login 3.1.0 [flutter font_awesome_flutter provider another_transformer_page_view another_flushbar flutter_signin_button quiver url_launcher]
- http 0.13.4 [async http_parser meta path]
- intl 0.17.0 [clock path]
- keyboard_actions 3.4.6 [flutter]
- provider 6.0.2 [collection flutter nested]
- qr_flutter 4.0.0 [flutter qr]
- url_launcher 6.0.18 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 2.8.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- another_flushbar 1.10.28 [flutter]
- another_transformer_page_view 1.1.0 [flutter]
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- charts_common 0.12.0 [collection intl logging meta vector_math]
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- font_awesome_flutter 9.2.0 [flutter]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- nested 1.0.0 [flutter]
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- qr 2.1.0 [meta]
- quiver 3.0.1+1 [matcher]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_android 6.0.14 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.14 [flutter url_launcher_platform_interface]
- url_launcher_linux 2.0.3 [flutter]
- url_launcher_macos 2.0.3 [flutter]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.7 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- vector_math 2.1.1
- webview_flutter_android 2.8.2 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.8.1 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.7.1 [flutter webview_flutter_platform_interface]
```

</details>

---

**Comment by darshankawar** [comment]
> when I was trying to replace my old login steps and views with FlutterFire's flutter_core, something wrong.

Can you elaborate on this ? Maybe while doing so, you might have missed some steps or config. 
But as you said, running from Android Studio, you seem to be getting expected result, but not while doing so from Xcode, that means, something is amiss related to the config. 

`MissingPluginException(No implementation found for method Firebase#initializeCore` indicates that it is not able to register the method `initializeCore` because it couldn't find it's implementation natively.

Check if any of the third party plugins you are using might be having conflict with your setup.

**Comment by SamTienz** [comment]
> Can you elaborate on this ?
    At flutter side, I just have the `main.dart` and the `HomeApp.dart` and try to initialize the firebase_core
    It won't be wrong ,I guess.

    And users login to my native iOS app through Firebase/Auth everything is fine.

In my iOS native project,
It's my `Podfile`
```
pod 'Firebase/Auth'
pod 'Firebase/Crashlytics'
pod 'Firebase/Analytics'
pod 'Firebase/DynamicLinks'
```
as you can see
I also pod 4 Firebase third party package
Both the flutter and iOS have `Firebase`
Is the conflict come from it?

**Comment by SamTienz** [comment]
Today, I try to create a new iOS and Flutter project, and follow the Flutter official document [Add-to-app](https://docs.flutter.dev/development/add-to-app/ios/project-setup) as same.
Then I upload both my iOS and Flutter project to my github.
- [iOS](https://github.com/SamTienz/TestFlutterFlire)
- [Flutter](https://github.com/SamTienz/firetest)

Please clone 
- cd to Flutter directory run `flutter pub get`
- cd to iOS directory run `pod install`
- Press run in Xcode
- Press the **_TestFlutterFire_** button at the center of simulator screen.
- Check the console in Xcode

May be you can see the error log and the bug is reproduced.

**Comment by SamTienz** [comment]
Thank you for your help, this issue is stock me for 3 days😭.
and sorry about my bad english😅.

**Comment by SamTienz** [comment]
Thank for reply.
I put them both to the same repo.
Link is [here](https://github.com/SamTienz/TestFlutterFire).

**Comment by darshankawar** [comment]
Thanks for the update. I cloned it and tried to run using xcode, but I think since my Xcode is on lesser version, I am getting `file can't be opened` error after running `open TestFlutterFire.xcworkspace`, so I am unable to verify this behavior.

But looking at the errorlog you provided earlier:
```

Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
<asynchronous suspension>
#1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:363:35)
<asynchronous suspension>
#2      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:31:23)
<asynchronous suspension>
#3      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
<asynchronous suspension>
#4      Firebase.initializeApp (package:firebase_core/src/firebase.dart:42:31)
<asynchronous suspension>
#5      main (package:traingeflutter/main.dart:17:3)
<asynchronous suspension>
```

You seem to be hitting same issue as https://github.com/FirebaseExtended/flutterfire/issues/4455 because the root-cause could be the same. So I suggest you to follow-up in the original issue and for further updates.
I am going ahead and closing this as a duplicate. If you disagree, write in comments and I'll reopen it.
