### ISSUE TITLE
🐛 [flutterfire] "firebase_auth/invalid-email" exception is thrown with right formatted string

### ISSUE THREAD

**Issue by mikexkllr** [FirebaseExtended/flutterfire#8132]
## firebase_auth/invalid-email" exception is thrown with right formatted string

**e-Mail validation triggers an exception**
The string used is perfectly formatted. I used regex validation and printed a char array of the characters to the console to make sure it didn't contain any incorrect characters. I even checked the length of the string and compared it to the input value and converted the string to a UTF-16 code array to make sure it didn't contain any unwanted characters. My SignIn Method and the call of it are below:

```
Future<void> signInWithEmailAndPassword(
    String email,
    String password,
    void Function(FirebaseAuthException e) errorCallback,
  ) async {
    try {
      await FirebaseAuth.instance.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
    } on FirebaseAuthException catch (e) {
      errorCallback(e);
    }
  }
```

**Method Call:**

```
applicationState!.signInWithEmailAndPassword(
                          pwd,
                          mail,
                          (e) => {
                                print(e),
                              });
                    }),
```

I tried it in Local Emulator and on production firebase env. I use an arm64 Mac. Thx for help! Mike

**Comment by darshankawar** [comment]
@mikexkllr 
Can you provide `flutter doctor -v`, `pubspec.yaml` and the complete exception log ?

**Comment by mikexkllr** [comment]
**An exception "T" occurs on the**
`FirebaseAuth.instance.signInWithEmailAndPassword(email: email, password: password)` method

**also following exception occurs:**

Exception has occurred.
```
"Error: Error: The email address is badly formatted.
    

    at Object.createErrorWithStack (http://localhost:49541/dart_sdk.js:5080:12)
    at http://localhost:49541/dart_sdk.js:40576:44
    at _RootZone.runBinary (http://localhost:49541/dart_sdk.js:40445:59)
    at _FutureListener.thenAwait.handleError (http://localhost:49541/dart_sdk.js:35374:33)
    at handleError (http://localhost:49541/dart_sdk.js:35947:51)
    at Function._propagateToListeners (http://localhost:49541/dart_sdk.js:35973:17)
    at _Future.new.[_completeError] (http://localhost:49541/dart_sdk.js:35823:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49541/dart_sdk.js:35859:31)
    at Object._microtaskLoop (http://localhost:49541/dart_sdk.js:40708:13)
    at _startMicrotaskLoop (http://localhost:49541/dart_sdk.js:40714:13)
    at http://localhost:49541/dart_sdk.js:36191:9"


```
**This is my flutter doctor -v output:**

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-arm, locale
    en-DE)
    • Flutter version 2.10.2 at /opt/homebrew/Caskroom/flutter/2.8.1/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/devmikekeller/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.64.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

THX!
