### ISSUE TITLE
🐛firebase_core: ^1.12.0 on web  Cannot read properties of undefined (reading 'app')

### ISSUE THREAD

**Issue by Tzanou123** [FirebaseExtended/flutterfire#8174]
## Bug report

**Describe the bug**
doesnt work on web platform !
I had with flutterfire configure my app then add firebase_core to pubspec.yaml
and finally 
```
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}
```

But no luck i getting this error
`TypeError: Cannot read properties of undefined (reading 'app')`
### Steps to reproduce

1. create new flutter app
2. add with flutterfire your firebase app
3. Insert firebase_core to pubspec.yaml
4. init firebase before runApp
5. run project
4. See error or incorrect behavior

### Expected behavior

App not crash and let using firebase_core as expected.

## Additional context

Any google search speak about adding some script tag in /web/index.html i trying that but no luck and i bit confused since i was thinking with flutterfire we can skip that step.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [version 10.0.19043.1526], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.64.2)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.1
Flutter SDK 2.10.2
iptv_max 1.0.0+1

dependencies:
- cloud_firestore 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.4
- file_picker 4.4.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path]
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 8.1.3 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_vlc_player 7.0.1 [flutter meta flutter_vlc_player_platform_interface]
- http 0.13.4 [async http_parser meta path]
- video_player 2.2.18 [flutter video_player_android video_player_avfoundation video_player_platform_interface video_player_web html]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.7 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- csslib 0.17.1 [source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.1.2 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.1.2 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_vlc_player_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1
- video_player_android 2.3.0 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.0 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.0 [flutter plugin_platform_interface]
- video_player_web 2.0.7 [flutter flutter_web_plugins video_player_platform_interface]
```

</details>

---

### Console error log

<details><summary>Click To Expand</summary>

```
Launching lib\main.dart on Chrome in debug mode...
lib\main.dart:1
This app is linked to the debug service: ws://127.0.0.1:49423/pCE6T5-rs-k%3D/ws
Debug service listening on ws://127.0.0.1:49423/pCE6T5-rs-k=/ws
 Running with sound null safety
Connecting to VM Service at ws://127.0.0.1:49423/pCE6T5-rs-k=/ws
TypeError: Cannot read properties of undefined (reading 'app')
at Object.app$ [as app] (http://localhost:49351/packages/firebase_core_web/src/interop/core.dart.lib.js:31:101)
at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:49351/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:791:64)
at Function.registerWith (http://localhost:49351/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:717:73)
at Object.registerPlugins (http://localhost:49351/packages/iptv_max/generated_plugin_registrant.dart.lib.js:17:46)
at main (http://localhost:49351/web_entrypoint.dart.lib.js:32:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:49351/dart_sdk.js:40590:34)

```

</details>

---

**Comment by darshankawar** [comment]
@Tzanou123 
Thanks for the report. I tried steps to replicate you mentioned, but was unable to replicate the error.

1. flutter create ff_issue_test
2. cd ff_issue_test
3. flutterfire configure
4. flutter pub add firebase_core
5. flutter run -d chrome

Following above steps, it compiled and built the app on chrome properly without any issues:

```
dhs@Dhss-MacBook-Pro ff_test_issue % flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             16.6s
This app is linked to the debug service: ws://127.0.0.1:52686/2cW8vhqA7QY=/ws
Debug service listening on ws://127.0.0.1:52686/2cW8vhqA7QY=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at:
http://127.0.0.1:52686/2cW8vhqA7QY=
The Flutter DevTools debugger and profiler on Chrome is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:52686/2cW8vhqA7QY=
```

```
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}
```

`Channel stable, 2.10.2`

Let me know if these are the correct steps to replicate the issue or did I miss anything.
