### ISSUE TITLE
🐛 [firebase_messaging] onBackgroundMessage: Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by brunodmn** [FirebaseExtended/flutterfire#8215]
## Bug report

**Describe the bug**
 FirebaseMessaging.onBackgroundMessage not working on Android and throwing error `Unhandled Exception: Null check operator used on a null value`

### Steps to reproduce

1. Create a new flutter project
2. add firebase_core and firebase_messaging to pubspec.yaml
3. run flutterfire cli to setup a new/existing firebase project (or do it manually)
4. initialize firebase on your flutter project
5. See error or incorrect behavior

### Expected behavior

Expected the onBackgroundMessage callback to run (i.e. show a [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) notification)

### Sample project

This is a newly created project to demonstrate: [link](https://github.com/brunodmn/flutter_application_2)

---

## Additional context

I also tried with firebase manual installation with same results. 
Messaging gets token and run onMessageOpenedApp and onMessage listeners with no problems, this issue seems to happen only using onBackgroundMessage.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.1, on Linux Mint 20.3 5.4.0-100-generic,
    locale en_US.UTF-8)
    • Flutter version 2.10.1 at /home/bruno/_development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/bruno/Android/Sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /snap/android-studio/current/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio
    • Android Studio at /snap/android-studio/current/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • android-studio-dir = /snap/android-studio/current/android-studio
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.64.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • M2003J15SC (mobile) • 0fe657a70502 • android-arm64  • Android 11 (API 30)
    • Linux (desktop)     • linux        • linux-x64      • Linux Mint 20.3
      5.4.0-100-generic
    • Chrome (web)        • chrome       • web-javascript • Google Chrome
      99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.1
Flutter SDK 2.10.1
ispjet_mobile 1.0.0+11

dependencies:
- adaptive_theme 2.3.0 [flutter shared_preferences]
- auto_size_text 3.0.0 [flutter]
- carousel_slider 4.0.0 [flutter]
- clipboard 0.1.3 [flutter]
- cloud_firestore 3.1.10 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.4
- dartz 0.10.1
- dio 4.0.4 [http_parser path]
- equatable 2.0.3 [collection meta]
- firebase_analytics 9.1.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.5.3 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 11.2.8 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_form_builder 7.1.1 [flutter intl collection]
- flutter_hooks 0.18.2+1 [flutter]
- flutter_local_notifications 9.3.3 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- form_builder_validators 7.6.1 [flutter flutter_localizations intl collection]
- geocoding 2.0.2 [flutter geocoding_platform_interface]
- geolocator 8.2.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web geolocator_windows]
- get 4.6.1 [flutter]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- in_app_review 2.0.4 [flutter in_app_review_platform_interface]
- internet_connection_checker 0.0.1+3
- liquid_progress_indicator 0.4.0 [flutter]
- mailer 5.1.0 [async logging intl mime path pedantic meta]
- open_file 3.2.1 [flutter ffi]
- package_info_plus 1.4.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- rxdart 0.27.3
- teledart 0.3.2 [json_annotation http]
- upgrader 3.13.0 [flutter device_info_plus http os_detect package_info_plus shared_preferences url_launcher version xml html]
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- webview_flutter 3.0.1 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- workmanager 0.4.1 [flutter]

dev dependencies:
- change_app_package_name 1.0.0
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_native_splash 2.0.5 [args image js meta path xml yaml universal_io flutter flutter_web_plugins]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.2.1 [crypto path]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.10 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.1 [source_span]
- dbus 0.7.1 [args ffi meta xml]
- device_info_plus 3.2.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.2 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.3.0+1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+8 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.2.5 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.9 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_linux 0.4.2 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geolocator_android 3.1.0 [flutter geolocator_platform_interface]
- geolocator_apple 2.1.1+1 [flutter geolocator_platform_interface]
- geolocator_platform_interface 4.0.3 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.1.4 [flutter flutter_web_plugins geolocator_platform_interface]
- geolocator_windows 0.1.0 [flutter geolocator_platform_interface]
- hive 2.0.6 [meta crypto]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.3 [archive meta xml]
- in_app_review_platform_interface 2.0.3 [flutter url_launcher plugin_platform_interface platform]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.4.0 [meta]
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- os_detect 2.0.0
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- process 4.2.4 [file path platform]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.8.0 [path]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_android 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.9 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.0 [flutter url_launcher_platform_interface]
- vector_math 2.1.1
- version 2.0.0
- webview_flutter_android 2.8.3 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.8.1 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.7.1 [flutter webview_flutter_platform_interface]
- win32 2.4.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
Thanks for the report. Cloned your demo and ran it on Android device. Although the app compiles, messaging token is generated, but console shows below error:
```

Installing build\app\outputs\flutter-apk\app.apk...                 5.6s
E/flutter (25930): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
E/flutter (25930): #0      MethodChannelFirebaseMessaging.registerBackgroundMessageHandler (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:180:53)
E/flutter (25930): #1      FirebaseMessagingPlatform.onBackgroundMessage= (package:firebase_messaging_platform_interface/src/platform_interface/platform_interface_messaging.dart:102:16)
E/flutter (25930): #2      FirebaseMessaging.onBackgroundMessage (package:firebase_messaging/src/messaging.dart:73:31)
E/flutter (25930): #3      main (package:flutter_application_2/main.dart:16:21)
E/flutter (25930): <asynchronous suspension>
E/flutter (25930):
I/flutter (25930): Messaging Token is cJ6jBAXkTBad8ODFPtgsn_:APA91bECZ3kq5dAqto7v3Ne5M4ypBoaVqdnGaiNwk8Ry0yG8NahqintCja7ArGwUndFebXA2nRuR_uAlqZkQMOEtIbJdOGGSWJkSDm9zpMhabxCRTEnJzNUUBk7PKjBwQUiY1ghf7f6t
Syncing files to device SM G975F...                                186ms
```

**Comment by brunodmn** [comment]
I came across  [this workaraound](https://github.com/fluttercommunity/flutter_workmanager/issues/366#issuecomment-1059826853) under flutter_workamanager issues page:

> Add in your pubspec.yaml:
> 
> path_provider_android: ^2.0.12
> path_provider_ios: ^2.0.8
> 
> Add in your workmanager callback:
> 
> if (Platform.isAndroid) PathProviderAndroid.registerWith();
> if (Platform.isIOS) PathProviderIOS.registerWith();

**Comment by itssidhere** [comment]
Any workaround for this?

**Comment by russellwheatley** [comment]
Hey @brunodmn, you need to initialize Firebase for the background message handler. [See example](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/lib/main.dart#L28). Let me know if this helps. Thanks.

**Comment by brunodmn** [comment]
Thanks for reply @russellwheatley, I think I already did that (on another project)..but I'll double check and let you know asap

**Comment by russellwheatley** [comment]
I see the problem now. You need to make it a top level function (i.e. remove the anonymous function and place `_firebaseMessagingBackgroundHandler` function as an argument to `onBackgroundMessage`):

```dart
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print("Handling a background message: ${message.messageId}");
}

void main() {
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  runApp(MyApp());
}
```

**Comment by brunodmn** [comment]
> I see the problem now. You need to make it a top level function (i.e. remove the anonymous function and place `_firebaseMessagingBackgroundHandler` function as an argument to `onBackgroundMessage`):
> 
> ```dart
> Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
>   print("Handling a background message: ${message.messageId}");
> }
> 
> void main() {
>   FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
>   runApp(MyApp());
> }
> ```

You are right, this way it won't throw any errors. Thank you.
