### ISSUE TITLE
🐛 [cloud_firestore] java.lang.RuntimeException: Internal error in Cloud Firestore (24.0.2).

### ISSUE THREAD

**Issue by mk-dev-1** [FirebaseExtended/flutterfire#8265]
## Bug report

This is a follow-up on the original issue reported here https://github.com/FirebaseExtended/flutterfire/issues/7988. It appears that the stacktrace I posted there belongs to a different error.

I have added the stacktrace below - apologies that it is slightly malformated.

### Stacktrace

<details><summary>Click To Expand</summary>

```
FATAL EXCEPTION: main

java.lang.RuntimeException: Internal error in Cloud Firestore (24.0.2).
       at com.google.firebase.firestore.util.-$$Lambda$AsyncQueue$jx84dqgUsF4ojecSMurRqFLFD1Y.void com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(java.lang.Throwable)(:1)
                                                                                              void run()
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7842)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: e.e.b.c.i.j: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
       at com.google.android.gms.tasks.zzw.java.lang.Object getResult()(:3)
       at com.google.firebase.firestore.remote.FirestoreChannel.void lambda$runBidiStreamingRpc$0(io.grpc.ClientCall[],com.google.firebase.firestore.remote.IncomingStreamObserver,com.google.android.gms.tasks.Task)(:1)
                                                                void lambda$runBidiStreamingRpc$0$FirestoreChannel(io.grpc.ClientCall[],com.google.firebase.firestore.remote.IncomingStreamObserver,com.google.android.gms.tasks.Task)
       at com.google.firebase.firestore.remote.-$$Lambda$FirestoreChannel$ThFui-hvcsrVGYxlBtcTH5vVbvE.void onComplete(com.google.android.gms.tasks.Task)(Unknown Source:6)
       at com.google.android.gms.tasks.zzi.run(Unknown Source:21)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(Unknown Source:15)
       at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.RuntimeException: java.lang.ExceptionInInitializerError
       at com.google.android.gms.tasks.zzz.run(Unknown Source:17)
       at com.google.firebase.firestore.util.ThrottledForwardingExecutor.void lambda$execute$0(java.lang.Runnable)(:1)
                                                                         void lambda$execute$0$ThrottledForwardingExecutor(java.lang.Runnable)
       at com.google.firebase.firestore.util.-$$Lambda$ThrottledForwardingExecutor$MfIJbVuxZtLwosAgPzPA-cU66Ko.run(Unknown Source:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       ... 1 more
Caused by: java.lang.ExceptionInInitializerError
       at io.grpc.okhttp.OkHttpChannelBuilder.forTarget(Unknown Source:0)
       at io.grpc.okhttp.OkHttpChannelProvider.io.grpc.okhttp.OkHttpChannelBuilder builderForTarget(java.lang.String)(:1)
                                               io.grpc.ManagedChannelBuilder builderForTarget(java.lang.String)
       at io.grpc.ManagedChannelBuilder.io.grpc.ManagedChannelBuilder forTarget(java.lang.String)(:2)
       at com.google.firebase.firestore.remote.GrpcCallProvider.io.grpc.ManagedChannel initChannel(android.content.Context,com.google.firebase.firestore.core.DatabaseInfo)(:2)
                                                                io.grpc.ManagedChannel lambda$initChannelTask$6()
                                                                io.grpc.ManagedChannel lambda$initChannelTask$6$GrpcCallProvider()
       at com.google.firebase.firestore.remote.-$$Lambda$GrpcCallProvider$SCD5iiibQ8l4haiO8ofSfE0wIJg.call(Unknown Source:2)
       at com.google.android.gms.tasks.zzz.run(Unknown Source:4)
       ... 5 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: h.b.k0.values []
       at java.lang.Enum.enumValues(Enum.java:270)
       at java.lang.Enum.access$000(Enum.java:61)
       at java.lang.Enum$1.create(Enum.java:277)
       at java.lang.Enum$1.create(Enum.java:275)
       at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
       at java.lang.Enum.getSharedConstants(Enum.java:289)
       at java.lang.Class.getEnumConstantsShared(Class.java:2459)
       at java.util.EnumSet.getUniverse(EnumSet.java:407)
       at java.util.EnumSet.noneOf(EnumSet.java:109)
       at java.util.EnumSet.of(EnumSet.java:235)
       at io.grpc.okhttp.OkHttpChannelBuilder.<clinit>(Unknown Source:89)
       ... 11 more
Caused by: java.lang.NoSuchMethodException: h.b.k0.values []
       at java.lang.Class.getMethod(Class.java:2103)
       at java.lang.Class.getDeclaredMethod(Class.java:2081)
       at java.lang.Enum.enumValues(Enum.java:267)
       ... 21 more
FATAL EXCEPTION: AsyncTask #1

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@302d989 rejected from com.google.firebase.firestore.e0.s$c$a@f748d8e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2086)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:848)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
       at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
       at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:654)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.execute(Unknown Source:7)
       at com.google.android.gms.tasks.zzf.void zzd(com.google.android.gms.tasks.Task)(Unknown Source:7)
       at com.google.android.gms.tasks.zzr.void zzb(com.google.android.gms.tasks.Task)(Unknown Source:35)
       at com.google.android.gms.tasks.zzw.void zza(java.lang.Exception)(:2)
       at com.google.android.gms.tasks.zzz.run(Unknown Source:20)
       at com.google.firebase.firestore.util.ThrottledForwardingExecutor.void lambda$execute$0(java.lang.Runnable)(:1)
                                                                         void lambda$execute$0$ThrottledForwardingExecutor(java.lang.Runnable)
       at com.google.firebase.firestore.util.-$$Lambda$ThrottledForwardingExecutor$MfIJbVuxZtLwosAgPzPA-cU66Ko.run(Unknown Source:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```

</details>

### Steps to reproduce

Simply build the app using `flutter run --release`.

### Expected behavior

This error should not appear and the app should not crash.

### Sample project

Unfortunately, I cannot provide a sample project to reproduce the error at this stage. I have set up a blank project, included firestore and a release configuration and I cannot reproduce the error.

---

## Additional context

This crash appears only when building in release mode, debug is not affected.

Adding the below two lines in the app level build.gradle "resolves" the issue, but it is not solving the underlying issue
```
            shrinkResources false
            minifyEnabled false
```

For the stacktrace below I have overwritten the Android sdk of cloud firestore like this:

```
    implementation 'com.google.firebase:firebase-firestore:24.0.2'
```

This issue started out as `Internal error in Cloud Firestore (24.0.1)`

None of the following actions have resolved the issue
- Clearing pub cache
- Downgrading flutter to previous version
- Downgrading to older plugin versions
- Downgrading gradle version
- Downgrading target sdk version

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.10.2, on macOS 12.2.1 21D62 darwin-arm, locale de-DE)
    • Flutter version 2.10.2 at /Users/mk-dev-1/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (3 weeks ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mk-dev-1/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.65.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12 (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 99.0.4844.51

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.1
Flutter SDK 2.10.2

dependencies:
- amplitude_flutter 3.8.1 [flutter flutter_web_plugins js]
- cloud_firestore 3.1.10 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.2.9 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.15.0
- connectivity_plus 2.2.1 [flutter connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- csv 5.0.1
- cupertino_icons 1.0.4
- device_info_plus 3.2.2 [flutter device_info_plus_platform_interface device_info_plus_macos device_info_plus_linux device_info_plus_web device_info_plus_windows]
- expandable 5.0.1 [flutter]
- file_picker 4.4.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path]
- firebase_analytics 9.1.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.9 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_crashlytics 2.5.3 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 4.0.8 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_remote_config 2.0.2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface firebase_remote_config_web flutter]
- firebase_storage 10.2.9 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_calendar_carousel 2.1.0 [intl flutter]
- flutter_html 2.2.1 [html csslib flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter_math_fork collection numerus flutter]
- flutter_local_notifications 10.0.0-dev.8 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection material_color_utilities meta path typed_data vector_math]
- flutter_markdown 0.6.9 [flutter markdown meta path]
- flutter_native_timezone 2.0.0 [flutter_web_plugins flutter js]
- flutter_reactive_ble 5.0.2 [collection flutter functional_data meta reactive_ble_mobile reactive_ble_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- get_it 7.2.0 [async collection]
- google_mobile_ads 1.1.0 [meta flutter]
- google_sign_in 5.2.4 [flutter google_sign_in_platform_interface google_sign_in_web]
- http 0.13.4 [async http_parser meta path]
- in_app_purchase 3.0.0 [flutter in_app_purchase_platform_interface in_app_purchase_android in_app_purchase_storekit]
- in_app_review 2.0.4 [flutter in_app_review_platform_interface]
- intl 0.17.0 [clock path]
- intl_generator 0.2.1 [collection analyzer args dart_style intl path petitparser]
- json_annotation 4.4.0 [meta]
- onesignal_flutter 3.2.8 [flutter]
- package_info_plus 1.4.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- path_provider 2.0.9 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 9.2.0 [flutter meta permission_handler_android permission_handler_apple permission_handler_windows permission_handler_platform_interface]
- purchases_flutter 3.3.1 [flutter collection]
- quick_actions 0.6.0+9 [flutter quick_actions_platform_interface]
- rx_command 6.0.1 [rxdart quiver]
- share 2.0.4 [meta mime flutter]
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- syncfusion_flutter_charts 19.4.53 [flutter intl vector_math syncfusion_flutter_core]
- timezone 0.8.0 [path]
- url_launcher 6.0.20 [flutter url_launcher_android url_launcher_ios url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- wakelock 0.6.1+1 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]

dev dependencies:
- build_runner 2.1.7 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 1.0.4 [lints]
- json_serializable 6.1.4 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]

transitive dependencies:
- _fe_analyzer_shared 31.0.0 [meta]
- analyzer 2.8.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.0
- async 2.8.2 [collection meta]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- chewie 1.3.0 [cupertino_icons flutter provider video_player wakelock very_good_analysis]
- chewie_audio 1.3.0 [cupertino_icons flutter video_player]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.5.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.10 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.1.1 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.2.9 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- connectivity_plus_linux 1.3.0 [flutter connectivity_plus_platform_interface meta nm]
- connectivity_plus_macos 1.2.1 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.2.0 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.2.0 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.0 [connectivity_plus_platform_interface flutter]
- convert 3.0.1 [typed_data]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.1 [source_span]
- dart_style 2.2.1 [analyzer args path pub_semver source_span]
- dbus 0.7.1 [args ffi meta xml]
- device_info_plus_linux 2.1.1 [device_info_plus_platform_interface file flutter meta]
- device_info_plus_macos 2.2.2 [device_info_plus_platform_interface flutter]
- device_info_plus_platform_interface 2.3.0+1 [flutter meta plugin_platform_interface]
- device_info_plus_web 2.1.0 [device_info_plus_platform_interface flutter_web_plugins flutter]
- device_info_plus_windows 2.1.1 [device_info_plus_platform_interface ffi flutter win32]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+8 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.9 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.13.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.2.5 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.6.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.2.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.1+1 [firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_platform_interface 1.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_remote_config_web 1.0.7 [firebase_core firebase_core_web firebase_remote_config_platform_interface flutter flutter_web_plugins js]
- firebase_storage_platform_interface 4.1.1 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.10 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- flutter_layout_grid 1.0.3 [flutter collection meta quiver]
- flutter_local_notifications_linux 0.5.0-dev.3 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 6.0.0-dev.2 [flutter plugin_platform_interface]
- flutter_math_fork 0.5.0 [flutter flutter_svg provider meta collection tuple]
- flutter_plugin_android_lifecycle 2.0.5 [flutter]
- flutter_svg 0.23.0+1 [flutter meta path_drawing vector_math xml]
- frontend_server_client 2.1.2 [async path]
- functional_data 1.0.0 [meta collection]
- glob 2.0.2 [async collection file path string_scanner]
- google_sign_in_platform_interface 2.1.2 [flutter quiver]
- google_sign_in_web 0.10.0+5 [flutter flutter_web_plugins google_sign_in_platform_interface js]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http_multi_server 3.2.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- in_app_purchase_android 0.2.2+1 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_purchase_platform_interface 1.3.1 [flutter plugin_platform_interface]
- in_app_purchase_storekit 0.3.0+1 [collection flutter in_app_purchase_platform_interface json_annotation]
- in_app_review_platform_interface 2.0.3 [flutter url_launcher plugin_platform_interface platform]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- lints 1.0.1
- logging 1.0.2
- markdown 4.0.1 [args charcode meta]
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- nested 1.0.0 [flutter]
- nm 0.5.0 [dbus]
- numerus 1.1.1
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_android 2.0.12 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.8 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- permission_handler_android 9.0.2 [flutter permission_handler_platform_interface]
- permission_handler_apple 9.0.2 [flutter permission_handler_platform_interface]
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- permission_handler_windows 0.1.0 [flutter permission_handler_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- protobuf 2.0.1 [fixnum collection]
- provider 6.0.2 [collection flutter nested]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- quick_actions_platform_interface 1.0.2 [flutter plugin_platform_interface]
- quiver 3.0.1+1 [matcher]
- reactive_ble_mobile 5.0.2 [flutter protobuf reactive_ble_platform_interface]
- reactive_ble_platform_interface 5.0.2 [collection flutter functional_data meta plugin_platform_interface]
- rxdart 0.27.3
- shared_preferences_android 2.0.11 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.1.0 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.1.0 [file flutter path path_provider_linux path_provider_platform_interface shared_preferences_platform_interface]
- shared_preferences_macos 2.0.3 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.1.0 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- sky_engine 0.0.99
- source_gen 1.2.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.1 [analyzer collection source_gen]
- source_span 1.8.2 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- syncfusion_flutter_core 19.4.53 [vector_math flutter]
- term_glyph 1.2.0
- timing 1.0.0 [json_annotation]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- url_launcher_android 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_ios 6.0.15 [flutter url_launcher_platform_interface]
- url_launcher_linux 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_macos 3.0.0 [flutter url_launcher_platform_interface]
- url_launcher_platform_interface 2.0.5 [flutter plugin_platform_interface]
- url_launcher_web 2.0.9 [flutter flutter_web_plugins url_launcher_platform_interface]
- url_launcher_windows 3.0.0 [flutter url_launcher_platform_interface]
- vector_math 2.1.1
- very_good_analysis 2.4.0
- video_player 2.2.19 [flutter html video_player_android video_player_avfoundation video_player_platform_interface video_player_web]
- video_player_android 2.3.0 [flutter video_player_platform_interface]
- video_player_avfoundation 2.3.0 [flutter video_player_platform_interface]
- video_player_platform_interface 5.1.0 [flutter plugin_platform_interface]
- video_player_web 2.0.7 [flutter flutter_web_plugins video_player_platform_interface]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webview_flutter 2.8.0 [flutter webview_flutter_android webview_flutter_platform_interface webview_flutter_wkwebview]
- webview_flutter_android 2.8.3 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.8.1 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.7.1 [flutter webview_flutter_platform_interface]
- win32 2.4.1 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment]
@mk-dev-1 
Thanks for the report. Looking at the stacktrace, it seems to be pointing to native logs and don't seem to have any entries pointing to `cloud_firestore` plugin which makes it a bit tough to analyze this as what exactly could be causing it.

A minimal reproducible use case or a pattern would really be helpful to debug further.

As a workaround or a potential solution, try [this](https://github.com/FirebaseExtended/flutterfire/issues/7471#issuecomment-988968106) and see if it helps.

**Comment by mk-dev-1** [comment]
@darshankawar Thank you for looking into this. The solution provided in https://github.com/FirebaseExtended/flutterfire/issues/7471 unfortunately does not make a difference. The app keeps crashing right the first moment anything touches `cloud_firestore`....Unfortunately, I still dont have anything that can reproduce the error in a minimally viable app....

**Comment by darshankawar** [comment]
@mk-dev-1 
Thanks for the feedback. Since its happening in release mode per your comment earlier, I am wondering if it might have something to do with the gradle version or any config related to it which may be conflicting with release mode.

See below links and check if they help or give you an idea to dig up further:

https://github.com/FirebaseExtended/flutterfire/issues/1993#issuecomment-589339536
https://github.com/FirebaseExtended/flutterfire/issues/1993#issuecomment-589779480
https://stackoverflow.com/questions/58353313/flutter-app-crashes-when-it-use-firestore-plugin-in-release-mode

**Comment by mk-dev-1** [comment]
@darshankawar
Your links did not solve the issue, but somehow the proposed solutions prompted me to pick a random commit from my app's history that was two months old. Funny enough that allowed me to boil down the issue to a single line of code:

Replacing classpath `com.android.tools.build:gradle:4.2.2` with classpath `com.android.tools.build:gradle:4.1.0` seems to have done the trick....I did try downgrading before, just not to this specific version. Strange how simple things like that can sometimes send you on a painfully long debugging journey...

Thanks for your support - ready to close!
