### ISSUE TITLE
🐛 [firebase_messaging] Crashes on Samsung devices with Android 12 claiming that WAKE_LOCK is required

### ISSUE THREAD

**Issue by vbuberen** [FirebaseExtended/flutterfire#8295]
## Bug report

Recently started to see in Firebase Crashlytics's some crashes among users with Samsung devices on Android 12 who experience crashes due to `firebase_messaging`. I suspect that this is something connected with Samsung's customisation of Android 12. 

Issues started to appear in Crashlytics since beginning of March.

Full logs from Crashlytics:

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver: java.lang.SecurityException: Neither user 10025 nor current process has android.permission.WAKE_LOCK.
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4766)
       at android.app.ActivityThread.access$1800(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
```
Caused by java.lang.SecurityException: Neither user 10025 nor current process has android.permission.WAKE_LOCK.
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
       at android.os.Parcel.createException(Parcel.java:2421)
       at android.os.Parcel.readException(Parcel.java:2404)
       at android.os.Parcel.readException(Parcel.java:2346)
       at android.os.IPowerManager$Stub$Proxy.acquireWakeLock(IPowerManager.java:1365)
       at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:3575)
       at android.os.PowerManager$WakeLock.acquire(PowerManager.java:3557)
       at io.flutter.plugins.firebase.messaging.JobIntentService$CompatWorkEnqueuer.enqueueWork(JobIntentService.java:129)
       at io.flutter.plugins.firebase.messaging.JobIntentService.enqueueWork(JobIntentService.java:476)
       at io.flutter.plugins.firebase.messaging.JobIntentService.enqueueWork(JobIntentService.java:445)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingBackgroundService.enqueueMessageProcessing(FlutterFirebaseMessagingBackgroundService.java:34)
       at io.flutter.plugins.firebase.messaging.FlutterFirebaseMessagingReceiver.onReceive(FlutterFirebaseMessagingReceiver.java:58)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4757)
       at android.app.ActivityThread.access$1800(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```
```
Caused by android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2273)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2301)
	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:8247)
	at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:604)
	at android.os.Binder.execTransactInternal(Binder.java:1215)
```

### Steps to reproduce

Not sure how to properly reproduce as it happens in production for us

### Expected behavior

No crashes expected

### Sample project

As I don't know how to reproduce the issue can't create a sample project.

---

## Additional context

Here are screenshots from the Firebase console with those issues:

<img width="837" alt="Screenshot 2022-03-17 at 18 40 04" src="https://user-images.githubusercontent.com/13467769/158850464-cc9cad2b-3d30-4d97-aeeb-7435f0a68f99.png">
<img width="460" alt="Screenshot 2022-03-17 at 18 40 33" src="https://user-images.githubusercontent.com/13467769/158850487-2836cc67-7cf1-413f-b0ef-f4ecef217c86.png">

---

### Flutter doctor

<details><summary>Click To Expand</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.6.1 20G224 darwin-x64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2021.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

</details>

**Comment by darshankawar** [comment]
@vbuberen 
Thanks for the report. The crashes may not be specific to `firebase_messaging` plugin only, as there's a similar issue open in flutter repo about same crash using different plugins too: https://github.com/flutter/flutter/issues/59063

Do you have `<uses-permission android:name="android.permission.WAKE_LOCK"/>` permission granted already in manifest ?
If no, can you try to add that and see if it makes any difference ?
If you already have it, I suggest you to follow-up in the original flutter issue, as other plugins (non-flutterfire) seem to have reported same error.
Closing from here as this is not specific to firebase_messaging and the plugin can't do much about it. If you disagree, write in comments and I'll reopen it.

**Comment by vbuberen** [comment]
Ok, thanks. Didn't know about this issue. Will provide info that it is seems Samsung specific in that issue.

Strange that it just started to appear, though. But will continue the discussion there.
