### ISSUE TITLE
[google_sign_in] [firebase_auth] PlatformException Error Code: 2

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#864]
I'm simply trying to use google_sign_in plugin to authorize myself on firebase via firebase_auth with function shown under. On the other hand I'm able to create user via email and password in my firebase project just this bloody google sign in is misbehaving. 

## Steps to Reproduce
```dart
Future<String> signInWithGoogle () async {

    try {
      GoogleSignIn googleSignIn = new GoogleSignIn();
      GoogleSignInAccount googleUser = await googleSignIn.signIn();
      GoogleSignInAuthentication googleAuth = await googleUser.authentication;

      FirebaseAuth firebaseAuth = FirebaseAuth.instance;
      print(googleAuth.accessToken);
      print(googleAuth.idToken);

      await firebaseAuth.signInWithGoogle(
        accessToken: googleAuth.accessToken,
        idToken: googleAuth.idToken,
      );

      final FirebaseUser user = firebaseAuth.currentUser;
      print(user.displayName);

      return('signInWithGoogle succeeded ');
    } catch (e) {
      print(e);
    }
```

### Log from Android studio terminal try/catch
```
/flutter (25608): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (25608): type '_AssertionError' is not a subtype of type 'PlatformException' of 'onError' where
E/flutter (25608):   _AssertionError is from dart:core
E/flutter (25608):   PlatformException is from package:flutter/src/services/message_codec.dart
E/flutter (25608): 
E/flutter (25608): #0      LoginScreenState._loginWithGoogle.<anonymous closure> (package:flutter_flat_app/screens/Login/index.dart:65:38)
E/flutter (25608): #1      _RootZone.runUnary (dart:async/zone.dart:1381)
E/flutter (25608): #2      _FutureListener.handleError (dart:async/future_impl.dart:144)
E/flutter (25608): #3      _Future._propagateToListeners.handleError (dart:async/future_impl.dart:645)
E/flutter (25608): #4      _Future._propagateToListeners (dart:async/future_impl.dart:666)
E/flutter (25608): #5      _Future._complete (dart:async/future_impl.dart:467)
E/flutter (25608): #6      _SyncCompleter.complete (dart:async/future_impl.dart:51)
E/flutter (25608): #7      _completeOnAsyncReturn (dart:async-patch/dart:async/async_patch.dart:292)
E/flutter (25608): #8      UserAuth.signInWithGoogle (package:flutter_flat_app/services/authentication.dart:59:3)
E/flutter (25608): #9      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:84)
E/flutter (25608): #10     _RootZone.runBinary (dart:async/zone.dart:1386)
E/flutter (25608): #11     _FutureListener.handleError (dart:async/future_impl.dart:141)
E/flutter (25608): #12     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:645)
E/flutter (25608): #13     _Future._propagateToListeners (dart:async/future_impl.dart:666)
E/flutter (25608): #14     _Future._completeError (dart:async/future_impl.dart:485)
E/flutter (25608): #15     _SyncCompleter._completeError (dart:async/future_impl.dart:55)
E/flutter (25608): #16     _Completer.completeError (dart:async/future_impl.dart:27)
E/flutter (25608): #17     FirebaseAuth.signInWithGoogle (package:firebase_auth/firebase_auth.dart)
E/flutter (25608): #18     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/dart:async/async_patch.dart:84)
E/flutter (25608): #19     _RootZone.runBinary (dart:async/zone.dart:1386)
E/flutter (25608): #20     _FutureListener.handleError (dart:async/future_impl.dart:141)
E/flutter (25608): #21     _Future._propagateToListeners.handleError (dart:async/future_impl.dart:645)
E/flutter (25608): #22     _Future._propagateToListeners (dart:async/future_impl.dart:666)
E/flutter (25608): #23     _Future._completeError (dart:async/future_impl.dart:485)
E/flutter (25608): #24     _SyncCompleter._completeError (dart:async/future_impl.dart:55)
E/flutter (25608): #25     _Completer.completeError (dart:async/future_impl.dart:27)
E/flutter (25608): #26     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
E/flutter (25608): #27     _RootZone.runUnary (dart:async/zone.dart:1381)
E/flutter (25608): #28     _FutureListener.handleValue (dart:async/future_impl.dart:129)
E/flutter (25608): #29     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:633)
E/flutter (25608): #30     _Future._propagateToListeners (dart:async/future_impl.dart:662)
E/flutter (25608): #31     _Future._completeWithValue (dart:async/future_impl.dart:477)
E/flutter (25608): #32     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:507)
E/flutter (25608): #33     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter (25608): #34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

### Print from 'catchError'  method 
```
  void _loginWithGoogle() {
    userAuth.signInWithGoogle().then((onValue) {
      if (onValue == "signInWithGoogle succeeded ")
        Navigator.pushNamed(context, "/HomePage");
      else
        showInSnackBar(onValue);
    }).catchError((PlatformException onError) {
      print(onError.toString());
      showInSnackBar(onError.message);
    });
  }


flutter (26060): PlatformException(exception, An internal error has occurred. [ Error code:2 ], null)
```

### Flutter analyze
```
Analyzing /home/tabuz/projects/flat-app...
  error • Target of URI doesn't exist: 'package:flutter_flat_app/Screens/Login/index.dart' at test/widget_test.dart:8:8 • uri_does_not_exist
  error • The constructor returns type 'dynamic' that isn't of expected type 'Widget' at test/widget_test.dart:15:29 • strong_mode_invalid_cast_new_expr
  error • Undefined class 'LoginScreen' at test/widget_test.dart:15:33 • undefined_class
  warning • This function declares a return type of 'Future<String>', but doesn't end with a return statement at lib/services/authentication.dart:34:3 • missing_return
  hint • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib/components/Buttons/roundedButton.dart:3:7 • must_be_immutable
  hint • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib/components/Buttons/textButton.dart:3:7 • must_be_immutable
  hint • This class inherits from a class marked as @immutable, and therefore should be immutable (all instance fields must be final) at lib/components/TextFields/inputField.dart:3:7 • must_be_immutable
7 issues found.
(Ran in 7.9s)
```

## Flutter Doctor

```
[✓] Flutter (Channel beta, v0.2.3, on Linux, locale pl_PL.UTF-8)
    • Flutter version 0.2.3 at /home/tabuz/software/flutter
    • Framework revision 5a58b36e36 (3 weeks ago), 2018-03-13 13:20:13 -0700
    • Engine revision e61bb9ac3a
    • Dart version 2.0.0-dev.35.flutter-290c576264

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /home/tabuz/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /home/tabuz/software/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_152-release"
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at /home/tabuz/software/android-studio
    • Java version openjdk version "1.8.0_152-release"

[✓] Connected devices (1 available)
    • Pixel • FA69L0304820 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```
### Dependencies

```
  image_picker: 0.1.1                                             # new
  google_sign_in: 0.3.1                                           # new
  firebase_analytics: 0.0.4                                       # new
  firebase_auth: 0.1.1                                            # new
  firebase_database: 0.0.12                                       # new
  firebase_storage: 0.0.5                                         # new
```

**Comment by kroikie** [comment]
@tabuz

The issue at https://github.com/flutter/flutter/issues/16239 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment]
Hi @tabuz
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by tabuz** [comment]
@iapicca Oh my friend... this was issue was addressed in April 2018, like more than a year ago. I don't have this code base anymore. Unfortunately I won't be much help here.
Anyway much appreciate that someone did look into it ;)

**Comment by iapicca** [comment]
Hi @tabuz 
I know, I apologize for the delay.

I'm closing this issue for now,
but if you are encountering any problem
please let me know and I'll open it again.
thank you
