### ISSUE TITLE
Firebase Auth Freezes the App sometimes and Throws this Error

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#887]
```
Reloaded 4 of 503 libraries in 5,577ms.
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at android.util.SparseArray.removeAt(SparseArray.java:168)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleStopListeningAuthState(FirebaseAuthPlugin.java:291)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:95)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:191)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:133)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at android.os.MessageQueue.next(MessageQueue.java:356)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at android.os.Looper.loop(Looper.java:138)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at android.app.ActivityThread.main(ActivityThread.java:6523)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
E/MethodChannel#plugins.flutter.io/firebase_auth(28187): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
I/FirebaseAuth(28187): [FirebaseAuth:] Loading module via FirebaseOptions.
I/FirebaseAuth(28187): [FirebaseAuth:] Preparing to create service connection to gms implementation
I/FlutterActivityDelegate(28187): onResume setting current activity to this
```

**Comment by GameSquatch** [comment]
I have been experiencing this lately and can't figure out why any connection to firebase auth infinitely waits. Here is what is printed during a flutter run.
```
I/BiChannelGoogleApi( 7404): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@449139e
W/DynamiteModule( 7404): Local module descriptor class for com.google.firebase.auth not found.
I/FirebaseAuth( 7404): [FirebaseAuth:] Preparing to create service connection to gms implementation
```
This was a call to create a new user (createUserWithEmailAndPassword), but this happens when I listen to the auth state AND when I attempt to get the currentUser. Here's my flutter doctor result:
```
$ flutter doctor -v
[√] Flutter (Channel master, v1.13.7-pre.23, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.13.7-pre.23 at C:\Users\bronc\Documents\flutter\flutter_file
    • Framework revision fa1ebab88e (2 hours ago), 2020-01-03 15:20:48 -0800
    • Engine revision eb139936eb
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 2f57602411)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bronc\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Android\New folder\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\New folder
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```
Not sure what `Local module descriptor class for com.google.firebase.auth not found` means, as I have done nothing to my project except for upgrade flutter. Please let me know if more information is needed.

**Comment by rfitz123** [comment]
Having an identical issue to @GameSquatch. Any fix?

**Comment by gen4sp** [comment]
same issue
