### ISSUE TITLE
[firebase_database v0.3.1]: MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#914]
## Steps to Reproduce

```
dependencies:
  firebase_analytics: ^0.2.0
  firebase_auth: ^0.4.0
  google_sign_in: ^2.0.0
  firebase_database: ^0.3.1
  firebase_messaging: ^0.1.0
  firebase_core: ^0.0.2
  flutter_facebook_connect: ^0.0.3
```

Running below code 
```java
@override
  void initState() {
    super.initState();

    final FirebaseDatabase database = new FirebaseDatabase(app: app);

    _categoryRef = database.reference().child(Strings.categoryTablename);

    Future<DataSnapshot> categorySnap = database.reference().child(Strings.categoryTablename).once(); //exception thrown here
    categorySnap.then((DataSnapshot snapshot) {
        debugPrint('Connected to app database and read ${snapshot.value}');
      }
    });
  }
```

produces below error logs

## Logs

```
E/flutter ( 3705): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 3705): MissingPluginException(No implementation found for method Query#observe on channel plugins.flutter.io/firebase_database)
E/flutter ( 3705): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:153:7)
E/flutter ( 3705): <asynchronous suspension>
E/flutter ( 3705): #1      Query._observe.<anonymous closure> (package:firebase_database/src/query.dart:50:38)
E/flutter ( 3705): #2      _runGuarded (dart:async/stream_controller.dart:803)
E/flutter ( 3705): #3      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:217)
E/flutter ( 3705): #4      _ControllerStream._createSubscription (dart:async/stream_controller.dart:816)
E/flutter ( 3705): #5      _StreamImpl.listen (dart:async/stream_impl.dart:466)
E/flutter ( 3705): #6      _NavigatorState.initState (/data/user/0/com.category/cache/categoryUDBOKZ/category/lib/routes/drawer/navigator_view.dart:59:50)
E/flutter ( 3705): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3655:14)
E/flutter ( 3705): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
E/flutter ( 3705): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
E/flutter ( 3705): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
E/flutter ( 3705): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3524:5)
E/flutter ( 3705): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
E/flutter ( 3705): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
E/flutter ( 3705): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
E/flutter ( 3705): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3524:5)
E/flutter ( 3705): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
E/flutter ( 3705): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4532:14)
E/flutter ( 3705): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4532:14)
E/flutter ( 3705): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
E/flutter ( 3705): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
E/flutter ( 3705): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3524:5)
E/flutter ( 3705): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3662:22)
E/flutter ( 3705): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
E/flutter ( 3705): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3556:16)
E/flutter ( 3705): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3445:5)
E/flutter ( 3705): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3524:5)
E/flutter ( 3705): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3519:5)
E/flutter ( 3705): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2660:12)
E/flutter ( 3705): #42     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4532:14)
E/flutter ( 3705): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2857:14)
E/flutter ( 3705): #44     Element.updateChild (
```

## `flutter analyze`
```
hint • The value of the field '_user' isn't used at lib/routes/drawer/sbs_navigator_view.dart:34:22 • unused_field
  hint • The value of the field '_databaseError' isn't used at lib/routes/drawer/navigator_view.dart:36:17 • unused_field
  hint • The value of the field '_lastLifeCycleState' isn't used at lib/routes/sbs_onboarding_page_view.dart:23:21 • unused_field
  hint • The method '_signInWithEmailPassword' isn't used at lib/routes/sign_in.dart:115:24 • unused_element
  hint • Method doesn't override an inherited method at lib/routes/sign_in.dart:149:8 • override_on_non_overriding_method
  hint • The value of the field '_lastLifeCycleState' isn't used at lib/routes/sign_in_with_email.dart:54:21 • unused_field
  hint • Unused import at lib/utils/database_utils.dart:1:8 • unused_import
```

## Flutter Doctor
```
[✓] Flutter (on Mac OS X 10.13.2 17C88, locale en-GB, channel alpha)
    • Flutter at /Users/etimbuk/sdks/flutter
    • Framework revision 8f65fec5f5 (4 weeks ago), 2017-12-12 09:50:14 -0800
    • Engine revision edaecdc8b8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.d8ae797298c3a6cf8dc9f4558707bd2672224d3e

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/etimbuk/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.6)
    • Flutter plugin version 18.3
    • Dart plugin version 172.4343.25

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)
```

Please I will appreciate your ind assistance. thanks

**Comment by shimonster** [comment]
If anyone is looking for the solution, please refer to [https://github.com/flutter/flutter/issues/13971](url)
